### ISSUE TITLE
README File points to old URL

### ISSUE THREAD

**Issue by GieltjE** [upx/upx#1]
Just a small notification that the README file still contains the URL.

As a sidenote http://compression.ca/ appears to be severely outdated, maybe once a new release is made we should create some new statistics?

**Comment by markus-oberhumer** [comment]
The move to github is not fully finished yet, but yes, the docs badly need some overhaul.

**Comment by GieltjE** [comment]
!stale

**Comment by markus-oberhumer** [comment]
Some work done on devel4 branch. Please feel free to open a new issue and suggest improvements.
