### ISSUE TITLE
latest UCL release is broken with GCC 6.3.0

### ISSUE THREAD

**Issue by rofl0r** [upx/upx#101]
## What's the problem (or question)?
UCL is a component required to build UPX.
building it with GCC 6.3.0 fails.
```
checking whether your compiler passes the ACC conformance test...
../acc/acc_defs.h:97:59: error: variably modified '__acc_cta' at file scope
 #    define ACC_COMPILE_TIME_ASSERT_HEADER(e)  extern int __acc_cta[1-2*!(e)]; 
                                                           ^
ucl_init.c:73:33: note: in expansion of macro 'ACC_COMPILE_TIME_ASSERT_HEADER'  
 #define ACCCHK_ASSERT(expr)     ACC_COMPILE_TIME_ASSERT_HEADER(expr)
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../acc/acc_chk.ch:207:5: note: in expansion of macro 'ACCCHK_ASSERT'
     ACCCHK_ASSERT((1   << (8*SIZEOF_INT-1)) < 0)
     ^~~~~~~~~~~~~
../acc/acc_defs.h:97:59: error: variably modified '__acc_cta' at file scope
 #    define ACC_COMPILE_TIME_ASSERT_HEADER(e)  extern int __acc_cta[1-2*!(e)]; 
                                                           ^
ucl_init.c:73:33: note: in expansion of macro 'ACC_COMPILE_TIME_ASSERT_HEADER'  
 #define ACCCHK_ASSERT(expr)     ACC_COMPILE_TIME_ASSERT_HEADER(expr)
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## What should have happened?
It should have compiled without error.

## Do you have an idea for a solution?
fix the macros used in acc_chk.h

## How can we reproduce the issue?
1 compile ucl 1.03 tarball with GCC 6.3.0

## Please tell us details about your environment.
Sabotage Linux, x86_64, musl libc 1.1.16

**Comment by markus-oberhumer** [comment]
gcc is broken because it changed the language in 6.0. Use "CC=gcc -std=gnu89".

**Comment by sebastien-rosset** [comment]
Here are specific steps that work for me (gcc 9.3.0):

```bash
$ CC="gcc -std=gnu89" ./configure
$ make
```

Sometimes people would might try `CC="gcc" CFLAGS="-std=gnu89" ./configure` but that does not work in this particular case.

**Comment by rofl0r** [comment]
> Sometimes people would might try CC="gcc" CFLAGS="-std=gnu89" ./configure but that does not work in this particular case.

that's the default way of doing it, indeed. apparently the build system here discards user-provided CFLAGS.
