### ISSUE TITLE
UPX 3.93 fails to decompress file compressed with UPX 3.91

### ISSUE THREAD

**Issue by rofl0r** [upx/upx#102]
## What's the problem (or question)?
The challenge [easy_re from RCTF 2017](https://0x0.st/E1j.zip) cannot be uncompressed with UPX 3.93, but it works with 3.91 as provided on kali linux.

```
upx -d ~/contest/rctf/easy_re 
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.93        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 29th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: /home/rofl/contest/rctf/easy_re: Exception: compressed data violation

Unpacked 1 file: 0 ok, 1 error.

```

## What should have happened?
should have uncompressed it too.

## Do you have an idea for a solution?
no.

## How can we reproduce the issue?

1. try upx -d easy_re

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.93
* Host Operating System and version: sabotage linux
* Host CPU architecture: i386
* Target Operating System and version: i386
* Target CPU architecture: i386

**Comment by rofl0r** [comment]
update: the issue exists in 3.94, too.

**Comment by jreiser** [comment]
Fixed by d8f47e248af4d6673ea9d9d11ba5392f9534023d on devel branch.  upx-3.91 (--fileinfo version 13) did not compress easy_re (--fileinfo version 11).  The last compressor using version 11 was around 15 years ago.  Also note that easy_re has been hacked by overwriting the UPX copyright notice with spaces.

**Comment by markus-oberhumer** [comment]
We don't support hacked executables (this is acutally a copyright violation). Closing.

**Comment by rofl0r** [comment]
thanks for fixing!

> We don't support hacked executables (this is acutally a copyright violation).

well, i guess in that case you should sue the chinese "team rois" hacker group that made this contest binary for their CTF. i'm washing my hands in innocence.
