### ISSUE TITLE
build regression with UPX 3.94

### ISSUE THREAD

**Issue by rofl0r** [upx/upx#103]
## What's the problem (or question)?
crosscompiling UPX will silently pull in host headers, if UPX_UCLDIR environment variable is not set. this can lead to using a 32 bit compiler with 64 bit headers and vice versa, resulting in cryptic error messages from miniacc.h, such as
```
error: #error "unexpected configuration - check your compiler defines"
```
cryptic, because

1) BUILD_USE_DEPEND is by default 1, in which case the command line used to compile the .depends file is not echoed to stdout, not even when V=1 is passed to the make command, so its completely hidden what happens and

2) it's immensely hard to debug why `ULONG_MAX != ACC_0xffffffffL` in the forest of preprocessor macros in miniacc.h

## What should have happened?
if it now assumed that UPX_UCLDIR must be set, it would be better if an error was thrown, like "error: need to set UPX_UCLDIR", instead of silently adding -I/include to CXXFLAGS.

## Do you have an idea for a solution?

2 possible solutions.

1) if UPX_UCLDIR is not set, do not add any -I include switches. this is imo preferable, as it behaves like previously, where you could have UCL installed into your compilers default directories (for example /lib and /include) and it would automatically pick the headers up.

2) if UPX_UCLDIR is not set, throw an error.

## How can we reproduce the issue?

1. do not set UPX_UCLDIR
2. compile with make V=1 BUILD_USE_DEPEND=0
3. see how `-I/include` gets added to the compiler command line, and realize that this will pull in 64bit headers on a 64bit host when using a 32bit crosscompiler.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94
* Host Operating System and version: sabotage linux
* Host CPU architecture: x86_64
* Target Operating System and version: i386
* Target CPU architecture:i386

**Comment by markus-oberhumer** [comment]
Actually there is a check in src/Makefile for $(UPX_UCLDIR)/include/ucl/ucl.h .

So that's what you get when you have completely non-standard dirs like `/include` .

**Comment by rofl0r** [comment]
it's not ubuntu, so it's non-standard, so it's not supported, gotcha.

**Comment by markus-oberhumer** [comment]
https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

**Comment by rofl0r** [comment]
/usr is the result of very small harddrives in the 70s, so you had to split your FS into 2 trees.
it was a mistake, and it's about time to get rid of it; but the [freedesktop zealots like poettering & co see it differently](http://0pointer.de/blog/projects/the-usr-merge.html). that doesn't mean i have to agree with them, though.
