### ISSUE TITLE
upx-compressed PIE executable crashes on i386

### ISSUE THREAD

**Issue by roblub** [upx/upx#106]
## What's the problem (or question)?
Today I've discovered that compressing i386 mutt executable compressed with upx crashes while trying to run it (i.e. cp /usr/bin/mutt ./mutt; upx ./mutt; ./mutt). After a while I've discovered that this is because mutt is compiled with -fPIE flag.

## What should have happened?
It shouldn't have crashed :)

## Do you have an idea for a solution?
IMHO changes from commit d688a05ac785 should be applied to PackLinuxElf32::canPack().
See the attached [Check-DT_REL-i386.patch.txt](https://github.com/upx/upx/files/1034162/Check-DT_REL-i386.patch.txt) that does it. This seems to fix the issue with upx-3.91 and upx-3.93,
however with upx-3.94 the program still crashes even with this patch for some reason

## How can we reproduce the issue?
I am attaching two files ([mutt-1.6.1-1.zip](https://github.com/upx/upx/files/1034164/mutt-1.6.1-1.zip), [mutt-1.6.1-2.zip](https://github.com/upx/upx/files/1034165/mutt-1.6.1-2.zip)) taken from i386 Debian packages of mutt (downloaded from http://snapshot.debian.org/binary/mutt/). 
 - mutt-1.6.1-1 is not a PIE, and it runs correctly after compressing it with upx
 - mutt-1.6.1-2 is a PIE and it crashes after compressing it with upx:
```
robert@vox:/tmp$ cp mutt-1.6.1-2 mutt-1.6.1-2.upx; upx ./mutt-1.6.1-2.upx 
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2013
UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1327220 ->    604932   45.58%  linux/elf386   mutt-1.6.1-2.upx              

Packed 1 file.
robert@vox:/tmp$ ./mutt-1.6.1-2.upx 
Segmentation fault (core dumped)
```

## Please tell us details about your environment.
* UPX version used: 3.91, 3.93, 3.94
* Host Operating System and version: Linux vox 4.9.0-3-amd64 #1 SMP Debian 4.9.25-1 (2017-05-02) x86_64 GNU/Linux
* Host CPU architecture: amd64
* Target Operating System and version: as above
* Target CPU architecture: i386

**Comment by roblub** [comment]
I've just played with ``git bisect`` and found out that the reason why [the patch from the previous comment](https://github.com/upx/upx/files/1034162/Check-DT_REL-i386.patch.txt) does not help for upx-3.94 is commit 5da6a27e6bad.

**Comment by jreiser** [comment]
https://github.com/upx/upx/commit/a51330cf074cd5c826dc823e7a1375d316f27293 handles the compression side.  Major changes to the execution stub for -pie are coming soon.

**Comment by roblub** [comment]
Hi,

Thank you, however it looks like in your commit you replaced
```
unsigned const symnum = get_te64(&rela->r_info) >> 32;
```
with
```
 unsigned const symnum = get_te32(&rela->r_info) >> 8;
```
in 64-bit version of the function. Is it OK?

**Comment by jreiser** [comment]
@roblub Thank you for catching that flub.

**Comment by jreiser** [comment]
@roblub Commit 8f572e5fe674202da33542fca7e0588722adb99e at tip of 'devel' branch works for me.

**Comment by jreiser** [comment]
Closing because it seems to be fixed: works for me, and no reply in a long time (3 months).  If the same issue still happens, then please enter a comment and we can re-open this issue.

**Comment by quequotion** [comment]
This might not be quite the same issue, as it is on a 64-bit system, but I also found  [upx compressed application/x-pie-executable](https://aur.archlinux.org/packages/makepkg-optimize/#comment-674947) programs crash.

Perhaps a similar thing that was done for i386 needs to be done for x86_64 (assuming it worked)?
