### ISSUE TITLE
UPX License Violation?

### ISSUE THREAD

**Issue by ObiWanYouKnowMe** [upx/upx#108]
## What's the problem (or question)?
Steve Gibson, world renowned security expert (in his mind), has been developing a [simple HMAC algorithm](https://www.grc.com/sqrl/sqrl.htm) called "SQRL" for four years.

Along with all of the other executables on [his site](https://www.grc.com/freepopular.htm), he is distributing SQRL development mystery exes such as [sqrl-0.0.6368.65.exe](https://www.grc.com/dev/sqrl/sqrl-0.0.6368.65.exe) packed with UPX **with a modified header/stub to prevent unpacking**. If that link no longer works, check the latest EXEs in [the dev directory](https://www.grc.com/dev/sqrl/).

He does this to hide his code and dependencies, because he's likely packing in other open source libraries and not disclosing them. Steve never, ever shares his code, but he claims it's all clean ASM. **321KB of packed ASM** in this case, with a QR code printer and who knows what else, that he supposedly wrote in ASM and it's 321KB **packed**.

In an effort to determine what open source libraries he is using in violation of their licenses and to audit the code, I attempted to unpack the SQRL exe. It is definitely using UPX with a modified header.

Output from `upx -d ..\..\sqrl-0.0.6368.65.exe`:

    file is modified/hacked/protected; take care!!!```

Output from PE Explorer UPX Unpacker plug-in:

    UPX: File compressed with UPX
    UPX: UPX version: 12
    UPX: Crafty modification to UPX header detected!
    ...
    UPX: Failed to recover the PE file header!

Obviously, he's modifying the header to prevent decompression, because people could see the libraries he's bundling, and they could see his code as well in disassembler.

The license has [seemingly always](https://web-beta.archive.org/web/20000408181541/http://wildsau.idv.uni-linz.ac.at:80/mfx/upx.html) prevented header modification since 1.0, but he's doing it anyway. The license states:

> We grant you special permission to freely use and distribute all UPX compressed programs. But any modification of the UPX stub (such as, but not limited to, **removing our copyright string** or **making your program non-decompressible**) will immediately revoke your right to use and distribute a UPX compressed program.

When confronted with this, Steve Gibson claims that he was [extended a commercial license](https://www.grc.com/x/news.exe?cmd=article&group=grc.sqrl&item=15139&utag=) ([archive link](https://archive.fo/x66K5)) of UPX in 2001 that allows him to perform header modification to prevent decompression. Steve says:

> "They once also offered in a paid-for commercial version that offered additional features, including the ability to obtain additional compression and the option to thwart command-line decompression. And that appears to be the version I'm using, since its last copyright year is 2001."

Furthermore, he [later claims again](https://www.grc.com/x/news.exe?cmd=article&group=grc.sqrl&item=15150&utag=) ([archive link](https://archive.fo/0Sqcw)) that:

> "I am quite certain that my use of UPX is congruent with what its authors authorized at the time I acquired it from them and I have no need to prove that to anyone.
> If Laszlo Molnar, or any of the other UPX copyright holders, wish to contact me through official GRC channels, rather than by borrowing Shania's newsreader, I will be more than pleased to settle any concerns they might rightfully have."

What hasn't been discussed above is that `strings` run on the packed EXE also returns none of the copyright string, so it appears he's removing this as well. However, the more nefarious violation is the fact that you can't inspect the code or the libraries that he's packing in.

Steve is publicly inviting UPX copyright holders to enforce their license against him. Please let me know if you need any more information.

## What should have happened?
Steve Gibson should have used the real `upx.exe` that would allow `upx.exe -d`

## Do you have an idea for a solution?
Compel Steve Gibson to adhere to the license.

## How can we reproduce the issue?
1. Run `upx.exe -d` on [his exe](https://www.grc.com/dev/sqrl/sqrl-0.0.6368.65.exe) or any recent exe in [his dev directory](https://www.grc.com/dev/sqrl/).

## Please tell us details about your environment.
* UPX version used (`upx --version`): Unknown
* Host Operating System and version: Windows
* Host CPU architecture: x86
* Target Operating System and version: Windows Any
* Target CPU architecture: x86

**Comment by ml1050** [comment]
Nice! We never made a commercial version of UPX. Especially not without decompression support.

**Comment by ObiWanYouKnowMe** [comment]
@ml1050 He's been doing this with all his EXEs since the early 2000s. Can I do anything to help facilitate a resolution? Or will you be contacting him directly?

My links go to a web viewer for his private NNTP *(what year is this?)* but you can connect to his NNTP server to participate in discussions.

**Comment by ml1050** [comment]
I'm afraid we do not have the resources to do anything about this :-(

**Comment by cyian-1756** [comment]
> I'm afraid we do not have the resources to do anything about this :-(

You could try shaming him/making his infringement widely known

**Comment by thedjnK** [comment]
@ObiWanYouKnowMe If it's provable then put it on his wikipedia page: https://en.wikipedia.org/wiki/Steve_Gibson_(computer_programmer)

**Comment by ObiWanYouKnowMe** [comment]
Do you think you could assist in unpacking it? It does run correctly under Win32. He claims to write everything in ASM, but he has lots of code he can't account for, like the QR printer. I'd be interested to see the actual statically linked code.

**Comment by ObiWanYouKnowMe** [comment]
Steve Gibson, [better known](http://seclists.org/nmap-announce/2001/25) for media manipulation than technical wizardry, has now doubled down on his lies about UPX in his [private news group](https://www.grc.com/x/news.exe?cmd=article&group=grc.sqrl&item=15210&utag=) ([archive link](https://archive.fo/u9F7M)).

He begins with a lie that 20 years ago, @ml1050 sold him UPX with a commercial license that prevented decompression on a web page he can see in "his mind's eye."

> As I have said, I have a clear memory of having once purchased a  flavor of UPX that offered additional features & removed command line decompression. I can still see the web page in my mind's eye despite it being more than 20 years ago. I've looked around, but it was so long ago that any receipt I might have, or the original download package with its license, are several workstation generation past, and are no longer online.

He claims now that he's been exposed, he will switch packers:

> But this controversy has caused me to revisit my choice in EXE compressors.

He continues by throwing shade at UPX directly:

> But the nicest news is that it's also **better than UPX**. It's **faster to both compress & decompress, and it compresses more**. :)
> Whereas the most recently published v0.0.6368.65 was 328,176 bytes, this alternative compressor just squeezed the working version I have down to 283,648 bytes... and it appears to work perfectly.

So, it appears Steve Gibson's mystery EXEs will now come packed with a mystery packer, all because he doesn't want anyone to see what statically linked libraries he's using.

@ml1050, do you think you'll be able to assist in unpacking the original EXE linked? I have it downloaded in case he replace(s/d) it.

**Comment by ml1050** [comment]
It was very easy to unpack that file. Here is how you can do it:
Use a hex editor to change the name of the first PE header to UPX (at offset 0x1d8). Then replace the 4 zero bytes at offset 0x3e0 to UPX!. That's all, now you can use "upx -d" to uncompress the file.

Have fun.

**Comment by ObiWanYouKnowMe** [comment]
Thanks @ml1050. For anyone who's interested in looking at it, here's the [unpacked exe](https://www.dropbox.com/s/cazc1ywo5ducohj/sqrl-0.0.6368.65.exe?dl=1). Here's the original, [packed, modified header exe](https://www.dropbox.com/s/3i5oiyl4a7cc5ik/sqrl-0.0.6368.65.orig.exe?dl=1).

The only library I can see for sure (so far) that he's included illegally is [libsodium](https://github.com/jedisct1/libsodium). Are you interested in this at all @jedisct1?

The libsodium library ISC License states:

>  * Permission to use, copy, modify, and/or distribute this software for any
> * purpose with or without fee is hereby granted, provided that the above
> * copyright notice and this permission notice appear in all copies.

Obviously the packed, modified EXE doesn't have this string anywhere. The unpacked EXE doesn't either. He's redistributing statically linked libsodium code without acknowledgement.

If you're interested where it's used in the unpacked EXE, you can find references to it at address `0x004B45E7` and `0x004B4610`.

    SSZ004B45E7_Initializing_Sodium_Crypto_Libra:
     		db	'Initializing Sodium Crypto Library: %s',0Dh,0Ah,0
    SSZ004B4610_Sodium_library_random_source____:
     		db	'Sodium library random source: ',27h,'%s',27h,0Dh,0Ah,0

In case he tries to repudiate his EXE, the original, modified packed EXE I linked above is digitally signed by him (GRC). You can follow @ml1050's instructions to get to my unpacked EXE exactly:

> Use a hex editor to change the name of the first PE section header to UPX (at offset 0x1d8). Then replace the 4 zero bytes at offset 0x3e0 to UPX!. That's all, now you can use "upx -d" to uncompress the file.

**Comment by wbsdty331** [comment]
try to unpack manually?

**Comment by ml1050** [comment]
It was easy to uncompress the file, because the packheader info was intact. If UPX could automatically locate the header in recovery mode without the magic UPX! value, then people would simply zero that header too. Even in that case it could be possible to uncompress the file, but I do not think this should be a use case for us.

**Comment by DamonBlais** [comment]
Good to know, will avoid his programs in the future. It's a shame to see someone in the IT industry, especially security, so vehemently dishonest as to keep this charade going on like this. To this date, I have not seen him admit his wrongful position.

This thread now also shows up to searches of removing the UPX header, which is great news.
