### ISSUE TITLE
Datatype of overlay_offset in p_mac.cpp

### ISSUE THREAD

**Issue by zongyuwu** [upx/upx#109]
## What's the problem (or question)?

`overlay_offset` will be negative when perform the first non-zero word scanning backwards from __LINKEDIT.fileoffin in p_mac.cpp:1800. However, the `overlay_offset` is defined as `unsigned` in p_unix.h:85. That will cause overflow when calling seek and mem_size_assert in file.c

## What should have happened?

Calling seek and mem_size_assert in file.c with correct overlay_offset.

## How can we reproduce the issue?

1. 
2. 
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): UPX git-d31947+
* Host Operating System and version: Ubuntu 14.04.1
* Host CPU architecture: x86_64
* Target Operating System and version: Ubuntu 14.04.1
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
@zongyuwu Please attach a test case file wich exhibits the problem, or give a URL where the test case can be downloaded.

**Comment by zongyuwu** [comment]
@jreiser My sample is a malware so is it okay to share it here?

**Comment by jreiser** [comment]
@zongyuwu Thank you for the warning, but I need to see a test case to investigate.  Put "malware" as part of the name of the attachment or the filename part of the URL.

**Comment by zongyuwu** [comment]
@jreiser Thanks, I've mailed the sample to you.

**Comment by jreiser** [comment]
Fixed in https://github.com/upx/upx/commit/650df95b7240c864479844c87a040e453120c328 on 'devel' branch.
