### ISSUE TITLE
Erro / Help

### ISSUE THREAD

**Issue by ednorjr** [upx/upx#112]
## What's the problem (or question)?
When trying to use upx in Windows 10 x64, via command line:
C:\upx394w>upx --best myproject.exe

I receive the following error message:
upx: invalid string 'C:\Arquivos' in environment variable 'UPX'

Can someone help me?
Sorry if I'm in the wrong section.

## What should have happened?
error message:
upx: invalid string 'C:\Arquivos' in environment variable 'UPX'

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):upx 3.94
NRV data compression library 0.84; UCL data compression library 1.03; zlib data compression library 1.2.3; LZMA SDK version 4.43* 
Host Operating System and version: Windows 10 Pro x64
* Host CPU architecture: Intel i5
* Target Operating System and version: Windows
* Target CPU architecture: do not understand

**Comment by jreiser** [comment]
What are all the variables in your current environment?  Run "SET" in a CMD window, then copy+paste the output here.

**Comment by ednorjr** [comment]
**ERRO:**
UPX=C:\Arquivos de programas\upx391w\upx.exe

Your question has helped me solve the problem.
Thank you very much.

**Comment by ednorjr** [comment]
**ERRO:**
UPX=C:\Arquivos de programas\upx391w\upx.exe

Your question has helped me solve the problem.
Thank you very much.

**Comment by ednorjr** [comment]
**ERRO:**
UPX=C:\Arquivos de programas\upx391w\upx.exe

Your question has helped me solve the problem.
Thank you very much.

**Comment by ednorjr** [comment]
Problem solved.
