### ISSUE TITLE
ImportError: DLL load failed: Invalid access to memory location, 

### ISSUE THREAD

**Issue by ReddyKilowatt** [upx/upx#113]
## What's the problem (or question)?

When running single file exe created with Pyinstaller + upx, for a 1line Python 2.7.13 application,
the following error is displayed: **"ImportError: DLL load failed: Invalid access to memory location"**
Removing the upx compression causes the runtime exception to go away.

Ideally, the program should work the same whether compressed or not compressed

## What should have happened?

My application should have executed without this error message being displayed.

## Do you have an idea for a solution?

It only happens on Python 2.7.13 
When I created the exe using Python 3.5, the error does not occur.

## How can we reproduce the issue?

1. Create a 32-bit Python 2.7.13 (32-Bit) environment. I have not tried a 64-Bit Python environment.
I'm using Python 2.7.13 |Anaconda 4.4.0 (32-bit)| (default, May 11 2017, 14:07:41) [MSC v.1500 32 bit (Intel)]
2. Add this 1 line to an empty Python file: import SimpleXMLRPCServer
3. pyinstaller -F appname
4. cd dist
run the exe version of the application

This is very repeatable on my system. It happens 10 out of 10 times.
The following gist has all of the necessary files, including a traceback and some logs
https://gist.github.com/a9b4f476c3c50c4e9de92b399d0286aa.git

## Please tell us details about your environment.

* UPX version used (`upx --version`):
3.94

* Host Operating System and version:
Windows 7 Pro, 64 -Bit

* Host CPU architecture:
Intel i7-4600U 2.1-2,7GHZ

* Target Operating System and version:
Windows 7 Pro, 64 -Bit

* Target CPU architecture:
Any, but the issue was seend on the same development system
Intel i7-4600U 2.1-2,7GHZ

**Comment by markus-oberhumer** [comment]
Could you try if upx 3.91 works ?

**Comment by ReddyKilowatt** [comment]
I believe I started with 3.91, then updated to 3.94, while going through
the Pyinstaller debug steps.

**Comment by ReddyKilowatt** [comment]
Hi Marcus,

Were you able to duplicate this issue?
Do you need any more information from me?

**Comment by nusijsteel** [comment]
Hi All, 

I am also having this problem. 

Could not load 'nvcuda.dll'. The GPU version of TensorFlow requires that
this DLL be installed in a directory that is named in your %PATH%
environment variable. Typically it is installed in 'C:\Windows\System32'.
If it is not present, ensure that you have a CUDA-capable GPU with the
correct driver installed.

I have already put the nvcuda.dll into the %PATH% specified for my python installation.
Hope someone could help. Thanks.

**Comment by sithis993** [comment]
I'm also hitting this problem with my project, which uses wxPython and is compiled using pyinstaller 3.4. It executes perfectly fine without UPX, but as soon as I use UPX I get the same error

**Comment by splitbrain** [comment]
For what it's worth, I have the same problem when I try to compress the mbstring extension of the 32 bit version of PHP. The DLL can be found in https://windows.php.net/downloads/releases/php-7.3.16-Win32-VC15-x86.zip Using UPX 3.96
