### ISSUE TITLE
Blue Screen of Death on Windows 10 Creators Update

### ISSUE THREAD

**Issue by freesemt** [upx/upx#114]
## What's the problem (or question)?

The following DLLs compressed by UPX cause BSoD - Blue Screen of Death - errors on Windows 10 Creators Update ( around OS build 15063.483). (Load time errors may be caused on other versions of Windows)
concrt140.dll
mfc140u.dll
msvcp140.dll
ucrtbase.dll
vcamp140.dll
vccorlib140.dll
vcomp140.dll
vcruntime140.dll
## What should have happened?

No such errors should happen.
## Do you have an idea for a solution?

I have no idea.
## How can we reproduce the issue?

1. UPX vcruntime140.dll
2. Place the mouse cursor over the compressed DLL in Explorer window to show their properties in a balloon display.
3. BSoD - Blue Screen of Death - will result in a few seconds.

BSoDs do not result on earlier versions of Windows before "Creators Uptdate", while load time errors should be caused instead.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
3.92 - 3.94
* Host Operating System and version:
Windows 10 Pro version 1703 (Creators Update or later)
(Load time errors may have been caused on earlier versions of Windows)
* Host CPU architecture:
Intel i7-5500U 2.40GHz
* Target Operating System and version:
Windows 10 Pro version 1703
(Load time errors may have been caused on earlier versions of Windows)
* Target CPU architecture:
Intel i7-5500U 2.40GHz

**Comment by feesemt** [comment]
This bug seems to have existed in earlier versions for Visual Studio 2015 related DLLs.
See https://github.com/pyinstaller/pyinstaller/issues/1565.
So, I suspect BSoD is caused by the same bug.

**Comment by markus-oberhumer** [comment]
Could you try if upx 3.91 works ?

**Comment by feesemt** [comment]
upx 3.91 causes the same error.

FYI, loading by the following Python script causes the error.
(BSoD on Creators Update, and , perhaps, a load error on earlier versions )

import ctypes
hllDll = ctypes.WinDLL ("d:\\temp\\vcruntime140.dll")

**Comment by AStrunk** [comment]
Just had the same problem. UPX version 3.94.

**Comment by Kotauskas** [comment]
On my Win 10 Creators Update no BSoD - just a Python app compiled with Pyinstaller is not working... Fixed that by replacing it with an uncompressed vcruntime140.dll.

**Comment by feesemt** [comment]
I tried to reproduce BSoD, but failed. After opening this issue on 1 Aug, OS build number seems to have proceeded from 15063.483 to 15063.674 according to my Windows Update history. So, I suspect they (Microsoft) fixed  BSoD sometime during this period. However, the load error still remains.
