### ISSUE TITLE
release for mac OS

### ISSUE THREAD

**Issue by roccomuso** [upx/upx#115]
## What's the problem (or question)?
Why the release page doesn't have a build for mac OS?

## Do you have an idea for a solution?
Put also the compiled version for mac.

## Please tell us details about your environment.

I'm looking for a compiled version of `upx`.

**Comment by markus-oberhumer** [comment]
Did you try `brew install upx` ?

**Comment by roccomuso** [comment]
I don't have Mac. I'm just looking for the executable to embed it in a lib.

**Comment by markus-oberhumer** [comment]
Well, then just download the file manually from the `brew` archive. Closing.

**Comment by webdizi** [comment]
What if me need a NON-latest version?
