### ISSUE TITLE
after compression, arm so file can't be loaded

### ISSUE THREAD

**Issue by pcheng74** [upx/upx#116]
## What's the problem (or question)?

I am using upx 3.94 version to compress the arm 32-bit so file, and after compression, this file can't be loaded. It will return the following error:
pi@raspberrypi:~ $ ./sample
./sample: error while loading shared libraries: libaes.so: cannot open shared object file: No such file or directory.

## How can we reproduce the issue?

1. Compress libaes.so
2. run sample
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94
* Host Operating System and version: Win 10 VMWare
* Host CPU architecture: x64
* Target Operating System and version: Raspberry Pi 3 (arm embedded Linux)
* Target CPU architecture: ARM Cortex-A53 1.2GHZ
[sample.zip](https://github.com/upx/upx/files/1236985/sample.zip)

**Comment by jreiser** [comment]
Please give more information so that anyone can reproduce the problem that you see.  Which embedded ARM Linux are you using, and which version?  Which software package contains libaes.so?  What is the full rooted pathname of the original libaes.so? What does "ls -l" say for the original libaes.so as input to upx, and for the output of upx after compression?  What is the output from "ldd sample"?  What is the expansion of the shell variable LD_LIBRARY_PATH?

**Comment by jreiser** [comment]
@pcheng74 Please respond to the questions in the previous comment, which you might not have seen yet because I forgot to refer explicitly to your loginID.

**Comment by pcheng74** [comment]
@jreiser 

embedded ARM Linux: Linux raspberrypi 4.4.11-v7+ #888 SMP Mon May 23 20:10:33 BST 2016 armv7l GNU/Linux.

I have attached the sample.zip for you, it includes the original libaes. so, and sample to call it.

Please see the following output as you suggested.
pi@raspberrypi:~ $ls -l libaes.so
-rwxrwxrwx 1 pi pi 8412 Aug 20 06:48 libaes.so

pi@raspberrypi:~ $ ldd sample
        linux-vdso.so.1 (0x7effc000)
        /usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76fe3000)
        libaes.so => not found
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76e90000)
        /lib/ld-linux-armhf.so.3 (0x54b75000)
pi@raspberrypi:~ $ echo $LD_LIBRARY_PATH
It is empty. sample will load libaes.so from the current folder.

Thanks,
Peter

**Comment by jreiser** [comment]
@pcheng74 It works for me when I run on Fedora 26, using either upx-3.94 or upx-tip.
```
$ uname -a
Linux f26xfcepi.local 4.12.5-300.fc26.armv7hl #1 SMP Mon Aug 7 17:00:28 UTC 2017 armv7l armv7l armv7l GNU/Linux
$ rpm -qf /lib/ld-linux-armhf.so.3   ## the package for RTLD runtime linker
glibc-2.25-7.fc26.armv7hl
$ mv libaes.so libaes.so.orig
$ upx-3.94-src/src/upx.out -f -o libaes.so.upx-3.94 libaes.so.orig
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.94        Markus Oberhumer, Laszlo Molnar & John Reiser   May 12th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
     13215 ->      8292   62.75%    linux/arm    libaes.so.upx-3.94            

Packed 1 file.
$ cp libaes.so.upx-3.94 libaes.so
$ ls -l
-rwxrwxr-x. 1 jreiser jreiser  8292 Aug 22 08:57 libaes.so
-rwxrwxr-x. 1 jreiser jreiser 13215 Aug 22 08:26 libaes.so.orig
-rwxrwxr-x. 1 jreiser jreiser  8292 Aug 22 09:06 libaes.so.upx-3.94
-rwxrwxr-x. 1 jreiser jreiser  8653 Aug 22 08:26 sample
$ sum libaes.so*
30702     9 libaes.so
03341    13 libaes.so.orig
30702     9 libaes.so.upx-3.94
$ cmp libaes.so libaes.so.upx-3.94
  ## empty output: files are identical
$ readelf --all ./sample  |  grep RPATH
 0x0000000f (RPATH)                      Library rpath: [.:/home/pcheng/so_sample]   ## note '.' as first path
$ ldd ./sample
	libaes.so => ./libaes.so (0xb6fd2000)   ## found in current directory '.'
	libc.so.6 => /lib/libc.so.6 (0xb6e2f000)
	/lib/ld-linux-armhf.so.3 (0xb6fac000)
$ ./sample   ## actual output; equals expected output
key_bit 128: 
	input  :  01 23 45 67 89 ab cd ef fe dc ba 98 76 54 32 10 
	encrypt:  ff 0b 84 4a 08 53 bf 7c 69 34 ab 43 64 14 8f b9 
	decrypt:  01 23 45 67 89 ab cd ef fe dc ba 98 76 54 32 10 
key_bit 192: 
	input  :  01 23 45 67 89 ab cd ef fe dc ba 98 76 54 32 10 
	encrypt:  66 4e 00 1d 2f cb 6c 48 c5 a7 f1 ac f3 0e 87 a8 
	decrypt:  01 23 45 67 89 ab cd ef fe dc ba 98 76 54 32 10 
key_bit 256: 
	input  :  01 23 45 67 89 ab cd ef fe dc ba 98 76 54 32 10 
	encrypt:  fb 6e ee fe bf ee 19 d8 ce 8b 99 42 73 b5 f0 02 
	decrypt:  01 23 45 67 89 ab cd ef fe dc ba 98 76 54 32 10 
$ 
```

**Comment by pcheng74** [comment]
@jreiser, it is very strange, I am using windows version upx 3.94 for compressing, is there any difference.
and I also find the compressed libaes.so checksum is different with your side. Please see the following steps in my side.

E:\arm_linux\exe sample\so\upx394w>upx -f libaes.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.94w       Markus Oberhumer, Laszlo Molnar & John Reiser   May 12th 2017
        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
     13215 ->      8292   62.75%    linux/arm    libaes.so
Packed 1 file.

and then I copied it to arm Linux board.

pi@raspberrypi:~/so_sample $ sum *
03341    13 libaes-org.so
13345     9 libaes.so
46147     9 sample

pi@raspberrypi:~/so_sample $ readelf -all ./sample | grep RPATH
 0x0000000f (RPATH)                      Library rpath: [.:/home/pcheng/so_sample]

pi@raspberrypi:~/so_sample $ ldd ./sample
        linux-vdso.so.1 (0x7eff8000)
        /usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76eed000)
        libaes.so => not found
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76d9a000)
        /lib/ld-linux-armhf.so.3 (0x54b84000)

pi@raspberrypi:~/so_sample $ ./sample
./sample: error while loading shared libraries: libaes.so: cannot open shared object file: No such file or directory

[libaes.zip](https://github.com/upx/upx/files/1245588/libaes.zip)

I attached the compressed libaes.so for your testing. 

And can you share upx.out  and compressed libaes.so from your side with me, I can test them in my side again.

Appreciate your effort !

Thanks,
Peter

**Comment by jreiser** [comment]
@pcheng74 I see two problems.  1) The output of compressing libaes.so is not the same for the Win32 versus AMD64-Linux versions of UPX-3.94.  I have uploaded  [libaes-upx394.so.gz](https://github.com/upx/upx/files/1247602/libaes-upx394.so.gz) produced by the AMD64-Linux version of UPX-3.94 which can be downloaded starting at upx.github.io.  2) Ubuntu's  runtime linker+loader /lib/ld-linux-armhf.so.3 does not accept some ELF .so files built by UPX as legitimate shared libraries.  This is likely a very similar problem to Android, where they have introduced a mis-feature by having the runtime linker look at some of the "linking view" fields in the ELF header.  This is a bug; the runtime linker should look only at the "executable view" fields in the ELF header.  For instance, any Section header info (.e_shoff, .e_shentsize, .e_shnum, .e_shstrndx) matters only for [re-]building a new executable by the static linker /bin/ld.  Those fields have no connection at all with anything at runtime, which uses only the "execution view" fields relating to Program headers.

Still investigating...

**Comment by pcheng74** [comment]
@jreiser , I downloaded libaes-upx394.so.gz, and run it in my side, unfortunately it can't work also in my side.

I tried other executable files (not so), compressed by upx394w. and compressed executable files can work well in arm embedded Linux board.  Are there any differences between so and normal exe files？

Please see the following info:
------------------------------------------------------------------------------------------------
pi@raspberrypi:~/so_sample $ sum libaes*
03341    13 libaes-plain.so
30702     9 libaes.so
pi@raspberrypi:~/so_sample $ ./sample
./sample: error while loading shared libraries: libaes.so: cannot open shared object file: No such file or directory

pi@raspberrypi:~/so_sample $ ls -l
-rwxrwxrwx 1 pi pi 13215 Aug 20 06:48 libaes-plain.so
-rwxrwxrwx 1 pi pi  8292 Aug 20 21:48 libaes.so
-rwxrwxrwx 1 pi pi  8653 Aug 20 06:08 sample

------------------------------------------------------------------------------------------------

Thanks,
Peter

**Comment by jreiser** [comment]
https://bugs.launchpad.net/bugs/1712938
It's a bug in a check that Ubuntu added.  Workaround for UPX is in progress.

**Comment by jreiser** [comment]
The size difference [item **1)** of about a day ago] is caused by the official releases using NRV code for deflating, while development uses UCL which is just slightly less good.

**Comment by pcheng74** [comment]
@jreiser,


I used the last code you committed (f4947cc) ,  it still can't work.
please see the following so info.

pi@raspberrypi:~/so_sample $ readelf -a libaes.so
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x5a0
  Start of program headers:          52 (bytes into file)
  Start of section headers:          0 (bytes into file)
  Flags:                             0x5000402, has entry point, Version5 EABI, hard-float ABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         6
  Size of section headers:           40 (bytes)
  Number of section headers:         0
  Section header string table index: 0

There are no sections in this file.

There are no sections to group in this file.

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x000000 0x00000000 0x00000000 0x013fc 0x013fc R E 0x8000
  LOAD           0x001f0c 0x00009f0c 0x00009f0c 0x00134 0x00138 RW  0x8000
  DYNAMIC        0x001f18 0x00009f18 0x00009f18 0x000e8 0x000e8 RW  0x4
  NOTE           0x0000f4 0x000000f4 0x000000f4 0x00024 0x00024 R   0x4
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x10
  GNU_RELRO      0x001f0c 0x00009f0c 0x00009f0c 0x000f4 0x000f4 R   0x1

Dynamic section at offset 0x1f18 contains 25 entries:
  Tag        Type                         Name/Value
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
 0x00000001 (NEEDED)                     Shared library: [ld-linux-armhf.so.3]
 0x0000000c (INIT)                       0x1021
 0x0000000d (FINI)                       0x121c
 0x00000019 (INIT_ARRAY)                 0x9f0c
 0x0000001b (INIT_ARRAYSZ)               4 (bytes)
 0x0000001a (FINI_ARRAY)                 0x9f10
 0x0000001c (FINI_ARRAYSZ)               4 (bytes)
 0x6ffffef5 (GNU_HASH)                   0x118
 0x00000005 (STRTAB)                     0x304
 0x00000006 (SYMTAB)                     0x174
 0x0000000a (STRSZ)                      325 (bytes)
 0x0000000b (SYMENT)                     16 (bytes)
 0x00000003 (PLTGOT)                     0xa000
 0x00000002 (PLTRELSZ)                   48 (bytes)
 0x00000014 (PLTREL)                     REL
 0x00000017 (JMPREL)                     0x504
 0x00000011 (REL)                        0x4bc
 0x00000012 (RELSZ)                      72 (bytes)
 0x00000013 (RELENT)                     8 (bytes)
 0x6ffffffe (VERNEED)                    0x47c
 0x6fffffff (VERNEEDNUM)                 2
 0x6ffffff0 (VERSYM)                     0x44a
 0x6ffffffa (RELCOUNT)                   3
 0x00000000 (NULL)                       0x0

There are no relocations in this file.

Dynamic symbol information is not available for displaying symbols.

Histogram for `.gnu.hash' bucket list length (total of 3 buckets):
 Length  Number     % of total  Coverage
      0  0          (  0.0%)
      1  0          (  0.0%)      0.0%
      2  0          (  0.0%)      0.0%
      3  0          (  0.0%)      0.0%
      4  3          (100.0%)    100.0%

No version information found in this file.

Displaying notes found at file offset 0x000000f4 with length 0x00000024:
  Owner                 Data size       Description
  GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: ac6ea6fe7322fa24472e5cce18f5ea1b24f5863d

**Comment by jreiser** [comment]
@pcheng74 Are you sure?  Here's what I get.  Notice **Number of section headers:         4** and **ARM_ATTRIBUTES**
```
$ readelf --all libaes-ATTR.so
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x5a0
  Start of program headers:          52 (bytes into file)
  Start of section headers:          8256 (bytes into file)
  Flags:                             0x5000402, Version5 EABI, hard-float ABI, <unknown>
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         6
  Size of section headers:           40 (bytes)
  Number of section headers:         4
  Section header string table index: 0

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0] <no-name>         NULL            00000000 000000 000000 00      0   0  0
  [ 1] <no-name>         STRTAB          00000304 000304 000145 00   A  0   0  1
  [ 2] <no-name>         DYNAMIC         00009f18 001f18 0000e8 08  WA  1   0  4
  [ 3] <no-name>         ARM_ATTRIBUTES  00000000 0020e0 000033 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings)
  I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)

There are no section groups in this file.

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x000000 0x00000000 0x00000000 0x013fc 0x013fc R E 0x8000
  LOAD           0x001f0c 0x00009f0c 0x00009f0c 0x00134 0x00138 RW  0x8000
  DYNAMIC        0x001f18 0x00009f18 0x00009f18 0x000e8 0x000e8 RW  0x4
readelf: Error: no .dynamic section in the dynamic segment
  NOTE           0x0000f4 0x000000f4 0x000000f4 0x00024 0x00024 R   0x4
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x10
  GNU_RELRO      0x001f0c 0x00009f0c 0x00009f0c 0x000f4 0x000f4 R   0x1

Dynamic section at offset 0x1f18 contains 25 entries:
  Tag        Type                         Name/Value
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
 0x00000001 (NEEDED)                     Shared library: [ld-linux-armhf.so.3]
 0x0000000c (INIT)                       0x1021
 0x0000000d (FINI)                       0x121c
 0x00000019 (INIT_ARRAY)                 0x9f0c
 0x0000001b (INIT_ARRAYSZ)               4 (bytes)
 0x0000001a (FINI_ARRAY)                 0x9f10
 0x0000001c (FINI_ARRAYSZ)               4 (bytes)
 0x6ffffef5 (GNU_HASH)                   0x118
 0x00000005 (STRTAB)                     0x304
 0x00000006 (SYMTAB)                     0x174
 0x0000000a (STRSZ)                      325 (bytes)
 0x0000000b (SYMENT)                     16 (bytes)
 0x00000003 (PLTGOT)                     0xa000
 0x00000002 (PLTRELSZ)                   48 (bytes)
 0x00000014 (PLTREL)                     REL
 0x00000017 (JMPREL)                     0x504
 0x00000011 (REL)                        0x4bc
 0x00000012 (RELSZ)                      72 (bytes)
 0x00000013 (RELENT)                     8 (bytes)
 0x6ffffffe (VERNEED)                    0x47c
 0x6fffffff (VERNEEDNUM)                 2
 0x6ffffff0 (VERSYM)                     0x44a
 0x6ffffffa (RELCOUNT)                   3
 0x00000000 (NULL)                       0x0

There are no relocations in this file.

Histogram for `.gnu.hash' bucket list length (total of 3 buckets):
 Length  Number     % of total  Coverage
      0  0          (  0.0%)
      1  0          (  0.0%)      0.0%
      2  0          (  0.0%)      0.0%
      3  0          (  0.0%)      0.0%
      4  3          (100.0%)    100.0%

No version information found in this file.

Displaying notes found at file offset 0x000000f4 with length 0x00000024:
  Owner                 Data size	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: ac6ea6fe7322fa24472e5cce18f5ea1b24f5863d
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3-D16
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: Deprecated
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
```

**Comment by jreiser** [comment]
@pcheng74 Remember you must specify **upx --android-shlib** in order to activate the work-around.

**Comment by pcheng74** [comment]
@jreiser thanks very much, you are right, after I use upx --android-shilb, and then it can work now.

Really appreciate your help.

**Comment by jreiser** [comment]
The fix https://github.com/upx/upx/commit/f4947cc2ae57b8540a3dc40ee4d087e78cdec26a on the devel branch has been working for a month.
