### ISSUE TITLE
can you republish a ARM64(aarch64) version ? tks

### ISSUE THREAD

**Issue by 805447391** [upx/upx#117]
## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): lastest, now
* Host Operating System and version:LEDE with kernel 4.90.40 on linux (Raspbian)
* Host CPU architecture:aarch64
* Target Operating System and version:same as Host OS
* Target CPU architecture:same as Host CPU
My C library is musl.

**Comment by jreiser** [comment]
https://github.com/upx/upx/releases/tag/v3.94
"Note: all versions are functionally equivalent, i.e. each version can handle all executable formats, so you only need the file that runs on your host OS."
So each of the amd64 Linux version, the i386 Linux version, the Win32 version, etc. can compress executables for 32-bit ARM and 64-bit ARM and any other supported architecture.
If you supply a URL to a downloadable musl libc executable shared library then I'll see about building a native UPX for 64-bit ARM Linux.

**Comment by jreiser** [comment]
https://www.dropbox.com/s/jzcstmclb56o8yu/upx-aarch64?dl=0
needs libc.so.6, libm.so.6, libgcc_s.so.1, libc.so.1, ld-linux-aarch64.so.1

**Comment by markus-oberhumer** [comment]
We have lots of cross-builds (including aarch64) in our https://github.com/upx/upx-automatic-builds repo.

See https://github.com/upx/upx-automatic-builds/tree/gitlab-20170722-b9adfd8-gitlab/Ubuntu-16.04
