### ISSUE TITLE
[minor][Windows] Windows 10 compatibility + fix

### ISSUE THREAD

**Issue by eladkarako** [upx/upx#119]
I was had some issues with slow running Windows 10 running upx super slow,
through its file-virtualization engine.

I've <a href="https://github.com/eladkarako/upx-mod/blob/master/upx.exe.manifest">slightly modified the manifest</a> to make it compatible (+ other stuff).

Since upx.exe already has manifest as a resource,
and the external-manifest won't do much unless <a href="https://gist.github.com/eladkarako/d24d5ed3c917ef230b0fc990104f9fe6">a registry fix</a> will be applied, 
I've also slightly modified the <a href="https://github.com/eladkarako/upx-mod/blob/master/upx.exe">manifest resource in upx.exe</a> using <a href="https://github.com/eladkarako/manifest/">this tool</a>.

Ps.
Compressing UPX with UPX is <em>so META</em> :)

**Comment by markus-oberhumer** [comment]
Hi, could you explain why Windows 10 starts to "virtualize" things, and what exactly is needed here? Thanks.

**Comment by eladkarako** [comment]
Here are two helpful (short) articles:
https://docs.microsoft.com/en-us/windows/access-protection/user-account-control/how-user-account-control-works
https://blogs.msdn.microsoft.com/patricka/2009/12/14/tales-of-application-compatibility-weirdness-demystifying-uac-virtualization/
