### ISSUE TITLE
weird behavior of the compressed exe on windows

### ISSUE THREAD

**Issue by micsuka** [upx/upx#12]
## What's the problem (or question)?

Applications are behaving weird on windows (windows 8, but other versions have been reported too), they're lagging, especially when playing sounds. Maybe some section in the exe is missing/wrong.

I attached a small test program which playing a wav file. You can see that the same exe compressed with the new (unstable) upx is behaving weird, while compressed with the stable upx it's ok. But after I decompress the buggy exe, it's running as expected.

## What should have happened?

The compressed exe should work as the uncompressed one.
## How can we reproduce the issue?

See the attachment ( [test.zip](https://github.com/upx/upx/files/517756/test.zip) )

## Please tell us details about your environment.

- UPX version used (`upx --version`):
  git-1f51ef development version and 3.91 stable version.
- Operating System and version:
  upx is running on Linux (Debian 7) for a win32 application (cross compiling), tested on Windows 8.
- CPU architecture:
  The executable is i686 win32 application.

**Comment by ml1050** [comment]
I have committed a TLS related bug fix for the devel branch. Can you give it a try?

**Comment by markus-oberhumer** [comment]
We now have automated builds of the devel branch - please download the current win32 version from

https://github.com/upx/upx-automatic-builds/tree/devel-20170115-120150-ac4b51-travis/i386-w64-mingw32-gcc-4.6-release

**Comment by markus-oberhumer** [comment]
Please try the fresh UPX 3.93 release and close this issue if fixed.

**Comment by micsuka** [comment]
I tried the fresh 3.93 (more precisely 3.93-git-fdce705e55fb) on windows 8 and it seems to be working as expected, so I'm closing this issue.

thank you.
