### ISSUE TITLE
upx fails to compress alpine linux getconf

### ISSUE THREAD

**Issue by liamwhite** [upx/upx#120]
## What's the problem (or question)?
UPX cannot compress the Alpine getconf binary without erroring like so:
```
liam:alpine$ upx -qq usr/bin/getconf 
upx: usr/bin/getconf: CantPackException: need DT_INIT; try "void _init(void){}"
liam:alpine$ file usr/bin/getconf 
usr/bin/getconf: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), statically linked, stripped
```

## What should have happened?

UPX should be able to pack the executable.

## Do you have an idea for a solution?
UPX may be looking for ld.so loader information and failing to find it. I could not confirm this, because a simple statically linked binary I made was able to be compressed without issue.

## How can we reproduce the issue?

[Link to binary](https://a.pomf.cat/uayfkx)

1. upx -qq ./getconf

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94
* Host Operating System and version: Linux 4.12
* Host CPU architecture: x86_64
* Target Operating System and version: Linux 4.12
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
Fixed on devel branch by using DF_1_PIE as a marker for "not a shared library".
commit ee18fe9bbab4955191e68a0982196f1b6f3e5c7d
Author: John Reiser <jreiser@BitWagon.com>
Date:   Tue May 30 13:43:06 2017 -0700

    DF_1_PIE and calls_crt1() to handle part of -pie,-fPIE

    https://github.com/upx/upx/issues/106  [partial]
            modified:   p_elf_enum.h
            modified:   p_lx_elf.cpp
            modified:   p_lx_elf.h
