### ISSUE TITLE
alignment issue in arm32

### ISSUE THREAD

**Issue by kernelhack** [upx/upx#122]
## What's the problem (or question)?

when i compressed arm 32 shared library files, i found when i pack some armeabi so file, then i open it with dlopen ,it cause segment fault,so i debugged with IDA Pro, i found the loader(decompresser) decompress original so file content and then copy 0xBDFFDF00(aka svc 0, pop {r0-r7, pc} instructions in thumb mode),after decompress it will go to these instructions and then go to original _init() function.
the issue is loader copy 0xBDFFDF00 to the last of decompression data but not align address, so when program jump to this address , it may not aligned and pc will be set a wrong address.

## Do you have an idea for a solution?

before copy 0xBDFFDF00, make sure target address is aligned or calc an aligned address by code.

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.x
* Host Operating System and version: linux 
* Host CPU architecture: i386
* Target Operating System and version: android 5.0
* Target CPU architecture: armv5
![bug](https://user-images.githubusercontent.com/2366629/30408624-bc349de4-9932-11e7-8503-2c1fc88403b4.png)

![Uploading bug.png…]()

**Comment by jreiser** [comment]
The fix seems to have held.
