### ISSUE TITLE
arm64 issue in some android 7.0 devices

### ISSUE THREAD

**Issue by kernelhack** [upx/upx#126]
## What's the problem (or question)?

some android 7.0 system has enhanced security mechanism,  i encountered a compatibility issue

issue code in arm64-linux.shlib.init.s:
// Allocate pages to hold temporary copy.
        mov arg6,#0
        mov arg5,#-1  // cater to *BSD for fd of MAP_ANON
        mov arg4,#MAP_PRIVATE|MAP_ANONYMOUS
        mov arg3,#PROT_READ|PROT_WRITE|PROT_EXEC
        str arg2,[fp,#p_unmap+1*8]  // length to unmap
        mov arg1,#0  // any addr
        do_sys __NR_mmap64; cmn x0,#4096; bcc 0f; brk #0; 0:
        str x0,[fp,#p_unmap+0*8]  // address to unmap

        ldr rsi,[fp,#p_mprot]
        //mov edi,r0  // edi= dst  NOP: edi==r0
        ldr ecx,[fp,#o_wfrag]  // w_fragment
        bl movsl  // copy the fragment

        ldr rsi,[fp,#p_uncpr]  // src
        ldr ecx,[fp,#p_uncpr+1*8]  // len
        str rdi,[fp,#p_uncpr]
        add ecx,ecx,#3; lsr ecx,ecx,#2
        bl movsl  // copy compressed data

        mov rdx,rdi  // lo(dst) of copied code

        ldr rsi,[fp,#o_uncpr]
        str rdi,[fp,#o_uncpr]
        bl movsl_subr  // copy decompressor

        ldr rsi,[fp,#o_unflt]
        str rdi,[fp,#o_unflt]
        bl movsl_subr  // copy unfilter

        POP1(rsi)   // &supervise
        PUSH1(rdi)  // &copied
        bl movsl_subr  // copy supervisor

        POP1(lr); br lr  // goto copied supervisor

 which is loader of upx map a "rwx" memory region, and copy code into it, then jump to this new memory, but in some new android 7.0 devices like HUAWEI(EMUI 5.1), the br will cause an "illegal instruction" fault.

## Do you have an idea for a solution?

the issue is the writable and executable must not set at same time.
so when first map a new memory , set r+w
then before br target memory address, use mprotect change it to r+x

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version: HUAWEI ANDROID 7.0 (EMUI5.0/5.1)
* Target CPU architecture:AARCH64

**Comment by jreiser** [comment]
I believe this is fixed on <tt>devel</tt> branch.  If not, then please re-open.
