### ISSUE TITLE
Stack corruption depending of the number of environment variables (ARMv7)

### ISSUE THREAD

**Issue by st0mp** [upx/upx#131]
[test.zip](https://github.com/upx/upx/files/1362981/test.zip)

## What's the problem (or question)?
The application stack gets corrupted depending how many env variables are exported before execution. Odd number is OK.

## How can we reproduce the issue?

1. A test application is attached. The char buffer at the beginning is added to increase the binary size and the NOP assembler instructions are to avoid NotCompressibleException from UPX.
We're building with armv7lhf-baserock-linux-gnueabi-g++
As output we expect to see "--- main(): 1" but in the failing case instead of "1" we see some garbage value.
Also this seems related to the casting to "long long". The following are working fine:
```
std::to_string(1)
std::to_string(static_cast<long>(1))
```

2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.93
* Host Operating System and version: Linux visteon 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:08:14 UTC 2014 i686 i686 i686 GNU/Linux
* Host CPU architecture: x86
* Target Operating System and version: Linux with kernel 4.0.6
* Target CPU architecture: ARMv71

**Comment by jreiser** [comment]
Fixed on 2017-06-14 on devel branch by commit 8f572e5fe674202da33542fca7e0588722adb99e .
