### ISSUE TITLE
Can't pack mipsel/linux so file 

### ISSUE THREAD

**Issue by usualwyy** [upx/upx#135]
## What should have happened?

WangdeMacBook-Pro:~ usualwyy$ upx /Users/usualwyy/Downloads/libsecure.so 
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.94        Markus Oberhumer, Laszlo Molnar & John Reiser   May 12th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: /Users/usualwyy/Downloads/libsecure.so: UnknownExecutableFormatException

Packed 0 files.

## Do you have an idea for a solution?
No idea

## How can we reproduce the issue?
Can not pack the so file.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
WangdeMacBook-Pro:~ usualwyy$ upx --version
upx 3.94
UCL data compression library 1.03
zlib data compression library 1.2.8
LZMA SDK version 4.43
Copyright (C) 1996-2017 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2017 Laszlo Molnar
Copyright (C) 2000-2017 John F. Reiser
Copyright (C) 2002-2017 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
* Host Operating System and version:
WangdeMacBook-Pro:~ usualwyy$ uname -a
Darwin WangdeMacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
* Host CPU architecture:
Darwin/X64
* Target Operating System and version:
openwrt/linux
* Target CPU architecture:
mipsel
* Target file info:
`WangdeMacBook-Pro:~ usualwyy$ file /Users/usualwyy/Downloads/libsecure.so 
/Users/usualwyy/Downloads/libsecure.so: ELF 32-bit LSB shared object, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, not stripped

[libsecure.so.zip](https://github.com/upx/upx/files/1389564/libsecure.so.zip)

**Comment by jreiser** [comment]
Implemented.
