### ISSUE TITLE
Upx compressed exe not work for electron.exe on win7, win10 is OK

### ISSUE THREAD

**Issue by SLdragon** [upx/upx#141]
Upx compressed exe not work for electron.exe on win7, it will case APPCRASH. But the compressed exe is working on win10. 
![image](https://user-images.githubusercontent.com/5545529/32258997-9b014280-bef8-11e7-91be-344b6291684b.png)

Sample project url:
[Sample](https://pan.baidu.com/s/1c1ONssw)

This sample project is based on electron  v1.7.8 : 

https://github.com/electron/electron/releases/tag/v1.7.8

## What's the problem (or question)?
After compress the test.exe using upx.exe -1 test.exe, the program cannot work on win7.

## How can we reproduce the issue?

1. Download the sample
2. Compress the test.exe using upx
3. Run the compressed exe on win7
4. The program will crash

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94 / Other version 3.91 3.93 also not work
* Host Operating System and version: win7/wn10
* Host CPU architecture: x64
* Target Operating System and version: win7
* Target CPU architecture:x64

**Comment by roy2651** [comment]
same problem
