### ISSUE TITLE
SIGSEGV iterating imported dll of corrupted file

### ISSUE THREAD

**Issue by fanrong1992** [upx/upx#143]
## What's the problem (or question)?

SIGSEGV in upx when compressing the segfault.exe input file in the attached segfault.tar.gz.
[segfault.tar.gz](https://github.com/upx/upx/files/1448588/segfault.tar.gz)
PeFile::processImports0<LE64, unsigned long long> (this=0x9b0030, ord_mask=0x8000000000000000) at pefile.cpp:848
848	        while (im->dllname)

## What should have happened?

No SIGSEGV.

## How can we reproduce the issue?

1.upx segfault.exe
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94
* Host Operating System and version: Ubuntu16.04 Linux 4.4.0
* Host CPU architecture: x86_64
* Target Operating System and version: Windows8 Pro
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
@fanrong1992 Fixed on <tt>devel</tt> branch.
