### ISSUE TITLE
DLL files not works after packed by UPX latest version! UPX 3.94 released

### ISSUE THREAD

**Issue by Karaulov** [upx/upx#144]
## What's the problem (or question)?

Sometime dll files packed by upx not works! (Packed with 9 level compress)

## What should have happened?

dll packed by upx need to be working!

## Do you have an idea for a solution?

not using UPX 3.94

## How can we reproduce the issue?

1. download 3.94 upx
2. unpack upx.exe
3. run upx.exe dll path with 9 compress level
4. dll file not working

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version: Win7 x64
* Host CPU architecture: AMD
* Target Operating System and version: SP1
* Target CPU architecture: AMD 5000+ x64 Dual Core

**Comment by markus-oberhumer** [comment]
Does it work with any previous version like 3.91?

**Comment by Karaulov** [comment]
Yes. See video:

[![ICrash dll after using new version UPX ](https://img.youtube.com/vi/E4uc3nsahhI/0.jpg)](https://youtu.be/E4uc3nsahhI)
