### ISSUE TITLE
.dynamic section has invalid link(0) sh_type: 0 (expected SHT_STRTAB)

### ISSUE THREAD

**Issue by liangperfect** [upx/upx#147]
.dynamic section has invalid link(0) sh_type: 0 (expected SHT_STRTAB)
## What's the problem (or question)?

Sometime so files packed by upx not works in Android N 
## What should have happened?

so packed by upx need to be working!
## Do you have an idea for a solution?

 I have  read #65 , but it is invalid
## How can we reproduce the issue?

1.  ndk-build so
2.   packed so by upx   command line: ./upx.out -o librt.so librt_jni.so --android-shlib 
3.  so not working

## Please tell us details about your environment.

* UPX version used (`upx --version`):upx 3.95-git-6eafa552bb4b    branch :devel
* Host Operating System and version:Android N 7.1
* Host CPU architecture:  
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
@liangperfect Please look at the console log (or other source of the complaint), and copy+paste the whole exact message into a Comment here.  Android makes several mistakes, and knowing the complete text helps figure out their errors and how upx might adapt.

**Comment by jreiser** [comment]
@liangperfect Also please run these commands, then copy+paste the Section info for any STRTAB or DYNAMIC type.
```
$ readelf --sections my_lib-original.so
$ readelf --sections my_lib-compressed.so

# The original might look like:
Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 6] .dynstr           STRTAB           0000000000000b50  00000b50
       00000000000003d6  0000000000000000   A       0     0     1
  [28] .shstrtab         STRTAB           0000000000000000  0001283c
       0000000000000110  0000000000000000           0     0     1
  [22] .dynamic          DYNAMIC          0000000000211b78  00011b78
       00000000000001c0  0000000000000010  WA       6     0     8

# The compressed might look like:
  [ 0] <no-name>         NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] <no-name>         STRTAB           00000000000003e0  000003e0
       00000000000000c8  0000000000000000   A       0     0     1
  [ 2] <no-name>         DYNAMIC          0000000000072db0  00001db0
       0000000000000220  0000000000000010  WA       1     0     8
```
It seems to me that the code in p_lx_elf.cpp that relates to:
```
20bc848b (John Reiser             2017-03-31 13:24:36 -0700 3265)                     set_te16(&sptr->sh_link, smap[sptr->sh_link]);
```
will set {DYNAMIC}.sh_link to the new section ordinal of [some] STRTAB, which should not be zero.

**Comment by liangperfect** [comment]
@jreiser I only have Android Runtime Error Logs:

AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.example.admin.myapplication, PID: 12813
E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.example.admin.myapplication-1/lib/arm/librt_jni_shell.so" .dynamic section has invalid link(0) sh_type: 0 (expected SHT_STRTAB)
E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1530)
E AndroidRuntime: 	at android.view.View.performClick(View.java:5637)
E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22433)
E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6188)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)
W ActivityManager:   Force finishing activity com.example.admin.myapplication/.view.CameraActivity

================================================================
readelf --sections my_lib-compressed.so

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1]                   STRTAB          0000058c 00058c 000635 00   A  0   0  1
  [ 2]                   DYNAMIC         00003e88 002e88 000130 08  WA  1   0  4
  [ 3]                   ARM_ATTRIBUTES  00000000 0030a4 000034 00      0   0  1

================================================================
readelf --sections my_lib-original.so

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .interp           PROGBITS        00000154 000154 000013 00   A  0   0  1
  [ 2] .note.gnu.build-i NOTE            00000168 000168 000024 00   A  0   0  4
  [ 3] .dynsym           DYNSYM          0000018c 00018c 000400 10   A  4   1  4
  [ 4] .dynstr           STRTAB          0000058c 00058c 000635 00   A  0   0  1
  [ 5] .hash             HASH            00000bc4 000bc4 00019c 04   A  3   0  4
  [ 6] .gnu.version      VERSYM          00000d60 000d60 000080 02   A  3   0  2
  [ 7] .gnu.version_d    VERDEF          00000de0 000de0 00001c 00   A  4   1  4
  [ 8] .gnu.version_r    VERNEED         00000dfc 000dfc 000020 00   A  4   1  4
  [ 9] .rel.dyn          REL             00000e1c 000e1c 000040 08   A  3   0  4
  [10] .rel.plt          REL             00000e5c 000e5c 000040 08  AI  3  11  4
  [11] .plt              PROGBITS        00000e9c 000e9c 000074 00  AX  0   0  4
  [12] .text             PROGBITS        00000f10 000f10 001618 00  AX  0   0  4
  [13] .ARM.extab        PROGBITS        00002528 002528 000078 00   A  0   0  4
  [14] .ARM.exidx        ARM_EXIDX       000025a0 0025a0 000130 08  AL 12   0  4
  [15] .rodata           PROGBITS        000026d0 0026d0 000034 01 AMS  0   0  1
  [16] .fini_array       FINI_ARRAY      00003e7c 002e7c 000008 00  WA  0   0  4
  [17] .init_array       INIT_ARRAY      00003e84 002e84 000004 00  WA  0   0  1
  [18] .dynamic          DYNAMIC         00003e88 002e88 000130 08  WA  4   0  4
  [19] .got              PROGBITS        00003fb8 002fb8 000048 00  WA  0   0  4
  [20] .data             PROGBITS        00004000 003000 000004 00  WA  0   0  4
  [21] .bss              NOBITS          00004004 003004 000000 00  WA  0   0  1
  [22] .comment          PROGBITS        00000000 003004 000028 01  MS  0   0  1
  [23] .note.gnu.gold-ve NOTE            00000000 00302c 00001c 00      0   0  4
  [24] .ARM.attributes   ARM_ATTRIBUTES  00000000 003048 000034 00      0   0  1
  [25] .shstrtab         STRTAB          00000000 00307c 0000fe 00      0   0  1
  
  Thanks!

**Comment by jreiser** [comment]
@liangperfect There is a discrepancy between the complaint <tt>.dynamic section has invalid link(0) sh_type: 0 (expected SHT_STRTAB)</tt> and the output of <tt>readelf --sections my_lib-compressed.so</tt>.  In the compressed .so, then DYNAMIC Section[2].Lk is 1, not 0; and Section[1].Type is [SHT_]STRTAB, not 0.

Could there be a mixup between the .so that was used for execution, versus the .so that was specified to <tt>readelf</tt>? For example, if the pathnames have many levels of subdirectories, or involve symbolic links, then it can be easy to execute an old .so but inspect a new one.

**Comment by liangperfect** [comment]
@jreiser I'm sure the pathnames is righ .  Can I send you original .so  and you compresses it send to me ?

**Comment by jreiser** [comment]
@liangperfect Yes, please send me the original .so.  Apply gzip, then send as an email attachment.  My address is in the git log.

**Comment by liangperfect** [comment]
@jreiser I hava send email to jreiser@BitWagon.com with original .so , please check out .  my address is 1050269356@qq.com

**Comment by jreiser** [comment]
@liangperfect Please send it again.  I get so much spam from qq.com that I was automatically deleting anything from there.  However, I have stopped that temporarily so that I can receive the original .so from you.

**Comment by jreiser** [comment]
@liangperfect  I received your second message, extracted the original .so, used upx to compress it, ran readelf to inpsect the result, and sent it back to you.

**Comment by liangperfect** [comment]
@jreiser I received your compressed .so , run it in Android N ,  your compressed .so has link value 
but run compressed .so in Android N, the same error happen . 
Android Runtime error  logs:  
.dynamic section has invalid link(0) sh_type: 0 (expected SHT_STRTAB) .

**Comment by jreiser** [comment]
@liangperfect  I still do not understand why the complaint does not match the apparent code.
```
$ git clone git://github.com/android/platform_bionic.git
$ cd platform_bionic
$ git tag -l  # list all tags, look for "android-n"

$ git checkout android-n-preview-5  # the last android-n tag
$ git log | sed 4q
commit 85f900d58902bc54ac3f6efc7240de0a576ba51c
Merge: 48cedda 4ce902c
Author: Elliott Hughes <enh@google.com>
Date:   Thu Jul 14 16:54:23 2016 +0000

$ git checkout master  # the current tip
$ git log | sed 4q
commit f40402a39fc3effc4c35c12565ae1a7be90f1c18
Merge: e070051 5e235c8
Author: Treehugger Robot <treehugger-gerrit@google.com>
Date:   Fri Nov 17 02:40:35 2017 +0000

$ git diff 85f900d58902bc54ac3f6efc7240de0a576ba51c f40402a39fc3effc4c35c12565ae1a7be90f1c18 linker/linker_phdr.cpp
   const ElfW(Shdr)* strtab_shdr = &shdr_table_[dynamic_shdr->sh_link];

   if (strtab_shdr->sh_type != SHT_STRTAB) {
-    DL_ERR("\"%s\" .dynamic section has invalid link(%d) sh_type: %d (expected SHT_STRTAB)",
-           name_.c_str(), dynamic_shdr->sh_link, strtab_shdr->sh_type);
+    DL_ERR_AND_LOG("\"%s\" .dynamic section has invalid link(%d) sh_type: %d (expected SHT_STRTAB)",
+                   name_.c_str(), dynamic_shdr->sh_link, strtab_shdr->sh_type);
     return false;
   }
```
and that is the only place in platform_bionic that mentions ".dynamic section has invalid link".  That code does not match with the Elf32_Shdr records for my_lib-compressed.so as given in https://github.com/upx/upx/issues/147#issuecomment-345123229 .

Do you have any info about a different source for the runtime linker for Android-N ?

**Comment by liangperfect** [comment]
@jreiser There is not more info about runtime linker for Android-N ,  
if you understand Android Project ,I can send you the Android demo .
or this complaint  May not solve , I can close this issus.    
Thank for you!!!

**Comment by jreiser** [comment]
@liangperfect Let's try the simplest case.
```
// gcc -g -shared -fPIC my_lib.c -o my_lib.so
int const x[10000] = {1,2,3};
int my_sub(int j)
{
	return x[j];
}
=====
// gcc -g my_main.c $PWD/my_lib.so -o my_main
#include <stdio.h>
extern int my_sub(int);

int main(int argc, char *argv[])
{
        int val = my_sub(2);
        printf("val= %d\n", val);
        return val;
}
=====
# Execute with un-compressed shared library.
$ ./my_main
val= 3
$ echo $?
3

$ mv my_lib.so my_lib-orig.so
$ upx --android-shlib -o my_lib-upx.so my_lib-orig.so
# Use a symbolic link to choose which implementation for my_lib.so .
$ ln -s my_lib-upx.so my_lib.so
# Execute with compressed shared library.
$ ./my_main
val= 3
$ echo $?
3
```

**Comment by liangperfect** [comment]
@jreiser  This  simplest case is nomal, But My compressed .so can not  run in Android-N . 
I will close this issue, 
thank for your help!!!
