### ISSUE TITLE
Unable to  compress the app

### ISSUE THREAD

**Issue by vaidyaanand** [upx/upx#149]
![11-20-2017 5-03-41 pm](https://user-images.githubusercontent.com/22315535/33016624-41f81a34-ce15-11e7-97a9-5b2af49a9ca0.png)

I have created the electron app which I want to compress using UPX but It is throwing an error.

`upx: cpu-installer.exe: NotCompressibleException`
## What's the problem (or question)?
It must have to create a copressed exe file
 It is throwing an error

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.94
* Host Operating System and version: windows 10/8/7/vista/xp
* Host CPU architecture: windows x64
* Target Operating System and version: windows 10
* Target CPU architecture: windows x64

**Comment by jreiser** [comment]
@vaidyaanand Please give a pointer to the input file, and the exact command line that was used to invoke upx.  Do you encounter similar problems when compressing a small app, such as <tt>notepad</tt>?

**Comment by jreiser** [comment]
Not enough information to proceed.
