### ISSUE TITLE
segment fault when I run upx-compressed elf executable compiled with gcc-6.2.1, but gcc-4.8.4 is ok

### ISSUE THREAD

**Issue by HuiTongGe** [upx/upx#150]
## What's the problem (or question)?
I got segment fault when running a upx-compressed elf excutable file compiled with gcc-6.2.1, but it ran well when the version of gcc is gcc-4.8.4

## What should have happened?
it should run well after compressed by upx-3.94

## Do you have an idea for a solution?
I tried to compress the executable file mentioned above with upx-devel, and the compressed elf executalbe can then run properly, so i guess that the "bug" might have been solved in the dev branch

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94
* Host Operating System and version: custom Linux 64-bit based on Debian
* Host CPU architecture: x86_64
* Target Operating System and version: custom Linux 64-bit based on Debian
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
@HuiTongGe Please upload the file if it is small ("Attach files by ..."), or give a link or pointer to the input file itself.  Also, you say that it works using the <tt>devel</tt> branch.  So it looks like the problem has been solved?

**Comment by HuiTongGe** [comment]
@jreiser  Hi, I have uploaded the uncompressed executable files, you can run it from terminal.
BTW, the excutalbe file wineserver is actually part of the wine project(v2.0.3) compiled with different versions of GCC
Thank you for your help.
[upload.zip](https://github.com/upx/upx/files/1495170/upload.zip)

**Comment by jreiser** [comment]
@HuiTongGe Thank you for uploading the actual files.  They really help!
The gcc-4 wineserver is an ordinary ET_EXEC file that loads at the same address each time.  The gcc-6 wineserver is an ET_DYN  position-independent main program (gcc -pie -fpie) that loads at a different address each time.  upx-3.94 had problems with PIE programs.  Also, the linux kernel became less predictable about where it put various extra pieces such as [vvar], [vdso], etc (see <tt>cat /proc/self/maps</tt>).  Therefore the <tt>devel</tt> branch has a major re-write of the upx de-compression stub for laying out the address space.  Please use the <tt>devel</tt> branch.
```
$ file wine*
wineserver(gcc-4.x.x): ELF 32-bit LSB executable ...
wineserver(gcc-6.x.x): ELF 32-bit LSB shared object ...
```
