### ISSUE TITLE
How to package .EXE and app data folder into single .EXE?

### ISSUE THREAD

**Issue by agmcroberts** [upx/upx#153]
## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
Use a shell archive (/usr/bin/shar) or some analogous utility for MS Windows if cygwin is not installed.
