### ISSUE TITLE
Run brute force mode in parallel

### ISSUE THREAD

**Issue by Zeblote** [upx/upx#155]
## What's the problem (or question)?
It looks like brute force mode runs 12 different compression methods in a row and then tests which one worked best. Is this correct?

## What should have happened?
The 12 different methods should be run parallel, and the results compared after all finished.

## How can we reproduce the issue?
Compress a large binary in brute force mode.

## Please tell us details about your environment.
upx 3.94

**Comment by jreiser** [comment]
Same as https://github.com/upx/upx/issues/94 which contains some details that affect any implementation of this feature.
