### ISSUE TITLE
MetaTrader download UPX / via UTM affiliate link

### ISSUE THREAD

**Issue by Cemtey** [upx/upx#160]
## What's the problem (or question)?
Different size file each time downloading MetaTrader file from either links below.
https://download.mql5.com/cdn/web/metaquotes.software.corp/mt4/mt4setup.exe?utm_campaign=www.metatrader4.com
https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe?utm_campaign=www.metaquotes.net

When downloading via VPN file size seems the same, md5 still different each time.
When downloading through Safari and setting block all cookies, ask websites not to trace me, md5 is always the same, yet when changing connection md5 differs via connection but is same each download.

Attempting to download via https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/
results in same md5 each time for regular connection, that's ignoring the UTM affiliate link.

UPX packer is in there since virusscan.jotti.org is showing it as virus under one virusscan.

Does that mean there could be Trojan written in via HEX editing each time to make trojan undetectable?

## What should have happened?
md5 was supposed to be the same via different connections, without VPN device/connection, without blocking the cookies and asking websites not to trace you.

## Do you have an idea for a solution?
No idea for the solution.

## How can we reproduce the issue?
Attempting to download via official links metatrader4.com MetaTrader 4 and metaquotes.net for MetaTrader 5.

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): No idea (ClamAV at virusscan.jotti.org is showing PUA.Win.Packer.Upx-48)
* Host Operating System and version: No idea
* Host CPU architecture: No idea
* Target Operating System and version: macOS High Sierra 10.13.2
* Target CPU architecture: 1,4GHz Intel Core i5.

**Comment by jreiser** [comment]
There is no connection between UPX and MetaTrader 4.  UPX cannot be responsible for actions by the software of others.
