### ISSUE TITLE
cmdsize error unpacking Mach-O i386

### ISSUE THREAD

**Issue by lab313ru** [upx/upx#161]
As I know UPX version is 3.91: https://retrocdn.net/images/8/8a/Fusion363i.7z
Crashes at: throwCantUnpack("cmdsize");

**Comment by lab313ru** [comment]
Just commented:
```if ((unsigned)(ptr - (unsigned char const *)mhdr) > ph.u_len) {
    throwCantUnpack("cmdsize");
}
```
and now it works.

**Comment by jreiser** [comment]
Thank you for reporting this bug and including the test case.  Fixed on <tt>devel</tt> branch.
