### ISSUE TITLE
Any way to compress firefox.exe?

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#162]
## What's the problem (or question)?

crash after compression

## What should have happened?

should run fine after compression
## How can we reproduce the issue?

1.try to compress 64bit firefox.exe and make it run)
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94
* Host Operating System and version: win10 64
* Host CPU architecture:x86
* Target Operating System and version:win10 64
* Target CPU architecture:x86
Thanx

**Comment by lordmulder** [comment]
Did you try with UPX 3.91, for comparison?

I'm having serious problems with any release after that one, such as this longstanding issue:
https://github.com/upx/upx/issues/83
