### ISSUE TITLE
How to make a system call in i386-linux.elf-main.c?

### ISSUE THREAD

**Issue by chrisleeshu** [upx/upx#163]
## What's the problem (or question)?

-14 returned when I call open() function to open a file in i386-linux.elf-main.c
## What should have happened?

I want to open a file and read the content of it in i386-linux.elf-main.c but it can not works using the open() functon declared in linux.h.I even tried to use inline assembly language to achieve it but it cant not work either.They both return -14 and I know  a system call should return a positive number if it runs well.
## Do you have an idea for a solution?

I have no idea about it
## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx --3.95(the recent dev branch)
* Host Operating System and version: custom Linux 64-bit based on Debian
* Host CPU architecture: x86_64
* Target Operating System and version: custom Linux 64-bit based on Debian
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
@chrisleeshu The return value in the case of an error from a raw syscall is <tt>- errno</tt>, the negative of an error number; so -14 is EFAULT, a bad address (/usr/include/asm-generic/errno-base.h).
Run <tt>strace <i>./my_app</i></tt> to see the actual arguments to system calls.  Try <tt>strace /bin/date</tt>, for example.

**Comment by harpyja** [comment]
try `syscall(5,file_name,'r');`The open function in linux kernel.Maybe sometimes works

**Comment by jreiser** [comment]
The stub i386-linux.elf-main.c must do an open() of the PT_INTERP (ld-linux...); there it is:
```
        int const fdi = open(reloc + (char const *)phdr->p_vaddr, O_RDONLY, 0);
```
Notice the <tt>reloc +</tt>.  Also notice how the format string (the first argument) to DPRINTF is handled.  String constants must be position-independent.
