### ISSUE TITLE
Including parts of UPX in security product

### ISSUE THREAD

**Issue by CalebFenton** [upx/upx#165]
## What's the problem (or question)?

I work for an anti-malware company and we'd like to include parts of UPX in our product to unpack malware. This case is explicitly covered in the  [LICENSE](https://github.com/upx/upx/blob/master/LICENSE), but we're unable to get a response from anyone. Also, the `markus.oberhumer` address is dead. How can we contact the appropriate people?

## What should have happened?

We email the contacts in the license and get a response after several days or perhaps weeks. I'm sure the maintainers are busy people.

## Do you have an idea for a solution?

Ascertain the appropriate authorities or how to contact the appropriate authorities via GitHub issue. Also, update the defunct email address in the license, if possible.

## How can we reproduce the issue?
1. Email contacts in license
2. Wait a long time
3. I'm not trying to be a smart ass. The issue template says if I don't use the template my issue will get instantly closed without a response!

## Please tell us details about your environment.
* UPX version used (`upx --version`): not applicable
* Host Operating System and version: not applicable
* Host CPU architecture: not applicable
* Target Operating System and version: not applicable
* Target CPU architecture: not applicable

**Comment by jreiser** [comment]
The LICENSE file was written and signed using PGP almost 18 years ago.  This current Issue #165 is on github.  Use knowledge of how git works to find updated email addresses.
It helps if the [at least one] specific product can be identified: has a product name, a named company that produces it, a specific website URL, etc.
In 2011 (6.5 years ago) and 2013 (4.5 years ago) similar inquiries resulted in:
```
  we will allow you to use parts of UPX and/or UCL in security software,
  as long as it is only used for scanning compressed executables in order
  to dectect malicious software.
```
That policy continues.

**Comment by CalebFenton** [comment]
Thanks, I appreciate the quick response. I'm pretty sure I could've found an updated email address, but I thought it more prudent (i.e. faster and more accurate) to ask the community of maintainers rather than poke various email addresses and get lost in spam. Also, y'all might _want_ to update the license if y'all knew it was old. Thanks again!
