### ISSUE TITLE
Request to add Linux on System Z (s390x) support

### ISSUE THREAD

**Issue by rishigits** [upx/upx#17]
## What's the problem (or question)?

Unable to use UPX on Ubuntu 16.04 on s390x - UnknownExecutableFormatException
## How can we reproduce the issue?

1.  Compile any C 'hello world' - test.c
2. upx test
   root@7b5c09245da7:/go/src/github.com/deis/registry# upx test
                      Ultimate Packer for eXecutables
                         Copyright (C) 1996 - 2013
   UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013
   
   ```
   File size         Ratio      Format      Name
   ```
   ---
   
   upx: test: UnknownExecutableFormatException
## Help us understand your issue by providing context.

I am trying to use Deis registry component on s390x ubuntu
## Please tell us details about your environment.

- UPX version used (`upx --version`):
  $/go/src/github.com/deis/registry# upx --version
  upx 3.91
  UCL data compression library 1.03
  LZMA SDK version 9.22 beta
  Copyright (C) 1996-2013 Markus Franz Xaver Johannes Oberhumer
  Copyright (C) 1996-2013 Laszlo Molnar
  Copyright (C) 2000-2013 John F. Reiser
  Copyright (C) 2002-2013 Jens Medoch
  Copyright (C) 1999-2006 Igor Pavlov
  UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
- Operating System and version:
  $/go/src/github.com/deis/registry# uname -a
  Linux 7b5c09245da7 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:47:15 UTC 2016 s390x s390x s390x GNU/Linux
- CPU architecture:
  s390x

**Comment by jreiser** [comment]
Please say more about the use case and value proposition of UPX for s390x.
For personal, portable, or embedded devices (typically x86*, ARM, MIPS, PowerPC) where in many cases storage size and/or network bandwidth are limited or expensive (USB flash memory, ROM, wireless) then the benefits of compression are easy to understand.  For s390x which exists only in a data center or cloud, and therefore is surrounded by terabytes of storage and gigabytes/second of bandwidth, then the benefits of UPX compression of executable programs are not obvious.

**Comment by rishigits** [comment]
Hi there,

I am trying to install [Deis Workflow](https://deis.com/docs/workflow/) on s390x architecture and one of its component uses UPXto compress executable.  Predictably this fails on s390x.  As you may know storage on s390x is very expensive so I can see a good use case for UPX on s390x **Linux**.  I also notice that power architecture is already supported so having this support on s390x Linux would also be beneficial.  Not sure if I answered your question ... for now I have disabled UPX calls from the code.

Thanks.

**Comment by e-desouza** [comment]
Another use-case for this is for Go binaries in containers. With k8s/OpenShift support on the platform and multi-architecture containers, the x86/amd64 containers end up being significantly smaller than the s390x containers in container registries. With release proliferation on each node in the node local registries, this adds up pretty quickly. Container pulls (from dockerhub etc) also take much longer on non-UPXd s390x containers. I understand it's less critical for backend/cloud use-cases but there is a general push in industry to create the smallest containers with the smallest base-images (e.g alpine etc) for efficiency.

**Comment by jreiser** [comment]
_the x86/amd64 containers end up being significantly smaller than the s390x containers_  &nbsp;&nbsp;  Please give some numerical data about this.

And be sure to complain to the implementers of Go.  GoLang does not use shared libraries, even for system calls; and this is the source of much of the space problem.

**Comment by jreiser** [comment]
And for the specific case of container pulls: enhance the container storage and pull process to include compression of the entire container.  For instance, all modern web servers and web browsers have the capability for _transparent_ compression: the server can decide on its own to compress before sending (even before storage, for static pages), and the browser will de-compress automatically, transparent to the user.  The compression is gzip, and the server can choose how much; `gzip -3` or `gzip -2` is fast and effective.
