### ISSUE TITLE
NotCompressibleException for short .text and long .data in Linux i386 executables

### ISSUE THREAD

**Issue by pts** [upx/upx#170]
## What's the problem?

When compressing a statically linked Linux i386 ELF executable with a short .text section and a long .data section, UPX fails with NotCompressibleException, and doesn't make the file smaller.

Here is how to reproduce:

```
/* $ gcc -m32 -s -nostdlib -Wl,--build-id=none -o long_data long_data.s
 * $ upx --best -qq long_data
 *       10580 ->      2500   23.63%   linux/i386    long_data
 * ... Uncomment the .section .data below.
 * $ gcc -m32 -s -nostdlib -Wl,--build-id=none -o long_data2 long_data.s
 * $ upx --best -qq long_data2
 * upx: long_data2: NotCompressibleException
 * $ upx -V | head -1
 * upx 3.94
 */
.globl _start
_start:
mov $4, %eax  /* __NR_write */
xor %ebx, %ebx
inc %ebx  /* STDOUT_FILENO == 1 */
mov $msg, %ecx
mov $(msg_end - msg - 1), %edx
int $0x80
xor %eax, %eax  /* exit_code := 0 */
xor %ebx, %ebx
inc %eax  /* __NR__exit */
int $0x80
/*.section .data*/
msg:
.string "Hello, World!\n"
msg_end:
.fill 10000, 1, 1
```

## What should have happened?

Even with `.section .data` uncommented in the source file, UPX should have succeeded and made the executable file smaller (from about 10300 bytes to about 2400 bytes).

In the executable file above, the first PT_LOAD segment (containing `.text`) is very short, and the second PT_LOAD segment (containing `.data`) is long and repetitive (because of the 10000 bytes of `.fill`). When deciding whether an ELF executable is compressible, UPX is considering only the first PT_LOAD segment, and finds out that this segment is very short and uncompressible, and decides (incorrectly) that the entire file is uncompressible.

For the reference, see the uncompressed `long_data2` executable here: [long_data2.zip](https://github.com/upx/upx/files/1608715/long_data2.zip).

## Do you have an idea for a solution?

When deciding whether an ELF executable is compressible, UPX should consider all PT_LOAD segments, not only the very first one.

## How can we reproduce the issue?

1. Save the example source file above as `long_data.s`.
2. Run the commands and do the steps indicated in the first `/*` above (starting with `gcc -m32 ...`).

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94
* Host Operating System and version: Linux
* Host CPU architecture: i386
* Target Operating System and version: Linux
* Target CPU architecture: i386

**Comment by jreiser** [comment]
This is related to Issue #171. Analyzing all subsets of PT_LOAD multiplies the work at compress time.

**Comment by jreiser** [comment]
@pts It ought to be a quick hack to implement a flag "--always-compress" which would skip the test.  You could do it.

**Comment by pts** [comment]
`--always-compress` as a quick hack could be useful here and for other problems, however it doesn't fix the root cause, i.e. that UPX is miscalculating the (possible) savings, because it is ignoring the 2nd PT_LOAD segment in its calculations.

I've been playing around with an `--always-compress` hack already, but it didn't work for me, because it made UPX make suboptimal decisions, i.e. with the hack UPX would choose method A even though method B would produce smaller output. So I have given up on this hack, and moved to another workaround (specific to my project). As soon as I have to time to dig deeper into these size-related decisions UPX is making, I'll implement the hack correctly, and I'll let you know. (No promises on the ETA though.)

**Comment by AraHaan** [comment]
I get this problem with conviently linking without the C Runtime library on windows where UPX would mistakingly say it is not compressible but yet I can compress it with Petite v2.4 from https://www.un4seen.com/petite however petite has an bug where if your cursor or any other resource has the name of the first icon resource that nothing in the resource directory is compressed. I have reported it to them and asked them to use UPX’s resource lookup stuff.
