### ISSUE TITLE
Filter is not used for .data in Linux i386 executables

### ISSUE THREAD

**Issue by pts** [upx/upx#171]
## What's the problem?

When compressing a statically linked Linux i386 ELF executable with a .data section which could benefit from a filter, UPX still decides not to use the filter for the .data section, thus creating an output which is larger than necessary.

Here is how to reproduce:

```
/* $ gcc -m32 -s -nostdlib -Wl,--build-id=none -o data_filter data_filter.s
 * $ upx --best -qq data_filter
 *    1031376 ->    428732   41.57%   linux/i386    data_filter
 * $ python -c 'import sys; print "filter=0x%x" % ord(sys.stdin.read()[-8 : -7])' <data_filter 
 * filter=0x49
 * ... Uncomment the .section .data below.
 * $ gcc -m32 -s -nostdlib -Wl,--build-id=none -o data_filter2 data_filter.s
 * $ upx --best -qq data_filter2
 *    1031424 ->    458308   44.43%   linux/i386    data_filter2
 * $ python -c 'import sys; print "filter=0x%x" % ord(sys.stdin.read()[-8 : -7])' <data_filter2 
 * filter=0x0
 * $ upx -V | head -1
 * upx 3.94
 */
.globl _start
_start:
mov $4, %eax  /* __NR_write */
xor %ebx, %ebx
inc %ebx  /* STDOUT_FILENO == 1 */
mov $msg, %ecx
mov $(msg_end - msg - 1), %edx
int $0x80
xor %eax, %eax  /* exit_code := 0 */
xor %ebx, %ebx
inc %eax  /* __NR__exit */
int $0x80
ret
.globl msg
msg:
.string "Hello, World!\n"
msg_end:
.fill 10000, 1, 1
/*.section .data*/
.incbin "/bin/sh"
```

As visible see above, in the first execution UPX has chosen filter 0x49. (We have two pieces of evidence for this: 1. the Python script has extracted this filter code from the PackHeader; 2. The output size is about 30 KiB smaller than in the second execution.) Also in the second execution UPX has chosen no filter (`filter=0x0`). (Again we have two pieces of evidence: output of the Python script and the file size difference.)

For the record, see the compressed `data_filter2` executable here: [data_filter2.zip](https://github.com/upx/upx/files/1608711/data_filter2.zip).

The inclusion of `/bin/sh` to the executable was chosen so that we have a long input (about 1 MiB) whose compression benefits from using a filter.

It looks like UPX is considering the use of a filter only for first PT_LOAD segment in the input ELF executable, and it uses no filter subsequent PT_LOAD segments, even if they would benefit from them.

## What should have happened?

UPX should have considered and used a filter for the .data section, and should have produced a `data_filter2` file using a filter, thus making it about 30 KiB smaller than the current output, about the same size as of `data_filter`.

## Do you have an idea for a solution?

UPX should consider using a filter for each PT_LOAD segment in the input ELF executable, i.e. when UPX is considering a (method, filter) tuple for the executable, first it should apply the compression method for each segment without a filter; and then for each compressed segment UPX should consider 1. unfiltered, and 2. using that filter; and UPX should choose the smaller output (1 or 2) independently for each compressed PT_LOAD segment.

The decompression stub `src/stub/src/i386-linux.elf-main.c` is already smart enough to accommodate this change.

## How can we reproduce the issue?

1. Save the example source file above as `data_filter.s`.
2. Run the commands and do the steps indicated in the first `/*` above (starting with `gcc -m32 ...`).

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94
* Host Operating System and version: Linux, Ubuntu 14.04
* Host CPU architecture: amd64
* Target Operating System and version: Linux
* Target CPU architecture: i386

**Comment by jreiser** [comment]
Although i386-linux.elf-main.c (and all *-linux.elf-main.c) already deal with applying any designated filter, the possibility of more than one filter is another step towards combinatorial explosion when compressing.  Already there is (n_methods * n_filters); the Enhancement would multiply by n_PT_LOAD [or more]. So for now, this is considered an Enhancement.

**Comment by pts** [comment]
Here is how to avoid the combinatorial explosion (beyond n_methods * n_filters, which UPX already has). When UPX is trying a filter, it should try it for each segment separately. If the segment benefits from the filter, UPX should use it, otherwise not. Thus it can happen that section 0 has filter 0x49, section 1 has no filter and section 2 has filter 0x49. But it can't happen that section 0 has filter 0x49 and section 2 has filter 0x46.

**Comment by jreiser** [comment]
Agreed: allowing only one filter per file, where the one filter is optionally applied to each PT_LOAD separately, does avoid the combinatorial explosion.  However, it is very likely that the  PT_LOAD for .text (has PF_X) will compress best with a 32-bit call trick filter (0x49 or 0x46), while the PT_LOAD for .data (lacks PF_X) will compress best with one of the simple delta filters (0x9Z or 0xbZ); and "best" for either PT_LOAD by itself, will be by a large margin.  So not being able to use two filters is likely to be far from optimal.
Getting Android shared libraries and/or iOS working probably is more important for now.
