### ISSUE TITLE
how to compile the stub?

### ISSUE THREAD

**Issue by harpyja** [upx/upx#173]
## What's the problem (or question)?

How to compile the stub?
## What should have happened?

I have some questions about the /stub/Makefile as a beginner:
1.What's the arm64-linux-gcc-3.4.4?aarch64 compiler?and how can I get it?
2.What's the multiarch?It doesn't work on Ubuntu_16.04_LTS_x86_64 when I wanna compile the arm_v5a_fold.S at ld.But I have already install the multiarch-support,binutils-multiarch,binutils-multiarch-dev.
3.Why the array diff of the original documents when I attempt to get all other architecture out without arm(not arm64) to compile.Because I don't have the Compiler
## Do you have an idea for a solution?

just to change the makefile or compiler?
## How can we reproduce the issue?

1.just a Ubuntu16.04 x86_64 pc with apt-get gcc-4.7-arm-linux-gnueabihf,aarch64-linux-gnu-gcc-4.9,gcc

## Please tell us details about your environment.

* UPX version used (`upx --version`):3.94
* Host Operating System and version:Ubuntu_16.04_LTS_x86_64
* Host CPU architecture:Intel Celeron(R) CPU  N3150
* Target Operating System and version:BeagleBoneBlack debian 9.1
* Target CPU architecture:armV7l

**Comment by jreiser** [comment]
1. Install upx-stubtools from the link on the page https://github.com/upx
2. See the code in src/stub/Makefile which follows the iine
```
# update $PATH for our special stub build tools
```
3. Solve 1) and 2) first.

**Comment by harpyja** [comment]
Thank you for answer me，but it seems doesn't work.Should I also change the compiler name?
PS:My Ubuntu support the multiarch,x86,x86_64.(gcc -m64,gcc -m32 works)
The upx-stubtools-check-version and sstrip have already updated in $PATH

`amd64-linux-gcc-3.4.4 -m64 -nostdinc -MMD -MT amd64-darwin.dylib-entry.h -fno-exceptions -fno-asynchronous-unwind-tables -Wall -W -Wcast-align -Wcast-qual -Wstrict-prototypes -Wwrite-strings -Werror -c src/amd64-darwin.dylib-entry.S -o tmp/amd64-darwin.dylib-entry.bin
make: amd64-linux-gcc-3.4.4: Command not found
Makefile:296: recipe for target 'amd64-darwin.dylib-entry.h' failed
make: *** [amd64-darwin.dylib-entry.h] Error 127
`
Even change the compiler name, I got this:

`python ./../../src/stub/scripts/xstrip.py --with-dump=tmp/amd64-win64.pep.bin.dump tmp/amd64-win64.pep.bin
Traceback (most recent call last):
  File "./../../src/stub/scripts/xstrip.py", line 221, in <module>
    sys.exit(main(sys.argv))
  File "./../../src/stub/scripts/xstrip.py", line 215, in main
    do_file(arg)
  File "./../../src/stub/scripts/xstrip.py", line 180, in do_file
    assert pos == len(odata), ("unexpected strip_with_dump", pos, len(odata))
AssertionError: ('unexpected strip_with_dump', 6406, 15568)
Makefile:411: recipe for target 'amd64-win64.pep.h' failed
make: *** [amd64-win64.pep.h] Error 1
`
Once I get out of the assert,It shows this:

`chmod a-x tmp/arm.v4a-linux.elf-entry.bin
multiarch-objcopy -F elf32-littlearm --strip-unneeded tmp/arm.v4a-linux.elf-entry.bin
multiarch-objcopy: tmp/arm.v4a-linux.elf-entry.bin: Invalid bfd target
Makefile:458: recipe for target 'arm.v4a-linux.elf-entry.h' failed
make: *** [arm.v4a-linux.elf-entry.h] Error 1
`
Does the binutils-multiarch not support other architectures without x86?or my configure was wrong?
My configure:

`./configure --prefix=/opt/binutils`

**Comment by jreiser** [comment]
What does your distro invoke for <tt>python</tt>?  If that doesn't get python2 then you must change stub/Makefile:
```
# commands
ECHO_e     = /bin/echo -e
ECHO_E     = /bin/echo -E
PERL       = perl
PYTHON     = python
```
[github uses Markdown to format Comments nicely.  Blocks of code or transcripts should be quoted by using a line that contains three backticks (and nothing else) just before the quoted block, and another line of three backticks just after the quoted block.  Backtick is 0140 octal, 96 decimal, 0x60 hex; on a US keyboard it is often to the left of the numeral 1, underneath the tilde. Try the quoting using the Preview tab.]

**Comment by harpyja** [comment]
The distro invoke for python was the 2.7.12 produced by Ubuntu.I didn't change the environment of python from Ubuntu16.04

**Comment by harpyja** [comment]
Emmmmmm,When I build them over by arm-linux-gnueabihf-gcc-4.7,gcc -m32 gcc -m64,aarch64-linux-gnu-gcc-4.9,I got these:
>upx.out: /root/WorkSpace/test/test_change_byte_armv4: InternalError: unknown relocation type 'R_ARM_JUMP24'

**Comment by jreiser** [comment]
Where is the <tt>R_ARM_JUMP24</tt>, how was it generated, and what is the corresponding source?
```
$ cd upx/src/stub; grep -sr R_ARM_ .
```
shows only <tt>R_ARM_PC24</tt>.  /usr/include/elf.h hints that R_ARM_JUMP24 is the same as R_ARM_PC24.  If so, then it should be easy to adapt upx/src/linker.cpp to handle them the same.  ElfLinkerArmBE::relocate1 and ElfLinkerArmLE::relocate1.

**Comment by jreiser** [comment]
f3a7620ae83135ee84706b7a558138b43ad50711 on <tt>devel</tt> branch.

**Comment by harpyja** [comment]
Thank you very much.But seems also some trouble with it.
upx.out: /root/WorkSpace/test/test_change_byte: InternalError: unknown symbol O_BINFO

**Comment by jreiser** [comment]
The original description of this Issue says that <tt>Target CPU architecture:armV7l</tt>, that is, the compressed program is to be run on a 32-bit ARM CPU under a Linux-like operating system.  The symbol <tt>O_BINFO</tt> is referenced in stub/src/arm.v4a-linux.elf-entry.S and defined in p_lx_elf.cpp:
```
void PackLinuxElf::defineSymbols(Filter const *)
{   
    linker->defineSymbol("O_BINFO", (!!opt->o_unix.is_ptinterp) | o_binfo);
}   
```
which is called by all <tt>\*-linux.elf-\*</tt> packings.  Why not yours?

**Comment by harpyja** [comment]
Emmmmmm,sorry.That my mistake.It passed.
But the compiled stub also doesn't work at armv7l.When it passed at compress program,Segmentation fault happened.Core dumped at 0xC0.
My code:
>#include<stdio.h>
const int src[1234]={1,2,3};
int main(){
printf("start\n");
printf("over\n");
}

My compile code:
>arm-linux-gnueabihf-gcc-4.7 -march=armv4 -O0 -g test.c -o test

My compress code:
>./upx.out test -o test_upx

Running test have result like this:
>start
over

But the test_upx runing like this:
>Segmentation fault

I just wanna to compile the stub passed and run armv7l elf executable file. I'm sorry to subject you to this trouble as a upx beginner

**Comment by jreiser** [comment]
It is time to deal with the actual files.  Please create a .tgz file (<tt>tar cvfz harpyja.tgz ./test ./test_upx</tt>) that contains both ./test and ./test_upx, then upload the harpyja.tgz file here.  See the line "Attach files by ..." at the bottom of the text box when entering a Comment here at github.
I have uploaded my issue173.gz where I changed the name from .tgz to .gz in order to persuade github to accept it for uploading.  (I also added "my_" as a prefix to the file names, in an attempt to avoid name clashes or accidental overwrite when extracting.)
[issue173.gz](https://github.com/upx/upx/files/1630407/issue173.gz)

**Comment by harpyja** [comment]
This is my harpyja.tgz file:
[harpyja.gz](https://github.com/upx/upx/files/1630500/harpyja.gz)

**Comment by jreiser** [comment]
Something is wrong with how the file arm.v5a.linux.elf-fold.h was built.  It is about 32KiB (0x8000) too big, and the extra bytes are all zero.  Contrast with the original src/stub/arm.v5a.linux.elf-fold.h.  Look at the lines
```
/* 0x0060 */   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
   [[snip]]
/* 0x8070 */   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
```
Looking at the stub/Makefile, I see that many of the tc.default.* entries have been changed.  Start over with no changes (install the complete upx-stubtools), and verify successful execution of the upx-compressed <tt>test_upx</tt> file.  Then change *one* of the tc.default.* entries, build the stubs, build upx, build test_upx, and run test_upx.  Continue changing one entry at a time until you find which one causes trouble.  [Or, you might be able to do a binary search on the set of changed lines.]

**Comment by harpyja** [comment]
Emmmmmm, alright.I'll have a try.Thank you very much for help me.
