### ISSUE TITLE
Knowing what brute / ultra-brute does?

### ISSUE THREAD

**Issue by ddurham2** [upx/upx#174]
First, upx is awesome!  Thanks for the great tool.

Next, linux x86_64

I'm running upx on my [PIE] binary and by default it compresses from 12 to 5.5 megs.  That's great.  But what's better is that --brute/--ultra-brute get it down to 3.4 megs.   (And it _still_ runs, which is great)

Question:  Is --brute just trying different combinations of compression ratios and filters that I could control via command flags? If so, can it be made to output how I should run it to get the same compression?  Or is it necessary to run with --brute every time.   I ask because my build process is slowed down by --brute and would be faster if I could just pass flags that keep it from having to try different things.

**Comment by jreiser** [comment]
```
$ grep ultra.brute *.cpp
help.cpp:                    "  --ultra-brute       try even more compression variants [very slow]\n"
main.cpp:    case 902:                               // --ultra-brute
main.cpp:        opt->ultra_brute = true;
main.cpp:    {"ultra-brute",      0x10, 0, 902},     // compress best, brute force
main.cpp:    {"ultra-brute",      0x10, 0, 902},     // compress best, brute force
packer.cpp:        if (method == M_ULTRA_BRUTE && !opt->ultra_brute)
packer.cpp:        if (filter_id == FT_ULTRA_BRUTE && !opt->ultra_brute)
$ grep M_ULTRA_BRUTE *.cpp
packer_c.cpp:    static const int m_all[]   = { M_NRV2B_8, M_NRV2D_8, M_NRV2E_8, M_LZMA, M_ULTRA_BRUTE, M_LZMA_003, M_LZMA_407, M_END };
packer_c.cpp:    static const int m_all[]   = { M_NRV2B_LE32, M_NRV2D_LE32, M_NRV2E_LE32, M_LZMA, M_ULTRA_BRUTE, M_LZMA_003, M_LZMA_407, M_END };
packer.cpp:        if (method == M_ULTRA_BRUTE && !opt->ultra_brute)
packer.cpp:        if (method == M_SKIP || method == M_ULTRA_BRUTE)
$ vi main.cpp
    // compression method
    {"nrv2b",            0x10, 0, 702},     // --nrv2b
    {"nrv2d",            0x10, 0, 704},     // --nrv2d
    {"nrv2e",            0x10, 0, 705},     // --nrv2e
    {"lzma",             0x10, 0, 721},     // --lzma
    {"no-lzma",          0x10, 0, 722},     // disable all_methods_use_lzma
    {"prefer-nrv",       0x10, 0, 723},
    {"prefer-ucl",       0x10, 0, 724},
```
So we see that --brute adds M_LZMA for consideration; normally only nrv is considered.  (lzma decompression is almost an order of magnitude slower than nrv decompression.)  --ultra-brute adds M_LZMA_003 and M_LZMA_407 to the list of possibilities.  These are special cases of lzma that are tailored for some patterns of data that lzma might not otherwise discover.  Unless your program has those patterns, then upx will take more but compress no better.

Run <tt>upx --fileinfo</tt> to see what parameters were used.  --lzma forces that method.  And of course <tt>-9</tt> forces the most -exhaustive search for the current method.

**Comment by ddurham2** [comment]
Great!  Interesting that there are "undocumented" command line flags.

So, just --lzma as the sole argument compresses to the optimal 3.6meg. Adding -9 slows compression down slightly but gets another 20kb off.

Startup times  of --nrvXX vs --lzma for the compressed binary are quite different.  --nrv starts up with a 110ms overhead while --lzma starts up with a ~360ms overhead.  But that should be fine for my application.

**Comment by 0wwafa** [comment]
@jreiser considering that ultrabrute scans all possible compressions and then picks the best one, is it possible to output which one it used so to apply the same to subsequent runs instead of using ultrabrute everytime?

**Comment by jreiser** [comment]
> output which one it used

The `--fileinfo` command-line argument outputs what was used:
```
$ upx -f -o foo /bin/date;  upx --fileinfo foo
foo [amd64-linux.elf, linux/amd64]
     51112 bytes, compressed by UPX 14, method 2, level 8, filter 0x49/0x07
```
The numerical methods are listed in `upx/src/conf.h`:
```
#define M_NRV2B_LE32  2
#define M_NRV2B_8     3
#define M_NRV2B_LE16  4
#define M_NRV2D_LE32  5
#define M_NRV2D_8     6
#define M_NRV2D_LE16  7
#define M_NRV2E_LE32  8
#define M_NRV2E_8     9
#define M_NRV2E_LE16  10
// #define M_CL1B_LE32   11
// #define M_CL1B_8      12
// #define M_CL1B_LE16   13
#define M_LZMA        14
```
and can be specified during a compression run as `--lzma`, `--nrv2e` etc; see `upx/src/main.cpp` under `// compression method`.
As a rule-of-thumb, then `--lzma` almost always gives the tightest compression of more than a hundred kilobytes or so, but you might not like the significantly longer time required to de-compress. For smaller inputs, then it's a contest between the larger code for the runtime de-compressor of the tighter output of `--lzma` versus the smaller de-compressor of less-tight results given by `--nrv2b` or `--nrv2e`.
