### ISSUE TITLE
Segmentation fault when executing qt static executables which are packed by UPX

### ISSUE THREAD

**Issue by antony-jr** [upx/upx#175]
## What's the problem (or question)?

When I use **UPX** to pack a **static compiled Qt App** , the new **packed executable** seems to crash without any error. Decompressing the **packed executable** with **UPX** seems to work. 
```$ upx -d QtApp && ./QtApp ``` , This particular error only occurs when I use **GUI**.

## What should have happened?

The program should execute without any error.

## Do you have an idea for a solution?

I have no idea. But I think **UPX** is doing something to the **GUI** stuff by Qt.

## How can we reproduce the issue?

1. Download [this zip file](https://github.com/upx/upx/files/1649211/AppImageUpdater.zip) which has the **UPX executable**.
2. Decompress the zip ```$ unzip AppImageUpdater.zip``` and Mark it executable , ```$ chmod +x AppImageUpdater```
3. Execute it , ```$ ./AppImageUpdater``` , it should give you a segfault.
4. It should work when uncompressed , ```$ upx -d AppImageUpdater && ./AppImageUpdater```

## Please tell us details about your environment.

* UPX version used (`upx --version`): **UPX v3.94**
* Host Operating System and version: **Linux 4.14.10-1-ARCH**
* Host CPU architecture: **x86_64**
* Target Operating System and version: **Linux 4.14.10-1-ARCH**
* Target CPU architecture: **x86_64**

**Comment by jreiser** [comment]
Thank you for attaching the test case.
Please try the <tt>devel</tt> branch of upx.  It works for me, and with <tt>--lzma</tt>.  I see the compressed program start and complete de-compression, then
```
<program>: error while loading shared libraries: libts.so.0: cannot open shared object file: No such file or directory
```
because my non-ARCH system has no <tt>libts.so.0</tt>.

**Comment by antony-jr** [comment]
Worked like a charm ❤️ 
Thank You! Keep up your good work , Not everyday we can see an amazing **packer** like **UPX**. 👍 

This is what I did to fix the issue on my **Arch Box** , Use this if any of you run into the same issue.
( **UPX** converted **18 MiB** to **5.3 MiB** )
# Solution
```
 $ git clone https://aur.archlinux.org/upx-git.git
 $ cd upx-git
 $ makepkg -s
 $ sudo pacman -U upx-git*-x86_64.pkg.tar.xz
 $ upx --version # Compress your Qt Apps
```
