### ISSUE TITLE
NoConpressibleException when trying to compress an exe that is linked with /NODEFAULTLIB to avoid the C runtime library.

### ISSUE THREAD

**Issue by AraHaan** [upx/upx#176]
## What's the problem (or question)?

the non CRT build cannot be compressed, however the CRT one always compresses fine. In fact the CRT/no CRT should not effect the file at all because the Petite compressed version (the one that has an bug on compressing the resources despite telling it to and does it even with the CRT) runs fine.

## What should have happened?

the EXE to compress, petite compresses it but does not compress the resource section for some reason.

## Do you have an idea for a solution?

Not at the moment.

## How can we reproduce the issue?

* UPX version used (`upx --version`): latest
* Host Operating System and version: Windows 7 Ultimate build 7601 (SP1)
* Host CPU architecture: x64
* Target Operating System and version: Any that supports x86 programs after windows vista.
* Target CPU architecture: x86

**Comment by jreiser** [comment]
Please upload a small actual example file which suffers the problem that you describe.  See "Attach files by ..." at the bottom of a new Comment window here on GitHub;  compress the upload using zip or gzip. A concrete test case helps immensely.

**Comment by AraHaan** [comment]
while trying to reproduce it it seems that it randomly started to compress the source with Ultra brute + all methods + all filters + force. It did not work with all those settings before. :thinking: so looks like something that was messing up is now randomly working.

**Comment by jreiser** [comment]
For the case of "random" behavior it is even more important to have an actual example which sometimes fails and sometimes works, because then running upx under valgrind may help pinpoint a bug.  Please "Attach files by ..." such a case.  [Or, you could run upx under valgrind yourself.]

**Comment by AraHaan** [comment]
I figured out why and it was because of the amount of data in the .rsrc section. After I removed some trash test resources that made the file compress it failed again. Also lost internet for a while due to it being only on my phone currently only.
