### ISSUE TITLE
cannot compile, no upx nor upx/upx.h folder/file

### ISSUE THREAD

**Issue by mgood7123** [upx/upx#178]
## What's the problem (or question)?
[exec@exec-pc upx-3.94]$ make all
make -C src all
make[1]: Entering directory '/chakra/home/universalpackagemanager/UPM/asm/elf-parser/upx-3.94/src'
Updating .depend
In file included from c_file.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from c_init.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from c_none.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from c_screen.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from compress.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from compress_lzma.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from compress_ucl.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from compress_zlib.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from except.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from file.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from filter.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from filteri.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from help.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from lefile.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from linker.cpp:28:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from main.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from mem.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from msg.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_armpe.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_com.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_djgpp2.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_exe.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_lx_elf.cpp:33:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_lx_exc.cpp:33:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_lx_interp.cpp:33:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_lx_sh.cpp:33:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_mach.cpp:28:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_ps1.cpp:33:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_sys.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_tmt.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_tos.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_unix.cpp:33:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_vmlinx.cpp:33:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_vmlinz.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_w32pe.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_w64pep.cpp:34:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_wcle.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from packer.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from packer_c.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from packer_f.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from packhead.cpp:28:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from packmast.cpp:28:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from pefile.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from s_djgpp2.cpp:28:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from s_object.cpp:28:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from s_vcsa.cpp:28:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from s_win32.cpp:28:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from snprintf.cpp:62:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from stdcxx.cpp:28:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from ui.cpp:28:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from util.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from work.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
make[1]: *** Deleting file '.depend'
make[1]: *** No rule to make target '.depend', needed by 'c_file.o'.  Stop.
make[1]: Leaving directory '/chakra/home/universalpackagemanager/UPM/asm/elf-parser/upx-3.94/src'
make: *** [Makefile:31: all] Error 2
[exec@exec-pc upx-3.94]$ find | grep upx
./upx-stubtools
./upx-stubtools/README.txt
./upx-stubtools/.git
./upx-stubtools/.git/HEAD
./upx-stubtools/.git/hooks
./upx-stubtools/.git/hooks/commit-msg.sample
./upx-stubtools/.git/hooks/pre-receive.sample
./upx-stubtools/.git/hooks/prepare-commit-msg.sample
./upx-stubtools/.git/hooks/pre-commit.sample
./upx-stubtools/.git/hooks/pre-push.sample
./upx-stubtools/.git/hooks/pre-applypatch.sample
./upx-stubtools/.git/hooks/applypatch-msg.sample
./upx-stubtools/.git/hooks/pre-rebase.sample
./upx-stubtools/.git/hooks/post-update.sample
./upx-stubtools/.git/hooks/update.sample
./upx-stubtools/.git/objects
./upx-stubtools/.git/objects/9d
./upx-stubtools/.git/objects/9d/b054911ccc8d7942632d2021e4aead4e68788e
./upx-stubtools/.git/objects/c2
./upx-stubtools/.git/objects/c2/4fbf68a66cc7423b2c1c5c9d61bf19fbdbf4b8
./upx-stubtools/.git/objects/ba
./upx-stubtools/.git/objects/ba/a84704cf717a15dbe4b5e2f65866219fdff96f
./upx-stubtools/.git/objects/e7
./upx-stubtools/.git/objects/e7/587013ab05e8523da6702ab13c61fe043fd5e6
./upx-stubtools/.git/objects/40
./upx-stubtools/.git/objects/40/98d96cb555f0fd29ab5eaf57dfe7051dc56110
./upx-stubtools/.git/objects/6e
./upx-stubtools/.git/objects/6e/096e4bc1070a4090a09609a9e435d753e2e2b6
./upx-stubtools/.git/objects/9b
./upx-stubtools/.git/objects/9b/bfef9ef8f1a00bedce55143b32ec23cd0599cd
./upx-stubtools/.git/objects/72
./upx-stubtools/.git/objects/72/810dd2492c551f71d74403f9f91eb0dd41bd37
./upx-stubtools/.git/objects/88
./upx-stubtools/.git/objects/88/bd6dfa1107ca44f0c56c82409ce74a3268887a
./upx-stubtools/.git/objects/7f
./upx-stubtools/.git/objects/7f/befdb2ac7e9b79a278c791d30416605b084656
./upx-stubtools/.git/objects/f8
./upx-stubtools/.git/objects/f8/00139179b604dbe8b320d170701e1a98b1eeaa
./upx-stubtools/.git/objects/05
./upx-stubtools/.git/objects/05/6e385162b7f0822f7fbd0285d97a5cd1ad34ef
./upx-stubtools/.git/objects/pack
./upx-stubtools/.git/objects/d5
./upx-stubtools/.git/objects/d5/d10da0d63f09f28505086c1695a3a86f16465b
./upx-stubtools/.git/objects/76
./upx-stubtools/.git/objects/76/c88f2f86b3c2313b71f5b00a090ad578a0273a
./upx-stubtools/.git/objects/info
./upx-stubtools/.git/objects/0c
./upx-stubtools/.git/objects/0c/000b128edd1a75383742e1c8cb27d29d0457e0
./upx-stubtools/.git/objects/d2
./upx-stubtools/.git/objects/d2/30e9271be585946807b5e0cee7141d2c368f58
./upx-stubtools/.git/objects/27
./upx-stubtools/.git/objects/27/472e5c2c5a9c3dfcc4048d128afaedac5f6746
./upx-stubtools/.git/objects/25
./upx-stubtools/.git/objects/25/1bf4bd8404495e99dbc6c4a126fdc2999085fd
./upx-stubtools/.git/objects/a4
./upx-stubtools/.git/objects/a4/45ea10fa522a6985c461b5252541a29ed51b14
./upx-stubtools/.git/objects/f9
./upx-stubtools/.git/objects/f9/42c17ea78d18f0a2a6d43e3ad93d7064b1faea
./upx-stubtools/.git/objects/41
./upx-stubtools/.git/objects/41/1685d89fefaa94421e27627c8134eaef73a348
./upx-stubtools/.git/branches
./upx-stubtools/.git/info
./upx-stubtools/.git/info/exclude
./upx-stubtools/.git/config
./upx-stubtools/.git/logs
./upx-stubtools/.git/logs/HEAD
./upx-stubtools/.git/logs/refs
./upx-stubtools/.git/logs/refs/heads
./upx-stubtools/.git/logs/refs/heads/master
./upx-stubtools/.git/logs/refs/remotes
./upx-stubtools/.git/logs/refs/remotes/origin
./upx-stubtools/.git/logs/refs/remotes/origin/HEAD
./upx-stubtools/.git/refs
./upx-stubtools/.git/refs/heads
./upx-stubtools/.git/refs/heads/master
./upx-stubtools/.git/refs/tags
./upx-stubtools/.git/refs/remotes
./upx-stubtools/.git/refs/remotes/origin
./upx-stubtools/.git/refs/remotes/origin/HEAD
./upx-stubtools/.git/description
./upx-stubtools/.git/packed-refs
./upx-stubtools/.git/index
./upx-stubtools/upx-stubtools-check-version
./src/stub/i386-darwin.macho-upxmain.exe
./src/stub/scripts/upx-clang-format
./src/stub/src/arch/i386/upx_itoa.S
./src/stub/src/amd64-darwin.macho-upxsubr.S
./src/stub/src/i386-darwin.macho-upxmain.c
./src/stub/src/i386-darwin.macho-upxsubr.S
./src/stub/src/powerpc-darwin.macho-upxsubr.S
./src/stub/src/powerpc-darwin.macho-upxmain.c
./src/stub/src/amd64-darwin.macho-upxmain.c
./src/stub/src/i386-linux.elf.execve-upx_itoa.S
./src/stub/src/amd64-darwin.macho-upxhide.txt
./src/stub/powerpc-darwin.macho-upxmain.h
./src/stub/i386-darwin.macho-upxmain.h
./src/stub/amd64-darwin.macho-upxmain.exe
./src/stub/powerpc-darwin.macho-upxmain.exe
./src/stub/amd64-darwin.macho-upxmain.h
./doc/upx.pod
./.github/upx-automatic-builds@github.com.enc
[exec@exec-pc upx-3.94]$

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
See the file README.SRC in the top-level directory, especially the paragraphs with headings: Prerequisites, Tools needed to build/modify the UPX sources, To compile the packer sources.
