### ISSUE TITLE
compressed binary Segment fault with option --lzma on arm64

### ISSUE THREAD

**Issue by xqdoo00o** [upx/upx#181]
## What's the problem (or question)?
compress with `--lzma` option on `aarch64`, then run compressed binary I got "Segment fault",
if without `--lzma` option, the program runs normal.
I use the gitlab branch in [autobuilds](https://github.com/upx/upx-automatic-builds/blob/gitlab-20180119-16bb7ab-gitlab/Ubuntu-16.04/aarch64-linux-gnu-gcc-5-release/upx-git-16bb7ab84143.out)

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): git-ca18e3
* Host Operating System and version: Archlinuxarm
* Host CPU architecture: aarch64
* Target Operating System and version: Archlinuxarm
* Target CPU architecture: aarch64

**Comment by jreiser** [comment]
Thank you for reporting this issue.  Fixed on <tt>devel</tt> branch.
