### ISSUE TITLE
what is "mem_size 2; take care"?

### ISSUE THREAD

**Issue by yajiedesign** [upx/upx#183]
## What's the problem (or question)?
when i upxing some dll,it hint error ` CantPackException: mem_size 2; take care`.
After a simple reading of the code.I think it's probably my file too big,it 705mb.

## What should have happened?
can't normal compression.

## Do you have an idea for a solution?
Modifying the UPX_RSIZE_MAX_MEM should work, but I see a warning not to modify it.

## How can we reproduce the issue?
1.The steps are too simple to be provided.If necessary, I can provide DLL

## Please tell us details about your environment.

* UPX version used (`upx --version`):upx 3.94
* Host Operating System and version:windows 10 
* Host CPU architecture:x64
* Target Operating System and version:windows 10 
* Target CPU architecture:x64

**Comment by jreiser** [comment]
Yes, 705MB is too big.  The internal limit of (768 * 1024 * 1024) must allow for some working space, too; check the traceback at the time of error.
Perhaps dividing the code into a couple pieces (main program and .dlls) might work.  Or, apply some internal compression (zlib, LZO, etc.) to <tt>const</tt> arrays; etc.

**Comment by yajiedesign** [comment]
@jreiser Would there be any side effects if I changed the internal limit on my own?

**Comment by jreiser** [comment]
@yajiedesign A small increase (10% ?  20% ?) probably would be OK, especially if upx itself runs on a 64-bit machine.  UPX wants to handle every input, independent of the architecture on which UPX itself runs, including 32-bit i686.  So between a limit of 3G, 2.5G, or even 2G of total user address space on i686, and hostile inputs that try to trick UPX with bogus sizes, then 768KiB is chosen for safety.  Also, the runtime decompression stubs typically have absolute limits of 4GiB, and even 2GiB in some places.  The extra code (and registers) to handle larger sizes is not worth it.

**Comment by yajiedesign** [comment]
@jreiser thanks,

**Comment by jreiser** [comment]
```
conf.h:  #define UPX_RSIZE_MAX_MEM   (905 * 1024 * 1024)
$ make util.o
util.cpp:54:1: note: in expansion of macro ‘ACC_COMPILE_TIME_ASSERT_HEADER’
 ACC_COMPILE_TIME_ASSERT_HEADER(2ull * UPX_RSIZE_MAX * 9 / 8 + 16 * 1024 * 1024 < INT_MAX)
```
(900 * 1024 * 1024)  passes that test, and the resulting upx works, at least for small cases on x86_64 under linux.  There may be other failures.
