### ISSUE TITLE
upx is incompatible with golang generated Mac64 binary 

### ISSUE THREAD

**Issue by CaledoniaProject** [upx/upx#187]
## What's the problem (or question)?

I have a golang program, when I compress it with `upx -9 mac64.bin` it works.

```
# upx -9 tmp/webdir-mac64
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2013
UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   6299936 ->   2248704   35.69%   Mach/AMD64    webdir-mac64

Packed 1 file.
```

But when I execute it, it just get killed

```
./go/tmp/webdir-mac64
Killed: 9
```

## What should have happened?

Should work normally

## Do you have an idea for a solution?

Nope

## How can we reproduce the issue?

1. The test binary can be fetched from [this link](https://github.com/baidu-security/webshell-scanner-client/releases/download/v1.0/webdir-mac64)
2. On ubuntu 16.04, install upx with `apt-get install -y upx`
3. Compress the binary downloaded
4. Execute the compressed file and it get killed on Mac OS 10.13.3

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.91  / UCL data compression library 1.03 / LZMA SDK version 9.22 beta
* Host Operating System and version: Ubuntu 16.04
* Host CPU architecture: amd64
* Target Operating System and version: macos 
* Target CPU architecture: amd64

**Comment by jreiser** [comment]
Why was upx-3.91 used?  upx-3.94 is the current release, almost 10 months old.  But for MacOS today, please  use the <tt>devel</tt> branch  of upx.

**Comment by CaledoniaProject** [comment]
Thanks, it works with upx installed from homebrew, which is version 3.94.

**Comment by jfromaniello** [comment]
I've the same problem with 3.95

**Comment by jreiser** [comment]
If the <tt>devel</tt> branch does not work for you, then please apply gzip and upload ("Attach files by ...") the executable.gz.

**Comment by CaledoniaProject** [comment]
@tammersaleh Just use homebrew
