### ISSUE TITLE
Compressed go app fails to start with error code 139

### ISSUE THREAD

**Issue by configurator** [upx/upx#192]
## What's the problem (or question)?

Trying to use upx from within Docker creates an unusable executable. I've created a minimal example using a statically compiled Go "Hello Docker" app.

## What should have happened?

The executable should have worked as normal. In my example, it should print "Hello Docker".

## How can we reproduce the issue?

1. Download both files from https://gist.github.com/configurator/2c8b10227201f201af0bcaed598d13af
2. Run `docker build . -t upxtest && ( docker run --rm -it upxtest; echo $? )`
You will see the output end with
```
Successfully tagged upxtest:latest
139
```

To run a successful case, uncomment the line `COPY --from=builder /build/app /` from the Dockerfile. This will make it build the same executable, but use the original version in the built image rather than the compressed one. The output should look like:
```
$ docker build . -t upxtest && ( docker run --rm -it upxtest; echo $? )
(...)
Successfully tagged upxtest:latest
Hello Docker
0
```
## Please tell us details about your environment.

* UPX version used (`upx --version`):
```
upx 3.91
UCL data compression library 1.03
LZMA SDK version 9.20
```
I've also tried using the Docker `ubuntu` image with `apt-get install upx`:
```
upx 3.91
UCL data compression library 1.03
LZMA SDK version 9.22 beta
```
* Host Operating System and version:
Docker 17.09.1-ce running on Ubuntu 17.10
* Host CPU architecture:
x86_64
* Target Operating System and version:
(Same as host) Docker 17.09.1-ce running on Ubuntu 17.10
* Target CPU architecture:
(Same as host) x86_64

## Source files
(Also available in https://gist.github.com/configurator/2c8b10227201f201af0bcaed598d13af )

#### app.go
```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello Docker");
}
```
#### Dockerfile
```
# Build app
FROM golang as builder
COPY . /build
RUN cd /build && CGO_ENABLED=0 go build -ldflags='-s -w' app.go

# Compress
FROM lalyos/upx as compressor
COPY --from=builder /build/app /compress/
RUN ["upx", "/compress/app"]

# Create empty image with only the app in it
FROM scratch
COPY --from=compressor /compress/app /
# COPY --from=builder /build/app /
ENTRYPOINT ["/app"]
```

**Comment by jreiser** [comment]
upx-3.94 has been released for 10.5 months, and processes the output fromf "go build app.go" into a compressed executable which runs correctly under Linux, on both x86_64 and aarch64 (64-bit ARM) [those were the machines that I had handy.]
