### ISSUE TITLE
Android arm64-v8a upx: libXXXXXX.so: InternalError: unknown relocation type 'R_AARCH64_CALL26'

### ISSUE THREAD

**Issue by llxxhm** [upx/upx#194]
## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`3.94`):
* Host Operating System and version: win7 / Ubuntu12.04
* Host CPU architecture: 64bit
* Target Operating System and version: android5.1
* Target CPU architecture: arm64-v8a

**Comment by jreiser** [comment]
Please use the <tt>devel</tt> branch where R_AARCH64_CALL26 was implemented in linker.cpp on 2017-05-06.  The change will be in the next release of upx.
