### ISSUE TITLE
go.rice compatibility

### ISSUE THREAD

**Issue by lookfirst** [upx/upx#195]
## What's the problem (or question)?

When I run upx on my golang binary, it strips out the appended [go.rice box](https://github.com/GeertJohan/go.rice#append).

## What should have happened?

Kept the box that was appended to the binary.

## Do you have an idea for a solution?

Nope, but I sure would like this to work as I need to copy this binary to literally thousands of tiny linux boxes. Any size savings is huge.

## How can we reproduce the issue?

Use go.rice to add a box to a golang binary.

I tried the `--overlay=copy` option as well.

## Please tell us details about your environment.
* UPX version used (`upx --version`): 3.94
* Host Operating System and version: OSX 10.13.1 (17B48)
* Host CPU architecture: intel64
* Target Operating System and version: arm 7 linux
* Target CPU architecture: arm 7 linux

**Comment by jreiser** [comment]
Just as you ask for upx to accommodate rice, so too you should ask rice to accommodate upx.  That is, it should work to append the rice box to a executable binary that is already compressed by upx.  At run time the upx exeuction stub unpacks the PT_LOAD segments (<elf.h>) from RAM into RAM, then transfers control to the original entry point (or the entry point of the PT_INTERP if present).  Of course if <rr>rice</tt> depends on ElfXX_Shdr then <tt>rice</tt> will fail.  The ELF format has a <i>linking</i> view (ElfXX_Shdr) and an <i>execution view</i> (ElfXX_Phdr).  At run time only the execution view is guaranteed.  Any use of ElfXX_Shdr during execution is optional, so at compress time then upx removes ElfXX_Shdr to save space.  [The Android dynamic linker for shared libraries botches this by also demanding some elements of the linking view; this is a violation of the ELF design. <tt>upx --android-shlib</tt> creates an "impostor" page of ElfXX_Shdr to deceive the Android dynamic linker.]

**Comment by jreiser** [comment]
@lookfirst Please upload ("Attach files by ...") or otherwise provide access to a specific example file or set of files that illustrate the situation.  Having a concrete example helps immensely in understanding the situation and exploring possible changes.

**Comment by jreiser** [comment]
<tt>--overlay</tt> is implemented for PE files; plus "tmt" (i386/dos32), "tos" (atari m68k), and "wcle" (dos32.watcom) files.

**Comment by lookfirst** [comment]
Thank you so much for the detailed explanation. Oh, you're totally right. Appending the rice box after the upx step worked just fine. Why didn't I think of that? (I must be stupid). ;-) Since that is a viable work around, no need to fix anything.
