### ISSUE TITLE
Why upx can not  obscure fuction name of dynamic so lib

### ISSUE THREAD

**Issue by joelihn** [upx/upx#197]
## What's the problem (or question)?

Why upx can not  obscure fuction name of liba.so  like the image below when i packed my so on linux for android by command "upx.out --android-shlib liba.so".after then, i use IDA open the packed so, i also can view the function original name...  another question is, does upx can process my const string or vector in so source code , make it not visable directly.
![image](https://user-images.githubusercontent.com/8198266/38482178-cb671e24-3c00-11e8-85dd-67f61bc61466.png)

## Please tell us details about your environment.

*UPX version used (`upx --version`):UPX 3.95
* Host Operating System and version: Ubuntu 16.04
* Host CPU architecture:arm64-v8a
* Target Operating System and version:Android
* Target CPU architecture:arm64-v8a

**Comment by jreiser** [comment]
The goal of UPX is small size, not necessarily obfuscation.  Obfuscation is merely a common by-product of the encoding that UPX uses to reduce size.  (Also note that the goal of <tt>upx -d</tt> is to re-create by de-compression the exact file that was used as input to <tt>upx</tt> for compression.)
The basic strategy of UPX is deflation (replace a substring by a reference to some earlier occurrence of that substring); but a reference can be encoded using various representations.  So try <tt>upx --lzma</tt> etc.
Compilers commonly use UTF-8 to encode symbol names.  Ideographs that have initial bytes of 0xDy or 0xEy often have no earlier matching substrings, so will be encoded as visible literals.  Try using a name that has earlier matching substrings.  Restricting symbol names to have only bytes that are less than 0x80 might tend to increase the chances of an earlier matching substring.

**Comment by jreiser** [comment]
Also, the dynamic linker performs relocation on a shared library before the UPX decompression stub (for that library) runs.  Therefore UPX must leave alone anything that the dynamic linker needs to perform relocation.  The string name of a subroutine that is visible externally (is not STV_HIDDEN, nor STV_PROTECTED, etc.) might be used by the dynamic linker in resolving external references, so UPX cannot change the name.  In practice only the executable instructions in the tail of the .text segment can be compressed, which omits DT_STRTAB, DT_SYMTAB, etc.
