### ISSUE TITLE
is it possible to compile UPX on WIN?

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#20]
i don`t think template applicable

**Comment by l2dy** [comment]
Use Windows Subsystem for Linux.

**Comment by mudlord** [comment]
You mean msys2 or something?

**Comment by necros2k7** [comment]
I mean - is it possible and if yes how to compile UPX from sources to Windows binary? PS. what`s the name of your packer?

**Comment by l2dy** [comment]
See https://msdn.microsoft.com/en-us/commandline/wsl/about

**Comment by markus-oberhumer** [comment]
The current devel branch compiles fine under Windows + msvc. See AppVeyor results on https://github.com/upx/upx/branches .  Closing.

**Comment by necros2k7** [comment]
Sorry but i can`t see link to appveyor generated binaries

**Comment by markus-oberhumer** [comment]
https://ci.appveyor.com/project/markus-oberhumer/upx

**Comment by necros2k7** [comment]
I`m confused @The build job does not contain any artifacts.@ still no binaries

**Comment by markus-oberhumer** [comment]
Binaries are only provided for releases - you're supposed to compile the devel branch by yourself.

**Comment by necros2k7** [comment]
Always though Appveyor have an option to auto compile it for people`s testing...

**Comment by markus-oberhumer** [comment]
I won't work on this, but feel free to provide a patch for .appveyor.yml .
