### ISSUE TITLE
error on WSL ubuntu 16.04.4 LTS, win 10

### ISSUE THREAD

**Issue by Justsoos** [upx/upx#201]
the same compressed file by upx named "annie" can be run on linux virtual machine well, but not work on wsl with win 10: 
```
# file ./annie
./annie: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
# ./annie
-bash: ./annie: cannot execute binary file: Exec format error
```
then I downloaded upx-3.94-amd64_linux.tar.xz and run the "compressed upx" on WSL, it got same error too.
and I decompressed this "upx" and re-run it, it worked on WSL, and
```
# file upx-3.94-amd64_linux/upx
upx-3.94-amd64_linux/upx: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.4.3, stripped
```

**Comment by Justsoos** [comment]
in order to point the real key error, I tried upx itself, u c, upx-3.94-amd64_linux/upx is also compressed by upx, am I right? the upx download from git does not work, after decompress, the upx itself run well. So, some annie program is not the key. 

I have run upx-3.94-amd64_linux to compress programs in two platform, only WSL got error, Windows10 exe program work well.

**Comment by jreiser** [comment]
WSL has had, and probably continues to have, issues with <tt>execve</tt> of ELF files.  See for instance https://github.com/Microsoft/WSL/issues/330 and the rat's nest of linked and related issues, and other similar issues as well.  It might be worth perusing the source to WSL.execve(), but my searching the 'net for a while did not find it.

**Comment by kumarharsh** [comment]
Confirming that UPX compressed builds of other softwares can be executed successfully on WSL. But running upx itself fails with this error for me:

```
upx -9 path/to/binary
/usr/bin/upx: 1: /usr/bin/upx: Syntax error: redirection unexpected
```

just running upx also results in this error:
```
Failed to execute process '/usr/bin/upx'. Reason:
exec: Exec format error
The file '/usr/bin/upx' is marked as an executable but could not be run by the operating system.
```

```
> uname -a
Linux qvkslvr 4.4.0-17763-Microsoft #253-Microsoft Mon Dec 31 17:49:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
> lsb_release -a
Description: Ubuntu 18.04.1 LTS
Release: 18.04

System info:
Windows 10 Pro 1809
```

**Comment by asantoni** [comment]
FYI this has regressed in Windows 1903, at least with WSL 1. I haven't tested it with WSL 2 yet.

**Comment by cary-sas** [comment]
sudo apt install upx 
Then use upx-ucl instead of upx
