### ISSUE TITLE
UPX not compressing vcruntime140.dll properly

### ISSUE THREAD

**Issue by answerquest** [upx/upx#203]
## What's the problem (or question)?

Pyinstaller uses UPX to build windows executable of python program. One of the DLLs included in all builds is `vcruntime140.dll`. This dll is compressed by UPX same way other DLLs are. Running the output executable on Windows 7 64-bit systems has no problems and presumably  `vcruntime140.dll` is never run. But on Windows 10 64-bit the program fails with the popup error described here: https://github.com/WRI-Cities/static-GTFS-manager/issues/78

## Other places where this problem has been reported
- https://github.com/pyinstaller/pyinstaller/issues/1565
- https://github.com/pyinstaller/pyinstaller/issues/2659

## What should have happened?
There should not have been any popup error and the program should have run properly on Window 10 system. A dos-box should open with some messages, and then a browser tab should be spawned with the program shown as a website.

## Do you have an idea for a solution?
Temporary workaround: Skip compression of  `vcruntime140.dll` and return it uncompressed to the program calling UPX (Pyinstaller in this case)  
Permanent fix: Figure out if and why UPX compression is making `vcruntime140.dll` unusable for Windows 10 systems.

## How can we reproduce the issue?

1. On a Windows 10 64-bit system, download and unzip [GTFS-Manager-Windows-v1.4.3.zip](https://github.com/WRI-Cities/static-GTFS-manager/releases/download/v.1.4.3/GTFS-Manager-Windows-v1.4.3.zip).
2. Double-click the shortcut `GTFSManager.lnk`. (Note: `.lnk` extension might not be visible at your end, but shortcut sign will be there. Don't mix it with the .py file of the same name in the same folder)
3. You should get the same popup as shared in the screenshot [here](https://github.com/WRI-Cities/static-GTFS-manager/issues/78#issue-321802035).

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.94
* Host Operating System and version: Windows 7 64-bit
* Host CPU architecture: Intel Pentium CPU B960 @ 2.20Ghz
* Target Operating System and version: Windows 10 64-bit
* Target CPU architecture: n/a (multiple targets, any computer or laptop running any variation of Windows 10  64bit and up)

**Comment by FloraFo** [comment]
Hello ! 
Thank you for your report, I just have one question: how do you  skip compression of vcruntime140.dll ?
I'm using pyinstaller with upx.

PyInstaller: 3.3.1
Python: 3.6.5
Platform: Windows-10-10.0.14393-SP0
upx: 3.95

**Comment by answerquest** [comment]
Hi @FloraFo , I'm not using UPX anymore. By using a new empty virtual environment, keeping a tight control on packages and using pip to install packages instead of conda, I was able to keep my output binary (single file) limited to 28mb in windows and 32.2mb in linux, which was acceptable. My project [is here](https://github.com/WRI-Cities/static-GTFS-manager), with the binaries also loaded. My current workflow with pyinstaller is documented here: https://github.com/WRI-Cities/static-GTFS-manager/issues/63#issuecomment-427424257 . Some folks might find the pandas hidden-import command useful too

But I had found a workaround with using UPX earlier which was possible if one is not doing single-file (and has a folder full of dlls to manage), have detailed it on https://github.com/WRI-Cities/static-GTFS-manager/issues/78 . Basically you retrieve the original dll from windows miniconda/anaconda installation and copy it over, Unfortunately that approach puts the .exe in with a whole lot of other dlls two folders deep, and if one brings it up to main folder then all the other files (tons!) also have to be brought up, which was totally defacing my program's top folder. And my program needed to run with the top folder as working folder to be able to use all the dependency data. There was a very complicated workaround of making a shortcut but it had to be manually set each time one unzipped the program at a new location. I finally chucked UPX altogether and things are much simpler now with the single binary file.

@Mattiwatti 's post might also help, check it out.

**Comment by pwnorbitals** [comment]
So basically, if I understand well, any use of UPX is incompatible with Windows >8.1 ? I suggest we should add a warning message for users to be aware of the issue

**Comment by Mattiwatti** [comment]
@pwnorbitals No, that is not correct. UPX is not compatible with binaries compiled with CFG, which is a feature only supported by Windows 8.1 and later. Therefore the following still work:
- Any UPX compressed binary running on Windows 8 or earlier, even if CFG was enabled in the binary.
- Any UPX compressed binary running on any version of Windows, so long as the binary was **not** compiled with CFG.
- Any UPX compressed binary running on any version of Windows, even if the binary was compiled with CFG, so long as the 'CFG supported' flag was stripped from the PE header.

**Comment by pwnorbitals** [comment]
I understand. What would be the best approach for best user transparency ? Detect the incompatible files and give off a warning ? It would pave the way for the workaround of not compressing the files that wouldn't work

**Comment by Mattiwatti** [comment]
Yes, that is one way. It seems to me a warning would be helpful on any input file compiled with CFG. Other than that it is debatable what to do. UPX could silently strip the feature flag that advertises CFG support in the PE header, and that will simply silently "fix" things. This behaviour may however run counter to what the user expects, if they expect CFG to remain enabled and working in the binary. I would say that a warning would be sufficient to make people understand this is not the case.

**Comment by splitbrain** [comment]
Here are my $0.02 from a user perspective: I think the current devel behavior of skipping the compression with an error message is good, but a command line flag should be introduced to optionally compress and strip the CFG supported flag instead.

**Comment by bitraid** [comment]
> Here are my $0.02 from a user perspective: I think the current devel behavior of skipping the compression with an error message is good, but a command line flag should be introduced to optionally compress and strip the CFG supported flag instead.

This is not enough for the compressed file to run.

**Comment by splitbrain** [comment]
Oh. I guess then I misunderstood the explanations above. sorry for the noise.
