### ISSUE TITLE
code analysis

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#21]
[src\stub\src\i386-linux.elf-main.c:557] -> [src\stub\src\i386-linux.elf-main.c:653]: (warning) Either the condition '0!=p_reloc' is redundant or there is possible null pointer dereference: p_reloc.
[src\stub\src\i386-linux.elf.interp-main.c:281]: (error) Analysis failed. If the code is valid then please report this failure.
[src\stub\src\arch\i086\l_test.c:95]: (error) Memory leak: s

**Comment by markus-oberhumer** [comment]
In case you want to contibute please provide patches for the "devel" branch. Closing.
