### ISSUE TITLE
Can upx support so implicit calling?

### ISSUE THREAD

**Issue by pcheng74** [upx/upx#210]
## What's the problem (or question)?

I found compressed so can't be loaded by implicit calling on Linux. And it can work with explicit calling only. 
## What should have happened?

Can upx support so implicit calling?

## Do you have an idea for a solution?

I want to support so implicit calling even after so is compressed by upx.

## How can we reproduce the issue?

1. so sample
/*mylib.c*/
#include <stdio.h>
#include "mylib.h"

void Print()
{
    printf("This is in mylib\n");
}

gcc -fpic -shared mylib.c -o mylib.so

2. loader sample
#include <stdio.h>
#include "mylib.h"

int main()
{
    Print();
}

gcc -o main main.c -L./ mylib.so

3. ~/dll_sample$ ./upx mylib.so
4. export LD_LIBRARY_PATH=./ 
5. ~/dll_sample$ ./main
./main: error while loading shared libraries: mylib.so: ELF load command address/offset not properly aligned

## Please tell us details about your environment.

* UPX version used (`upx --version`): latest Linux upx 3.94
* Host Operating System and version: 14.04.1-Ubuntu 64-bit 
* Host CPU architecture: X64
* Target Operating System and version:  14.04.1-Ubuntu 64-bit 
* Target CPU architecture:  X64

**Comment by jreiser** [comment]
If mylib.so cannot be uploaded for some reason, then please report the output from <tt>readelf --segments mylib.so</tt> both before and after compression by upx.  When pasting the output into a github Comment dialog, then place a line with three backticks (character code hex 0x60, decimal 96, octal 0140; often found on a key to the left of the numeral '1') both before and after the text.  That will make the output look nice in github.

**Comment by pcheng74** [comment]
@jreiser , I attached the sample code, and the exact steps as below.

$export LD_LIBRARY_PATH=./ 
$gcc -fpic -shared mylib.c -o mylib.so
$ ./upx mylib.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.94        Markus Oberhumer, Laszlo Molnar & John Reiser   May 12th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    417699 ->      8284    1.98%   linux/amd64   mylib.so                      

Packed 1 file.


### $ gcc -o main main.c -L. ./mylib.so

/tmp/ccW7CjU6.o: In function `main':
main.c:(.text+0xa): undefined reference to `Print'
collect2: error: ld returned 1 exit status

----------------------------------------------------------------------------------------------
When I build main to call so implicitly, it will return the error. I assume symbol can't be found during building process because I run nm to list the symbol as below, it will return "no symbols" found.

$ nm mylib.so
nm: mylib.so: no symbols

If I use dlopen to load the compressed so, and it can work successfully.



[demo.zip](https://github.com/upx/upx/files/2260118/demo.zip)

**Comment by jreiser** [comment]
Please upload your mylib.so which is produced by <tt>gcc -fpic -shared mylib.c -o mylib.so</tt>.  I get:
```
$ gcc -fpic -shared mylib.c -o mylib.so

$ ls -l mylib.so
-rwxrwxr-x. 1 jreiser jreiser 7816 Aug  5 06:37 mylib.so

$ size mylib.so
   text	   data	    bss	    dec	    hex	filename
   1239	    544	      8	   1791	    6ff	mylib.so

$ readelf --segments mylib.so

Elf file type is DYN (Shared object file)
Entry point 0x550
There are 7 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000000006bc 0x00000000000006bc  R E    0x200000
  LOAD           0x0000000000000e08 0x0000000000200e08 0x0000000000200e08
                 0x0000000000000220 0x0000000000000228  RW     0x200000
  DYNAMIC        0x0000000000000e20 0x0000000000200e20 0x0000000000200e20
                 0x00000000000001c0 0x00000000000001c0  RW     0x8
  NOTE           0x00000000000001c8 0x00000000000001c8 0x00000000000001c8
                 0x0000000000000024 0x0000000000000024  R      0x4
  GNU_EH_FRAME   0x0000000000000638 0x0000000000000638 0x0000000000000638
                 0x000000000000001c 0x000000000000001c  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x0000000000000e08 0x0000000000200e08 0x0000000000200e08
                 0x00000000000001f8 0x00000000000001f8  R      0x1

 Section to Segment mapping:
  Segment Sections...
   00     .note.gnu.build-id .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .text .fini .rodata .eh_frame_hdr .eh_frame 
   01     .init_array .fini_array .data.rel.ro .dynamic .got .got.plt .bss 
   02     .dynamic 
   03     .note.gnu.build-id 
   04     .eh_frame_hdr 
   05     
   06     .init_array .fini_array .data.rel.ro .dynamic .got 
```
which is very much smaller than the 417699 bytes that you get.

**Comment by pcheng74** [comment]
[mylib.zip](https://github.com/upx/upx/files/2260409/mylib.zip)
@jreiser Please see attached file.

**Comment by jreiser** [comment]
The size difference arises because mylib.c from demo.zip contains
```
const unsigned int  test[102400] = { 1};

int returnTest(int i)
{
 if (i >= 10240)
   return -1;

  return test[i];
}

```
which was not in the original description.  But with the array <tt>test[102400]</tt> then upx will compress mylib.so.

After compression of mylib.so, then <tt>gcc -o main main.c -L. ./mylib.so</tt> will draw a complaint from the link step.  This is because upx compresses the information in the <i>linking view</i> of mylib.so.  The linking view is not needed during execution, and it occupies more space if left uncompressed.  The compressed linking view could be discarded (nothing from the linking view is needed during execution), but then <tt>upx -d</tt> would not be able to reconstruct the original input.

In order to link with a shared library after it has been compressed, then the linker must have access to the uncompressed linking view.  So, uncompress the shared library before linking: <tt>upx -d mylib.so</tt>.  Or, keep a copy of the uncompressed shared library in a separate directory DIR, and use the flag <tt>-W,-l,-rpath-link=DIR</tt> when building <tt>main</tt>.  See the documentation <tt>info ld</tt> about <tt>-rpath-link</tt>.

**Comment by pcheng74** [comment]
@jreiser,

Thanks for your detailed information.
I can understand this reason right now. Please close this issue.

Thanks,
