### ISSUE TITLE
virtual int InputFile::readx(MemBuffer*, int): Assertion `(unsigned)len <= buf->getSize()' failed.

### ISSUE THREAD

**Issue by SailZhang** [upx/upx#211]
## What's the problem (or question)?

when use : ./upx.out libnet.so

the error message:
upx: ../../../src/file.cpp:274: virtual int InputFile::readx(MemBuffer*, int): Assertion `(unsigned)len <= buf->getSize()' failed.

I try to add a log on line 274. 

"
len 1096048 , buflen 1096048
len 1096048 , buflen 1096048
len 1096048 , buflen 1096048
len 1096048 , buflen 1096048
len 1096048 , buflen 1096048
len 393216 , buflen 1096048
len 340 , buflen 340
len -1016 , buflen 1096048
"

Dynamic library has error ?

## Please tell us details about your environment.

* UPX version used (`upx --version`): linux upx-3.94
* Host Operating System and version:Ubuntu 16.04 LTS
* Host CPU architecture:x64
* Target Operating System and version:Ubuntu 16.04 LTS
* Target CPU architecture:x64

**Comment by jreiser** [comment]
Please try the <tt>devel</tt> branch, which has many fixes.  If that still does not work, then please upload libnet.so ("Attach files by ..." at the bottom of a Comment entry box), or otherwise give the URL for libnet.so, etc.  I could not find libnet.so on my Ubuntu 16.04.5 system.

**Comment by SailZhang** [comment]
thanks , it works well at devel @jreiser
