### ISSUE TITLE
Packing fails with CantPackException: mem_size 2 on the linked dll

### ISSUE THREAD

**Issue by SwooshyCueb** [upx/upx#213]
## What's the problem (or question)?

When running upx on the dll linked below, I get the error `CantPackException: mem_size 2; take care`.

This is the `cudafilters` module from a build of OpenCV 3.4.1 with several CUDA architectures enabled, so it's rather large:  
https://filedump.swooshalicio.us/tmp-upx/opencv_cudafilters341.dll

## What should have happened?

As with the rest of the modules from this build of OpenCV, it should've packed properly.

## Do you have an idea for a solution?

The error appears to be the result of a buffer size assertion to prevent integer overflows (`util.cpp`). Maybe use (u)int64 everywhere so these values can be raised?

## How can we reproduce the issue?

1. Download the dll.
2. Try to pack it with UPX. (i.e. `upx --best -o opencv_cudafilters341.upx.dll opencv_cudafilters341.dll`)

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94 (the prebuilt versions from the github releases tab)
* Host Operating System and version: Tried on both Windows 7 SP1 and Ubuntu MATE 18.04.
* Host CPU architecture: x86_64 (though I think the Windows upx binary was x86)
* Target Operating System and version: Windows 7+
* Target CPU architecture: x86_64

**Comment by Mattiwatti** [comment]
There is [a line in src/conf.h](https://github.com/upx/upx/blob/d9288213ec156dffc435566b9d393d23e87c6914/src/conf.h#L168)...
```C++
#define UPX_RSIZE_MAX_MEM (768 * 1024 * 1024) // DO NOT CHANGE
```
I speculate that, if you were to change this to twice the current value, your DLL would compress with no errors and a compression ratio of ~6%. But since the line clearly says 'DO NOT CHANGE', I didn't dare to try this and it is merely a thought experiment... ;)

PS. This thought experiment occurred using a 64 bit UPX compiled from the current `devel` branch. I'm not so sure whether a 32 bit exe would be up to the task.

**Comment by jreiser** [comment]
Part of the reason for the limit is that <i>packing</i> requires space for boh uncompressed and compressed images, as well as overhead.  Also, UPX wants to be cross-platform on all machines, even 32-bit machines that have a limit of 2GB user data.

There was a similar issue in the past.  IIRC  an experiment was successful in raising the limit to the very low 900MB range before some other constraint triggers; but UPX will stick with 768MB.

An executable as big as 900MB really is too big.  Split it into a few pieces, or put the compression inside the program as an explicit programmer-controlled feature.

**Comment by SwooshyCueb** [comment]
The library in question is 434MB, well below the 768MB and 900MB figures you mentioned.

**Comment by jreiser** [comment]
It is exceedingly convenient to require that both the entire input file and the compressed output be present in the memory space at the same time.  Like all loss-less compressors, there are some inputs that get expanded; in upx the worst case is by a factor of 9/8. Then the compressor requires working storage, such as a hash table to aid in finding matching substrings efficiently.  Look in util.cpp:
```
ACC_COMPILE_TIME_ASSERT_HEADER(2ull * UPX_RSIZE_MAX * 9 / 8 + 16 * 1024 * 1024 < INT_MAX)
```
which does a static check, and at subroutine <tt>mem_size()</tt> which does a dynamic check.  Upx also wants be universally cross-platform; this includes running on 32-bit machines, some of which allow only 2GB of user address space.

You are welcome to experiment and submit patches.

**Comment by markus-oberhumer** [comment]
Does this DLL have a huge BSS segment?

**Comment by jreiser** [comment]
@markus-oberhumer According to the PE file analyzer application Cerbero PE Insider 1.0.2, the file opencv_cudafilters341.dll contains 0x68a800 bytes of Code, 0x1ab27a00 bytes of Initialized data, and 0x0 bytes of Uninitialized data.  So: no, the BSS segment is not huge; it is empty.

**Comment by necros2k7** [comment]
+1 , same error while compressing eduke32.exe (https://dukeworld.com/eduke32/synthesis/latest/eduke32_win64_20190518-7657.7z )

**Comment by SwooshyCueb** [comment]
go away stalebot. you completely defeat the purpose of giving a :+1: to the issue.

**Comment by markus-oberhumer** [comment]
Neither  `wget https://filedump.swooshalicio.us/tmp-upx/opencv_cudafilters341.dll` nor
`wget https://dukeworld.com/eduke32/synthesis/latest/eduke32_win64_20190518-7657.7z` works for me.

Please open a new issue if you hit that problem again.
