### ISSUE TITLE
 upx 3.95-git-b711d2f750d3 

### ISSUE THREAD

**Issue by xautzbl** [upx/upx#214]
## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
What is the Issue, the problem (or question)?

**Comment by jreiser** [comment]
Closing: no content.
