### ISSUE TITLE
3.95 crashes on MacOS Assertion failed: ((unsigned)len <= buf->getSize()), function readx, file file.cpp, line 276.

### ISSUE THREAD

**Issue by javian** [upx/upx#218]
## What's the problem (or question)?

upx compiles just fine but fails to execute but fails to run the test method outlined here in the Homebrew package manager https://github.com/Homebrew/homebrew-core/blob/master/Formula/upx.rb . The error occurs when it tries to decompress a binary.

We noticed the error in the Homebrew package manager repo since the error occurred in the CI test of the submission for the update to 3.95 patch https://github.com/Homebrew/homebrew-core/pull/31660/files and the test worked fine on with 3.94 .

upx -d php
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

File size         Ratio      Format      Name
`--------------------   ------   -----------   -----------`
Assertion failed: ((unsigned)len <= buf->getSize()), function readx, file file.cpp, line 276.

I can also reproduce it locally by compressing a binary and the decompressing it again which produces the crash. I found #211 which looked similar but also indicated that the issue would be fixed by the time of the 3.95 release.

## What should have happened?
The decompression should work without any issues.

## Do you have an idea for a solution?
No

## How can we reproduce the issue?
1. Compile on MacOS
2. Compress a binary
3. Decompress the same binary
4. Crash

## Please tell us details about your environment.

* UPX version used (`upx --version`):
➜  Trash upx --version
upx 3.95
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
Copyright (C) 1996-2018 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2018 Laszlo Molnar
Copyright (C) 2000-2018 John F. Reiser
Copyright (C) 2002-2018 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
* Host Operating System and version:
MacOS 10.13.6
* Host CPU architecture:
CPU: quad-core 64-bit sandybridge
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
See the fix in https://github.com/upx/upx/commit/0dac6b7be3339ac73051d40ed4d268cd2bb0dc7c above.  For how, you must start over and re-compress first.

**Comment by javian** [comment]
This seems to have solved the issue but another might have popped up on El Capitan, will see if we can submit a new report on that issue specifically.

**Comment by jreiser** [comment]
Thank you for testing.  As you investigate on El Capitan, please try upx on /bin/date, and upload that here ("Attach files by ...") if it fails.  I no longer have a system running El Capitan.

**Comment by jreiser** [comment]
Please test again; thanks.

**Comment by julian7** [comment]
It is reproducable on linux too, with a binary brought from a mac. The same thing works well on previous version:

```
js@mooo:~/tmp % curl -L https://github.com/upx/upx/releases/download/v3.94/upx-3.94-amd64_linux.tar.xz | tar xJf -
js@mooo:~/tmp % curl -L https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz | tar xJf -
js@mooo:~/tmp % upx-3.95-amd64_linux/upx -o date-hsierra-3.95 ~/date-hsierra
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
     28592 ->     16400   57.36%   macho/amd64   3.95-date

Packed 1 file.
js@mooo:~/tmp % upx-3.95-amd64_linux/upx -d date-hsierra-3.95
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.94        Markus Oberhumer, Laszlo Molnar & John Reiser   May 12th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: ../../../src/file.cpp:274: virtual int InputFile::readx(MemBuffer*, int): Assertion `(unsigned)len <= buf->getSize()' failed.
zsh: abort      ./upx-3.94-amd64_linux/upx -d 3.95-date
js@mooo:~/tmp % upx-3.94-amd64_linux/upx -o date-hsierra-3.94 ~/date-hsierra
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.94        Markus Oberhumer, Laszlo Molnar & John Reiser   May 12th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
     28592 ->     17000   59.46%   macho/amd64   date-hsierra-3.94

Packed 1 file.
js@mooo:~/tmp % upx-3.94-amd64_linux/upx -d date-hsierra-3.94
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.94        Markus Oberhumer, Laszlo Molnar & John Reiser   May 12th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
     28592 <-     17000   59.46%   macho/amd64   date-hsierra-3.94

Unpacked 1 file.
```

Also look at the binary file differences.

On the mac though, while I'm getting good results for /bin/date, my darwin go-compiled (1.11) binary got corrupted (I've tested with that executable off-camera on linux, and it produced the same results as High Sierra's /bin/date).

```
js@my mac:~ % upx -o awsentlogin .../target/awsentlogin-darwin-amd64-v0.2.0-7-g8930d2f
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  12598620 ->   4608016   36.58%   macho/amd64   awsentlogin

Packed 1 file.
js@my mac:~ % ./awsentlogin
zsh: killed     ./awsentlogin
js@my mac:~ % upx -d ./awsentlogin
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: ./awsentlogin: CantUnpackException: file corrupted

Unpacked 0 files.
uname -a
js@my mac:~ % Darwin my_mac 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64
```

**Comment by jreiser** [comment]
Works for me using https://github.com/upx/upx/commit/9bb6854e642a2505102b9d3f9ec8535ec8ab6d9c from the <tt>devel</tt> branch of 16 days ago, or any later version.

**Comment by julian7** [comment]
@jreiser good for you. I installed upx @3.95 using homebrew onto Mojave, which is already containing this patch, and it fails miserably for me when compressing my go-compiled binaries.

**Comment by jreiser** [comment]
The tag v3.95 for upx-3.95 refers to commit 7a3637ff5a800b8bcbad20ae7f668d8c8449b014 of Aug.26.
Commit 9bb6854e642a2505102b9d3f9ec8535ec8ab6d9c of Sept.9, "Fix stub for MacOS El Capitan..." is the one I referred to on 5 days go on Sept.25.  Current tip 37d6a34e5867b288bf1cc27616ca479272fb13f4 of <tt>devel</tt> branch also works for me on MacOS El Capitan, Sierra, High Sierra, and Mojave.

**Comment by julian7** [comment]
@jreiser tested and confirmed :) there is still a test and decode error (reporting `CantUnpackException: corrupt b_info`), but compressed binaries run flawlessly.

**Comment by afwn90cj93201nixr2e1re** [comment]
same with 3.96

**Comment by jreiser** [comment]
@afwn90cj93201nixr2e1re Please upload ("Attach files by ...") an actual executable file which triggers the complaint; compress the upload using zip, gzip, or .tgz to save space on Github.  Or, give the URL; or, specify a pathname on current MacOS (Mojave) which triggers the problem. The point is: I need a `specific, actual` testcase.

**Comment by afwn90cj93201nixr2e1re** [comment]
btw it triggers on linux debian 8/10 amd64, i found this thread on google.

[testsuite.zip](https://github.com/upx/upx/files/4142173/testsuite.zip)


If you need sourcecode i can send it to email.

**Comment by afwn90cj93201nixr2e1re** [comment]
[version_script.zip](https://github.com/upx/upx/files/4142175/version_script.zip)

**Comment by afwn90cj93201nixr2e1re** [comment]
```
./upx -l test_i386.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: test_i386.so: NotPackedException: not packed by UPX


./upx -9 test_i386.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
test_i386.so  7/9  [*********************************************]   40.3%  /      34408 ->     24204   70.34%   linux/i386    test_i386.so

Packed 1 file.

./upx -d test_i386.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: test_i386.so: NotPackedException: not packed by UPX

Unpacked 0 files.






./upx --best test_i386.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
test_i386.so  7/9  [*********************************************]   40.3%  /      34408 ->     24204   70.34%   linux/i386    test_i386.so

Packed 1 file.

./upx -d test_i386.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: test_i386.so: NotPackedException: not packed by UPX

Unpacked 0 files.
```
As you can see it pack it only with --best option and can't with -9

**Comment by afwn90cj93201nixr2e1re** [comment]
Also if you wanna i compiled it without optimization and with full debug.
[test_i386.zip](https://github.com/upx/upx/files/4142267/test_i386.zip)

**Comment by afwn90cj93201nixr2e1re** [comment]
Also if you wanna i compiled it without optimization and with full debug.
[test_i386.zip](https://github.com/upx/upx/files/4142269/test_i386.zip)


And it's also doesnt pack it, idk why.

https://hastebin.com/idayurodin.cpp

**Comment by afwn90cj93201nixr2e1re** [comment]
Also if you wanna i compiled it without optimization and with full debug.
[test_i386.zip](https://github.com/upx/upx/files/4142269/test_i386.zip)


And it's also doesnt pack it, idk why.

https://hastebin.com/idayurodin.cpp

@jreiser

**Comment by jreiser** [comment]
@afwn90cj93201nixr2e1re The problem with i386 ELF shared library is not related to this #218 for MachO executables.  ELF format is totally different than MachO.  Please direct all comments to #341.

**Comment by afwn90cj93201nixr2e1re** [comment]
@jreiser that's crazy, i posted files to 'dead' issue for privatly ;(
ok, im gonna try to create new one file, wait.

**Comment by 6a7070** [comment]
I'm still interested in decompressing a upx-packed MachO file. The file was compressed with v.3.95 and unfortunately I'm unable to decompress it with v3.94, v3.95, or v3.96. Is there an alternative solution or manual approach I can use to decompress the file?

**Comment by jreiser** [comment]
In the file src/p_mach.cpp there are 5 reasons for "file header corrupted"; figure out which one applies, and why.  In src/Makefile, set `BUILD_TYPE_DEBUG    ?= 1` then rebuild.  Run under a debugger such as lldb; plant breakpoints; trigger one of them, look at the `if` conditions.
Using the Mac X-code tool `otool -hl ./my_app` (on both the compressed and the never-compressed program) might provide other clues.
