### ISSUE TITLE
MacOs Sierra- can't install

### ISSUE THREAD

**Issue by dlewand691** [upx/upx#22]
## What's the problem (or question)?

Trying to install UPX on MacOs Sierra (10.12.1) and getting the error:

`upx: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.`

Brew is installed, updated, and doctored.

## What should have happened?

Should have installed UPX

## Do you have an idea for a solution?

Update to work with Sierra?

## How can we reproduce the issue?

1.
2.
3.
4.

## Help us understand your issue by providing context.

Trying to run UPX on an app patcher file. 

## Please tell us details about your environment.

* UPX version used (`upx --version`): none
* Operating System and version: Macos 10.12.1
* CPU architecture:

**Comment by tsamu** [comment]
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/upx.rb
depends_on MaximumMacOSRequirement => :el_capitan

sierra/upx 3.91 has this issue https://github.com/upx/upx/issues/4 so wait for upx 3.92 (or build from source)

**Comment by markus-oberhumer** [comment]
Please report this issue to the Homebrew team. Closing.

**Comment by sephethus** [comment]
Where are the installation instructions to install this from the github files instead of brew?

**Comment by legentz** [comment]
Same problem... Can't install via brew.

I'm currently using Mac Os Sierra 10.12.1 and I got upx working doing as follows:
- download upx compressed file
- before doing anything, install ucl via brew
- cd into upx src folder
- type "make" inside the terminal and wait for it to finish the process
- type "ls -la" inside the terminal to see upx.out (that's the compiled binary!) 

You can use it as ./upx.out
