### ISSUE TITLE
upx output of binary 'go' file can not run on macOS

### ISSUE THREAD

**Issue by hr3lxphr6j** [upx/upx#222]
## What's the problem (or question)?
upx output binary file can not run on macOS

## What should have happened?
```go
package main

import "fmt"

func main() {
	fmt.Println("Hello World")
}
```

```shell
$ go build go-test.go

$ ./go-test
Hello World

$ upx go-test
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   2003464 ->   1007632   50.29%   macho/amd64   go-test

Packed 1 file.

$ ./go-test
[1]    9461 killed     ./go-test
```

## Please tell us details about your environment.
* UPX version used (`upx --version`):
    ```
    upx 3.95
    UCL data compression library 1.03
    zlib data compression library 1.2.11
    LZMA SDK version 4.43
    ```
* Host Operating System and version: `macOS High Sierra 10.13.6`
* Host CPU architecture: `x86_64`
* Target Operating System and version: `macOS High Sierra 10.13.6`
* Target CPU architecture: `x86_64`

**Comment by joshdk** [comment]
I can confirm that I am also seeing this issue. It appears to be an issue with the [official 3.95 release](https://github.com/upx/upx/releases/tag/v3.95), as I do **not** see the failure using the [official 3.94 release](https://github.com/upx/upx/releases/tag/v3.94).

To reproduce I built a simple Docker image (using the following Dockerfile with `macos$ docker build -t upx-macos-repro .`) that installs the 3.94 and 3.95 UPX releases:

```dockerfile
FROM golang:1.10.4

RUN apt update \
 && apt install xz-utils \
 && cd /tmp \
 && wget --quiet https://github.com/upx/upx/releases/download/v3.94/upx-3.94-amd64_linux.tar.xz \
 && wget --quiet https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz \
 && tar -xf upx-3.94-amd64_linux.tar.xz \
 && tar -xf upx-3.95-amd64_linux.tar.xz
```

I then ran the image with:

```
macos$ docker run --rm -it \
  -v $PWD:$PWD -w $PWD \
  upx-macos-repro:latest
```

Inside the image, I compiled and compressed test binaries using both releases:

```
root# ls -lh
total 8.0K
-rw-r--r-- 1 root root 356 Sep 19 01:18 Dockerfile
-rw-r--r-- 1 root root  72 Sep 19 01:03 main.go

root# GOOS=darwin GOARCH=amd64 go build -o hello .

root# ls -lh
total 2.0M
-rw-r--r-- 1 root root  356 Sep 19 01:18 Dockerfile
-rwxr-xr-x 1 root root 2.0M Sep 19 01:25 hello
-rw-r--r-- 1 root root   72 Sep 19 01:03 main.go

root# cp hello hello-3.94

root# cp hello hello-3.95

root# ls -lh
total 6.0M
-rw-r--r-- 1 root root  356 Sep 19 01:18 Dockerfile
-rwxr-xr-x 1 root root 2.0M Sep 19 01:25 hello
-rwxr-xr-x 1 root root 2.0M Sep 19 01:25 hello-3.94
-rwxr-xr-x 1 root root 2.0M Sep 19 01:25 hello-3.95
-rw-r--r-- 1 root root   72 Sep 19 01:03 main.go

root# /tmp/upx-3.94-amd64_linux/upx hello-3.94
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.94        Markus Oberhumer, Laszlo Molnar & John Reiser   May 12th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   2085008 ->    696976   33.43%   macho/amd64   hello-3.94

Packed 1 file.

root# /tmp/upx-3.95-amd64_linux/upx hello-3.95
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   2085008 ->    696336   33.40%   macho/amd64   hello-3.95

Packed 1 file.

root# ls -lh
total 3.5M
-rw-r--r-- 1 root root  356 Sep 19 01:18 Dockerfile
-rwxr-xr-x 1 root root 2.0M Sep 19 01:25 hello
-rwxr-xr-x 1 root root 681K Sep 19 01:25 hello-3.94
-rwxr-xr-x 1 root root 681K Sep 19 01:25 hello-3.95
-rw-r--r-- 1 root root   72 Sep 19 01:03 main.go

root# sha256sum --binary --tag hello*
SHA256 (hello) = 4a15193351665d4acf528b01c8edd6e486e4ae8867c890e2c0514b679351159f
SHA256 (hello-3.94) = 0cbaf0a47d94ffb7f1680b8a4a5525ce8bc645842cf31fa1cc57a0b40ad88b38
SHA256 (hello-3.95) = 9c8dc585c0ac84af66b19561111cd4a81cd64e4a59eb83adcc2b3382910e0b15
```

After exiting the image, I then ran the original and compressed binaries, resulting in the execution failure:

```
macos$ ./hello
Hello World
macos$ ./hello-3.94
Hello World
macos$ ./hello-3.95
Killed: 9
```

Additionally, I have bundled all of these files together and uploaded them in [repro.tar.gz](https://github.com/upx/upx/files/2395092/repro.tar.gz).

Thank you all for the hard work on this amazing project!
Cheers!

**Comment by jreiser** [comment]
The tip of <tt>devel</tt> branch, 37d6a34e5867b288bf1cc27616ca479272fb13f4, works for me; also tested on Mojave.  A compiled version for Linux is available beginning at the upx-automatic-builds page as: https://github.com/upx/upx-automatic-builds/blob/devel-20180924-37d6a34-travis/amd64-linux-gcc-8-release/upx-git-37d6a34e5867.out .

**Comment by jreiser** [comment]
The tip of <tt>devel</tt> branch fixes <tt>upx -d</tt> for such 'rust' executables.

**Comment by hairyhenderson** [comment]
@jreiser is there any timeline on a UPX release with this fix?

**Comment by jreiser** [comment]
@tammersaleh See the comment https://github.com/upx/upx/issues/222#issuecomment-425749652 of Sep.30.  I'll bet you can figure out how to get the version which runs on amd64-darwin.

**Comment by hairyhenderson** [comment]
@jreiser is there anything blocking a 3.96 release with this fix? Is there anything we can do to help this along?

**Comment by jreiser** [comment]
@hairyhenderson 
1. Post a Comment that "I tried commit #... [paste the 40-character commit ID, which github will turn into a link] from ... [give the download link, or say how you created the executable of upx itself].  The output from upx compression worked for me in this case, and <tt>upx -d</tt> decompression restored the original file."  The experience of UPX Team is that not enough users actually <i>try</i> the development versions.  Posting reproducible issues is a big help that is made even more valuable when real users verify developer fixes <b>before</b> a release.
See the comment https://github.com/upx/upx/issues/222#issuecomment-425749652 for an example of pre-built executable of upx.  Or use homebrew, or borrow a Linux box.
2. If part 1 works, then why aren't you happy?  Oh, you say that some other entire project wants to use upx?  Then have 1 or 2 others from that project chime in, "I tried commit #..., it works for me."
3. Making a release is not an automated process.  There are 6 or 7 different hardware+OS combinations which must be tested to verify hand-written assembly language decompressors.  Virtualization is not available for some of them, so real hardware must be employed.
4. Markus is the only one who can make an official release.  The NRV match finder+selector is not open source.  The UCL implementation is compatible but with slightly less compression.  Almost any worthwhile real executable will be smaller if compressed with LZMA, but LZMA decompression takes around 10 times long [still reasonably fast] and about 10 times the energy (a multiply operation for every bit).
5. $DAYJOB often has priority.

**Comment by hairyhenderson** [comment]
Thanks for the quick response @jreiser. I'll try to find some time to test the fix.

I can imagine that it's a complex project to deal with, given all the different platforms you support! I'm not trying to complain or rush things, and I totally understand priority pressures. It just wasn't clear to me where this stood. Now it is, and I thank you for the clarity!

**Comment by hairyhenderson** [comment]
Ok, I've used `brew install --HEAD upx` to build 473b90419f68, and I've compressed a Go program (gomplate) with it, then decompressed (with `upx -d`), and it looks good to me ✅:

```console
$ sha256sum bin/*
5b7a8474260b3ed09884afb0b798aa0e710cfa42b17b1dcff92e77bb38207c21  bin/gomplate_darwin-amd64 # original
dd30fde418e918dca38764d72821bb32cbe5a8836adac8412c68a61b6e9bfb19  bin/gomplate_darwin-amd64-slim # compressed
5b7a8474260b3ed09884afb0b798aa0e710cfa42b17b1dcff92e77bb38207c21  bin/gomplate_darwin-amd64-slim-decompressed # decompressed
```

and the compressed executable works:

```console
$ bin/gomplate_darwin-amd64-slim -i '{{ print "it works!" }}'
it works!
```

Perhaps some others can verify as well?

**Comment by hairyhenderson** [comment]
Thanks @grtfou!

**Comment by hairyhenderson** [comment]
@jreiser @markus-oberhumer - it looks like at least 2 more (myself and @grtfou) have confirmed the fix. I'll try to see if I can find more if you need more broad testing.

Also @hackmac89 - I see you 👍d my comment - does that mean you can also verify the fix? Can you do so in writing? 🙂

**Comment by geocine** [comment]
@hairyhenderson I can confirm , your comment is working. I uninstalled 3.95 and installed HEAD

**Comment by zhanhb** [comment]
On macos amd64, upx seems to be broken to process macho/i386 binary
```
wget -O- https://github.com/xtaci/kcptun/releases/download/v20181114/kcptun-darwin-386-20181114.tar.gz | tar -zxf -
upx client_darwin_386
./client_darwin_386
```
I got as the following:
`Segmentation fault: 11`

**Comment by hackmac89** [comment]
@hairyhenderson yep, can confirm it´s working.

**Comment by fxcoudert** [comment]
@markus-oberhumer could a 3.96 release be cut? While shipping `upx` in Homebrew we are seeing the number of necessary patches accumulate (4 patches now) to make the software work.

**Comment by markus-oberhumer** [comment]
Yeah, a new release is probably a good idea. Should happen soon.

**Comment by jreiser** [comment]
Fix confirmed by @hairyhenderson and others.  Markus has indicated v3.96 release "soon".

**Comment by hairyhenderson** [comment]
Thank you @jreiser and @markus-oberhumer! Looking forward to the release 😬

**Comment by philippgille** [comment]
I'm also looking forward to an official release with the fix. I learned today that a side project of mine is affected by this, leading to a macOS user not being able to run my released CLI tool. I use UPX in Travis CI with `apt-get`,  AppVeyor with `choco install upx` and on my local machine with `scoop install upx`, where all are bound to official releases afaik.

Great work on UPX though! In my case it reduces the CLI tool's size from 6.2 MB to 1.8 MB.

**Comment by homme** [comment]
I've just experienced this issue in the wild, so also looking forward to a 3.96 release, thanks!

**Comment by gonejack** [comment]
Still meeting the same on MacOS with go 1.14.

**Comment by jicdude** [comment]
Same issue here

**Comment by sc0Vu** [comment]
UPX compressed binary still not work on MacOS with UPX 3.96 go 1.14. But thanke @hairyhenderson -d works for me!

**Comment by hairyhenderson** [comment]
@sc0Vu which Go release are you using? I had issues with 1.14.0 + upx 3.96, but 1.14.2 + uxp 3.96 _seems_ to be working OK for me...

Also given that this particular issue is closed, perhaps you should open a new one? (Same goes for @gonejack and @jicdude)

**Comment by steeve** [comment]
Same issue, 3.96 and HEAD are broken for my Go 1.14 + CGo + C++ program, 3.94 is fine.

A pure Go binary runs ok.

**Comment by jreiser** [comment]
@steeve If you want to pursue this, then please upload ("Attach files by ...") an actual executable that fails when compressed by UPX.  Compress the upload using gzip, zip, or .tgz to save space on Github.  Or, provide a link so that the executable can be fetched from somewhere on the 'net.

**Comment by steeve** [comment]
Thanks @jreiser!

**Comment by steeve** [comment]
@jreiser here you go! https://send.firefox.com/download/594c08e0cd92320f/#52Y12jN8cXd3firimbIuSg

**Comment by steeve** [comment]
Just ran a bisect, and it found this commit: 4f6979967d8a4396a32fcdb69f5f74547fb7108a.

**Comment by gonejack** [comment]
@hairyhenderson it works for me too now, after go upgraded to 1.14.3 while upx is still at 3.96

**Comment by jicdude** [comment]
I have the same issue but with Lazarus IDE 2.0.8 x86_64.
Any suggestions how to downgrade upx on Mac to 3.94 using homebrew?

**Comment by steeve** [comment]
> Any suggestions how to downgrade upx on Mac to 3.94 using homebrew?

You can do that:
```
brew uninstall upx
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/b1f92701367028062abb3518426aa5d8dacc224b/Formula/upx.rb
```

**Comment by jicdude** [comment]
Thanks @steeve, I can now compress again with version 3.94 :)

**Comment by jicdude** [comment]
> > Any suggestions how to downgrade upx on Mac to 3.94 using homebrew?
> 
> You can do that:
> 
> ```
> brew uninstall upx
> brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/b1f92701367028062abb3518426aa5d8dacc224b/Formula/upx.rb
> ```

@steeve Is there a way to test different versions, ex: 3.9.5, I can't seem to find a list of formulas for upx ?

**Comment by steeve** [comment]
You could find the history at https://github.com/Homebrew/homebrew-core/commits/master/Formula/upx.rb

You can look for the affect commit: https://github.com/upx/upx/issues/222#issuecomment-635330482

**Comment by KempWatson** [comment]
Where is v3.96 for Mac OS? I don't see it in the downloads in GitHub? Thanks!

**Comment by jreiser** [comment]
> @KempWatson  That's right, there are no pre-built executables of UPX for MacOS listed on https://github.com/upx/upx/releases because there are no free (as in beer) public build environments for MacOS like there are for Linux and MSWindows.  This is due  to Apple's licensing policies.  Various users have reported success building UPX using `brew`; search the internet for examples.  (Or, because UPX is universally cross-platform [any UPX on any platform can compress for _every_ supported executable file format] then use any Linux or WIndows machine to do the compression.)

**Comment by jph00** [comment]
@jreiser GitHub Actions provides a free public build environment for MacOS, Linux, and MSWindows.

**Comment by dimitarvp** [comment]
On macOS Big Sur 11.1:

Tried using an older version via the methods specified above and figured I'll try the last version (`3.95_1`) but...

> /usr/local/Homebrew/Library/Homebrew/formulary.rb:227:in `load_file': Invalid usage: Installation of upx from a GitHub commit URL is unsupported! 'brew extract upx' to stable tap on GitHub instead. (UsageError)

Current version (`3.96`) produces binaries that display `Killed` when started still.

**Comment by dimitarvp** [comment]
Haven't tried compiling `upx` from source btw; just did `brew install upx`. Attached at the bottom is a zipped executable file that you can generate yourself (if you have Rust installed) and test like so:

```sh
$ upx --version
upx 3.96
# <extra text snipped>
$ cargo new --bin hello
$ cd hello
$ cargo build --release
$ ./target/release/hello
"Hello, world!"
$ upx --all-methods ./target/release/hello
$ ./target/release/hello
[1]    40004 killed     ./target/release/hello
```
[hello.zip](https://github.com/upx/upx/files/5727227/hello.zip)
