### ISSUE TITLE
UPXed rust binary fails on RaspberryPi 1 (UPX v3.95)

### ISSUE THREAD

**Issue by agherzan** [upx/upx#225]
## What's the problem (or question)?
When running a rust binary compressed with UPX, sometimes, the binary fails to run with exit code 127. We see this on a RapsberryPi 1 board running kernel 4.14.50+. Reproducing this is as simple as running such a rust binary in a loop until it breaks. When that happens, strace logs bad descriptors as it follows:

```
execve("/usr/bin/os-config.upx", ["/usr/bin/os-config.upx", "-h"], 0xbecbddec /* 13 vars */) = 0                                                           
open("/proc/self/exe", O_RDONLY)        = 3                                                                                                                
mmap2(NULL, 1056028, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6bcd000                                                                  
mmap2(0xb6bcd000, 1055153, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0xb6bcd000                                                                 
cacheflush(0xb6cce2c0, 0xb6cced1c, 0, 0xb6cce2c0, 0) = 0                                                                                                   
mprotect(0xb6ccd000, 7452, PROT_READ|PROT_EXEC) = 0                                                                                                        
readlink("/proc/self/exe", "/usr/bin/os-config.upx", 4095) = 22                                                                                            
cacheflush(0xbeefc3bc, 0xbeefc530, 0, 0xbeefc3bc, 0) = 0                                                                                                   
mmap2(NULL, 2736128, PROT_NONE, MAP_FILE, -1, 0) = -1 EBADF (Bad file descriptor)                                                                          
mmap2(0xfffff000, 2633199, PROT_READ|PROT_WRITE, MAP_FILE|MAP_FIXED, -1, 0) = -1 EBADF (Bad file descriptor)                                               
exit(127)                               = ?                                                                                                                
+++ exited with 127 +++
```

This behaviour seems to **not be reproducible** with v3.94 and, as well, with uncompressed binaries.

EDIT: We were able to reproduce the same behaviour on an Odroid C1 board so it doesn't seem to be CPU architecture specific as RaspberyPi 1 is armv6 while Odroid C1 is armv7. And for example, a RaspberryPi 2 doesn't reproduce this issue (which is armv7). 

## What should have happened?
UPX compressed binary should run correctly.

## Do you have an idea for a solution?
Not yet at least.

## How can we reproduce the issue?

1. cross compile a simple rust binary (hello world for example https://doc.rust-lang.org/rust-by-example/hello.html)
2. `upx --best` the hello binary - [hello.zip](https://github.com/upx/upx/files/2456207/hello.zip)
3. run the binary in a loop on RaspberryPi (1) until it breaks with exit code 127: `time while true; do /tmp/hello &> /dev/null; [ "$?" != "0" ] && break; done`

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.95
* Host Operating System and version: Ubuntu 16.04.5 LTS
* Host CPU architecture: x86_64
* Target Operating System and version: Raspbian GNU/Linux 9 (stretch)
* Target CPU architecture: armv6l

**Comment by agherzan** [comment]
Updated the description with a simple rust binary attached.

**Comment by agherzan** [comment]
After some more digging, I got to the conclusion that this is somehow specific to the yocto environment. The same rust, cargo and upx version, used separately on a host doesn't reproduce this issue. So there must be something in the way yocto builds the rust compiler which triggers this issue with UPX. Do you guys see anything obvious with the hello binary I uploaded and attached in the description?

**Comment by jreiser** [comment]
This is a data==>instruction cache consistency problem that was introduced in 3.95.  The fix is somewhat simple and should be ready soon.

**Comment by agherzan** [comment]
@jreiser Good to hear that is something you have under the radar. Do you know at this point if this affects every architecture? Basically, I'm asking if it is by chance that we can't reproduce for x86 or is it only affecting arm?

**Comment by jreiser** [comment]
This problem is only for 32-bit ARM, and arises because mmap() has different MAP_* definitions on QNX  than on Linux.  There is a related problem for machines that have variable page size: mostly MIPS and PowerPC, but not x86 and not x86_64.

**Comment by agherzan** [comment]
That explains it now. Are you aware of any workaround at the moment? Otherwise, I'm thinking of downgrading to 94 for ARM and use 95 only for x86. We were forced to upgrade to 95 due to the fac that x86 had other issues.

**Comment by jreiser** [comment]
There is workaround other than the fix.

**Comment by jreiser** [comment]
Please try the tip of <tt>devel</tt> branch which should fix this issue.  Pre-built binaries for Linux x86_64 should be available shortly under https://github.com/upx/upx-automatic-builds/branches .

**Comment by agherzan** [comment]
Hi @jreiser . I tried initially to only cherry-pick https://github.com/upx/upx/commit/78b1da5c00be6e51b1f01427ca9c4f89cf916634 and it didn't work. it did ameliorate the situation but it still broke after a couple of seconds of looping. Afterwards, I tried successfully, the tip of the develop branch. With that revision, this issue is fixed. Do you plan to have a release soon?

**Comment by cafarm** [comment]
I'm seeing this issue on an x86_64 binary compressed with UPX v3.96. As indicated by @agherzan, you must loop over executing the binary until it breaks exit code 127.

**Comment by jreiser** [comment]
What is the meaning of `loop over executing the binary until it breaks with exit code 127.`?  Can you write some shell code that illustrates?

**Comment by cafarm** [comment]
This is the script I use:

`time while true; do ./my_binary -version &> /dev/null; code="$?"; [ "$code" != "0" ] && echo "$code" && break; done`

It is nearly identical to the one @agherzan posted.

I can also confirm the issue exists in 3.96 and 3.95 but not 3.94.

**Comment by agherzan** [comment]
It looks like an old issue - most probably outdated. Closing for now.
