### ISSUE TITLE
Compressed executable does not run on MIPS target (Onion Omega2+)

### ISSUE THREAD

**Issue by eflukx** [upx/upx#226]
## What's the problem (or question)?

After compressing a linux/mipsel binary (on Linux x86-64 host machine) it does not run on the target machine. It only reports back the error: `Illegal instruction`

The _uncompressed_ binary runs fine on the target machine.

## What should have happened?
The binary should run correctly.

## Do you have an idea for a solution?

Afraid not..

## How can we reproduce the issue?

1. Comile 'trivial source" with (OpenWRT) cross toolchain:
  `rustc --target mipsel-unknown-linux-musl -C linker=mipsel-openwrt-linux-musl-gcc hello.rs`

2. Optionally strip binary `mipsel-openwrt-linux-strip hello`

3. `./upx.out hello`

trivial source (hello.rs): 
```
fn main() {
   println!("Hello World!");
}
```

## Please tell us details about your environment.

* UPX version used (`upx --version`):

Self-built from master

```
$ ./upx.out --version
upx 3.95-git-7a3637ff5a80
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
```

* Host Operating System and version:
Ubuntu 17.10

* Host CPU architecture:
Intel x86-64

* Target Operating System and version:
OpenWRT: `Linux Omega-E555 4.4.153 #0 Sun Sep 16 18:40:20 2018 mips GNU/Linux`

* Target CPU architecture:
```
system type             : MediaTek MT7688 ver:1 eco:2
machine                 : Onion Omega2+
processor               : 0
cpu model               : MIPS 24KEc V5.5
```

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") the <tt>hello</tt> file which failed.  Compress using gzip to <tt>hello.gz</tt> to save space on github.  This will make it much easier to analyze because establishing the toolchain is tedioius.

**Comment by eflukx** [comment]
@jreiser Thanks for your quick response! 
I was having doubts uploading binaries to GH, but here you go! 😄 

[hello-rs.gz](https://github.com/upx/upx/files/2469195/hello-rs.gz)

**Comment by jreiser** [comment]
The file hello-rs is defective.  It is ET_DYN which indicates a shared library unless the DT_FLAGS_1 also contains DF_1_PIE to indicate a Position-Independent-Executable main program.  [Check with <tt>readelf --file-header --dynamic hello-rs</tt>.]  To work around this defect, then use the flag <tt>--force-pie</tt> when invoking upx.
The old accident that a shared library (ET_DYN) also could be run as a main program is incompatible with upx compression.  You must choose either shared library or main program.

**Comment by eflukx** [comment]
Thanks, for clearing this up! Works like a charm now.

About the executable output with the DYN flag: can this be considered a bug in my compiler/tool chain. i.e. would it make sense to file a bug report in the appropriate place?

**Comment by jreiser** [comment]
Yes, I would appreciate it if you would file a bug against the toolchain. Building with -fPIE (or -fpie) should set DF_1_PIE in DT_FLAGS_1.  Thank you.
