### ISSUE TITLE
Building Docker PHP+UPX Alpine image segfaults

### ISSUE THREAD

**Issue by nevstokes** [upx/upx#227]
## What's the problem (or question)?
I used to be able to use upx when building custom PHP Docker images but of late I'm experiencing segmentation faults after packing. I've also tried using upx on the official PHP images without any luck.

Output from `strace` below:

```
execve("/usr/local/bin/php-upx", ["php-upx"], 0x7ffff69b4760 /* 7 vars */) = 0
mmap(0x600000, 2097152, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, 0, 0) = 0x600000
readlink("/proc/self/exe", "/usr/local/bin/php-upx", 4096) = 22
mmap(NULL, 6934528, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0f1f56c000
mmap(0x7f0f1f56c000, 4219296, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f0f1f56c000
mprotect(0x7f0f1f56c000, 4219296, PROT_READ|PROT_EXEC) = 0
mmap(0x7f0f1fb72000, 570872, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0x406000) = 0x7f0f1fb72000
mprotect(0x7f0f1fb72000, 570872, PROT_READ|PROT_WRITE) = 0
mmap(0x7f0f1fbfe000, 41008, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f0f1fbfe000
open("/lib/ld-musl-x86_64.so.1", O_RDONLY) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\210}\5\0\0\0\0\0"..., 1024) = 1024
mmap(NULL, 2695168, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0f1ff13000
mmap(0x7f0f1ff13000, 577500, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x7f0f1ff13000
mmap(0x7f0f201a0000, 5268, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x8d000) = 0x7f0f201a0000
mmap(0x7f0f201a2000, 8552, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f0f201a2000
close(3)                                = 0
munmap(0x7f0f1fc09000, 6949920)         = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7f0f1ff6ad88} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

## What should have happened?
Running `php -v` on the packed binary should give the same result as the unpacked one.

## Do you have an idea for a solution?
I don't even know where to begin! :)

## How can we reproduce the issue?
1. Use the Dockerfile in this gist https://gist.github.com/nevstokes/05f2d50fdee93b0b5670979b001a4bdb
2. `docker build -t segfault-example .`
3. `docker run --rm -ti segfault-example sapi/cli/php -v` - works as expected
4. `docker run --rm -ti segfault-example sh`
5. `sapi/cli/php-upx -v` - segfaults

## Please tell us details about your environment.

* UPX 3.94
* `Docker version 18.06.0-ce, build 0ffa825`

**Comment by jreiser** [comment]
Please clarify the instructions to reproduce.
I downloaded the link in step1 above, but that is an .html file, not a Dockerfile.  So I copy+pasted the raw contents as Dockerfile.  But then:
```
$ sudo docker build -t segfault-example .
Sending build context to Docker daemon 7.168 kB
Step 1/8 : ARG ALPINE_IMAGE=alpine:3.8@sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528
Please provide a source image with `from` prior to commit
$ sudo docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
docker.io/hello-world   latest              4ab4c602aa5e        5 weeks ago         1.84 kB
$ cat Dockerfile
ARG ALPINE_IMAGE=alpine:3.8@sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528

FROM ${ALPINE_IMAGE} AS build

COPY --from=nevstokes/php-src:7.2 php.tar.xz .

ENV PHP_INI_DIR=/usr/local/etc/php

WORKDIR /usr/src/php

RUN echo '@community http://dl-cdn.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories \
    && apk --update-cache upgrade && apk add \
        build-base \
        upx@community \
        xz \
    \
    && tar -Jxf /php.tar.xz --strip-components=1

# Apply stack smash protection to functions using local buffers and alloca()
# Make PHP's main executable position-independent
# Enable optimization (-Os — Optimize for size)
# Enable linker optimization
# Adds GNU HASH segments to generated executables
# https://github.com/docker-library/php/issues/272

RUN export CFLAGS="-fstack-protector-strong -fpic -fpie -Os" \
    CPPFLAGS="-fstack-protector-strong -fpic -fpie -Os" \
    LDFLAGS="-Wl,-O1 -Wl,--hash-style=both -pie" \
    \
    && ./configure -q -C \
        --with-config-file-path="$PHP_INI_DIR" \
        \
        --disable-option-checking \
        \
        --disable-all \
        --disable-cgi \
        --disable-phpdbg \
    \
    && make -j "$(getconf _NPROCESSORS_ONLN)" \
    && strip --strip-all sapi/cli/php

RUN cp sapi/cli/php sapi/cli/php-upx \
    && upx -9 sapi/cli/php-upx
```
What should I do now?  "sudo docker run hello-world" works.  I'm on Fedora, which requires sudo because docker lacks a good security model.

**Comment by nevstokes** [comment]
Thanks for replying so quickly!

Docker version 1.13.1 is really quite old now. They moved away from semantic versioning in March 2017. The Dockerfile I copied into a gist uses some more up-to-date syntax in quite a few places.

Would it be possible to install a newer version of the Docker engine?

**Comment by jreiser** [comment]
That was Fedora 28, the latest shipping version of Fedora (6 month release cycle). In Fedora 29 beta (due to ship in about one month) the version is:
```
Docker version 1.13.1, build accfe55-unsupported
```
So what Linux are you running?  Suggestions?

**Comment by nevstokes** [comment]
I'm on Ubuntu and just used `apt` - I'm not really a Linux expert.

Could you maybe try the instructions from the Docker website?
https://docs.docker.com/install/linux/docker-ce/fedora/

**Comment by jreiser** [comment]
Using the recipe from the Docker website, I get
```
$ docker --version
Docker version 18.06.1-ce, build e68fc7a
```
In Dockerfile I added <tt>gdb</tt> and <tt>strace</tt> after <tt>xz</tt>.  Running the steps to reproduce in the original description, and invoking with
```
sudo docker run --rm --cap-add SYS_PTRACE --security-opt seccomp=unconfined -v $PWD:/src -ti segfault-example sh
```
I was able to see the SIGSEGV under strace, but gdb did not work.  It always hung, even after <tt>(gdb) set disable-randomization off</tt>. 
However, the current tip of the <tt>devel</tt> branch of upx works on the sapi/cli/php of step 5 in the steps to reproduce.  Please try that.

**Comment by nevstokes** [comment]
That's great to hear.

Many thanks for your help on this and your work on the project!
