### ISSUE TITLE
upx3.9.5 compress arm32 so，apk run error

### ISSUE THREAD

**Issue by afeindsc** [upx/upx#229]
## What's the problem (or question)?
Dear coders,
After using upx3.9.5 to reinforce arm32 so, execute the apk report exception.
The original apk performs normally.

## How can we reproduce the issue?
1. ./upx.out libnative-lib.so -o libnative-lib.so.pack  --android-shlib
2. Replace the compressed so to apk, re-sign the installation apk
3. Original package see attachment
[app-debug.zip](https://github.com/upx/upx/files/2529193/app-debug.zip)

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.9.5
* Host Operating System and version: 5.1.1  
* Host CPU architecture:    ARM64
* Target Operating System and version: EMUI 3.1
* Target CPU architecture: ARM64

**Comment by jreiser** [comment]
<i>... execute the apk report exception.</i>  And what exception did it report?  Please copy+paste (or attach) the report and likely debug info, such as the values of the registers and the traceback.

**Comment by afeindsc** [comment]
hello @jreiser 
here is  the exception report and traceback:

m2DGameFront = false, m3DGameFront = false, mMediaPerceptible = false, mMusicPerceptible = false
mAudioActive = false, mMusicPerceptible = false
return for smartPAOn and mLowAudioEffectEnable both = false
libnative-lib.so: unused DT entry: type 0x6ffffffe arg 0x4cac
libnative-lib.so: unused DT entry: type 0x6fffffff arg 0x3
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 20374 (com.example.tc)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Honor/Che2-UL00/hwChe2:5.1.1/HonorChe2-UL00/C00B425:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 20374, tid: 20374, name: com.example.tc >>> com.example.tc <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
r0 00000000 r1 f00b7904 r2 f6000000 r3 e52de004
r4 e59fff03 r5 00000793 r6 e08fe00e r7 bef0ff08
r8 01cdf0e5 r9 c6ff0000 sl ffa6cf90 fp f59d0a60
ip ca1ce28f sp ffa6cce8 lr f00c6f0d pc f00c6ea8 cpsr 200e0010

backtrace:
#00 pc 00017ea8 /data/app/com.example.tc-2/lib/arm/libnative-lib.so
#01 pc 00017f09 /data/app/com.example.tc-2/lib/arm/libnative-lib.so

Tombstone written to: /data/tombstones/tombstone_04
Object Path:/data/system/dropbox/, mask=0x00000080
event->len=48, name=data_app_native_crash@1540864214755.txt
process_one_event, can not find this event(data_app_native_crash@1540864214755.txt)
clean_cur_cache:992, system(rm -r /data/log/logcache/3576840/* > /dev/null 2>&1)
Object Path:/data/system/dropbox/, mask=0x00000080

**Comment by afeindsc** [comment]
![image](https://user-images.githubusercontent.com/33506422/47690993-57d3c180-dc2b-11e8-9a41-072fa75577fd.png)

**Comment by afeindsc** [comment]
![image](https://user-images.githubusercontent.com/33506422/47699450-f1ac6600-dc4d-11e8-966a-2c3dba4b7f68.png)

**Comment by afeindsc** [comment]
use NDK-r14b

**Comment by jreiser** [comment]
Please test the tip of <tt>devel</tt> branch.  The fix for issue #236 should help here, too.
