### ISSUE TITLE
PyInstaller can't load vcruntime140.dll when packed with upx 3.95

### ISSUE THREAD

**Issue by ghost** [upx/upx#230]
## What's the problem (or question)?

UPX 3.94 and UPX 3.95 appear to be breaking vcruntime140.dll (64 bit) - at least for PyInstaller

See https://github.com/pyinstaller/pyinstaller/issues/3600#issuecomment-433895981

```
PS C:\git\pyinstaller-loadlibrary-upx-bug\dist\test> .\test.exe
Error loading Python DLL 'C:\git\pyinstaller-loadlibrary-upx-bug\dist\test\python37.dll'.
LoadLibrary: The parameter is incorrect.
```

## What should have happened?

```
PS C:\git\pyinstaller-loadlibrary-upx-bug\dist\test> .\test.exe
Hello World
```

## How can we reproduce the issue?

1. Grab a version of Python x64 on Windows 10, preferably 3.7.1
2. Install pyinstaller via pip and add it to PATH
3. Create a simple script with `print("Hello World")`
4. With upx.exe in PATH, run `pyinstaller test.py`
5. Files are built and packed
6. Run `dist\test\test.exe`

I've attached the generated files here:
[pyinstaller-loadlibrary-upx-bug.zip](https://github.com/upx/upx/files/2529554/pyinstaller-loadlibrary-upx-bug.zip)

## Please tell us details about your environment.

* UPX version used (`upx --version`): 
```
upx --version
upx 3.95
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Copyright (C) 1996-2018 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2018 Laszlo Molnar
Copyright (C) 2000-2018 John F. Reiser
Copyright (C) 2002-2018 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```
* Host Operating System and version: Windows 10 x64 1803
* Host CPU architecture: x64
* Target Operating System and version: Windows 10 x64 1803
* Target CPU architecture: x64

**Comment by jreiser** [comment]
Looks the same as https://github.com/upx/upx/issues/203 .  See that issue for a suggestion that might help.

**Comment by voltagex** [comment]
Apologies for the duplicate issue. Interesting that it's caused by a
security feature.
