### ISSUE TITLE
[Question] Creating a shared object that provides an API to perform unpacking

### ISSUE THREAD

**Issue by recvfrom** [upx/upx#232]
## What's the problem (or question)?

It'd be awesome to be able to easily leverage the core UPX-unpacking code in other applications.  One example is in ClamAV -- ClamAV scans UPX-packed executables frequently, so it has its own UPX-unpacking implementation, but it doesn't unpack as reliably and thoroughly as this UPX codebase does.  It'd be great if the ClamAV code could just link with a .so version of this code that provided an API call to do the unpacking.

Is this something you all have thought about making available?  Or do you have any advice on how best to implement something like this?

Thank you!

## What should have happened?
N/A

## Do you have an idea for a solution?
N/A

## How can we reproduce the issue?
N/A

## Please tell us details about your environment.
N/A

**Comment by jreiser** [comment]
Please <i>read</i> the LICENSE file at the top level of the UPX tree of source code!
Part of the LICENSE says:
```
  - We want to actively support manufacturers of virus scanners and
    similar security software. Please contact us if you would like to
    incorporate parts of UPX or UCL into such a product.
```

**Comment by recvfrom** [comment]
@jreiser Sorry about that - I literally read every line in the license except that one.  I think I saw the second to last bullet and navigated away to double-check what the license of ClamAV was (also GPL v2), never to return :(

Would you like me to contact you via email, then?  Thanks!

**Comment by jreiser** [comment]
Yes.  Please send an email to the 3 UPX maintainers (Markus, Laszlo, me) with appropriate information, including: what is ClamAV, pointers to the source code and license(s) of ClamAV, the intended use of UPX and/or UCL in ClamAV, and your role as authorized representative of ClamAV.

**Comment by recvfrom** [comment]
Will do - thanks!
