### ISSUE TITLE
An idea to fix issue #229

### ISSUE THREAD

**Issue by mYicheng** [upx/upx#236]
## What's the problem (or question)?

Dear coder,  
I have an apk which one of so file(shared library) compressed by upx3.95, but unfortunately it crashed after in runtime.  
When I try to fix this bug, I find the crash reason is similar to the issue 229 crash reason..  
![image](https://user-images.githubusercontent.com/34729349/49870576-c1600600-fe4e-11e8-921d-549da0165c99.png)  
![image](https://user-images.githubusercontent.com/34729349/49870635-f2d8d180-fe4e-11e8-97a8-cb4bc16857db.png)  
## What should have happened?

I think, when the loader first copy the fragment data to the new memory area, if the fragment data equal to 7 * 4 bytes, the program will crash.  
![image](https://user-images.githubusercontent.com/34729349/49871670-d0948300-fe51-11e8-9ff3-cf55cb1af922.png)  
Because the program want to run { bx lr }, but in this time, the program running in thumb mode, and the code is arm mode, so than the program will skip the { bx lr } code and run the next code.  
![image](https://user-images.githubusercontent.com/34729349/49872132-1e5dbb00-fe53-11e8-8950-687ea7982c03.png)  
And the next code is arm cache flush program, it will flush the r1 which save the point of new memory area, and then run the { bx lr }.
![image](https://user-images.githubusercontent.com/34729349/49872490-32ee8300-fe54-11e8-8cec-7523ec0ac582.png)  
Then, in the second copy time, the program want to copy compressed data to the new memory area, but in this time r1 just save 00000000, and program can't find the memory area, so the program crash!  
![image](https://user-images.githubusercontent.com/34729349/49872881-6382ec80-fe55-11e8-81f9-d69c21129f54.png)  

## Do you have an idea for a solution?

![image](https://user-images.githubusercontent.com/34729349/49873004-beb4df00-fe55-11e8-9878-36b7480dc063.png)
After change the code, my apk and issue #229 apk will not crash.
## How can we reproduce the issue?

1.Download the [bangbao.zip](https://github.com/upx/upx/files/2672098/bangbao.zip)  
2../upx.out libweibosdkcore.so
3.Replace the compressed so to apk, re-sign the installation apk

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.95
* Host Operating System and version: Ubuntu 14.04
* Host CPU architecture:  X86_64
* Target Operating System and version: Android 6.0.1 (Nexus 5)
* Target CPU architecture: armeabi

**Comment by jreiser** [comment]
Thank you for debugging this issue!

**Comment by mYicheng** [comment]
It's my pleasure!
