### ISSUE TITLE
has invalid shdr offset (Android)

### ISSUE THREAD

**Issue by antizy0** [upx/upx#242]
Android 7.1：
"/data/app/xxxxx/lib/arm/libxxx.so" has invalid shdr offset/size: 127392/960

**Comment by jreiser** [comment]
How can I reproduce this problem?

**Comment by csrbzhb** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.youzu.snsgz.ly-xN4-ZZqdm6rl8Dhi79l95g==/lib/arm/libathena.so" has invalid shdr offset/size: 111480/1080

android o(8.0) and android p(9.0) also happened this issue.

**Comment by csrbzhb** [comment]
readelf--------------------------------
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          52 (bytes into file)
  Start of section headers:          111480 (bytes into file)
  Flags:                             0x5000200, Version5 EABI, soft-float ABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         8
  Size of section headers:           40 (bytes)
  Number of section headers:         27
  Section header string table index: 26
readelf: Error: Reading 0x438 bytes extends past end of file for section headers

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  PHDR           0x000034 0x00000034 0x00000034 0x00100 0x00100 R   0x4
  LOAD           0x000000 0x00000000 0x00000000 0x1313c 0x1313c R E 0x1000
  LOAD           0x0137d0 0x0001a7d0 0x0001a7d0 0x01934 0x01e49 RW  0x1000
  DYNAMIC        0x014ce4 0x0001bce4 0x0001bce4 0x00128 0x00128 RW  0x4
  NOTE           0x000134 0x00000134 0x00000134 0x000bc 0x000bc R   0x4
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x10
  EXIDX          0x00f0d8 0x000150d8 0x000150d8 0x00e28 0x00e28 R   0x4
  GNU_RELRO      0x0137d0 0x0001a7d0 0x0001a7d0 0x01830 0x01830 RW  0x10

Dynamic section at offset 0x14ce4 contains 32 entries:
  Tag        Type                         Name/Value
 0x00000003 (PLTGOT)                     0x1be78
 0x00000002 (PLTRELSZ)                   760 (bytes)
 0x00000017 (JMPREL)                     0x625c
 0x00000014 (PLTREL)                     REL
 0x00000011 (REL)                        0x3b84
 0x00000012 (RELSZ)                      9944 (bytes)
 0x00000013 (RELENT)                     8 (bytes)
 0x6ffffffa (RELCOUNT)                   858
 0x00000006 (SYMTAB)                     0x1f0
 0x0000000b (SYMENT)                     16 (bytes)
 0x00000005 (STRTAB)                     0x1810
 0x0000000a (STRSZ)                      5798 (bytes)
 0x00000004 (HASH)                       0x2eb8
 0x00000001 (NEEDED)                     Shared library: [liblog.so]
 0x00000001 (NEEDED)                     Shared library: [libmg_core.so]
 0x00000001 (NEEDED)                     Shared library: [libm.so]
 0x00000001 (NEEDED)                     Shared library: [libdl.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so]
 0x0000000e (SONAME)                     Library soname: [libathena.so]
 0x0000000c (INIT)                       0x12d51
 0x0000001a (FINI_ARRAY)                 0x1a7d0
 0x0000001c (FINI_ARRAYSZ)               8 (bytes)
 0x00000019 (INIT_ARRAY)                 0x1a7d8
 0x0000001b (INIT_ARRAYSZ)               4 (bytes)
 0x0000001e (FLAGS)                      BIND_NOW
 0x6ffffffb (FLAGS_1)                    Flags: NOW
 0x6ffffff0 (VERSYM)                     0x3864
 0x6ffffffc (VERDEF)                     0x3b28
 0x6ffffffd (VERDEFNUM)                  1
 0x6ffffffe (VERNEED)                    0x3b44
 0x6fffffff (VERNEEDNUM)                 2
 0x00000000 (NULL)                       0x0

**Comment by csrbzhb** [comment]
besides android 5.1 does not occur this issue.

**Comment by jreiser** [comment]
Did you remember to use the command-line argument `--android-shlib` when compressing?  Omitting that flag is the most common cause of complaints such as "has invalid shdr offset/size: 127392/960".

**Comment by csrbzhb** [comment]
tks. I add the argument --android-shlib to compress the so lib.this problem is solved.
