### ISSUE TITLE
Segfault on Android when loading library

### ISSUE THREAD

**Issue by pweiskircher** [upx/upx#243]
## What's the problem (or question)?

I used latest master (https://github.com/upx/upx/commit/7a3637ff5a800b8bcbad20ae7f668d8c8449b014) to try and compress our shared libraries for Android. I used `upx --brute --android-shlib thelibrary.so` and it got it compressed quite a bit!

When packaging everything up into the APK and trying to run it on the emulator, I immediately get a crash:
```
2019-01-16 13:56:09.194 12500-12524/? A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x55acdd44 in tid 12524 (RxCachedThreadS), pid 12500 (it.pspdfcatalog)
2019-01-16 13:56:09.234 12530-12530/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-01-16 13:56:09.234 12530-12530/? A/DEBUG: Build fingerprint: 'Android/sdk_phone_x86/generic_x86:9/PSR1.180720.012/4923214:userdebug/test-keys'
2019-01-16 13:56:09.234 12530-12530/? A/DEBUG: Revision: '0'
2019-01-16 13:56:09.234 12530-12530/? A/DEBUG: ABI: 'x86'
2019-01-16 13:56:09.234 12530-12530/? A/DEBUG: pid: 12500, tid: 12524, name: RxCachedThreadS  >>> com.pspdfkit.pspdfcatalog <<<
2019-01-16 13:56:09.234 12530-12530/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x55acdd44
2019-01-16 13:56:09.234 12530-12530/? A/DEBUG:     eax 8bd61d84  ebx e995bfe8  ecx c9c90000  edx ca2788c9
2019-01-16 13:56:09.234 12530-12530/? A/DEBUG:     edi c9d6bfa0  esi 55acdd44
2019-01-16 13:56:09.234 12530-12530/? A/DEBUG:     ebp cb1cc058  esp cb1cc04c  eip ca2794ce
2019-01-16 13:56:09.239 12530-12530/? A/DEBUG: backtrace:
2019-01-16 13:56:09.239 12530-12530/? A/DEBUG:     #00 pc 005e94ce  /data/app/com.pspdfkit.pspdfcatalog-XFnPYFNJAWXEehAPJJtRDQ==/lib/x86/libpspdfkit.so
```

## What should have happened?
It should run as normally.

## How can we reproduce the issue?
This is a little difficult as it is a very big, very proprietary code base. I may be able to send you the APK after talking to some people, if that would help.

## Please tell us details about your environment.
* UPX version used (`upx --version`):
upx 3.95-git-7a3637ff5a80+
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43

* Host Operating System and version:
macOS 10.14.2

* Host CPU architecture:
x86-64

* Target Operating System and version:
Android 9.0 emulator

* Target CPU architecture:
x86

* In another ticket, I saw you requested a `readelf` output:

```
$ readelf --headers --segments --sections libpspdfkit.so 
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Intel 80386
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          52 (bytes into file)
  Start of section headers:          896928 (bytes into file)
  Flags:                             0x0
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         8
  Size of section headers:           40 (bytes)
  Number of section headers:         28
  Section header string table index: 27

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 0dafa0 000000 00      0   0  0
  [ 1] .note.android.ide NOTE            00000134 000134 000098 00   A  0   0  2
  [ 2] .note.gnu.build-i NOTE            000001cc 0001cc 000024 00   A  0   0  4
  [ 3] .dynsym           DYNSYM          000001f0 0001f0 01fcd0 10   A  4   1  4
  [ 4] .dynstr           STRTAB          0001fec0 01fec0 0622e8 00   A  0   0  1
  [ 5] .hash             HASH            000821a8 0821a8 00bf48 04   A  3   0  4
  [ 6] .gnu.version      VERSYM          0008e0f0 08e0f0 003f9a 02   A  3   0  2
  [ 7] .gnu.version_d    VERDEF          0009208c 09208c 00001c 00   A  4   1  4
  [ 8] .gnu.version_r    VERNEED         000920a8 0920a8 000060 00   A  4   3  4
  [ 9] .rel.dyn          REL             00092108 092108 0419b0 08   A  3   0  4
  [10] .rel.plt          REL             000d3ab8 0d3ab8 0074e0 08  AI  3  22  4
  [11] .plt              PROGBITS        000dbfa0 0dafa0 00e9d0 04  AX  0   0 16
  [12] .text             PROGBITS        000ea970 0e9970 b35128 00  AX  0   0 16
  [13] .gcc_except_table PROGBITS        00c1fa98 c1ea98 0e5efc 00   A  0   0  4
  [14] .rodata           PROGBITS        00d059c0 d049c0 278b10 00   A  0   0 64
  [15] .eh_frame         PROGBITS        00f7e4d0 f7d4d0 108d44 00   A  0   0  4
  [16] .eh_frame_hdr     PROGBITS        01087214 1086214 03f604 00   A  0   0  4
  [17] .fini_array       FINI_ARRAY      010c86d0 10c66d0 000008 04  WA  0   0  4
  [18] .data.rel.ro      PROGBITS        010c86e0 10c66e0 02c7d4 00  WA  0   0 16
  [19] .init_array       INIT_ARRAY      010f4eb4 10f2eb4 000bb0 04  WA  0   0  4
  [20] .dynamic          DYNAMIC         010f5a64 617a64 000120 08  WA  4   0  4
  [21] .got              PROGBITS        010f5b84 10f3b84 0009fc 00  WA  0   0  4
  [22] .got.plt          PROGBITS        010f6580 10f4580 003a7c 00  WA  0   0  4
  [23] .data             PROGBITS        010fa000 10f8000 01fbc8 00  WA  0   0  8
  [24] .bss              NOBITS          01119c00 1117bc8 0095e0 00  WA  0   0 64
  [25] .comment          PROGBITS        00001000 1117bc8 00012f 01  MS  0   0  1
  [26] .note.gnu.gold-ve NOTE            000db400 0db400 00001c 00      0   0  4
  [27] .shstrtab         STRTAB          00001000 0db400 000124 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  p (processor specific)

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  PHDR           0x000034 0x00000034 0x00000034 0x00100 0x00100 R   0x4
  LOAD           0x000000 0x00000000 0x00000000 0x5e95c1 0x5e95c1 R E 0x1000
  LOAD           0x5ea6d0 0x010c86d0 0x010c86d0 0x514f8 0x5ab10 RW  0x1000
  DYNAMIC        0x617a64 0x010f5a64 0x010f5a64 0x00120 0x00120 RW  0x4
  NOTE           0x000134 0x00000134 0x00000134 0x000bc 0x000bc R   0x4
  GNU_EH_FRAME   0x5aa214 0x01087214 0x01087214 0x3f604 0x3f604 R   0x4
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x10
  GNU_RELRO      0x5ea6d0 0x010c86d0 0x010c86d0 0x31930 0x31930 RW  0x10

 Section to Segment mapping:
  Segment Sections...
   00     
   01     .note.android.ident .note.gnu.build-id .dynsym .dynstr .hash .gnu.version .gnu.version_d .gnu.version_r .rel.dyn .rel.plt .plt 
   02     .dynamic .bss 
   03     .dynamic 
   04     .note.android.ident .note.gnu.build-id 
   05     
   06     
   07     .dynamic 
```

**Comment by jreiser** [comment]
Thank you for posting the command line and the output from readelf.
The <tt>master</tt> branch is 17 months old; the current source is in branch <tt>devel</tt>, so please try that.
Meanwhile (or afterwards, if you can use <tt>devel</tt>) let's try to reduce the number of suspects.  Please show the output from <tt>upx --fileinfo thelibrary.so</tt> on the compressed .so; this tells which compression method was used.  Then please try compressing without <tt>--brute</tt>.

**Comment by pweiskircher** [comment]
Thanks for the quick reply! I didn't know about the `devel` branch - I'll get that compiled and test first thing tomorrow morning. If it still doesn't work, I'll follow your further instructions.

**Comment by pweiskircher** [comment]
I now tried using the `devel` branch. It still simply crashed using `--brute`. Without `--brute` it also crashes. This is the requested information without `--brute`:

```
upx.out --fileinfo libpspdfkit.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX git-716d20+ Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 27th 2018

libpspdfkit.so [i386-linux.elf, linux/i386]
   8346604 bytes, compressed by UPX 13, method 8, level 7, filter 0x00/0x00

WARNING: this is an unstable beta version - use for testing only! Really.
```

**Comment by pweiskircher** [comment]
Is there any other information I could provide to help resolve this problem? :)

**Comment by jreiser** [comment]
In order to debug this problem, then I must reproduce it locally.  Android Studio fails to install on Fedora 28, so I am using a SNAP on Ubuntu 18.0.4.  But I'm not familiar with Android Studio, so the going is slow.
Suggestions:
1. Upload ("Attach files by "...) an actual file (gzipped) that triggers the problem, with instructions on how to cause the problem.  Perhaps: take a copy of libpspdfkit.so, zero-out the contents of the .text section, gzip and upload that (and tell me what to do next).  Or, any other (shorter) library that triggers the problem.
2. I am trying to use https://developer.android.com/studio/projects/add-native-code as a clue for how to create a .so that Android Studio will run.  (I will then compress the library, put the compressed version back in the same place, and try to run.  Is this a good approach?)  Give me a recipe that works for you.

**Comment by pweiskircher** [comment]
@jreiser Thank you for looking into this! I can prepare you an easy way to reproduce the problem by just building one of our release zips. I'll get started on doing this (it'll take an hour or so to compile) and will post a new comment with instructions on how to reproduce this easiest.

**Comment by pweiskircher** [comment]
Alright! Sorry for the wait. It took a while to compile this.

The zip file is pretty big, so I uploaded it to Dropbox, it can be downloaded here: https://www.dropbox.com/s/awmu9jhd970t1ph/pspdfkit-upx.zip?dl=0

Reproducing the issue is pretty simple with this:
- Unzip it and in Android Studio choose `Open an existing Android Studio project`
- Point it at the `examples/simple` directory
- After Android Studio does its thing, you can simply try to `Run` the project in any x86 Android Emulator.

This pretty immediately causes this error:
```
2019-02-11 13:06:32.292 4704-4704/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-02-11 13:06:32.292 4704-4704/? A/DEBUG: Build fingerprint: 'google/sdk_gphone_x86/generic_x86:9/PSR1.180720.075/5124027:user/release-keys'
2019-02-11 13:06:32.292 4704-4704/? A/DEBUG: Revision: '0'
2019-02-11 13:06:32.292 4704-4704/? A/DEBUG: ABI: 'x86'
2019-02-11 13:06:32.292 4704-4704/? A/DEBUG: pid: 4680, tid: 4699, name: RxCachedThreadS  >>> com.pspdfkit.example <<<
2019-02-11 13:06:32.292 4704-4704/? A/DEBUG: signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
2019-02-11 13:06:32.292 4704-4704/? A/DEBUG:     eax fffffff4  ebx c8e07f94  ecx 000000f0  edx f30beb86
2019-02-11 13:06:32.292 4704-4704/? A/DEBUG:     edi c7af60f0  esi c81d9131
2019-02-11 13:06:32.292 4704-4704/? A/DEBUG:     ebp c8e07fe8  esp c8e07f94  eip c81d91b6
2019-02-11 13:06:32.293 4704-4704/? A/DEBUG: backtrace:
2019-02-11 13:06:32.293 4704-4704/? A/DEBUG:     #00 pc 007c11b6  /data/app/com.pspdfkit.example-9jE7_7n1-gUcpW_hX5qSKw==/lib/x86/libpspdfkit.so
```

I only included the x86 shared library to keep the zip file size down, but I can easily make you another zip file with different architectures, if that helps.

I updated to the latest `devel` version (UPX `git-3c2bfc+`) before making this zip file.

If you have any Android Studio questions, I asked my colleague @davidschreiber to help us out. I don't do a lot of Android development either, I'm only responsible for the C++ parts.

**Comment by jreiser** [comment]
Got the pspdfkit-upx.zip from DropBox; thank you.  Unzipping, I see
<tt>pspdfkit-upx/examples/simple/sample/libs/pspdfkit-5.3.0-95614-g6e0662a.aar</tt> which is another .zip.  Unzipping that, I see <tt>pspdfkit-upx/examples/simple/sample/libs/jni/x86/libpspdfkit.so</tt> which is the only .so.  It is not so healthy:
```
$ ln -s pspdfkit-upx/examples/simple/sample/libs/jni/x86/libpspdfkit.so .
$ readelf --wide --all libpspdfkit.so >libpspdfkit.readelf
readelf: libpspdfkit.so: Warning: Size of section 12 is larger than the entire file!
readelf: libpspdfkit.so: Warning: Corrupt note: name size is too big: (got: 68732e00, expected no more than: 10)
readelf: libpspdfkit.so: Warning: note with invalid namesz and/or descsz found at offset 0x0
readelf: libpspdfkit.so: Warning:  type: 0x2e006261, namesize: 0x00000000, descsize: 0x74727473
```
and looking at the .readelf output, those complaints look valid:
```
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [12] .text             PROGBITS        000ecb10 0ebb10 b5f928 00  AX  0   0 16
```
The Size 0xb5f928 is 11925800 which is greater than the file size of 8472540.

I'll investigate in Android Studio; please check libpspdfkit.so on your side.

**Comment by pweiskircher** [comment]
Very curious. I'm sure our build process spits out a working `libpspdfkit.so` usually. The only steps I added are there:

```

```

**Comment by pweiskircher** [comment]
Very curious. I'm sure our build process spits out a working `libpspdfkit.so` usually. The only steps I added was to strip the binary (which we already did before) and then to call `upx-mac --android-shlibs libpspdfkit.so`.

Do you think the strip before `upx` could interfere with this?

**Comment by jreiser** [comment]
`strip` before `upx` should not disturb Elf32_Shdr.sh_size.
I see <tt>upx-mac</tt> in your Comment.  Is the library for Mac or for Linux?

**Comment by pweiskircher** [comment]
The library is for Android/Linux. Our build process is running on the Mac, though, so I compiled `upx` for the Mac.

I'm currently rebuilding the zip file I sent you and I'm going to slowly go through the far too large log after it is done to see if *something* in the Android build process is screwing up the library.

**Comment by pweiskircher** [comment]
Alright. I don't see anything in the log-output. It seems to be `upx` which is causing this problem? I'm attaching the `libpspdfkit.so` that hasn't been through `upx` yet and `readelf` seems to be pretty happy with it. 

[no-upx.zip](https://github.com/upx/upx/files/2852896/no-upx.zip)

**Comment by jreiser** [comment]
Got no-upx.zip; looking ...

**Comment by pweiskircher** [comment]
Hm. We use the `gold` linker because we couldn't get `LTO` working without it. But I don't think we tried that lately.

Do you think there's a way to make this work with UPX as is?

**Comment by jreiser** [comment]
That commit might not be enough for Android, but it makes `readelf` happy about the SHT_NOTE.

**Comment by jreiser** [comment]
Please give me a recipe to reproduce the error.  I have Android Studio 3.3 of December 24, 2018 running as a SNAP on Ubuntu 18.0.4 Linux on x86_64.  I unzipped pspdfkit-upx.zip, and then Android Studio > File > Open > pspdfkit-upx .  What now?
The Build menu has "Make module 'pspdfkit-upx'" and when I click it, then nothing happens.
The Run menu has the first 3 lines {Run, Debug, Run with coverage} grayed-out, followed by {Run..., Debug..., Profile...} [notice the ellipses] not grayed-out; clicking on Run... nothing happens.
How do I reproduce the error?

**Comment by bommo1** [comment]
@pweiskircher did your problem get solved by the latest commit?

**Comment by f4grx** [comment]
For my part I have asked our test team to do a test run with compiled libs. I will report the results when its done.

**Comment by TomTasche** [comment]
Sorry for bumping up such an old issue, but I'm willing to sponsor work on fixing this library for Android. Is anyone interested in working on this?

**Comment by jreiser** [comment]
@TomTasche The problem is the debugging environment.  The best would be something like what worked recently for fixing an issue on MIPS: see https://github.com/upx/upx/issues/342#issuecomment-583801963.  Namely: a short sequence of shell command lines running on Linux x86_64 that reliably reproduce the problem under a debugger that can examine registers and memory, plant breakpoints, and single step, WITHOUT having any corresponding source code available. `readelf` and gdb work just fine [almost always].
Why is Android so hard to debug?  Android Studio is a GUI; a GUI is the WORST possible environment: They're all different, so the learning curve is very steep; there is a huge variation in layout (relevant pieces may be hidden under several layers of menu), the build process for a project is full of slang, even just naming the pieces is bizarre.  Like most GUIs, Android Studio apparently does not offer an interface to EVERY POSSIBLE option and build strategy, and is buggy to the max: it does not even install on my Fedora 30 for x86_64.  So I try on Ubuntu 18.04 LTS.  It takes all afternoon just to install because the download image is incomplete, and internet search for the apparently-missing pieces is rife with misunderstandings and broken and/or incompatible links.  There is no self-test, so I may have done something "wrong" without knowing. The "walk through" for creating a simple project does not match the current implementation: things have moved, changed names, etc.  Reproducing a failure is extremely tedious, nearly impossible.
I want: one small main program that uses one shared library; such that in 15 seconds I can  substitute and begin debugging with a different shared library.  You know, a "hello world" program (or as close as posslble to it) that uses a shared library, for a totally-vanilla Android device.  And it must run under shell command line on Linux, either x86_64 or RaspberryPi model 3.  Look at the example `qemu-mips` that I pointed to above;  why cannot Android be just as simple?

**Comment by TomTasche** [comment]
Thanks a lot for summarizing the challenges of fixing this issue! Android Studio setup isn't always straightforward, but it's doable as soon as you get used to some of the specialities. If that'd be the only thing keeping you from fixing this issue we could find someone to walk through the setup process with you...

Regarding gdb, this might help to avoid the GUI you despise so much: https://source.android.com/devices/tech/debug/gdb

I've reached out to a few colleagues to see if they'd be interested in working on this issue too.

**Comment by 4ntoine** [comment]
I can see UPX 3.96 is available with `brew`. Does it have the issue?
Very curious to make it working for ARM executables on Android..

**Comment by 4ntoine** [comment]
@pweiskircher i can find the doc for `--android-shlib`. Where did you find it?

**Comment by 4ntoine** [comment]
I can confirm ARM64 executables crash. I'm happy to provide the details.

**Comment by 4ntoine** [comment]
Also tried ARMeabi-v7a and it also finished with result code 139 (so it was not crash). It seems to be Android 10 issue:
```
2020-11-26 01:34:07.877 5325-5325 W/avr-g++: type=1400 audit(0.0:233150): avc: denied { execmod } for path="/data/app/name.antonsmirnov.android.testapp2-IeYrfN9sWiUKbC3yz213ag==/lib/arm64/libavr_avr-g++.so" dev="sda32" ino=108212 scontext=u:r:untrusted_app:s0:c98,c257,c512,c768 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0
2020-11-26 01:34:07.892 3913-5323 W/System.err: /data/data/name.antonsmirnov.android.testapp2/sdk/hardware/tools/avr/bin/avr-g++ returned 139
```
