### ISSUE TITLE
UPX (3.95) can't pack vc142 (VS2019 Prev 2.0) binaries

### ISSUE THREAD

**Issue by RaiKoHoff** [upx/upx#245]
## What's the problem (or question)?

Using UPX for years, without any problems for my compilations, the new build (VS2019 Prev 2.0, compiler vc142 (ver. 192027305) produces executables, which can't be compressed (UPX 3.95) anymore.

## What should have happened?

Should compress these binaries like the builds of previous compiler version (vc141).

## Do you have an idea for a solution?

No clue yet :-O

## How can we reproduce the issue?

```
upx395_64.exe --best --no-backup --compress-icons=2 --compress-resources=1 Notepad3.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95w       Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx395_64: Notepad3.exe: CantPackException: size of Load Configuration directory unexpected

Packed 1 file: 0 ok, 1 error.
```
Notepad3.exe attached as ZIP

[Notepad3.zip](https://github.com/upx/upx/files/2798811/Notepad3.zip)
## Please tell us details about your environment.

* UPX version used (`upx --version`):
   ```
   upx 3.95
   NRV data compression library 0.84
   UCL data compression library 1.03
   zlib data compression library 1.2.3
   LZMA SDK version 4.43
   ```
* Host Operating System and version:
  Windows 10 Home (64-bit) Ver. 1803  Build 17134.523
* Host CPU architecture:
  Intel Core i7-4790
* Target Operating System and version:
  - same as Host
* Target CPU architecture:
  -same as Host

**Comment by jreiser** [comment]
The complaint seemed to be a vague misgiving about large Load Configuration directory.  Avoiding throwCantPack() in favor of info(), which can be seen by using the command-line flag <tt>-i</tt>, seems to work OK.  Please test the tip of <tt>devel</tt> branch, commit 70ed2d0, for which an auto-build should be available soon using the link just above this Comment.

**Comment by RaiKoHoff** [comment]
The complaint has been a vague misgiving, cause the only change for building the binaries was the change to the new compiler tool-set.
Nevertheless the corresponding auto-build ([devel-20190126-70ed2d0](https://github.com/upx/upx-automatic-builds/tree/devel-20190126-70ed2d0-appveyor)) works fine on these binaries - thank you.

**Comment by Mattiwatti** [comment]
Some info re: this: the hardcoded `MAX_SOLOADCONF = 256` is no longer applicable because a recent update to the Windows SDK increased the maximum size to 264 (x64 only, for x86 it's 164). My hypothesis is that the VS2019 toolchain uses this new larger value when inserting an auto-generated load config directory and that this is the reason for the error/now info message.

The real maximum possible size value can only be obtained as `sizeof(IMAGE_LOAD_CONFIG_DIRECTORY)` (assuming the Windows SDK is up to date since this is in `winnt.h`). Since MS keeps adding entries to this struct, I don't know if it's really feasible to have a hard limit that matches the header exactly. As this is now an info message instead of an error it's basically harmless, but it does mean that older versions of UPX would start printing bogus info messages after an MSVC update even if the above approach were used. IMO this check is not useful unless it is used to reject clearly bogus sizes, but then you get into the question of at what point precisely the size is bogus...

**Comment by BullyWiiPlaza** [comment]
What happened to the release of version `3.96`? Can someone please provide a fixed build? I'm running into the same issue as the original poster. Thank you.

**Comment by tomgron** [comment]
I get the same issue when trying to UPX (3.95w) a Rust (2018) compiled simple binary (no opts). Linking done with 2019 VS linker (or 2017). Here's the output:

```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95w       Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
[Processing hello-rust.exe, format win64/pe, 5 sections]
    Copying original stub: 232 bytes
    Processing imports: 8 DLLs
    [WARNING] can't remove unneeded imports

    Imports: original size: 2799 bytes, preprocessed size: 1295 bytes
    TLS: 1 callback(s) found, adding TLS callback handler
    TLS: 192 bytes tls data and 0 relocations added
upx: .\hello-rust.exe: CantPackException: size of Load Configuration directory unexpected
```

**Comment by kingdevnl** [comment]
Yep im getting the same error

**Comment by casept** [comment]
Same issue here.

**Comment by johnwbyrd** [comment]
+1.  This issue still exists, and it should not be closed.

**Comment by jreiser** [comment]
Works for me on the Notepad3 from the original .zip of the Description, using the tip of `devel` branch:
```
UPX git-6a53c0+ Markus Oberhumer, Laszlo Molnar & John Reiser   Feb 24th 2019

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   3622912 ->   1366528   37.72%    win64/pe     Notepad3.exe              
```

**Comment by svenstaro** [comment]
I just tested [my own executable](https://github.com/svenstaro/proxyboi/releases/download/0.1.5/proxyboi-windows-amd64.exe) built here on GitHub Actions CI and can confirm that it works using devel.
