### ISSUE TITLE
several busybox applets do not spawn from internal shell when compressed with upx

### ISSUE THREAD

**Issue by sixmillonisntenough** [upx/upx#248]
## What's the problem (or question)?

BACKGROUND: busybox's applets are often accessed by symlinks of the applet name to the busybox binary; however, I am using the NOFORK/NOEXEC feature within the 'ash' shell in busybox to run the applets from the command line and do NOT have them symlinked to the binary. 

BUG: when executing many applets from within the shell, when busybox is compressed with UPX (latest version), the shell tries to execute the program in its $PATH and NOT the internal applet. However, when busybox is executed with the applet name as it's argv[0] (symlinked) or argv[1] (busybox top , for instance) it works fine. It is only when operating under the shell, 'ash', that it does not. When NOT compressed with UPX, it operates fine.

## What should have happened?

The UPX compressed busybox 'ash' shell should be able to execute the same internal busybox applets as when it is not compressed, but is unable to.

## How can we reproduce the issue?

1. Compile busybox with CONFIG_FEATURE_PREFER_APPLETS=y  and  CONFIG_FEATURE_SH_NOFORK=y. Make sure to enable 'ash' shell and all the default applets.
2. Compile busybox; run the shell with ./busybox ash and, once in the shell, type "top -h" or "grep -h". You will see their headers indicate they are the internal busybox versions.
3. Compress busybox with upx and do the same. You'll find that the headers indicate they are the binaries on the system (e.g. procps' 'top').
4. Note that "./busybox top" "./busybox grep" etc. work just fine when UPX compressed, as does moving the busybox binary to those program names or symlinking those programs and trying it, but just NOT under the shell.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:
upx 3.94
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43

Linux centos6 2.6.32-754.10.1.el6.x86_64.debug #1 SMP Tue Jan 15 17:12:29 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jreiser** [comment]
Please clarify the build instructions.  In your step 2), I see the same output from "top -h" under busybox as I do under bash.
```
$ git clone https://github.com/mirror/busybox.git

$ git log | sed 5q
commit 2feaba1d8dc2893d9f1064673e500312eaa70777
Date:   Tue Feb 5 17:48:24 2019 +0100

$ make defconfig

$ vim .config   ## edit as instructed by step 1) of Description

$ grep CONFIG_FEATURE_PREFER_APPLETS .config   ## show results of editing
CONFIG_FEATURE_PREFER_APPLETS=y

$ grep CONFIG_FEATURE_SH_NOFORK .config
CONFIG_FEATURE_SH_NOFORK=y

$ grep ASH .config   ## show existing CONFIG_* relating to ASH
CONFIG_FEATURE_VOLUMEID_SQUASHFS=y
CONFIG_FBSPLASH=y
# CONFIG_FLASHCP is not set
# CONFIG_FLASH_ERASEALL is not set
# CONFIG_FLASH_LOCK is not set
# CONFIG_FLASH_UNLOCK is not set
CONFIG_FEATURE_LESS_DASHCMD=y
CONFIG_SH_IS_ASH=y
# CONFIG_BASH_IS_ASH is not set
# CONFIG_BASH_IS_HUSH is not set
CONFIG_BASH_IS_NONE=y
CONFIG_ASH=y
CONFIG_ASH_OPTIMIZE_FOR_SIZE=y
CONFIG_ASH_INTERNAL_GLOB=y
CONFIG_ASH_BASH_COMPAT=y
# CONFIG_ASH_BASH_SOURCE_CURDIR is not set
CONFIG_ASH_BASH_NOT_FOUND_HOOK=y
CONFIG_ASH_JOB_CONTROL=y
CONFIG_ASH_ALIAS=y
CONFIG_ASH_RANDOM_SUPPORT=y
CONFIG_ASH_EXPAND_PRMT=y
CONFIG_ASH_IDLE_TIMEOUT=y
CONFIG_ASH_MAIL=y
CONFIG_ASH_ECHO=y
CONFIG_ASH_PRINTF=y
CONFIG_ASH_TEST=y
CONFIG_ASH_HELP=y
CONFIG_ASH_GETOPTS=y
CONFIG_ASH_CMDCMD=y
CONFIG_HUSH_BASH_COMPAT=y
# CONFIG_HUSH_BASH_SOURCE_CURDIR is not set

$ ./busybox ash   ## invoke busybox and make 'ash' the shell

$ ps   ## prove it
  PID TTY          TIME CMD
17831 pts/3    00:00:00 bash
24406 pts/3    00:00:00 busybox
24414 pts/3    00:00:00 ps

$ top -h   ## under busybox
  procps-ng 3.3.12
Usage:
  top -hv | -bcHiOSs -d secs -n max -u|U user -p pid(s) -o field -w [cols]
$ exit   ## back to bash

$ top -h   ## under bash
  procps-ng 3.3.12
Usage:
  top -hv | -bcHiOSs -d secs -n max -u|U user -p pid(s) -o field -w [cols]

```

**Comment by jreiser** [comment]
You can also do a bit of debugging via <tt>strace -f -o strace.out -e trace=execve ./busybox ash</tt> etc.

**Comment by sixmillonisntenough** [comment]
> Please clarify the build instructions. In your step 2), I see the same output from "top -h" under busybox as I do under bash.
> 
> ```
> $ git clone https://github.com/mirror/busybox.git
> 
> $ git log | sed 5q
> commit 2feaba1d8dc2893d9f1064673e500312eaa70777
> Date:   Tue Feb 5 17:48:24 2019 +0100
> 
> $ make defconfig
> 
> $ vim .config   ## edit as instructed by step 1) of Description
> 
> $ grep CONFIG_FEATURE_PREFER_APPLETS .config   ## show results of editing
> CONFIG_FEATURE_PREFER_APPLETS=y
> 
> $ grep CONFIG_FEATURE_SH_NOFORK .config
> CONFIG_FEATURE_SH_NOFORK=y
> 
> $ grep CONFIG_TOP .config    ## 'top' is an internal app [??]
> CONFIG_TOP=y
> 
> $ grep ASH .config   ## show existing CONFIG_* relating to ASH
> CONFIG_FEATURE_VOLUMEID_SQUASHFS=y
> CONFIG_FBSPLASH=y
> # CONFIG_FLASHCP is not set
> # CONFIG_FLASH_ERASEALL is not set
> # CONFIG_FLASH_LOCK is not set
> # CONFIG_FLASH_UNLOCK is not set
> CONFIG_FEATURE_LESS_DASHCMD=y
> CONFIG_SH_IS_ASH=y
> # CONFIG_BASH_IS_ASH is not set
> # CONFIG_BASH_IS_HUSH is not set
> CONFIG_BASH_IS_NONE=y
> CONFIG_ASH=y
> CONFIG_ASH_OPTIMIZE_FOR_SIZE=y
> CONFIG_ASH_INTERNAL_GLOB=y
> CONFIG_ASH_BASH_COMPAT=y
> # CONFIG_ASH_BASH_SOURCE_CURDIR is not set
> CONFIG_ASH_BASH_NOT_FOUND_HOOK=y
> CONFIG_ASH_JOB_CONTROL=y
> CONFIG_ASH_ALIAS=y
> CONFIG_ASH_RANDOM_SUPPORT=y
> CONFIG_ASH_EXPAND_PRMT=y
> CONFIG_ASH_IDLE_TIMEOUT=y
> CONFIG_ASH_MAIL=y
> CONFIG_ASH_ECHO=y
> CONFIG_ASH_PRINTF=y
> CONFIG_ASH_TEST=y
> CONFIG_ASH_HELP=y
> CONFIG_ASH_GETOPTS=y
> CONFIG_ASH_CMDCMD=y
> CONFIG_HUSH_BASH_COMPAT=y
> # CONFIG_HUSH_BASH_SOURCE_CURDIR is not set
> 
> $ make
> 
> $ ./busybox ash   ## invoke busybox and make 'ash' the shell
> 
> $ ps   ## prove it
>   PID TTY          TIME CMD
> 17831 pts/3    00:00:00 bash
> 24406 pts/3    00:00:00 busybox
> 24414 pts/3    00:00:00 ps
> 
> $ top -h   ## under busybox
>   procps-ng 3.3.12
> Usage:
>   top -hv | -bcHiOSs -d secs -n max -u|U user -p pid(s) -o field -w [cols]
> 
> $ exit   ## back to bash
> 
> $ top -h   ## under bash
>   procps-ng 3.3.12
> Usage:
>   top -hv | -bcHiOSs -d secs -n max -u|U user -p pid(s) -o field -w [cols]
> ```

Yes, the top is supposed to show 'busybox multicall binary' when you give top -h or ps -h; procps would be it executing the one on the system. This is the issue; when busybox is NOT compressed with UPX, and you run those tools under busybox 'ash', they call the built-in 'applets' and thus show the busybox header. When you run them under a UPX-compressed busybox 'ash' they execute the ones on the system and thus show procps. So that is the output as expected.

Compile a busybox w/ NOFORK and APPLETS PREFERRED and do not compress and you should get the busybox header.  (If you don't, it's not compiled properly for this feature; look at the 'NOFORK_NOEXEC' files in the root busybox directory from a fresh git clone. You want it so that it prefers internal applets and uses nofork/noexec whenever possible). When you compress, you'll get the procps or some other header than busybox, indicating it is calling the system executable in its PATH and not the internal applet.

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") a copy of <tt>.config</tt> with the settings which cause the problem; gzip it first.  The directions you have given are not explicit enough.  My .config has <tt>CONFIG_FEATURE_SH_NOFORK=y</tt> and <tt>CONFIG_FEATURE_PREFER_APPLETS=y</tt> and the other lines as above.  Yet I still get the same output from <tt>top -h</tt> under both <tt>bash</tt> and <tt>./busybox ash</tt>, uncompressed.

**Comment by jreiser** [comment]
You forgot <tt>CONFIG_FEATURE_SH_STANDALONE=y</tt>, which I found in the INSTALL file under <tt>Quick Start:</tt>.  Grrrr....
Also, it works as desired when compressed by upx-3.95, which has been released for 17 months.  Console transcript:
```
$ upx-3.95 -o busybox-3.95 busybox
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    939488 ->    524152   55.79%   linux/amd64   busybox-3.95                  

Packed 1 file.

$ ./busybox-3.95 ash

$ top -h
top: invalid option -- 'h'
BusyBox v1.31.0.git (2019-02-06 22:05:37 PST) multi-call binary.
  [[snip]]
```

**Comment by sixmillonisntenough** [comment]
You are correct-- it does work under 3.95. I'm sorry, I was using 3.94 as I had made a few modifications to the source tree in the past while trying to fix similar bugs (quite the under-taking with this code base; I was just focusing on amd64, keeping it limited) and hadn't upgraded to 3.95 and didn't notice. I'll be checking out the diff's to see what changed and made this work.

Thank you!
