### ISSUE TITLE
Is upx_3.9.2 support compress armeabi-v7a lib or executable file?

### ISSUE THREAD

**Issue by zdfan** [upx/upx#25]
## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Operating System and version:
* CPU architecture:

**Comment by jreiser** [comment]
According to https://developer.android.com/ndk/guides/abis.html#v7a, armeabi-v7a is ARMv5TE (32-bit, plus Thumb) plus softfp (floating-point arguments are passed in pairs of integer registers) plus optional hardware extensions such as vfp (vector floatng point), NEON, etc. UPX does not use any floating-point instructions, nor any SIMD (NEON) instructions.  UPX does not use any Thumb instructions.  UPX-3.91 already supports 32-bit ARMv5TE with a few software ABI flavors.  Have you tried UPX-3.91?

Please designate a small actual executable file which is in the format you desire; give an explicit literal URL or other means to point to a specific file.  /bin/date is often a good candidate.  Or, compile and link the C program
```
int x[10000]  = {1,2,3};
int main(int argc, char *argv[]) {
    return x[1];
}
```
then compress the executable using gzip, encode into text, and paste the results in a comment to this Issue.

**Comment by zdfan** [comment]
UPX 3.9.1 can support simple lib, exec is not supported, but my lib (just complex lib) don't support. UPX 3.9.2 meets my needs. I can use upx 3.9.2, thank you very much!
