### ISSUE TITLE
electron.exe fails on win10 but working for win7

### ISSUE THREAD

**Issue by mingyuan-xia** [upx/upx#250]
## What's the problem (or question)?
electron.exe, compressed on win7, works good on win7, but fails on win10.
https://github.com/electron/electron/releases/v4.0.0
win32-x64.zip is used here.
UPX version 3.9.5

## What should have happened?
electron.exe works fine on both platforms

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.9.5
* Host Operating System and version: windows
* Host CPU architecture: x64
* Target Operating System and version: win10
* Target CPU architecture: x64

**Comment by jreiser** [comment]
https://github.com/upx/upx/issues/141 says the opposite:  Upx compressed exe not work for electron.exe on win7, win10 is OK

Please give the exact error message, complaint, or  reason why you believe win10 fails but  win7 works.  Please give the exact invocation which triggers the problem that you see.

**Comment by mingyuan-xia** [comment]
It is a fact, not a "reason".
Our automated build process uses UPX to compress electron.exe per release of our product.
Recently we upgrade to electron 4.0.0 and UPX 3.9.5 (previously electron 1.4.15 + upx 3.9.3). The compressed electron.exe is built on win7 and tested on win7 only. Then the users (quite a lot) report failure on win10. We simply re-distribute the uncompressed electron.exe and solve this emergency. I will try to get some error log/crash log, but bear me for the possible delay (packed schedule + no win10 box at hand)

**Comment by Mattiwatti** [comment]
> It is a fact, not a "reason".

He isn't saying it isn't a fact. He's asking what the reason is. The reason is Control Flow Guard being enabled in `electron.exe`.
