### ISSUE TITLE
several Segmentation faults

### ISSUE THREAD

**Issue by hello2b** [upx/upx#252]
## What's the problem (or question)?

upx 3.95 executed with setting args which is a mutated input. Segmentation fault occurred.

## What should have happened?

if neccesary, i can support my input files. all of them can cause  errors. I've analyzed one by gdb，and the rest is coming 

Starting program: /home/cz/upx/src/upx.out '/home/cz/Desktop/c0' 
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX git-7a3637+ Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------

Program received signal SIGSEGV, Segmentation fault.

[----------------------------------registers-----------------------------------]
EAX: 0x8511ba8 
EBX: 0x83cce18 --> 0x82e7ae8 --> 0x8147b70 (<PackLinuxElf32x86::~PackLinuxElf32x86()>:    lea    esp,[esp-0x10])
ECX: 0x83ccf68 --> 0x83cd4d8 --> 0x464c457f 
EDX: 0x83c7be0 --> 0x838f6f0 --> 0x82671b0 (<N_BELE_RTP::LEPolicy::~LEPolicy()>:lea    esp,[esp-0x10])
ESI: 0x83cd4d8 --> 0x464c457f 
EDI: 0x83c7be0 --> 0x838f6f0 --> 0x82671b0 (<N_BELE_RTP::LEPolicy::~LEPolicy()>:lea    esp,[esp-0x10])
EBP: 0x838f6f0 --> 0x82671b0 (<N_BELE_RTP::LEPolicy::~LEPolicy()>:    lea    esp,[esp-0x10])
ESP: 0xbfffe15c --> 0x8156bda (<PackLinuxElf32::canPack()+3546>:    add    eax,esi)
EIP: 0x8266754 (<N_BELE_RTP::LEPolicy::get32(void const*) const+52>:    )
EFLAGS: 0x10202 (carry parity adjust zero sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x8266749 <N_BELE_RTP::LEPolicy::get32(void const*) const+41>:    
    mov    edi,DWORD PTR [esp]
   0x826674c <N_BELE_RTP::LEPolicy::get32(void const*) const+44>:    
    lea    esp,[esp+0x10]
   0x8266750 <N_BELE_RTP::LEPolicy::get32(void const*) const+48>:    
    mov    eax,DWORD PTR [esp+0x8]
### => 0x8266754 <N_BELE_RTP::LEPolicy::get32(void const*) const+52>:    
    mov    eax,DWORD PTR [eax]
   0x8266756 <N_BELE_RTP::LEPolicy::get32(void const*) const+54>:    ret    
   0x8266757:    xchg   ax,ax
   0x8266759:    xchg   ax,ax
   0x826675b:    xchg   ax,ax
[------------------------------------stack-------------------------------------]
0000| 0xbfffe15c --> 0x8156bda (<PackLinuxElf32::canPack()+3546>:    add    eax,esi)
0004| 0xbfffe160 --> 0x83c7be0 --> 0x838f6f0 --> 0x82671b0 (<N_BELE_RTP::LEPolicy::~LEPolicy()>:    lea    esp,[esp-0x10])
0008| 0xbfffe164 --> 0x8511ba8 
0012| 0xbfffe168 --> 0x46e8 
0016| 0xbfffe16c --> 0x0 
0020| 0xbfffe170 --> 0xb7c62eb8 --> 0x491b 
0024| 0xbfffe174 --> 0x4f9 
0028| 0xbfffe178 --> 0xb7c67603 --> 0xd001200 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
0x08266754 in get_le32 (p=0x8511ba8) at bele.h:164
164        return ACC_UA_GET_LE32(p);
gdb-peda$ **x/x 0x8511ba8**
0x8511ba8:    Cannot access memory at address 0x8511ba8

 
## How can we reproduce the issue?

use the seed i've fuzzed by afl. 16 new uniq crashes will be determined recently. if neccesary ,i can send to you. Details will not be published ,and i want to apply for the cve number with your support. Thanks very much.

1 Pack a file(for ex: ls tool)
2 Compile the source code by instrumenting it with afl-g++
3 Execute instrumented UPX binary under AFL fuzzer and unpack file from (1)

## Please tell us details about your environment.

* UPX version used (`upx --version`):
upx 3.95-git-7a3637ff5a80+
UCL data compression library 1.03
zlib data compression library 1.2.8
LZMA SDK version 4.43
* Host Operating System and version: Ubuntu 16.04.3 LTS
* Host CPU architecture: i686 ，32bit
* Target Operating System and version:Ubuntu 16.04.3 LTS
* Target CPU architecture: i686 ，32bit

[pos_51.zip](https://github.com/upx/upx/files/2887518/pos_51.zip)

**Comment by hello2b** [comment]
the 16 crashes have be classified into 2 bugs. can we request a CVE ID?

**Comment by hello2b** [comment]
cz@ubuntu:~$ gdb /home/cz/upx/src/upx.out
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/cz/upx/src/upx.out...done.
gdb-peda$ set args '/home/cz/Desktop/c1' 
gdb-peda$ r
Starting program: /home/cz/upx/src/upx.out '/home/cz/Desktop/c1' 
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX git-7a3637+ Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------

Program received signal SIGSEGV, Segmentation fault.

[----------------------------------registers-----------------------------------]
EAX: 0xc3cdc1b 
EBX: 0x83cce18 --> 0x82e7ae8 --> 0x8147b70 (<PackLinuxElf32x86::~PackLinuxElf32x86()>:    lea    esp,[esp-0x10])
ECX: 0x12 
EDX: 0x838f6f0 --> 0x82671b0 (<N_BELE_RTP::LEPolicy::~LEPolicy()>:    lea    esp,[esp-0x10])
ESI: 0xc3cdc1b 
EDI: 0x828f5bb ("__libc_start_main")
EBP: 0x83cde5c --> 0x1507 
ESP: 0xbfffe130 --> 0x83c7be0 --> 0x838f6f0 --> 0x82671b0 (<N_BELE_RTP::LEPolicy::~LEPolicy()>:    lea    esp,[esp-0x10])
EIP: 0x8151561 (<PackLinuxElf32::calls_crt1(N_Elf::Rel<N_Elf::ElfITypes<LE16, LE32, LE32, LE32, LE32> > const*, int)+641>:    )
EFLAGS: 0x10206 (carry PARITY adjust zero sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x8151558 <PackLinuxElf32::calls_crt1(N_Elf::Rel<N_Elf::ElfITypes<LE16, LE32, LE32, LE32, LE32> > const*, int)+632>:    add    eax,esi
   0x815155a <PackLinuxElf32::calls_crt1(N_Elf::Rel<N_Elf::ElfITypes<LE16, LE32, LE32, LE32, LE32> > const*, int)+634>:    mov    ecx,0x12
   0x815155f <PackLinuxElf32::calls_crt1(N_Elf::Rel<N_Elf::ElfITypes<LE16, LE32, LE32, LE32, LE32> > const*, int)+639>:    mov    esi,eax
=> 0x8151561 <PackLinuxElf32::calls_crt1(N_Elf::Rel<N_Elf::ElfITypes<LE16, LE32, LE32, LE32, LE32> > const*, int)+641>:    
    repz cmps BYTE PTR ds:[esi],BYTE PTR es:[edi]
   0x8151563 <PackLinuxElf32::calls_crt1(N_Elf::Rel<N_Elf::ElfITypes<LE16, LE32, LE32, LE32, LE32> > const*, int)+643>:    seta   dl
   0x8151566 <PackLinuxElf32::calls_crt1(N_Elf::Rel<N_Elf::ElfITypes<LE16, LE32, LE32, LE32, LE32> > const*, int)+646>:    setb   cl
   0x8151569 <PackLinuxElf32::calls_crt1(N_Elf::Rel<N_Elf::ElfITypes<LE16, LE32, LE32, LE32, LE32> > const*, int)+649>:    add    esp,0x10
   0x815156c <PackLinuxElf32::calls_crt1(N_Elf::Rel<N_Elf::ElfITypes<LE16, LE32, LE32, LE32, LE32> > const*, int)+652>:    cmp    dl,cl
[------------------------------------stack-------------------------------------]
0000| 0xbfffe130 --> 0x83c7be0 --> 0x838f6f0 --> 0x82671b0 (<N_BELE_RTP::LEPolicy::~LEPolicy()>:    lea    esp,[esp-0x10])
0004| 0xbfffe134 --> 0x83cd824 --> 0x40001c7 
0008| 0xbfffe138 --> 0x13 
0012| 0xbfffe13c --> 0xa8 
0016| 0xbfffe140 --> 0x8116720 (<PackLinuxElf32::elf_get_offset_from_address(unsigned int) const>:    lea    esp,[esp-0x10])
0020| 0xbfffe144 --> 0x838f6f0 --> 0x82671b0 (<N_BELE_RTP::LEPolicy::~LEPolicy()>:    lea    esp,[esp-0x10])
0024| 0xbfffe148 --> 0x81512fd (<PackLinuxElf32::calls_crt1(N_Elf::Rel<N_Elf::ElfITypes<LE16, LE32, LE32, LE32, LE32> > const*, int)+29>:    mov    eax,DWORD PTR [esp+0xc])
0028| 0xbfffe14c --> 0x83cce18 --> 0x82e7ae8 --> 0x8147b70 (<PackLinuxElf32x86::~PackLinuxElf32x86()>:    lea    esp,[esp-0x10])
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
0x08151561 in PackLinuxElf32::calls_crt1 (this=0x83cce18, rel=0x83cde58, 
    sz=0xa8) at p_lx_elf.cpp:1694
1694            if (0==strcmp(symnam, "__libc_start_main")  // glibc
gdb-peda$  0x8151561 <PackLinuxElf32::calls_crt1(N_Elf::Rel<N_Elf::ElfITypes<LE16, LE32, LE32, LE32, LE32> > const*, int)+641>:
Undefined command: "0x8151561".  Try "help".
gdb-peda$     repz cmps BYTE PTR ds:[esi],BYTE PTR es:[edi]
Undefined command: "repz".  Try "help".

**Comment by jreiser** [comment]
If you're going to run a fuzzer, then please test against the `devel` branch, which is current and has many fixes.  (Several others have run their fuzzers previously, and all reported problems have been fixed on `devel`.) Or, wait a little bit: Markus has scheduled the release of upx-3.96 "soon".

`id_000015,sig_11,src_000008,op_flip1,pos_847` and `id_000000,sig_11,src_000008,op_flip1,pos_51 ` already are fixed:
```
UPX git-cc5f68+ Markus Oberhumer, Laszlo Molnar & John Reiser   Feb 24th 2019

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: id_000015,sig_11,src_000008,op_flip1,pos_847: CantPackException: bad .st_name 0x40001c7 in DT_SYMTAB[21]
upx: id_000000,sig_11,src_000008,op_flip1,pos_51: CantPackException: bad .e_shstrndx 32796 >= .e_shnum 29

```
Fuzzing an input for compression by upx is not particularly interesting.  A crash there has no <i>security</i> implications at all; the SIGSEGV is merely a poor diagnostic error message for a "syntax error" in the input.  There is no output, so there is no threat of harm from the output.  So, no CVE for such an error.  If you want to be useful, then fuzz the input for de-compression (`upx -d`).  A bug  in de-compression represents a denial-of-service for a program which scans compressed code, looking for malware.  It's important that upx be able to de-compress reliably, because an administrator who cannot de-compress in order to run a malware detector just might ban <i>all</i> executables compressed by upx; we  don't want that.
