### ISSUE TITLE
Error with mips&mipsel shared library

### ISSUE THREAD

**Issue by hitsjt** [upx/upx#258]
## What's the problem (or question)?

I tried to use UPX 3.95 to pack shared libraries on linux that run on mips and mipsel.But I got **Trace/breakpoint trap on mips** and **segmentation fault on mipsel** when i ran the program that used the packed library.

## What should have happened?

The program that used the packed shared library should run normally.

## Do you have an idea for a solution?

Sorry, I do not have any idea.

## How can we reproduce the issue?

1.Here are the source files i used.
so_test.h
`#include "stdio.h"
void test_a();
void test_b();
void test_c();`

test_a.c
```
#include "so_test.h"

int const dummy_to_make_this_compressible[100000] = {1,2,3};

void test_a()
{
  printf("this is in test_a...\n");
}
```

test_b.c
`#include "so_test.h"
void test_b()
{
  printf("this is in test_b...\n");
}`

test_c.c
`#include "so_test.h"
void test_c()
{
  printf("this is in test_c...\n");
}`

test.c
`#include "so_test.h"
int main()
{
test_a();
test_b();
test_c();
return 0;
}`

2.(mips/mipsel)-gcc test_a.c test_b.c test_c.c -fPIC -shared -o libtest.so 
3.(mips/mipsel)-gcc test.c -L. -ltest -o test
4.Use UPX 3.95 to compress the libtest.so 
5.Run the program test

## Please tell us details about your environment.

* UPX version used (`upx --version`):3.95
* Host Operating System and version:Ubuntu 14.04_01 32bit
* Host CPU architecture:X86
* Target Operating System and version:Linux( kernel 3.18.21 for mipsel Kernel 2.6.36 for mips)
* Target CPU architecture:mips32 interAptiv for mipsel and mips32 34kc for mips

**Comment by jreiser** [comment]
Note to self: possible debugging environment: https://github.com/upx/upx/issues/200#issuecomment-410452385

**Comment by hitsjt** [comment]
@jreiser will you do some debugging recently?
Thanks.
