### ISSUE TITLE
Compressed notepad.exe with upx3.91 not working on windows7

### ISSUE THREAD

**Issue by brupelo** [upx/upx#26]
## What's the problem (or question)?

I've compressed notepad (64bit) on windows7 using upx 3.91 and the compressed executable won't run anymore, when I tried to open it with ollydbg it said "File notepad_upx.exe is probably not a 32-bit Portable Executable. Try to load it anyway?"

## What should have happened?

The compressed notepad_upx.exe should run normally as its uncompressed counterpart notepad.exe

## How can we reproduce the issue?

1. On windows7, copy c:\windows\notepad to another folder
2. upx -o notepad_upx.exe notepad.exe
3. Try to open it and see how nothing happens

## Please tell us details about your environment.

* UPX version used (`upx --version`):

upx 3.91
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Copyright (C) 1996-2013 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2013 Laszlo Molnar
Copyright (C) 2000-2013 John F. Reiser
Copyright (C) 2002-2013 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov

* Operating System and version:

Windows7-Ultimate 64bit SP1

* CPU architecture:

Intel core i7-4720HQ

**Comment by ml1050** [comment]
I do not have windows, can you attach your file here?

**Comment by Rikk** [comment]
@brupelo
Note: In the case of an unmodified _notepad.exe_, you also need to copy the corresponding _notepad.exe.mui_ file according to the language of your system, for the copy to work in any folder.
Ref: https://blogs.technet.microsoft.com/markrussinovich/2006/10/01/the-case-of-the-notepad-that-wouldnt-run/

Anyway, the UPX compressed file also doesn't work here in Win 8.1 (independently of the presence of _.mui_ file); tried with upx 3.92, 3.91 and 3.09.

@ml1050
I think system files may be trick to make work when they are changed. Maybe Windows has more checks...

In any case, I'm attaching 32bit and 64bit original and compressed _notepad.exe_
(Rename executable to "notepad.exe" when testing).
I have only pt-BR .mui file, but this file should not be needed for the error to trigger.

[notepad-upx.tar.gz](https://github.com/upx/upx/files/725528/notepad-upx.tar.gz)

Thanks

**Comment by Mattiwatti** [comment]
This has to do with resource compression; the `"MUI"` resource somehow does not get uncompressed correctly which causes `LoadStringW` to fail, regardless of .mui files being present or not. This in turn causes notepad to bail (nice error handling...). If you compress with `upx --compress-resources=0` you'll see that it works.
