### ISSUE TITLE
Encryption using external key

### ISSUE THREAD

**Issue by smipi1** [upx/upx#261]
## What's the problem (or question)?
Support AES encryption of the packed UPX data with an externally supplied key or passphrase.

I know the documentation states:
> We will NOT add any sort of protection and/or encryption.
> This only gives people a false feeling of security because
> by definition all protectors/compressors can be broken.
> And don't trust any advertisement of authors of other executable
> compressors about this topic - just do a websearch on "unpackers"...

The goal however is not better obfuscation, but better protection of- and control over the produced executable. Keeping the key / passphrase properly managed outside the packed executable does achieve this if coupled with proper security practices.

Claiming that any cipher can be broken should not be an excuse to force users to forego secrecy and trust practices altogether. The license already protects the developers from claims, and the documentation can be explicit about following proper security practices before attempting to use this.

## What should have happened?
Either:
1. Provide a passphrase when packing and running the packed executable.
1. Provide a keyfile when packing and running the packed executable.

The passphrase / keyfile can be provided as a command-line argument when running upx pack, and as an environment variable when running the packed executable.

## Do you have an idea for a solution?
1. Add AES CBC encryption of the compressed stream being added to the packed executable.
1. Use libssl to decrypt and decompress the packed stream before executing the executable.

## How can we reproduce the issue?
N/A

## Please tell us details about your environment.
N/A

**Comment by jreiser** [comment]
Try this first: compress using upx, encrypt the compressed result using the encryption of your choice, put the encrypted compressed file into a shell archive (/usr/bin/shar), then pre-pend a shell script that extracts, decrypts, and invokes the compressed program; using some secure directory as a temporary place to store the extracted and decrypted (but still compressed) file.  Except for the temporary directory, that's close to fulfilling the request.  It will provide a testbed for key management, for instance.  [Managing keys is a nightmare.]
It is fundamental to the operation of the UPX run-time decompression stub that the entire plain text of the program is re-created in memory before executing it.  This is a weakness that cannot be overcome: just intercept control at the "magic moment", then copy [formatted} from address space into a file.

**Comment by CycloneRing** [comment]
Create your own packer : https://www.codeproject.com/Articles/5317556/Creating-Your-Very-Own-x64-PE-Packer-Protector-fro
