### ISSUE TITLE
arm64-v8a so dlopen crash

### ISSUE THREAD

**Issue by chengrain** [upx/upx#265]
## What's the problem (or question)?

Before compression, dlopen will be successful.
## What should have happened?

load this compressed so file with dlopen will crash.

## How can we reproduce the issue?

1. Using upx to compress libhellojni.so with --android-shlib
2. In another so component to dlopen("libhellojni.so", RTLD_NOW);
3. It will crash

## Please tell us details about your environment.

* UPX version used (`upx --version`): I tried both upx dev branch and upx 3.95 version
* Host Operating System and version: Win10
* Host CPU architecture:  x64
* Target Operating System and version: Android 8
* Target CPU architecture: arm64-v8a 
[libhellojni.zip](https://github.com/upx/upx/files/3059293/libhellojni.zip)

**Comment by chengrain** [comment]
Hi Jreiser,
Sorry, I don't know how to generate crash log file.
I assume it can be duplicated easily in your side, right?

**Comment by chengrain** [comment]
BTW, after compression, I used readelf to parse it. And there is the following error:
readelf: Error: Reading 0x98 bytes extends past end of file for notes.

**Comment by jreiser** [comment]
Before compression, `readelf --all libhellojni.so >/tmp/foo` complains on stderr:
```
readelf: libhellojni.so: Warning: local symbol 3 found at index >= .dynsym's sh_info value of 3
readelf: libhellojni.so: Warning: local symbol 4 found at index >= .dynsym's sh_info value of 3
readelf: libhellojni.so: Warning: local symbol 5 found at index >= .dynsym's sh_info value of 3
```

**Comment by chengrain** [comment]
It is strange, I used readelf to parse libhellojni.so. And there are no such kind of warnings. I attached it for your reference. 
My readelf version is: GNU readelf (binutils-2.25-0666073) 2.25.51.20141117
[1.zip](https://github.com/upx/upx/files/3066182/1.zip)

**Comment by chengrain** [comment]
Hi @jreiser ,
Is there any update for this issue?
Thanks.

**Comment by jreiser** [comment]
The above commit has several tweaks for Android shared libraries.  How well does it work for you?

**Comment by chengrain** [comment]
Hi @jreiser ,
I used above committed code, but the problem is still here. 
It returned the following error when I debug to dlopen to load this compressed so.
_SIGILL (signal SIGILL: illegal instruction)_

**Comment by jreiser** [comment]
Please give a proper crash report: the contents of all registers, the subroutine call traceback, and the exact name and version number of the product in which the crash occurred.

**Comment by chengrain** [comment]
Hi @jreiser,
I just use another so to call this so. The code is like " handle = dlopen("libhellojni.so", RTLD_LAZY);"
In my side, I can't generate crash report. I have attached this so. 
I am using Android studio 3.3.2 to debug it. It just showed the following information.

Starting LLDB server: /data/data/com.example.hellojni/lldb/bin/start_lldb_server.sh /data/data/com.example.hellojni/lldb unix-abstract /com.example.hellojni-0 platform-1555342648772.sock "lldb process:gdb-remote packets"
Debugger attached to process 4172
Signal: SIGILL (signal SIGILL: illegal instruction)

It is Android 8 API 28.

**Comment by f4grx** [comment]
I also get a crash with upxed jnilibs on android arm64 and x86_64.

Crash is immediate when java code loads the native lib, there is no backtrace.

2019-07-02 11:58:12.320 26334-26334/? A/DEBUG: Build fingerprint: 'Sony/E6633/E6633:7.1.1/32.4.A.1.54/3761073091:user/release-keys'
2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: Revision: '0'
2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: ABI: 'arm64'
2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: pid: 26310, tid: 26310, name: redacted
2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x7f7ff6d764
2019-07-02 11:58:12.321 26334-26334/? A/DEBUG:     x0   0000000000000000  x1   0000000000073838  x2   0000000000000005  x3   00000000f9005ffe
2019-07-02 11:58:12.321 26334-26334/? A/DEBUG:     x4   ffffffffffffffff  x5   0000000000000000  x6   0000000000000000  x7   0000000000000000
2019-07-02 11:58:12.321 26334-26334/? A/DEBUG:     x8   00000000000000e2  x9   0000000000000001  x10  0000000000000018  x11  0000000000000000
2019-07-02 11:58:12.321 26334-26334/? A/DEBUG:     x12  0000000000000000  x13  0000007f8bb47000  x14  0000007f79d7d000  x15  0000007f8be1f000
2019-07-02 11:58:12.321 26334-26334/? A/DEBUG:     x16  0000007fee18fd80  x17  0000007fee18fc4f  x18  00000000ffffffff  x19  0000007f79d52b00
2019-07-02 11:58:12.321 26334-26334/? A/DEBUG:     x20  0000007f69995cd0  x21  0000007f8c035000  x22  0000007f8ba9c080  x23  0000007f8c035000
2019-07-02 11:58:12.321 26334-26334/? A/DEBUG:     x24  0000007f79a77600  x25  0000007f79a1ed40  x26  0000007f79a1ed50  x27  0000007f8803e0c0
2019-07-02 11:58:12.321 26334-26334/? A/DEBUG:     x28  0000007f880e9400  x29  0000007fee18ffc0  x30  0000007f7ff6d764
2019-07-02 11:58:12.321 26334-26334/? A/DEBUG:     sp   0000007fee18fee0  pc   0000007f7ff6d764  pstate 0000000000000000
2019-07-02 11:58:12.322 26334-26334/? A/DEBUG: backtrace:
2019-07-02 11:58:12.322 26334-26334/? A/DEBUG:     #00 pc 0000000000073764  <anonymous:0000007f7fefa000>

I am using the latest devel branch and the --android-shlib option

Crash report indicates signal 4 (SIGILL), code 1 (ILL_ILLOPC)

Notice both are 64-bit platforms. Could that be a bad code/stack alignment?

I will try to write a minimal test case.

**Comment by jreiser** [comment]
<i>Notice both are 64-bit platforms. Could that be a bad code/stack alignment?</i> The crash info ` sp 0000007fee18fee0 pc 0000007f7ff6d764` shows a 16-byte aligned `sp` and a 4-byte aligned `pc`, which should be good enough.

The complaints about `Displaying notes` are because the recorded offsets are `after` de-compression (so that they are valid after the upx stub disappears), but `readelf` is working on the compressed file.

The biggest help to me for all upx problems with Android would be getting a debugging environment that runs under Linux using x86_64, or 32-bit ARM, or 64-bit ARM hardware.  I don't have a real device running Android.  Right now I debug upx decompression for Android by running under Linux on RaspberryPi, creating symlinks to scrounged copies of Android shared libraries (or applying a binary editor to library names), etc.  Android Studio fails to install on Fedora Linux x86_64; I think it's because my $HOME is a symlink.  On Ubuntu Linux x86_64, the directions for installing and using Android Studio are incomplete (pieces are missing, requiring internet search and manual download+install), out-of-date (the menu items or locations have changed, and Help is not helpful), or just plain wrong.  The most helpful would be an install method that uses a shell script with literal URLs and good "error" diagnostics.  The goal is a text command-line environment (no GUI, or only ncurses "GUI", etc.) where something similar to "$ gdb foo.upx" brings up a debugger with a text interface that can start, breakpoint, single-step, display registers and memory. upx decompression does not require a GUI, and in fact a GUI gets in the way.  I want a text Terminal only.  [Yes: really simple, but I haven't found it yet.]

**Comment by f4grx** [comment]
Last time I tried with linux mint (based on ubuntu), android studio was a "simple" download-unzip-and-run, and it worked.

Would it be acceptable to run android studio in a virtual machine? it could be outrageously inefficient, but workaround all your specific environment problems... usb passthrough is functional with virtualbox, or you could debug using a virtual device.

I am not sure a full CLI debug system for android is possible... I really share your pain.

**Comment by jreiser** [comment]
I'll try Android Studio again, but how do I
```
1. Introduce a compressed-by-upx "external" program
    as an object known by the Studio which expects some conglomeration of sources, etc?
2. Start that program under a debugger?
```

**Comment by f4grx** [comment]
I know to do both separately but not really at once
-put the native libs in a "lib" folder and add this lib to gradle sources https://stackoverflow.com/questions/46908038/adding-existing-jni-libraries-already-compiled-so-to-another-android-studio/46908643

you can add some c++ source files to a android studio project and they will get compiled, then they can be debugged with breakpoints etc

I still dont know how to debug an EXISTING compiled native lib.

**Comment by Virenz** [comment]
> I also get a crash with upxed jnilibs on android arm64 and x86_64.
> 
> arm64 android 7
> x86_64 android 5
> ndk version 20
> I am using the latest upx devel branch and the --android-shlib option
> 
> Crash is immediate when java code loads the native lib, there is no backtrace.
> 
> 2019-07-02 11:58:12.320 26334-26334/? A/DEBUG: Build fingerprint: 'Sony/E6633/E6633:7.1.1/32.4.A.1.54/3761073091:user/release-keys'
> 2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: Revision: '0'
> 2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: ABI: 'arm64'
> 2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: pid: 26310, tid: 26310, name: redacted
> 2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x7f7ff6d764
> 2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: x0 0000000000000000 x1 0000000000073838 x2 0000000000000005 x3 00000000f9005ffe
> 2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: x4 ffffffffffffffff x5 0000000000000000 x6 0000000000000000 x7 0000000000000000
> 2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: x8 00000000000000e2 x9 0000000000000001 x10 0000000000000018 x11 0000000000000000
> 2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: x12 0000000000000000 x13 0000007f8bb47000 x14 0000007f79d7d000 x15 0000007f8be1f000
> 2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: x16 0000007fee18fd80 x17 0000007fee18fc4f x18 00000000ffffffff x19 0000007f79d52b00
> 2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: x20 0000007f69995cd0 x21 0000007f8c035000 x22 0000007f8ba9c080 x23 0000007f8c035000
> 2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: x24 0000007f79a77600 x25 0000007f79a1ed40 x26 0000007f79a1ed50 x27 0000007f8803e0c0
> 2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: x28 0000007f880e9400 x29 0000007fee18ffc0 x30 0000007f7ff6d764
> 2019-07-02 11:58:12.321 26334-26334/? A/DEBUG: sp 0000007fee18fee0 pc 0000007f7ff6d764 pstate 0000000000000000
> 2019-07-02 11:58:12.322 26334-26334/? A/DEBUG: backtrace:
> 2019-07-02 11:58:12.322 26334-26334/? A/DEBUG: #00 pc 0000000000073764 anonymous:0000007f7fefa000
> 
> Notice both are 64-bit platforms. Could that be a bad code/stack alignment?
> 
> Also note these warnings given by readelf (2.27.0.20170315):
> 
> Displaying notes found at file offset 0x0000f770 with length 0x00000024:
> Owner Data size Description
> readelf: Warning: note with invalid namesz and/or descsz found at offset 0x0
> readelf: Warning: type: 0x1, namesize: 0x00000008, descsize: 0x00000084
> 
> Displaying notes found at file offset 0x0000f770 with length 0x00000098:
> Owner Data size Description
> Android 0x00000084 NT_VERSION (version)
> 
> These warnings _do not_ appear with the original uncompressed SO file.
> 
> I will try to write a minimal test case. Before that, I will try to compile with ndk 19 in case last version 20 broke something.
> edit: it still fails with ndk 19.

I have the same problem

**Comment by yunshouhu** [comment]
I also encountered the same problem

**Comment by yunshouhu** [comment]
signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x7055e65fc0 
in Android 8.1 arm64

**Comment by weirenren** [comment]
i also  encountered the same problem, @jreiser have you fix it?
