### ISSUE TITLE
Request to add Linux shared library support 

### ISSUE THREAD

**Issue by DerrickChina** [upx/upx#27]
## What's the problem (or question)?
request to support Linux x86_64 shared library support

## What should have happened?
same with the problem

## Do you have an idea for a solution?
N/A

## How can we reproduce the issue?
N/A

## Help us understand your issue by providing context.
N/A

## Please tell us details about your environment.

* UPX version used (`upx --version`):  3.91
* Operating System and version: CentOS 6.7
* CPU architecture: x86_64

**Comment by jreiser** [comment]
Works for me by first linking the main executable with the not-compressed shared library, then compressing the shared library, then executing.  You should complain to libbfd and /bin/ld that they do not handle correctly the case (0==.e_shnum) [see \<elf.h\>].  Namely: libbfd and its clients should use the symbol information (and other information) in the execution view (ElfXX_Phdr[])  when the linking view (ElfXX_Shdr[])  is empty.
```
// ===== my_lib.c
int const x[10000] = {1,2,3};
int my_sub(int j)
{
	return x[j];
}
// ===== my_main.c
extern int my_sub(int);

int main(int argc, char *argv[])
{
	return my_sub(2);
}
# =====
$ gcc -fPIC -shared -o my_lib.so my_lib.c   # create shared library
$ gcc -o my_main my_main.c $PWD/my_lib.so   # link main program with not-compressed shared library
$ ./my_main   # execute with not-compressed shared library
$ echo $?  # print shell exit code of previous process
3     # x[2]     # expected result
$ upx my_lib.so   # compress the shared library
$ ./my_main   # re-execute with compressed shared library
$ echo $?
3     # x[2]     # same result as with not-compressed shared library
$ 
```
