### ISSUE TITLE
clang-cl+lld creates image fails to compress: "size of Load Configuration directory unexpected"

### ISSUE THREAD

**Issue by fefe17** [upx/upx#270]
## What's the problem (or question)?
I am using clang-cl on Linux to create Windows binaries. I'll upload a zipped hello world exe generated this way to https://ptrace.fefe.de/clangcl-helloworld.zip but this appears to be independent of the compiled code and related to the header structures generated by lld.

Here is the error message I'm getting:

upx: t.exe: CantPackException: size of Load Configuration directory unexpected

## What should have happened?
I was hoping upx could compress the file.

## Do you have an idea for a solution?
Nope, no idea.

## How can we reproduce the issue?
Run upx 3.95 on the t.exe from https://ptrace.fefe.de/clangcl-helloworld.zip

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

* Host Operating System and version:
Linux 5.1 (homebrew distro)
* Host CPU architecture:
amd64
* Target Operating System and version:
Windows 10
* Target CPU architecture:
x64

**Comment by jreiser** [comment]
The current tip of `devel` branch compresses clangcl-helloworld.zip for me.
