### ISSUE TITLE
"UnknownExecutableFormatException" when trying to pack an executable file on Raspbian Stretch most current version

### ISSUE THREAD

**Issue by martijintro** [upx/upx#271]
## What's the problem (or question)?
"UnknownExecutableFormatException" when trying to pack an executable file on Raspbian Stretch most current version -> "2019-04-08-raspbian-stretch-lite.zip"

## What should have happened?
Compression without any errors, equivalent to windows when i pack an executable with build on MSVC x32 or x64.

## Do you have an idea for a solution?
No - otherwise i would not ask here...;-)

## How can we reproduce the issue?
1. Entering  upx -9 ./p*****_master2

## Please tell us details about your environment.
* UPX version used (`upx --version`): 3.91
* Host Operating System and version: 2019-04-08-raspbian-stretch-lite
* Host CPU architecture: armhf
* Target Operating System and version: 2019-04-08-raspbian-stretch-lite
* Target CPU architecture: armhf

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") `./practiframe_master2` or other file which reproduces the issue.  Apply gzip before uploading, so that github accepts the file.

**Comment by martijintro** [comment]
file is not for public, can i send it with mail to you?

and: can you rename "p**********_master2" on both (yours and mine) entries? i've forgot to "censor" it.

thx for feedback.

**Comment by jreiser** [comment]
Yes: attach to a private email message.  Look at the git log for the `devel` branch for my address.

**Comment by jreiser** [comment]
The tip of `devel` branch works for me:
```
../upx.out -f -o foo p*****2
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2019
UPX git-497663+ Markus Oberhumer, Laszlo Molnar & John Reiser   Feb 24th 2019

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1245008 ->    406660   32.66%    linux/arm    foo                           

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
```

**Comment by martijintro** [comment]
thank you very much, will try it!

**Comment by martijintro** [comment]
for compile, i expanded it and switched to directory upx-devel/src, then executed "make".

then i got a message: "*** ERROR: missing directory src/lzma-sdk/; visit https://github.com/upx/upx-lzma-sdk"

then i downloaded https://github.com/upx/upx-lzma-sdk/archive/master.zip and expanded it. after that, i renamed the expanded dir to "lzma-sdk" (before it was "upx-lzma-sdk-master") then i moved the renamed dir to upx-devel/src.

after that, i got still the same message:  *** ERROR: missing directory src/lzma-sdk/; visit https://github.com/upx/upx-lzma-sdk

how to compile it? thx.

**Comment by martijintro** [comment]
oh no i was wrong, there was a problem with moving.

but after correction, i get these errors:

In file included from p_lx_sh.cpp:33:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_mach.cpp:28:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
^XIn file included from p_ps1.cpp:33:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from p_sys.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"

**Comment by jreiser** [comment]
```
$ set | grep UPX
UPX_LUADIR=/path/to/lua-5.1.1
UPX_LZMADIR=/path/to/lzma1509
UPX_LZMA_VERSION=0x1509
UPX_UCLDIR=/path/to/ucl-1.03
```
See also README.SRC at the top level of the source tree.

**Comment by martijintro** [comment]
it almost compiles to the end with that settings, then i get:

/usr/bin/ld: cannot find -lucl
collect2: error: ld returned 1 exit status
Makefile:86: recipe for target 'upx.out' failed
make: *** [upx.out] Error 1


commands i executed with script:

```
#!/bin/bash
chmod +x ./buildvars.sh;
set -x > /dev/null 2>&1;  # Define script execution output behavior
export UPX_LUADIR=/root/lua-5.1.1;
export UPX_LZMADIR=/root/lzma1509;
export UPX_LZMA_VERSION=0x1509;
export UPX_UCLDIR=/root/ucl-1.03;
exit 0;
```

**Comment by martijintro** [comment]
when i try to compile again, i get that message agan, even after "make clean":

```
Updating .depend
In file included from c_file.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from c_init.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
In file included from c_none.cpp:29:0:
conf.h:140:6: error: #error "please upgrade your UCL installation"
 #    error "please upgrade your UCL installation"
      ^~~~~
^Cmake: *** Deleting file '.depend'
```

**Comment by martijintro** [comment]
using echo does also not help:

```
#!/bin/bash
chmod +x ./buildvars.sh;
set -x > /dev/null 2>&1;  # Define script execution output behavior
echo export UPX_LUADIR=/root/lua-5.1.1;
echo export UPX_LZMADIR=/root/lzma1509;
echo export UPX_LZMA_VERSION=0x1509;
echo export UPX_UCLDIR=/root/ucl-1.03;
exit 0;
```

https://stackoverflow.com/questions/11076350/how-do-you-export-a-variable-through-shell-script

**Comment by martijintro** [comment]
it was a problem with shell script, does not work - neither with "echo", nor without...

but that problem is stll present:
```
/usr/bin/ld: cannot find -lucl
collect2: error: ld returned 1 exit status
Makefile:86: recipe for target 'upx.out' failed
make: *** [upx.out] Error 1`

```

**Comment by martijintro** [comment]
https://forum-raspberrypi.de/forum/thread/43118-export-in-shell-scripts/#post380040

**Comment by jreiser** [comment]
Did you build libucl.a ?  The build command for upx.out ends with
```
g++   ...   work.o -L$UPX_UCLDIR/src/.libs/ -lucl -lz
```
which means that the archive library of subroutines should be `$UPX_UCLDIR/src/.libs/libucl.a`.  See the upx/src/Makefile:
```
# we need UCL and zlib - you can set envvar UPX_UCLDIR
ifneq ($(wildcard $(UPX_UCLDIR)/include/ucl/ucl.h),)
INCLUDES += -I$(UPX_UCLDIR)/include
LIBS += $(addprefix -L,$(dir $(wildcard $(UPX_UCLDIR)/libucl$(libext) $(UPX_UCLDIR)/src/.libs/libucl$(libext))))
endif
LIBS += -lucl -lz
```
See the file $UPX_UCLDIR/INSTALL.  So, something like:
```
$ cd $UPX_UCLDIR
$ ./configure 
$ make
$ sudo make install  # not necessary for just buildling upx
```

**Comment by martijintro** [comment]
Note: ucl-1.03 with gcc 6.x need that flag:

export CPPFLAGS="$CPPFLAGS -std=c90 -fPIC"



-> https://github.com/Distrotech/ucl/issues/1

**Comment by martijintro** [comment]
Works:

```
root@localhost:~/upx-devel/src# ./upx.out -9 /root/deployment/Temp/PF_CPPP/xxx_master/xxx_master2
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2019
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Feb 24th 2019

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1245008 ->    400988   32.21%    linux/arm    xxx_master2

Packed 1 file.
```

**Comment by jreiser** [comment]
This issue is one that most programmers are expected to solve in the ordinary course of work.

**Comment by xxrz** [comment]
> it was a problem with shell script, does not work - neither with "echo", nor without...
> 
> but that problem is stll present:
> 
> ```
> /usr/bin/ld: cannot find -lucl
> collect2: error: ld returned 1 exit status
> Makefile:86: recipe for target 'upx.out' failed
> make: *** [upx.out] Error 1`
> ```

I would like to ask you how to solve this problem? The reason for this problem is that UCL is not compiled correctly?

**Comment by jayjupdhig** [comment]
so still unsolved...??

**Comment by xxrz** [comment]
> so still unsolved...??

I am sad that it is indeed, and I confirm that my UCL compilation is successful, but I can't find the reason for the error. I hope to get your help.

**Comment by jayjupdhig** [comment]
me too!!

**Comment by xxrz** [comment]
Oops! I saw that you generated upx.out in your previous reply, and I mistakenly thought you solved the problem successfully. : ( On 11/09/2020 18:01, jayjupdhig wrote: 
me too!!

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/upx/upx/issues/271#issuecomment-723906748",
"url": "https://github.com/upx/upx/issues/271#issuecomment-723906748",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
