### ISSUE TITLE
Can't pack mips64 linux elf file.

### ISSUE THREAD

**Issue by jiapan1984** [upx/upx#272]
## What's the problem (or question)?

upx -o http_client.elf.upx http_client.elf
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95w       Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: http_client.elf: UnknownExecutableFormatException

Packed 0 files.
## What should have happened?

Can't pack mips64 binary file
upx: http_client.elf: UnknownExecutableFormatException

## Do you have an idea for a solution?

No idea
## How can we reproduce the issue?

It can't work.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
upx -V
upx 3.95
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Copyright (C) 1996-2018 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2018 Laszlo Molnar
Copyright (C) 2000-2018 John F. Reiser
Copyright (C) 2002-2018 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
* Host Operating System and version:
Windows 7 X86 64
* Host CPU architecture:
X86 64, i386
* Target Operating System and version:
Linux (none) 2.6.32.13-Cavium-Octeon #1 SMP Thu May 9 01:10:30 CST 2019 mips64 unknown
* Target CPU architecture:
mips64
* Target File info
http_client.elf: ELF 64-bit MSB executable, MIPS, MIPS64 rel2 version 1 (SYSV),dynamically linked (uses shared libs), for GNU/Linux 2.6.10, with unknown capability 0x410000000f676e75 = 0x1000000070403, not stripped

[a.txt](https://github.com/upx/upx/files/3166699/a.txt)

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") an actual executable file which reproduces the problem.  Compress with gzip before uploading, so that github will accept the file.

**Comment by jreiser** [comment]
This file probably will work.  Compile, link, gzip, and upload:
```
int const x[10000] = {1};
int main(int argc, char *argv[]) { return 0; }
```

**Comment by jiapan1984** [comment]
file test.elf 
test.elf: ELF 64-bit MSB executable, MIPS, MIPS64 rel2 version 1 (SYSV), dynamically linked, interpreter /lib64/ld.so.1, for GNU/Linux 2.6.10, not stripped

ls -la test.*
-rw-rw-r-- 1 jiapan jiapan    73 May 10 23:38 test.c
-rwxrwxr-x 1 jiapan jiapan 50635 May 10 23:38 test.elf

[test.elf.zip](https://github.com/upx/upx/files/3168709/test.elf.zip)

**Comment by jiapan1984** [comment]
when i use go build gin for mips64 linxu , it can also reproduce the issue：

C:\Users\jiapan\go>env GOOS=linux GOARCH=mips64 go build  -ldflags "-s -w" gin-test.go

C:\Users\jiapan\go>ls -la gin*
-rw-r--r-- 1 jiapan Administrators 12717824 May 11 15:40 gin-test
-rwxr-xr-x 1 jiapan Administrators 15310336 May 11 15:26 gin-test.exe
-rw-r--r-- 1 jiapan Administrators      188 Apr 30 15:25 gin-test.go

C:\Users\jiapan\go>upx -o gin-test.elf gin-test
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95w       Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: gin-test: UnknownExecutableFormatException

Packed 0 files.

**Comment by jreiser** [comment]
64-bit MIPS is not supported yet.

**Comment by yuxiaokui** [comment]
When can upx support 64-bit MIPS?

**Comment by jreiser** [comment]
These are the requirements:
```
1. Free (as in libre) and free (as in beer) and readily-available
   downloadable documentation of the user-mode instruction set
   for the specific CPU variants that matter.
2. A cross-compiler for C language, a cross-assembler
   for MIPS64 assembly language, and a cross-loader for MIPS64
   relocatable object files, that runs on Fedora or Debian
   Linux for x86_64, and produces executable ELF for MIPS64.
   Also a readelf utility that understands such ELF files.
3. A qemu package for x86_64 Fedora or Debian Linux that
   emulates a user-mode MIPS64 program, and a gdb server
   for MIPS64 that runs on x86_64 Linux.
4. The individual binary shared libraries and runtime loader(s)
   that are required for usual user-mode MIPS64 programs,
   such as libc.so and ld-linux.so.
```
Downloads must be specified by explicit literal URL of an actual instance.  `Finding` the downloads has been a problem in the past.

**Comment by knuckolls** [comment]
@jreiser I admittedly may be misunderstanding a bit of this but I use gcc to make mips64 binaries in a variety of variations. musl-cross-make [1] got me some toolchains for experimenting with. I understand that this is musl based, but I believe these may help as well: the modern version of gcc used in that toolchain generator, the gcc mips specific documentation [2], and this qemu mips64 gist [3].

Compiling a non-musl libc & kernel is surely possible but I don't have a link handy. Hopefully someone in the future finds this helpful.

[1] https://github.com/richfelker/musl-cross-make
[2] https://gcc.gnu.org/onlinedocs/gcc-9.2.0/gcc/MIPS-Options.html
[3] https://gist.github.com/sergev/1cb8abf6d64c63378cca1bed00bdd4d2

**Comment by markus-oberhumer** [comment]
MIPS64 is currently not supported, and there are no plans to work on it, so `wontfix` for now.
