### ISSUE TITLE
CantPackException: writable shared sections not supported

### ISSUE THREAD

**Issue by fawdlstty** [upx/upx#273]
## What's the problem (or question)?

![20190517095838](https://user-images.githubusercontent.com/7323999/57898145-68c3e780-788a-11e9-8149-53b9b081a614.png)

## What should have happened?

successfully compress

## Do you have an idea for a solution?

no

## How can we reproduce the issue?

use visual studio 2017 and compile this code

```cpp
#pragma comment (linker, "/SECTION:share,RWS")
#pragma data_seg ("share")
#pragma data_seg ()
__declspec (allocate ("share")) volatile int g_share = 0;

//...hello world...
```

## Please tell us details about your environment.
* UPX version used (`upx --version`):3.95
* Host Operating System and version: Win7 x64 SP1 (7601)
* Host CPU architecture: Intel i5-3470
* Target Operating System and version: Win7 x64 SP1 (7601)
* Target CPU architecture: Intel i5-3470

**Comment by jreiser** [comment]
The operating system and run-time process instantiator do not document when the sharing begins.  If before the upx stub gains control, then that is too early.  If after the stub gains control, then there is a race to finish the de-compression, with no guarantee that upx will win against other processes.  Either way is a loss.

**Comment by fawdlstty** [comment]
Maybe we can skip this section

**Comment by Mattiwatti** [comment]
> Maybe we can skip this section

And pray the executable will still work somehow? That is not compression but truncation.

> The operating system and run-time process instantiator do not document when the sharing begins.

The 'sharing' technically only begins when another process using the same image section is started, but I guess that is obvious. The 'can this be shared' flag however already takes effect when the protection is set on the page table entry in the kernel by `NtCreateSection`. This happens before the process is created. So yes, too early.

**Comment by fawdlstty** [comment]
or do not compress shared section, if try decompile failed, ignore the section

**Comment by pingogeek** [comment]
pls attach compiled binary to test

**Comment by greenozon** [comment]
Hi, sorry for bumping up closed issue (but without solution)
here is a test dll that has the same case:

```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.2       Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 30th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: test1.DLL: CantPackException: writable shared sections not supported (try --force)

Packed 1 file: 0 ok, 1 error.
```

https://www.sendspace.com/file/fzd38t

@pingogeek 
@jreiser

**Comment by markus-oberhumer** [comment]
Sorry, but this issue is closed `wontfix`.
