### ISSUE TITLE
dotnet app with feature PublishSingleFile fails to start

### ISSUE THREAD

**Issue by dhcgn** [upx/upx#274]
## What's the problem (or question)?
I packed an application that was created with the dotnet feature **PublishSingleFile**, this application is not running under windows and linux. 

## What should have happened?
The packed files should be able to run.

## How can we reproduce the issue?

1. Download and install [SDK 3.0.100-preview5-011568](https://dotnet.microsoft.com/download/dotnet-core/3.0)
2. Create a Hello World Sample with: `dotnet new console`
3. Publish this for linux in a single file `dotnet publish -c Release -r linux-x64 /p:PublishSingleFile=true`
4. Publish this for windows in a single file `dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true`
5. Pack the files 
`upx.exe --lzma "C:\DEV\PublishSingleFileExample\bin\Release\netcoreapp3.0\win-x64\publish\PublishSingleFileExample.exe"` and 
`upx.exe --lzma "C:\DEV\PublishSingleFileExample\bin\Release\netcoreapp3.0\linux-x64\publish\PublishSingleFileExample"`
6. Try to run these files

All files are here:
[PublishSingleFileExample.zip (150MB)](https://mega.nz/#!t1thiSwR!ANP0JHCS6xcfm1c_Qvc3FtslfLf1DaRZYg-U5_BEmyE)

I opened an similar issue at dotnet/coreclr (https://github.com/dotnet/coreclr/issues/24543) but because the packed application is not running I hope you can help.

## Please tell us details about your environment.

* UPX version used (`upx --version`): UPX 3.95w
* Host Operating System and version:  Microsoft Windows 10 Pro (10.0.17763)
* Host CPU architecture: x64-based PC
* Target Operating System and version: same as above
* Target CPU architecture: same as above

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") something smaller than 150MB that triggers the problem; how about "Hello World Sample"?  Apply zip or gzip before uploading, so thtat github accepts the file.

**Comment by dhcgn** [comment]
The "Hello World" Sample is nearly 70 MB and the upload limit here is 10 MB.

See here [PublishSingleFileExample.zip (150MB)](https://mega.nz/#!t1thiSwR!ANP0JHCS6xcfm1c_Qvc3FtslfLf1DaRZYg-U5_BEmyE)

1. `PublishSingleFileExample\bin\Release\netcoreapp3.0\win-x64\publish` 
1. `PublishSingleFileExample\bin\Release\netcoreapp3.0\linux-x64\publish`

**Comment by dhcgn** [comment]
### dotnet version

```
PS C:\DEV\dotnetconsolesample> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614
```
 
### upx version

```
PS C:\DEV\dotnetconsolesample> upx -V
upx 3.96
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
```

### Steps (pwsh)

1. Create folder:  mkdir dotnetconsolesample; cd .\dotnetconsolesample\
3. Create console project: dotnet new console
4. Publish single file: dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true
5. Test single file: .\bin\Release\net6.0\win-x64\publish\dotnetconsolesample.exe
6. Compress executable: upx --lzma .\bin\Release\net6.0\win-x64\publish\dotnetconsolesample.exe
7. Test compresse executable.\bin\Release\net6.0\win-x64\publish\dotnetconsolesample.exe

#### Error

Console:
```
ResourceUnavailable: Program 'dotnetconsolesample.exe' failed to run: An error occurred trying to start process 'C:\DEV\dotnetconsolesample\bin\Release\net6.0\win-x64\publish\dotnetconsolesample.exe' with working directory 'C:\DEV\dotnetconsolesample'. The parameter is incorrect.At line:1 char:1
+ .\bin\Release\net6.0\win-x64\publish\dotnetconsolesample.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
```

Explorer:
![image](https://user-images.githubusercontent.com/6566207/184592550-71ca7670-a0e7-45e6-b958-089c912fca0e.png)
