### ISSUE TITLE
"error while loading shared libraries", "Unable to run arch-specific checks"

### ISSUE THREAD

**Issue by martijintro** [upx/upx#275]
## What's the problem (or question)?
upx can't compress .so libraries on raspbian stretch. (must current version on 2019-05-21)

## What should have happened?
The executable that uses the library should work without any problems...

## Do you have an idea for a solution?
No, otherwise i would not ask here

## How can we reproduce the issue?
1. Compress the libraries with parameter:
/root/deployment/Tools/upx/upx --android-shlib -9 ./libxxx.so;
...i've got that parameter recommendation from UPX itself!! Without it, the file size (compressed file) will be a few bytes... 

2. Run the executable that uses these libraries, then get that message:
"./xxx: error while loading shared libraries: /usr/lib/libxxx.so: Unable to run arch-specific checks"

## Please tell us details about your environment.
* UPX version used (`upx --version`): 3.96, compiled by myself
* Host Operating System and version: Raspbian Stretch, most current edition on 2019-05-21)
* Host CPU architecture: armhf
* Target Operating System and version:  Raspbian Stretch, most current edition on 2019-05-21)
* Target CPU architecture: armhf

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") an actual shared library that triggers the problem.  Apply gzip before uploading, so that github will accept the file.  If that is not possible then please show the output from `readelf --segments --dynamic libxxx.so`

**Comment by martijintro** [comment]
[Compressed libraries with problems.zip](https://github.com/upx/upx/files/3206219/Compressed.libraries.with.problems.zip)

**Comment by jreiser** [comment]
Raspbian Stretch is not an Android OS, so `--android-shlib` is not appropriate, so do not use that command-line option when compressing for a target system that runs Raspbian Stretch.  Android claims to be a `OS/ABI:   UNIX - System V` system (readelf --headers) but has a run-time linker that does not follow the ELF specification, and has no other `readelf --dynamic` flags that are definitive for "I am a shared library to be run on Android", so upx must be told.  Forgetting to specify `--android-shlib` is the number one mistake when compressing for Android, hence the reminder.

**Comment by martijintro** [comment]
thank you for your feedback. problem solved by leave the libraries uncompressed...;-)

**Comment by martijintro** [comment]
...i can confirm that UPX v3.96 works without any problems on Raspbian Stretch for executables. (But not for libraries, maybe there was never support for linux armhf .so-files?) The author warned me via mail i should not use it for productive systems, but i think i tested it well enough to say that...;-)

**Comment by jreiser** [comment]
UPX does support compressing .so shared libraries for armhf on linux.  In the https://github.com/upx/upx/files/3206219/Compressed.libraries.with.problems.zip of 21 days ago https://github.com/upx/upx/issues/275#issuecomment-494692750 the three already-compressed libxaxadevka.so  libxshedler.so  libyoctobob.so can be de-compressed and re-compressed using the tip of `devel` branch.  If there are problems with execution then please submit a recipe for test case execution which reproduces a problem.

**Comment by martijintro** [comment]
ok thx
