### ISSUE TITLE
UPX 3.95 cannot pack 64-bit (x64) executable built with Visual Studio 2019.

### ISSUE THREAD

**Issue by dbjh** [upx/upx#277]
## What's the problem (or question)?
UPX 3.95 cannot pack 64-bit (x64) executable built with Visual Studio 2019.

## What should have happened?
UPX should be able to pack 64-bit (x64) executables built with Visual Studio 2019, just like it is able to pack 32-bit (x86) executables.

## How can we reproduce the issue?
1. Compile attached hello.c with Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64:
 a. "%VS160COMNTOOLS%\..\..\VC\Auxiliary\Build\vcvarsall.bat" x64
 b. cl hello.c
2. Try to compress the resulting hello.exe:
  upx hello.exe
3. Observe UPX's behavior:
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95w       Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: hello.exe: CantPackException: size of Load Configuration directory unexpect
ed

Packed 1 file: 0 ok, 1 error.

## Please tell us details about your environment.
* UPX version used (`upx --version`):
upx 3.95
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Copyright (C) 1996-2018 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2018 Laszlo Molnar
Copyright (C) 2000-2018 John F. Reiser
Copyright (C) 2002-2018 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.

* Host Operating System and version:
Windows 7 Home Basic & Windows 10 Enterprise version 1803.

* Host CPU architecture:
x86-64.

* Target Operating System and version:
Windows 7 Home Basic & Windows 10 Enterprise version 1803.

* Target CPU architecture:
x86-64.

I have attached an executable built with the command mentioned above and renamed it to hello-vs2019-x64.exe. I have compressed it with gzip.

I have also attached an executable built with:
"%VS160COMNTOOLS%\..\..\VC\Auxiliary\Build\vcvarsall.bat" x86
cl hello.c
The compiler in that case is Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86. The linker version in both cases is Microsoft (R) Incremental Linker Version 14.00.24215.1
I renamed that hello.exe to hello-vs2019-x86.exe. I have compressed it with gzip. That executable can be packed fine with UPX 3.95.

[hello.c.gz](https://github.com/upx/upx/files/3250280/hello.c.gz)
[hello-vs2019-x64.exe.gz](https://github.com/upx/upx/files/3250281/hello-vs2019-x64.exe.gz)
[hello-vs2019-x86.exe.gz](https://github.com/upx/upx/files/3250282/hello-vs2019-x86.exe.gz)

**Comment by jreiser** [comment]
Same as https://github.com/upx/upx/issues/270 and others.  Compression succeeds with the tip of `devel` branch.
