### ISSUE TITLE
upx adds environment variable with empty key

### ISSUE THREAD

**Issue by stefan-improbable** [upx/upx#278]
## What's the problem (or question)?

I have a file `main.go`

```go
package main

import (
	"fmt"
	"os"
	"strings"
)

func main() {
	fmt.Printf("%v\n", strings.Join(os.Environ(), "\n"))
}
```

If I run `go build main.go && upx main && ./main` , I can see an environment variable with empty key in the output:
```
   =/home/stefan/usr/upx_test/main
```
, which I don't see if I don't use `upx`.

## What should have happened?

An environment variable with empty key should not have been exported.

## Do you have an idea for a solution?

No.

## How can we reproduce the issue?

Compile `main.go` with go1.11.5 on linux/amd64, upx it and run the resulting binary. You should see an environment variable with empty key on the output.

## Please tell us details about your environment.
* UPX version used (`upx --version`): 3.95
* Host Operating System and version: ubuntu 18.04 LTS
* Host CPU architecture: amd64
* Target Operating System and version: ubuntu 18.04 LTS
* Target CPU architecture: amd64

**Comment by jreiser** [comment]
This is by design, at the request of many users.  The name of the environment variable is '\x20\x20\x20' (three spaces).  The value is  readlink() of the path of the executable, which otherwise would disappear because upx replaces *ALL* of the originally-mmap()ed pages.

**Comment by stefan-improbable** [comment]
@jreiser would it be possible to add a flag to upx to disable this behaviour? A software we depend on is parsing output of `export -p` executed by `bash`. On ubuntu 16.04, this program
```go
package main

import (
        "os"
        "os/exec"
)

func main() {
        os.Setenv("   ", "/x/y/z")

        c := exec.Command("/bin/bash", "-c", "export -p")
        c.Stdout = os.Stdout
        c.Stderr = os.Stderr
        c.Run()
}
```
displays
```bash
declare -x    
declare -x HOME="/home/myself"
...
```
The first line does not consist of key-value pair, so the parsing fails. bash on ubuntu 18.04 does not show this variable in `export -p` output.

**Comment by jreiser** [comment]
What is the value of `$BASH_VERSINFO` on that ubuntu 18.04 system that does not show the three-spaces variable in the output of `export -p`?
The manual page "man bash" says
```
if the -p  option is  supplied,  a  list  of names of all exported variables is printed

**Comment by stefan-improbable** [comment]
`$BASH_VERSINFO` prints 4. I actually think that bash on 16.04 is broken, because bash variable names can't contain spaces. According to http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html:

> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit.

Thanks for the tips, I think we'll just unexport that variable then.
