### ISSUE TITLE
Compression ratio differs between Windows and Linux

### ISSUE THREAD

**Issue by tobiaskarnat-remondis** [upx/upx#281]
## What's the problem (or question)?
Compression ratio differs between Windows and Linux version.
Windows version is always more efficient (with any tested Go-binary).

## What should have happened?
Linux version should be as efficient.

## Do you have an idea for a solution?
None at the moment.

## How can we reproduce the issue?
1. 
```
# go version       
go version go1.12.7 linux/amd64
# go build -ldflags="-w -s" hello.go
```
Src: https://tour.golang.org/welcome/1

2.
```
>upx.exe --best hello
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95w       Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1406880 ->    492648   35.02%   linux/amd64   hello

Packed 1 file.
```
2.
```
# upx --best hello
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1406880 ->    531240   37.76%   linux/amd64   hello                         

Packed 1 file.
```

## Please tell us details about your environment.
* UPX version used (`upx --version`):
```
upx.exe --version
upx 3.95
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
```
```
upx --version
upx 3.95
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
```
* Host Operating System and version:
Windows 10
Ubuntu 18.04.2 (inside WSL)

* Host CPU architecture:
 x86-64

* Target Operating System and version:
Linux

* Target CPU architecture:
 x86-64

**Comment by bitraid** [comment]
As you can see, your linux version is build with different/missing compression libraries. Use the binaries from https://github.com/upx/upx/releases. You can also use `--ultra-brute` to get the smallest size.

**Comment by tobiaskarnat-remondis** [comment]
The binary does not run in WSL:
```
# md5sum upx
a5d210943da9dcf79448c7817bddf54e  upx
# ./upx
-bash: ./upx: cannot execute binary file: Exec format error
```

After compiling the source, it does run. But with the same result (and missing NRV).
What development library do I need to install to also have NRV available?

**Comment by bitraid** [comment]
There isn't any.  From `README.SRC`:
>The precompiled UPX versions are linked against the NRV compression
  library instead of the UCL library. Using the same compression algorithms,
  NRV achieves a better compression ratio. NRV is not publicly
  available, though, and probably never will be.

For larger files, lzma (`--lzma`) usually provides better compression ratio.

**Comment by tobiaskarnat-remondis** [comment]
Oh I see. Using --lzma seems to be the fastest and with best results.
