### ISSUE TITLE
FreeBSD 12.0 UnknownExecutableFormatException

### ISSUE THREAD

**Issue by claytonjwong** [upx/upx#288]
## What's the problem (or question)?
When I run upx on a freebsd binary, I see a UnknownExecutableFormatException

## What should have happened?
I'd like to see successful output of a compressed freebsd binary

## Do you have an idea for a solution?
No

## How can we reproduce the issue?
run the command ```upx -q --ultra-brute``` on a freebsd binary

## Please tell us details about your environment.

* UPX version used (`upx --version`): latest version currently available from apk ( added to docker on demand, ie. RUN apk add --no-cache upx )
* Host Operating System and version: Debian 9
* Host CPU architecture: 
* Target Operating System and version: FreeBSD 12.0
* Target CPU architecture: amd64

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") an actual file that triggers the complaint; perhaps /bin/date, or something else that is a small ELF file..  Apply gzip before uploading, so that gitlab will accept it.

**Comment by jreiser** [comment]
No actual file which triggers the complaint has been uploaded.  The issue must not be important.

**Comment by davidnewhall** [comment]
This dups #111. Same problem here. I +1d that old, currently open, issue.
