### ISSUE TITLE
Cannot pack perl PAR::Packer executables

### ISSUE THREAD

**Issue by noobposter123** [upx/upx#289]
## What's the problem (or question)?

When I try to pack a 32 bit Windows executable generated with PAR::Packer using upx 3.95 (32 bit and 64 bit) the resulting executable is successfully shrunk and packed. However when I run the executable I get the following error messages:
IO error: reading header signature :
 at -e line 603.
IO error: reading header signature :
 at -e line 595.
...
mkdir C:\Users\ADMINI~1\AppData\Local\Temp\par-41646d696e6973747261746f72\cache-287b72321943f32b96f721e8c8356c9fd1949556\inc\script\: File exists; Cannot create a file when that file already exists at C:/strawberry/perl/vendor/lib/Archive/Z
ip/Archive.pm line 196.

## What should have happened?

The executable should successfully unpack the resources to the temp dir and run.

## Do you have an idea for a solution?

I suspect the upx packed exe can't read (I/O error) the pp packed resources in order create and populate the directories properly, and zero length files are created instead.
Maybe need the PAR::Packer team to improve compatibility with upx.

## How can we reproduce the issue?

1. Install strawberry perl 32 bit on Windows 10 (use the add perl to environment and path option) 
2. run cpan install pp to install PAR::Packer and dependencies
3. Create a simple helloworld.pl file
4. pp helloworld.pl -o helloworld.exe
5. install upx 3.95w 32 bit
6. upx helloworld.exe
7. Run the generated helloworld.exe on another system or the same system.

Note: you won't get an error from running the upx packed exe if you run the non-upx packed pp generated exe first on the target system because that non-upx exe will successfully create and populate the temp directories.
Note 2: you will get an error if you run the non-upx packed exe after running the upx packed exe first since the non-upx exe does not overwrite the zero length files with directories. You will have to delete the temporary par directories in the temp folder to successfully run the non-upx exe.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
3.95w and 3.91w
* Host Operating System and version:
Microsoft Windows [Version 10.0.17763.615] Windows 10 64 bit
Strawberry Perl 5.30.0.1-32bit
* Host CPU architecture:
Intel x86 64 bit
* Target Operating System and version:
Microsoft Windows [Version 6.1.7600] Windows Server 2008 R2 64 bit
* Target CPU architecture:
Intel x86 64 bit

**Comment by noobposter123** [comment]
Attached are the exes and source for reference

[hello.zip](https://github.com/upx/upx/files/3434088/hello.zip)

**Comment by obetz** [comment]
Since most of the contents of a PAR/pp packed executable are already compressed, using upx on it seems to be pointless to me. In the end, all the Perl stuff is unpacked to %temp%, anyway.

**Comment by noobposter123** [comment]
1) You can see from the supplied zip file the upx packed exe is less than 50% the size of the original pp exe. Running upx -d on the upx compressed executable produces a working executable, so upx isn't throwing away data required to run.
2) Whether stuff in the exe is ultimately unpacked to %TEMP% or %ProgramFiles% or elsewhere seems irrelevant to the issue.

**Comment by necros2k7** [comment]
Agree, any size reduction is a goodness.

**Comment by bitraid** [comment]
Executables with overlays must be able to correcty detect the offset of the overlay (when the size changes) in order to work. There isn't something upx can do.

**Comment by necros2k7** [comment]
any possibility to reopen?

**Comment by bitraid** [comment]
@markus-oberhumer There is no reason to keep this open. As I previously commented, this is a case of a program trying to access itself from disk. The executable has a zip archive as overlay data, which contains the perl runtimes and scripts, and are extracted to tmp and executed at runtime. Since overlay data are not loaded in memory upon program execution, upx does not pack/unpack them, but copies them by default (unless `--overlay=strip` is used), so if the program could detect its location at runtime (since its offset has changed from compression), it could still function (something that most self-extracting archives do). But this program expects to find it at a specific offset, thus the `header signature error`. So, this should actually be  feature request for https://github.com/rschupp/PAR-Packer.
