### ISSUE TITLE
Compressed electron.exe fails on Windows 7 and 10

### ISSUE THREAD

**Issue by mingyuan-xia** [upx/upx#29]
## What's the problem (or question)?

upx compressed electron.exe fails on Windows 7 and WIndows 10.

## What should have happened?

compressed version should work as usual.

## Do you have an idea for a solution?

No, no idea why that happens.

## How can we reproduce the issue?

1. Download the electron.exe from https://github.com/electron/electron/releases 
e.g., electron-v1.4.8-win32-x64.zip
2. compress it with upx
3. run the compressed version, failed

I also tried 1.4.0, 1.4.2. All fail. 
Related issue: https://github.com/electron/electron/issues/5506

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Operating System and version:
Windows 7 and Windows 10
* CPU architecture:
x64

**Comment by ml1050** [comment]
Unfortunately I can not test this file, because the .zip file does not contain all the DLLs that are needed by electron.exe (for example: UIAutomationCore.DLL) .

**Comment by AraHaan** [comment]
Well electron is open source on github as well so I don't see why building that from source would not generate an electron process almost byte identical?

**Comment by ml1050** [comment]
I do not have Windows. I can only test PE files under linux + wine. There is no UIAutomationCore.DLL in wine, so I can not test it. Can you attach your copy of this file here?

**Comment by AraHaan** [comment]
I found a link to one https://www.dropbox.com/s/adxsx0mxb6wztil/UIAutomationCore.rar

**Comment by markus-oberhumer** [comment]
We now have automated builds of the devel branch - please download the current win32 version from

https://github.com/upx/upx-automatic-builds/tree/devel-20170115-120150-ac4b51-travis/i386-w64-mingw32-gcc-4.6-release

**Comment by mingyuan-xia** [comment]
ok I will have a try, thx.

**Comment by mingyuan-xia** [comment]
electron 1.4.8 failed after using `upx-git-ac4b.exe` on the nightly build.

**Comment by markus-oberhumer** [comment]
Please try the fresh UPX 3.93 release and close this issue if fixed - it seems to work for me.

**Comment by markus-oberhumer** [comment]
Closing - please reopen if it does not work for you.

**Comment by mingyuan-xia** [comment]
confirmed working on 1.4.x and the latest 1.6.x, FYI, thanks a lot.

**Comment by LiamDotPro** [comment]
Very good stuff 💃
