### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by leo-lb** [upx/upx#290]
## What's the problem (or question)?

Currently UPX does not support WebAssembly (.wasm) files. It could be nice if it supported it so that web users could profit from faster load times.

## What should have happened?

I am not very knowledgeable with the WASM format so I would not know but I would simply like to motivate research in this area.

**Comment by bitraid** [comment]
Almost all web servers support and use compression  to serve http requests.

**Comment by leo-lb** [comment]
@bitraid yes they do, but a compression algorithm that is tailored to the format is always more efficient than a generic one. That's what UPX does.

**Comment by jreiser** [comment]
According to the dates in github, the "current work" decompressor-prototype is 2 to 3 years old.

UPX won't be interested until the run-time environment is well defined with introspection functions (such as "read the entire current program as a byte array, and with pointers to all current WebAssembly interpreter knowledge"), type conversions ("bless this array of bytes as code, and connect it to the WebAssembly interpreter in all the right ways: symbol definitions, etc."), random-access input and output, convert-to-text analyzers (such as `readelf`), cost metrics, etc.  It is unclear that the WA VM is powerful enough to allow UPX to do an effective job.

**Comment by jreiser** [comment]
And as always, please upload ("Attach files by ...") an actual file that you believe should be compressible.

**Comment by leo-lb** [comment]
Link to the file: https://github.com/leo-lb/random-files/raw/master/test_upx.wasm

Github does not allow attaching .wasm files.

**Comment by jreiser** [comment]
github will upload any output of gzip or zip, subject to some size limit that is at least 100KiB, perhaps several times that much.

A ball-park approximation of what UPX might do: prepend "#!/bin/sh\n", chmod +x, and apply UPX to the "executable shell script":
```
  13258   test_upx.wasm
   5459   test_upx.wasm.gz
   7653   test_upx.wasm.upx
```
The 2.2KB increase from .gz to .upx is the de-compressor "stub" for i386-linux.  The de-compressor itself can be as small as 1KiB; the other 1.2 KB is adapting to the linux environment.  So the gzip compression that is supported by default on most web servers and browsers is likely to be about as good as UPX.

**Comment by leo-lb** [comment]
That file is far from a practical use case for compression ratio, it does not do anything. It's an example project.

**Comment by leo-lb** [comment]
Here's a more practical use case for compression ratio (though, not a big [project](https://github.com/schmilblick-org/violetear-web-client) either)
[a.zip](https://github.com/upx/upx/files/3439982/a.zip)

**Comment by jreiser** [comment]
```
114996  web-client.wasm.upx-lzma
148258  web-client.wasm.gz
148420  web-client.wasm.zip
150796  web-client.wasm.upx-ucl
469965  web-client.wasm
```
The built-in, native-compiled, gzip handling of web servers and browsers is adequate.  Any interpreter suffers around 10X speed loss, and LZMA de-compression is around 10X slower (and more energy-intensive: a multiply operation and a cache Read-Modify-Write for almost every bit) than UPX (using UCL or NRV.)

**Comment by leo-lb** [comment]
WebAssembly is not interpreted and speed is near-native if not just as native with JIT. It is evident that there's more to do than generic compression (gzip, lzma, bzip2, ..) when you face a format that's known in advance, I was suggesting that. Also note that WebAssembly does not only run on the web but also as regular binaries. [Lucet](https://github.com/fastly/lucet/), [WASI](https://github.com/CraneStation/wasi)

**Comment by pyros2097** [comment]
Just to re-iterate on good gzip compression is you can look at this repo which does a comparison of golang wasm binaries,
https://github.com/syumai/go-wasm-sizes

example:
```
fmt/fmt.wasm
before gzip - 2.15MB 
after gzip - 444KB
after brotli - 336KB
```
The only other thing other than compression that i think that can be used to reduce the size is tree shaking but that has to be done at the compiler level.
Maybe if there is a way to compress based on wasm binary instruction format (bytecode) then i guess it might be possible to get better results.
Some people have done it for jave byte code,
http://www.cs.umd.edu/~pugh/java/latex2html/pack/node7.html

**Comment by rjzak** [comment]
Wasm support would benefit the [Wasi](https://wasi.dev/) use case, where WebAssembly applications are run on a system with a runtime, like [Wasmtime](https://github.com/bytecodealliance/wasmtime), [Wasm3](https://github.com/wasm3/wasm3), [WasmEdge](https://github.com/WasmEdge/WasmEdge), [WasmCloud](https://wasmcloud.dev/), [Enarx](https://github.com/enarx/enarx), etc, and not in a browser.

Some Wasi applications which have runtimes, like .Net, Ruby, Python, Go can get to be 20-40MB (or more), since they contain a runtime, standard scripts, and other bundled resources in addition to the code the person is trying to run.

**Comment by markus-oberhumer** [comment]
I don't think UPX is the right tool for dealing with compressed WASM files, so closing this as `wontfix` for now.

**Comment by XinyuZeng** [comment]
> @bitraid yes they do, but a compression algorithm that is tailored to the format is always more efficient than a generic one. That's what UPX does.
> 
> Current work is: https://github.com/WebAssembly/decompressor-prototype/blob/master/CompressionLayer1.md
> 
> Please note that there also exists freestanding WASM binaries that run outside the browser.

@llebout I agree with you. General-purpose compression is good for reducing size but it requires a full decompression to run the Wasm executable. Do you know why the decompressor-prototype you mentioned is deprecated?
