### ISSUE TITLE
--brute and --ultra-brute do not produce best result

### ISSUE THREAD

**Issue by Smattr** [upx/upx#297]
## What's the problem (or question)?
While trying to compress the binary of a program called [Rumur](https://github.com/smattr/rumur) with UPX 3.95 using `--brute` I think I ran into #253 but on Linux. UPX succeeds but then the resulting binary will not run (exits with 127, which indicates a missing library/dep...?). Using a suggestion I vaguely remembered from other UPX debugging, I switched to `--lzma`. This worked. However, to my surprise it produced a *smaller* binary than `--brute`. My curiosity piqued, I tried `--ultra-brute` and it produced an even bigger binary than `--brute`! Am I expecting the wrong result or is this genuinely surprising?

```sh
$ ls -l
rumur-lzma        544176
rumur-brute       600832
rumur-ultra-brute 606816
```

## What should have happened?
`--brute` should have produced a result <= `--lzma`. `--ultra-brute` should have produced a result <= `--brute`.

## Do you have an idea for a solution?
Not having looked at the implementation of these options, I do not.

## How can we reproduce the issue?
1. Compile Rumur using GCC 9.1 on Linux on SUSE Linux 11
2. Use UPX 3.95 to compress the binary in three different ways, `--lzma`, `--brute`, `--ultra-brute`
3. Observe the sizes of resulting binaries

## Please tell us details about your environment.
* UPX version used (`upx --version`): 3.95
* Host Operating System and version: SUSE Linux Enterprise Server 11
* Host CPU architecture: x86_64
* Target Operating System and version: SUSE Linux Enterprise Server 11
* Target CPU architecture: x86_64

**Comment by bitraid** [comment]
I have also noticed this, which also happens with the development branch.
These are the logs of upx compressing itself using `--lzma`, `--brute` and `ultra-brute`:
```
$./upx --lzma ./upx
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2019
UPX git-6a53c0+ Markus Oberhumer, Laszlo Molnar & John Reiser   Feb 24th 2019

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
compressWithFilters: m(1): 14 f(2): 73 0

14 49: 175585 +4690 +  0 = 180275  (best: 469653 +   0 +  0 = 469653)

14 00: 189605 +   0 +  0 = 189605  (best: 175585 +4690 +  0 = 180275)

   2096952 ->    374452   17.86%   linux/amd64   upx

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
```
```
$./upx --brute ./upx

                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2019
UPX git-6a53c0+ Markus Oberhumer, Laszlo Molnar & John Reiser   Feb 24th 2019

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
compressWithFilters: m(4): 2 5 8 14 f(2): 73 0

 2 49: 205810 +2313 +  0 = 208123  (best: 469653 +   0 +  0 = 469653)

 2 00: 222111 +   0 +  0 = 222111  (best: 205810 +2313 +  0 = 208123)

 5 49: 203789 +2326 +  0 = 206115  (best: 205810 +2313 +  0 = 208123)

 5 00: 219978 +   0 +  0 = 219978  (best: 203789 +2326 +  0 = 206115)

 8 49: 202859 +2358 +  0 = 205217  (best: 203789 +2326 +  0 = 206115)

 8 00: 219259 +   0 +  0 = 219259  (best: 202859 +2358 +  0 = 205217)

14 49: 175585 +4690 +  0 = 180275  (best: 202859 +2358 +  0 = 205217)

14 00: 189605 +   0 +  0 = 189605  (best: 175585 +4690 +  0 = 180275)

   2096952 ->    392220   18.70%   linux/amd64   upx

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
```
```
$./upx --ultra-brute ./upx

                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2019
UPX git-6a53c0+ Markus Oberhumer, Laszlo Molnar & John Reiser   Feb 24th 2019

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
compressWithFilters: m(6): 2 5 8 14 782 263950 f(2): 73 0

 2 49: 205810 +2313 +  0 = 208123  (best: 469653 +   0 +  0 = 469653)

 2 00: 222111 +   0 +  0 = 222111  (best: 205810 +2313 +  0 = 208123)

 5 49: 203789 +2326 +  0 = 206115  (best: 205810 +2313 +  0 = 208123)

 5 00: 219978 +   0 +  0 = 219978  (best: 203789 +2326 +  0 = 206115)

 8 49: 202859 +2358 +  0 = 205217  (best: 203789 +2326 +  0 = 206115)

 8 00: 219259 +   0 +  0 = 219259  (best: 202859 +2358 +  0 = 205217)

14 49: 175585 +4690 +  0 = 180275  (best: 202859 +2358 +  0 = 205217)

14 00: 189605 +   0 +  0 = 189605  (best: 175585 +4690 +  0 = 180275)

782 49: 175294 +4673 +  0 = 179967  (best: 175585 +4690 +  0 = 180275)

782 00: 189191 +   0 +  0 = 189191  (best: 175294 +4673 +  0 = 179967)

263950 49: 175088 +4730 +  0 = 179818  (best: 175294 +4673 +  0 = 179967)

263950 00: 188874 +   0 +  0 = 188874  (best: 175088 +4730 +  0 = 179818)

   2096952 ->    395296   18.85%   linux/amd64   upx

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
```

**Comment by jreiser** [comment]
rumur does not build.  I changed the beginning of CMakeLists.txt to
```
# cmake_minimum_required(VERSION 3.1)
cmake_minimum_required(VERSION 3.14)

project(rumur LANGUAGES CXX)
install(PROGRAMS rumur DESTINATION /usr/local/bin)
```
but still got
```
$ cmake --version   # in Fedora 30
cmake version 3.14.5
$ cmake ../rumur
CMake Error at CMakeLists.txt:93 (install):
  install PROGRAMS given no DESTINATION!


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.14)
```

**Comment by bitraid** [comment]
As you can see from my previous comment, you can also reproduce this when compressing the upx binary (dev branch, linux, gcc 9.1.0). It happens for many other files, too.

**Comment by Smattr** [comment]
I've clarified on https://github.com/Smattr/rumur/issues/146 how to compile Rumur: essentially `cmake ..` instead of `cmake ../rumur`. However, it looks like this issue is reproducible with UPX itself as @bitraid has explored.

**Comment by jreiser** [comment]
Explanation: in NEWS:
```
Changes in 2.93 beta (08 Mar 2007):
  * new formats Mach/i386 and Mach/fat support Mac OS X i686 and
    Universal binaries [i686 and PowerPC only]
  * dos/exe: LZMA is now also supported for 16-bit dos/exe. Please note that
    you have to explicitly use '--lzma' even for '--ultra-brute' here
    because runtime decompression is about 30 times slower than NRV -
    which is really noticeable on old machines.

Changes in 2.90 beta (08 Oct 2006):
  * LZMA algorithm support for most of the 32-bit and 64-bit file formats;
    use new option '--lzma' to enable
```
--lzma is so much slower at decompressing (and energy intensive: a multiply and ReadModifyWrite for each input bit [sort of]) that  LZMA is regarded as a different space from the default NRV/UCL compression algorithm.  It's been 12 years; probably UPX should unify everything.  Meanwhile: for [almost] all but the smallest inputs, --lzma will produce smaller executables that take longer and more energy to decompress.

**Comment by bitraid** [comment]
Isn't that only for `dos/exe` though? In my example, both `--brute` and `--ultra-brute` used LZMA compression as the best choise. And also `--brute` gave better results than `--ultra-brute`!

**Comment by Smattr** [comment]
@jreiser's last reply sufficiently explains the situation to me -- it was my misunderstanding to expect `--brute` and `--ultra-brute` to outperform `--lzma` -- and I learned something in the process, so thanks! I think my misunderstanding stemmed from the wording in the `--help` text:

```
  --brute             try all available compression methods & filters [slow]
  --ultra-brute       try even more compression variants [very slow]
```

 `--brute` outperforming `--ultra-brute` is still a little surprising. Though perhaps this is also an incorrect assumption on my part.

**Comment by bitraid** [comment]
`--brute` and `--ultra-brute` won't use LZMA only when compressing DOS executables.
For example, using `--ultra-brute` to compress `grep.exe` from Free-DOS:
```
$upx --ultra-brute GREP.EXE

                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2019
UPX git-6a53c0+ Markus Oberhumer, Laszlo Molnar & John Reiser   Feb 24th 2019

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
compressWithFilters: m(3): 3 6 9 f(1): 0

     89679 ->     40514   45.18%     dos/exe     GREP.EXE

Packed 1 file.
```
We can see that the compression methods tried are: **3 (M_NRV2B_8), 6 (M_NRV2D_8), 9 (M_NRV2E_8)**
For non-DOS executables (as is shown with my first example), there is also method **14 (LZMA)** tried.
So i think there is a problem calculating the best method/filter choice.

**Comment by bitraid** [comment]
It is also interesting to see that (from my first example) both `--lzma` and `--brute` chose:
`14 49: 175585 +4690 +  0 = 180275`
but gave different results.

**Comment by necros2k7** [comment]
Did you try latest 4.00dev build?

**Comment by Smattr** [comment]
Unfortunately, the issue persists:

```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
$ uname -rmsv
Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64
$ ./src/upx.out --version
upx 4.0.0-git-d53376d672ea
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
Copyright (C) 1996-2020 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2020 Laszlo Molnar
Copyright (C) 2000-2020 John F. Reiser
Copyright (C) 2002-2020 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx.out -L'.
$ cp src/upx.out upx-ultra-brute
$ cp src/upx.out upx-brute
$ cp src/upx.out upx-lzma
$ ./src/upx.out --lzma upx-lzma
...
$ ./src/upx.out --brute upx-brute
...
$ ./src/upx.out --ultra-brute upx-ultra-brute
...
$ ls -la upx-*
-rwxr-xr-x 1 matthew matthew 440532 Feb  3 21:10 upx-brute
-rwxr-xr-x 1 matthew matthew 423060 Feb  3 21:10 upx-lzma
-rwxr-xr-x 1 matthew matthew 443856 Feb  3 21:10 upx-ultra-brute
```

**Comment by markus-oberhumer** [comment]
I agree that `--ultra-brute` should dominate `--brute` as is should include all algorithms and filters from brute.

Has anybody been able to debug what is going on here?

**Comment by bitraid** [comment]
I just noticed that in this case (upx self compress) where `brute`/`ultra-brute` give different results (although the same method/filter is used), the compressed executable also fails to run:
```
$./upx --lzma -o upx-lzma upx
$./upx --lzma -9 -o upx-lzma-9 upx
$./upx --lzma --best -o upx-lzma-best upx
$./upx --brute -o upx-brute upx
$./upx --ultra-brute -o upx-ultra-brute upx
#./upx --file-info upx*
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX git-d7ba31  Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

upx-brute [amd64-linux.elf, linux/amd64]
    393656 bytes, compressed by UPX 13, method 14, level 10, filter 0x49/0x15
upx-lzma [amd64-linux.elf, linux/amd64]
    375664 bytes, compressed by UPX 13, method 14, level 7, filter 0x49/0x15
upx-lzma-9 [amd64-linux.elf, linux/amd64]
    375664 bytes, compressed by UPX 13, method 14, level 9, filter 0x49/0x15
upx-lzma-best [amd64-linux.elf, linux/amd64]
    375664 bytes, compressed by UPX 13, method 14, level 10, filter 0x49/0x15
upx-ultra-brute [amd64-linux.elf, linux/amd64]
    396696 bytes, compressed by UPX 13, method 14, level 10, filter 0x49/0x15

WARNING: this is an unstable beta version - use for testing only! Really.
```
Running the `upx-brute` or `upx-ultra-brute` compressed executables, the program
just exits returning error `127`.

**Comment by markus-oberhumer** [comment]
> Running the `upx-brute` or `upx-ultra-brute` compressed executables, the program
> just exits returning error `127`.

@bitraid Please open a new issue for this specific problem. Thanks!

**Comment by Smattr** [comment]
The failure of these executables to run is the problem I noted in my original description, that led me to discover this issue. My uneducated guess is that it's related to #253.

**Comment by bitraid** [comment]
I don't think its the same issue, as the problem here is only when `brute` or `ultra-brute` is used. Also when trying to uncompress these files, it fails with: `Exception: compressed data violation`.
I'll run some more tests when i get the chance, and open a new issue.

**Comment by bitraid** [comment]
>@bitraid Please open a new issue for this specific problem. Thanks!

@markus-oberhumer  Maybe this issue should be renamed instead, since the real problem described here (by both @Smattr and me) is not just the file size, but the inability of the affected programs to start or to unpack with `-d`.

**Comment by markus-oberhumer** [comment]
Ok, thanks. @jreiser John please have a look!

**Comment by jreiser** [comment]
The problem in https://github.com/upx/upx/issues/297#issuecomment-592424787 of 10 days ago is caused by changes in the layout of PT_LOAD segments:
``` 
  LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
                 0x0000000000001c60 0x0000000000001c60  R      0x1000
  LOAD           0x0000000000002000 0x0000000000402000 0x0000000000402000
                 0x00000000000b6441 0x00000000000b6441  R E    0x1000
  LOAD           0x00000000000b9000 0x00000000004b9000 0x00000000004b9000
                 0x000000000013fff0 0x000000000013fff0  R      0x1000
  LOAD           0x00000000001f9bf8 0x00000000005fabf8 0x00000000005fabf8
                 0x00000000000009c0 0x0000000000003260  RW     0x1000
```
Now there are 4 [PT_]LOAD (before there were only 2) and the most compressible one is not the first one.  Another issue with this same root cause is https://github.com/upx/upx/issues/294.  The fix involves a generalization of the strategy at compress time, to compress PT_LOAD that are contiguous both physically in the file and virtually in the address space; in progress.

**Comment by markus-oberhumer** [comment]
Is this issue fixed?

**Comment by Smattr** [comment]
Looks like yes. Re-running my previous experiment on commit 63298ebd6d1bf506bee2368d75f161ab3c30dba8:

```
$ ls -l upx*
-rwxr-xr-x 1 matthew matthew 554832 Sep 16 16:55 upx-brute     
-rwxr-xr-x 1 matthew matthew 554832 Sep 16 16:55 upx-lzma
-rwxr-xr-x 1 matthew matthew 554832 Sep 16 16:56 upx-ultra-brute
```
