### ISSUE TITLE
Illegal instruction with compressed mips shared library

### ISSUE THREAD

**Issue by kasome** [upx/upx#298]
## What's the problem (or question)?

Use UPX 3.95 to pack cross-compiled one executable file and one shared library on Ubuntu 18.04 64bit that run on mips32 Linux. But I got **Illegal instruction** when i ran the program that use the packed shared library.

## What should have happened?

If the executable file run normally, it print “Hello World!” string and then call 4 functions from the same shared library to do some arithmetic operations, like Add, Subtract, Multiply, and Divide of two double floating-point numbers.

## Do you have an idea for a solution?

i have no clue, but any suggestions will be welcome.

## How can we reproduce the issue?

1. Here are the source files i used:

Compile Shared Library (Arithmetic.h & Arithmetic.cpp => libTestSharedLibrary.so)

Arithmetic.h
```
#ifndef _ARITHMETIC_H_
#define _ARITHMETIC_H_

double Add(double augend, double addend);

double Subtract(double minuend, double subtrahend);

double Multiply(double multiplicand, double multiplier);

double Divide(double dividend, double divisor);

#endif
```

Arithmetic.cpp
```
#include <Arithmetic.h>

int const x[102400] = {1,2,3};
int my_sub(int j)
{
	return x[j];
}

double Add(double augend, double addend){
	return augend + addend;
}

double Subtract(double minuend, double subtrahend){
	return minuend - subtrahend;
}

double Multiply(double multiplicand, double multiplier){
	return multiplicand * multiplier;
}

double Divide(double dividend, double divisor){
	if(divisor){
		return dividend / divisor;
	}

	return 0;
}
```
Compile & Link

> mips-linux-g++ -I/home/user/TestSharedLibrary -I/home/user/ToolChain/mips-linux/include -I/home/user/ToolChain/mips-linux/lib/gcc/mips-linux/4.4.5/include -O3 --sysroot=/home/user/ToolChain -fPIC -MMD -MP -MF"Arithmetic.d" -MT"Arithmetic.o" -o "Arithmetic.o" "../Arithmetic.cpp"
> 
> mips-linux-g++ -L/home/user/ToolChain/mips-linux/lib --sysroot=/home/user/ToolChain -shared -o "libTestSharedLibrary.so"  ./Arithmetic.o   
> 

Compile Executable file (main.cpp => TestApplication)

main.cpp
```
#include <iostream>
#include <cstdio>

using namespace std;

#include <Arithmetic.h>

int const data[102400] = {1,2,3};

int my_data(int j)
{
	return data[j];
}

int main(int argc, char *argv[]){
	printf("Hello World!\n");

	for(int i=0; i<102400; ++i){
		my_data[i];
	}

	double input1 = 5, input2 = 3;
	printf("%f + %f = %f\n", input1, input2, Add(input1, input2));
	printf("%f - %f = %f\n", input1, input2, Subtract(input1, input2));
	printf("%f * %f = %f\n", input1, input2, Multiply(input1, input2));
	printf("%f / %f = %f\n", input1, input2, Divide(input1, input2));

	return 0;
}
```

Compile & Link
> mips-linux-g++ -I/home/user/TestSharedLibrary -I/home/user/ToolChain/mips-linux/include -I/home/user/ToolChain/mips-linux/lib/gcc/mips-linux/4.4.5/include -O3 --sysroot=/home/user/ToolChain -fPIC -MMD -MP -MF"main.d" -MT"main.o" -o "main.o" "../main.cpp"
> 

> mips-linux-g++ -L/home/user/TestSharedLibrary/Release -L/home/user/ToolChain/mips-linux/lib --sysroot=/home/user/ToolChain -o "TestApplication"  ./main.o   -lTestSharedLibrary
> 

2. I create 4 directories, each directory have TestApplication and libTestSharedLibrary.so as mention above, as follows:

> TestApplication/
> ./TestApplication (No compressed by UPX)
> ./libTestSharedLibrary.so (No compressed by UPX)

> TestApplication2/
> ./TestApplication (compressed by UPX: upx -1 TestApplication)
> ./libTestSharedLibrary.so (No compressed by UPX)

> TestApplication3/
> ./TestApplication (No compressed by UPX)
> ./libTestSharedLibrary.so (compressed by UPX: upx -1 libTestSharedLibrary.so)

> TestApplication4/
> ./TestApplication (compressed by UPX: upx -1 TestApplication)
> ./libTestSharedLibrary.so (compressed by UPX: upx -1 libTestSharedLibrary.so)

3. I put the 4 directories to the target device and run, **first two cases** (TestApplication & TestApplication2) **is normal running with no error**, **other two cases** (TestApplication3 & TestApplication4) **have illegal instruction** error.

[4 directories](https://www.asuswebstorage.com/navigate/a/#/s/C796BAF335964AC4A8B8220A5BF45DA8Y)

4. i also use strace to debug, the result is in the attachment file.

[ Strace Debug Result](https://www.asuswebstorage.com/navigate/a/#/s/ADDE2536E12048EEB1A6CA1DE259D849Y)

## Please tell us details about your environment.

* UPX version used (`upx --version`): UPX 3.95
* Host Operating System and version: Ubuntu 18.04 64bit
* Host CPU architecture: x86_64
* Target Operating System and version: Linux rlx-linux 2.6.30.9
* Target CPU architecture: mips32

**Comment by jreiser** [comment]
Please try the tip of the `devel` branch.  The placement of PT_DYNAMIC in the first PT_LOAD had not been seen before, so a fix was needed when updating DT_INIT.
