### ISSUE TITLE
Howdy folks, welcome to GitHub!

### ISSUE THREAD

**Issue by geoff-codes** [upx/upx#3]
Great to have you here! I know its a bit sad to leave sf.net but in the end it really is well worth it, I swear!

For example, you get to get to hear about tons of new cool new issues, like #4!

🍻 -Geoff

**Comment by markus-oberhumer** [comment]
Indeed - hopefully the move to GitHub will spur some fresh development activity and help improving the project.

**Comment by ssokolow** [comment]
I hope the new spartan UPX website is only temporary. I remember the old one exciting passers-by much more effectively.

(The old site is robots.txt'd out of the wayback machine, but I remember it having an example chart of some sort and a list of supported binary formats, among other things.)
