### ISSUE TITLE
UPX compress result is different

### ISSUE THREAD

**Issue by Vityacv** [upx/upx#30]
## What's the problem (or question)?

UPX compresses differently between UPX official binary and self-builded binary
## What should have happened?

Equal compressing results

## Do you have an idea for a solution?

No idea

## How can we reproduce the issue?

1. Compress executable using UPX binary builded from source:
```
upx -9 --small explorer.exe 
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2013
UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   4673304 ->   1668888   35.71%    win64/pe     explorer.exe        
```
2. Compress executable using UPX official binary
```
./upx3.91 -9 --small explorer.exe 
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2013
UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   4673304 ->   1546008   33.08%    win64/pe     explorer.exe                  


```
## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.91
* Operating System and version: archlinux amd64
* CPU architecture: amd64

**Comment by jreiser** [comment]
Run
```
upx --fileinfo explorer.upx  # compressed version of explorer
```
and if it says "method 2" through "method 10"  then the difference is explained by official releases of UPX using the NRV library (proprietary) versus the UCL library (open source).  "upx --lzma" should give the same results for both builds.
