### ISSUE TITLE
Can you make a release?

### ISSUE THREAD

**Issue by svenstaro** [upx/upx#300]
Last release has been quite a while ago and especially with https://github.com/upx/upx/issues/245 being fixed in the `devel` branch I think it's quite important to get that fix into stable.

What do you think?

**Comment by necros2k7** [comment]
Markus, make people happy in 2019)

**Comment by ofek** [comment]
@jreiser @markus-oberhumer Any update?

**Comment by markus-oberhumer** [comment]
Done.

**Comment by svenstaro** [comment]
Thanks!
