### ISSUE TITLE
Compressed binary created by Golang is not working on MacOS

### ISSUE THREAD

**Issue by polomsky** [upx/upx#301]
## What's the problem?
Binary created by golang 1.13 for MacOS platform is not working after packing with upx
and reports `Killed: 9`

## What should have happened?
Binary should work as not packed version

## How can we reproduce the issue?
golang code:
```go
// hello.go
package main

func main() {
	println("Hello")
}
```
1. build for macOS 64 bit: `GOOS=darwin go build -o hello -trimpath src/hello.go`
2. `upx hello`
3. run `hello`
4. on the screen is `Killed: 9`

## Please tell us details about your environment.

* UPX version used (`upx --version`):
```
upx 3.95
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
```
* Host Operating System and version:
`4.15.0-60-generic #67~16.04.1-Ubuntu SMP Mon Aug 26 08:57:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Host CPU architecture:
`x86_64`
* Target Operating System and version:
`Darwin 18.7.0`
* Target CPU architecture:
`x86_64`

**Comment by jreiser** [comment]
Same as https://github.com/upx/upx/issues/222.  The tip of `devel` branch, when applied to `hello`, produces a compressed executable that runs correctly and does not suffer SIGSEGV.
