### ISSUE TITLE
Seg fault on Linux x86-64, probably missing return value check

### ISSUE THREAD

**Issue by aycock** [upx/upx#302]
## What's the problem (or question)?

upx seg faults when run on a upx-packed file under certain conditions.

## What should have happened?

No seg fault.

## Do you have an idea for a solution?

I suspect that the open of /proc/self/exe is assumed to always succeed, but it doesn't in this case due to missing read perms on the executable. mmap then tries to use the file descriptor with nonoptimal results. (Note that besides perms, a system could be in a state where /proc isn't mounted.)

## How can we reproduce the issue?

1. Pack an executable with upx, call it foo.
2. Make upx mode 711.
3. Chown upx to a different user.
4. Run the chown'ed upx on the packed file (might need to repeat this step). Seg fault should result.

strace of faulting instance:
strace ~/bin/upx-notmine ./ls
execve("/home/profs/aycock/bin/upx-notmine", ["/home/profs/aycock/bin/upx-n"..., "./ls"], 0x7ffe30b686a8 /* 57 vars */) = 0
open(0x466939, O_RDONLY)                = -1 EACCES (Permission denied)
mmap(NULL, 422143, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f670d9ab000
mmap(0x7f670d9ab000, 421726, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, -13, 0) = -1 EBADF (Bad file descriptor)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x66943} ---
+++ killed by SIGSEGV +++
Segmentation fault (core dumped)

For comparison, an strace where I *do* have read perms:
execve("/home/profs/aycock/bin/upx", ["/home/profs/aycock/bin/upx", "./ls"], 0x7ffeb42e2998 /* 57 vars */) = 0
open("/proc/self/exe", O_RDONLY)        = 3
mmap(NULL, 422143, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0e48e23000
mmap(0x7f0e48e23000, 421726, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x7f0e48e23000
mprotect(0x7f0e48e88000, 8447, PROT_READ|PROT_EXEC) = 0
readlink("/proc/self/exe", "/home/profs/aycock/bin/upx", 4095) = 30

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:
upx 3.95
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
% uname -a
Linux rsx1 4.14.11-200.fc26.x86_64 #1 SMP Wed Jan 3 13:58:53 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jreiser** [comment]
The days when /proc is not mounted (at least on x86_64) ended many years ago.  The only reasonable alternative is an error exit.  Similarly for an executable that cannot be read.  Dealing with such situations has low priority.

**Comment by aycock** [comment]
I completely agree: an error message should be issued, and that it's a low priority.

However, the reason I'm reporting this is that this literally just happened in practice. Multiple people were affected and reported the seg fault, and I had to reproduce it, track down the bug in upx, and find the (luckily trivial) workaround.

(In case anyone trips across this in the future from a web search: the workaround is to chmod 755 upx.)

**Comment by jreiser** [comment]
Fixed for amd64, 32-bit ARM, and 64-bit ARM on tip of `devel` branch, commit 75a2cc4ecb8c82ce3675d1b645694fc27480862a.
