### ISSUE TITLE
To execute only "make" seems to be wrong in your documentation, i needs "make all"... #1

### ISSUE THREAD

**Issue by martijintro** [upx/upx#304]
I wrote it on the wrong place, please read here https://github.com/korczis/upx/issues/1

Thx.

**Comment by jreiser** [comment]
What was the working directory (`$ pwd`)?

**Comment by jreiser** [comment]
In the `src` directory (which contains file `p_lx_elf.cpp`, for instance), then in Makefile the first dependency rule for a target is `all:` on line 82.  `make -n` says `make: Nothing to be done for 'all'.`
In the `src/stub` directory (which contains file `amd64-linux.elf-entry.h`, for instance), then in Makefile the first dependency rule for a target is `default:` on line 153 whose recipe is
```
        @echo "UPX info: type 'make all' if you have all the required build tools."
```
because few non-maintainers have all the tools that are necessary to rebuild the stubs.
Those executions are with GNU Make 4.2.1.  So the Makefiles look OK to me.

**Comment by martijintro** [comment]
Will look about it, thx..

**Comment by martijintro** [comment]
Here is an example that works without that problems (and i also found a bug with 'check_whitespace.sh'..):

https://github.com/upx/upx/issues/306

**Comment by jreiser** [comment]
In a new git clone of the upx project, there the top-level directory contains README.SRC which gives an overview of building the upx executable.
At the top level:
```
$ make -n
echo "UPX info: please choose a target for 'make'"
```
and inspecting the Makefile shows that the main action takes place in the `src` subdirectory.
In the `src` subdirectory of the top level:
```
$ make -n
../src/stub/src/c/Makevars.lzma:10: *** ERROR: missing git submodule; run 'git submodule update --init --recursive'.  Stop.

# Shell environment variables UPX_LUADIR, UPX_LZMADIR, UPX_LZMA_VERSION, UPX_UCLDIR
# must be set (by you; not illustrated here) to point to external source inputs.  Then:

$ git submodule update --init --recursive
Submodule 'src/lzma-sdk' (https://github.com/upx/upx-lzma-sdk.git) registered for path 'lzma-sdk'
Cloning into '/<<path>>/upx/src/lzma-sdk'...
Submodule path 'lzma-sdk': checked out '426fe82d122e2cf140a86751055ee523378fe2ef'
```
Finally, actual building can take place:
```
$ make -n
Updating .depend
g++ '-DUPX_VERSION_GITREV="7a3637ff5a80"' -I/home2/ucl-1.03/include -O2 -fno-delete-null-pointer-checks -fno-strict-aliasing -fwrapv -funsigned-char -Wall -W -Wcast-align -Wcast-qual -Wmissing-declarations -Wpointer-arith -Wshadow -Wvla -Wwrite-strings -Werror -o c_file.o -c c_file.cpp
   <<snip>>
g++ -O2 -fno-delete-null-pointer-checks -fno-strict-aliasing -fwrapv -funsigned-char -Wall -W -Wcast-align -Wcast-qual -Wmissing-declarations -Wpointer-arith -Wshadow -Wvla -Wwrite-strings -Werror -o upx.out c_file.o <<snip>>
./../src/stub/scripts/check_whitespace_git.sh ./..
```
Explaining any more takes time away from maintaining and extending UPX.
