### ISSUE TITLE
unity libil2cpp.so crash on x86 platform after upx compress

### ISSUE THREAD

**Issue by Ficing** [upx/upx#307]
## What's the problem (or question)?
unity libil2cpp.so crash on x86 platform after upx compress, while on arm platform, it works fine.

## What should have happened?
should not crash after upx compress on x86 platform.

## Do you have an idea for a solution?
No solution here, only found that the unity internal function "Debug.log()" will cause the crash, but it should not be the reason, because it works fine on the arm platform

## How can we reproduce the issue?
1. Write a unity Demo app, it's better that include the "Debug.log()" statement, build with il2cpp, and do not forget include the armv7 and x86 platform when export a apk file.
2. unpack the apk, and use upx to compress the libil2cpp.so in folder armv7 and x86, and then repack it.
3. run the apk on an android phone, and use logcat to check the log, it works fine.
4. run the apk on an android simulator, and use logcat to check the log, it crashed. 

![image](https://user-images.githubusercontent.com/30288072/66823476-ed6d7b80-ef78-11e9-892a-9461d73775f7.png)

## Please tell us details about your environment.

* UPX version used (`upx --version`): both upx 3.95 and upx3.94 tried. 
* Host Operating System and version: linux 64
* Host CPU architecture: Amd64
* Target Operating System and version: x86
* Target CPU architecture: intel

**Comment by jreiser** [comment]
`Write a unity Demo app ...` Please upload ("Attach files by ...") the actual binary executable (before compressing with upx) which suffers the crash.  Compress with gzip, zip, or .tgz before uploading, so that github will accept the file.

**Comment by Ficing** [comment]
[libil2cpp.zip](https://github.com/upx/upx/files/3732091/libil2cpp.zip)
Hello, this is the source .so file which crashed after compress on x86 platform, please help to check it.

**Comment by Ficing** [comment]
Hi, any news?

**Comment by jreiser** [comment]
In src/p_lx_elf.cpp function PackLinuxElf32::canPack() near line 2117
```
                                   if (Elf32_Ehdr::EM_ARM == e_machine
                                    &&  R_ARM_RELATIVE == r_type) {
                                        user_init_va = get_te32(&file_image[user_init_off]);
                                    }
                                    else {
                                        char msg[50]; snprintf(msg, sizeof(msg),
                                            "bad relocation %#x DT_INIT_ARRAY[0]",
                                            r_info);
                                        throwCantPack(msg);
                                    }
                                    break;
```
the code should be extended to handle `Elf32_Ehdr:: EM_386== e_machine` in the same way as EM_ARM.  You could try that.  I plan to try it soon.

**Comment by JmpRegister** [comment]
thx for your help！I had the same problem . I changed my code in devel branch.but the problem still exists.

**Comment by dingwenjie** [comment]
init_array is an array in general,  each item is a function entry offset, but there are also cases of 0. Because init_array the actual resolution timing may also be repositioned init_array after the repositioning is complete. So to resolve the init_array you also need to determine the relocation table
