### ISSUE TITLE
Compressed binaries segfault when run if the original program segment is of specific size

### ISSUE THREAD

**Issue by skel554** [upx/upx#308]
## What's the problem (or question)?
Upx can produce binaries which would segfault when run, if the program segment is of specific size (when the padding it has is less than 4 bytes). Normally the program segment is page size-aligned, meaning that it can have at most 4095 unused bytes in its last page, so there's a good chance it would have at least 4 bytes. However, that's not guaranteed, and there's roughly a 0.1% chance the space would not be there.

## What should have happened?
The compressed binary should run normally, irrespective of the program segment size.

## Do you have an idea for a solution?
I tracked down the issue to the function make_hatch_x86_64() not being able to find space for the hatch, at the following location: https://github.com/upx/upx/blob/7a3637ff5a800b8bcbad20ae7f668d8c8449b014/src/stub/src/amd64-linux.elf-main.c#L233
None of the conditions match, and the function returns 0. Later the hatch is attempted to be used at https://github.com/upx/upx/blob/7a3637ff5a800b8bcbad20ae7f668d8c8449b014/src/stub/src/amd64-linux.elf-fold.S#L169
...and, since it's zero, jump happens to 0 and it all segfaults.

## How can we reproduce the issue?

Since this happens when there's no padding space left after program segment, we generate binaries of increasing sizes and run them until one of them crash. A test program and a shell script to do this are included. Run `./test-all.sh` and see it segfault at some point.

test.c
```
#include <unistd.h>

int main()
{
  _exit(0);
}

#define NOP2 asm("nop"); asm("nop");
#define NOP4 NOP2 NOP2
#define NOP8 NOP4 NOP4
#define NOP16 NOP8 NOP8
#define NOP32 NOP16 NOP16
#define NOP64 NOP32 NOP32
#define NOP128 NOP64 NOP64
#define NOP256 NOP128 NOP128
#define NOP512 NOP256 NOP256
#define NOP1024 NOP512 NOP512
#define NOP2048 NOP1024 NOP1024

void  __attribute__((section(".fini"))) foo()
{
  NOP2048
  NOP2048
  NOP2048
  NOP1024

  #if (VAL&1)
    asm("nop");
  #endif
  #if (VAL&2)
    NOP2
  #endif
  #if (VAL&4)
    NOP4
  #endif
  #if (VAL&8)
    NOP8
  #endif
  #if (VAL&16)
    NOP16
  #endif
  #if (VAL&32)
    NOP32
  #endif
  #if (VAL&64)
    NOP64
  #endif
  #if (VAL&128)
    NOP128
  #endif
  #if (VAL&256)
    NOP256
  #endif
  #if (VAL&512)
    NOP512
  #endif
  #if (VAL&1024)
    NOP1024
  #endif
  #if (VAL&2048)
    NOP2048
  #endif
}
```

test-all.sh
```
#!/bin/bash

set -xue

for x in `seq 0 4095`; do
gcc -DVAL=$x test.c -o test
upx test
./test
done
```

Here is what I get (it takes 537 iterations to find the right size in my case, only the final output is included):
```
...

+ for x in '`seq 0 4095`'
+ gcc -DVAL=537 test.c -o test
+ upx test
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
     20728 ->      5448   26.28%   linux/amd64   test                          

Packed 1 file.
+ ./test
./test-all.sh: line 5: 29621 Segmentation fault      ./test
```

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.95 (or any other version, including current devel tip)
* Host Operating System and version: linux/amd64
* Host CPU architecture: linux/amd64
* Target Operating System and version: linux/amd64
* Target CPU architecture: amd64

**Comment by jreiser** [comment]
Fixed by above commit 936013f; cost is ~100 bytes in decompression stub.
