### ISSUE TITLE
EOFException when compressing MUSL binaries

### ISSUE THREAD

**Issue by hectormonacci** [upx/upx#309]
## What's the problem (or question)?
When UPX 3.95 tries to pack the simplest Linux 64-bit MUSL executable (at least if compiled by Nim), it fails with this error message: ```EOFException: premature end of file```

## What should have happened?
UPX 3.95 should have compressed the executable.

## Do you have an idea for a solution?
Sorry but I have no idea for a solution.

## How can we reproduce the issue?
The issue is easy to reproduce.

1. Save the short program «echo "Hello World!"» as hello.nim
2. Compile this program thus: «nim -f --gcc.exe:x86_64-linux-musl-gcc --gcc.linkerexe:x86_64-linux-musl-gcc --passL:-static c hello.nim»
3. Try to compress thus: «upx hello»
4. Read the error message «upx: hello: EOFException: premature end of file»

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.95
* Host Operating System and version: Void Linux current
* Host CPU architecture: x86_64
* Target Operating System and version: any x86_64 Linux
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") an actual binary executable file (before UPX compression) that triggers the complaint.  Compress the file using zip, gzip, or .tgz before uploading, so that github will accept the file.

**Comment by hectormonacci** [comment]
Please find attached the executable file before UPX compression. Source code is simply «echo "Hello World!"».
[hello.zip](https://github.com/upx/upx/files/3750264/hello.zip)

**Comment by jreiser** [comment]
Works for me using tip of `devel` branch, commit 6a53c0b3d499d62346a5c51034db543a4ef78ea3.
```
$ ../upx.out -f -o foo hello
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2019
UPX git-6a53c0+ Markus Oberhumer, Laszlo Molnar & John Reiser   Feb 24th 2019

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
     30144 ->     14508   48.13%   linux/amd64   foo                           

```
