### ISSUE TITLE
VMOS virtual environment problems

### ISSUE THREAD

**Issue by gassion** [upx/upx#312]
I compiled a binary executable program, in the mobile terminal is no problem, when to install the program in vmos is executed up inside, hope to be able to help me, thank you very much!

UPX 3.95 

upx -f -o   xxx  xxx 

Here is to capture the error:

11-04 17:44:44.194 31517 31517 F DEBUG   : Build fingerprint: 'Rock/odin/odin:7.1.1/NMF26F/1565941878:user/dev-keys'
11-04 17:44:44.194 31517 31517 F DEBUG   : Revision: '0'
11-04 17:44:44.194 31517 31517 F DEBUG   : ABI: 'arm'
11-04 17:44:44.194 31517 31517 F DEBUG   : pid: 31514, tid: 31514, name: initlinker32  >>> /data/data/com.touchsprite.android/files/jar/armeabi/core <<<
11-04 17:44:44.194 31517 31517 F DEBUG   : signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0xf686d880
11-04 17:44:44.194 31517 31517 F DEBUG   :     r0 f6b7688e  r1 000006f1  r2 f686d880  r3 00000000
11-04 17:44:44.194 31517 31517 F DEBUG   :     r4 ff000000  r5 ffffffff  r6 f6b76880  r7 f6b76f7d
11-04 17:44:44.194 31517 31517 F DEBUG   :     r8 00000000  r9 0030756c  sl ffcf7000  fp ff9bb5dc
11-04 17:44:44.194 31517 31517 F DEBUG   :     ip ff9bb530  sp ff9bb5a4  lr f6b765ec  pc f6b765e0  cpsr b00d0010
11-04 17:44:44.195 31517 31517 F DEBUG   :
11-04 17:44:44.195 31517 31517 F DEBUG   : backtrace:
11-04 17:44:44.195 31517 31517 F DEBUG   :     #00 pc 003075e0  /data/data/com.vmos.app/osimg/r/ot01/data/data/com.touchsprite.android/files/jar/armeabi/core
11-04 17:44:44.195 31517 31517 F DEBUG   :     #01 pc 003075e8  /data/data/com.vmos.app/osimg/r/ot01/data/data/com.touchsprite.android/files/jar/armeabi/core
11-04 17:44:44.404   589   933 I AudioFlinger: BUFFER TIMEOUT: remove(4096) from active list on thread 0xf4f83a40
11-04 17:44:44.437   589   828 I APM_AudioPolicyManager: stopOutput() output 29, stream 3, session 169
11-04 17:44:44.438   589   828 I APM_AudioPolicyManager: setOutputDevice() io 29 prevDevice 0x0002, cur 0x0000

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") an actual binary executable program (after building, but before compressing with UPX) which suffers the problem.  Compress with zip, gzip, or .tgz so that github will accept the file.

**Comment by gassion** [comment]
@jreiser   Thank you very much

The attachment is as follows

source  code ：

-------------------------

#include <iostream>

#include <android/log.h>
#define LOG(format, ...)__android_log_print(ANDROID_LOG_WARN, "tsCore", format, ##__VA_ARGS__)

using namespace std;
int main(int argc, char *argv[]) {
    for (int i =0;i<10;i++) {
        LOG("nice tTo meet you too");
    }
}

-------------------------

[armeabi.zip](https://github.com/upx/upx/files/3807022/armeabi.zip)

**Comment by gassion** [comment]
@jreiser  http://www.vmos.cn/   virtual master download address   executed crash   thank you
