### ISSUE TITLE
android so arm64-v8a : CantPackException: bad PT_DYNAMIC phdr[2]

### ISSUE THREAD

**Issue by Virenz** [upx/upx#316]
## What's the problem (or question)?

upx.out -9 --brute --android-shlib lib**.so (arm64-v8a)
Error: CantPackException: bad PT_DYNAMIC phdr[2]

## How can we reproduce the issue?

i use android studio and ndk-build  a test project so

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.95
* Host Operating System and version: macos 10.15
* Host CPU architecture: x86-64
* Target Operating System and version: android
* Target CPU architecture: arm64-v8a

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") an actual shared library that triggers the complaint.  Compress the library using zip, gzip, or .tgz so that Github will accept the upload.
If uploading is not possible then please run these commands, and copy+paste the output into a Comment here.
```
ls -l libfoo.so
readelf --headers --segments --dynamic libfoo.so
```

**Comment by Virenz** [comment]
> Please upload ("Attach files by ...") an actual shared library that triggers the complaint. Compress the library using zip, gzip, or .tgz so that Github will accept the upload.
> If uploading is not possible then please run these commands, and copy+paste the output into a Comment here.
> 
> ```
> ls -l libfoo.so
> readelf --headers --segments --dynamic libfoo.so
> ``

**Comment by Virenz** [comment]
> > Please upload ("Attach files by ...") an actual shared library that triggers the complaint. Compress the library using zip, gzip, or .tgz so that Github will accept the upload.
> > If uploading is not possible then please run these commands, and copy+paste the output into a Comment here.
> > ```
> > ls -l libfoo.so
> > readelf --headers --segments --dynamic libfoo.so
> > ``
> > ```

[libnative-lib.so.zip](https://github.com/upx/upx/files/3866889/libnative-lib.so.zip)

**Comment by jreiser** [comment]
Works for me using tip of `devel` branch:
```
$ ../upx.out -f -o foo --android-shlib libnative-lib.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2019
UPX git-819c33+ Markus Oberhumer, Laszlo Molnar & John Reiser   Feb 24th 2019

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1361608 ->    446572   32.80%   linux/arm64   foo                           
```

**Comment by Virenz** [comment]
> using tip of `devel` branch

 i use devel upx.out -9 --brute --android-shlib can sucess,but run apk jni can't call(no crash)
