### ISSUE TITLE
upx-devel ddos Vulnerability

### ISSUE THREAD

**Issue by freebufdaolang** [upx/upx#317]
ubuntu 1604 x32
////////////////////////////////////////////////////////////
ddos 1 attachment p_lx_elf.cpp^%1613
p_lx_elf.cpp:1613
 unsigned const nbucket = get_te32(&hashtab[0]); crashes
/////////////////////////////////////////////////////////////////////
ddos 2 attachment p_lx_elf.cpp^%1635
p_lx_elf.cpp:1635
 unsigned const n_bucket = get_te32(&gashtab[0]);
        unsigned const n_bitmask = get_te32(&gashtab[2]);
        unsigned const gnu_shift = get_te32(&gashtab[3]);
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////
ddos 3 attachment p_lx_elf.cpp^%1839
p_lx_elf.cpp^%1839
 unsigned const symnum = get_te32(&rel->r_info) >> [8];

////////////////////////////////////////////////////////////////////////////

find by topsec(hj)

[upx.zip](https://github.com/upx/upx/files/3873925/upx.zip)

**Comment by jreiser** [comment]
Fixed in `devel` branch.
```
upx.out: p_lx_elf.cpp^%1613: CantUnpackException: duplicate DT_0x5: [0x3] [0xb]
upx.out: p_lx_elf.cpp^%1635: CantUnpackException: bad DT_GNU_HASH 0x80481ac
upx.out: p_lx_elf.cpp^%1839: CantPackException: duplicate DT_0x6: [0x9] [0x11]
```
