### ISSUE TITLE
Android8.0 W + E load segments are not allowed

### ISSUE THREAD

**Issue by xiaofeng666** [upx/upx#319]
## What's the problem (or question)?
After the Android 8.0 version, the android system will detect whether the loader segment of the so file has write permissions and execute permissions. This will cause the upx packed so files to fail to run. Is there a solution?
android log:W + E load segments are not allowed
## Do you have an idea for a solution?
Modifying the AndroidManifest.xml file with a targetversion tag less than 26 can solve the problem, but for some reasons I cannot modify the AndroidManifest.xml file

## Please tell us details about your environment.

* UPX version used (`upx --version`):3.95
* Host Operating System and version:win10
* Host CPU architecture: x86-64
* Target Operating System and version:android
* Target CPU architecture:arm64-v8a

**Comment by jreiser** [comment]
I cannot find an output from UPX that has PT_LOAD.p_flags with both PF_X and PF_W flags, unless the input already has such flags.
Please upload ("Attach files by ...") an actual shared library (before UPX compression) which triggers the complaint.  Compress with zip, gzip, or .tgz before uploading, so that github  will accept the file.
If that is not possible, then please run `readelf --headers --segments my_lib.so` then copy+paste the output into a Comment here. Put one line with three backtick characters only (hex 0x60, decimal 96, octal 0140) before the pasted output, and another identical line just after the pasted output, so that the Markdown formatting preserves columns.

**Comment by xiaofeng666** [comment]
There is a problem with my so file, the problem has been solved. thank you very much :)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"John Reiser"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 中午11:32
收件人:&nbsp;"upx/upx"<upx@noreply.github.com&gt;;
抄送:&nbsp;"1021500681"<1021500681@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [upx/upx] Android8.0 W + E load segments are not allowed (#319)




I cannot find an output from UPX that has PT_LOAD.p_flags with both PF_X and PF_W flags, unless the input already has such flags.
 Please upload ("Attach files by ...") an actual shared library (before UPX compression) which triggers the complaint.  Compress with zip, gzip, or .tgz before uploading, so that github  will accept the file.
 If that is not possible, then please run readelf --headers --segments my_lib.so then copy+paste the output into a Comment here. Put one line with three backtick characters only (hex 0x60, decimal 96, octal 0140) before the pasted output, and another identical line just after the pasted output, so that the Markdown formatting preserves columns.

**Comment by xiaofeng666** [comment]
There is a problem with my so file, the problem has been solved. thank you very much

**Comment by xiaofeng666** [comment]
> I cannot find an output from UPX that has PT_LOAD.p_flags with both PF_X and PF_W flags, unless the input already has such flags.
> Please upload ("Attach files by ...") an actual shared library (before UPX compression) which triggers the complaint. Compress with zip, gzip, or .tgz before uploading, so that github will accept the file.
> If that is not possible, then please run `readelf --headers --segments my_lib.so` then copy+paste the output into a Comment here. Put one line with three backtick characters only (hex 0x60, decimal 96, octal 0140) before the pasted output, and another identical line just after the pasted output, so that the Markdown formatting preserves columns.
> (Also, please use the tip of the `devel` branch.)
