### ISSUE TITLE
Packed exe crash

### ISSUE THREAD

**Issue by Vityacv** [upx/upx#32]
## What's the problem (or question)?

Packed exe crash

## Do you have an idea for a solution?

Fix import table

File in HEX:
0x2CF - end of api string
0x2D0 - function entry

original entry:
B8 94 88 01 00
after upx:
00 94 88 01 00

## How can we reproduce the issue?

1. Pack attached file [test32.zip](https://github.com/upx/upx/files/637775/test32.zip) with UPX 3.91 or newer (flags upx -9 --small)
2. Run packed file and get crash

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.91, upx 3.92-git-4f3b85e604f2
* Operating System and version: archlinux amd64, wine (Crash on windows 10 too)
* CPU architecture: amd64

**Comment by ml1050** [comment]
Fixed on the devel branch. c7cb0365364bd968f878d1b55aa59e453335d310
Thanks for your report.
