### ISSUE TITLE
UPX 3.95 : UnknownExecutableFormatException

### ISSUE THREAD

**Issue by senioi** [upx/upx#323]
## What's the problem (or a question)?
An error occurred during compression: UnknownExecutableFormatException

## What should have happened?
not support FreeBSD?

## Do you have an idea for a solution?
No idea, If there is any solution please let me know

## How can we reproduce the issue?
1.No any FreeBSD binary can be compressed ,e.g : /bin or /usr/bin 
2.[test.zip](https://github.com/upx/upx/files/3939134/test.zip)
3.Install: pkg install upx

## Please tell us details about your environment.
* UPX version used (`upx --version`): 3.95
* Host Operating System and version: FreeBSD 12.1
* Host CPU architecture: intel e3-1240
* Target Operating System and version: FreeBSD 12.1
* Target CPU architecture: intel e3-1240

**Comment by jreiser** [comment]
Only 32-bit *BSD executables are supported.

**Comment by jreiser** [comment]
Now that "OpenBSD system-call-origin verification" has been implemented, then UPX cannot run on OpenBSD because UPX must make system calls outside of libc.
