### ISSUE TITLE
UPX stub modification win32.pe.S

### ISSUE THREAD

**Issue by zunair11** [upx/upx#328]
## What's the problem (or question)?

I am trying to modify the UPX pre-compiled stub and just want to add a simple delay before the stub decompresses my compressed application. What I want to achieve is the executable to loaded in memory and unpacked after a delay.

## What should have happened?

`section         ZED1`
`mov     cx, 0x02FA`
`mov     dx, 0xF080`
`mov     ah, 0x86`
`mov     al, 0`
`int     0x15`

As the stubs are in assembly I was expecting to add an interrupt based delay to achieve this functionality.But every time I implemented the delay the program loaded instantly.

## Do you have an idea for a solution?

I believe that the approach of using an interrupt to generate is based on 16 bit assembly and the stub is 32 bit assembly and that does not uses interrupts. the interrupt in question is 21H

## Please tell us details about your environment.

* UPX version used (`upx --version`):
upx 3.95-git-7a3637ff5a80+
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43

* Host Operating System and version:
Ubuntu 18.04 
* Host CPU architecture:
x86-64
* Target Operating System and version:
Ubuntu 18.04
* Target CPU architecture:
x86-64

**Comment by ml1050** [comment]
You should not mix 16-bit and  32-bit code in the stub. It  will not work.

**Comment by jreiser** [comment]
In practice: Because any 32-bit API for a timed delay involves calling a named Windows subroutine, then doing so is impossible in the UPX stub for 32-bit PE executables. Instead, you can do a CPU busy wait by decrementing a counter repeatedly, etc.  Of course this is expensive in heat (energy), etc.

**Comment by zunair11** [comment]
@ml1050 yes , I realized that, but is there a way to implement the feature of delay using 32 bit code as such functionality namely of interrupt driven delays in 32 bit assembly seems to be non-existence.


Is there a resource to understand the assembly being used here as I am unable to pin down on what **assembly dialect** is being used and is it for **windows** as I understood or for **Linux** too.


Pardon my novice queries.


Thank you for your prompt reply

**Comment by jreiser** [comment]
Compress the smallest program that you can find or construct, that still does compress (is not too small.)  Use a programmer helper app to examine all sections of the compressed PE file.  Compare and correlate with src/stub/src/i386-win32.pe.S (particularly the `call` instructions), PackW32Pe::buildLoader(), src/pefile.cpp, and possibly others.  You are restricted to calling named low-level APIs that are already always present when the PE loader runs.  The assembly language in src/stub/src/*.S is the language of the target (in this case Win32 PE) with `section`s pieced together (at compress time) by a linker that is internal to UPX.

**Comment by zunair11** [comment]
> Compress the smallest program that you can find or construct, that still does compress (is not too small.) Use a programmer helper app to examine all sections of the compressed PE file. Compare and correlate with src/stub/src/i386-win32.pe.S (particularly the `call` instructions), PackW32Pe::buildLoader(), src/pefile.cpp, and possibly others. You are restricted to calling named low-level APIs that are already always present when the PE loader runs. The assembly language in src/stub/src/*.S is the language of the target (in this case Win32 PE) with `section`s pieced together (at compress time) by a linker that is internal to UPX.

Thanks @jreiser I am now clear that the language is for target.

I am a bit confused on your recommendation of comparing the compressed PE files, particularly how it would help me?.

I need my compressed PE file to be decompressed after some time delay this is what I am trying to achieve . So far I think I have to modify src/stub/src/i386-win32.pe.S as this is the code that gets packed with the compressed PE file, if I am correct.

Where in .s file and What type of code should I add is a bit unclear for me, as I am unable to find relavant code for delay in x86 32 bit assembly.

Thanks

**Comment by ml1050** [comment]
If you can find a kernel32 API that can sleep for you, then it's easy to add to UPX. Just search for the string "VirtualProtect" in the UPX source - and you will see what you need to do to  make you API entry work.

**Comment by zunair11** [comment]
Thanks @ml1050 I have found virtualProtect in i386-win32.pe.s. Are you trying to imply that I should use the win32 API in a similar fashion as VirtualProtect, or does VirtualProtect also has some modifications to be done. Please disregard my little knowledge of 32 bit assembly. Thanks

**Comment by ml1050** [comment]
You should use the win32 API in a similar fashion as VirtualProtect is used. Also look for VirtualProtect in the .cpp files, as adding code to the assembly is only half the work.

**Comment by zunair11** [comment]
@ml1050 what is the functionality of the cpp is there a document which could help me to read about how the stubs work. Although I know the basic working that the decompression stubs are embedded in the compressed executable if I am not wrong

**Comment by ml1050** [comment]
See doc/loader.txt.

**Comment by zunair11** [comment]
does the sequence of addLoader in p_w32pe.cpp sets the execution of section ?. As I want to add the delay first thing after the libraries are loaded. the kernel32 has a sleep function which takes in one argument so what I have inferred from the hints @ml1050  gave is that I have to do the following.

add section to assembly like

`addLoader("PETLSC2", NULL);`

define symbol in cpp like
```
linker->defineSymbol("GetProcAddress", 0u-rvamin +
                         ilinkerGetAddress("kernel32.dll", "Sleep"));
```

**Comment by ml1050** [comment]
linker->defineSymbol("Sleep", 0u-rvamin +
                         ilinkerGetAddress("kernel32.dll", "Sleep"));

**Comment by zunair11** [comment]
> ```
> linker->defineSymbol("Sleep", 0u-rvamin +
>                          ilinkerGetAddress("kernel32.dll", "Sleep"));
> ```

thanks for pointing that out. Also can you shed some light on the importance of sequence of addLoader

**Comment by zunair11** [comment]
@ml1050  as I am unable to comprehend the section precedence , I was thinking of adding my code in a existing section probably the one where getProcessAddress is used this will help me avoid declaring a new section but again I can not understand when will that be executed. Also I am of the understanding that the Imports should be completed before calling the sleep function in assembly stub

**Comment by ml1050** [comment]
Put your code into the beginning of PEMAIN20 (before popa).
You also need to add  addKernelImport("Sleep") into PeFile::addStubImports().

**Comment by zunair11** [comment]
@ml1050 I am getting this error 
`
InternalError: unknown symbol Sleep
`
It seems like that even after declaring the symbol it is still not resolving it.

I have imported Sleep from Kernel32.dll 

`linker->defineSymbol("Sleep", 0u-rvamin +
                            ilinkerGetAddress("kernel32.dll", "Sleep"));`

I have declared it just below LoadLibraryA

**Comment by ml1050** [comment]
Have you also added the code I wrote to you in my last comment?

**Comment by zunair11** [comment]
> Have you also added the code I wrote to you in my last comment?

`void PeFile::addStubImports()
{
    addKernelImport("LoadLibraryA");
    addKernelImport("GetProcAddress");
    if (!isdll)
        addKernelImport("ExitProcess");
    addKernelImport("VirtualProtect");
    **addKernelImport("Sleep");**
}`

yes like this in pefile.cpp

**Comment by zunair11** [comment]
UPX is getting build properly but packing file is throwing this error

**Comment by ml1050** [comment]
Are you sure that the assembly stub was also rebuilt?

**Comment by zunair11** [comment]
yes as the stub produced header file changes its size on adding code

**Comment by zunair11** [comment]
That was very irresponsible of me, apologies. Thanks @ml1050 it is resolved . will test now.
I though that UPX compilation and stub compilation happens simultaneously.

**Comment by zunair11** [comment]
@ml1050 thanks , but the sleep function is not working , rather it is not even letting the executable run. seems like I need to find a new method to implement delay

**Comment by zunair11** [comment]
@ml1050 the sleep function is working now as I was previously using the wrong register to pass the parameter.

I wanted to reposition the sleep function so it pauses the decompression of the executable, where should I put it. Also using what steps can I figure this out myself.

Thanks

**Comment by ml1050** [comment]
Do you want to put the code before the decompression? Append your code to the end of PEMAIN01. Check out PackW32Pe::buildLoader() if you want to find another place.

**Comment by zunair11** [comment]
@ml1050  yes I want to put my code before decompression. What I want to achieve is delay the unpacking of the executable by a set amount of time, so at one instance the program executed is packed and after a delay the program is unpacked.

I have placed my code in different location but that has only delayed the execution of the program but the code gets unpacked in memory immediately.

Please note now I am working on win64 and have changed the relevant files. I followed your instruction but the code immediately gets unpacked.

` section         PEMAIN01

                //; remember to keep stack aligned!
                push    rbx
                push    rsi
                push    rdi
                push    rbp
                lea     rsi, [rip + start_of_compressed]
                lea     rdi, [rsi + start_of_uncompressed]
               // Zunair Modification
                mov     rcx, 0xC350                      //; move the value of 50000 for 50 seconds delay
                call    [rip + Sleep]                        //; call the sleep function to implement delay
`

Thanks

**Comment by ml1050** [comment]
You need to align the stack correctly before calling win64 functions. Try adding 

`sub     rsp, 0x28`

before your call, and

`add     rsp, 0x28`

after it.

**Comment by zunair11** [comment]
@ml1050 I have tried this, but itgives same result

`  
section         PEMAIN01

                //; remember to keep stack aligned!
                push    rbx
                push    rsi
                push    rdi
                push    rbp
                lea     rsi, [rip + start_of_compressed]
                lea     rdi, [rsi + start_of_uncompressed]
               // Zunair Modification
                sub rsp, 0x28
                mov     rcx, 0xC350                      //; move the value of 50000 for 50 seconds delay
                call    [rip + Sleep]                        //; call the sleep function to implement delay
                add rsp, 0x28
`
I will reiterate what I am trying to achieve , I want to analyse files in memory before and after decompression, to see source code in both packed and unpacked phase. Although the delay works properly and the executable is delayed but before that delay I get unpacked code rather than packed one. Please suggest a work around.

**Comment by ml1050** [comment]
I guess you use a debugger to look at the memory. So why don't you simply use a breakpoint ?

**Comment by zunair11** [comment]
@ml1050 I am not using a debugger at the moment rather trying to work with memory dump as that will help me in my analysis down the road

**Comment by ml1050** [comment]
Add an infinite loop before the decompression.

**Comment by jreiser** [comment]
A total newbie has exhausted our patience.

**Comment by davehuhudave** [comment]
@ml1050, could you please do me a help in your free time? It's difficult to understand it under windows. Can you guide me on the specific steps ?  I want to XOR all the Bytes of decompressed application with special Byte, What can I do ?
Sincere thanks!

**Comment by ml1050** [comment]
Add a new filter.

**Comment by davehuhudave** [comment]
@ml1050, Can you be more specific？I roughly know to edit in 'i386-win32.pe.s ', but what position and how to edit it?

**Comment by ml1050** [comment]
Filters are used in UPX for post processing the decompressed data. If you want to XOR the decompressed data, then this is the right way to do it. You need to check out how the filter system is implemented, and create a new filter for yourself. You then only have to add your filter identifier to i386-win32.pe.s, and UPX will call everything in the right time for you if you implement the supporting code (not totally trivial unfortunately - but there are lots of examples you can look at).

**Comment by davehuhudave** [comment]
@ml1050, Thank you for your reply. I will try to learn the relevant content
