### ISSUE TITLE
Need clarification of UPX license

### ISSUE THREAD

**Issue by elainehsu5** [upx/upx#329]
## What's the problem (or question)?
Under "Abstract", it is stated that the terms of GPL ...still apply as compressing a program is a special form of linking with our stub". 

Under "SPECIAL EXCEPTION FOR COMPRESSED EXECUTABLES", it is stated that "Markus F.X.J. Oberhumer and Laszlo Molnar grant you special permission to freely use and distribute all UPX compressed programs (including commercial ones), subject to the following restrictions..."

Based upon the above two quoted statements, is a UPX compressed executable complying to all three restrictions "subject to" OR "exempted from" the terms of GNU GPL?

Thanks for your help.

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
By way of the "SPECIAL EXCPETION FOR COMPRESSED EXECUTABLES", then UPX places no [additional] GPL restrictions on an executable that has been compressed by UPX which was built from unmodified official sources.  If the executable input to UPX already was subject to GPL restrictions, then compressing that input with UPX does not [and cannot] change those pre-existing restrictions.
