### ISSUE TITLE
Go built exe changed behaviour

### ISSUE THREAD

**Issue by Pymann** [upx/upx#336]
## What's the problem (or question)?
I compiled a self-written go-tool, and compressed it with upx, an compressing the file changed the output.

i share file: 

`package main

import (
	"fmt"
	"bufio"
    "os"
    "encoding/hex"
)

func main() {

    path := os.Args[0]
    
    file, err := os.OpenFile(path, os.O_RDONLY, 0755)
    if err != nil {
        fmt.Printf("Error: %s\n", err.Error())
        os.Exit(1)
    }
    defer file.Close()
    
    sigbin_path := "./MyVariant_sig.txt"
    sig_file, err := os.OpenFile(sigbin_path, os.O_RDWR|os.O_CREATE, 0755)
    if err != nil {
        fmt.Printf("Error: %s\n", err.Error())
        os.Exit(1)
    }
    defer sig_file.Close()

    scanner := bufio.NewScanner(file)
    for scanner.Scan() {
        s:=scanner.Bytes()
        dst := make([]byte, hex.EncodedLen(len(s)))
        hex.Encode(dst, s)
        sig_file.WriteString(fmt.Sprintf("%s", string(dst)))
    }
}`

## What should have happened?
I expected same output

## Do you have an idea for a solution?
No.

## How can we reproduce the issue?
you can download golang, go build file.go
and then do upx ofile_compressed.exe file.exe
Its version 1.11.2 amd64

## Please tell us details about your environment.
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\EhrhardtN\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Data\Go-Projects
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

**Comment by bitraid** [comment]
You are reading different files each time (uncompressed vs compressed). You should expect different outputs.

**Comment by jreiser** [comment]
About reproducing the issue:  if the `go` language processor ever has existed in more than one version, then `you can download golang, go build file.go` probably depends on which version of `go`.  Therefore, please upload ("Attach files by ...") the exact executable file that is presented to upx for compression.  Gitlab wants to save space, so compress the executable using zip, gzip, or .tgz before uploading.

**Comment by Pymann** [comment]
> You are reading different files each time (uncompressed vs compressed). You should expect different outputs.

No, definitely both times I read uncompressed file. As you see in code, path is given via cmd, it has nothing to do with packing the exe.

> About reproducing the issue: if the go language processor ever has existed in more than one version, then you can download golang, go build file.go probably depends on which version of go. Therefore, please upload ("Attach files by ...") the exact executable file that is presented to upx for compression. Github wants to save space, so compress the executable using zip, gzip, or .tgz before uploading.

I added version its: 1.11.2 amd64

**Comment by Pymann** [comment]
[dumpbin.zip](https://github.com/upx/upx/files/4111999/dumpbin.zip)

**Comment by bitraid** [comment]
>No, definitely both times I read uncompressed file. As you see in code, path is given via cmd, it has nothing to do with packing the exe.

The path is not given via cmd, the path is set to `Args[0]` which is the name of the program.

**Comment by Pymann** [comment]
This can explan alot ...

**Comment by jreiser** [comment]
Closed: user error (incorrect source code for executable being compressed.)
