### ISSUE TITLE
Virus warning on Windows 64

### ISSUE THREAD

**Issue by manliomazzon** [upx/upx#337]
## What's the problem (or question)?
I'm getting a virus warning when using upx.exe on Windows 10, 64 bit.

## How can we reproduce the issue?

1. Downloaded 64 bit upx.exe
2. copied into a folder where I wanted to used it to compress a 64 bit windows app I just made
3. Get the virus warning shown in the attached image.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version: Windows 10
* Host CPU architecture: 64 bit
* Target Operating System and version: Windows
* Target CPU architecture: 64 bit

<img width="378" alt="upx" src="https://user-images.githubusercontent.com/49060526/73226804-a85d0600-4171-11ea-8339-68de9584bd32.png">

**Comment by jreiser** [comment]
Tell us which version of upx was used.  Running `upx --version` prints the version.  UPX also prints the version as the third line of output during compression, such as `UPX git-d53376+ Markus Oberhumer, ...`.
Tell us which anti-virus or anti-malware program, and which version, generated the warning.
Upload ("Attach files by ...") an actual compressed executable that triggers the warning.  Compress the upload using zip, gzip, or .tgz to help Github save space.

**Comment by manliomazzon** [comment]
Upx version: upx-3.96-win64
Anti-virus: Windows security, i.e. what comes bundled with Windows 10.
Anti-virus version: not sure but I let Windows 10 install all the updates automatically, so it's likely to be the very latest version of Windows Defender/Windows Security, or whatever they call it these days.
How was the warning generated:
I downloaded upx-3.96-win64.zip from the official web site (github), unzipped it, copied upx.exe in the same folder where my Delphi compiler saves the exe of my project. Then, I ran a bat file, from the same folder, that simply goes:
upx.exe myprogram.exe
(where myprogram.exe is what I just compiled with Delphi, and which I wanted to protect).
As soon as I try to run the above one-line bat file, I get the virus warning, and at the same time the upx.exe file itself disappears from the folder where I copied it. (I guess Windows Defender deems it dangerous enough to immediately delete it...)

**Comment by cristi-neagu** [comment]
Got a virus warning when scanning the latest release download with Bitdefender.
![image](https://user-images.githubusercontent.com/30549178/73446698-1e6d9280-4355-11ea-99cc-1c9e8a1c19a9.png)
Also, when i clicked the download link on the releases page Bitdefender gave me a warning about malicious links.

**Comment by 0x1001d00d** [comment]
On VirusTotal 19 engines detected upx.exe **(upx-3.96-win64)** positive.
[https://www.virustotal.com/gui/file/24624a9d3786d7ba93575383edf694505453af59b39b0463260a75c6344d0ae7/detection](url)
upx-3.96-win32, upx-3.95-win64, upx-3.95-win32, upx394w : no engines detected.

**Comment by necros2k7** [comment]
Use latest dev build it`s OK and close issue)
https://www.virustotal.com/gui/file/9b7244cc7a0ecdbad4b1b726fbb3adea13a5755e256d0335b9f929b545c08442/detection

**Comment by Tobias-B-Besemer** [comment]
Three noob questions here, befor I open new issues for it...

Are the Dev Builds anywhere to download as bineries ???

When comes the next realese ??? Because I try to fix a prob with virus detection...

Exist there any mirror, where I can download always the latest release with the samen URL ??? I would use in AppVeyor always the latest stable version of UPX and as the VM gets after each build destroyed, UPX must be each time downloaded...

**Comment by jreiser** [comment]
Downloadable binaries of `devel` builds: Visit the page https://github.com/upx/upx-automatic-builds
and follow the links.  One link to see the branches:   https://github.com/upx/upx-automatic-builds/branches/all and one method to fetch a specific branch:
```
  git clone -b THE_BRANCH_NAME --single-branch https://github.com/upx/upx-automatic-builds.git
```
For instance: https://github.com/upx/upx-automatic-builds/tree/devel-20200215-b72eac6-appveyor which has builds for Windows using various compilers with the b72eac6 commit as input source.  There is no URL which "floats" to the latest branch.

The date of the next release is not yet known.

**Comment by 0x1001d00d** [comment]
@necros2k7 this issue is about **precompiled** UPX versions. 
As can be learned from `upx/README.SRC`: 
> precompiled UPX versions are linked against the NRV compression library instead of the UCL library

and from
```
upx --version
upx 3.96
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43

upx-git-b72eac.exe --version
upx 4.0.0-git-b72eac69a5de
UCL data compression library 1.03
zlib data compression library 1.2.8
LZMA SDK version 4.43
```
These are different executable files that use different source codes.
Also, in addition to triggering antiviruses on Virustotal, a large and very suspicious difference is visible in the sandbox analysis. The version from Github does not raise suspicions (note that I am not an expert in this area and this is only at my first glance)
https://www.hybrid-analysis.com/sample/972cbc336a87f5666e34f13864c53e65e0918b7f6226747730c4e493b4f0d6b8/5e56b64705dfc831a2236488 
All “MITRE ATT&CK™ Techniques Detection”s explainable and are false positives.

But on precompiled upx 3.96 64-bit:
https://www.hybrid-analysis.com/sample/24624a9d3786d7ba93575383edf694505453af59b39b0463260a75c6344d0ae7/5e56b6e440712d7a436820de
MITRE ATT&CK™ Technique - T1055 - Process Injection
MITRE ATT&CK™ Technique - T1076 - Remote Desktop Protocol
Reads terminal service related keys (often RDP related)
"upx.exe" (Path: "HKLM\SYSTEM\CONTROLSET001\CONTROL\TERMINAL SERVER"; Key: "TSUSERENABLED") 

Precompiled upx 3.96 32-bit:
https://www.hybrid-analysis.com/sample/7beeec92a73c0e42b0fa7c4cdc3a1f609dd4c7f2b8ada78edd036ba6e45e0773/5e3378652d3fc9728f77bb23
Same as precompiled 64-bit plus:
MITRE ATT&CK™ Technique - T1179 - Hooking
Installs hooks/patches the running process
"upx_.exe" wrote bytes "711146027a3b4502ab8b02007f950200fc8c0200729602006cc805001ecd42027d264202" to virtual address "0x74CE07E4" (part of module "USER32.DLL")

There are many other differences in behavior from the Github version (without NRV): in accessing the registry, used DLLs, and so on, which does not fit into the claimed other implementation of the same compression algorithm.
For pointing to builds based entirely on open source, thank you and @jreiser , but I think you should not ignore the warning issued by these builds 
> WARNING: this is an unstable beta version - use for testing only! Really.

**Comment by markus-oberhumer** [comment]
Could you also try if you get these false positives with our older precompiled UPX versions like 3.95 and 3.94 ?

**Comment by markus-oberhumer** [comment]
> Could you also try if you get these false positives with our older precompiled UPX versions like 3.95 and 3.94 ?

Oh, I've just seen that this has already been answered in https://github.com/upx/upx/issues/337#issuecomment-580504082 .

First JFYI all prebuilt versions are built using cross-compilers under Linux.

Are all win64/pe programs compressed by upx 3.96 affected, or is just our prebuilt upx-3.96-win64.zip itself that triggers these warnings?

And I've just visited https://www.virustotal.com/gui/file/24624a9d3786d7ba93575383edf694505453af59b39b0463260a75c6344d0ae7/detection and it seems that as of today only 8 engines (down from 21) detect it as a possible threat, so maybe it's just a matter of time until the engines get new updates and everything is fine again.

**Comment by markus-oberhumer** [comment]
[Wrong button, didn't mean to close this issue]

**Comment by markus-oberhumer** [comment]
For future discussion please use the following **filenames** to avoid ambiguities - they are listed here with sha256 checksum and file size in bytes.

(The *-packed.exe files are the official prebuilt releases).

```
d634cde09d1aa1320a1d4c589d35d306f8350129faf225b2bca394128c2c4442  411648 upx-3.96-win32-packed.exe
7beeec92a73c0e42b0fa7c4cdc3a1f609dd4c7f2b8ada78edd036ba6e45e0773 2007040 upx-3.96-win32-unpacked.exe
24624a9d3786d7ba93575383edf694505453af59b39b0463260a75c6344d0ae7  412672 upx-3.96-win64-packed.exe
e3d7bf452a9283ef0a48853f5947450e90b4417d42155e1e15ba97672ab365f5 2070016 upx-3.96-win64-unpacked.exe
```

**Comment by markus-oberhumer** [comment]
And here are the corresponding links on VirusTotal:

upx-3.96-win32-packed.exe
https://www.virustotal.com/gui/file/d634cde09d1aa1320a1d4c589d35d306f8350129faf225b2bca394128c2c4442/detection

upx-3.96-win32-unpacked.exe
https://www.virustotal.com/gui/file/7beeec92a73c0e42b0fa7c4cdc3a1f609dd4c7f2b8ada78edd036ba6e45e0773/detection

upx-3.96-win64-packed.exe
https://www.virustotal.com/gui/file/24624a9d3786d7ba93575383edf694505453af59b39b0463260a75c6344d0ae7/detection

upx-3.96-win64-unpacked.exe
https://www.virustotal.com/gui/file/e3d7bf452a9283ef0a48853f5947450e90b4417d42155e1e15ba97672ab365f5/detection

**Comment by markus-oberhumer** [comment]
And just for comparision, here are the corresponding links on VirusTotal for UPX 3.95 (which was released in Aug 2018):

upx-3.95-win32-packed.exe
https://www.virustotal.com/gui/file/803bd799ffa8bac5113f230b6eb21bff543b8670d225e47e263b75c44692634e/detection

upx-3.95-win32-unpacked.exe
https://www.virustotal.com/gui/file/e0dfcb440bb43d53cf68f0178429a5136f8f7f13544499ad17699a98a6f8ffc0/detection

upx-3.95-win64-packed.exe
https://www.virustotal.com/gui/file/3660fa3c1e91917e8388c85e222bf3973edebf89f5898b2908111c981481dd40/detection

upx-3.95-win64-unpacked.exe
https://www.virustotal.com/gui/file/c5007328ffcec842bb808329470afd71c9f7bf6416f5f5c978be1f942fe72618/detection

**Comment by kbh81** [comment]
I have the same problem on upx 3.96 win64. At first (a few days ago) Windows Defender (I do not have any additional virus scanner running) did allow me to open and compress my AutoHotKey exe files, but as soon as I moved or wanted to open the result files, it caught. Now (attached version information) I can not even open upx (precompiled versions 3.96 and 3.95 both tested) anymore.
![WindowsSecurityVersion](https://user-images.githubusercontent.com/55461942/76687529-d8ae1600-65f2-11ea-8bf5-0619e4663083.JPG)
![WindowsVersion](https://user-images.githubusercontent.com/55461942/76687531-d946ac80-65f2-11ea-8fca-81f78163012e.JPG)

**Comment by bakito** [comment]
My company also detects the file as threat.
![positive](https://user-images.githubusercontent.com/2733215/77053121-23060d00-69ce-11ea-8ed3-027d2539e0df.PNG)

**Comment by jreiser** [comment]
@danilw See the pinned report https://github.com/upx/upx/issues/437.  Your antivirus vendors deserve a swift kick in the pants.  They have not learned in over **20 years**.

**Comment by markus-oberhumer** [comment]
I'm closing this now. Please refer to #437, and feel free to open a new issue if there are new aspects.

**Comment by danilw** [comment]
I got 3 scam emails coming from this thread

![image](https://github.com/user-attachments/assets/f2c34ced-fa5e-4ef3-840d-194ce0b40da0)

> Your payment has been successfully received, and your e-billing has
been updated. The invoice is attached for your reference and review.

(it say $691 payment... no idea what they want.. email come from random-numbers at gmail - scam I assume)

Anyone else got this?

**Comment by metal3d** [comment]
Actually the problem happens with compressed binaires too. I compress Katenary application with upx (inside Linux), and Windows Defender (inside a VM) detects my app as malware.

**Comment by jreiser** [comment]
> ... Windows Defender (inside a VM) detects my app as malware.

See  pinned issue https://github.com/upx/upx/issues/437  "False positive antivirus alerts of official UPX releases #437".
Don't believe everything that you read from the internet, especially from only one anti-malware program, regardless of which one it is.
Official releases of UPX itself contain no malware, and compression by UPX does not create any "new" malware. Thus such complaints by an anti-malware program are "false positive" reports.  From time to time it is necessary for end users of UPX to remind their anti-malware vendor of this fact; and this is the only way that such vendors learn.
