### ISSUE TITLE
packed dll relocation problem

### ISSUE THREAD

**Issue by ajr0n** [upx/upx#338]
## What's the problem (or question)?
The application crashes when trying to load a packed dll to a non-default address.
An exception occurs in Windows dll loader while processing the relocation table.

## What should have happened?
The application should always load packed dll.

## Do you have an idea for a solution?
Dll library packed with upx 2.90 works with no problem.

## How can we reproduce the issue?

1. Download [test.zip](https://github.com/upx/upx/files/4127931/test.zip)

dlllib.dll (in test.zip) is library created with Visual Studio 2017. The source code is:

```
#pragma comment(linker, "/ENTRY:DllMain")
#include <windows.h>

__declspec(thread) int test[64]; // array to avoid not compressible exception in upx 2.90

extern "C" __declspec(dllexport) int* Test() { return test; }

BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpReserved) { return TRUE; }
```
2.  Pack dlllib.dll library and create second copy:

```
upx dlllib.dll -o test1.dll
copy test1.dll test2.dll
```
3. Create windows app with code below, and run app.

```
#include <windows.h>

int main()
{
	::LoadLibrary("test1.dll");
	::LoadLibrary("test2.dll"); // loads the library to a different address
	return 0;
}
```

4. test.zip contains versions of dlllib.dll packed with upx 2.90 (test_0.dll, test_1.dll) and packed with upx 3.96 (test_2.dll, test_3.dll). You can run loadlib.exe (in test.zip)  to see the problem. The code for loadlib is:

```
#include <windows.h>
#include <iostream>
using namespace std;

int main()
{
	HMODULE h1, h2, h3, h4;

	h1 = ::LoadLibrary("test_0.dll");
	cout << "LoadLibrary('test_0.dll') = 0x" << hex << reinterpret_cast<size_t>(h1) << endl;

	h2 = ::LoadLibrary("test_1.dll");
	cout << "LoadLibrary('test_1.dll') = 0x" << hex << reinterpret_cast<size_t>(h2) << endl;

	h3 = ::LoadLibrary("test_2.dll");
	cout << "LoadLibrary('test_2.dll') = 0x" << hex << reinterpret_cast<size_t>(h3) << endl;

	h4 = ::LoadLibrary("test_3.dll");
	cout << "LoadLibrary('test_3.dll') = 0x" << hex << reinterpret_cast<size_t>(h4) << endl;

	if(h1 == NULL || h2 == NULL || h3 == NULL || h4 == NULL)
	{
		::SetConsoleTextAttribute(::GetStdHandle(STD_OUTPUT_HANDLE), FOREGROUND_RED | FOREGROUND_INTENSITY);
		cout << "Module load error" << endl;
		return 1;
	}

	return 0;
}
```

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.96
* Host Operating System and version: Windows 7
* Host CPU architecture: x64
* Target Operating System and version: Win32
* Target CPU architecture: x32

**Comment by levicki** [comment]
Your test DLLs packed with UPX 2.90 load at randomized base address, while the ones packed with 3.96 load at `0x10000000` which is the old fixed default base address. If you unpack either `test_2.dll` or `test_3.dll` all of them will load.

It seems that for DLLs packed with UPX 3.96 the system is trying to load two DLLs at the same base address (`0x10000000`) and failing to load the second one for obvious reasons.

This doesn't happen with 64-bit DLLs.

**Comment by ajr0n** [comment]
The packed dll should always be able to load at any address, like original dll before packing.

**Comment by levicki** [comment]
@ajr0n I agree, I was just clarifying what seems to be going on.

**Comment by Mattiwatti** [comment]
This is the same bug as #83 (invalid relocation block generated for TLS directory). Using the fix I posted on that issue I can get the test program to work correctly, i.e. all DLLs are properly relocated.
