### ISSUE TITLE
Decompression fails for i386 ELF shared library

### ISSUE THREAD

**Issue by jreiser** [upx/upx#341]
same with 3.96

_Originally posted by @afwn90cj93201nixr2e1re in https://github.com/upx/upx/issues/218#issuecomment-580852245_

This is a new issue with de-compressing ELF shared library for i386.  It is unrelated to #218 for MacOS x86_64, which was for MachO format.

**Comment by jreiser** [comment]
The relevant attached files from #218:
```
https://github.com/upx/upx/files/4142173/testsuite.zip   # asd_i386.so and Compile.sh
https://github.com/upx/upx/files/4142175/version_script.zip  # version_script.lds
https://github.com/upx/upx/files/4142269/test_i386.zip  # test_386.so
```
The complaint:
```
$ upx.out -f -o foo test_i386.so
$ upx.out -f -o bar -d foo
upx.out: foo: NotPackedException: not packed by UPX
```

**Comment by afwn90cj93201nixr2e1re** [comment]
@jreiser can you delete your comment and write new one?

[source.zip](https://github.com/upx/upx/files/4143683/source.zip)

here is source, archive contains compiled binary file too


cd dir && ./Compile.sh && ./upx -t -9 t1.so


I tried to remove all relevant options, but nothing was changed.

**Comment by afwn90cj93201nixr2e1re** [comment]
Btw problem is not in decompression as i said it's compress, but there is segfault on load.

Main problem in compression algorithm, seems like it's just broken.

**Comment by afwn90cj93201nixr2e1re** [comment]
Also to indicate problem you can run ./upx -l lib.so, which also gonna fail(seems like it's have built-in -t option?), but --best -9 works without fail, btw here's decompression problem.

**Comment by afwn90cj93201nixr2e1re** [comment]
any updates?

**Comment by afwn90cj93201nixr2e1re** [comment]
@jreiser im not sure, is that makes a sense but im trying to run upx 3.95, 3.96 on amd64 machine, and it's just ouput './upx: cannot execute binary file: Exec format error'.

Btw 3.94 works fine.

**Comment by jreiser** [comment]
The problem seems to relate to the large size of debug information.  I'm still looking.

**Comment by afwn90cj93201nixr2e1re** [comment]
Any updates @jreiser ?

**Comment by afwn90cj93201nixr2e1re** [comment]
xD, thanks for fast response.

**Comment by afwn90cj93201nixr2e1re** [comment]
1) Is that ready at least in developer branch? How i can compile it? (mb possible you should make prelease for developer branches too? For example with github actions)

2) Can you explain how we possible can dump shared dynamic library from memory when it loaded and unpacked?
Coz there's no manuals about **shared dynamic _libraries_** at all, only about executables.
For example:
https://github.com/lIkesimba9/UPX_ELF_UNPACK

And etc.

Im dumping it from memory and using this script.
```
gdb --pid (number)
> (inside gdb) dump memory /root/cs/memdump 0xed404000(start) 0xed40e000(end)
> quit
./bin2elf.sh memory memory.so 0x00000000
```

```
#!/bin/sh
# Usage: memtoelf memdump outputname baseaddr
echo $$;
echo $1;
echo $2;
echo $3;
cat > raw$$.ld <<EOF
SECTIONS
{
EOF

echo " . = $3;" >> raw$$.ld

cat >> raw$$.ld <<EOF
  .text : { *(.text) }
}
EOF

ld -b binary -r -o raw$$.elf $1 -m elf_i386
objcopy  --rename-section .data=.text --set-section-flags .data=alloc,code,load raw$$.elf
ld raw$$.elf -T raw$$.ld -o $2 -m elf_i386
#strip -s $2 # Is that really needed?

rm -rf raw$$.elf raw$$.ld
```
btw after that i getting this err:
![изображение](https://user-images.githubusercontent.com/9306996/90090303-32864980-dd13-11ea-8629-11d7ff0e746b.png)
![изображение](https://user-images.githubusercontent.com/9306996/90090307-35813a00-dd13-11ea-8c3f-6f22269391a4.png)
(also there's no import/export tables)

Did you ever tried to dump and restore elf dynamic library from memory or core dump (also there's core2elf btw it's doesn't work especially with that so file)?
@jreiser 

If you need a file i can provide it, but if it's possible to email.
Waiting for response.

**Comment by afwn90cj93201nixr2e1re** [comment]
1) Is that ready at least in developer branch? How i can compile it? (mb possible you should make prelease for developer branches too? For example with github actions)

2) Can you explain how we possible can dump shared dynamic library from memory when it loaded and unpacked?
Coz there's no manuals about **shared dynamic _libraries_** at all, only about executables.
For example:
https://github.com/lIkesimba9/UPX_ELF_UNPACK

And etc.

Im dumping it from memory and using this script.
```
gdb --pid (number)
> (inside gdb) dump memory /root/lua-scripts/lua-server/memdump 0xed404000(start) 0xed40e000(end)
> quit
./bin2elf.sh memory memory.so 0x00000000
```

```
#!/bin/sh
# Usage: memtoelf memdump outputname baseaddr
echo $$;
echo $1;
echo $2;
echo $3;
cat > raw$$.ld <<EOF
SECTIONS
{
EOF

echo " . = $3;" >> raw$$.ld

cat >> raw$$.ld <<EOF
  .text : { *(.text) }
}
EOF

ld -b binary -r -o raw$$.elf $1 -m elf_i386
objcopy  --rename-section .data=.text --set-section-flags .data=alloc,code,load raw$$.elf
ld raw$$.elf -T raw$$.ld -o $2 -m elf_i386
#strip -s $2 # Is that really needed?

rm -rf raw$$.elf raw$$.ld
```
btw after that i getting this err:
![изображение](https://user-images.githubusercontent.com/9306996/90090303-32864980-dd13-11ea-8629-11d7ff0e746b.png)
![изображение](https://user-images.githubusercontent.com/9306996/90090307-35813a00-dd13-11ea-8c3f-6f22269391a4.png)
(also there's no import/export tables)

Did you ever tried to dump and restore elf dynamic library from memory or core dump (also there's core2elf btw it's doesn't work especially with that so file)?
@jreiser 

If you need a file i can provide it, but if it's possible to email.
Waiting for response.

**Comment by afwn90cj93201nixr2e1re** [comment]
Any updates on resolving this issue?

**Comment by markus-oberhumer** [comment]
What is the status of this issue?

**Comment by jreiser** [comment]
Status is "not forgotten", but the fix is complicated by the change in ELF layout to 4 PT_LOAD segments: ELF headers and rtld symbol tables with protection `r--`, executable code `r-x`, constant data `r--`, writable data `rw-`; from the old format when executable code did not have a PT_LOAD all to itself.  Handling all cases, old and new, is cumbersome.

**Comment by markus-oberhumer** [comment]
Ok, thanks! Milestone v5.0.0 then.

**Comment by zmtong1988** [comment]
upx  -d   ELF shared library for i386.
err:InternalError: MemBuffer raw_bytes invalid size

**Comment by jreiser** [comment]
@xiaotong1988 Please upload ("Attach files by ..." in the footer of any comment) or give the URL of an actual file which fails (before compression by UPX.)  Compress the file by zip, gip, or .tgz for transport.  If that is not possible, then please run `readelf --headers ./my_file` and post the output here.

**Comment by afwn90cj93201nixr2e1re** [comment]
I think your mention did not work this time, so you have to repeat. @jreiser, or i can if you need, @zmtong1988.

**Comment by zmtong1988** [comment]
@afwn90cj93201nixr2e1re 
Thank you for your answer.

@jreiser modifications have enabled compression and availability of the i386/amd64 ELF shared library (. so file). There is no problem executing 4 PT_LOAD.

If you have a better way to implement it, I can try using and learning.
