### ISSUE TITLE
feature request: fix test suite to work with release tarball

### ISSUE THREAD

**Issue by ncopa** [upx/upx#343]
## What's the problem (or question)?

It would be nice to have a testsuite for downstream packagers to verify that the compiled upx binary actually works.

Downstream discussion: https://gitlab.alpinelinux.org/alpine/aports/merge_requests/3753

## What should have happened?

It would be nice if there was a `make check` or similar that tests if the built upx binary works.

## Do you have an idea for a solution?

create a `tests/` subdir with some basic tests that can be run to verify that the built binary works.

Example of tests can be found here:
https://git.alpinelinux.org/aports/tree/community/upx/APKBUILD?id=4000113176ed2aaaf24894857a7808ca3ad565bf#n21

Having tests would also be useful for a CI, so you can verify that pull requests does not unexpectedly break things.

## How can we reproduce the issue?

run `make check`.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.96
* Host Operating System and version: Alpine Linux edge (rolling)
* Host CPU architecture: various (x86, x86_64, s390x, armv7, ppc64le, aarch64)
* Target Operating System and version: same as host CPU arch
* Target CPU architecture: same as host CPU arch.

**Comment by jreiser** [comment]
Please compare with `cd src; make run-testsuite` that already exists in UPX.

**Comment by ncopa** [comment]
Ah, very nice! I totally missed that, sorry.

A few suggestions that would be good for downstream packagers:
- merge this git repo into upx so the tests are shipped with the release tarball.
- make it work without travis (include the travis_testsuite_1.sh in the release tarball - and maybe rename it)
- add a make target `make check` that does `$(MAKE) -C src run-testuite`.

I have not been able to run the tests from the release tarball due to the missing .github directory.

Thanks!
