### ISSUE TITLE
internal error when compressing HDSDR.EXE under Windows

### ISSUE THREAD

**Issue by xrayer** [upx/upx#344]
## What's the problem (or question)?
upx: HDSDR.EXE: InternalError: should not happen

## What should have happened?
should not happen :)

## How can we reproduce the issue?

1. Download HDSDR 2.80 http://www.hdsdr.de/download/HDSDR280b13_install.exe
2. install (or extract installer files)
3. pack the HDSDR.EXE

## Please tell us details about your environment.

* upx 3.96
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Copyright (C) 1996-2020 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2020 Laszlo Molnar
Copyright (C) 2000-2020 John F. Reiser
Copyright (C) 2002-2020 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upxw -L'.
* WinXP SP3
* core i7-2600K
* Win2k-10
* x86-32

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") a plain .zip, .gz, or .tgz file that contains HDSDR.EXE.  UPX development is done on Linux, where "install the .EXE" does not work.

**Comment by xrayer** [comment]
Hi, get file here: http://www.rayer.g6.cz/1tmp/HDSDR.ZIP

**Comment by Mattiwatti** [comment]
This is the same bug as #223 (UPX cannot deal with import descriptors containing 0 function entries that are generated by the Embarcadero linker). There are two separate fixes posted there.

**Comment by necros2k7** [comment]
Isn`t it the same with https://github.com/upx/upx/issues/168 ? Close if so pls

**Comment by xrayer** [comment]
Seems to be...
