### ISSUE TITLE
Feat req. - auto "leanify" exe after compression / make option flag to leanify

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#347]
https://github.com/JayXon/Leanify

**Comment by jreiser** [comment]
No.  Write a two-line shell script.

**Comment by jreiser** [comment]
Besides, from the README.md then "leanify" should be run before UPX.  Particularly debug information is likely to lose its identity after processing by UPX, so "leanify" cannot remove it.

**Comment by necros2k7** [comment]
should be, but practically less size is after upx not before
