### ISSUE TITLE
Unable to compress GCC compiled EXE files under Windows

### ISSUE THREAD

**Issue by dbyoung720** [upx/upx#348]
Unable to compress GCC compiled EXE files under Windows

https://github.com/dbyoung720/FFUI/blob/master/bin/Win32/video/mpv/mpv.exe

**Comment by bitraid** [comment]
What version of binutils are you using?

**Comment by dbyoung720** [comment]
upx-3.96-win32

**Comment by dbyoung720** [comment]
upx-3.96-win64 also no

**Comment by dbyoung720** [comment]
https://github.com/dbyoung720/FFUI/blob/master/bin/Win64/video/mpv/mpv.7z

**Comment by dbyoung720** [comment]
unzip mpv.7z, Win64 mpv.exe

**Comment by bitraid** [comment]
I'm referring to [GNU binutils](https://www.gnu.org/software/binutils/)

**Comment by dbyoung720** [comment]
msys2 (gcc) compile

**Comment by dbyoung720** [comment]
mingw-w64-i686-binutils-2.34-1  (x86)
mingw-w64-x86_64-binutils-2.34-1 (x64)

**Comment by bitraid** [comment]
This is probably a linker bug. Use `--force` with upx.

**Comment by dbyoung720** [comment]
test 
add -f  
x86/x64 OK
