### ISSUE TITLE
List of known compressible mimetypes

### ISSUE THREAD

**Issue by quequotion** [upx/upx#349]
## What's the problem (or question)?
I'd like to be able to find, in documentation, a list of mimtypes (ie `application/x-executable`, etc) known to be safe to compress with upx. I've tried looking through the code, but I was quickly overwhelmed. The filter documentation lists some types of files, but not all, and not in mime format.

This would be a big help for [makepkg-optimize](https://aur.archlinux.org/packages/makepkg-optimize) which attempts [to use upx to compress executables](https://aur.archlinux.org/cgit/aur.git/tree/upx.sh.in?h=makepkg-optimize) (and perhaps shared libraries?) when building packages with makepkg.

Currently, I've only whitelisted `application/x-executable` and `application/x-dosexec` as I am unsure if any other types are safe (in particular, I'd like to add `application/x-sharedlib` and `application/x-pie-executable`).

## What should have happened? / Do you have an idea for a solution?
It would be helpful to have documentation that lists mimetypes that upx has been tested on, showing them to be safe or unsafe to compress.

**Comment by namazso** [comment]
i'm pretty sure upx will gracefully and safely fail on anything not compressible

**Comment by jreiser** [comment]
`doc/upx.doc` contains a list that is somewhat complete.  What UPX compresses are `executables` for various combinations of hardware, operating system, and executable formats supported by that operating system.  It seems that mimetypes do not enumerate that space; if they do, then please post the URL of such a list; how the entries are spelled matters.  As for source code, see 
```
// Executable formats. Note: big endian types are >= 128.
```
in `src/conf.h`.

**Comment by jreiser** [comment]
Closing because mime types in their present form (both standardized and de facto; https://en.wikipedia.org/wiki/Media_type) do not contain the necessary information: CPU architecture, operating system, executable encoding format.
