### ISSUE TITLE
Could not find the section that owns the Delay Import Directory

### ISSUE THREAD

**Issue by svaccari** [upx/upx#35]
## What's the problem (or question)?
exe cannot be executed

## What should have happened?
program should have started

## Do you have an idea for a solution?
Dependency Walker says: "Could not find the section that owns the Delay Import Directory"

## How can we reproduce the issue?
UPX is called without parameters (all defaults).
It only happens with my executable.
Decompression is fine.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.92
* Operating System and version: Windows 10 64bit
* CPU architecture: compressed exe is 32bit

**Comment by ml1050** [comment]
Can you please try UPX 3.91?

**Comment by svaccari** [comment]
Yes, but not until January the 9th

**Comment by ml1050** [comment]
You may also want to check out the devel branch, which contains some fixes for 3.92.

**Comment by svaccari** [comment]
Cannot reproduce the problem anymore after my code changed.
Version 3.92 seems now fine.
Thanks.
