### ISSUE TITLE
Return of "CantPackException: size of Load Configuration directory unexpected"

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#352]
## What's the problem (or question)?
CantPackException: size of Load Configuration directory unexpected - during exe compression with 3.93, 3.95, exe corruption with latest dev version

## What should have happened?
compressed 
## Do you have an idea for a solution?
nope

## How can we reproduce the issue?
1. compress attached file
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.93, 3.95, latest dev
* Host Operating System and version: win10 1909 x64
* Host CPU architecture: x64
* Target Operating System and version: same as above
* Target CPU architecture: same as above
[Leanify.exe.gz](https://github.com/upx/upx/files/4362356/Leanify.exe.gz)

**Comment by jreiser** [comment]
@necros2k7 Did you try with the recent release 3.96?  Please also specify the git commit which you used for "latest dev".  The one I see is
```
commit b72eac69a5de09e63c77838f4cd22be1de54805f (origin/devel)
Author: John Reiser <jreiser@...>
Date:   Sat Feb 15 15:04:44 2020 -0800
```

**Comment by necros2k7** [comment]
after compressing with 3.96 - "not supported win16 app"
i used - https://github.com/upx/upx-automatic-builds/tree/devel-20200215-b72eac6-appveyor

**Comment by jreiser** [comment]
This was fixed by 6428292477e03ca024aa7cf6e1f2b0bd46e6f5ed .

**Comment by necros2k7** [comment]
Thanx, is it in binary already?

**Comment by jreiser** [comment]
The fix is on the `devel` branch.  Commits to the `devel` branch are auto-built for Linux and Windows.  See the second part of https://github.com/upx/upx/issues/405#issuecomment-687362939 for how to access recent auto-builds.
