### ISSUE TITLE
Why x64 MSVC12 dev build is faster then x64 MSVC14.1 one?

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#353]
## What's the problem (or question)?
builds performance
## What should have happened?
msvc14.1outperform msvc12?
## Do you have an idea for a solution?
-

## How can we reproduce the issue?
1. bench 2 builds
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): latest dev
* Host Operating System and version: win10 1909 x64
* Host CPU architecture: x64
* Target Operating System and version: same as above
* Target CPU architecture: same as above

**Comment by jreiser** [comment]
@necros2k7 What are your results?  Please specify the inputs and the measured times for compression.

**Comment by necros2k7** [comment]
my bad, wrong benchmarking
