### ISSUE TITLE
Still no * wildcard support on latest 20-09-06 win build

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#354]
## What should have happened?
trying to pack several dlls:
"upx *.dll"
upx: *.dll: FileNotFoundException: *.dll: No such file or directory

## Do you have an idea for a solution?
Enable appropriate flags during Appveyor compilation to support it

## How can we reproduce the issue?
try to pack several dlls

## Please tell us details about your environment.

* UPX version used (`upx --version`): https://github.com/upx/upx-automatic-builds latest appveyor msvc 14.1 x64 build
* Host Operating System and version: win10 2004
* Host CPU architecture: x64
* Target Operating System and version: win10 2004
* Target CPU architecture: x64

**Comment by jreiser** [comment]
Name a previous version in which the current "regression" worked as you desire.

**Comment by necros2k7** [comment]
3.96 works fine

**Comment by jreiser** [comment]
@necros2k7 Looking at the git log:
```
commit d7ba31cab8ce8d95d2c10e88d2ec787ac52005ef (tag: v3.96, origin/master, origin/HEAD)
Author: Markus F.X.J. Oberhumer <markus@...>
Date:   Wed Jan 22 22:29:58 2020 +0100
```
Then we can find the differences between commit d7ba31cab8ce8d95d2c10e88d2ec787ac52005ef and commit b72eac6:
```
$ git diff d7ba31cab8ce8d95d2c10e88d2ec787ac52005ef b72eac6  |  grep +++
+++ b/.github/travis_testsuite_1-expected_sha256sums.sh
+++ b/BUGS
+++ b/NEWS
+++ b/PROJECTS
+++ b/README
+++ b/README.1ST
+++ b/THANKS
+++ b/src/help.cpp
+++ b/src/main.cpp
+++ b/src/p_lx_elf.cpp
+++ b/src/stub/mips.r3000-linux.elf-fold.h
+++ b/src/stub/mipsel.r3000-linux.elf-fold.h
+++ b/src/stub/src/include/linux.h
+++ b/src/stub/tmp/mips.r3000-linux.elf-fold.map
+++ b/src/stub/tmp/mipsel.r3000-linux.elf-fold.map
+++ b/src/version.h
```
and inspecting those shows nothing that affects PE files.  So it is highly that the problem is not in the UPX source code.

**Comment by necros2k7** [comment]
then problem in what?)

**Comment by jreiser** [comment]
Possibilities include:
```
1. different language support run-time libraries used when building upx.exe.
   Several different build systems and/or compilers are used by Appveyor;
   each produces a different upx.exe.
2. different run-time environment used during testing (CMD vs PowerShell,
   MSVC runtime versions, etc.)
3. misunderstanding (or even "silly error") in the meaning of "*.dll".

**Comment by bitraid** [comment]
For wildcard expansion to work with msvc, the program must be linked with `setargv.obj`.

**Comment by bitraid** [comment]
Thats not the case with older versions though. Maybe a variable should be set in `.appveyor.yml` with the link parameter for msvc 14.x.
