### ISSUE TITLE
Compression of object files

### ISSUE THREAD

**Issue by michaeleisel** [upx/upx#355]
## What's the problem (or question)?
Currently, when I try to compress an x86-64 object file for MacOS, it fails. It appears that this file type is not supported.

## What should have happened?
It'd be great if it was supported. For object files (and static libraries) sent across the network for remote builds, download speed can easily eclipse compilation time. Making those files smaller would be a big win (and remove the need for complicated multi-level caches to make downloads so fast). Remote builds and caching are used by many, many companies at scale, so better compression would be a big win.

## Do you have an idea for a solution?
No, I just imagine that a lot of existing code could be reused to do this.

## How can we reproduce the issue?
See problem statement.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
* Host Operating System and version: MacOS 10.15
* Host CPU architecture: x86-64
* Target Operating System and version: Same as host
* Target CPU architecture: Same as host

**Comment by jreiser** [comment]
At run time, UPX works by intercepting control of execution, de-compressing the payload, then resuming execution.  An object file that is not executable does not have any execution for UPX to intercept.  Instead, use a general-purpose compression utility such as zip, gzip, etc when sending an object file across  a network. If the remote build/caching system transfers files by http or https, then most browsers (including firefox and chrome) have a setting which uses gzip compression automatically, without any explicit per-transfer requests.

**Comment by michaeleisel** [comment]
I see, makes sense
