### ISSUE TITLE
compressed executable print errormessage

### ISSUE THREAD

**Issue by lazna** [upx/upx#356]
## What's the problem (or question)?
Compressing [exiftool executable](https://exiftool.org/exiftool-11.92.zip) is successfull, but when running executable, it print errormessage:

```
format error: bad signature: 0x403434bb at offset 3210625 in file c:\utils\exiftool.exe at -e line 639.
format error: bad signature: 0xd9503a5c at offset 3210659 in file c:\utils\exiftool.exe at -e line 639.

```
When process `upx.exe -d exiftool.exe` problem disappear

## What should have happened?
It should run without errormessage

## Do you have an idea for a solution?
have no idea

## How can we reproduce the issue?
1. Download archive provided in link
2. Decompress exiftool(k).exe
3. Rename it to exiftool.exe
4. Perform `upx.exe --ultra-brute exiftool.exe`
5. Run `exiftool -ver`

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.96w
* Host Operating System and version: Windows 10 / 64 bit
* Host CPU architecture: Intel
* Target Operating System and version: Windows 10 /64 bit
* Target CPU architecture: Intel

**Comment by bitraid** [comment]
That's because the exiftool executable contains zip overlay data (that conains its perl code) which is read from disk (and extracted at `temp` on first run). This also means that there is not much sense in compressing the file (most of the file size is the zip archive).

**Comment by lazna** [comment]
Thanks for this explanation
