### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by michaeleisel** [upx/upx#358]
## What's the problem (or question)?
iOS is not supported

## What should have happened?
This ticket is to brainstorm ways of using UPX with iOS. The big win here would be to decrease app download size (rather than on-disk size after it's been downloaded). Currently, Apple serves app binaries as part of a .ipa file, which is basically a zip file and which has zip compression. Being able to use arbitrary compression formats for the binary rather than their particular zip compression can offer big savings.

## Do you have an idea for a solution?
This would be difficult at least, and may just be totally impossible. But here are some thoughts:
- How would code signing be dealt with? E.g., perhaps it could store the compressed binary in a dynamic library somehow, and replace the real binary at runtime after Apple has loaded that binary fully from disk. The dynamic library would be loaded with `dlopen` the first time after decompression.
- Once the binary is decrypted, how would it be stored to disk? Does Apple allow changing the contents of the binary at all? They generally don't like modifying executable data.

**Comment by 42Bastian** [comment]
Just my 2cents: I doubt Apple will allow any change to the binary once signed. So the program needs to be compressed before encrypting it.

**Comment by arm-in** [comment]
Apple Release Notes for iOS 13 say:

https://support.apple.com/en-us/HT210393#13
"Performance
    60 percent smaller app updates on average
    Up to 50 percent smaller apps from the App Store"

Packaging of the files has changed. So this implies some kind of compression and / or binary diff already present.

**Comment by michaeleisel** [comment]
That change is just Apple no longer shooting themself in the foot. They were encrypting the __TEXT segment prior to compression, which came with little security and a high size cost. More here: https://medium.com/@michael.eisel/one-trick-to-drastically-reduce-your-ios-apps-downlsize-ae68aad0d369

**Comment by arm-in** [comment]
Good catch!

**Comment by JuunChen** [comment]
Here are some of the experiments I did:

First one:
1. Create an iOS project from Xcode, and then can run it on simulator
2. Find the executable file in the product, use upx compress it
3. Return to the Xcode, use `ctrl + cmd + r` to run the project again without rebuild
4. Then you can see that it works very well

The second:
Same as above, but on my iPhone X device, not simulator. Xcode prompt "Unable to install"
```
Details

Unable to install "testupx"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
--
No code signature found.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE800801C)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000012652e81a DTDKCreateNSErrorFromAMDErrorCode + 233
	1   DTDeviceKitBase                     0x000000012656ff70 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x000000010c89af35 DVTInvokeWithStrongOwnership + 73
	3   DTDeviceKitBase                     0x000000012656fca8 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1654
	4   IDEiOSSupportCore                   0x00000001263e6e91 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.352 + 4165
	5   DVTFoundation                       0x000000010c9ce5d4 __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x000000010c9d0216 __DVTDispatchAsync_block_invoke + 1194
	7   libdispatch.dylib                   0x00007fff6b6806c4 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff6b681658 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff6b686c44 _dispatch_lane_serial_drain + 597
	10  libdispatch.dylib                   0x00007fff6b6875d6 _dispatch_lane_invoke + 363
	11  libdispatch.dylib                   0x00007fff6b690c09 _dispatch_workloop_worker_thread + 596
	12  libsystem_pthread.dylib             0x00007fff6b8dba3d _pthread_wqthread + 290
	13  libsystem_pthread.dylib             0x00007fff6b8dab77 start_wqthread + 15
);
}
--


System Information

macOS Version 10.15.5 (Build 19F101)
Xcode 11.6 (16141)
```

The third:
I archived the project,  find the executable file in the .xcarchive file, and use upx to compress it.
Then I tried to distribute it, but App refused it, the error is:
```
ERROR ITMS-90700: "Incorrect Platform. You included armv7 executable “Test.app/Test” in your ios bundle. Only ios executables can be included."
ERROR ITMS-90086: "Missing 64-bit support. iOS apps submitted to the App Store must include 64-bit support and be built with the iOS 8 SDK or later. We recommend using the default "Standard Architectures" build setting for "Architectures" in Xcode, to build a single binary with both 32-bit and 64-bit support."
ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS SDK. As of June 30, 2020, all apps for iPhone or iPad must be built with the iOS 13 SDK or later, included with Xcode 11 or later."
ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'Test.app/Test' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
ERROR ITMS-90208: "Invalid Bundle. The bundle Test.app does not support the minimum OS Version specified in the Info.plist."
ERROR ITMS-90700: "Incorrect Platform. You included armv7 executable “Test.app/Test” in your iOS bundle. Only iOS executables can be included."
```
The executable files before and after use upx is here:
[executable.zip](https://github.com/upx/upx/files/5172684/executable.zip)

And this is the comparison:
![image](https://user-images.githubusercontent.com/13558319/92199989-35580280-eeab-11ea-86e4-58e5b7c3d879.png)

**Comment by JuunChen** [comment]
There are some questions here:
1. Compared with experiment 1 and 2, why can it run on the simulator but can't installed on the real machine?
2. As for experiment 3, did UPX process too much information, causing problems in Apple's detection?
3. I want to use UPX to reduce the **Install** Size of my App. Is it possible?

**Comment by michaeleisel** [comment]
for 1., my guess is it's because the simulator has far fewer protections around code signing and integrity

**Comment by michaeleisel** [comment]
for 3, have you tried decompressing a dylib and loading it with dlopen?

**Comment by JuunChen** [comment]
The upx doesn't support dylib on arm 64, so I raised the issue [#404 ](https://github.com/upx/upx/issues/404) .

By the way，I used your [trick way](https://medium.com/@michael.eisel/one-trick-to-drastically-reduce-your-ios-apps-downlsize-ae68aad0d369) and reduced more than 70MB download size on my app, now it works very well in the App store. And I solved the `???` problem in the crash report metioned in the comments on your article, the reason is that there are some problems in Apple's analysis, and can use the atos tool for manual parsing. I also solved a linker error "... out of range ...... +/-12MB " which will be appeared when the executable file is too large. Thank you, @michaeleisel

**Comment by michaeleisel** [comment]
thanks, always glad to hear these things. one thing i'm curious about is, do you still see this app download size difference in ios 13? i've seen indicators that apple compresses it prior to encryption for ios 13+

**Comment by JuunChen** [comment]
This method is not valid for iOS13 or above, and there is no difference in download size. My app supports iOS 10 at least, so it is very helpful for me.

**Comment by michaeleisel** [comment]
excellent, i'm glad to hear it. how'd you solve the `???` problem?

**Comment by JuunChen** [comment]
I dodn't know if it was legal for me to post the company's code information, so I added mosaics.

This is the Binary Images info in the crash.log, I found the 0x100010000 - 0x100203fff is too small, because I know that my executable is very large. So I found this address range only counts the rest of the TEXT segment, but I rename most of it to another segments. So the log is error.
![image](https://user-images.githubusercontent.com/13558319/92202157-f4fb8300-eeb0-11ea-81f9-e7e6ca160572.png)

The left is the crash.log , the right is that I use atos to parse the crash with crash log info and dsym. For more information about ATOS, you can go to Google. So ... use the atos can solve this problem.
![image](https://user-images.githubusercontent.com/13558319/92202850-73a4f000-eeb2-11ea-8709-dbec80866c21.png)

**Comment by michaeleisel** [comment]
nice!
