### ISSUE TITLE
Weird ram usage and laggy experience compared to UPX 3.91 at Windows 32bit PE binary

### ISSUE THREAD

**Issue by Syping** [upx/upx#36]
## What's the problem (or question)?

The application don't use RAM how it should be and have laggy experience.

## What should have happened?

A stable RAM usage and no laggs like upx 3.91.

## Do you have an idea for a solution?

Because i haven't idea how upx works revert/fix the RAM usage like 3.91 i guessing

## How can we reproduce the issue?

Compressing a application with upx --best on Qt Framework 5.6.2 Static Build application (MinGW 4.9.1 Debian i686 target)
I can provide binaries from my project for testing purposes.

## Please tell us details about your environment.

upx 3.92
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Windows 10 Pro 64bit (Build 1607)

**Comment by ml1050** [comment]
I have committed a TLS related bug fix for the devel branch. Can you give it a try?

**Comment by Syping** [comment]
Works totally fine with the build i made from the devel branch.
But: I had used my Debian to compile UPX because i didn't got it done on Windows (idk how to do it with MSVC)

I will build later the upx 3.92 stable on my Debian system just for reproducing the same thing to test if it's not just only in Windows.

**Comment by ml1050** [comment]
Yes, the fix is still only on the devel branch. Thanks for your report.
