### ISSUE TITLE
android arm64 *.so crash after upx compress #2

### ISSUE THREAD

**Issue by Empier** [upx/upx#360]
## What's the problem (or question)?

1. compress native-lib.so use upx 3.9.6 with --android-shlib parameter, compress success. then use the so file which has compressed, crash on android phone
2. I found that the first slot in init_array is not replaced differently than arm32.

<img src="http://vuln.kr/issue/crashafterpack.png" width="40%">
- Crash point after pack - 0x1D14D20
<img src="http://vuln.kr/issue/arm64_pack.png" width="40%">
- init_array first slot - 0x1D14D20
<img src="http://vuln.kr/issue/arm32_pack.png" width="40%">
- On arm32 it is replaced with a different address.

## What should have happened?

[file list]
- http://vuln.kr/issue/libUE4_ori.so - origin file
- http://vuln.kr/issue/libUE4_test2.so  - with argument "--android-shlib" 

- ELF64-arm64 needs to be replaced for the first slot.

<img src="http://vuln.kr/issue/1.png" width="40%">
<img src="http://vuln.kr/issue/2.png" width="40%">

- The value "08 55 39 03" should be located at 0x1498D38.

## Do you have an idea for a solution?

I don't know 으아아아아아악!! 으아아악!!

I think there might be a problem with ELF64 parsing, but no flaws were found in the UPX source code.

## How can we reproduce the issue?

1. Original so file attachment.
2. Both English and programming are lacking, but I have a passion to do it. Would you like to do it together?

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version: android 9.0
* Target CPU architecture: arm64

**Comment by Empier** [comment]
https://github.com/Empier/upx

**Comment by yunshouhu** [comment]
I also encountered the same problem. Upx 3.9.6 has a high probability of crashing on Android 8.1 arm64, including upx-devel。
