### ISSUE TITLE
UPX refuses to accept a rust executable compiled with --release

### ISSUE THREAD

**Issue by BaiqingL** [upx/upx#369]
## What's the problem (or question)?
I am attempting to use UPX to decrease the size of a rust executable compiled with release tag, but UPX returns the error of CantPackException: bad DT_GNU_HASH

## What should have happened?
UPX should've decreased the binary file size

## Do you have an idea for a solution?
An interesting thing is that if I build the project with just cargo build, UPX accepts the binary just fine

## How can we reproduce the issue?
1. Clone my project repository at https://github.com/BaiqingL/aggressive_work_request
2. Run cargo build --release
3. Go into the folder of target/release and locate executable
4. Attempt to put executable through upx

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.96-git-d7ba31cab8ce+
* Host Operating System and version: Arch Linux
* Host CPU architecture: i7-8565U
* Target Operating System and version: N/A
* Target CPU architecture: N/A

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") an actual binary executable that UPX fails to compress.  (Compress the upload with gzip, zip, or .tgz first.) Different versions of Rust are `designed` to produce different results.  You didn't mention the actual version of Rust, and anyway Rust is not part of the standard developer environment.

**Comment by BaiqingL** [comment]
Apologies, here are some more information:
rustc 1.42.0 (b8cedc004 2020-03-09)

Not sure how to properly upload things to github issues so here's a firefox send link containing the binary I built:
https://send.firefox.com/download/04f8ed04cc557744/#j0vNPXrCrj-DW0U80A8DQA

**Comment by jreiser** [comment]
Thank you for the actual executable.  Fixed on `devel` branch.

To upload a file: click on "Attach files by ..." at the bottom of a Comment entry.
Incidentally, on my Fedora 30:
```
$ rustc --version
rustc 1.42.0
```
but my compiled `aggressive_work_request` drew no complaint from previous UPX, even though "rustc 1.42.0" is the same as you report.  This illustrates why it is necessary to present an actual executable when creating an Issue.

**Comment by BaiqingL** [comment]
Understood, thank you!
