### ISSUE TITLE
Android armeabi *.so crash after upx compress

### ISSUE THREAD

**Issue by yunshouhu** [upx/upx#370]
## What's the problem (or question)?

1. compress libhellojni.so use upx devel 3.9.6 with --android-shlib parameter, compress success. then use the so file which has compressed, crash on android phone
2. The command line used is:  
./upx-git-60f19b72e067.out   --android-shlib libs/armeabi/libhellojni.so

## What should have happened?
1. When installing and running the apk it crashed

## Do you have an idea for a solution?

1. [download_upx_files](https://github.com/yunshouhu/myfiles/tree/master/upx_file) According to the crashed tombstone_02 log file and readelf -a libhellojni.so output
2. Memory near sl register at the time of the crash: it is parsing the __atomic_fetch_add symbol.
3. __atomic_fetch_add is IFUNC symbol in the so file, I suspect that the relocation information of IFUNC symbol is not fixed by upx.
![IFUNC](https://raw.githubusercontent.com/yunshouhu/myfiles/master/upx_file/002.jpg)
4. hope you can help me fix this problem, Thank you very much!
5. the crash log show:
```html
04-16 16:37:38.783 28176 28176 F DEBUG   : Build fingerprint: 'vivo/PD1801/PD1801:8.1.0/O11019/1560411816:user/release-keys'
04-16 16:37:38.783 28176 28176 F DEBUG   : Revision: '0'
04-16 16:37:38.783   390   477 I hwcomposer: [DBQ] (q2:0x7c03c69c00) Reallocate Slot(0), pool(0 -> 0) size(0 -> 9849600)  
04-16 16:37:38.783 28176 28176 F DEBUG   : ABI: 'arm'
04-16 16:37:38.783 28176 28176 F DEBUG   : pid: 28156, tid: 28156, name: shouhu.hellojni  >>> com.yunshouhu.hellojni <<<
04-16 16:37:38.783 28176 28176 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xd34e97b4
04-16 16:37:38.783 28176 28176 F DEBUG   :     r0 d34e97b4  r1 0000000a  r2 000487b4  r3 00323378
04-16 16:37:38.783 28176 28176 F DEBUG   :     r4 f5980e10  r5 d34e97b4  r6 0000000b  r7 d34a6e48
04-16 16:37:38.783 28176 28176 F DEBUG   :     r8 00000000  r9 00000016  sl d34a350f  fp 00000007
04-16 16:37:38.783 28176 28176 F DEBUG   :     ip ff000000  sp ff94b088  lr f6fe0b41  pc d34e97b4  cpsr 60070010
04-16 16:37:38.798   390   477 I hwcomposer: [DBQ] (q2:0x7c03c69c00) Reallocate Slot(1), pool(0 -> 0) size(0 -> 9849600)  
04-16 16:37:38.815   390   477 I hwcomposer: [DBQ] (q2:0x7c03c69c00) Reallocate Slot(2), pool(0 -> 0) size(0 -> 9849600)  
04-16 16:37:38.861 28176 28176 F DEBUG   : 
04-16 16:37:38.861 28176 28176 F DEBUG   : backtrace:
04-16 16:37:38.861 28176 28176 F DEBUG   :     #00 pc 000197b4  <anonymous:d34d0000>
04-16 16:37:38.861 28176 28176 F DEBUG   :     #01 pc 00006b3f  /system/bin/linker (__dl__Z19call_ifunc_resolverj+6)
04-16 16:37:38.861 28176 28176 F DEBUG   :     #02 pc 00007b4d  /system/bin/linker (__dl__ZN6soinfo8relocateI20plain_reloc_iteratorEEbRK14VersionTrackerOT_RK10LinkedListIS_19SoinfoListAllocatorESB_+308)
04-16 16:37:38.861 28176 28176 F DEBUG   :     #03 pc 000072af  /system/bin/linker (__dl__ZN6soinfo10link_imageERK10LinkedListIS_19SoinfoListAllocatorES4_PK17android_dlextinfo+586)
04-16 16:37:38.861 28176 28176 F DEBUG   :     #04 pc 0000491f  /system/bin/linker (__dl__Z14find_librariesP19android_namespace_tP6soinfoPKPKcjPS2_PNSt3__16vectorIS2_NS8_9allocatorIS2_EEEEjiPK17android_dlextinfobbRNS8_13unordered_mapIPKS1_9ElfReaderNS8_4hashISJ_EENS8_8equal_toISJ_EENSA_INS8_4pairIKSJ_SK_EEEEEEPNS9_IS0_NSA_IS0_EEEE+2042)
04-16 16:37:38.861 28176 28176 F DEBUG   :     #05 pc 00005c53  /system/bin/linker (__dl__ZL12find_libraryP19android_namespace_tPKciPK17android_dlextinfoP6soinfo+66)
04-16 16:37:38.861 28176 28176 F DEBUG   :     #06 pc 0000593b  /system/bin/linker (__dl__Z9do_dlopenPKciPK17android_dlextinfoPKv+1070)
04-16 16:37:38.861 28176 28176 F DEBUG   :     #07 pc 000033f3  /system/bin/linker (__dl__ZL10dlopen_extPKciPK17android_dlextinfoPKv+38)
04-16 16:37:38.861 28176 28176 F DEBUG   :     #08 pc 00001107  /system/lib/libdl.so (android_dlopen_ext+4)
04-16 16:37:38.861 28176 28176 F DEBUG   :     #09 pc 000023bd  /system/lib/libnativeloader.so (android::OpenNativeLibrary(_JNIEnv*, int, char const*, _jobject*, _jstring*, bool*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)+252)
```

6. I've uploaded more crash information here.[download_upx_files](https://github.com/yunshouhu/myfiles/tree/master/upx_file) Thank you!

## How can we reproduce the issue?

1. [download_upx_files](https://github.com/yunshouhu/myfiles/tree/master/upx_file)
Download the apk and libhellojni.so file and use the latest version of upx to compress the libhellojni.so file
2. Then generate a new libhellojni.so file, replace the lib/armeabi/libhellojni.so file in the apk, and then resign apk
3. install & run the apk

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 4.0.0-git-60f19b72e067 or upx 3.9.6
* Host Operating System and version: 14.04.1-Ubuntu x86_64
* Host CPU architecture: intel x86_64
* Target Operating System and version: Android 8.1 
* Target CPU architecture: armeabi

**Comment by yunshouhu** [comment]
1. I suspect that the cause of this problem is the existence of ifunc type symbols in libhellojni.so.
2. Does upx already support ifunc type symbol compression and relocation? Thank you very much for your reply.
https://sourceware.org/glibc/wiki/GNU_IFUNC

**Comment by 4ntoine** [comment]
I can see on the [WIKI](https://github.com/upx/upx):
> Future: AArch64 (64-bit ARM) for Linux and iOS.

Is it meant to be already working?
@yunshouhu can you provide any details how you packed an executable

PS. is it a duplicate https://github.com/upx/upx/issues/409 ?
