### ISSUE TITLE
coredump: exception throwed by  C++ not catched after UPX the .so file in CentOS7.5

### ISSUE THREAD

**Issue by samueldeng** [upx/upx#372]
## What's the problem (or question)?
exception throwed by  C++ not catched after UPX the DLL.

I have write a simple sample:
https://github.com/samueldeng/upx-coredump-demo
which contains:

-  `exception_func`:  throw exception. 
-   `call_exception_fun.cpp`: call `exception_func` and **try/catch the exception**.
-   compile `exception_func/call_exception_fun.cpp` into a DLL/SO file named `libexception.so`
-   `upx libexception.so`
-  `main.cpp`:  dlopen(`libexception.so`)  and call `call_exception_fun.cpp`'s function.

**In expection:**
`call_exception_fun.cpp` would catch the exception throwed by `call_exception_func.cpp` and return normally.

**However:**
`call_exception_fun.cpp` failed to catch. and this exception throw to `main.cpp`, which cause whole application coredump.
And if donnot upx the `libexception.so`, everything work fine.

## What should have happened?
c++ code catch the exception.

## Do you have an idea for a solution?
No clues.
Furthermore, I found change the compile sequence of line would solve this issue. But it's so wiered.
https://github.com/samueldeng/upx-coredump-demo#more-weird-tips

## How can we reproduce the issue?
I have upload my sample code into my github repo. 
https://github.com/samueldeng/upx-coredump-demo

Furthermore, create a github action to reproduce this issue.
https://github.com/samueldeng/upx-coredump-demo/actions

**coredump line in docker(centos7)**: 
https://github.com/samueldeng/upx-coredump-demo/runs/594821663?check_suite_focus=true#step:8:19

## Please tell us details about your environment.
* UPX version used (`upx --version`): upx 3.9.1, 3.9.6
* Host Operating System and version: centos 7.5
* Host CPU architecture: x86-amd64
* Target Operating System and version: centos 7.5
* Target CPU architecture: centos 7.5

**Comment by samueldeng** [comment]
upx 3.9.1 and upx-3.9.6 is the release version in `release page.`

**Comment by jreiser** [comment]
The layout of the typical shared library produced by recent gcc and binutils has changed significantly from the former layout (say, from 2018.)  For
```
$ gcc --version
gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
$ rpm -qf /usr/bin/ld
binutils-2.31.1-37.fc30.x86_64
```
notice that the shared library initialization subroutine `_init` (designated by [DT_]INIT) is at the beginning of the first executable "segment" ([PT_]LOAD) at address 0x1000 (see output from `readelf` below.) In previous layouts `_init` was near the end of executable code.  It makes a difference because the address range from the beginning of executable code up to the `_init` routine is easier to compress than any other range.  In a shared library, then any non-executable "segment" requires extreme care to compress, because `data` can be both the target of relocation and also the source for R_xxx_COPY relocation.  Relocation processing of an instantiated shared library happens before the UPX de-compressor gains control via intercepting `_init`, so `data` cannot be compressed.
Anyway, compressing the new layout of a shared library will require a significant re-write of the compressor and run-time de-compressor.
```
$ readelf --segments --dynamic libexception.so.orig

Elf file type is DYN (Shared object file)
Entry point 0x1100
There are 9 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000d00 0x0000000000000d00  R      0x1000
  LOAD           0x0000000000001000 0x0000000000001000 0x0000000000001000
                 0x0000000000001df9 0x0000000000001df9  R E    0x1000
  LOAD           0x0000000000003000 0x0000000000003000 0x0000000000003000
                 0x0000000000000514 0x0000000000000514  R      0x1000
  LOAD           0x0000000000003d88 0x0000000000004d88 0x0000000000004d88
                 0x0000000000000300 0x0000000000000308  RW     0x1000
  DYNAMIC        0x0000000000003db8 0x0000000000004db8 0x0000000000004db8
                 0x0000000000000200 0x0000000000000200  RW     0x8
  NOTE           0x0000000000000238 0x0000000000000238 0x0000000000000238
                 0x0000000000000024 0x0000000000000024  R      0x4
  GNU_EH_FRAME   0x000000000000316c 0x000000000000316c 0x000000000000316c
                 0x00000000000000ac 0x00000000000000ac  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x0000000000003d88 0x0000000000004d88 0x0000000000004d88
                 0x0000000000000278 0x0000000000000278  R      0x1

 Section to Segment mapping:
  Segment Sections...
   00     .note.gnu.build-id .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt 
   01     .init .plt .text .fini 
   02     .rodata .eh_frame_hdr .eh_frame .gcc_except_table 
   03     .init_array .fini_array .data.rel.ro .dynamic .got .got.plt .data .bss 
   04     .dynamic 
   05     .note.gnu.build-id 
   06     .eh_frame_hdr 
   07     
   08     .init_array .fini_array .data.rel.ro .dynamic .got 

Dynamic section at offset 0x3db8 contains 28 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libexception.so]
 0x000000000000000c (INIT)               0x1000
 0x000000000000000d (FINI)               0x2dec
 0x0000000000000019 (INIT_ARRAY)         0x4d88
 0x000000000000001b (INIT_ARRAYSZ)       32 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x4da8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x260
 0x0000000000000005 (STRTAB)             0x608
 0x0000000000000006 (SYMTAB)             0x2c0
 0x000000000000000a (STRSZ)              886 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x5000
 0x0000000000000002 (PLTRELSZ)           312 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0xbc8
 0x0000000000000007 (RELA)               0xa48
 0x0000000000000008 (RELASZ)             384 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x9c8
 0x000000006fffffff (VERNEEDNUM)         3
 0x000000006ffffff0 (VERSYM)             0x97e
 0x000000006ffffff9 (RELACOUNT)          6
 0x0000000000000000 (NULL)               0x0
```

**Comment by wintung** [comment]
we met the same problem, does there exist any workaround method to solve it ?

**Comment by jreiser** [comment]
As in my comment about one month ago https://github.com/upx/upx/issues/372#issuecomment-636415383 , the problem is a changed arrangement of the bytes in the shared library.  This requires a changed strategy for compression, and a changed run-time decompressor.
One workaround is to re-link the shared library using the old linker script, such as from some particular previous version of the `binutils` package which contains /usr/bin/ld.  The linker script for the current ld is given by `ld -shared --verbose`.

**Comment by wintung** [comment]
thanks a lots. I changed linker script and rebuild the so, but it did not work. I found another workaround: when compiling so, statically linking to libstdc++.a can solve this problem. I guess when .so running , it can not find c++ abis which catch exceptions.

**Comment by markus-oberhumer** [comment]
This seems fixed, please reopen if you disagree.
