### ISSUE TITLE
UPX does not compress Win32 binary from RAD Studio 10.3

### ISSUE THREAD

**Issue by Rafciq** [upx/upx#375]
## What's the problem (or question)?
I have problem with compressing binary for Win32 produced by RAD Studio 10.3.
Please resolve my problem.

## What should have happened?
When I run UPX in compress mode with binary, it show message "upx: FileName.exe: InternalError: should not happen"

## Do you have an idea for a solution?
I don't have.

## How can we reproduce the issue?

1. In RAD Studio 10.3 create C++ project for Windows 32 platform.
2. Compile nad Build this project.
3. Try to compress by UPX the new binary.

## Please tell us details about your environment.

* UPX version used (3.96w):
* Host Operating System and version: Microsoft Windows [Version 10.0.18363.815]
* Host CPU architecture:Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, 2701 MHz, Cores 2, Logical processors: 4
* Target Operating System and version:
* Target CPU architecture:
![UPX Problem](https://user-images.githubusercontent.com/4492691/80594026-88640980-8a22-11ea-8499-6275bf36dd02.png)

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") an actual binary executable which triggers the InternalError.  Compress the upload with zip, gzip, or .tgz to save space on GitHub.

**Comment by Rafciq** [comment]
Thanks for your response.
Please download binary from https://storage.wapro.pl/storage/InstalatorWAPRO/InstalatorWAPRO.exe and try to compress by UPX,

**Comment by bitraid** [comment]
This is the same as #69, #90, #97, #223, #344.

**Comment by Rafciq** [comment]
Thank you. 
This fix temporarily fixes my problem. Will this fix be added to the next version?

**Comment by jreiser** [comment]
Yes, this fix will be in the next release from `master`.
