### ISSUE TITLE
segfault when compressing deno amd64

### ISSUE THREAD

**Issue by kokizzu** [upx/upx#376]
## What's the problem (or question)?
error running upx'ed deno (when decompressed it works normally)
```
$ upx --version
upx 3.94
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
Copyright (C) 1996-2017 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2017 Laszlo Molnar
Copyright (C) 2000-2017 John F. Reiser
Copyright (C) 2002-2017 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.

$ upx `which deno`
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.94        Markus Oberhumer, Laszlo Molnar & John Reiser   May 12th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  51883864 ->  20067832   38.68%   linux/amd64   deno                          

Packed 1 file.

$ deno
[1]    7791 segmentation fault (core dumped)  deno
```

## What should have happened?
no error

## Do you have an idea for a solution?
no idea

## How can we reproduce the issue?
1. curl -fsSL https://deno.land/x/install/install.sh | sh
2. export DENO_INSTALL="$HOME/.deno"
3. export PATH="$DENO_INSTALL/bin:$PATH"
4. upx `which deno`
5. deno

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.94
* Host Operating System and version: Ubuntu 18.04.3
* Host CPU architecture: amd64
* Target Operating System and version: Ubuntu 18.04.3
* Target CPU architecture: amd64

**Comment by bitraid** [comment]
Works fine with version 3.96
