### ISSUE TITLE
upx 3.92 notepad++ plugins

### ISSUE THREAD

**Issue by humandxp** [upx/upx#38]
## What's the problem (or question)?
notepad++ says problem with loading plugin into memory, illegal operation

## How can we reproduce the issue?
1. just compress for example updated PluginManager.dll with upx 3.92

## Please tell us details about your environment.
notepad 7.2.2 x86
* UPX version used 3.92, 3.91 works:
* Operating System and version: windows 7
* CPU architecture: x64

**Comment by ml1050** [comment]
I've downloaded

https://notepad-plus-plus.org/repository/7.x/7.2.2/npp.7.2.2.bin.x64.7z

but there is no PluginManager.dll in it.

**Comment by Vityacv** [comment]
Maybe this is new upx bug come from 3.92.
Example: dll/exe(ASLR) have base 0x10000000 - when this memory is already taken - reloc table is being used, which lead to crash

**Comment by humandxp** [comment]
i gave all info:)
notepad 7.2.2 x86

    UPX version used 3.92, 3.91 works:
    Operating System and version: windows 7
    CPU architecture: x64

x86 not x64. x64 version still doesnt have 95% plugins

**Comment by ml1050** [comment]
This was a relocation handling regression, introduced in 3.92.
Fixed on the devel branch (commit 67797efeadd24b9df37e6049a518df6e85094144).
Thanks for you report.
