### ISSUE TITLE
upx doesn't follow symlinks

### ISSUE THREAD

**Issue by james-antill** [upx/upx#382]
## What's the problem (or question)?

If you have:

ln -s mybin.bin.darwin-amd64 mybin

...then "upx mybin.bin.darwin-amd64" works but "upx mybin" does not.

## What should have happened?

Same thing in both cases above, compress the mybin.bin.darwin-amd64 file.

## Do you have an idea for a solution?

Resolve the path to the followed symlinks name (man 3 realpath).

## How can we reproduce the issue?

1.cp /usr/bin/vim /tmp
2.ln -s vim /tmp/vim-1
3.upx /tmp/vim-1
4.upx /tmp/vim

## Please tell us details about your environment.

* UPX version used (`upx --version`):
upx 3.96
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
Copyright (C) 1996-2020 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2020 Laszlo Molnar
Copyright (C) 2000-2020 John F. Reiser
Copyright (C) 2002-2020 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
* Host Operating System and version: 18.7.0 Darwin Kernel Version 18.7.0
* Host CPU architecture:x86_64
* Target Operating System and version: 18.7.0 Darwin Kernel Version 18.7.0
* Target CPU architecture:x86_64

**Comment by jreiser** [comment]
This is not a bug, it's the way that symbolic links work in \*nix.  The proper implementation would be that a symlink is followed unless you ask explicitly for it not to be followed, and following the symlink would be built-in to the operating system everywhere that a pathname is processed, except if a flag argument chose the option "do not follow symlink".  Unfortunately, \*nix does not work this way.  stat\*() of a symlink (with no altering flag argument, such as an `input` value in statbuf.st_mode) gets you the info about the symlink, not the info about the ultimate file that is the transitive closure of any links.

**Comment by james-antill** [comment]
> The proper implementation would be that a symlink is followed unless you ask explicitly for it not to be followed

Yes, that's how it works.

> Unfortunately, *nix does not work this way. stat*() of a symlink (with no altering flag argument, such as an input value in statbuf.st_mode) gets you the info about the symlink

This is not true. That is why there is an fstat() call.

**Comment by jreiser** [comment]
```
$ rm -f foo bar  # start with a clean state
$ cp /bin/date bar  # some initial contents
$ ln -s bar foo  # with a symlink that refers to the initial contents
$ ls -l foo bar  # show the symlink configuration
-rwxr-xr-x. 1 user group 176296 Jun  2 19:37 bar
lrwxrwxrwx. 1 user group      3 Jun  2 19:37 foo -> bar
$ date >foo.new  # new contents for an updated version of foo
$ mv foo.new foo  # the recommended procedure to create a new version with the same name
$ ls -l foo bar
-rwxr-xr-x. 1 user group 176296 Jun  2 19:37 bar
-rw-rw-r--. 1 user group     32 Jun  2 19:37 foo  # symlink was not preserved
$ 
```
The shell session above illustrates how the `rename()` system call (the heart of `mv`) does not "always follow symlinks unless explicitly asked not to".  The new version `foo.new` does not replace the target of the symlink `foo` (namely, `bar`) but instead replaces the symlink name `foo` itself.    The operating system does not follow symlinks in the target of `rename`.  A user-mode program which tries to follow symlinks is not so trivial to write: `PATH_MAX` and `..` (parent directory) cause trouble, and it is impossible to avoid races (time-of-check versus time-of-use).  Also, the concept of "realname" [sometimes pretended as the result of `readlink`] gets murky whenever there are multiple links (either hard or soft) to one or more of the directories in the path.  It is bettertto insist on `S_IFREG` in the first place, in order to force the user to deal with such issues.

**Comment by james-antill** [comment]
Yes, rename() doesn't follow symlinks ... it can't because symlinks can cross devices and rename() does not.

> A user-mode program which tries to follow symlinks is not so trivial to write

True, that's why realpath(3) exists.

> Also, the concept of "realname" [sometimes pretended as the result of readlink] gets murky

No, realname/resolved-name/whatever is the result of realpath(3). readlink() just reads the symbolic link at destination, realpath(3) "returns the canonicalized absolute pathname"

If, for some reason, you need just the final part of the path resolved it becomes more difficult. Although, even then, in 2020 there are implementations you can easily look at:

https://github.com/vim/vim/blob/ca70c07b72c24aae3d141e67d08f50361f051af5/src/memline.c#L4285


> It is better to insist on S_IFREG in the first place, in order to force the user to deal with such issues

It's certainly not better.
