### ISSUE TITLE
upx-3.96-win64 failed, but upx-3.95-win64 works

### ISSUE THREAD

**Issue by kousyougi** [upx/upx#383]
## What's the problem (or question)?

C:\upx-3.96-win64>upx -k --best --lzma naive
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96w       Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name

upx: naive: CantPackException: bad DT_HASH nbucket=0x2d9  len=0x1134

Packed 0 files.

## What should have happened?

I can run the new "naive" compressed by UPX 3.95w.

C:\upx-3.95-win64>upx -k --best --lzma naive
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95w       Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name

   8706136 ->   2008984   23.08%  linux/mipsel   naive

Packed 1 file.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
upx-3.96-win64
* Host Operating System and version:
Win 10 64bit
* Host CPU architecture:
Intel Core i3-4010U
* Target Operating System and version:
Openwrt 19.07.03 
* Target CPU architecture:
MediaTek MT7620A

Original file:
https://github.com/klzgrad/naiveproxy/releases/download/v83.0.4103.61-1/naiveproxy-v83.0.4103.61-1-openwrt-mipsel_24kc.tar.xz

**Comment by jreiser** [comment]
Thank you for submitting the test case.  Fixed on `devel` branch by above commit.
