### ISSUE TITLE
where is the file UPX.DOC

### ISSUE THREAD

**Issue by kingjie0210** [upx/upx#384]
in the README file ,it says:"Please see the file UPX.DOC for the full documentation. The files
NEWS and BUGS also contain various tidbits of information." I want to know where the UPX.DOC fie is?  I want to konw the description of UPX, for example:How to complie and How to use.  If anyone knows please tell me,Thanks very much!

**Comment by jreiser** [comment]
```
$ cd upx; git ls-files | grep -i doc
doc/Makefile
doc/elf-to-mem.txt
doc/filter.txt
doc/loader.txt
doc/selinux.txt
doc/upx.pod
$ git branch
* devel
$ ls -k src/Makefile
-rw-rw-r--. 1 user group 6081 Jun 13 15:09 src/Makefile
$ 

```
