### ISSUE TITLE
Information inquiry on b_info struct

### ISSUE THREAD

**Issue by albertzsigovits** [upx/upx#389]
## What's the problem (or question)?
This is more like an inquiry, asking for information about structs (b_info, l_info, p_info.)

Trying to understand structures from linux.h:
https://github.com/upx/upx/blob/d7ba31cab8ce8d95d2c10e88d2ec787ac52005ef/src/stub/src/include/linux.h

```
struct b_info {     // 12-byte header before each compressed block
    uint32_t sz_unc;            // uncompressed_size
    uint32_t sz_cpr;            // compressed_size
    unsigned char b_method;     // compression algorithm
    unsigned char b_ftid;       // filter id
    unsigned char b_cto8;       // filter parameter
    unsigned char b_unused;
};

struct l_info       // 12-byte trailer in header for loader (offset 116)
{
    uint32_t l_checksum;
    uint32_t l_magic;
    uint16_t l_lsize;
    uint8_t  l_version;
    uint8_t  l_format;
};

struct p_info       // 12-byte packed program header follows stub loader
{
    uint32_t p_progid;
    uint32_t p_filesize;
    uint32_t p_blocksize;
};
```

Now in the following example, I can see the trailer_info and the program_info:

```
00000000: 7f45 4c46 0101 0161 0000 0000 0000 0000  .ELF...a........
00000010: 0200 2800 0100 0000 8819 0100 3400 0000  ..(.........4...
00000020: 0000 0000 0202 0000 3400 2000 0300 2800  ........4. ...(.
00000030: 0000 0000 0100 0000 0000 0000 0080 0000  ................
00000040: 0080 0000 37ab 0000 37ab 0000 0500 0000  ....7...7.......
00000050: 0080 0000 0100 0000 585e 0000 58de 0200  ........X^..X...
00000060: 58de 0200 0000 0000 0000 0000 0600 0000  X...............
00000070: 0080 0000 51e5 7464 0000 0000 0000 0000  ....Q.td........
00000080: 0000 0000 0000 0000 0000 0000 0700 0000  ................
```
00000090: 0400 0000 **f3da 0088** **5550 5821** **c811 0d17**  ........UPX!....
000000a0: **0000 0000** **04c5 0100** **04c5 0100** 9400 0000  ................
```
000000b0: 6000 0000 0200 0000 7f3f 64f9 7f45 4c46  `........?d..ELF
000000c0: 0100 0200 0300 0d64 8104 df6d b3dd 0834  .......d...m...4
000000d0: 07c8 b017 0b20 1928 000a 0009 d77e 6db2  ..... .(.....~m.
000000e0: 002d 8023 03a0 ac0a 037d 7fb3 df05 1310  .-.#.....}......
000000f0: 001f 3730 0508 0388 b01f 6cdb 0aa0 0603  ..70......l.....
00000100: 061f 51e5 7464 0000 0000 f705 1f04 0302  ..Q.td..........
00000110: 0000 0000 0000 40ff 0cac 0000 f851 0000  ......@......Q..
00000120: 0249 0000 ee6b bffc 5589 e553 e800 1881  .I...k..U..S....
00000130: c377 af06 0a78 04bf 0bd8 ffa3 885b 5dc3  .w...x.......[].
00000140: 8b1c 24c3 9000 2b83 ec08 803d a0ff bbfb  ..$...+....=....
00000150: ff30 0508 0074 0ceb 3583 c004 a324 0cff  .0...t..5....$..
00000160: d2a1 068b 1085 d275 ebff f6ed bbb8 4200  .......u......B.
00000170: 85c0 7410 2b0c 68a0 2c16 e804 7ffb f783  ..t.+.h.,.......
00000180: c462 dfdb ef10 c605 3801 c953 8db4 2624  .b......8..S..&$
00000190: 552a fdb1 ffc5 5477 885a 81c2 f4ae 3b15  U*....Tw.Z....;.
000001a0: 526a 0068 a49d 3bf2 cc2d 40c3 7ea1 1011  Rj.h..;..-@.~...
000001b0: 1d16 d7fd ce61 620d 14ff d01e c9ac fdef  .....ab.........
000001c0: feff 31ed 5e89 e183 e4f0 5054 5268 4624  ..1.^.....PTRhF$
000001d0: 4094 8004 0851 5668 20ce 04ff b797 fd64  @....QVh ......d
000001e0: 9a07 f4cf 5653 3f04 8a44 2418 8b5c 2414  ....VS?..D$..\$.
000001f0: 88ee f6dd 6d07 030b 1025 ff93 c65d 7e23  ....m....%...]~#
00000200: 0ecd fdff ff03 3a43 0474 228d 5308 31c9  ......:C.t".S.1.
00000210: eb0e 8a42 0489 d383 c208 3a17 7b6d 17be  ...B......:.{m..
00000220: fd41 39f1 75ed 8b0a 1c5a 5b5e 2a1b 8943  .A9.u....Z[^*..C
00000230: 1cff ef12 860d 2f57 630c 8a5d 0c0f b67d  ....../Wc..]...}
00000240: 10f6 eeef 6e03 7518 837b 2983 f8ff 7404  ....n.u..{)...t.
00000250: 610e 8d65 f42e cb64 efc2 5f69 8db6 d11b  a..e...d.._i....
...
```

l_info, l_checksum: `f3da 0088`
l_info, l_magic: `5550 5821`
l_info, l_size: `c811`
l_info, l_version: `0d`
l_info, l_format: `17`

p_info, p_progid: `0000 0000`
p_info, p_filesize: `04c5 0100`
p_info, p_blocksize: `04c5 0100`

Where would I find the **b_info** struct in an UPX packed binary?
Would you be so kind as to point out the exact HEX location for **b_info** for me as I was not able to find it for many days now.

`struct b_info {     // 12-byte header before each compressed block`
It mentions before each compressed block? What do you mean by block?
Tried to reverse engineer from a binary by trying to figure out the value for cto8, and b_method, but can't see those in my UPX (3.95) packed binaries so far. 

## Please tell us details about your environment.
* UPX version used (`upx --version`):
```
upx 3.95
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
```

* Host Operating System and version: Ubuntu 20.04 LTS
* Host CPU architecture: x86_64
* Target Operating System and version: Ubuntu 20.04 LTS
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
For ELF files, the offset of the first `struct b_info` for the compressed program is given in
``` 
       .long O_BINFO  // offset of b_info for .text
```
of src/stub/src/\<arch\>-linux.elf-entry.S.  There is also a b_info for the compressed part of the loader itself, which is located soon after the instruction `call unfold` near the label `main:`, reached from `_start` which is `ElfXX_Ehdr.e_entry`.  Soon before _start there is a 4-byte aligned 4-byte field which is equal to its offset, called `sz_pack2`.

**Comment by albertzsigovits** [comment]
For anyone looking to re-produce or want to get the exact offsets and values, get into `unfold`, and go down to the 3 lodsd instructions, then:

```
> px @ 0x7f7fef0fc4a0
- offset -       0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x7f7fef0fc4a0  6f63 2f73 656c 662f 6578 6500 0001 0000  oc/self/exe.....
0x7f7fef0fc4b0  b307 0000 3906 0000 0249 0800 ffff ffe5  ....9....I......
```
sz_unc: `b307 0000`
sz_cpr: `3906 0000`
b_method: `02`
b_ftid: `49`
b_cto8: `08`
b_unused: `00`

**Comment by albertzsigovits** [comment]
Thanks, got my answer!

**Comment by jreiser** [comment]
> For anyone looking to re-produce or want to get the exact offsets and values, get into `unfold`, and go down to the 3 lodsd instructions, then:

Note that those are the b_info for the compressed portion of the stub loader itself (the compiled code of *.elf-main.c is stored compressed, saving (0x07b3 - 0x0639) bytes), and do not describe any portion of the target executable that was specified on the command line to UPX.  The offset (file position) of the first b_info for the target program is stored in that `.long O_BINFO`.

**Comment by albertzsigovits** [comment]
Would the `b_info` for the target program also have the same _b_ parameters_ as the stub loader's?
I'm assuming yes.

```
b_method: 02
b_ftid: 49
b_cto8: 08
b_unused: 00
```

**Comment by jreiser** [comment]
Currently the b_method and (if non-zero) the b_ftid must be the same for all b_info in a given file, because these correspond to the code for the de-compressor and the un-filter.  But in a while they could be different, because it will be possible to have more than one piece of code for each. The intent is to allow for different parameters for each PT_LOAD, because .text and .data often have very different characteristics.

**Comment by jreiser** [comment]
See also `upx --fileinfo foo`:
```
foo [amd64-linux.elf, linux/amd64]
     52224 bytes, compressed by UPX 13, method 2, level 8, filter 0x49/0x08
```

**Comment by albertzsigovits** [comment]
Thank you, did not know about this argument!
