### ISSUE TITLE
The executable generated by UPX, executes the error: "The parameter is incorrect."

### ISSUE THREAD

**Issue by DorianB2017** [upx/upx#398]
With an executable kit created with the new WinRAR ver. 5.91 - Default.SFX/Default64.SFX, after compressing the executable with upx ver. 3.96, ie `upx.exe -9 namefile.exe`, the executable resulting from the compression, when it is executed, appears the message **"The parameter is incorrect."**

![image](https://user-images.githubusercontent.com/30018486/88654837-96cfc900-d0d6-11ea-8642-4557355de40d.png)

* UPX version used (`upx --version`): 3.96 - 32/64-bit
* Host Operating System and version: Windows 10 (10.0.19041.388/10.2004)
* Host CPU architecture: Intel i5
* Target Operating System and version: Windows 10
* Target CPU architecture: Intel/AMD

Plese fix this bug.
Thank you

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") or provide the URL to an actual executable file which triggers the problem.  Compress the upload using zip, gzip, or .tgz to save space.

**Comment by bitraid** [comment]
That's because of [Control Flow Guard (CFG)](https://docs.microsoft.com/en-us/windows/win32/secbp/control-flow-guard). Same as #154, #203, #250
@jreiser, are you interested in a pull request that disables the compression of such images?

**Comment by jreiser** [comment]
_are you interested in a pull request_   &nbsp;&nbsp;Let's see the content, please.

**Comment by jreiser** [comment]
Fixed on `devel` branch by merge noted above https://github.com/upx/upx/pull/399
