### ISSUE TITLE
UPX dll unnecessary DLL_PROCESS_ATTACH check can lead to crash

### ISSUE THREAD

**Issue by Vityacv** [upx/upx#40]
## What's the problem (or question)?

UPX dll unnecessary DLL_PROCESS_ATTACH check can lead to crash

## What should have happened?

Possible crash of dll should not happen

## Do you have an idea for a solution?

Remove unnecessary check of DLL_PROCESS_ATTACH

## How can we reproduce the issue?

10003720 | 80 7C 24 08 01    | cmp byte ptr ss:[esp+8],1  <- upx dll entry
10003725 | 0F 85 55 01 00 00 | jne test32.10003880  <- if this is not DLL_PROCESS_ATTACH - jmp
...
10003880 | E9 7B D7 FF FF    | jmp test32.10001000  <- here jump to uninitialized dll entry = crash
same in x64
## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.91, 3.92
* Operating System and version: Windows 10
* CPU architecture: amd64

**Comment by ml1050** [comment]
This check is there to prevent multiple decompression of the compressed data. Do you say that you have a DLL which is not called with DLL_PROCESS_ATTACH when windows loads it?

**Comment by Vityacv** [comment]
Oops. Correct. Forgot additional DllMain calls when attach fail on dll code.

hm maybe will be better rewrite that:
`00007FFE965037xx | 48 89 4C 24 08    | mov qword ptr ss:[rsp+8],rcx <- upx entry
00007FFE965037xx | 48 89 54 24 10    | mov qword ptr ss:[rsp+10],rdx
00007FFE965037xx | 4C 89 44 24 18    | mov qword ptr ss:[rsp+18],r8
00007FFE965037xx | 80 FA 01          | cmp dl,1
00007FFE965037xx | 0F 85 F0 01 00 00 | jne cpl console trainer 64.7FFE965039B8
...
00007FFE965039B8 | 4C 8B 44 24 18    | mov r8,qword ptr ss:[rsp+18]
00007FFE965039xx | 48 8B 54 24 10    | mov rdx,qword ptr ss:[rsp+10]
00007FFE965039xx | 48 8B 4C 24 08    | mov rcx,qword ptr ss:[rsp+8]
00007FFE965039xx | E9 34 D6 FF FF    | jmp cpl console trainer 64.7FFE96501000 <- dll entry

to:
00007FFE965037xx | 80 FA 01          | cmp dl,1 <- upx entry
00007FFE965037xx | 0F 85 F0 01 00 00 | jne test 64.7FFE96501000 <- dll entry
00007FFE965037xx | 48 89 4C 24 08    | mov qword ptr ss:[rsp+8],rcx 
00007FFE965037xx | 48 89 54 24 10    | mov qword ptr ss:[rsp+10],rdx
00007FFE965037xx | 4C 89 44 24 18    | mov qword ptr ss:[rsp+18],r8
...
00007FFE965039xx | 4C 8B 44 24 18    | mov r8,qword ptr ss:[rsp+18]
00007FFE965039xx | 48 8B 54 24 10    | mov rdx,qword ptr ss:[rsp+10]
00007FFE965039xx | 48 8B 4C 24 08    | mov rcx,qword ptr ss:[rsp+8]
00007FFE965039xx | E9 34 D6 FF FF    | jmp cpl console trainer 64.7FFE96501000 <- dll entry`

**Comment by Vityacv** [comment]
There something else i want to ask. Why we need this code?
```
// clear the dirty stack
.macro          clearstack128  tmp_reg
                .local   loop
                lea     \tmp_reg, [rsp - 128]
loop:
                push    0
                cmp     rsp, \tmp_reg
                jnz     loop
                sub     rsp, -128
.endm

```

**Comment by ml1050** [comment]
I can not see how your code rearrangement would prevent a crash. Have you actually seen a crash in that code?

About you second question. It's just clears a part of the stack. I guess Markus added that code to hide traces of the decompression process from the uncompressed code. I'm not sure this stuff is really necessary, but it's harmless.

**Comment by Vityacv** [comment]
Maybe:
cmp dword[original_entry],0
jnz init
cmpb    [esp + 8], 1
jnz     original_entry
init:

[original_entry] - always zero

**Comment by ml1050** [comment]
Have you actually seen a crash in a compressed DLL?

**Comment by Vityacv** [comment]
When dll support reinitialization in her dllmain, and call second time dllmain (upx entry) - crash

**Comment by ml1050** [comment]
Can this really happen? Trying to attach to a DLL again, when it failed to initialize for the first time? I have seen no bug reports this till now. 

If you can attach a test case with the crash, then I will come with a fix.

**Comment by Vityacv** [comment]
I meant if you manually call DllMain upx will decompress it again and in case dll is not a hello world this will cause crash

**Comment by ml1050** [comment]
You're right, that manually calling DllMain twice would cause a crash, but I can not really imagine a reason why would anyone do this. The problem could be fixed, but I'm not sure it would worth the effort. Let this issue be an "enhancement".
