### ISSUE TITLE
Where is the packed file stored?

### ISSUE THREAD

**Issue by ayashgupta** [upx/upx#400]
## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
The output from UPX overwrites the input file, unless the command-line option `-o _filename_` is given.

**Comment by ayashgupta** [comment]
Thanks!
