### ISSUE TITLE
UPX 3.96 crashes on nexus 5x (android 8.1 arm64 ) 

### ISSUE THREAD

**Issue by hacku7** [upx/upx#406]
## What's the problem (or question)?

1、compress so file use upx 3.9.6 success (no use --android-shlib parameter). then use the so file which has compressed, crash on android 7+ amd64，android arm32 is fine.
2、how can i do when compress so file exception ->CantPackException: bad init address 0 in Elf32_Shdr[14].0x7e40

## What should have happened?

[file list]
https://github.com/high0go/high_0go/blob/master/libdemo.so   -------  orgin file
https://github.com/high0go/high_0go/blob/master/libdemo_packed.so  -------  compressed file
## Do you have an idea for a solution?

I don't know
 
## How can we reproduce the issue?

nexus 5x load libdemo_packed.so 

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.9.6
* Host Operating System and version: 
* Host CPU architecture:
* Target Operating System and version: android 8.1
* Target CPU architecture:   arm64

**Comment by yunshouhu** [comment]
I also encountered the same problem， Android 8.1 arm64
