### ISSUE TITLE
How to debug with Clion (idea)? 

### ISSUE THREAD

**Issue by gshmu** [upx/upx#408]
is there some doc?

**Comment by jreiser** [comment]
Please give some context.  What are you trying to do, specifically?  The compression side of UPX is an "ordinary" C++ user-mode app that runs on Linux, Windows, and Mac; the src/Makefile applies.  The de-compression side (the UPX de-compression stub) is a "bare native assembly language" app for each target architecture, and it is constructed at run time of the compression side.  For instance: edit src/stub/src/amd64-linux.elf-entry.S beginning at the label `_start`, then re-build in src/stub, then rebuild in src, then compress, then apply gdb.

**Comment by gshmu** [comment]
@jreiser I want build and debug with CLion.
but not find any doc talk about this.

**Comment by jreiser** [comment]
Can you be more specific?  Which part of UPX do you want to debug (the compressor, the decompressor, ...), on which development platform (Linux, WIndows, Mac, ...), for applications that target which OS (32-bit or 64-bit; Linux, Windows, Mac, Atari, ...)?
See src/Makefile, stub/Makefile, README.SRC (particularly ucl, lzma, upx-stubtools).  Perhaps CLion cannot handle apps that are as complex as UPX.

**Comment by gshmu** [comment]
thanks,  i found the `README.SRC`.
I'm tried on Mac 10.15.6, the 'string.h' is missing, and I try on Windows.

I want build the debugger 32-bit upx, and then debug decompress some file.exe @jreiser

**Comment by jreiser** [comment]
In a little while you may find some of these details interesting: https://github.com/upx/upx/issues/328
