### ISSUE TITLE
Android 8.1 arm64-v8a so dlopen crash by UPX 3.9.6

### ISSUE THREAD

**Issue by yunshouhu** [upx/upx#409]
## What's the problem (or question)?
1、compress so file use upx 3.9.6 success (use --android-shlib parameter). then use the so file which has compressed, crash on android 8.1 amd64，android arm32 is fine.

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):  3.9.6 and upx-devel
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version: Android8.1 
* Target CPU architecture: arm64

**Comment by yunshouhu** [comment]
error log：
`Softversion: PD1635_A_8.20.7
Time: 2020-10-22 11:00:08
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'vivo/PD1635/PD1635:8.1.0/OPM1.171019.019/compil09011027:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 14953, tid: 14953, name: nshouhu.testjni  >>> com.yunshouhu.testjni <<<
signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x7638102964
    x0   00000076380f4250  x1   000000000000e714  x2   000000759d2aa250  x3   0000007fe13bd4e0
    x4   0000007638102964  x5   0000000000000000  x6   000000759d2aa000  x7   75792e6d6f632f70
    x8   00000000000000de  x9   000000763c5253d0  x10  000000763c5253d8  x11  0000000000000000
    x12  0000000000000000  x13  000000763c413000  x14  000000763c40f000  x15  000000763c40f000
    x16  0000000000000000  x17  000000763c433ef4  x18  0000000000000020  x19  000000763996d450
    x20  000000759d2b9f58  x21  000000763c40f710  x22  000000763996d5f0  x23  000000763c525000
    x24  000000763bdf7010  x25  0000007fe13be5f8  x26  0000000000000000  x27  00000075b6c27000
    x28  00000075aa6abac0  x29  0000007fe13bd5a0  x30  0000007638102bbc
    sp   0000007fe13bd470  pc   0000007638102964  pstate 0000000060000000
    v0   00000000000000000000000000000000  v1   625f5f0061746164655f006f732e6362
    v2   735f7373625f5f0074726174735f7373  v3   00000002000000000000080000000000
    v4   00000000000000020000000000000000  v5   00000000000000000000000000000000
    v6   00000000000000000000000000000000  v7   80200802802008028020080280200802
    v8   00000000000000000000000000000000  v9   00000000000000000000000000000000
    v10  00000000000000000000000000000000  v11  00000000000000000000000000000000
    v12  00000000000000000000000000000000  v13  00000000000000000000000000000000
    v14  00000000000000000000000000000000  v15  00000000000000000000000000000000
    v16  40100401401004014010040140100401  v17  00000002000000000002000002000800
    v18  00000000000000020000000000000000  v19  000000000000000000000000ebad8083
    v20  0000000000000000d87f1dcc36378afb  v21  000000000000000029b935270f46069f
    v22  0000000000000000c3556fef1b2a7223  v23  00000000000000009d79a806b4c09d21
    v24  000000000000000000000000ebad8088  v25  000000000000000000000000ebad8089
    v26  000000000000000000000000ebad808a  v27  000000000000000000000000ebad808b
    v28  000000000000000000000000ebad808c  v29  000000000000000000000000ebad808d
    v30  000000000000000000000000ebad808e  v31  0000000000000000000000001669ffe8
    fpsr 00000013  fpcr 00000000

backtrace:
    #00 pc 000000000000e964  <anonymous:00000076380f4000>
    #01 pc 000000000000ebb8  <anonymous:00000076380f4000>

stack:
         0000007fe13bd3f0  000000763996d450  [anon:linker_alloc]
         0000007fe13bd3f8  000000763c5252b0
         0000007fe13bd400  000000763c5252f8
         0000007fe13bd408  000000763c4417a8  /system/bin/linker64 (__dl__ZN15CFIShadowWriter9AfterLoadEP6soinfoS1_+40)
         0000007fe13bd410  000000763c122510  [anon:linker_alloc_small_objects]
         0000007fe13bd418  0000000000000001
         0000007fe13bd420  0000007fe13bd5a0
         0000007fe13bd428  000000763c435e3c  /system/bin/linker64 (__dl__Z14find_librariesP19android_namespace_tP6soinfoPKPKcmPS2_PNSt3__16vectorIS2_NS8_9allocatorIS2_EEEEmiPK17android_dlextinfobbRNS8_13unordered_mapIPKS1_9ElfReaderNS8_4hashISJ_EENS8_8equal_toISJ_EENSA_INS8_4pairIKSJ_SK_EEEEEEPNS9_IS0_NSA_IS0_EEEE+3404)
         0000007fe13bd430  0000007fe13bd5f8
         0000007fe13bd438  0000007fe13bd5f8
         0000007fe13bd440  0000000001000000
         0000007fe13bd448  000000763c40f710  [anon:linker_alloc_small_objects]
         0000007fe13bd450  000000763c590b10
         0000007fe13bd458  000000763c590b98
         0000007fe13bd460  0000007fe13bd4b0
         0000007fe13bd468  000000763c4c9aa0  /system/bin/linker64 (__dl__ZL12should_tracev+332)
    #00  0000007fe13bd470  0000000000000006
         ........  ........
    #01  0000007fe13bd470  0000000000000006
         0000007fe13bd478  0000007fe13c3fb8
         0000007fe13bd480  0000007fe13c3ff0
         0000007fe13bd488  000000759d2ab528
         0000007fe13bd490  fffffffffffff000
         0000007fe13bd498  000000763c44bd0c  /system/bin/linker64 (__dl__ZN6soinfo17call_constructorsEv+532)
         0000007fe13bd4a0  000000759d2cd50c
         0000007fe13bd4a8  00000076380f4000
         0000007fe13bd4b0  000000000000ec48
         0000007fe13bd4b8  000000759d2aa000
         0000007fe13bd4c0  000000000002450c
         0000007fe13bd4c8  0000007638102b34
         0000007fe13bd4d0  0000000000000094
         0000007fe13bd4d8  000000759d2aa250
         0000007fe13bd4e0  00000000000242bc
         0000007fe13bd4e8  0000000000000000
`

**Comment by yunshouhu** [comment]
`memory near x30:
    0000007638102b88 52801bc8aa0003e6 eb06001fd4000001  .......R........
    0000007638102b98 d420000054000040 f9401fe1b94063e5  @..T.. ..c@...@.
    0000007638102ba8 f94047e49400001d a94a8fe2a94987e0  .....G@...I...J.
    0000007638102bb8 94000004d63f0080 a8cc07e0d4000001  ..?.............
    0000007638102bc8 f9401be4d61f0060 f9000080a94007c0  `.....@...@.....
    0000007638102bd8 f9402fe4b9000881 a94687e0a9478fe2  ...../@...G...F.
    0000007638102be8 d63f0080b4000043 d28000a2a94487e0  C.....?...D.....
    0000007638102bf8 d400000152801c48 a94387e0a94293fe  H..R......B...C.
    0000007638102c08 a9410fe252801ae8 b85fc025d61f0080  ...R..A.....%._.
    0000007638102c18 3600008512005ca5 510004a5b8404423  .\.....6#D@....Q
    0000007638102c28 340000a5b8004403 510008a528c10c22  .D.....4"..(...Q
    0000007638102c38 35ffffa528810c02 f9005ffed65f03c0  ...(...5.._.._..
    0000007638102c48 0000000000000000 0000000000000000  ................
    0000007638102c58 0000000000000000 0000000000000000  ................
    0000007638102c68 0000000000000000 0000000000000000  ................
    0000007638102c78 0000000000000000 0000000000000000  ................

code around pc:
    0000007638102c20 510004a5b8404423 340000a5b8004403  #D@....Q.D.....4
    0000007638102c30 510008a528c10c22 35ffffa528810c02  "..(...Q...(...5
    0000007638102c40 f9005ffed65f03c0 0000000000000000  .._.._..........
    0000007638102c50 0000000000000000 0000000000000000  ................
    0000007638102c60 0000000000000000 0000000000000000  ................
    0000007638102c70 0000000000000000 0000000000000000  ................
    0000007638102c80 0000000000000000 0000000000000000  ................
    0000007638102c90 0000000000000000 0000000000000000  ................
    0000007638102ca0 0000000000000000 0000000000000000  ................
    0000007638102cb0 0000000000000000 0000000000000000  ................
    0000007638102cc0 0000000000000000 0000000000000000  ................
    0000007638102cd0 0000000000000000 0000000000000000  ................
    0000007638102ce0 0000000000000000 0000000000000000  ................
    0000007638102cf0 0000000000000000 0000000000000000  ................
    0000007638102d00 0000000000000000 0000000000000000  ................
    0000007638102d10 0000000000000000 0000000000000000  ................

code around sp:
    0000007fe13bd450 000000763c590b10 000000763c590b98  ..Y<v.....Y<v...
    0000007fe13bd460 0000007fe13bd4b0 000000763c4c9aa0  ..;.......L<v...
    0000007fe13bd470 0000000000000006 0000007fe13c3fb8  .........?<.....
    0000007fe13bd480 0000007fe13c3ff0 000000759d2aa528  .?<.....(.*.u...
    0000007fe13bd490 fffffffffffff000 000000763c44bd0c  ..........D<v...
    0000007fe13bd4a0 000000759d2cc50c 00000076380f4000  ..,.u....@.8v...
    0000007fe13bd4b0 000000000000ec48 000000759d2a9000  H.........*.u...
    0000007fe13bd4c0 000000000002450c 0000007638102b34  .E......4+.8v...
    0000007fe13bd4d0 0000000000000094 000000759d2a9250  ........P.*.u...
    0000007fe13bd4e0 00000000000242bc 0000000000000000  .B..............
    0000007fe13bd4f0 0000000000000052 0000007638102964  R.......d).8v...
    0000007fe13bd500 0000000000005202 00000076380f4250  .R......PB.8v...
    0000007fe13bd510 000000000000e714 000000759d2a9250  ........P.*.u...
    0000007fe13bd520 0000007fe13bd4e0 0000007638102b74  ..;.....t+.8v...
    0000007fe13bd530 000000759d2a43db 0000000000000000  .C*.u...........
    0000007fe13bd540 0000000000000000 0000000000000000  ................
`

**Comment by yunshouhu** [comment]
crash address:
C0 03 5F D6
FE 5F 00 F9
=> arm64 instructions
ret 
str x30, [sp, #0xb8]

**Comment by yunshouhu** [comment]
1. The test problem machine found that the app directly clicked to start and loaded the so after compression by upx, which crashed directly.
But the app started successfully in debug mode.

adb shell am start -D -n com.yunshouhu.testjni/com.yunshouhu.testjni.MainActivity
jdb -connect "com.sun.jdi.SocketAttach:hostname=127.0.0.1,port=8700"

2. What could be the reason for this situation? Is it possible that a system call failed? Or is it a memory permission mechanism?

**Comment by yunshouhu** [comment]
The so crashed on some systems such as PD1635_A_8.20.7, and it can run normally on other systems.

**Comment by 4ntoine** [comment]
I can see on the WIKI:
> Future: AArch64 (64-bit ARM) for Linux and iOS.
Is it meant to be already working?

**Comment by Ficing** [comment]
@yunshouhu this problem has solved? I met the same problem, could you give some help?

**Comment by SlientOutBurst** [comment]
@yunshouhu this problem has solved? I met the same problem, could you give some help?
