### ISSUE TITLE
Cannot build with cmake.

### ISSUE THREAD

**Issue by AraHaan** [upx/upx#41]
## What's the problem (or question)?

cmake cannot be used when it is only make installed on Windows.

## What should have happened?

built using cmake.

## Do you have an idea for a solution?

Add option to be able to use cmake.

## How can we reproduce the issue?

1. Download.
2. Extract.
3. Create a build script that has ``cmake -C Makefile``
4. This Error shows:

```cmd
loading initial cache file Makefile
CMake Error: Error in cmake code at
./Makefile:7:
Parse error.  Expected "(", got unquoted argument with text "+=".
CMake Error: Error processing file: Makefile
CMake Error: The source directory "./Makefile" is a file, not a directory.
Specify --help for usage, or press the help button on the CMake GUI.
Press any key to continue . . .
```

## Please tell us details about your environment.

* UPX version used (`upx --version`): latest
* Operating System and version: Windows 7 (SP1) x64 Ultimate Build 7601
* CPU architecture: amd64

**Comment by markus-oberhumer** [comment]
UPX uses GNU make as build system, not cmake.
