### ISSUE TITLE
CantPackException: PT_NOTE 0xa71cc above stub

### ISSUE THREAD

**Issue by esmailzadeh1** [upx/upx#410]
## What's the problem (or question)?
upx can't compress file build by Golang with -buildmode=c-shared 

## What should have happened?
I wrote a simple Golang file. is as follows:
`package main
func main() {
}`
Then build it :
`go build -buildmode=c-shared -o library.so main.go`

Then `upx library.so` and got this error:

`upx: library.so: CantPackException: PT_NOTE 0xa71cc above stub`

## Do you have an idea for a solution?
I Don't know how to fix.

## How can we reproduce the issue?
1.
2.
3.
4.

## Please tell us details about your environment.
* UPX version 3.96
* Host Operating System and version: CentOS 7 64bit
* Host CPU architecture: arm64
* Target Operating System and version: 
* Target CPU architecture:

**Comment by jreiser** [comment]
The file `library.so' does not have the correct format to allow compression.
```
$ readelf --segments library.so

Elf file type is DYN (Shared object file)
Entry point 0x42210
There are 11 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000041e88 0x0000000000041e88  R      0x1000
  LOAD           0x0000000000042000 0x0000000000042000 0x0000000000042000
                 0x0000000000050545 0x0000000000050545  R E    0x1000
  LOAD           0x0000000000093000 0x0000000000093000 0x0000000000093000
                 0x000000000000e96c 0x000000000000e96c  R      0x1000
  LOAD           0x00000000000a1ac8 0x00000000000a2ac8 0x00000000000a2ac8
                 0x0000000000072000 0x000000000008fbb0  RW     0x1000
  DYNAMIC        0x0000000000110db8 0x0000000000111db8 0x0000000000111db8
                 0x0000000000000200 0x0000000000000200  RW     0x8
  NOTE           0x00000000000002a8 0x00000000000002a8 0x00000000000002a8
                 0x0000000000000024 0x0000000000000024  R      0x4
  NOTE           0x00000000000a1908 0x00000000000a1908 0x00000000000a1908
                 0x0000000000000064 0x0000000000000064  R      0x4
  TLS            0x00000000000a1ac8 0x00000000000a2ac8 0x00000000000a2ac8
                 0x0000000000000000 0x0000000000000008  R      0x8
  GNU_EH_FRAME   0x00000000000a1530 0x00000000000a1530 0x00000000000a1530
                 0x00000000000000ac 0x00000000000000ac  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x00000000000a1ac8 0x00000000000a2ac8 0x00000000000a2ac8
                 0x000000000006f538 0x000000000006f538  R      0x1

 Section to Segment mapping:
  Segment Sections...
   00     .note.gnu.build-id .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt 
   01     .init .plt .text .fini 
   02     .rodata .eh_frame_hdr .eh_frame .note.go.buildid 
   03     .init_array .fini_array .data.rel.ro .dynamic .got .got.plt .data .noptrdata .bss .noptrbss 
   04     .dynamic 
   05     .note.gnu.build-id 
   06     .note.go.buildid 
   07     .tbss 
   08     .eh_frame_hdr 
   09     
   10     .init_array .fini_array .data.rel.ro .dynamic .got 
$ 
```
The second [PT_]NOTE is at address 0x00000000000a1908 which interferes with compression.  Instead, the NOTE should be adjacent to the other NOTE at 0x00000000000002a8.  Golang must fix it.

**Comment by jreiser** [comment]
Probably the 2 NOTEs are generated at different points in the build process.  Here's one way (a "hack") to make them adjacent.
When the first NOTE is generated, then make it larger by adding an additional 0x64 bytes of "blank" note: either allocated but totally-unused space, or an actual note with a type and title something like "this is a placeholder for the second NOTE".  Proceed through the rest of the build process, adding the second NOTE.  Then copy the contents of the second NOTE into the reserved space of the first NOTE, and change the .p_type of the second PT_NOTE to become PT_NULL, thus turning the second PT_NOTE into a "comment".  The space cost is 0x64 bytes, the size of the second NOTE.

**Comment by mengzhuo** [comment]
I can't reproduce this bug.
What did I missed?
```
go version go1.15.3 linux/amd64
UPX 3.91
```

**Comment by jreiser** [comment]
go version go1.12.17 linux/amd64
upx 4.0.0-git-14992260c60b+
[library.so.gz](https://github.com/upx/upx/files/5465193/library.so.gz)

**Comment by jreiser** [comment]
go version go1.14.10 linux/amd64 works.  There is only onte [PT_}NOTE segment, of length 0x88 at offset 0x270:
```
$ readelf --segments library.so

Elf file type is DYN (Shared object file)
Entry point 0x3f210
There are 10 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x000000000003e6d0 0x000000000003e6d0  R      0x1000
  LOAD           0x000000000003f000 0x000000000003f000 0x000000000003f000
                 0x0000000000059415 0x0000000000059415  R E    0x1000
  LOAD           0x0000000000099000 0x0000000000099000 0x0000000000099000
                 0x0000000000011608 0x0000000000011608  R      0x1000
  LOAD           0x00000000000ab4c8 0x00000000000ac4c8 0x00000000000ac4c8
                 0x00000000000671b8 0x0000000000092fc0  RW     0x1000
  DYNAMIC        0x000000000010edd0 0x000000000010fdd0 0x000000000010fdd0
                 0x0000000000000200 0x0000000000000200  RW     0x8
  NOTE           0x0000000000000270 0x0000000000000270 0x0000000000000270
                 0x0000000000000088 0x0000000000000088  R      0x4
  TLS            0x00000000000ab4c8 0x00000000000ac4c8 0x00000000000ac4c8
                 0x0000000000000000 0x0000000000000008  R      0x8
  GNU_EH_FRAME   0x00000000000aa220 0x00000000000aa220 0x00000000000aa220
                 0x00000000000000ac 0x00000000000000ac  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x00000000000ab4c8 0x00000000000ac4c8 0x00000000000ac4c8
                 0x0000000000063b38 0x0000000000063b38  R      0x1

 Section to Segment mapping:
  Segment Sections...
   00     .note.gnu.build-id .note.go.buildid .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt 
   01     .init .plt .text .fini 
   02     .rodata .eh_frame_hdr .eh_frame 
   03     .init_array .fini_array .data.rel.ro .dynamic .got .got.plt .data .go.buildinfo .noptrdata .bss .noptrbss 
   04     .dynamic 
   05     .note.gnu.build-id .note.go.buildid 
   06     .tbss 
   07     .eh_frame_hdr 
   08     
   09     .init_array .fini_array .data.rel.ro .dynamic .got 
$ ../upx.out -f -o foo library.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX git-149922+ Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 24th 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
library.so  6/8  [***********************************************]   93.5%  \   
1493584 ->   1210020   81.01%   linux/amd64   foo

```

**Comment by MaskRay** [comment]
On my machine there is no `.note.gnu.build-id` (`ld --build-id=` produces the section) and `.note.go.buildid` appears in the start of the section header table, hence no problem.

There can be multiple PT_NOTE segments due to different alignments (4 or 8; if `.note.gnu.property` exists, its alignment is 8 on ELFCLASS64; see https://github.com/llvm/llvm-project/blob/master/lld/test/ELF/note-alignment.s) upx needs to work with multiple PT_NOTE segments.

**Comment by jreiser** [comment]
UPX does handle multiple PT_NOTE segments, but for a shared library they must all appear below the first PF_X segment.  The run-time linker is allowed to examine PT_NOTEs (this is a bad idea, but legal), and for a shared-library then UPX de-compression happens after all linker processing (DT_*REL, etc) so PT_NOTEs cannot be compressed.

**Comment by mengzhuo** [comment]
> go version go1.14.10 linux/amd64 works. There is only onte [PT_}NOTE segment, of length 0x88 at offset 0x270:
> 
> ```
> $ readelf --segments library.so
> 
> Elf file type is DYN (Shared object file)
> Entry point 0x3f210
> There are 10 program headers, starting at offset 64
> 
> Program Headers:
>   Type           Offset             VirtAddr           PhysAddr
>                  FileSiz            MemSiz              Flags  Align
>   LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
>                  0x000000000003e6d0 0x000000000003e6d0  R      0x1000
>   LOAD           0x000000000003f000 0x000000000003f000 0x000000000003f000
>                  0x0000000000059415 0x0000000000059415  R E    0x1000
>   LOAD           0x0000000000099000 0x0000000000099000 0x0000000000099000
>                  0x0000000000011608 0x0000000000011608  R      0x1000
>   LOAD           0x00000000000ab4c8 0x00000000000ac4c8 0x00000000000ac4c8
>                  0x00000000000671b8 0x0000000000092fc0  RW     0x1000
>   DYNAMIC        0x000000000010edd0 0x000000000010fdd0 0x000000000010fdd0
>                  0x0000000000000200 0x0000000000000200  RW     0x8
>   NOTE           0x0000000000000270 0x0000000000000270 0x0000000000000270
>                  0x0000000000000088 0x0000000000000088  R      0x4
>   TLS            0x00000000000ab4c8 0x00000000000ac4c8 0x00000000000ac4c8
>                  0x0000000000000000 0x0000000000000008  R      0x8
>   GNU_EH_FRAME   0x00000000000aa220 0x00000000000aa220 0x00000000000aa220
>                  0x00000000000000ac 0x00000000000000ac  R      0x4
>   GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
>                  0x0000000000000000 0x0000000000000000  RW     0x10
>   GNU_RELRO      0x00000000000ab4c8 0x00000000000ac4c8 0x00000000000ac4c8
>                  0x0000000000063b38 0x0000000000063b38  R      0x1
> 
>  Section to Segment mapping:
>   Segment Sections...
>    00     .note.gnu.build-id .note.go.buildid .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt 
>    01     .init .plt .text .fini 
>    02     .rodata .eh_frame_hdr .eh_frame 
>    03     .init_array .fini_array .data.rel.ro .dynamic .got .got.plt .data .go.buildinfo .noptrdata .bss .noptrbss 
>    04     .dynamic 
>    05     .note.gnu.build-id .note.go.buildid 
>    06     .tbss 
>    07     .eh_frame_hdr 
>    08     
>    09     .init_array .fini_array .data.rel.ro .dynamic .got 
> $ ../upx.out -f -o foo library.so
>                        Ultimate Packer for eXecutables
>                           Copyright (C) 1996 - 2020
> UPX git-149922+ Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 24th 2020
> 
>         File size         Ratio      Format      Name
>    --------------------   ------   -----------   -----------
> library.so  6/8  [***********************************************]   93.5%  \   
> 1493584 ->   1210020   81.01%   linux/amd64   foo
> ```

No, you have setup a c-shard mode to trigger this issue.
```
go build -buildmode=c-shared -o library.so main.go
```

I found that it's gcc default link script causing this issue and  Ian thinks this is a upx bug.
https://go-review.googlesource.com/c/go/+/265957
But Go team trying to work around it.

**Comment by jreiser** [comment]
@mengzhuo  In the original Description near the top of this Issue, the 4th line of "What should have happened" says that the build recipe is:
```
go build -buildmode=c-shared  -o library.so main.go
```
which is what I used.  `go version go1.12.17 linux/amd64` from Fedora 28 reproduced the problem using that build recipe.  `go version go1.14.10 linux/amd64` from Fedora 32 did NOT reproduce the problem using that recipe.

I just re-verified that go1.14.10 from Fedora 32 generates only one PT_NOTE (length=0x88, offset=0x270).
Regardless of which software build step generates which PT_NOTES, UPX can compress a shared library only if all the PT_NOTES have an .p_offset and .p_vaddr which is less than the .p_offset and .p_vaddr of the DT_*INIT.d_ptr.  So if GoLang wants to allow for UPX compression of library.so, then each PT_NOTE must have a "low" address.  If nothing else, then GoLang can arrange for this to happen by following the hint that I gave in https://github.com/upx/upx/issues/410#issuecomment-717663201 .

**Comment by mengzhuo** [comment]
Go calling gcc for external link mode.

I'm thinking it's Fedora 32 using newer version of ld which resolved this issue.
Could you provide full `ld --verbose` for me?
```
ld --version
GNU ld (GNU Binutils for Debian) 2.28

ld --verbose

SECTIONS
{
  /* Read-only sections, merged into text segment: */
  PROVIDE (__executable_start = SEGMENT_START("text-segment", 0x400000)); . = SEGMENT_START("text-segment", 0x400000) + SIZEOF_HEADERS;
  .interp         : { *(.interp) }
  .note.gnu.build-id : { *(.note.gnu.build-id) }
  .hash           : { *(.hash) }
  .gnu.hash       : { *(.gnu.hash) }
  .dynsym         : { *(.dynsym) }
  .dynstr         : { *(.dynstr) }
  .gnu.version    : { *(.gnu.version) }
  .gnu.version_d  : { *(.gnu.version_d) }
  .gnu.version_r  : { *(.gnu.version_r) }
  .rela.dyn       :
....
```

**Comment by jreiser** [comment]
[ld-shared-verbose.txt](https://github.com/upx/upx/files/5472721/ld-shared-verbose.txt)
[ld-verbose.txt](https://github.com/upx/upx/files/5472722/ld-verbose.txt)
The linker script depends on "all" the other flags, not just on -verbose.

**Comment by mengzhuo** [comment]
OK
I've found the root cause of this "bug", it's binutils/ld that should groups note sections.
Anyone who try to build Go in c-shared mode below binutils 2.32 will failed to compress the elf output.

https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=1887ae7304dced5b081ee200a9e27fbb8f180143

@esmailzadeh1 Please update your ld (binutils) version to 2.32.

**Comment by MaskRay** [comment]
I am not sure it is fair to say "not grouping SHT_NOTE sections" is a GNU ld bug. It has no obligation to do that. The internal linker script does not have an output section description for `.note.go.buildid`, so `.note.go.buildid` is an orphan. There is not necessarily a rule to place `.note.go.buildid` at a particular place. If the Go toolchain does not manipulate the linked image by itself, it could provide its own linker script - if it knows other .note.* always exist, it can use `SECTIONS { .note.go.buildid : { *(.note.go.buildid) }} INSERT BEFORE .note.something` (see also https://sourceware.org/bugzilla/show_bug.cgi?id=26404)

**Comment by esmailzadeh1** [comment]
> OK
> I've found the root cause of this "bug", it's binutils/ld that should groups note sections.
> Anyone who try to build Go in c-shared mode below binutils 2.32 will failed to compress the elf output.
> 
> https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=1887ae7304dced5b081ee200a9e27fbb8f180143
> 
> @esmailzadeh1 Please update your ld (binutils) version to 2.32.

Hello,

ld --version
GNU ld (GNU Binutils for Ubuntu) 2.34

but still give this error:

upx.out: socket1.so: CantPackException: PT_NOTE 0xaec54 above stub

Thanks!

**Comment by jreiser** [comment]
@esmailzadeh1  Please run `readelf --segments socket1.so` then copy+paste the output here, similar to https://github.com/upx/upx/issues/410#issuecomment-720192325.

**Comment by esmailzadeh1** [comment]
> @esmailzadeh1 Please run `readelf --segments socket1.so` then copy+paste the output here, similar to [#410 (comment)](https://github.com/upx/upx/issues/410#issuecomment-720192325).

`
Elf file type is DYN (Shared object file)
Entry point 0x361c0
There are 9 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000000aecb8 0x00000000000aecb8  R E    0x200000
  LOAD           0x00000000000aef80 0x00000000002aef80 0x00000000002aef80
                 0x000000000005c860 0x000000000008ecc8  RW     0x200000
  DYNAMIC        0x0000000000106dc0 0x0000000000306dc0 0x0000000000306dc0
                 0x0000000000000200 0x0000000000000200  RW     0x8
  NOTE           0x0000000000000238 0x0000000000000238 0x0000000000000238
                 0x0000000000000024 0x0000000000000024  R      0x4
  NOTE           0x00000000000aec54 0x00000000000aec54 0x00000000000aec54
                 0x0000000000000064 0x0000000000000064  R      0x4
  TLS            0x00000000000aef80 0x00000000002aef80 0x00000000002aef80
                 0x0000000000000000 0x0000000000000008  R      0x8
  GNU_EH_FRAME   0x00000000000ae870 0x00000000000ae870 0x00000000000ae870
                 0x00000000000000a4 0x00000000000000a4  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x00000000000aef80 0x00000000002aef80 0x00000000002aef80
                 0x0000000000058080 0x0000000000058080  R      0x1

 Section to Segment mapping:
  Segment Sections...
   00     .note.gnu.build-id .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .text .fini .rodata .eh_frame_hdr .eh_frame .note.go.buildid 
   01     .init_array .fini_array .jcr .data.rel.ro .dynamic .got .got.plt .data .go.buildinfo .noptrdata .bss .noptrbss 
   02     .dynamic 
   03     .note.gnu.build-id 
   04     .note.go.buildid 
   05     .tbss 
   06     .eh_frame_hdr 
   07     
   08     .init_array .fini_array .jcr .data.rel.ro .dynamic .got 
`

**Comment by esmailzadeh1** [comment]
`
Elf file type is DYN (Shared object file)
Entry point 0x361c0
There are 9 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000000aecb8 0x00000000000aecb8  R E    0x200000
  LOAD           0x00000000000aef80 0x00000000002aef80 0x00000000002aef80
                 0x000000000005c860 0x000000000008ecc8  RW     0x200000
  DYNAMIC        0x0000000000106dc0 0x0000000000306dc0 0x0000000000306dc0
                 0x0000000000000200 0x0000000000000200  RW     0x8
  NOTE           0x0000000000000238 0x0000000000000238 0x0000000000000238
                 0x0000000000000024 0x0000000000000024  R      0x4
  NOTE           0x00000000000aec54 0x00000000000aec54 0x00000000000aec54
                 0x0000000000000064 0x0000000000000064  R      0x4
  TLS            0x00000000000aef80 0x00000000002aef80 0x00000000002aef80
                 0x0000000000000000 0x0000000000000008  R      0x8
  GNU_EH_FRAME   0x00000000000ae870 0x00000000000ae870 0x00000000000ae870
                 0x00000000000000a4 0x00000000000000a4  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x00000000000aef80 0x00000000002aef80 0x00000000002aef80
                 0x0000000000058080 0x0000000000058080  R      0x1

 Section to Segment mapping:
  Segment Sections...
   00     .note.gnu.build-id .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .text .fini .rodata .eh_frame_hdr .eh_frame .note.go.buildid 
   01     .init_array .fini_array .jcr .data.rel.ro .dynamic .got .got.plt .data .go.buildinfo .noptrdata .bss .noptrbss 
   02     .dynamic 
   03     .note.gnu.build-id 
   04     .note.go.buildid 
   05     .tbss 
   06     .eh_frame_hdr 
   07     
   08     .init_array .fini_array .jcr .data.rel.ro .dynamic .got 
`

**Comment by jreiser** [comment]
I see two problems.  First, the different spelling of `build-id` and `buildid`:
```
03 .note.gnu.build-id
04 .note.go.buildid
```
and second, the separation into different Segments of ` .note.gnu.build-id` and `.note.go.buildid`.

The first problem (different spelling) is a bug in `go`; you should file a bug against `go`.
The second problem (separation) is a bug in the linker specification, which should group together all Sections`.note.*.build*id`  You should file a bug against binutils.  Meanwhile, it should be possible for you to workaround the second problem by editing the linker script, then re-linking socket1.so.  Capture the output from `ld --verbose <_other flag arguments to ld_>`, edit so that the linker aggregates together all `.note.*.build*id` sections, and re-run `ld -T <_filename of modified script_> <_other arguments_>`.

**Comment by esmailzadeh1** [comment]
> I see two problems. First, the different spelling of `build-id` and `buildid`:
> 
> ```
> 03 .note.gnu.build-id
> 04 .note.go.buildid
> ```
> 
> and second, the separation into different Segments of ` .note.gnu.build-id` and `.note.go.buildid`.
> 
> The first problem (different spelling) is a bug in `go`; you should file a bug against `go`.
> The second problem (separation) is a bug in the linker specification, which should group together all Sections`.note.*.build*id` You should file a bug against binutils. Meanwhile, it should be possible for you to workaround the second problem by editing the linker script, then re-linking socket1.so. Capture the output from `ld --verbose <_other flag arguments to ld_>`, edit so that the linker aggregates together all `.note.*.build*id` sections, and re-run `ld -T <_filename of modified script_> <_other arguments_>`.

Hello,

I set build-id=none in ldflags and it's solved 

segments:

`readelf: Error: Reading 1984 bytes extends past end of file for section headers

Elf file type is DYN (Shared object file)
Entry point 0x4a220
There are 10 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000049230 0x0000000000049230  R      0x1000
  LOAD           0x000000000004a000 0x000000000004a000 0x000000000004a000
                 0x00000000000218dd 0x00000000000218dd  R E    0x1000
  LOAD           0x000000000006c000 0x00000000000a1000 0x00000000000a1000
                 0x0000000000010858 0x0000000000010858  R      0x1000
  LOAD           0x000000000006c4c8 0x00000000000b34c8 0x00000000000b34c8
                 0x0000000000079220 0x0000000000096f00  RW     0x1000
  DYNAMIC        0x00000000000e1dc0 0x0000000000128dc0 0x0000000000128dc0
                 0x0000000000000200 0x0000000000000200  RW     0x8
  NOTE           0x0000000000000270 0x0000000000000270 0x0000000000000270
                 0x0000000000000024 0x0000000000000024  R      0x4
  TLS            0x000000000006c4c8 0x00000000000b34c8 0x00000000000b34c8
                 0x0000000000000000 0x0000000000000008  R      0x8
  GNU_EH_FRAME   0x000000000006b448 0x00000000000b1448 0x00000000000b1448
                 0x00000000000000b4 0x00000000000000b4  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x000000000006c4c8 0x00000000000b34c8 0x00000000000b34c8
                 0x0000000000075b38 0x0000000000075b38  R      0x1
`

`                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
socket1.so  6/8  [***********************************************]   28.8%  /    1228784 ->    939788   76.48%   linux/amd64   socket1.so

Packed 1 file.
`


**Now I have another problem , after compress completed I can't use the library file and shows "Segmentation fault (core dumped)"**


Also the file can't revert and decompress and show this error:

`                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx96: socket1.so: CantUnpackException: ElfXX_Ehdr corrupted

Unpacked 1 file: 0 ok, 1 error.
`

I tired with latest devel version and it's show another error:

`                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX 4.0.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx.out: socket1.so: EOFException: premature end of file                       

Packed 1 file: 0 ok, 1 error.
`


Thanks!

**Comment by esmailzadeh1** [comment]
> I see two problems. First, the different spelling of `build-id` and `buildid`:
> 
> ```
> 03 .note.gnu.build-id
> 04 .note.go.buildid
> ```
> 
> and second, the separation into different Segments of ` .note.gnu.build-id` and `.note.go.buildid`.
> 
> The first problem (different spelling) is a bug in `go`; you should file a bug against `go`.
> The second problem (separation) is a bug in the linker specification, which should group together all Sections`.note.*.build*id` You should file a bug against binutils. Meanwhile, it should be possible for you to workaround the second problem by editing the linker script, then re-linking socket1.so. Capture the output from `ld --verbose <_other flag arguments to ld_>`, edit so that the linker aggregates together all `.note.*.build*id` sections, and re-run `ld -T <_filename of modified script_> <_other arguments_>`.

Hello,

I set build-id=none in ldflags and it's solved 

segments:
```
readelf: Error: Reading 1984 bytes extends past end of file for section headers

Elf file type is DYN (Shared object file)
Entry point 0x4a220
There are 10 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000049230 0x0000000000049230  R      0x1000
  LOAD           0x000000000004a000 0x000000000004a000 0x000000000004a000
                 0x00000000000218dd 0x00000000000218dd  R E    0x1000
  LOAD           0x000000000006c000 0x00000000000a1000 0x00000000000a1000
                 0x0000000000010858 0x0000000000010858  R      0x1000
  LOAD           0x000000000006c4c8 0x00000000000b34c8 0x00000000000b34c8
                 0x0000000000079220 0x0000000000096f00  RW     0x1000
  DYNAMIC        0x00000000000e1dc0 0x0000000000128dc0 0x0000000000128dc0
                 0x0000000000000200 0x0000000000000200  RW     0x8
  NOTE           0x0000000000000270 0x0000000000000270 0x0000000000000270
                 0x0000000000000024 0x0000000000000024  R      0x4
  TLS            0x000000000006c4c8 0x00000000000b34c8 0x00000000000b34c8
                 0x0000000000000000 0x0000000000000008  R      0x8
  GNU_EH_FRAME   0x000000000006b448 0x00000000000b1448 0x00000000000b1448
                 0x00000000000000b4 0x00000000000000b4  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x000000000006c4c8 0x00000000000b34c8 0x00000000000b34c8
                 0x0000000000075b38 0x0000000000075b38  R      0x1

```
```
Ultimate Packer for eXecutables
 Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

File size         Ratio      Format      Name
 --------------------   ------   -----------   -----------
socket1.so  6/8  [***********************************************]   28.8%  /    1228784 ->    939788   76.48%   linux/amd64   socket1.so

Packed 1 file.
```

**Now I have another problem , after compress completed I can't use the library file and shows "Segmentation fault (core dumped)"**


Also the file can't revert and decompress and show this error:
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx96: socket1.so: CantUnpackException: ElfXX_Ehdr corrupted

Unpacked 1 file: 0 ok, 1 error.

```
I tired with latest devel version and it's show another error:
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX 4.0.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx.out: socket1.so: EOFException: premature end of file                       

Packed 1 file: 0 ok, 1 error.
```

Thanks!

**Comment by mengzhuo** [comment]
FYI I’ve submitted fix in Go https://go-review.googlesource.com/c/go/+/265957

**Comment by esmailzadeh1** [comment]
> FYI I’ve submitted fix in Go https://go-review.googlesource.com/c/go/+/265957

Hello,

Thank you, Now I can compress with disable build-id but give Segmentation fault.

**Comment by mengzhuo** [comment]
> > FYI I’ve submitted fix in Go https://go-review.googlesource.com/c/go/+/265957
> 
> Hello,
> 
> Thank you, Now I can compress with disable build-id but give Segmentation fault.

Cl 265957 has been submitted, can you try Go tip (1.18) ?

**Comment by Dennis-Zhang-SH** [comment]
> > > FYI I’ve submitted fix in Go https://go-review.googlesource.com/c/go/+/265957
> > 
> > 
> > Hello,
> > Thank you, Now I can compress with disable build-id but give Segmentation fault.
> 
> Cl 265957 has been submitted, can you try Go tip (1.18) ?

Hi I am encounting this issue on go plugin system with go version 1.18, did this commit fix go plugin?

**Comment by jreiser** [comment]
@Dennis-Zhang-SH I'm unclear about what you mean by ` did this commit fix go plugin?`.  Please try upx-4.0.2, or even the latest successful build under the Actions choice in the GitHub menu bar.  If there still is a problem, then please give a current reproducible test case, including all the version info.

**Comment by Dennis-Zhang-SH** [comment]
> @Dennis-Zhang-SH I'm unclear about what you mean by ` did this commit fix go plugin?`. Please try upx-4.0.2, or even the latest successful build under the Actions choice in the GitHub menu bar. If there still is a problem, then please give a current reproducible test case, including all the version info.

Sorry, I was replying to @mengzhuo in this issue, and I manage to fix this problem by golang build flags, it's my fault.
