### ISSUE TITLE
Bad image , error 0xc000007b after compression / CantPackException: size of Load Configuration directory unexpected

### ISSUE THREAD

**Issue by pingogeek** [upx/upx#412]
## What's the problem (or question)?
Relevant issue with Virtualbox installation compression https://github.com/upx/upx/issues/411

## What should have happened?
App should start

## Do you have an idea for a solution?
-

## How can we reproduce the issue?
1. Install Virtualbox 
2. Compress qt5corevbox.dll
3. Run virtualbox.exe
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): Lastest Appveyor Autobuild , 3.93
* Host Operating System and version: Windows 10 2004
* Host CPU architecture: x64
* Target Operating System and version: Windows 10 2004
* Target CPU architecture: x64

**Comment by jreiser** [comment]
The tip of `devel` branch does not get `CantPackException` for this .dll:
```
$ ls -l
total 5592
-rw-r--r--. 1 user group 5724888 Oct 16 17:31 Qt5CoreVBox.dll
$ sha256sum Qt5CoreVBox.dll
54d8aff2a065b634a9add6e274eb7e83b54a3aedc43e1cfdd4d9862b97345246  Qt5CoreVBox.dll
$ ../upx.out -f -o Qt5CVB-upx.dll Qt5CoreVBox.dll
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX git-149922+ Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 24th 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   5724888 ->   2805976   49.01%    win64/pe      Qt5CVB-upx.dll                   
```
UPX version 3.93 ("Please tell us details about your environment") is old.  Please use a recent tip of `devel` branch, such as the build on https://github.com/upx/upx-automatic-builds/tree/devel-20200906-107cd48-appveyor/amd64-win64-msvc-14.1-release .  You may encounter a problem related to https://github.com/upx/upx/issues/411, but that is separate from CantPackException.
