### ISSUE TITLE
No published aarch64 alpine package

### ISSUE THREAD

**Issue by davidsbond** [upx/upx#419]
## What's the problem (or question)?

I cannot install upx via `apk` when doing so on an arm device, like a Raspberry Pi. Looking at the list of packages:

https://pkgs.alpinelinux.org/packages?name=upx&branch=edge

The `aarch64` package does not exist.

So when I run `apk add upx`, I get:

```                                                                                                                                                      
0.218 fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/aarch64/APKINDEX.tar.gz                                                                                                                                                   
0.503 fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/aarch64/APKINDEX.tar.gz
1.037 ERROR: unsatisfiable constraints:
1.099   upx (missing):
1.099     required by: world[upx]
```

## What should have happened?

The package should've been installed

## Do you have an idea for a solution?

Publish the aarch64 package for alpine

## How can we reproduce the issue?

1. Use an alpine based docker image on arm64 architecture, you can do this using `docker buildx`
2. Try to install upx via `apk add upx`
3. See that it fails

**Comment by jreiser** [comment]
UPX Team does not prepare installation packages for any operating system.  There is only one file to install, namely the UPX compressor+decompressor executable file.  Put it where executable application files may be found.  If your operating system needs more than that, then you must supply whatever your operating system requires.

**Comment by davidsbond** [comment]
@jreiser Thanks for the reply, that makes sense. I'll just have to install manually or see if I can ask the maintainer of that package to put the `aarch64` version up there too.

**Comment by sdavids** [comment]
https://github.com/upx/upx/issues/441
