### ISSUE TITLE
C# program cannot load c++ dll packed with upx 3.96 (vs 2019)

### ISSUE THREAD

**Issue by shp10** [upx/upx#422]
## What's the problem (or question)?

I am developing using visual studio professional 2019 (16.8.0).
My software is made in c# language. The software loads the c++ dll.
After packing c++ dll using upx 3.96, loading it in c# software does not run.
By the way, when the packed c++ dll is loaded in c++ software, it runs normally.

## Do you have an idea for a solution?

When I packed c++ dll built with visual studio 2005 to upx 3.96 version, it worked normally with c# program. 
So, I think there is a problem with Visual studio 2019 compatibility

## How can we reproduce the issue?

1. Create a program in C#
2. Packing c++ dll with upx 3.96 ex) upx.exe test.dll
3. Loading the c++ library in a c# program
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):  3.96
* Host Operating System and version:  windows 7 pro
* Host CPU architecture: x64
* Target Operating System and version: windows 7 pro
* Target CPU architecture: x64

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") or give the downloadable URL for an actual C# binary and actual C++ library that fails.  Compress uploads using zip or gzip so that Github will accept them.

**Comment by jreiser** [comment]
Also, please try the tip of the `devel` branch. There have been a handful of fixes that affect PE files.

**Comment by jsm174** [comment]
Hello. I had something similar while compressing an x86 dll that gets registered as a COM object.

- If the compressed x86 dll was initialized from a VBS script it would fail to load.
ex:`Set obj = CreateObject("VPinMAME.Controller")`

- If I initialized it in C++ using `CoCreateInstance`, it would run fine.

- The compressed x64 versions all ran without issues.

It took me a few days to realize it was a upx issue.  

After reading this issue, I found a `devel` build here:

https://github.com/upx/upx-automatic-builds/tree/devel-20201206-830b242-appveyor/amd64-win64-msvc-14.1-release

And now the x86 dll works fine!

Any chance for an official release?

**Comment by jsm174** [comment]
One more observation.. The build from 20201206 (latest I could find), unfortunately the decompressor would fail. 

I forked the repo, and updated the github action to leave an artifact for head. 

That version was able to compress and decompress successfully.

So if we couldn't get an official release or pre-release any time soon, would it be possible to add some artifacts to the CI?

**Comment by jreiser** [comment]
@jsm174  What artifact was remembered?  Please display (or point to) your modifications.

**Comment by jsm174** [comment]
@jreiser - nothing crazy, just added an upload artifact at the end of the workflow:

https://github.com/jsm174/upx/blob/ci-add-artifact/.github/workflows/ci.yml#L101-L110

Just enough so I could download a copy.

![Screen Shot 2021-03-07 at 10 11 39 AM](https://user-images.githubusercontent.com/1197137/110244609-8b2a6780-7f2d-11eb-888c-6617b5f8b68b.png)

**Comment by jsm174** [comment]
@jreiser - created a PR for this: https://github.com/upx/upx/pull/470
