### ISSUE TITLE
UPX compressed application fails to start on latest macOS release: Big Sur 11.01

### ISSUE THREAD

**Issue by w-A-L-L-e** [upx/upx#424]
## What's the problem (or question)?
MacOS Big Sur doesn't open compressed application executables anymore and gives an error on compressed binary with upx v 3.95 and 3.96.
We have an installer dmg with inside it executables compressed with upx. On Mojave everything was working fine.
Right now however we get a permission error when opening the same application on Big Sur (and it's not fixable by actually setting any different permission flags). We solved it by not using upx anymore on our distributed binaries.

## What should have happened?
The application should just work on Big Sur as it did on Mojave

## Do you have an idea for a solution?
We have no clue why this is happening. We just know that not using upx solved it for us.

## How can we reproduce the issue?
1. Download the AnyKey installer with upx compressed executable and drag+drop them into your apps folder. Try to start it and see the error. Notice that with codesign --verify --verbose /Applications/AnyKey.app there is no issue with signature.
[Installer with compressed binaries that fails on Big Sur](https://github.com/w-A-L-L-e/anykey-configurator/blob/development/mac-installer/AnyKeyInstaller_06-08-2020.dmg
)

2. Download the new installer we released with similar binary and same codesigning that is not compressed with upx. Notice everything works again without any issues:
[Installer that works again on Big Sur because we skipped upx compression in the release](https://github.com/w-A-L-L-e/anykey-configurator/blob/development/mac-installer/AnyKeyInstaller_11-13-2020.dmg)
Open the dmg, drag drop the app to applications, open it and see you get no errors, everything is fine.

3. Extra info: The error does not seem to happen for console based applications (just running in terminal). But it does happen for anything placed in /Applications that you click to open.

## Please tell us details about your environment.
* UPX version :
upx 3.95
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43

* Host Operating System and version:
macOS v 11.03 Big Sur
* Host CPU architecture:
Intel core i5 (64 bit) x86_64
* Target Operating System and version:
macOS v 11.03 Big Sur
* Target CPU architecture:
Intel core i5 (64 bit) x86_64

**Comment by rsheasby** [comment]
Can confirm I'm having the same issue even on a non-signed terminal only binary under Big Sur. I've build from HEAD but still no luck.

**Comment by jreiser** [comment]
re: "the same issue": please Copy+Paste the actual complaint, error message, and/or log info a Comment here.  Please run the executable under a debugger, in order to get more and better info. We cannot tell if the cases are the same unless we see the symptoms.  re: source code: Please use the HEAD of `devel` branch, which is dozens of commits beyond `master` branch.

**Comment by rsheasby** [comment]
I'm installing using `brew install upx --HEAD`, which does build from devel branch. 

Here's a console output containing the info you asked for:

```
$ upx testbin
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX git-3f30e4  Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 24th 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  36769752 ->  11751440   31.96%   macho/amd64   testbin

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.

$ ./testbin
fish: './testbin' terminated by signal SIGKILL (Forced quit)

$ lldb ./testbin
(lldb) target create "./testbin"
Current executable set to '/Users/rsheasby/Downloads/testbin' (x86_64).
(lldb) run
error: Bad executable (or shared library)
(lldb) ^D
```

Testbin is a Go binary that works correctly before upx'ing.
Unfortunately I'm unable to try debugging with GDB, as there seems to be an issue with that on Big Sur too.

**Comment by jreiser** [comment]
`error: Bad executable (or shared library)`. Thank you; now we can make progress.  Please upload ("Attach files by ...") or give a downloadable URL to an actual `testbin` that fails.  If uploading then use .gz, .zip, or .tgz to save space and pass through the GitHub file-type filter.  Or, please run `otool -hl testbin` both before and after applying UPX compression, then Copy+Paste the output (or give a URL).  This should give more clues!

**Comment by rsheasby** [comment]
Here's the zip of the binary
[testbin.zip](https://github.com/upx/upx/files/5641841/testbin.zip)
The working original file is here:
https://github.com/rsheasby/brood-clash/releases/download/v1.0.3/brood-clash-1.0.3-macos-amd64.11-amd64

Here's the otool outputs:
<details>
<summary>Broken Binary</summary>
<pre>
$ otool -hl testbin
testbin:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x80           2     6        512 0x00000085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __PAGEZERO
   vmaddr 0x0000000000000000
   vmsize 0x0000000004000000
  fileoff 0
 filesize 0
  maxprot 0x00000000
 initprot 0x00000000
   nsects 0
    flags 0x0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 152
  segname __TEXT
   vmaddr 0x000000000634b000
   vmsize 0x0000000000b35000
  fileoff 0
 filesize 11751424
  maxprot 0x00000007
 initprot 0x00000005
   nsects 1
    flags 0x0
Section
  sectname upxTEXT
   segname __TEXT
      addr 0x000000000634b3b0
      size 0x0000000000b34c50
    offset 944
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x0000000006e80000
   vmsize 0x0000000000001000
  fileoff 11751424
 filesize 16
  maxprot 0x00000007
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 3
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.11
      sdk 10.11
Load command 4
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 5
        cmd LC_UNIXTHREAD
    cmdsize 184
     flavor x86_THREAD_STATE64
      count x86_THREAD_STATE64_COUNT
   rax  0x0000000000000000 rbx 0x0000000000000000 rcx  0x0000000000000000
   rdx  0x0000000000000000 rdi 0x0000000000000000 rsi  0x0000000000000000
   rbp  0x0000000000000000 rsp 0x0000000000000000 r8   0x0000000000000000
    r9  0x0000000000000000 r10 0x0000000000000000 r11  0x0000000000000000
   r12  0x0000000000000000 r13 0x0000000000000000 r14  0x0000000000000000
   r15  0x0000000000000000 rip 0x0000000006e7f324
rflags  0x0000000000000000 cs  0x0000000000000000 fs   0x0000000000000000
    gs  0x0000000000000000
</pre>
</details>

<details>
<summary>Working Binary</summary>
<pre>
$ otool -hl brood-clash-1.0.3-macos-amd64.11-amd64
brood-clash-1.0.3-macos-amd64.11-amd64:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x80           2    17       2520 0x00000085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __PAGEZERO
   vmaddr 0x0000000000000000
   vmsize 0x0000000004000000
  fileoff 0
 filesize 0
  maxprot 0x00000000
 initprot 0x00000000
   nsects 0
    flags 0x0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 952
  segname __TEXT
   vmaddr 0x0000000004000000
   vmsize 0x0000000000fce000
  fileoff 0
 filesize 16572416
  maxprot 0x00000007
 initprot 0x00000005
   nsects 11
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000004001be0
      size 0x0000000000891bce
    offset 7136
     align 2^5 (32)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x00000000048937ae
      size 0x0000000000000438
    offset 8992686
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x0000000004893be8
      size 0x0000000000000718
    offset 8993768
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __rodata
   segname __TEXT
      addr 0x0000000004894300
      size 0x00000000003731a6
    offset 8995584
     align 2^5 (32)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __typelink
   segname __TEXT
      addr 0x0000000004c074c0
      size 0x00000000000050ec
    offset 12612800
     align 2^5 (32)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __itablink
   segname __TEXT
      addr 0x0000000004c0c5b0
      size 0x00000000000017d0
    offset 12633520
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __gosymtab
   segname __TEXT
      addr 0x0000000004c0dd80
      size 0x0000000000000000
    offset 12639616
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __gopclntab
   segname __TEXT
      addr 0x0000000004c0dd80
      size 0x00000000003b2f73
    offset 12639616
     align 2^5 (32)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x0000000004fc0d00
      size 0x000000000000714c
    offset 16518400
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x0000000004fc7e50
      size 0x00000000000054d0
    offset 16547408
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x0000000004fcd320
      size 0x0000000000000cc4
    offset 16569120
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 872
  segname __DATA
   vmaddr 0x0000000004fce000
   vmsize 0x00000000011e2000
  fileoff 16572416
 filesize 18513920
  maxprot 0x00000007
 initprot 0x00000003
   nsects 10
    flags 0x0
Section
  sectname __nl_symbol_ptr
   segname __DATA
      addr 0x0000000004fce000
      size 0x0000000000000010
    offset 16572416
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 180 (index into indirect symbol table)
 reserved2 0
Section
  sectname __got
   segname __DATA
      addr 0x0000000004fce010
      size 0x0000000000000030
    offset 16572432
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 182 (index into indirect symbol table)
 reserved2 0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x0000000004fce040
      size 0x00000000000005a0
    offset 16572480
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 188 (index into indirect symbol table)
 reserved2 0
Section
  sectname __const
   segname __DATA
      addr 0x0000000004fce5e0
      size 0x0000000000002948
    offset 16573920
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __go_buildinfo
   segname __DATA
      addr 0x0000000004fd0f30
      size 0x0000000000000020
    offset 16584496
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __noptrdata
   segname __DATA
      addr 0x0000000004fd0f60
      size 0x000000000118c53f
    offset 16584544
     align 2^5 (32)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x000000000615d4a0
      size 0x0000000000018830
    offset 34985120
     align 2^5 (32)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x0000000006175ce0
      size 0x0000000000035ac8
    offset 0
     align 2^5 (32)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Section
  sectname __noptrbss
   segname __DATA
      addr 0x00000000061ab7c0
      size 0x00000000000046c8
    offset 0
     align 2^5 (32)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Section
  sectname __common
   segname __DATA
      addr 0x00000000061afe88
      size 0x0000000000000010
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 3
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x00000000061b0000
   vmsize 0x000000000019b000
  fileoff 35086336
 filesize 1683416
  maxprot 0x00000007
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 4
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 0
    rebase_size 0
       bind_off 35086336
      bind_size 520
  weak_bind_off 0
 weak_bind_size 0
  lazy_bind_off 35086856
 lazy_bind_size 3640
     export_off 35090496
    export_size 7504
Load command 5
     cmd LC_SYMTAB
 cmdsize 24
  symoff 35128696
   nsyms 33235
  stroff 35661928
 strsize 1107824
Load command 6
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 32672
     iextdefsym 32672
     nextdefsym 371
      iundefsym 33043
      nundefsym 192
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 35660456
  nindirectsyms 368
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 7
          cmd LC_LOAD_DYLINKER
      cmdsize 32
         name /usr/lib/dyld (offset 12)
Load command 8
     cmd LC_UUID
 cmdsize 24
    uuid 6700AC12-F617-3E40-BD00-D332076FF8DC
Load command 9
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.11
      sdk 10.11
Load command 10
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 11
       cmd LC_MAIN
   cmdsize 24
  entryoff 434528
 stacksize 0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 02:00:02 1970
      current version 1225.1.1
compatibility version 1.0.0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 104
         name /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (offset 24)
   time stamp 2 Thu Jan  1 02:00:02 1970
      current version 1253.0.0
compatibility version 150.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name /System/Library/Frameworks/Security.framework/Versions/A/Security (offset 24)
   time stamp 2 Thu Jan  1 02:00:02 1970
      current version 57336.1.9
compatibility version 1.0.0
Load command 15
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 35098000
 datasize 30264
Load command 16
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 35128264
 datasize 432
</pre>
</details>

**Comment by rsheasby** [comment]
Interestingly, I've just tried it with a go "hello world" binary, including the exact same compile and link flags, and it worked without issue. Might indicate that the size of the input binary is part of the problem?

**Comment by elfmimi** [comment]
I have a Rust program 3945KB uncompressed and 513KB compressed, which didn't run.

**Comment by rsheasby** [comment]
Other notable differences I can think about between the hello world and the other testbin are as follows:

- Testbin has web assets built-in to the binary using pkger. AFAIK this is the equivalent of a massive amount of const variables, so I can't imagine it would matter besides just the size.
- Testbin is statically linked with sqlite and relies on cgo.

**Comment by jreiser** [comment]
@elfmimi Please run under lldb as in https://github.com/upx/upx/issues/424#issuecomment-738677075 then report what lldb says.  The actual detailed symptoms matter.

**Comment by fxcoudert** [comment]
At Homebrew, we're seeing the same issue (I think) as @rsheasby. It happens both with 3.96 and the top of the devel branch. Same symptoms in the `otool -hl` output.

**Comment by jreiser** [comment]
Please see #434 where a similar problem is evaded.
If a compressed executable does not run, then please report `otool -hl my_executable` both before and after compression.

**Comment by mitchblank** [comment]
> Please see #434 where a similar problem is evaded.

I opened up a homebrew PR (https://github.com/Homebrew/homebrew-core/pull/71160) so we can at least see how CI feels about it.

At least homebrew's sanity test (which just runs `upx` on itself and verifies that it still can run) passes now on my desktop which was not the case before.

**Comment by mitchblank** [comment]
Update; my homebrew CI test run passed on Intel 10.14, 10.15, and 11.  So it is definitely an improvement!

Didn't pass on 11-ARM which I guess is an known issue with upx (#404): https://github.com/Homebrew/homebrew-core/runs/1899633976?check_suite_focus=true
```
==> Testing upx
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210214-1390-1kffk6h.sb ruby -W0 -I $LOAD_PATH -- /opt/homebrew/Library/Homebrew/test.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/upx.rb --verbose
==> /opt/homebrew/Cellar/upx/3.96_1/bin/upx -1 ./upx
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1961716 ->    684048   34.87%   macho/arm64   upx

Packed 1 file.
==> ./upx -V
An exception occurred within a child process:
Error: upx: failed
```
I don't currently have a MacOS ARM machine to run local tests on so I can't tell you more

**Comment by leaanthony** [comment]
Currently my Go apps are failing using ARM/3.96/11.2.3. Weirdly, I just get an instant exit with no messages. Running through lldb doesn't give me much, just: `Process 10721 exited with status = 5 (0x00000005) `. Happy to test on ARM if someone could help me get set up.

**Comment by gauthamcode** [comment]
I'm getting Assertion failed: ((unsigned)len <= buf->getSize()), function readx, file file.cpp, line 276 error. when I run sudo upx -d /Applications/my_app.app/Contents/MacOS/my_app

**Comment by jreiser** [comment]
@gauthamcode Please upload ("Attach files by ..."), give the URL, or email an actual compiled binary executable which suffers the failure; use zip or gzip to reduce transfer size.  Or, run `upx -d` under a debugger, place a breakpoint on the assertion failure (such as symbol `__assert_fail@@GLIBC_2.2.5`; then capture and report the traceback when the breakpoint is hit.

**Comment by tyde7** [comment]
Hi I recently met this problem, and I just compiled a very simple c program by clang...
source code:
```c
#include <stdio.h>

int main(){
	printf("abc");
	return 0;
}
```
compiled not-runnable executable file: [acc.gz](https://github.com/upx/upx/files/6760296/acc.gz)

### version: 
macos 11.1
### clang version: 
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

### upx version:
upx 3.96
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
Copyright (C) 1996-2020 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2020 Laszlo Molnar
Copyright (C) 2000-2020 John F. Reiser
Copyright (C) 2002-2020 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.

**Comment by Naatan** [comment]
Any updates on this? It basically makes UPX unusable on macOS.

**Comment by zhanhb** [comment]
UPX work fine on my notebook
```txt
Darwin HOSTNAME 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64 i386 MacBookAir7,2 Darwin
```
```
$ brew info upx
upx: stable 3.96 (bottled), HEAD
Compress/expand executable files
https://upx.github.io/
/usr/local/Cellar/upx/3.96_1 (8 files, 1.9MB) *
  Poured from bottle on 2021-02-18 at 13:03:33
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/upx.rb
==> Dependencies
Build: ucl ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 7,746 (30 days), 26,007 (90 days), 108,500 (365 days)
install-on-request: 7,735 (30 days), 25,974 (90 days), 108,340 (365 days)
build-error: 31 (30 days)
```

**Comment by w-A-L-L-e** [comment]
@zhanhb yes the binary works. But if you compress an executable with upx on latest macos and then try to execute the signed and compressed executable from the applications folder it does not work anymore (I noticed this while developing the qt application for a project of mine). Hence this issue is reported...

**Comment by leaanthony** [comment]
Yeah, this is problematic for my use case too. What's the latest?

**Comment by Naatan** [comment]
fwiw we only saw this issue happen with Go compiled binaries that used cgo. We've since disabled cgo (`CGO_ENABLED=0`), which seems to have solved our upx issues.

**Comment by leaanthony** [comment]
Which is my exact use case 😃

**Comment by leaanthony** [comment]
What can we do to try and get this fixed?

**Comment by jreiser** [comment]
`What can we do to try and get this fixed?`  Point to comprehensive documentation on the requirements for an executable file to be launched as a graphical app.  Not "develop from start to finish in Xcode", but rather the content, layout, and interrelationships of the loader commands in the executable file.

For instance, the complete program `main5.c`:
```
int x[10000] = {1,2,3};  /* x[3..9999] are obviously compressible */

int main(int argc, char *argv[])
{
    return 5;
}
```
when compiled by `clang -o main5 main5.c` and examined by `otool -hl main5` shows these loader commands:
```
      cmd LC_SEGMENT_64  # __PAGEZERO
      cmd LC_SEGMENT_64  # __TEXT
      cmd LC_SEGMENT_64  # __DATA
      cmd LC_SEGMENT_64  # __LINKEDIT
            cmd LC_DYLD_INFO_ONLY
     cmd LC_SYMTAB
            cmd LC_DYSYMTAB
          cmd LC_LOAD_DYLINKER
     cmd LC_UUID
      cmd LC_BUILD_VERSION
      cmd LC_SOURCE_VERSION
       cmd LC_MAIN
          cmd LC_LOAD_DYLIB
      cmd LC_FUNCTION_STARTS
      cmd LC_DATA_IN_CODE
```
and examination of the description of the LC_SEGMENT_64 with name \_\_TEXT shows that all the LC_\* commands are contained within the \_\_TEXT segment.  When compressed by upx, then the loader commands are
```
      cmd LC_SEGMENT_64  # __PAGEZERO
      cmd LC_SEGMENT_64  # __TEXT (compressed)
      cmd LC_SEGMENT_64  # __LINKEDIT
      cmd LC_SOURCE_VERSION
        cmd LC_UNIXTHREAD
```
When loaded into the memory space of a new process according to the LC_SEGMENT_64 descriptors, and started executing at the initial program counter given in LC_UNIX_THREAD, then the UPX run-time stub de-compresses and re-constructs the contents of memory exactly as described by the original non-compressed LC_SEGMENT_64.  UPX also loads the LC_LOAD_DYLINKER, and starts it at its entry address.  The result is ordinary execution with shell exit code 5, as expected.

However, that does not work for a compressed graphical app, and the error information is not helpful in figuring out why. Because Apple's documentation is sparse (i.e., NONE), then Team UPX is left with the trial-and-error task of figuring out which subset of the ten or eleven non-LC_SEGMENT_64 commands must be added to the `compressed` file (the de-compressed run-time process image `already` is exactly the same as if compression were not involved) and what their contents and interrelationships must be.  Even if that can be engineered, there is the possibility that the launch process of a graphical app under MacOS inspects the loader commands `before` launching the executable file, and expects the pre-launch content (and pointed-to portions of the executable file) to be relevant to the post-launch process image.  Compression could easily break such assumptions.

**Comment by w-A-L-L-e** [comment]
@jreiser I can relate. We've had similar stuff going wrong with usb libraries on macOS between High Sierra and Mojave, somehow however apple fixed that by themselves (everything kept on working for us, even when upgrading to Big Sur). Problem was we patched it on our side to make it work again for that specific version of macOS and then when they fixed their side, it broke again on our side as well. Maybe that will happen for UPX too: if they have some spare time, they might be able to fix the issue on their side.

I still think UPX is a great tool for windows and linux and hopefully soon again for MacOS also. So keep up the great work, when it should appear to be fixed again we will definitely integrate UPX again in our build process for our next release to macOS.

**Comment by jreiser** [comment]
@w-A-L-L-e  Thank you for the encouragement.
In http://www.zarkonnen.com/signing_notarizing_catalina I have found some clues.  At the beginning of execution of a compressed program, then UPX de-compression is a kind of JIT code generation (Just-In-Time: i.e., at run time instead of at compile time), so probably a UPX-compressed app must have the same entitlements as a JAVA app: com.apple.security.cs.allow-jit(YES), etc.  Apparently the entitlements must be specified externally in a file such as `entitlements.plist` at the time of applying `codesign`.  It is Apple's deficiency that they cannot be expressed in a LC_... loader command within the executable itself.  UPX would add such a LC_... command into the compressed executable.

**Comment by Naatan** [comment]
> Point to comprehensive documentation on the requirements for an executable file to be launched as a graphical app

For what it's worth we ran into this issue through psutil's cgo usage:

https://github.com/shirou/gopsutil/blob/master/process/process_darwin_cgo.go

Which far as I can tell doesn't include any GUI components.

**Comment by leaanthony** [comment]
The only thing that stounds out there is  trying to access the details of an external process.

**Comment by flyingzl** [comment]
`brew ugprade  upx` works  well for me now

```bash
upx: stable 3.96 (bottled), HEAD
Compress/expand executable files
https://upx.github.io/
/usr/local/Cellar/upx/3.96_1 (8 files, 1.9MB) *
  Poured from bottle on 2022-01-12 at 09:40:56
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/upx.rb
==> Dependencies
Build: ucl ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 5,847 (30 days), 21,029 (90 days), 108,253 (365 days)
install-on-request: 5,848 (30 days), 21,013 (90 days), 108,091 (365 days)
build-error: 40 (30 days)
```

**Comment by leaanthony** [comment]
Is this really fixed though?

**Comment by Brawl345** [comment]
Still not fixed. Compress a binary with UPX and it will not start on macOS.

**Comment by timmattison** [comment]
The easiest way I can see to reproduce this on an M1 Mac is as follows:

```
$ brew install upx
… installs 3.96_1 as of today …

$ cp /bin/ls .
$ upx ls
                      Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
     88816 ->     20496   23.08%   macho/arm64   ls                            

Packed 1 file.

$ ./ls
zsh: killed ./ls
```

**Comment by gzm55** [comment]
> The easiest way I can see to reproduce this on an M1 Mac is as follows:
> 
> ```
> $ brew install upx
> … installs 3.96_1 as of today …
> 
> $ cp /bin/ls .
> $ upx ls
>                       Ultimate Packer for eXecutables
>                           Copyright (C) 1996 - 2020
> UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020
> 
>         File size         Ratio      Format      Name
>    --------------------   ------   -----------   -----------
>      88816 ->     20496   23.08%   macho/arm64   ls                            
> 
> Packed 1 file.
> 
> $ ./ls
> zsh: killed ./ls
> ```

`file /bin/ls` shows:

```bash
/bin/ls: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/bin/ls (for architecture x86_64):      Mach-O 64-bit executable x86_64
/bin/ls (for architecture arm64e):      Mach-O 64-bit executable arm64e
```

on x64 macos, after upx compressing, the output file is an arm64e executable

```bash
❯ file ls
ls: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
ls (for architecture x86_64):   Mach-O 64-bit executable x86_64
ls (for architecture arm64e):   Mach-O 64-bit executable arm64e

~
❯ upx ls
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
     88816 ->     20496   23.08%   macho/arm64   ls

Packed 1 file.

~
❯ file ls
ls: Mach-O 64-bit executable arm64e

~
❯ ./ls
zsh: bad CPU type in executable: ./ls
```

**Comment by dray92** [comment]
this is what I'm seeing on an M2 Mac 
```bash
$ arch
arm64
```

note: binary is built on a diff box
```bash
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ arch
x86_64
``` 

Uncompressed binary generated w/ `CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -trimpath -tags internal -ldflags "$(LDFLAGSINT)" -o dz-darwin-arm64` (`LDFLAGSINT="-s -w"`)
```bash
$ file ~/Downloads/dz-darwin-arm64
/Users/debo/Downloads/dz-darwin-arm64: Mach-O 64-bit executable arm64

$ ~/Downloads/dz-darwin-arm64 -h
....
```
Compressing:
```bash
$ upx dz-darwin-arm64 
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  49525378 ->  18567184   37.49%   macho/arm64   dz-darwin-arm64               

Packed 1 file.
```

Executing post compression
```bash
$ file ~/Downloads/dz-darwin-arm64
/Users/debo/Downloads/dz-darwin-arm64: Mach-O 64-bit executable arm64

$ ~/Downloads/dz-darwin-arm64 -h
zsh: killed     ~/Downloads/dz-darwin-arm64 -h
```

**Comment by jreiser** [comment]
@dray92 Please confirm the MacOS version where you observe the "killed".  MacOS 13 (Ventura), 12 (Monetrey), 11(Big Sur).  They're all different in ways that might matter.

**Comment by dray92** [comment]
@jreiser I'm on Ventura (`13.0.1 (22A400)`)

**Comment by munntjlx** [comment]
Sadness me as well, thank the universe that I am mostly a unix user!

**Comment by rsheasby** [comment]
> Sadness me as well, thank the universe that I am mostly a unix user!

macOS is the only currently maintained POSIX (Unix) compliant certified OS 🙂

**Comment by yanfaliupst** [comment]
Adding data seeing on Sonoma 14.1.2

**Comment by Arvin2focus** [comment]
Mac M3 max , sonoma 14.4  

$ upx redress
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   7427778 ->   4259856   57.35%   macho/arm64   redress

Packed 1 file.

$ ./redress
Killed: 9

**Comment by jreiser** [comment]
@Arvin2focus  Repeating the complaint with an old upx 4.1.0 will not hasten the fix.  upx-4.2.3 was released today.  The problem is Apple changing the requirements [every year!] but not giving any documentation.  The tracking issue for upx on MacOS  is https://github.com/upx/upx/issues/612 .
