### ISSUE TITLE
Create a sandbox for UPX

### ISSUE THREAD

**Issue by liamjm** [upx/upx#427]
## What's the problem (or question)?
We should create a sandbox to allow users to handle un-trusted input.
Google has already created (and using) a UPX sandbox using [Sandboxed API](https://developers.google.com/sandboxed-api). I can work on migrating the code to this github repo.

## What should have happened?
This sandbox should support the decompression of untrusted input, as this is more important than the compression mode.

## Do you have an idea for a solution?
Utilize [Sandboxed API](https://developers.google.com/sandboxed-api)

## How can we reproduce the issue?
See recent issues found by fuzzing examples of the risk of running untrusted code.

## Please tell us details about your environment.
 n/a

**Comment by liamjm** [comment]
I have proposed using Sandboxed API as a solution already exists, but let me know if there is a preference for an alternative.

A couple of questions:
a) should the code go in src/sapi_sandbox ?
b) SAPI supports CMake and Bazel. Is CMake preferred?

**Comment by jreiser** [comment]
b) UPX will allow CMake only if the use of CMake is a completely optional addition, with absolutely no modifications to current operations.  In particular a file whose name begins with 'M' (capital em) must not be added, else bash shell filename completion of "M<TAB>" (which currently gives "Makefile" or nothing) would be different.
a) If "src/sapi_sandbox" is a directory then please use ".dir" suffix.  If it is an ordinary file then please use an appropriate common suffix.

**Comment by liamjm** [comment]
Re the directory name, why the ".dir" suffix?
None of the other directories have this suffix and having a suffix on directories is not common practice.

**Comment by jreiser** [comment]
re: .dir.  OK.  I was confused about the purpose.
