### ISSUE TITLE
The compressed .exe is not working it says "This app can`t run on your PC" the exe is created in electron-packager

### ISSUE THREAD

**Issue by MotagamwalaTaha** [upx/upx#430]
## What's the problem (or question)?
The compressed .exe is not working it says "This app can`t run on your PC" the exe is created in electron

## What should have happened?
The compressed exe should have opened

## Please tell us details about your environment.
* UPX version used (`upx --version`): 3.96
* Host Operating System and version: Windows 10 20H2
* Host CPU architecture: X64
* Target Operating System and version: same as host
* Target CPU architecture: same as host

**Comment by jreiser** [comment]
Please use the `devel` branch which has several fixes related to PE files.  This issue might also be the same as https://github.com/upx/upx/issues/411# which has been resolved and closed.

**Comment by MotagamwalaTaha** [comment]
Thanks but what is the procedure for building upx source can you please tell me
