### ISSUE TITLE
Decompression fails for ununtu20.04 shared library   and   upx-3.96-amd64_linux.tar.xz can't be used

### ISSUE THREAD

**Issue by sunrong0511** [upx/upx#433]
## What's the problem (or question)?
THE FIRST:It feel same with posted by@jreiser #341
./upx.out -1 -o lib.so libdark.so
libdark.so  6/8  [*******************************************]   48.2%  \    2979176 ->   1449348   48.65%   linux/amd64   lib.soPacked 1 file.
./upx.out -d -o lib1.so lib.so
upx.out: lib.so: NotPackedException: not packed by UPXUnpacked 0 files
upx.out  is build by code（https://github.com/upx/upx.git）
readelf -d libdark.so
Dynamic section at offset 0x107a18 contains 30 entries:  
Tag        Type                         Name/Value 
0x0000000000000001 (NEEDED)             Shared library: [libgomp.so.1] 
0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0] 
0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6] 
0x0000000000000001 (NEEDED)             Shared library: [libm.so.6] 
0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1] 
0x0000000000000001 (NEEDED)             Shared library: [libc.so.6] 
0x000000000000000e (SONAME)             Library soname: [libdark.so] 
0x000000000000000c (INIT)               0x1e000 
0x000000000000000d (FINI)               0xe5ad0 
0x0000000000000019 (INIT_ARRAY)         0x108880 
0x000000000000001b (INIT_ARRAYSZ)       32 (bytes) 
0x000000000000001a (FINI_ARRAY)         0x1088a0 
0x000000000000001c (FINI_ARRAYSZ)       8 (bytes) 
0x000000006ffffef5 (GNU_HASH)           0x2f0 
0x0000000000000005 (STRTAB)             0xb648 
0x0000000000000006 (SYMTAB)             0x2ba0 
0x000000000000000a (STRSZ)              37943 (bytes) 
0x000000000000000b (SYMENT)             24 (bytes) 
0x0000000000000003 (PLTGOT)             0x109000 
0x0000000000000002 (PLTRELSZ)           25152 (bytes) 
0x0000000000000014 (PLTREL)             RELA 
0x0000000000000017 (JMPREL)             0x17198 
0x0000000000000007 (RELA)               0x157a0 
0x0000000000000008 (RELASZ)             6648 (bytes) 
0x0000000000000009 (RELAENT)            24 (bytes) 
0x000000006ffffffe (VERNEED)            0x15610 
0x000000006fffffff (VERNEEDNUM)         6 
0x000000006ffffff0 (VERSYM)             0x14a80 
0x000000006ffffff9 (RELACOUNT)          130 
0x0000000000000000 (NULL)               0x0THE 

SECOND:upx from upx-3.96-amd64_linux.tar.xz can't be used, the same with upx-3.95-amd64_linux.tar.xz
./upxbash: ./upx: cannot execute binary file: Exec format error
uname -aLinux LAPTOP-MR19TKB1 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

## How can we reproduce the issue?
1.2.3.4.
## Please tell us details about your environment.
* UPX version used (`upx --version`): 3.96
* Host Operating System and version: ununtu20.04
* Host CPU architecture: amd64
* Target Operating System and version: ununtu20.04
* Target CPU architecture: amd64
[libdark.zip](https://github.com/upx/upx/files/5605469/libdark.zip)

**Comment by jreiser** [comment]
0) Please try the tip of `devel` branch which has many fixes beyond version 3.96.
1) Please upload ("Attach files by ...") or provide URL to libdark.so or any other actual file which fails the compress+decompress cycle.  Use .zip, .gz, or .tgz to compress uploads so that github will accept them.
2) https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz does run after extracting the xz archive (compresses ELF executables for amd64_linux, etc.) on vanilla Linux.  If it fails on your system then your system has a bug.
Evidence of successful execution:
```
$ sha256sum upx
b97d182d9718fd7fd608fa2ce3375a15f479c73415b51999dcb5fea72646f53c  upx
$ readelf --headers upx
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x4673d8
  Start of program headers:          64 (bytes into file)
  Start of section headers:          0 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         3
  Size of section headers:           64 (bytes)
  Number of section headers:         0
  Section header string table index: 0

There are no sections in this file.

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
                 0x000000000006866c 0x000000000006866c  R E    0x200000
  LOAD           0x0000000000000000 0x0000000000469000 0x0000000000469000
                 0x0000000000000000 0x0000000000385f18  RW     0x1000
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
$ ./upx -f -o foo /bin/date
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    176296 ->     49924   28.32%   linux/amd64   foo                           

Packed 1 file.
$ ./foo
Thu 26 Nov 2020 09:37:29 AM PST
$ 
```

**Comment by jreiser** [comment]
upx-3.96 also runs successfully on
```
Linux ubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
which was running the Live system of ubuntu-20.04.1 from
```
https://releases.ubuntu.com/20.04/ubuntu-20.04.1-desktop-amd64.iso.torrent?_ga=2.161709556.959308878.1606413289-658093758.1606413289
```

**Comment by sunrong0511** [comment]
> 1. Please try the tip of `devel` branch which has many fixes beyond version 3.96.
> 2. Please upload ("Attach files by ...") or provide URL to libdark.so or any other actual file which fails the compress+decompress cycle.  Use .zip, .gz, or .tgz to compress uploads so that github will accept them.
> 3. https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz does run after extracting the xz archive (compresses ELF executables for amd64_linux, etc.) on vanilla Linux.  If it fails on your system then your system has a bug.
>    Evidence of successful execution:
> 
> ```
> $ sha256sum upx
> b97d182d9718fd7fd608fa2ce3375a15f479c73415b51999dcb5fea72646f53c  upx
> $ readelf --headers upx
> ELF Header:
>   Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
>   Class:                             ELF64
>   Data:                              2's complement, little endian
>   Version:                           1 (current)
>   OS/ABI:                            UNIX - System V
>   ABI Version:                       0
>   Type:                              EXEC (Executable file)
>   Machine:                           Advanced Micro Devices X86-64
>   Version:                           0x1
>   Entry point address:               0x4673d8
>   Start of program headers:          64 (bytes into file)
>   Start of section headers:          0 (bytes into file)
>   Flags:                             0x0
>   Size of this header:               64 (bytes)
>   Size of program headers:           56 (bytes)
>   Number of program headers:         3
>   Size of section headers:           64 (bytes)
>   Number of section headers:         0
>   Section header string table index: 0
> 
> There are no sections in this file.
> 
> Program Headers:
>   Type           Offset             VirtAddr           PhysAddr
>                  FileSiz            MemSiz              Flags  Align
>   LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
>                  0x000000000006866c 0x000000000006866c  R E    0x200000
>   LOAD           0x0000000000000000 0x0000000000469000 0x0000000000469000
>                  0x0000000000000000 0x0000000000385f18  RW     0x1000
>   GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
>                  0x0000000000000000 0x0000000000000000  RW     0x10
> $ ./upx -f -o foo /bin/date
>                        Ultimate Packer for eXecutables
>                           Copyright (C) 1996 - 2020
> UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020
> 
>         File size         Ratio      Format      Name
>    --------------------   ------   -----------   -----------
>     176296 ->     49924   28.32%   linux/amd64   foo                           
> 
> Packed 1 file.
> $ ./foo
> Thu 26 Nov 2020 09:37:29 AM PST
> $ 
> ```
0.I tested devel just now, but the problem is the same:
./upx.out -o libdark.so libdark1.so
libdark1.so  6/8  [*******************************************]   29.8%  \    2979176 ->   1052036   35.31%   linux/amd64   libdark.so
Packed 1 file.
./upx.out -d -o libda.so libdark.so
upx.out: libdark.so: NotPackedException: not packed by UPX
Unpacked 0 files.
1.here is file[libdark1.zip](https://github.com/upx/upx/files/5606060/libdark1.zip)

**Comment by sunrong0511** [comment]
@jreiser ，Have you test my files “libdark.so”？

**Comment by jreiser** [comment]
@sunrong0511  Thank you for providing a URL for libdark1.zip.  Yes, I have reproduced the problem with applying `upx -d` to the upx-compressed libdark.so.  I have an idea for a fix, have added that to my work queue.

**Comment by sunrong0511** [comment]
@jreiser  Thanks a lot for your kindly response，waiting for your news.

**Comment by sunrong0511** [comment]
> @sunrong0511 Thank you for providing a URL for libdark1.zip. Yes, I have reproduced the problem with applying `upx -d` to the upx-compressed libdark.so. I have an idea for a fix, have added that to my work queue.

Hello, happy new year~ And is there any updates on resolving this issue?

**Comment by jreiser** [comment]
The above commit on `devel` branch successfully unpacks the result of packing libdark1.so.

**Comment by sunrong0511** [comment]
> The above commit on `devel` branch successfully unpacks the result of packing libdark1.so.

![微信图片_20210311174833](https://user-images.githubusercontent.com/30221502/110769381-13dd3680-8293-11eb-8108-c0adaba5d51a.png)

**Comment by sunrong0511** [comment]
I use commit--bbefbd7  to generate upx, but there is error message. what may cause the problem?
