### ISSUE TITLE
Bad compressed (GraalVM) executable produced by UPX on BigSur

### ISSUE THREAD

**Issue by bric3** [upx/upx#434]
Hi there, I'd to express my gratitude for this tool, I have been using it since 10 years. Reaaly thank you !

## What's the problem (or question)?

What brings me here is this https://github.com/oracle/graal/issues/3012 issue with GraalVM. I've seen and been pointed to 
https://github.com/upx/upx/issues/424, but I think the problem is slightly different, i.e. the binary is not signed.
And I can compress other executables.

Also the steps below works flawlessly on Catalina (macOs 10.15).

## What should have happened?

The program works normally.

## Do you have an idea for a solution?

None, I'm not versed in native code at all. 

All I can say is I have tried `dtruss`

```shell
$ sudo dtruss ./upxed
Password:
dtrace: failed to execute ./upxed: Bad executable (or shared library)
```

And gdb without success.

## How can we reproduce the issue?

```shell
$ brew install upx # the same happen when build from source
$ asdf install java graalvm-20.3.0+java11
$ gu install native-image
```

```shell
$ echo "public class UpxReproducer {
  public static void main(String... args) { System.out.println(\"hi\"); }
}" > UpxReproducer.java

$ javac UpxReproducer.java

$ java UpxReproducer
hi

$ native-image --native-image-info --no-fallback -cp . UpxReproducer upx-reproducer
[upx-reproducer:99157]    classlist:   1,434.47 ms,  0.96 GB
[upx-reproducer:99157]        (cap):   3,631.36 ms,  0.96 GB
[upx-reproducer:99157]        setup:   5,360.21 ms,  0.96 GB
[upx-reproducer:99157]     (clinit):     159.68 ms,  1.20 GB
[upx-reproducer:99157]   (typeflow):   3,948.16 ms,  1.20 GB
[upx-reproducer:99157]    (objects):   3,304.07 ms,  1.20 GB
[upx-reproducer:99157]   (features):     173.29 ms,  1.20 GB
[upx-reproducer:99157]     analysis:   7,750.64 ms,  1.20 GB
[upx-reproducer:99157]     universe:     359.12 ms,  1.22 GB
[upx-reproducer:99157]      (parse):     833.45 ms,  1.22 GB
[upx-reproducer:99157]     (inline):   1,071.70 ms,  1.67 GB
[upx-reproducer:99157]    (compile):   6,324.50 ms,  2.26 GB
[upx-reproducer:99157]      compile:   8,708.08 ms,  2.26 GB
[upx-reproducer:99157]        image:   1,235.02 ms,  2.26 GB
[upx-reproducer:99157]        write:     371.41 ms,  2.26 GB
[upx-reproducer:99157]      [total]:  25,403.60 ms,  2.26 GB

$ ./upx-reproducer
hi

$  upx -v -o upxed upx-reproducer
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   8032760 ->   2273296   28.30%   macho/amd64   upxed                         

Packed 1 file.

$ upx -t upxed
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

testing upxed [OK]

Tested 1 file.

$ ./upxed
[1]    80280 killed     ./upxed

$ upx -d -o upx-reproducerd upxed
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   8032752 <-   2273296   28.30%   macho/amd64   upx-reproducerd

Unpacked 1 file.

$ ./upx-reproducerd
hi
```

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.96
* Host Operating System and version: BigSur 11.0.1 (or 10.16.0)
* Host CPU architecture: Intel
* Target Operating System and version: same
* Target CPU architecture: same

**Comment by ericdallo** [comment]
Same issue with [clojure-lsp](https://clojure-lsp.github.io/clojure-lsp/) compiled with GraalVM and then compressed with UPX, it seems to only happens with MacOS Big Sur, any news here @jreiser ?

**Comment by jreiser** [comment]
The above commit on `devel` branch avoids the immediate "Bad executable" for MH_EXECUTE on BigSur.  There may be problems with code signing.

Note: if a compressed executable does not run, then please do:
```
otool -hl my_executable  # before compression
otool -hl my_executable.upx  # after compression
```
and copy+paste using enough Markdown formatting to preserve line breaks.  (For example, put a line containing only three backtick characters (hex 0x60, octal 0140, decimal 96) both before and after the text.)

**Comment by PeratX** [comment]
Fix confirmed. My compressed rust binaries can be executed on Big Sur now.

**Comment by bric3** [comment]
For reference here's the `otool` output on my reproducer.

<details>
<summary><code>otool -hl upx-reproducer</code></summary>

```shell
$otool -hl upx-reproducer
upx-reproducer:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           2    20       2472 0x00200085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __PAGEZERO
   vmaddr 0x0000000000000000
   vmsize 0x0000000100000000
  fileoff 0
 filesize 0
  maxprot 0x00000000
 initprot 0x00000000
   nsects 0
    flags 0x0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 632
  segname __TEXT
   vmaddr 0x0000000100000000
   vmsize 0x00000000002d4000
  fileoff 0
 filesize 2965504
  maxprot 0x00000005
 initprot 0x00000005
   nsects 7
    flags 0x0
Section
  sectname __stubs
   segname __TEXT
      addr 0x0000000100003810
      size 0x00000000000002f4
    offset 14352
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x0000000100003b04
      size 0x00000000000004fc
    offset 15108
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000100004000
      size 0x00000000002cc3d8
    offset 16384
     align 2^12 (4096)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x00000001002d03d8
      size 0x0000000000003012
    offset 2950104
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x00000001002d33f0
      size 0x0000000000000140
    offset 2962416
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __objc_methname
   segname __TEXT
      addr 0x00000001002d3530
      size 0x0000000000000023
    offset 2962736
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __eh_frame
   segname __TEXT
      addr 0x00000001002d3558
      size 0x00000000000002b8
    offset 2962776
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 392
  segname __DATA_CONST
   vmaddr 0x00000001002d4000
   vmsize 0x0000000000008000
  fileoff 2965504
 filesize 32768
  maxprot 0x00000003
 initprot 0x00000003
   nsects 4
    flags 0x10
Section
  sectname __got
   segname __DATA_CONST
      addr 0x00000001002d4000
      size 0x0000000000000028
    offset 2965504
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 126 (index into indirect symbol table)
 reserved2 0
Section
  sectname __mod_init_func
   segname __DATA_CONST
      addr 0x00000001002d4028
      size 0x0000000000000008
    offset 2965544
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000009
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __DATA_CONST
      addr 0x00000001002d5000
      size 0x0000000000003aa8
    offset 2969600
     align 2^12 (4096)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __objc_imageinfo
   segname __DATA_CONST
      addr 0x00000001002d8aa8
      size 0x0000000000000008
    offset 2984616
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 3
      cmd LC_SEGMENT_64
  cmdsize 632
  segname __DATA
   vmaddr 0x00000001002dc000
   vmsize 0x00000000004c4000
  fileoff 2998272
 filesize 4997120
  maxprot 0x00000003
 initprot 0x00000003
   nsects 7
    flags 0x0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x00000001002dc000
      size 0x00000000000003f0
    offset 2998272
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 131 (index into indirect symbol table)
 reserved2 0
Section
  sectname __objc_selrefs
   segname __DATA
      addr 0x00000001002dc3f0
      size 0x0000000000000010
    offset 2999280
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x10000005
 reserved1 0
 reserved2 0
Section
  sectname __objc_classrefs
   segname __DATA
      addr 0x00000001002dc400
      size 0x0000000000000008
    offset 2999296
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x10000000
 reserved1 0
 reserved2 0
Section
  sectname __svm_heap
   segname __DATA
      addr 0x00000001002dd000
      size 0x00000000004be478
    offset 3002368
     align 2^12 (4096)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x000000010079c000
      size 0x0000000000001a6c
    offset 7979008
     align 2^12 (4096)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x000000010079da70
      size 0x0000000000000200
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Section
  sectname __common
   segname __DATA
      addr 0x000000010079dc70
      size 0x00000000000000b0
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 4
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x00000001007a0000
   vmsize 0x000000000000c000
  fileoff 7995392
 filesize 37360
  maxprot 0x00000001
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 5
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 7995392
    rebase_size 4248
       bind_off 7999640
      bind_size 1304
  weak_bind_off 0
 weak_bind_size 0
  lazy_bind_off 8000944
 lazy_bind_size 2208
     export_off 8003152
    export_size 2160
Load command 6
     cmd LC_SYMTAB
 cmdsize 24
  symoff 8005320
   nsyms 1009
  stroff 8022496
 strsize 10256
Load command 7
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 809
     iextdefsym 809
     nextdefsym 40
      iundefsym 849
      nundefsym 160
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 8021464
  nindirectsyms 257
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 8
          cmd LC_LOAD_DYLINKER
      cmdsize 32
         name /usr/lib/dyld (offset 12)
Load command 9
     cmd LC_UUID
 cmdsize 24
    uuid 9999923E-D239-39AA-AAE2-2FBCF0442AFA
Load command 10
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 11.0
      sdk 11.0
   ntools 1
     tool 3
  version 609.7
Load command 11
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 12
       cmd LC_MAIN
   cmdsize 24
  entryoff 97824
 stacksize 0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1292.0.0
compatibility version 1.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1770.106.0
compatibility version 300.0.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name /usr/lib/libz.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1.2.11
compatibility version 1.0.0
Load command 16
          cmd LC_LOAD_DYLIB
      cmdsize 104
         name /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1770.106.0
compatibility version 150.0.0
Load command 17
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libobjc.A.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 228.0.0
compatibility version 1.0.0
Load command 18
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 8005312
 datasize 8
Load command 19
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 8005320
 datasize 0
```

</details>

<details><summary><code>otool -hl upxed</code></summary>

```shell
$ otool -hl upxed
upxed:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           2     5        496 0x00200085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __PAGEZERO
   vmaddr 0x0000000000000000
   vmsize 0x0000000100000000
  fileoff 0
 filesize 0
  maxprot 0x00000000
 initprot 0x00000000
   nsects 0
    flags 0x0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 152
  segname __TEXT
   vmaddr 0x0000000100000000
   vmsize 0x000000000022b000
  fileoff 0
 filesize 2273280
  maxprot 0x00000007
 initprot 0x00000005
   nsects 1
    flags 0x0
Section
  sectname upxTEXT
   segname __TEXT
      addr 0x00000001000003b0
      size 0x000000000022ac50
    offset 944
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x000000010022b000
   vmsize 0x0000000000001000
  fileoff 2273280
 filesize 16
  maxprot 0x00000007
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 3
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 4
        cmd LC_UNIXTHREAD
    cmdsize 184
     flavor x86_THREAD_STATE64
      count x86_THREAD_STATE64_COUNT
   rax  0x0000000000000000 rbx 0x0000000000000000 rcx  0x0000000000000000
   rdx  0x0000000000000000 rdi 0x0000000000000000 rsi  0x0000000000000000
   rbp  0x0000000000000000 rsp 0x0000000000000000 r8   0x0000000000000000
    r9  0x0000000000000000 r10 0x0000000000000000 r11  0x0000000000000000
   r12  0x0000000000000000 r13 0x0000000000000000 r14  0x0000000000000000
   r15  0x0000000000000000 rip 0x0000000100229f18
rflags  0x0000000000000000 cs  0x0000000000000000 fs   0x0000000000000000
    gs  0x0000000000000000
```

</details>

**Comment by christian-korneck** [comment]
Is there any chance that this fix could be added to master / a release?

While homebrew added this patch for the upx package they ship for MacOS, most Linux distros didn't. Therefore upx-compressing Mac executable on these Linux distros produces binaries that don't run on any actively supported MacOS version (quite common in cross compiling scenarios). I'd argue this should be a hotfix.

**Comment by jreiser** [comment]
Each commit which references a specific issue triggers a GitHub automatic build Action, and artifacts (results) of a successful build can be downloaded.  So anyone who is motivated can get a UPX executable that corresponds to a recent commit.  The main UPX page https://github.com/upx contains a link https://github.com/upx/upx-automatic-builds, which gives instructions. For instance, on the page https://github.com/upx/upx/actions/runs/823722400#artifacts for the current tip, there are 9 Artifacts including [https://github.com/upx/upx/suites/2686736961/artifacts/59228442](url) which is labeled amd64-linux-gcc-10. Please try it.

**Comment by christian-korneck** [comment]
@jreiser thanks a lot for the infos. I'm using a custom build of upx and the github actions workflow definition has been _very_ helpful for getting me there. Much appreciated that the CI exists. My comment was more meant as a _suggestion_ to transition this patch into a stable version of upx (for a reason). 

(Having said that I have no idea about the project's qa/release processes and it's just a suggestion).

**Comment by kritzikratzi** [comment]
a little summary from someone trying to figure this out: 

1. produce an unsigned bundle
1. pack the app with latest homebrew version of upx (has the patch mentioned in this thread)
2. sign the app with --options=runtime --entitlements app.entitlements
3. then staple as usual


entitlements file: (not sure all of them are needed, but those definitely work)

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.cs.disable-library-validation</key>
	<true/>
	<key>com.apple.security.cs.allow-unsigned-executable-memory</key>
	<true/>	
	<key>com.apple.security.cs.disable-executable-page-protection</key>
	<true/>	
</dict>
</plist>

```

**Comment by jreiser** [comment]
@kritzikratzi  Thank you for the encouraging news.  Could you please enhance your report by adding some details and explanations so that a newbie Apple developer can understand and repeat what you did?

1. What properties are important for a `bundle`?  Could a bare MH_EXECUTE file work?  What flags does `otool -hv` show in your case?
2. Which file(s) are processed by `pack the app`?
3. What properties are necessary for the identity used by `codesign`?  Does the null identity work: `codesign -s - --options=runtime  --entitlements app.entitlements filename-to-be-signed`, or is a certificate required, or a certificate that is trusted in a chain from Apple?
4. What does `staple` mean?  What literal commands (anonymized) did you use? Does the compressed MH_EXECUTE file run after it is copied somewhere else?

**Comment by kritzikratzi** [comment]
i mean... it's a painful process and apple keeps changing it, so expect this info to be outdated in a few months. 

you will need to prepare a few things, for simplicity i'm assuming all files are sitting flat in a folder. 


# intro

this is the binary made through whatever process. i'm assuming it to be named `intro` and executable as `./intro` in the scripts below. 

# icon.icns 

this is the simplest one. get any icns file ready and name it icon.icns :) 

# Info.plist

i'm sure it can be made shorter, but this is what i'm using. 

	<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
	<plist version="1.0">
	<dict>
		<key>CFBundleDevelopmentRegion</key>
		<string>English</string>
		<key>CFBundleExecutable</key>
		<string>intersect</string>
		<key>CFBundleIconFile</key>
		<string>icon.icns</string>
		<key>CFBundleIdentifier</key>
		<string>me.asdfg.intersect</string>
		<key>CFBundleInfoDictionaryVersion</key>
		<string>6.0</string>
		<key>CFBundleLongVersionString</key>
		<string></string>
		<key>CFBundleName</key>
		<string></string>
		<key>CFBundlePackageType</key>
		<string>APPL</string>
		<key>CFBundleShortVersionString</key>
		<string></string>
		<key>CFBundleSignature</key>
		<string>????</string>
		<key>CFBundleVersion</key>
		<string></string>
		<key>CSResourcesFileMapped</key>
		<true/>
		<key>NSHumanReadableCopyright</key>
		<string></string>
		<key>NSHighResolutionCapable</key>
		<true/>
	</dict>
	</plist>

# osx.entitlements

The entitlements file. Not sure those are all required. 

	<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
	<plist version="1.0">
	<dict>
		<key>com.apple.security.cs.disable-library-validation</key>
		<true/>
		<key>com.apple.security.cs.allow-unsigned-executable-memory</key>
		<true/>	
		<key>com.apple.security.cs.disable-executable-page-protection</key>
		<true/>	
	</dict>
	</plist>

# osx-sign.sh, osx-notarize.sh, osx-config.sh

you can find those here: https://github.com/kritzikratzi/Oscilloscope/tree/master/scripts

you will have to rename [osx-config-template.sh](https://github.com/kritzikratzi/Oscilloscope/blob/master/scripts/osx-config-template.sh) to osx-config.sh and fill in the details. 

i drag those from project to project and keep having to adjust a bit everytime. please don't assume those are perfect :) 

# osx-bundle.sh

	dest=intersect
	bundle_id="me.asdfg.intersect"

	if [ -f $dest ]
	then
		rm $dest
	fi

	strip intro
	upx -9 -o $dest intro

	if [ -f $dest.app ]
	then
		rm -rf $dest.app
	fi

	mkdir -p $dest.app/Contents/MacOS
	mkdir -p $dest.app/Contents/Resources

	mv $dest $dest.app/Contents/MacOS
	cp Info.plist $dest.app/Contents
	cp icon.icns $dest.app/Contents/Resources

	source osx-config.sh
	bash osx-sign.sh "$dest.app" "$DEVELOPER_IDENTITY" "osx.entitlements"
	bash osx-notarize.sh "$dest.app" "me.asdfg.intersect" "$DEVELOPER_TEAMID" "$ASC_PROVIDER" "$NOTARIZE_USER" "$NOTARIZE_PASSWORD" "$dest.zip"



# Use it! 

Well, now that you've done all that it should be as simple as calling `bash osx-bundle.sh`. To repeat, here are the steps it performs: 

1. First strip&pack the intro file. Then copy the tiny intro file, icon and plist and copy them together in folder structure that osx recognizes as app. 
2. osx-sign.sh uses the built-in `codesign` tool to digitally sign the files in the app bundle. 
3. osx-notarize.sh uses the built-in `ditto` to zip the bundle, `altool` sends the zip to apple's servers for notarization, and `staple` is used to store the resulting info into the existing bundle. the zip used for upload is deleted, and a new zip of the signed&notarized bundle is created. 


All the files above can certainly be made smaller, but hey.. gotta start somewhere :)

**Comment by markus-oberhumer** [comment]
I doubt this is fixed, reopening.

**Comment by christian-korneck** [comment]
> Please remove the stale label or add a comment

I believe this is still a valid issue?

**Comment by jreiser** [comment]
There will be no progress on this Issue until there is an explicit testcase: a specific literal executable file that becomes a bad executable when compressed.  The recipes given in the Description and follow-up Comments are too fragile to reproduce (or even to follow mentally).  So please construct a `.tar`, `.zip`, or `.gz` file which contains the Application [in Apple-speak] and all its resources (etc.), and identify which file is  the executable.  Then `Paste, drop, or click to add files`,or give the URL for downloading.

**Comment by markus-oberhumer** [comment]
Ok, closing then. We can reopen if necessary.
