### ISSUE TITLE
AppVeyor auto-builds of UPX complain MSVC C4245 signed versus unsigned

### ISSUE THREAD

**Issue by jreiser** [upx/upx#435]
## What's the problem (or question)?

Recent AppVeyor auto-builds of UPX for Windows using MSVC (all versions) fail on pefile.cpp.  For instance:
```
Environment: C=msvc-14.2-x64, CL_VERSION=19.24, VS_VERSION=2019, APPVEYOR_BUILD_WORKER_IMAGE=Visual Studio 2019
AppVeyor status: https://ci.appveyor.com/project/markus-oberhumer/upx/builds/36557404/job/327tk1ei57b2n0lf
Compiler complaint:
c:\projects\upx\src\pefile.cpp(2251): error C2220: the following warning is treated as an error
c:\projects\upx\src\pefile.cpp(3114): note: see reference to function template instantiation 'void PeFile::pack0<LE32,PeFile32::pe_header_t>(OutputFile *,ht &,ht &,unsigned int,upx_uint64_t,bool)' being compiled
        with
        [
            ht=PeFile32::pe_header_t
        ]
c:\projects\upx\src\pefile.cpp(2251): warning C4245: 'argument': conversion from 'int' to 'unsigned int', signed/unsigned mismatch
```
## What should have happened?

No complaint from the compiler.

## Do you have an idea for a solution?

In bele.c the macros such as `V unsigned get16_signed(const void *p) C` whose prototype declares that the result is `unsigned` must actually return `unsigned` results.

## How can we reproduce the issue?

1. Check failed AppVeyor build such as https://ci.appveyor.com/project/markus-oberhumer/upx/builds/36557404
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): UPX git-eb6647+
* Host Operating System and version: MSFT WIndows10
* Host CPU architecture: x86_64
* Target Operating System and version: MSFT WIndows10
* Target CPU architecture: x86_64

**Comment by markus-oberhumer** [comment]
Fixed in 92064c30abf276d28b504bb3e8ad839161def2b2.
