### ISSUE TITLE
Error when using Chromium Embedded Framework dlls compressed with UPX

### ISSUE THREAD

**Issue by soinalastudio** [upx/upx#436]
## What's the problem (or question)?
The main dll from CEF (Chromium Embedded Framework) is compressed successfully with UPX (version 3.96w): initial Size: 114Mb and final size: 44MB for the version I tested. When running the application, one error occurs at the starting of the program saying that the compressed file is not a valid win32 executable. I tried with different version of UPX but it's the same thing. 

## What should have happened?
When using non compressed dll, the program runs without problem.

## Do you have an idea for a solution?
No idea, sorry

## How can we reproduce the issue?

1. Download the sample application provided here: [https://cef-builds.spotifycdn.com/cef_binary_87.1.11%2Bg8bb7705%2Bchromium-87.0.4280.66_windows32_client.tar.bz2] from the CEF automated builds
2. Uncompress the tarball file into a folder
3. Compress with UPX (ex: the latest version 3.96w) the file: libcef.dll in the release folder
4. Run the program: "cefclient.exe"

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.96w 32bits
* Host Operating System and version: Windows 10
* Host CPU architecture: 64 bits
* Target Operating System and version: Windows 10
* Target CPU architecture: 32 bits

![2020-12-02 11_31_20-D__DEVS_QTX_qtx optimized_cef_binary_87 1 11+g8bb7705+chromium-87 0 4280 66_wind](https://user-images.githubusercontent.com/41461324/100813568-b0718a80-3493-11eb-9860-b6aa663a4087.png)
![2020-12-02 11_35_44-Release](https://user-images.githubusercontent.com/41461324/100813571-b23b4e00-3493-11eb-9ab1-b3d9092bb5be.png)

**Comment by jreiser** [comment]
In the `devel` branch of UPX which is current and contains many fixes, the file libcef.dll is diagnosed as `libcef.dll: CantPackException: CFGuard enabled PE files are not supported`.  Re-build without CFGuard, then re-run UPX.

**Comment by soinalastudio** [comment]
Okay, thank you. I will try.

**Comment by necros2k7** [comment]
close issue rebuild is not UPX related
