### ISSUE TITLE
Help does not contain lzma

### ISSUE THREAD

**Issue by TrueCat17** [upx/upx#439]
## What's the problem (or question)?

UPX supports param "--lzma", but "--help" does not info about it

## What should have happened?

Out from  
`upx --help | grep lzma`  
should be not empty

* UPX version used (`upx --version`): 3.96 (lzma works, so I think, that UPX built with support lzma)
* Debian, x86_64

**Comment by jreiser** [comment]
Fixed in a46fd4f04087c9cabce73b4200b0bccdbf8a7ee5 on `devel` branch.
