### ISSUE TITLE
UPX devel fails to build on macOS 11 (Big Sur)

### ISSUE THREAD

**Issue by fxcoudert** [upx/upx#440]
## What's the problem (or question)?

Compiling UPX devel on macOS 11 Big Sur fails:

```
==> make all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src all
Updating .depend
In file included from c_file.cpp:29:
./conf.h:37:6: error: "C++ 14 is required"
#    error "C++ 14 is required"
     ^
1 error generated.
```

(there are many more `C++ 14 is required` messages)

The system compiler does not have C++14 by default. `-std=c++14` needs to be passed.

## What should have happened?
The software should compile without having to specify extra flags.

## How can we reproduce the issue?
1. clone https://github.com/upx/upx.git
2. `make all`

## Please tell us details about your environment.

* UPX version used (`upx --version`): `HEAD is now at e4d6eaf Tweak unoptimizeReloc again`
* Host Operating System and version: macOS 11.0.1
* Host CPU architecture: x86_64
* Target Operating System and version: macOS 11.0.1
* Target CPU architecture: x86_64

**Comment by fxcoudert** [comment]
If I force it to use the right C++14 flags, I get more errors:

```
fx@rmeur src % make all CXXFLAGS=-std=c++14 -j1
clang++ '-DUPX_VERSION_GITREV="e4d6eafb9ef7"' -std=c++14 -o c_file.o -c c_file.cpp
In file included from c_file.cpp:29:
./conf.h:72:1: error: static_assert failed due to requirement '127 == 255' "CHAR_MAX == 255"
ACC_COMPILE_TIME_ASSERT_HEADER(CHAR_MAX == 255) // -funsigned-char
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./miniacc.h:2079:48: note: expanded from macro 'ACC_COMPILE_TIME_ASSERT_HEADER'
#    define ACC_COMPILE_TIME_ASSERT_HEADER(e)  static_assert(e, #e);
                                               ^             ~
In file included from c_file.cpp:29:
./conf.h:73:1: error: static_assert failed due to requirement '(char)(-1) > 0' "(char)(-1) > 0"
ACC_COMPILE_TIME_ASSERT_HEADER((char)(-1) > 0) // -funsigned-char
^                              ~~~~~~~~~~~~~~
./miniacc.h:2079:48: note: expanded from macro 'ACC_COMPILE_TIME_ASSERT_HEADER'
#    define ACC_COMPILE_TIME_ASSERT_HEADER(e)  static_assert(e, #e);
                                               ^             ~
2 errors generated.
```

**Comment by fxcoudert** [comment]
```
rmeur /tmp $ cat toto.h    
__cplusplus
rmeur /tmp $ clang++ toto.h -E
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
# 1 "toto.h"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 379 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "toto.h" 2
199711L
```

**Comment by jreiser** [comment]
Fixed in 648fa30f22ae195f591210d7d2fa264e69b233ae  on `devel` branch.

**Comment by jreiser** [comment]
@fxcoudert  The Makefile invokes the compiler with `CXXFLAGS += -funsigned-char` which should make the assertion `ACC_COMPILE_TIME_ASSERT_HEADER(CHAR_MAX == 255)` correct, according to `<limits.h>`.  If clang++ does not honor `-funsigned-char` then clang++ should complain.  Did clang ++complain?

**Comment by fxcoudert** [comment]
I compiled with `make CXXFLAGS=-std=c++14` but it seems instead of appending to `CXXFLAGS`, it overrode your `CXXFLAGS += -funsigned-char`. I don't know why, but don't feel the need to investigate since you fixed the Makefile and I can confirm it builds.

The resulting binary does not run well on Big Sur, as was already reported: https://github.com/upx/upx/issues/424#issuecomment-743396317

**Comment by markus-oberhumer** [comment]
Please use something like `make CXX="clang++ -std=c++14"` .
