### ISSUE TITLE
upx -5+ not finish for big file 180M,go build version 1.15.3+

### ISSUE THREAD

**Issue by mj520** [upx/upx#442]
## How can we reproduce the issue?

1.download https://releases.hashicorp.com/vault/1.6.0/vault_1.6.0_windows_amd64.zip
2.upx -5 vault.exe 
c:\Users\mj520\Desktop>upx -5 vault.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96w       Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
Compressing vault.exe [win64/pe, NRV2E/5]
[*******************************.................................]   24.9%  /
3.upx -1 ~ -4 ok,5+ slow not finish ,file size 180M

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
When I compress using the official release upx-3.96-amd64_linux/upx then I see the "infinite loop".  When I checkout the source code at git tag v3.96 and re-build and compress on amd64, then I get complete output in the usual amount of time.  Supposedly the difference is NRV versus UCL.

**Comment by jreiser** [comment]
Actual timing: 
```
$ time ../../upx-3.96-amd64_linux/upx -f -o foo -5 vault.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
 189229888 ->  67613504   35.73%    win64/pe     foo                           

Packed 1 file.

real	25m38.553s
user	25m28.191s
sys	0m0.598s
```

```
$ time ../upx.out -f -o foo2 -5 vault.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX git-d7ba31+ Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
 189229888 ->  69877056   36.93%    win64/pe     foo2                          

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.

real	0m10.134s
user	0m9.936s
sys	0m0.182s
```

**Comment by mj520** [comment]
try exec  time ../upx.out -f -o foo9 -9 vault.exe  ...

**Comment by jreiser** [comment]
```
real	1m26.564s   189229888 ->  67114304   35.47%   -9   tip of `devel`
real	43m1.903s   189229888 ->  62640960   33.10%   -9   upx-3.96-amd64_linux
real	1m23.979s   189229888 ->  53448512   28.25%   -9 --lzma   upx-3.96-amd64_linux  (slower to invoke)
```

**Comment by mj520** [comment]
c:\Users\mj520\Downloads\upx-3.96-win64>ls -l
total 185397
-rw-r--r-- 1 mj520 None      1750 Jan 23  2020 BUGS
-rw-r--r-- 1 mj520 None     18092 Jan 23  2020 COPYING
-rw-r--r-- 1 mj520 None      5448 Jan 23  2020 LICENSE
-rw-r--r-- 1 mj520 None     23062 Jan 23  2020 NEWS
-rw-r--r-- 1 mj520 None      4587 Jan 23  2020 README
-rw-r--r-- 1 mj520 None       800 Jan 23  2020 README.1ST
-rw-r--r-- 1 mj520 None      2198 Jan 23  2020 THANKS
-rw-r--r-- 1 mj520 None     43086 Jan 23  2020 upx.1
-rw-r--r-- 1 mj520 None     37244 Jan 23  2020 upx.doc
-rwxr-xr-x 1 mj520 None    412672 Jan 23  2020 upx.exe
-rw-r--r-- 1 mj520 None     39181 Jan 23  2020 upx.html
-rwxr-xr-x 1 mj520 None 189229888 Nov 11 03:06 vault.exe
-rwxr-xr-x 1 mj520 None       128 Dec 22 10:41 vault.upx

c:\Users\mj520\Downloads\upx-3.96-win64> .\upx.exe -f -o foo  -9 .\vault.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96w       Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
Compressing .\vault.exe [win64/pe, NRV2E/9]
[*******************************.................................]   21.2%  |

for windows10 2004，not finish，Usually -1 is good enough

**Comment by markus-oberhumer** [comment]
It does finish, but it takes very long. Use `upx -4` or `upx --lzma` if you don't want to wait.
