### ISSUE TITLE
upx not work for aarch64  build by golang ?

### ISSUE THREAD

**Issue by oldthreefeng** [upx/upx#443]
## What's the problem (or question)?

use upx then the binary not work  in aarch64  env.

## Do you have an idea for a solution?

no

## How can we reproduce the issue?

0. `git clone https://github.com/fanux/sealos `
1. build original  arm64 binary  like.  `GOARCH=arm64  go build -o sealos-arm64  main.go`
2. use upx to upx.   `upx  sealos-arm64`
3. use in aarch64 cpu machine.  `sealos-arm64  version` has no output.
4. anyway,  there has no problem with  amd64 . 

## Please tell us details about your environment.

my build log : https://github.com/oldthreefeng/sealos/runs/1576178878?check_suite_focus=true
* UPX version used (`upx --version`):
upx-ucl is already the newest version (3.94-4).
* Host Operating System and version:
Ubuntu18.04 github action machine.
* Host CPU architecture:
amd64
* Target Operating System and version:
arm64 centos7.6
* Target CPU architecture:
arm64

**Comment by fayep** [comment]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: object: /Users/faye/src/docker/docker-darwin-arm64 malformed object (load command 4 cmdsize not a multiple of 8)

**Comment by jreiser** [comment]
@fayep  Where is the requirement for code signing stated and/or enforced?  I have run many many unsigned ELF64 binaries, both as-compiled and compressed by UPX, without code signing on various Linux systems: Fedora, Debian, PiOS.

**Comment by fayep** [comment]
Apologies, it is a requirement for Darwin aarch64, apologies.

**Comment by jreiser** [comment]
@oldthreefeng   The tip of `devel` branch works for me:
```
$ uname -a
Linux Unknown.domain 5.9.14-100.fc32.aarch64 #1 SMP Fri Dec 11 14:02:34 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
$ ls -l sealos-arm64.upx
-rwxrwxr-x.  1 user group 24530980 Dec 20 14:41 sealos-arm64.upx
$ readelf --segments sealos-arm64.upx

Elf file type is EXEC (Executable file)
Entry point 0xb9c9cc
There are 3 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000010000 0x0000000000010000
                 0x0000000000b8d496 0x0000000000b8d496  R E    0x10000
  LOAD           0x0000000000000000 0x0000000000ba0000 0x0000000000ba0000
                 0x0000000000000000 0x00000000021f1368  RW     0x10000
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x8
$ ./sealos-arm64.upx
A longer description that spans multiple lines and likely contains
examples and usage of using your application. For example:

Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.

Usage:
  sealos [command]

Available Commands:
  cert        generate certs
  clean       Simplest way to clean your kubernets HA cluster
  cloud       sealos on cloud
  completion  Output shell completion code for the specified shell (bash or zsh)
  config      print config template to console
  delete      delete kubernetes apps installled by sealos..
  etcd        Simplest way to snapshot/restore your kubernets etcd
  exec        support exec cmd or copy file by Label/nodes 
  help        Help about any command
  init        Simplest way to init your kubernets HA cluster
  install     install kubernetes apps, like dashboard prometheus ..
  ipvs        sealos create or care local ipvs lb
  join        Simplest way to join your kubernets HA cluster
  route       set default route gateway
  upgrade     upgrade your kubernetes version by sealos
  version     show sealos version

Flags:
      --config string   config file (default is $HOME/.sealos/config.yaml)
  -h, --help            help for sealos
      --info            logger ture for Info, false for Debug

Use "sealos [command] --help" for more information about a command.
$ 
```

**Comment by oldthreefeng** [comment]
@jreiser  thanks for your work!!.   you may build the `sealos-arm64`  in `aarch64 GNU/Linux`? 

The problem is that i build it in github actions whinch has no aarch64 mahince.  can this cause the problem?

**Comment by jreiser** [comment]
@oldthreefeng   You ran upx-3.95, which is really old.  The latest official release is 3.96, which also is old: about one year.  I ran the tip of the `devel` branch.  Automatic builds of most commits to `devel` branch are run as part of "git push".  See https://github.com/upx/upx-automatic-builds .  AppVeyor builds for WIndows; Travis CI builds for Linux and Mac.
Also, the UPX compressor program is completely cross-platform: when built, then the same source code runs on any supported platform, and any instance of the UPX compressor on any platform can compress programs for any target platform.  UPX inspects the header records of each input file, and produces a compressed program for the same hardware and software target as the corresponding input.  In this case I ran the compressor on x86_64 Linux.

**Comment by oldthreefeng** [comment]
great job!!

**Comment by anacrolix** [comment]
I think I'm seeing this issue with a Go binary build for windows amd64. When run on Windows 11 ARM (it's emulated automatically) stuff may be missing in the binary (or there's some kind of corruption).

https://github.com/golang/go/issues/68268
