### ISSUE TITLE
macho/arm64 incorrect executable header after compression

### ISSUE THREAD

**Issue by fayep** [upx/upx#446]
## What's the problem (or question)?

on a darwin/arm64 binary:
`src/upx.out src/upx.out -o upx`
`objdump -m -x upx` returns `error: 'upx': truncated or malformed object (load command 4 cmdsize not a multiple of 8)`
It doesn't seem to matter if code is signed or not.
`src/upx.out -t upx` reports a successful test

## What should have happened?

Headers of properly formed binary should have been printed as they are when you run objdump -m -x src/upx.out.  Ideally code is re-signed (codesign -s -)

## Do you have an idea for a solution?

perhaps pad the compressed cmdsize to ensure it is a multiple of 8? (maybe just ensure that there is a Load command 4 section?)

## How can we reproduce the issue?

1. start with arm64 macho Darwin executable src/upx.out
2. src/upx.out src/upx.out -o ./upx
3. objdump -mx ./upx

## Please tell us details about your environment.

* UPX version used (`upx --version`): UPX git-680ed5+ (fixed ucl includes in Makefile)
* Host Operating System and version: MacOS 11 Apple Silicon
* Host CPU architecture: ARM64
* Target Operating System and version: MacOS 11 Apple Silicon
* Target CPU architecture: ARM64

```diff --cc src/Makefile
index 07273ccb,7351fe65..00000000
--- a/src/Makefile
+++ b/src/Makefile
@@@ -54,8 -47,8 +54,8 @@@ endi
  
  # we need UCL and zlib - you can set envvar UPX_UCLDIR
  ifneq ($(wildcard $(UPX_UCLDIR)/include/ucl/ucl.h),)
 -INCLUDES += -I$(UPX_UCLDIR)/include
 -LIBS += $(addprefix -L,$(dir $(wildcard $(UPX_UCLDIR)/lib/libucl$(libext) $(UPX_UCLDIR)/src/.libs/libucl$(libext))))
 +  INCLUDES += -I$(UPX_UCLDIR)/include
-   LIBS += $(addprefix -L,$(dir $(wildcard $(UPX_UCLDIR)/libucl$(libext) $(UPX_UCLDIR)/src/.libs/libucl$(libext))))
++  LIBS += $(addprefix -L,$(dir $(wildcard $(UPX_UCLDIR)/lib/libucl$(libext) $(UPX_UCLDIR)/src/.libs/libucl$(libext))))
  endif
  LIBS += -lucl -lz
  # LZMA from https://github.com/upx/upx-lzma-sdk
```

**Comment by jreiser** [comment]
The way to get sooner attention on this issue is to upload ("Attach files by ..."), or give a URL, or email an actual file that has the problem. Producing an executable for an Apple silicon (ARM) Mac is much easier for you than for me.  Smaller is better, as long as the problem is present: look at /bin/date, /bin/who, /bin/ls, etc.  Compress using zip or gzip before transferring.

**Comment by jreiser** [comment]
The above commit on `devel` branch fixes the immediate complaint, but there is more work to do for the typical Mach_FAT file that involves M1 and X86_64.

**Comment by stohn** [comment]
@jreiser I tried the above commit but I'm still unable to compress any executable on ARM64 (Mac Silicon, MacOS 11.2.1).

Like @fayep I also tried to compress the upx executable itself. When you try to run the compressed executable it will fail with the infamous "killed" message.

This is not a problem of universal or FAT binary (I tested with single ARM64 binary only)

Steps to reproduce:
- clone this repository and built the latest upx from source (51f69a2).
- compress upx with itself: 
```
% src/upx.out src/upx.out -o upx.comp
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-51f69a  Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   2002628 ->    466960   23.32%   macho/arm64   upx.comp                      

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
```
- test upx compression:
```
% src/upx.out upx.comp -t           
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-51f69a  Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

testing upx.comp [OK]

Tested 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
```
- try to execute the compressed upx:
```
% ./upx.comp
zsh: killed     ./upx.comp
```
- just to be sure code sign it:
```
% codesign -s - upx.comp
```
- try to execute the codesigned + compressed upx:
```
% ./upx.comp
zsh: killed     ./upx.comp
```

More information about original and compressed executables:

file:
```
% file src/upx.out
src/upx.out: Mach-O 64-bit executable arm64
```

```
% file upx.comp
upx.comp: Mach-O 64-bit executable arm64
```

otool:
```
% otool -hl upx.out  

src/upx.out:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777228          0  0x00           2    19       1960 0x00218085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __PAGEZERO
   vmaddr 0x0000000000000000
   vmsize 0x0000000100000000
  fileoff 0
 filesize 0
  maxprot 0x00000000
 initprot 0x00000000
   nsects 0
    flags 0x0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 632
  segname __TEXT
   vmaddr 0x0000000100000000
   vmsize 0x0000000000194000
  fileoff 0
 filesize 1654784
  maxprot 0x00000005
 initprot 0x00000005
   nsects 7
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000100002c64
      size 0x000000000007ec78
    offset 11364
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x00000001000818dc
      size 0x00000000000004d4
    offset 530652
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 12 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x0000000100081db0
      size 0x00000000000003fc
    offset 531888
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x00000001000821ac
      size 0x00000000000095a2
    offset 532908
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x000000010008b750
      size 0x0000000000105158
    offset 571216
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __gcc_except_tab
   segname __TEXT
      addr 0x00000001001908a8
      size 0x00000000000021e4
    offset 1640616
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x0000000100192a8c
      size 0x0000000000001570
    offset 1649292
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 312
  segname __DATA_CONST
   vmaddr 0x0000000100194000
   vmsize 0x0000000000010000
  fileoff 1654784
 filesize 65536
  maxprot 0x00000003
 initprot 0x00000003
   nsects 3
    flags 0x10
Section
  sectname __got
   segname __DATA_CONST
      addr 0x0000000100194000
      size 0x0000000000000240
    offset 1654784
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 103 (index into indirect symbol table)
 reserved2 0
Section
  sectname __mod_init_func
   segname __DATA_CONST
      addr 0x0000000100194240
      size 0x0000000000000008
    offset 1655360
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000009
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __DATA_CONST
      addr 0x0000000100194248
      size 0x000000000000d9f0
    offset 1655368
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 3
      cmd LC_SEGMENT_64
  cmdsize 392
  segname __DATA
   vmaddr 0x00000001001a4000
   vmsize 0x0000000000004000
  fileoff 1720320
 filesize 16384
  maxprot 0x00000003
 initprot 0x00000003
   nsects 4
    flags 0x0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x00000001001a4000
      size 0x0000000000000338
    offset 1720320
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 175 (index into indirect symbol table)
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x00000001001a4338
      size 0x0000000000000698
    offset 1721144
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __common
   segname __DATA
      addr 0x00000001001a49d0
      size 0x000000000000145c
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x00000001001a5e30
      size 0x0000000000000dc7
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 4
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x00000001001a8000
   vmsize 0x0000000000044000
  fileoff 1736704
 filesize 265924
  maxprot 0x00000001
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 5
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 1736704
    rebase_size 984
       bind_off 1737688
      bind_size 1032
  weak_bind_off 1738720
 weak_bind_size 12744
  lazy_bind_off 1751464
 lazy_bind_size 1408
     export_off 1752872
    export_size 53680
Load command 6
     cmd LC_SYMTAB
 cmdsize 24
  symoff 1809656
   nsyms 3396
  stroff 1865104
 strsize 121848
Load command 7
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 1547
     iextdefsym 1547
     nextdefsym 1747
      iundefsym 3294
      nundefsym 102
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 1863992
  nindirectsyms 278
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 8
          cmd LC_LOAD_DYLINKER
      cmdsize 32
         name /usr/lib/dyld (offset 12)
Load command 9
     cmd LC_UUID
 cmdsize 24
    uuid 082B2C03-F03E-3F42-8182-DC07CE7CCB8B
Load command 10
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 11.0
      sdk 11.1
   ntools 1
     tool 3
  version 609.8
Load command 11
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 12
       cmd LC_MAIN
   cmdsize 24
  entryoff 124952
 stacksize 0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name /usr/lib/libz.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1.2.11
compatibility version 1.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name /usr/lib/libc++.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 904.4.0
compatibility version 1.0.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1292.60.1
compatibility version 1.0.0
Load command 16
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 1806552
 datasize 3104
Load command 17
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 1809656
 datasize 0
Load command 18
      cmd LC_CODE_SIGNATURE
  cmdsize 16
  dataoff 1986960
 datasize 15668
```

```
% otool -hl upx.comp
upx.comp:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777228          0  0x00           2     6        616 0x00218001
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __PAGEZERO
   vmaddr 0x0000000000000000
   vmsize 0x0000000100000000
  fileoff 0
 filesize 0
  maxprot 0x00000000
 initprot 0x00000000
   nsects 0
    flags 0x0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 152
  segname __TEXT
   vmaddr 0x0000000000001000
   vmsize 0x0000000000072000
  fileoff 0
 filesize 466944
  maxprot 0x00000007
 initprot 0x00000005
   nsects 1
    flags 0x0
Section
  sectname upxTEXT
   segname __TEXT
      addr 0x0000000000001418
      size 0x0000000000071be8
    offset 1048
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x0000000000073000
   vmsize 0x0000000000006000
  fileoff 466944
 filesize 24448
  maxprot 0x00000007
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 3
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 4
        cmd LC_UNIXTHREAD
    cmdsize 288
     flavor ARM_THREAD_STATE64
      count ARM_THREAD_STATE64_COUNT
	    x0  0x0000000000000000 x1  0x0000000000000000 x2  0x0000000000000000
	    x3  0x0000000000000000 x4  0x0000000000000000 x5  0x0000000000000000
	    x6  0x0000000000000000 x7  0x0000000000000000 x8  0x0000000000000000
	    x9  0x0000000000000000 x10 0x0000000000000000 x11 0x0000000000000000
	    x12 0x0000000000000000 x13 0x0000000000000000 x14 0x0000000000000000
	    x15 0x0000000000000000 x16 0x0000000000000000 x17 0x0000000000000000
	    x18 0x0000000000000000 x19 0x0000000000000000 x20 0x0000000000000000
	    x21 0x0000000000000000 x22 0x0000000000000000 x23 0x0000000000000000
	    x24 0x0000000000000000 x25 0x0000000000000000 x26 0x0000000000000000
	    x27 0x0000000000000000 x28 0x0000000000000000  fp 0x0000000000000000
	     lr 0x0000000000000000 sp  0x0000000000000000  pc 0x0000000000071be8
	   cpsr 0x00000000
Load command 5
      cmd LC_CODE_SIGNATURE
  cmdsize 16
  dataoff 466960
 datasize 24432
```

Both files attached:
[upx_arm64_orig_comp.zip](https://github.com/upx/upx/files/5996329/upx_arm64_orig_comp.zip)

**Comment by cfstras** [comment]
Full repro below.

```
cat > test.go <<EOF
package main

import "fmt"

func main() {
	fmt.Println("Hello World")
}
EOF

GOOS=darwin GOARCH=arm64 go build -o arm64 test.go
GOOS=darwin GOARCH=amd64 go build -o amd64 test.go

./amd64
# Hello World

./arm64
# Hello World

upx amd64
upx arm64

./amd64
# Hello World

./arm64
[1]    16545 killed     ./arm64
```

```
go version go1.17.2 darwin/arm64

upx 3.96
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
```

The resulting upx'ed binaries are uploaded here: https://gist.github.com/cfstras/3fa6e56401d64be9d7325b1394b159ca

**Comment by jreiser** [comment]
@cfstras There are several things missing from `Full repo`: Which version of `go`?  Which hardware platform for `./amd64` and for `./arm64`?  Which version of MacOS?

**Comment by cfstras** [comment]
All of it was executed on an Apple M1 (MBP 13-inch 2020), with go 1.17.2 (compiled for darwin/arm64) on macOS Monterey 12.0.1 (21A559).
If you need any more files or samples, just let me know :)

**Comment by tomaswarynyca** [comment]
Any solution?

**Comment by jreiser** [comment]
A solution will come sooner if someone will produce (or point to) documentation of the explicit requirements for successful execution.  Trial-and-error is really slow.

**Comment by cfstras** [comment]
I‘m happy to provide any detail you still need for the repro I posted above. What can I help with?

**Comment by cfstras** [comment]
I've tried your branch locally and get the same results.
Trying to run the binary using `lldb` gives:
```
error: Bad executable (or shared library)
```

I've also noticed that the binary built from go is automatically ad-hoc codesigned. The binary produced by upx is not.
I've manually codesigned the compressed variant like this:
```
codesign -f -s - ./arm64.upx
```
But the result is still the same.

I don't know what else to diagnose about this now - My guess is the binary produced by upx is invalid somehow? Also note that I don't know anything about the mach-o file format.

---

Also, I've tried the same with a Hello-World C program. UPX crashes with an error here, and does not produce an output binary:

```
# cat main.c
```
```c
#include <stdio.h>
int main() {
    printf("Hello World\n");
    return 0;
}
```
```bash
# gcc -o arm64c main.c
# ./arm64c
Hello World
# src/upx.out --lzma -f -o arm64c.upx arm64c
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-3594a7  Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx.out: arm64c: CantPackException: bad Mach_command[10]{cmd=0x32, size=0x20}

Packed 0 files.

WARNING: this is an unstable beta version - use for testing only! Really.
# ./arm64c.upx
zsh: no such file or directory: ./arm64c.upx
```

**Comment by jreiser** [comment]
@cfstras  Some small progress has been made in discovering MacOS requirements for format of executable file; see `git log devel` for commit above.

**Comment by dlorenc** [comment]
Thank you for working on this!

**Comment by cfstras** [comment]
Hey, tried out your last code. With `devel`, I get this:
- Go binary `upx.out: arm64: CantPackException: bad Mach_command[6]{cmd=0x32, size=0x18}`
- C binary `upx.out: arm64c: CantPackException: bad Mach_command[10]{cmd=0x32, size=0x20}`

With a merge of `devel` and `jreiser-bigsur`, I can successfully compress the Go binary (still same error on C), but it still gets killed on start (even after codesign). 

For reference, here's how I build:
```bash
# make clean
# LIBRARY_PATH="$LIBRARY_PATH:$(brew --prefix)/lib" CPPFLAGS="-I$(brew --prefix)/include" make
# src/upx.out --lzma -f -o arm64.upx arm64
# codesign -f -s - ./arm64.upx
# ./arm64
[1]    36146 killed     ./arm64.upx
```

**Comment by jreiser** [comment]
@cfstras Yes, merging `devel` into `jreiser-bigsur` (which I just did and `git push`ed) fixes the problem with LC_BUILD_VERSION, which is a variable-size loader_command depending on the `.ntools` field.

More broadly, I am beginning to think that Apple's restrictions on the format of an executable main program for MacOS BigSur, particularly on Apple M1 silicon (aarch64), may require that a compressed program must have a separate DYLINKER.  This addtional "outer" Dylinker would just find the LC_MAIN and jump to it.  This would achieve the effect of LC_UNIXTHREAD but satisfy the MacOS requirement to use _some_ dynamic linker.  The UPX run-time de-compressor will then setup the address space as before, including whatever DYLINKER the original program specifies, and then start _that_ dynamic linker, which will see the same situation as if started directly from the original program before compression.

Trying to "use" /usr/lib/dyld (and thus /usr/lib/libSystem.B.dylib, because dyld requires that there be at least one LC_LOAD_DYLIB) for both the UPX run time de-compressor and the de-compressed program, seems like asking for trouble.  Can /usr/lib/dyld be started twice (once to invoke the UPX run-time de-compressor and then for the de-compressed program)? What if libSystem.B.dylib has static initializer subroutines?  Where is the subroutine API of dyld so that the de-compressed run-time external symbol table can be merged with that of the shared libraries?  How can the C++ "one definition" rule be enforced with respect to the definitions in compressed code?  All of the problems disappear if a separate dynamic linker is used to invoke the UPX run-time de-comrpessor.

However, a separate dynamic linker must be a separate file. The compressed program no longer is 100% standalone. The name of the file must be a literal string in the loader_commands of the compressed program; so, something like "/usr/lib/upx_dyld-XXXXX", or "/Applications/my_app.app/Contents/.../lib/upx_dyld-XXXXX".  Please think about this, and Comment.

**Comment by jreiser** [comment]
Use /opt/upx/dyld because /usr/lib is locked.

**Comment by cfstras** [comment]
What you say makes sense, but due to a complete lack of in-depth understanding on how dynamic loading works in macOS (or any OS), I'm sorry to say I can't help you further with that. Happy to try anything out though ;)
Two things I've found that might be helpful in Apple's guidance are [Addressing Architectural Differences in Your macOS Code
](https://developer.apple.com/documentation/apple-silicon/addressing-architectural-differences-in-your-macos-code)
and [Porting Just-In-Time Compilers to Apple Silicon
](https://developer.apple.com/documentation/apple-silicon/porting-just-in-time-compilers-to-apple-silicon). The latter one mentions specific entitlements necessary for JIT binaries, which might be related to our issue here. There should also be a reference to ABI differences between the platforms, though I can't find that...

**Comment by pcj** [comment]
Any progress here in the thinking here?  A separate file to invoke the compressed binary is obviously suboptimal, but M1 is here to stay, so some solution is desirable.

**Comment by markus-oberhumer** [comment]
Is this issue fixed?

**Comment by jh125486** [comment]
> Is this issue fixed?

I do not believe so.  Building it on an M1 and compressing still results in a broken binary for me.

**Comment by jreiser** [comment]
@jh125486 Please report `exactly` what "broken binary" means.  Does `otool -hl ./my-upx-compressed-binary` complain?  Did you apply the MacOS security ritual specified in https://github.com/upx/upx/issues/434#issuecomment-1064824409?  How does the result not run?  What error code and message output is produced?  Etc.

**Comment by dreampuf** [comment]
@jreiser 
I have the same problem. Upxed binary doesn't work in M1 macosx.
```
$ otool -hl ./cidr_withldflag_sw_upxed
./cidr_withldflag_sw_upxed:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777228          0  0x00           2     4        580 0x00200000
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __PAGEZERO
   vmaddr 0x0000000000000000
   vmsize 0x0000000100000000
  fileoff 0
 filesize 0
  maxprot 0x00000000
 initprot 0x00000000
   nsects 0
    flags 0x0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 152
  segname __TEXT
   vmaddr 0x0000000000001000
   vmsize 0x00000000000a6000
  fileoff 0
 filesize 679936
  maxprot 0x00000007
 initprot 0x00000005
   nsects 1
    flags 0x0
Section
  sectname upxTEXT
   segname __TEXT
      addr 0x0000000000001414
      size 0x00000000000a5bec
    offset 1044
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x00000000000a7000
   vmsize 0x0000000000001000
  fileoff 679936
 filesize 16
  maxprot 0x00000007
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 3
        cmd LC_UNIXTHREAD
    cmdsize 284
     flavor 1 (not ARM_THREAD_STATE64 6)
      count 67 (not ARM_THREAD_STATE64_COUNT 68)
	    x0  0x0000000000000000 x1  0x0000000000000000 x2  0x0000000000000000
	    x3  0x0000000000000000 x4  0x0000000000000000 x5  0x0000000000000000
	    x6  0x0000000000000000 x7  0x0000000000000000 x8  0x0000000000000000
	    x9  0x0000000000000000 x10 0x0000000000000000 x11 0x0000000000000000
	    x12 0x0000000000000000 x13 0x0000000000000000 x14 0x0000000000000000
	    x15 0x0000000000000000 x16 0x0000000000000000 x17 0x0000000000000000
	    x18 0x0000000000000000 x19 0x0000000000000000 x20 0x0000000000000000
	    x21 0x0000000000000000 x22 0x0000000000000000 x23 0x0000000000000000
	    x24 0x0000000000000000 x25 0x0000000000000000 x26 0x0000000000000000
	    x27 0x0000000000000000 x28 0x0000000000000000  fp 0x0000000000000000
	     lr 0x0000000000000000 sp  0x0000000000000000  pc 0x00000000000a5cec
	   cpsr 0x00000000

$ file cidr_withldflag_sw_upxed
cidr_withldflag_sw_upxed: Mach-O 64-bit executable arm64
```

**Comment by jreiser** [comment]
@dreampuf Thank you for the output from `otool`.  But **how** does the binary not work? After "blessing" the compressed output from upx (according to https://github.com/upx/upx/issues/434#issuecomment-1064824409) then what did you try, and what was the result (messages, error code, etc.)?  Give enough info to reproduce the behavior that you experience.

**Comment by pcj** [comment]
Still interested in this.  If I get a few spare cycles will post details.

**Comment by juanariastn** [comment]
@jreiser I'm still having this issue:

**otool output**

```
$ otool -hl yq_darwin_arm64
yq_darwin_arm64:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777228          0  0x00           2     4        580 0x00200000
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __PAGEZERO
   vmaddr 0x0000000000000000
   vmsize 0x0000000100000000
  fileoff 0
 filesize 0
  maxprot 0x00000000
 initprot 0x00000000
   nsects 0
    flags 0x0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 152
  segname __TEXT
   vmaddr 0x0000000000001000
   vmsize 0x00000000006ca000
  fileoff 0
 filesize 7118848
  maxprot 0x00000007
 initprot 0x00000005
   nsects 1
    flags 0x0
Section
  sectname upxTEXT
   segname __TEXT
      addr 0x0000000000001414
      size 0x00000000006c9bec
    offset 1044
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x00000000006cb000
   vmsize 0x0000000000001000
  fileoff 7118848
 filesize 16
  maxprot 0x00000007
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 3
        cmd LC_UNIXTHREAD
    cmdsize 284
     flavor 1 (not ARM_THREAD_STATE64 6)
      count 67 (not ARM_THREAD_STATE64_COUNT 68)
	    x0  0x0000000000000000 x1  0x0000000000000000 x2  0x0000000000000000
	    x3  0x0000000000000000 x4  0x0000000000000000 x5  0x0000000000000000
	    x6  0x0000000000000000 x7  0x0000000000000000 x8  0x0000000000000000
	    x9  0x0000000000000000 x10 0x0000000000000000 x11 0x0000000000000000
	    x12 0x0000000000000000 x13 0x0000000000000000 x14 0x0000000000000000
	    x15 0x0000000000000000 x16 0x0000000000000000 x17 0x0000000000000000
	    x18 0x0000000000000000 x19 0x0000000000000000 x20 0x0000000000000000
	    x21 0x0000000000000000 x22 0x0000000000000000 x23 0x0000000000000000
	    x24 0x0000000000000000 x25 0x0000000000000000 x26 0x0000000000000000
	    x27 0x0000000000000000 x28 0x0000000000000000  fp 0x0000000000000000
	     lr 0x0000000000000000 sp  0x0000000000000000  pc 0x00000000006ca364
	   cpsr 0x00000000
```

**execution output**

```
./yq_darwin_arm64 --version
zsh: killed     ./yq_darwin_arm64 --version
```

**Comment by pcj** [comment]
still relevant, should keep open

**Comment by pcj** [comment]
keep open

**Comment by fayep** [comment]
[hello.zip](https://github.com/upx/upx/files/12411391/hello.zip)
I've uploaded a small test with debug symbols and the compressed and uncompressed executables - the test is so small that the compressed is larger than the original after re-signing adhoc.

Please let me know if I can provide anything else helpful?

**Comment by jreiser** [comment]
> the compressed is larger than the original after re-signing adhoc. 

For MacOS on arm64, the pagesize is 16KiB, and hardware access protection (Read, Write, Execute) is on a page boundary that is also an offset boundary in the file.  So if you have one TEXT page and one DATA page, then that's 32KiB.  The Writeable DATA page must be separate from the noWrite TEXT, else UPX would have to subsume all relocation that is performed by the dynamic linker, which would be a waste of time, space, and maintenance liability. Mach-O demands that the LINKEDIT segment start on a page boundary, so it cannot overlap any part of DATA.  So right there is 32KiB plus at least a little.  The `hello` is 33666 bytes, the `compressed` is 35120, and the de-compressor accounts for around 1.5KiB.  There is not much to complain about.

**Comment by fathonix** [comment]
keep open

**Comment by tomaswarynyca** [comment]
keep open
