### ISSUE TITLE
Add custom decompression code in UPX

### ISSUE THREAD

**Issue by yalisandsoso** [upx/upx#449]
I want to use custom compression method instead of the built-in compression algorithms. What should I do? Help me,please!!!!!!

**Comment by fzcode** [comment]
Hi I am adding some custom cipher code before compress  ， I think we should talk about this and share something。 cls10010@aliyun.com

**Comment by jreiser** [comment]
@yalisandsoso  This Issue is inappropriate here unless the custom compression method is compatible with GPLv2+; see the LICENSE file in the top-level of UPX source.
What is the custom compression method?  The only known reasonable candidate is zstd, which has issues with large size of its code.

**Comment by yalisandsoso** [comment]
> Hi I am adding some custom cipher code before compress ， I think we should talk about this and share something。 [cls10010@aliyun.com](mailto:cls10010@aliyun.com)

How did you do that? Did you modify the assembly code?

**Comment by yalisandsoso** [comment]
> @yalisandsoso This Issue is inappropriate here unless the custom compression method is compatible with GPLv2+; see the LICENSE file in the top-level of UPX source.
> What is the custom compression method? The only known reasonable candidate is zstd, which has issues with large size of its code.

Thank you for your reply. I now know that I may need to modify the assembly code to do this.

**Comment by jreiser** [comment]
This is not an issue with UPX.  Closing.
