### ISSUE TITLE
Sometimes Python app crash on startup and sometimes it launches fine

### ISSUE THREAD

**Issue by 0xB00B** [upx/upx#452]
## What's the problem (or question)?
I made a program in Python + PyQt5 (packed in one directory mode with pyinstaller as 80mb folder). Its final size after manual optimisations is 32mb.

So to further reduce size, i used upx on 3 of the large qt DLLs

After compresssing 1 dll, my app crashes 30% of time on startup.

After compresssing 2 more DLLs, the app crashes 95% of time on startup but 5% of time it launches normally

*Edit* : I tried upx on all other DLL files and pyd file, program is still working (although a little slower than before). That random crash issue happens only with those 3 QT Dlls
## What should have happened?
The app should have launched normally as if DLLs were never Compressed
## Do you have an idea for a solution?
I suspect this is happening because the exe made by pyinstaller is not waiting long enough for DLLs to decompress. It wants them instantly but upx is taking time to decompress.

I think the app will work fine on high spec PC's but crash on low spec PC's
I even tried a lower compression preset, still same.
## How can we reproduce the issue?
1. Use pyinstaller on any PyQt5 app (one directory mode)
2. Use upx on QtCore.dll, QtWidgets.dll and QtGui.dll and other applicable DLLs.
3. Run the app now a few times
4. Sometimes it launches successfuly and sometimes it crashes.

## Please tell us details about your environment.
* UPX version used (`upx --version`): 1.94w
* Host Operating System and version: Windows 10 Pro 64-bit (version 2009)
* Host CPU architecture: x86_64
* Target Operating System and version: Windows 10 32bit and 64bit
* Target CPU architecture: x86 and x86_64
* UPX commad used to compress : `upx.exe -9 -k -f -lzma "path to DLL"`

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") or give the URL of a .zip of the actual binary files (.dll and .exe) which sometimes fail.

**Comment by Tanishq-Banyal** [comment]
Here is a self extracting archive of my PyQt5 app :- (dlls not compressed)
https://usersdrive.com/t1ik79c2nx11.html

List of dlls that randomly fail :-
QtCore.dll
QtWidgets.dll
QtGui.dll

**Comment by ewerybody** [comment]
Hey @Tanishq-Banyal: I was just looking over this and have a similar setup: I strip the PyInstaller assembly from lots of unneeded things and get my 7z archive down to 17mb compressed. Uncompressed 65mb. Where there is "only" 41mb of PySide2 stuff. [My package build scripts](https://github.com/ewerybody/a2/tree/master/lib/batches/build) ... are a bit of a mess ... the cleanup happens in [finish_package.py](https://github.com/ewerybody/a2/blob/master/lib/batches/build/finish_package.py#L259) Maybe this is something for you too? 🤷‍♀️ sorry for side tracking this.

**Comment by Tanishq-Banyal** [comment]
> Hey @Tanishq-Banyal: I was just looking over this and have a similar setup: I strip the PyInstaller assembly from lots of unneeded things and get my 7z archive down to 17mb compressed. Uncompressed 65mb. Where there is "only" 41mb of PySide2 stuff. [My package build scripts](https://github.com/ewerybody/a2/tree/master/lib/batches/build) ... are a bit of a mess ... the cleanup happens in [finish_package.py](https://github.com/ewerybody/a2/blob/master/lib/batches/build/finish_package.py#L259) Maybe this is something for you too? 🤷‍♀️ sorry for side tracking this.

I can already do that manually
I managed to bring app from 80mb to 32mb

But i wanted even smaller, so i used upx on pyd and dll files.

The size is now 15mb but those 3 dlls crash randomly. So without compresssing DLLs, the size is 22mb

For distribution i just create a 7zip archive , then it becomes 10mb

**Comment by ewerybody** [comment]
impressive! Which Qt dlls did you manage to upx compress? can you list them?

And ... upx compressing may result in antivirus heuristics complaining huh? (Thats actually the reason I kept from using it to compress my executables so far.) did you deal with that?

**Comment by Tanishq-Banyal** [comment]
> impressive! Which Qt dlls did you manage to upx compress? can you list them?
> 
> And ... upx compressing may result in antivirus heuristics complaining huh? (Thats actually the reason I kept from using it to compress my executables so far.) did you deal with that?

I use windows defender. And its pretty cool with UPX. Never got any warning.

First deleted useless qt DLLs.
Then i went to PyQt5 folder and compressed all .pyd files with upx.

Only non compressible DLLs are these :-
https://github.com/upx/upx/issues/452#issuecomment-761583385
