### ISSUE TITLE
Package is deleted automatically

### ISSUE THREAD

**Issue by TheGamingCoderNoob** [upx/upx#453]
## What's the problem (or question)?
EXEs compressed by UPX are automatically deleted by Norton 360 as a "high risk" virus.

## What should have happened?
It should have not done this.

## Do you have an idea for a solution?
Make the code less malware-like

## How can we reproduce the issue?

1. Paste this into a c++ file in Visual studio: `#include<iostream>
#include<fstream>
#include<string>
std::string fn;
std::string ln;
int main() {
	std::cout << "(use #end to close and save) Pick file name: ";
	std::cin >> fn;
	std::ofstream fp;
	fp.open(fn);
	while (true) {
		std::getline(std::cin, ln);
		if (ln == "#end") {
			fp.close();
			return 0;
		}
		fp << ln << std::endl;
	}
}`
2. Compile.
3.Install Norton 360 Antivirus.
4. Compress output file of code.

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.96
* Host Operating System and version:  Microsoft Windows 10 Home build 19042
* Host CPU architecture: x64
* Target Operating System and version: Same as earlier
* Target CPU architecture: also x64

**Comment by jreiser** [comment]
Same as pinned Issue https://github.com/upx/upx/issues/437.  Norton requires education; complain to them.  Closing this issue.
