### ISSUE TITLE
Failure to compress windows executables produced with Smaller C

### ISSUE THREAD

**Issue by alexfru** [upx/upx#46]
## What's the problem (or question)?

UPX fails to compress windows executables produced with [Smaller C](https://github.com/alexfru/SmallerC), e.g. [n2f.exe](https://github.com/alexfru/SmallerC/blob/master/v0100/binw/n2f.exe). The output of `upx n2f.exe` is:

>                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2016
UPX 3.92w       Markus Oberhumer, Laszlo Molnar & John Reiser   Dec 11th 2016

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
Assertion failed: f_ptr + f_len <= i_ptr + i_len, file ../../../src/packer.cpp, line 1596

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

## What should have happened?

Compression should probably succeed? Because neither Windows XP x86 nor Windows 7 x86-64 complain about the binaries produced with Smaller C.

## Do you have an idea for a solution?

None at the moment.

## How can we reproduce the issue?

1. Download [n2f.exe](https://github.com/alexfru/SmallerC/blob/master/v0100/binw/n2f.exe)
2. Run `upx n2f.exe`

## Please tell us details about your environment.

* UPX version used (`upx --version`):
> upx 3.92
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Copyright (C) 1996-2016 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2016 Laszlo Molnar
Copyright (C) 2000-2016 John F. Reiser
Copyright (C) 2002-2016 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.

* Operating System and version:
Windows 7

* CPU architecture:
x86-64

**Comment by ml1050** [comment]
This file has invalid header fields (in the optional header: fields code_base and data_base). Not an UPX bug.
