### ISSUE TITLE
unable to debug source code under visual studio 2015

### ISSUE THREAD

**Issue by rancher41** [upx/upx#460]
## How can we reproduce the issue?

1. add debug mode to project configuration manager
2. try to debug; a lot of errors will raise
3. in release mode you wont see any errors

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.96
* Host Operating System and version: windows 8.1
* Host CPU architecture: x64

**Comment by jreiser** [comment]
`try to debug; a lot of errors will raise`  Please exhibit here two or three of the errors that you see.  If the errors can be copy+paste as text, then please put each error into a separate Markdown paragraph (so that the Preview tab shows fixed-width text) by placing a line that contains only three backtick characters (decimal 96, hex 0x60, octal 0120) both before and after the pasted error text.  If the errors can only be seen as graphics then do a screen grab into file(s), and "Attach files by ..." into a Comment.

**Comment by rancher41** [comment]
Error (active)		cannot open source file "ucl/uclconf.h"	upx	c:\upx\upx-3.96\conf.h	142	
Error (active)		the size of an array must be greater than zero	upx	c:\upx\upx-3.96\conf.h	66	
Error (active)		the size of an array must be greater than zero	upx	c:\upx\upx-3.96\conf.h	67	
Error (active)		cannot open source file "ucl/ucl.h"	upx	c:\upx\upx-3.96\conf.h	143	
Error (active)		#error directive: "please upgrade your UCL installation"	upx	c:\upx\upx-3.96\conf.h	145	
Error (active)		not a class or struct name	upx	c:\upx\upx-3.96\conf.h	556	
Error (active)		identifier "ucl_uint" is undefined	upx	c:\upx\upx-3.96\conf.h	608	
Error (active)		class "ucl_compress_config_t" has no member "m_size"	upx	c:\upx\upx-3.96\main.cpp	591	
Error (active)		no instance of overloaded function "getoptvar" matches the argument list	upx	c:\upx\upx-3.96\main.cpp	683	
Error (active)		class "ucl_compress_config_t" has no member "c_flags"	upx	c:\upx\upx-3.96\main.cpp	683	
Error (active)		no instance of overloaded function "getoptvar" matches the argument list	upx	c:\upx\upx-3.96\main.cpp	686	
Error (active)		class "ucl_compress_config_t" has no member "s_level"	upx	c:\upx\upx-3.96\main.cpp	686	
Error (active)		no instance of overloaded function "getoptvar" matches the argument list	upx	c:\upx\upx-3.96\main.cpp	689	
Error (active)		class "ucl_compress_config_t" has no member "h_level"	upx	c:\upx\upx-3.96\main.cpp	689	
Error (active)		no instance of overloaded function "getoptvar" matches the argument list	upx	c:\upx\upx-3.96\main.cpp	692	
Error (active)		class "ucl_compress_config_t" has no member "p_level"	upx	c:\upx\upx-3.96\main.cpp	692	
Error (active)		no instance of overloaded function "getoptvar" matches the argument list	upx	c:\upx\upx-3.96\main.cpp	695	
Error (active)		class "ucl_compress_config_t" has no member "max_offset"	upx	c:\upx\upx-3.96\main.cpp	695	
Error (active)		no instance of overloaded function "getoptvar" matches the argument list	upx	c:\upx\upx-3.96\main.cpp	698	
Error (active)		class "ucl_compress_config_t" has no member "max_match"	upx	c:\upx\upx-3.96\main.cpp	698	
Error (active)		no instance of overloaded function "getoptvar" matches the argument list	upx	c:\upx\upx-3.96\main.cpp	701	
Error (active)		class "ucl_compress_config_t" has no member "m_size"	upx	c:\upx\upx-3.96\main.cpp	701	
Error (active)		identifier "UCL_VERSION" is undefined	upx	c:\upx\upx-3.96\main.cpp	1465	
Error (active)		identifier "ucl_version" is undefined	upx	c:\upx\upx-3.96\main.cpp	1465	
Error	LNK1561	entry point must be defined	zlib	C:\upx\zlib\LINK	1	
Error	LNK1561	entry point must be defined	ucl	C:\upx\ucl\LINK	1	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142	
Error	C2338	CHAR_MAX == 255	upx	c:\upx\upx-3.96\conf.h	66	
Error	C2338	(char)(-1) > 0	upx	c:\upx\upx-3.96\conf.h	67	
Error	C1083	Cannot open include file: 'ucl/uclconf.h': No such file or directory	upx	c:\upx\upx-3.96\conf.h	142

**Comment by rancher41** [comment]
please note that we have access to "ucl/uclconf.h" header in debug mode

**Comment by jreiser** [comment]
This is a problem with VS2015 and/or your installation, and/or its configuration for your project.  The source for UPX supplies none of that.  Besides, apparently it works in release mode.
