### ISSUE TITLE
the progress bar did not move when compress golang qt example widgets.exe

### ISSUE THREAD

**Issue by naowang** [upx/upx#461]
Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96w       Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
Compressing M:\work\code\go\src\github.com\therecipe\examples\basic\widgets\widgets.exe [win64/pe, NRV2E/7]
[***************************.....................................]   20.9%  /

**Comment by jreiser** [comment]
Please give a URL to an actual input file (compressed with zip, etc.).  The filename `M:\work\...` was not enough of a hint for me to find it.

This looks very similar to https://github.com/upx/upx/issues/442#issuecomment-748388872 where the default released NRV compression algorithm inside UPX took 43 minutes, but the compatible UCL development algorithm took 1.5 minutes.  NRV squeezed it 2.5% tighter than UCL.  So let NRV run overnight.  And if you can tolerate a slightly longer startup time when invoking the resulting compressed executable, then try `--lzma` compression.
