### ISSUE TITLE
UPX removes x86_64 architecture from mach-o binary

### ISSUE THREAD

**Issue by yene** [upx/upx#462]
## What's the problem (or question)?
Running upx removes amd64 architecture from mach-o binary.

## What should have happened?
Mach-o binary should contain both arm64 and amd64

## Do you have an idea for a solution?
No

## How can we reproduce the issue?
```
go install github.com/randall77/makefat@latest
GOOS=darwin GOARCH=amd64 go build -o binary-macos-amd64
GOOS=darwin GOARCH=arm64 go build -o binary-macos-arm64
makefat binary-macos binary-macos-amd64 binary-macos-arm64
# or lipo -create -output binary-macos binary-macos-amd64 binary-macos-arm64
upx binary-macos
```

## before and after upx
```
$ lipo -archs binary-macos
x86_64 arm64
$ upx binary-macos
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   2059954 ->   1101840   53.49%   macho/arm64   binary-macos-lipo             

Packed 1 file.
$ lipo -archs binary-macos
arm64
```

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.96
* Host Operating System and version: macos
* Host CPU architecture: intel amd
* Target Operating System and version: macOS
* Target CPU architecture: amd64 and arm64

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") or give the URL of an actual file which fails; compress using zip or gzip.
The recipe to reproduce does not work:
```
$ go install github.com/randall77/makefat@latest
can't load package: package github.com/randall77/makefat@latest: cannot use path@version syntax in GOPATH mode
```

**Comment by yene** [comment]
ups sorry

Attached simple hello world mach-o with archs: x86_64, arm64
[binary-macos.zip](https://github.com/upx/upx/files/6018005/binary-macos.zip)

**Comment by jreiser** [comment]
The above commit on `devel` branch fixes the immediate problem: x86_64 architecture is not removed from a MachFAT file that contains x86_64 and arm64.  However, right now successful execution of compressed executable on arm64 is doubtful. A real debug environment for arm64 is due soon.

**Comment by leaanthony** [comment]
Happy to help with testing on arm64 if someone can get me up to speed.

**Comment by leaanthony** [comment]
Can we keep this open please?
