### ISSUE TITLE
std::exception while compressing caddy binary

### ISSUE THREAD

**Issue by ninedraft** [upx/upx#463]
## What's the problem (or question)?

While compressing a binary, UPX emits an InternalError.
```
bash-3.2$ upx --best ~/go/bin/caddy
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
caddy  2/3  [****************************************************]  117.5%  | libc++abi.dylib: terminating with uncaught exception of type InternalError: std::exception
Abort trap: 6
```

## What should have happened?

UPX successfuly compressed the binary.
 
## Do you have an idea for a solution?

No

## How can we reproduce the issue?

1. Download and unpack [caddy.zip](https://github.com/upx/upx/files/6041918/caddy.zip)
2. Run `upx --best ./caddy`

## Please tell us details about your environment.

* UPX version used (`upx --version`):  upx 3.96; UCL data compression library 1.03; zlib data compression library 1.2.11; LZMA SDK version 4.43
* Host Operating System and version: macOS Big Sur 11.2.1
* Host CPU architecture: Intel Core i5 x86-64 
* Target Operating System and version: macOS Big Sur 11.2.1
* Target CPU architecture: Intel Core i5 x86-64

**Comment by jreiser** [comment]
The Abort trap will be fixed.  But the file `caddy` that is inside `caddy.zip` is already packed by UPX.  Compressing it again is sure to be no-op that wastes time: UPX will detect that the "compressed" output is larger than the input, and refuse to compress.  What is the real goal here?

**Comment by ninedraft** [comment]
>  But the file caddy that is inside caddy.zip is already packed by UPX.

Unfortunately, I did not notice this, since I ran the tool from a script. I should have run `upx -l caddy`.
