### ISSUE TITLE
openwrt bug

### ISSUE THREAD

**Issue by dosgo** [upx/upx#464]
upx 3.9.5-3.9.6  openwrt    Stuck 
upx 3.9.4  openwrt    normal

Test code

echo.go
package main
func main(){
 print("test\r\n")
}

build
GOOS="linux"
GOARCH="mipsle"

go build echo.go
upx.exe echo 
![image](https://user-images.githubusercontent.com/9545458/109414550-66df0000-79ee-11eb-9703-544ccb27f0f5.png)

**Comment by jreiser** [comment]
Which version of openwrt, and where can that version be obtained?

**Comment by dosgo** [comment]
https://downloads.openwrt.org/releases/19.07.7/targets/ramips/mt76x8/openwrt-19.07.7-ramips-mt76x8-gl-mt300n-v2-squashfs-sysupgrade.bin   

![image](https://user-images.githubusercontent.com/9545458/109423974-ac1a2680-7a1c-11eb-8639-511476d27659.png)


Other mipele devices will also work, right?

**Comment by dosgo** [comment]
My device does not have FPU, I don't know if it is the reason.
GOMIPS="softfloat"
echo1 is uncompressed, normal.
echo2 is 3.9.6, error.
echo3 is 3.9.4, normal.
[test.zip](https://github.com/upx/upx/files/6057238/test.zip)

**Comment by jreiser** [comment]
What actual physical device is the target (manufacturer, model, revision)?

**Comment by dosgo** [comment]
This device
https://www.gl-inet.com/products/gl-mt300n-v2/
