### ISSUE TITLE
How to understand the performance impact of upx?

### ISSUE THREAD

**Issue by frederikhors** [upx/upx#466]
## What's the problem (or question)?
_Sorry for this rookie question, but I don't know where else to ask._

I am learning Golang and I would like to distribute a small app on devices that do not have much storage. So I'm thinking of using UPX as described here: https://github.com/xaionaro/documentation/blob/master/golang/reduce-binary-size.md#6-compress-the-binary.

However, on that same page it says:

> The binary will be much slower.

I would like to know in what EXACTLY my app can slow down: in use or only at the first start (due to auto-decompression)?

> It will consume more RAM.

What is this increased use of RAM? The weight needed for self-decompression? Example: if my executable is 20MB before compression with UPX and after it is 5MB, will I have that 15MB difference in RAM once I start? That's all?

Thank you for all the work you have done: you are magnificent!

**Comment by jreiser** [comment]
Speed: de-compressing 20MB will take a small fraction of a second.  After that the speed will be identical to executing the never-packed executable from RAM, modulo demand paging (see Space below).  Some environments execute some programs from ROM, which usually is slower than RAM, but not always.
Space: During de-compression the RAM usage is approximately the sum of the compressed and de-compressed sizes.  It used to be just the de-compressed size, but that takes more execution time plus development complexity now that -fPIE must be supported.  After de-compression there is no difference in space.  When de-compression finishes then the in-memory image is identical to the start of a never-compressed image, except that the de-compressed image will tend to have all pages present in RAM (they were just written), while the never-compressed image will have almost no pages present (they will be fetched on demand.)

**Comment by frederikhors** [comment]
> except that the de-compressed image will tend to have all pages present in RAM (they were just written), while the never-compressed image will have almost no pages present (they will be fetched on demand.)

Could this affect or increase performances (on Windows 10 / Linux)?

Thanks a lot for your explanation! Amazing!

**Comment by jreiser** [comment]
`Could this affect or increase performances ...?` It depends on the demand paging behavior of the application.  In the steady state there will be no difference, except possibly for paging performance from writeable paging space instead of ROM.  Why don't you try it?  For something as small as 20MB you might not be able to measure the difference reliably.  And especially for a golang program, where the compression tends to be high because of no shared libraries, then a short program runtime might even be faster including de-compression.
