### ISSUE TITLE
is changing upx section name break the license

### ISSUE THREAD

**Issue by budibeta** [upx/upx#468]
i want to prevent users or buyers from reverse engineering

does changing section names using a hex editor violate licenses? even though I use the original / unmodified version of upx when compressing binaries

I want a simple answer, because it is too complicated to read the license because I use a language other than English

thanks

**Comment by jreiser** [comment]
`i want to prevent ... reverse engineering`  This is impossible.  Any attempt can only deter or delay success, not prevent.
 `does changing section names using a hex editor violate licenses?`  No.  But it _might_ make de-compression (`upx -d`) fail, which the astute user will recognize as a sign of tampering and/or malware.

**Comment by budibeta** [comment]
i mean prevent reverse engineering from noob people, i know hacker can still decompress

if "changing section names" does not "violate licenses"

does that mean I can legally sell my application, which has been compressed using upx

i need the last answer for my question

**Comment by jreiser** [comment]
The short answer is, "Yes, you can sell your application which has been compressed using UPX,"  but this short answer does not cover all the details.
It would be best to read and understand (or have someone who is familiar with English and software licensing to read and explain to you) the provisions contained in the LICENSE file at the top of the UPX source code tree.  The exact conditions and exceptions really do matter.
