### ISSUE TITLE
'brew install upx' not installing UPX on MacOSx BigSur

### ISSUE THREAD

**Issue by bambouseraie** [upx/upx#469]
## What's the problem (or question)?
I have installed brew and I cannot install upx from brew using "brew install upx" command (my shell is 'zsh') 

## What should have happened?
upx should have installed 

## Do you have an idea for a solution?
I figured it out by finding the solution on the HomeBrew Github (after searching for ages)
https://github.com/Homebrew/discussions/discussions/501

## How can we reproduce the issue?

1 run 'brew install upx --HEAD'

myusername@nameofmycomputer ~ % brew install upx --HEAD
fatal: Could not resolve HEAD to a revision
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "upx".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

or

2 run 'brew install upx'

myusername@nameofmycomputer /usr % brew install upx
Updating Homebrew...
fatal: Could not resolve HEAD to a revision
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "upx".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

## Please tell us details about your environment.
* UPX version used (`upx --version`): whatever brew should give me
* Host Operating System and version: MacOSX BigSur 11.2.1
* Host CPU architecture: 2.2 GHz Dual-Core Intel Core i7
* Target Operating System and version: MacOSX BigSur 11.2.1
* Target CPU architecture: 2.2 GHz Dual-Core Intel Core i7

Solution: run 'git -C $(brew --repo homebrew/core) checkout master'

myusername@nameofmycomputer ~ % git -C $(brew --repo homebrew/core) checkout master
Updating files: 100% (5796/5796), done.
Branch 'master' set up to track remote branch 'master' from 'origin'.
Already on 'master'

Result: now if you run 'brew install upx' 

myusername@nameofmycomputer /usr % brew install upx 
==> Downloading https://homebrew.bintray.com/bottles/upx-3.96_1.big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/5fc54db6b0fb2e8ebfa630d48c893e569e49b5c6795646d8912c447f3b0a1747?response-content-disposition=
######################################################################## 100.0%
==> Pouring upx-3.96_1.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/upx/3.96_1: 8 files, 1.9MB

Solved !

**Comment by jreiser** [comment]
This is a problem with `brew` and `git`; it has nothing to do with `upx`.

**Comment by bambouseraie** [comment]
Agreed 100% but this will be useful for many that struggle with this issue (and I have counted 8 already). 
A lot of people have similar issues (with UPX and with other soft indeed). 
Many users are semi noobs / beginners. Think about those guys, troubleshooting themselves. 
Thanks !
