### ISSUE TITLE
Please release the new version soon

### ISSUE THREAD

**Issue by onvejon** [upx/upx#475]
## What's the problem (or question)?

3.96 compress a program but it can't run . 

## What should have happened?

branches devel fix this

## Do you have an idea for a solution?

Please release the new version soon

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):3.96
* Host Operating System and version: win10
* Host CPU architecture:Intel
* Target Operating System and version:win10
* Target CPU architecture:win10
*

**Comment by markus-oberhumer** [comment]
You can download a build of the current devel versions from GitHub Actions - see https://github.com/upx/upx-automatic-builds for more info.

Otherwise if you encounter a problem please file a new bug report with exact instructions how to reproduce.
