### ISSUE TITLE
CantPackException: bad DT_HASH when trying to compress Rust executable statically linked against musl

### ISSUE THREAD

**Issue by ismail** [upx/upx#476]
## What's the problem (or question)?
upx can't pack a Rust binary, statically compiled with musl:

```
~/g/emu ❯❯❯ upx --best --lzma target/x86_64-unknown-linux-musl/release/emu
Ultimate Packer for eXecutables
Copyright (C) 1996 - 2021
UPX git-c4e002  Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

File size         Ratio      Format      Name
--------------------   ------   -----------   -----------
upx: target/x86_64-unknown-linux-musl/release/emu: CantPackException: bad DT_HASH nbucket=0  len=0x30

Packed 0 files.

WARNING: this is an unstable beta version - use for testing only! Really.
```

## What should have happened?
It should have exited without an error.

## Do you have an idea for a solution?
It works fine if you don't build against x86_64-unknown-linux-musl target.

## How can we reproduce the issue?

1. upx --best --lzma emu

[emu.zip](https://github.com/upx/upx/files/6203409/emu.zip)

## Please tell us details about your environment.

* UPX version used (`upx --version`):
```
upx 4.0.0-git-c4e00265a026
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
```

* Host Operating System and version: openSUSE Tumbleweed
* Host CPU architecture: x86-64
* Target Operating System and version: x86_64-unknown-linux-musl
* Target CPU architecture: x86-64

**Comment by ismail** [comment]
Confirmed fixed, thank you for the amazingly fast fix!

**Comment by cryptoquick** [comment]
I also ran into this error with upx 3.96, afaict, this is the latest release. What fixed it?

**Comment by cryptoquick** [comment]
n/m! I figured it out. For others:

`git clone git@github.com:upx/upx.git`
`cd upx`
`git submodule update --init --recursive`
`make`

The binary is in `./src/upx.out`.

Holy heck this is neat! It took a Rust GUI program (written in Iced) that's 9.8M in size and made it 2.8M!
