### ISSUE TITLE
I try to compress .so with upx, but the call fails after compression.

### ISSUE THREAD

**Issue by sjn939394630** [upx/upx#478]
## What's the problem (or question)?

I try to compress .so with upx, but the call fails after compression.

I wrote a Golang file

> func ContextTest(ctx context.Context, myStruct2 *about_struct.MyStruct){
> msg := ctx.Value("myStruct")
> fmt.Println("request:",msg, myStruct2)
> }

Then build it :

> go build -buildmode=plugin -ldflags="-w -s" soMain.go

Now the generated .so file can be used directly.

Then i want to compress it with UPX

> upx -9 soMain.so

Compile error at the beginning, so I search this issue #410 and upgraded my GNU version to 2.32. Then the compression was successful, But an error is reported when calling.

> fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f6108581000 pc=0x7f6108580ddf]

> runtime stack:
runtime.throw(0x4d51dc, 0x2a)
/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:726 +0x4ac

> goroutine 1 [syscall]:
runtime.cgocall(0x4b49d0, 0xc000041c28, 0xc000010010)
/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000041bf8 sp=0xc000041bc0 pc=0x43921b
plugin._Cfunc_pluginOpen(0xc000070000, 0xc000010010, 0x0)
_cgo_gotypes.go:79 +0x4e fp=0xc000041c28 sp=0xc000041bf8 pc=0x4b320e
plugin.open.func1(0xc000070000, 0x1001, 0x1001, 0xc000010010, 0x770620)
/usr/local/go/src/plugin/plugin_dlopen.go:64 +0x71 fp=0xc000041c58 sp=0xc000041c28 pc=0x4b4431
plugin.open(0x4d040c, 0x9, 0x0, 0xc00002e718, 0x4b2a0b)
/usr/local/go/src/plugin/plugin_dlopen.go:64 +0x345 fp=0xc000041ed0 sp=0xc000041c58 pc=0x4b3685
plugin.Open(...)
/usr/local/go/src/plugin/plugin.go:32
main.main()
/root/go/src/go_study/go_code/about_so/main.go:12 +0x48 fp=0xc000041f88 sp=0xc000041ed0 pc=0x4b46a8
runtime.main()
/usr/local/go/src/runtime/proc.go:204 +0x209 fp=0xc000041fe0 sp=0xc000041f88 pc=0x469989
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000041fe8 sp=0xc000041fe0 pc=0x495d41

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.96
* Host Operating System and version: Red Hat Enterprise Linux Server 7.6 (Maipo)
* Host CPU architecture: amd64
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") or give the URL to an actual file that fails; compress with gzip (or zip) to save space.  The Description is not reproducible.
```
func ContextTest(ctx context.Context, myStruct2 *about_struct.MyStruct){
msg := ctx.Value("myStruct")
fmt.Println("request:",msg, myStruct2)
}
```
```
$ go build -buildmode=plugin -ldflags="-w -s" soMain.go
can't load package: package main: 
soMain.go:1:1: expected 'package', found 'func'

$ go version
go version go1.12.17 linux/amd64
```

**Comment by sjn939394630** [comment]
[go_upx.zip](https://github.com/upx/upx/files/6218911/go_upx.zip)

my go version is
> go version go1.15.7 linux/amd64

**Comment by sjn939394630** [comment]
After compression, directly decompress and report an error.

upx -9 soMain.so

> [root@dwrj60136 about_so]# upx -9 soMain.so
>                        Ultimate Packer for eXecutables
>                           Copyright (C) 1996 - 2020
> UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020
> 
>         File size         Ratio      Format      Name
>    --------------------   ------   -----------   -----------
> soMain.so  6/8  [************************************************]   77.5%  |    3463080 ->   2792324   80.63%   linux/amd64   soMain.so
> 
> Packed 1 file.

upx -d soMain.so
> [root@dwrj60136 about_so]# upx -d soMain.so
>                        Ultimate Packer for eXecutables
>                           Copyright (C) 1996 - 2020
> UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020
> 
>         File size         Ratio      Format      Name
>    --------------------   ------   -----------   -----------
> upx: soMain.so: CantUnpackException: ElfXX_Ehdr corrupted
> 
> Unpacked 1 file: 0 ok, 1 error.
