### ISSUE TITLE
upx.out: libdest.so: CantUnpackException: corrupt b_info

### ISSUE THREAD

**Issue by suyanye1213** [upx/upx#479]
## What's the problem (or question)?
Unpack the error：upx.out: libdest.so: CantUnpackException: corrupt b_info

## What should have happened?

1)  ./upx.out libsrc.so -o libdest.so
UPX 4.0.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021
        File size         Ratio      Format      Name
    572096 ->    252700   44.17%   linux/amd64   libdest.so                    
Packed 1 file.

2) ./upx.out -d libdest.so -o libnewsrc.so
UPX 4.0.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021
        File size         Ratio      Format      Name
**upx.out: libdest.so: CantUnpackException: corrupt b_info**
Unpacked 1 file: 0 ok, 1 error.

3) readelf -d libdest.so
**readelf：error： Reading 0x940 bytes extends past end of file for section headers**
Dynamic section at offset 0x3cd60 contains 28 entries:
    Tag   Type   Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libDHLinuxTimer.so.1]
 0x000000000000000c (INIT)               0x1cc70
 0x000000000000000d (FINI)               0x1ca80
 0x0000000000000019 (INIT_ARRAY)         0x220aa0
 0x000000000000001b (INIT_ARRAYSZ)       24 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x220ab8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x1f0
 0x0000000000000005 (STRTAB)             0x5198
 0x0000000000000006 (SYMTAB)             0x1538
 0x000000000000000a (STRSZ)              54178 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x221000
 0x0000000000000002 (PLTRELSZ)           8304 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x133e8
 0x0000000000000007 (RELA)               0x12b18
 0x0000000000000008 (RELASZ)             2256 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x12a48
 0x000000006fffffff (VERNEEDNUM)         4
 0x000000006ffffff0 (VERSYM)             0x1253a
 0x000000006ffffff9 (RELACOUNT)          5
 0x0000000000000000 (NULL)               0x0

## Please tell us details about your environment.

* UPX version used (`upx --version`):4.43
* Host Operating System and version: ubuntu 16.04
* Host CPU architecture:amd64
* Target Operating System and version: ubuntu 16.04
* Target CPU architecture:amd64

Would you please take a look at this problem for me? Thank you.
Here is the source file:
[libsrc.so.zip](https://github.com/upx/upx/files/6218957/libsrc.so.zip)
Here is the compressed file:
[libdest.so.zip](https://github.com/upx/upx/files/6218959/libdest.so.zip)

**Comment by jsm174** [comment]
Hello.

I'm seeing the same issue with `devel` on a Linux shared object in Ubuntu 18.04.

```
➜  linux-x64 git:(master) ~/upx --version
upx 4.0.0-git-9c9fa84880eb
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
Copyright (C) 1996-2021 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2021 Laszlo Molnar
Copyright (C) 2000-2021 John F. Reiser
Copyright (C) 2002-2021 Jens Medoch
Copyright (C) 1995-2017 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.

➜  linux-x64 git:(master) ~/upx libpinmame.so.3.4 
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-9c9fa8  Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  11973008 ->   9759556   81.51%   linux/amd64   libpinmame.so.3.4             

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.

➜  linux-x64 git:(master) ~/upx -d libpinmame.so.3.4
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-9c9fa8  Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: libpinmame.so.3.4: CantUnpackException: corrupt b_info

Unpacked 1 file: 0 ok, 1 error.

WARNING: this is an unstable beta version - use for testing only! Really.
➜  linux-x64 git:(master) 
```

I tracked this down after wondering why my executable couldn't find the library.

upx 3.94 works fine.

Attached is the library (prior to compression)

[libpinmame.so.3.4.zip](https://github.com/upx/upx/files/6259831/libpinmame.so.3.4.zip)

**Comment by satmandu** [comment]
I'm seeing this too with libraries on linux/i686.  Is there maybe a temporary shell script solution that would extract to a temp file, attempt to decompress, and only overwrite the original with the compressed version if the decompression succeeded without errors?

**Comment by satmandu** [comment]
also seeing this with the main llvm library on x86_64:
```
chronos@localhost /usr/local/lib/crew/packages (master *%|SPARSE<>)$ upx /usr/local/lib64/libLLVM-12.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-8a8284+ Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
libLLVM-12.so  3/5  [********************************************]   18.8%  \  115464856 ->  73632260   63.77%   linux/amd64   libLLVM-12.so

Packed 1 file.
chronos@localhost /usr/local/lib/crew/packages (master *%|SPARSE<>)$ ls -aFl /usr/local/lib64/libLLVM-12.so
-rwxr-xr-x 1 chronos chronos 73632260 Jul 12 03:23 /usr/local/lib64/libLLVM-12.so*
chronos@localhost /usr/local/lib/crew/packages (master *%|SPARSE<>)$ upx -d /usr/local/lib64/libLLVM-12.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-8a8284+ Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: /usr/local/lib64/libLLVM-12.so: CantUnpackException: corrupt b_info

Unpacked 1 file: 0 ok, 1 error.
```

**Comment by jreiser** [comment]
@satmandu  Where did you get `libLLVM-12.so`?  Please state a URL for it, or other means where a copy can be downloaded.

**Comment by satmandu** [comment]
@jreiser Inside here: https://gitlab.com/api/v4/projects/26210301/packages/generic/llvm/12.0.1-1_x86_64/llvm-12.0.1-1-chromeos-x86_64.tpxz
 
That's a [pixz](https://github.com/vasi/pixz) archive. You can extract thus:
`pixz -x usr/local/lib64/libLLVM-12.so < llvm-12.0.1-1-chromeos-x86_64.tpxz | tar x`
