### ISSUE TITLE
"Hello World" go program crashes on i686 with Segmentation Fault

### ISSUE THREAD

**Issue by sebastien-rosset** [upx/upx#480]
## What's the problem (or question)?
A "Hello World" program is written in go and cross-compiled for i386. It is compressed by UPX v3.96. When the program is started, it crashes with "Segmentation Fault".

The SegFault occurs when the program has been compressed with upx v3.95 or v3.96. The same program compiled with the same options and compressed with  upx 3.94 does not crash.

## What should have happened?
The "Hello World" program should output `Hello World`.

## Do you have an idea for a solution?
Not yet, still capturing data to troubleshoot.

## How can we reproduce the issue?
Create the following `main.go` program:
```go
package main
import "fmt"
func main() {
  fmt.Println("Hello world")
}
```
Build, compress and transfer the go program:
```bash
$ CGO_ENABLED=0 GOOS=linux GOARCH=386 go build  -o helloworld main.go
$ upx-3.96-amd64_linux/upx --brute helloworld
$ scp helloworld user@targethost:
```
Execute the program on the target platform:
```bash
./helloworld 
Segmentation fault (core dumped)
```

I thought maybe I could do a git bisect to identify which commit introduced the regression between 3.94 and 3.95, but the instructions to build upx in README.SRC seem outdated.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
The hello world program fails with upx 3.95 and upx 3.96.
The same program works when compressed with upx 3.94.
* Host Operating System and version:
This is the host where the go build occurs:
```bash
$ uname -a
Linux 3e36f1cf3512 5.8.0-48-generic #54~20.04.1-Ubuntu SMP \
      Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
* Host CPU architecture:
```bash
$ arch 
x86_64
```
* Target Operating System and version:
This is the host where the `helloworld` program executes:
```bash
$ uname -a
Linux samc34-A 2.6.27.47 #1 SMP Tue May 8 18:29:06 PDT 2018 i686 i686 i386 GNU/Linux
```
* Target CPU architecture:
```bash
$ arch 
i686
```
* Go version:
$ go version
go version go1.15.10 linux/amd64

Note: if I execute the same compressed program on host system (x86_64), it works.

**Comment by sebastien-rosset** [comment]
Related issues: #478

**Comment by sebastien-rosset** [comment]
```
$ readelf --segments helloworld 

Elf file type is EXEC (Executable file)
Entry point 0x80ae380
There are 3 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x000000 0x08048000 0x08048000 0x67647 0x67647 R E 0x1000
  LOAD           0x000000 0x080b0000 0x080b0000 0x00000 0xd3f18 RW  0x1000
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x4
```

**Comment by jreiser** [comment]
```
Linux samc34-A 2.6.27.47 #1 SMP Tue May 8 18:29:06 PDT 2018 i686 i686 i386 GNU/Linux
```
That's a very old target system: kernel 2.6.27 from year 2008.  Please supply links to Live USB, or DVD installer, or at least the kernel package and enough to boot.

Meanwhile, please run under `strace` and report the last 20 lines.  Also run under a debugger such as gdb until triggering the crash, and report
```
(gdb) x/i $pc   # current instruction
(gdb) x/12i $pc-0x20   # likely surrounding instructions
(gdb) info reg   # all registers
(gdb) info proc   # to get PID process ID
(gdb) shell cat /proc/PID/maps   # current layout of address space
```
The compressed ./helloworld executable that is inside helloworld.zip runs correctly in 32-bit mode under Fedora 30: 
```
Linux f30e64.domain 5.6.13-100.fc30.x86_64 #1 SMP Fri May 15 00:36:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by sebastien-rosset** [comment]
yes I agree it's old. It's an embedded system, so I can't just upgrade it like I would upgrade my linux servers/laptops.
I will run your suggestions. Also, would it be useful to run git bisect? If so, are there updated instructions to build upx?

**Comment by jreiser** [comment]
`git bisect` might be useful.  UPX uses `src/Makefile`; the requirements for source of UCL and lzma SDK can be a minor hurdle.  See also the top-level `README.SRC`.  In practice, the 3.91 release of UPX in 2013 might just work: search the 'net.

**Comment by sebastien-rosset** [comment]
https://github.com/upx/upx/blob/devel/README.SRC#L73 
It looks like a much newer gcc is needed. It states gcc >= 3.3, but with gcc 4.8.5 I get  C++ 14 is required
So it has to be gcc >=6.1
From https://gcc.gnu.org/projects/cxx-status.html:
> GCC has full support for the of the 2014 C++ standard.
> This mode is the default in GCC 6.1 up until GCC 10 

I will change my gcc.

**Comment by sebastien-rosset** [comment]
> `git bisect` might be useful. UPX uses `src/Makefile`; the requirements for source of UCL and lzma SDK can be a minor hurdle. See also the top-level `README.SRC`. In practice, the 3.91 release of UPX in 2013 might just work: search the 'net.

Yes, it works with upx 3.94 too.

**Comment by sebastien-rosset** [comment]
```bash
# strace ./helloworld 
execve("./helloworld", ["./helloworld"], [/* 20 vars */]) = 0
open("/proc/self/exe", O_RDONLY)        = 3
old_mmap(NULL, 423788, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x77f4d000
--- SIGSEGV (Segmentation fault) @ 0 (0) ---
+++ killed by SIGSEGV (core dumped) +++
Process 12000 detached
```

**Comment by sebastien-rosset** [comment]
I did a `git bisect` between v3.94 and v3.95. I was able to build every step by invoking `CXXFLAGS_WERROR= make all`

This is the first commit that introduces the regression:
```
e8de4abe5f86bde43a6fa1ce11acb69e273b406 is the first bad commit
commit 9e8de4abe5f86bde43a6fa1ce11acb69e273b406
Author: John Reiser <jreiser@BitWagon.com>
Date:   Sun Oct 1 15:56:34 2017 -0700

    i386: new stub strategy to avoid problems with early mmap layout
    
    The stub occupies the same region that execve() would create
    for the original progam.  The stub copies everything to a new area,
    erases the original region, replaces it with the de-compressed
    program, and erases the copy of itself via the escape hatch.
    The copy is inexpensive via mmap() of /proc/self/exe.
    
            modified:   stub/src/i386-linux.elf-entry.S
            modified:   stub/src/i386-linux.elf-fold.S
            modified:   stub/src/i386-linux.elf-main.c
    
            modified:   p_lx_elf.cpp
            modified:   p_lx_elf.h
            modified:   p_lx_interp.cpp
            modified:   p_lx_interp.h
            modified:   p_lx_sh.cpp
            modified:   p_lx_sh.h
            modified:   p_mach.cpp
            modified:   p_mach.h
            modified:   p_unix.cpp
            modified:   p_unix.h
            modified:   p_vmlinx.cpp
    
            plus .h, .map, .dump

 src/p_lx_elf.cpp                             |   68 +-
 src/p_lx_elf.h                               |    8 +-
 src/p_lx_interp.cpp                          |    3 +-
 src/p_lx_interp.h                            |    2 +-
 src/p_lx_sh.cpp                              |    5 +-
 src/p_lx_sh.h                                |    2 +-
 src/p_mach.cpp                               |   32 +-
 src/p_mach.h                                 |   10 +-
 src/p_unix.cpp                               |    3 +-
 src/p_unix.h                                 |    2 +-
 src/p_vmlinx.cpp                             |    3 +-
 src/stub/arm.v4a-linux.elf-fold.h            |  178 +-
 src/stub/arm.v5a-linux.elf-fold.h            |  178 +-
 src/stub/armeb.v4a-linux.elf-fold.h          |  178 +-
 src/stub/i386-linux.elf-entry.h              | 3939 +++++++++++++-------------
 src/stub/i386-linux.elf-fold.h               |  227 +-
 src/stub/mips.r3000-linux.elf-fold.h         |  200 +-
 src/stub/mipsel.r3000-linux.elf-fold.h       |  200 +-
 src/stub/powerpc-linux.elf-fold.h            |  270 +-
 src/stub/src/i386-linux.elf-entry.S          |  266 +-
 src/stub/src/i386-linux.elf-fold.S           |   60 +-
 src/stub/src/i386-linux.elf-main.c           |   88 +-
 src/stub/tmp/arm.v4a-linux.elf-fold.map      |   16 +-
 src/stub/tmp/arm.v5a-linux.elf-fold.map      |   16 +-
 src/stub/tmp/armeb.v4a-linux.elf-fold.map    |   16 +-
 src/stub/tmp/i386-linux.elf-entry.bin.dump   |   25 +-
 src/stub/tmp/i386-linux.elf-fold.map         |   26 +-
 src/stub/tmp/mips.r3000-linux.elf-fold.map   |   17 +-
 src/stub/tmp/mipsel.r3000-linux.elf-fold.map |   17 +-
 src/stub/tmp/powerpc-linux.elf-fold.map      |   18 +-
 30 files changed, 2949 insertions(+), 3124 deletions(-)
```

**Comment by jreiser** [comment]
`Yes, it works with upx 3.94 too.` So using upx-3.94 is one method for success.
`i386: new stub strategy to avoid problems with early mmap layout`  No surprise: a new strategy forgot some cases of the old.
`runs correctly in 32-bit mode under [linux kernel] 5.6.13-100.fc30.x86_64` so the bug depends on OS policy.
`[strace] open .. old_mmap .. SIGSEGV`: consult the source in `src/stub/src/i386-linux.elf-entry.S` between the only uses of `__NR_mmap` and `__NR_mprotect`.  Put a breakpoint on the mmap, single step by instruction (`stepi`) to see what happens; step over (not through) the call to `f_exp` if possible.

**Comment by jreiser** [comment]
upx-3.94 works.  The environment of the embedded target system `Linux samc34-A 2.6.27.47` is not available to reproduce the problem for debugging.  Closing this issue.
