### ISSUE TITLE
make stub src 

### ISSUE THREAD

**Issue by heysion** [upx/upx#484]
## What's the problem (or question)?

rebuild stub tmp files 

```code
amd64-linux-gcc-3.4.4 -m64 -nostdinc -MMD -MT amd64-darwin.dylib-entry.h -fno-exceptions -fno-asynchronous-unwind-tables -Wall -W -Wcast-align -Wcast-qual -Wstrict-prototypes -Wwrite-strings -Werror -c src/amd64-darwin.dylib-entry.S -o tmp/amd64-darwin.dylib-entry.bin
make: amd64-linux-gcc-3.4.4: Command not found
```

## What should have happened?

maybe stub/makefile was old , we should upgrade the build tools .

## Do you have an idea for a solution?

replease build tools define at stub/makefile

or please tell me correct build stub method.

## How can we reproduce the issue?

1. cd src/stub
2. make clean   or find . -name "*.dump" -exec rm {} -v \;
3. make
4.

## Please tell us details about your environment.

* v3.94
* debian 10
* arm64 and amd64
* debian10
* arm64 and amd64

**Comment by jreiser** [comment]
On page https://github.com/upx see the link for upx-stubtools: https://github.com/upx/upx-stubtools.  Download `bin-upx-20210104.tar.xz` then
```
$ xzcat bin-upx-20210104.tar.xz | tar tvf - | grep amd64-linux-gcc-3.4.4
lrwxrwxrwx 0/0               0 2005-05-07 05:08 bin-upx-20210104/amd64-linux-gcc-3.4.4 -> packages/amd64-linux/gcc-3.4.3.20050507-glibc-2.3.5/bin/x86_64-unknown-linux-gnu-gcc-3.4.4
-rwxr-xr-x 0/0          162337 2005-05-07 05:08 bin-upx-20210104/packages/amd64-linux/gcc-3.4.3.20050507-glibc-2.3.5/bin/x86_64-unknown-linux-gnu-gcc-3.4.4
```
so you must extract the archive, then put `bin-upx-20210104` in `PATH`.

**Comment by heysion** [comment]
thanks
