### ISSUE TITLE
dlopen failed: cannot find "libdl.so" from verneed[0] in DT_NEEDED

### ISSUE THREAD

**Issue by mrcas** [upx/upx#489]
Here is original so file

[libmylib.zip](https://github.com/upx/upx/files/6290495/libmylib.zip)

Here is packed file

[out.zip](https://github.com/upx/upx/files/6290490/out.zip)

## What's the problem (or question)?
After pack the so. It cannot be loaded. I got the error:

dlopen failed: cannot find "libdl.so" from verneed[0] in DT_NEEDED

Here is the command which i used to pack: (.bat file)

upx.exe %1 --android-shlib -o "output.so"
pause

## What should have happened?
It should be automatically unpacked.

## Do you have an idea for a solution?
No

## How can we reproduce the issue?
I built so file from android studio. Then i packed it and run for testing.

## Please tell us details about your environment.

* UPX version used: 3.96
Tested on Android 11
armeabi-v7a

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") or give the URL of an actual binary executable file which fails.  Compress the uplaod with gzip or zip to save space.

**Comment by mrcas** [comment]
I attached the file. Please check it.

**Comment by mrcas** [comment]
Please help me check.

**Comment by Yangruipis** [comment]
I got the same error with UPX==3.96 and arch==armeabi-v7a

**Comment by dukaixuan** [comment]
I got the same error with UPX==3.96 and arch==armeabi-v7a
