### ISSUE TITLE
Compressed MFC120.DLL with UPX 3.92 doesn't work in Windows XP

### ISSUE THREAD

**Issue by xrayer** [upx/upx#49]
## What's the problem (or question)?

When I compressed the library MFC120.DLL with UPX 3.92 (regardless of used compression level or UPX executable version dos/win32) the result was that application which use this library failed to start with initialization error 0xc0000005. If the library is decompressed and repacked by previous UPX 3.91 (regardless of used compression level or executable version dos/win32) it always works fine. I found yet another DLL causing the same problem - IDRVDLL.DLL from intel BIOS tools. Also it worked packed by previous UPX version. So I'm suspecting there was introduced a bug that may affect even more Win32 DLLs.

## What should have happened?

The application (Flash Loader Demonstrator) should start normally.

## Do you have an idea for a solution?

You can compare and analyze what/how is packed differently on the DLL (file size is the same for same compression level but there are hundreds of thousands different bytes)

## How can we reproduce the issue?

1. download and install STM32 Flash loader demonstrator ( http://www.st.com/en/development-tools/flasher-stm32.html ) or find other app using MFC120.DLL (the library is placed in Windows\system32)
2. run the application (GUI version) to check if starts normally - open a main window
3. compress MFC120.DLL by UPX 3.92 (any other parameter is not needed)
4. run the application again and you'll see just an error window
5. decompress the library by upx -d MFC120.DLL 
6. pack the library with UPX 3.91
7. run the application to check if starts normally - open a main window
Here I uploaded for you a testing package with app and library, it's just ~2,5MB zip file: http://rayer.g6.cz/1tmp/stm32fld.zip

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.92
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Copyright (C) 1996-2016 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2016 Laszlo Molnar
Copyright (C) 2000-2016 John F. Reiser
Copyright (C) 2002-2016 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upxw -L'.
* Operating System and version: Windows XP SP3
* CPU architecture: intel core i7-2600K

**Comment by ml1050** [comment]
Unfortunately your test files do not work on wine. Can you try the devel branch of UPX?

**Comment by xrayer** [comment]
Hi, yes sure I can test it.
Didn't you have any VM with some Windows?
Martin

László Molnár wrote:
> Unfortunately your test files do not work on wine. Can you try the devel 
> branch of UPX?

**Comment by ml1050** [comment]
I used W95 20 years ago. Then I switched to Linux, no looking back.

**Comment by PaulWebSec** [comment]
"We don't need VM software with windows, because they have there own software base"; Second instead of installing Linux on a computable purpose; i.e. machine, just use the (ISO) version of Linux testing the proactive assimilation while making notes with sectors while considering proprietary standards aligning run levels.  'remember (UNIX)'.cap(#)  "version"-venom; Except this 'as it stands presently it is my personal belief that as far as transference in any remote series type operational range from encryption to encryption ("stuff") load storage has to exactly match the extended repository prorated capacity promise unless you never intend to use that extension for anything else again like software upgrades unless the root table source from that primary can be stabilized, but obviously stated prior ("the previous news letter we all no this and I don't like that part, because the itemization roll listing bothers me greatly as far as editorial commentary; however I will be working on that subject as well while performing  other thousand of marvelous act before this evening depending on what my (X) has to think; First and I don't mean. . .) Ultra personally though we will downloading this software right now and then maybe a possible upload Sunday; meaning Monday by the latest depending on its manufacturing rights given to trial; and error then reestablish the quantified results. . . .. .https://github.com/PaulWebSec/1/11/2017

**Comment by PaulWebSec** [comment]
What's the problem (or question)?
When I compressed the library MFC120.DLL with UPX 3.92 (regardless of used compression level or UPX executable version dos/win32) the result was that application which use this library failed to start with initialization error 0xc0000005. If the library is decompressed and repacked by previous UPX 3.91 (regardless of used compression level or executable version dos/win32) it always works fine. I found yet another DLL causing the same problem - IDRVDLL.DLL from intel BIOS tools. Also it worked packed by previous UPX version. So I'm suspecting there was introduced a bug that may affect even more Win32 DLLs.
What should have happened?
The application (Flash Loader Demonstrator) should start normally.
Do you have an idea for a solution?
You can compare and analyze what/how is packed differently on the DLL (file size is the same for same compression level but there are hundreds of thousands different bytes)
How can we reproduce the issue?
download and install STM32 Flash loader demonstrator ( http://www.st.com/en/development-tools/flasher-stm32.html ) or find other app using MFC120.DLL (the library is placed in Windows\system32)
run the application (GUI version) to check if starts normally - open a main window
compress MFC120.DLL by UPX 3.92 (any other parameter is not needed)
run the application again and you'll see just an error window
decompress the library by upx -d MFC120.DLL
pack the library with UPX 3.91
run the application to check if starts normally - open a main window
Here I uploaded for you a testing package with app and library, it's just ~2,5MB zip file: http://rayer.g6.cz/1tmp/stm32fld.zip
Please tell us details about your environment.
UPX version used (upx --version): upx 3.92
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Copyright (C) 1996-2016 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2016 Laszlo Molnar
Copyright (C) 2000-2016 John F. Reiser
Copyright (C) 2002-2016 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upxw -L'.
Operating System and version: Windows XP SP3
CPU architecture: intel core i7-2600K

**Comment by xrayer** [comment]
OK, I understand. I would rather like to jump out of the Window(s) too 
than mess with tiles (so I keep XP ALAP) but at work I need to use many 
scpecific windows-only developers/engineering apps so no way...

Well, I tried to compile upx-master.zip sources from GIT undfer Debial 
Linux but I got some strange error at probably final linking phase:

g++ -O2 -fno-delete-null-pointer-checks -fno-strict-aliasing -fwrapv 
-funsigned-char -Wall -W -Wcast-align -Wcast-qual -Wmissing-declarations 
-Wpointer-arith -Wshadow -Wvla -Wwrite-strings -Werror -o upx.out 
c_file.o c_init.o c_none.o c_screen.o compress.o compress_lzma.o 
compress_ucl.o compress_zlib.o except.o file.o filter.o filteri.o help.o 
lefile.o linker.o main.o mem.o msg.o p_armpe.o p_com.o p_djgpp2.o 
p_elks.o p_exe.o p_lx_elf.o p_lx_exc.o p_lx_interp.o p_lx_sh.o p_mach.o 
p_ps1.o p_sys.o p_tmt.o p_tos.o p_unix.o p_vmlinx.o p_vmlinz.o p_w16ne.o 
p_w32pe.o p_w64pep.o p_wcle.o packer.o packer_c.o packer_f.o packhead.o 
packmast.o pefile.o s_djgpp2.o s_object.o s_vcsa.o s_win32.o snprintf.o 
stdcxx.o ui.o util.o work.o -L/upx-master/src/ucl-1.03/src/.libs/ -lucl -lz
./../src/stub/scripts/check_whitespace.sh ./..
ERROR: binary file detected ./src/c_file.o: ELF4( GCC: (Debian 
4.9.2-10) 4.9.2.symtab.strtab.shstrtab.text.data.bss.comment.note.GNU-stackń˙c_file.cpp4!44,045RRE 
...(binary garbage on console)

Makefile:87: návod pro cíl ,,upx.out" selhal
make: *** [upx.out] Chyba 1
make: *** Maže se soubor ,,upx.out"


László Molnár wrote:

**Comment by ml1050** [comment]
Please try the devel branch.

**Comment by xrayer** [comment]
Sorry, I'm not familiar with Github, how do I checkout the devel branch?
Martin

**Comment by ml1050** [comment]
In the "Code" tab there is a "Branch: master" button. Press it, then select "devel" . Then use the "Clone or download" button.

**Comment by PaulWebSec** [comment]
Problem Introductions:  sytax

**Comment by markus-oberhumer** [comment]
We now have automated builds of the devel branch - please download the current win32 version from

https://github.com/upx/upx-automatic-builds/tree/devel-20170115-051904-acd993-travis/i386-w64-mingw32-gcc-4.6-release

**Comment by xrayer** [comment]
Thanks for ease testing with auto build. I had left sources on linux machine 
at work. Now I tested automated build upx-acd99364e092.exe under windows and 
problem seems to be solved. Compressed MFC120.DLL for flashloader and 
IDRVDLL.DLL, PMXDLL.DLL for intel ME tools are working now. I tested both with 
--best and --lzma compressions. I'm forward on new stable release :)

**Comment by markus-oberhumer** [comment]
Please try the fresh UPX 3.93 release and close this issue if fixed.

**Comment by xrayer** [comment]
I redo my test and all works fine. Thank you. I'm closing the bug.
Martin
