### ISSUE TITLE
"Cannot open self" after upx 

### ISSUE THREAD

**Issue by c02y** [upx/upx#492]
## What's the problem (or question)?

After I use `upx --best --lzma the-bin-file`, the binary is not working anymore

## What should have happened?
It should works fine after that.

## How can we reproduce the issue?

1. Download the zip file and extract https://github.com/cs01/gdbgui/releases/download/v0.14.0.2/gdbgui_linux.zip
2. chmod and `upx --best --lzma xxx`
3. `./gdbgui --version`
4. it fails

```
>> ./gdbgui_0.14.0.2 --version
0.14.0.2
>> upx --best --lzma ./gdbgui_0.14.0.2
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-2dae2a  Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  31932424 ->  31794848   99.57%   linux/amd64   gdbgui_0.14.0.2

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
>> ./gdbgui_0.14.0.2 --version
[2011176] Cannot open self /home/chz/Dotfiles.d/bin/.local/bin/gdbgui_0.14.0.2 or archive /home/chz/Dotfiles.d/bin/.local/bin/gdbgui_0.14.0.2.pkg
```

It is same result if I use `upx 3.96-git-d7ba31cab8ce+` which is the stable version.

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 4.0.0-git-2dae2a39972b
* Host Operating System and version: Manjaro-Linux 21.0.2
* Host CPU architecture: Intel x86_64
* Target Operating System and version: host
* Target CPU architecture: host

**Comment by bitraid** [comment]
From the `31,932,424` bytes of this file, `31,898,997` bytes is the pydata section which holds a zlib compressed archive that the program tries to read from disk. This is expected to fail and there is no sense in compressing this file with upx.

**Comment by c02y** [comment]
Yeah, when I saw `31932424 ->  31794848`, I understand no need to compress this file, but upx should not break it, so I file this issue, maybe this problem should be avoided, like "this file shouldn't be compressed" kind of thing.

**Comment by bitraid** [comment]
It doesn't "break it" - the file tries to read itself from disk and can't find what it expects since the file has changed. There is no way for upx to know that and prevent compressing.

**Comment by c02y** [comment]
OK, I'll close this then. Thanks.

**Comment by jreiser** [comment]
Block data from `readelf --all gdbgui_0.14.0.2`:
```
Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [27] pydata            PROGBITS         0000000000000000  00007a50
       0000000001e6bd75  0000000000000000           0     0     1
```
Notice that the `Flags` are empty and do not contain `A `(Allocated); the `pydata` section is not part of any [PT_]LOAD segment.
```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
                 0x000000000000758c 0x000000000000758c  R E    0x200000
  LOAD           0x0000000000007590 0x0000000000607590 0x0000000000607590
                 0x0000000000000480 0x00000000000107d8  RW     0x200000
```
Notice that the `Offset` region of the second [PT_]LOAD ends at 0x0000000000007590+0x0000000000000480 = 0x7a10, while the `pydata` section begins at Offset 0x7a50 (from `Section headers` above).
```
 Section to Segment mapping:
  Segment Sections...
   00
   01     .interp
   02     .interp .note.ABI-tag .note.gnu.build-id .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .text .fini .rodata .eh_frame_hdr .eh_frame
   03     .init_array .fini_array .jcr .dynamic .got .got.plt .data .bss
   04     .dynamic
   05     .note.ABI-tag .note.gnu.build-id
   06     .eh_frame_hdr
   07
```
Notice that `pydata` is not in the mapping.
If the program wants access to `pydata` then `pydata` should be part of some [PT_]LOAD.  Use a "linker script" to assign global symbolic names to the beginning and end of the Section.  To see an example of a linker script, then invoke `ld --verbose` and note the address assignments to symbols such as 
```
  PROVIDE (__etext = .);
  PROVIDE (_etext = .);
  PROVIDE (etext = .);
  _edata = .; PROVIDE (edata = .);
  _end = .; PROVIDE (end = .);
```

**Comment by bitraid** [comment]
That's because the program doesn't want to load `pydata` in memory - it wants to read it from disk, extract its contents to `/tmp` and run from there. Probably to save RAM, because it has no use for the zlib archive after extraction.
