### ISSUE TITLE
Compression failed, using UPX v3.93-v3.96 but works with v3.91 !

### ISSUE THREAD

**Issue by wosaX** [upx/upx#494]
## What's the problem (or question)?

I´m using  since very, very long. 

Since ~2 years I realized some rare failing in compression, BUT had success with older versions(s) of UPX, mainly with v.3.91!

Instead I get the following error(s):
_"upx: UnrealCommander32.exe: Internal Error: should not happen"_

BTW: this happens on those files WHATEVER additional parameters I´m using: -n, --best, --brute, --all-methods, --ultra-brute.

## What should have happened?

It should have compressed the file instead...! - the more, since UPX v.3.91 DOES the job and results in perfectly running compressed executables.

## How can we reproduce the issue?

1. I can send you (an) example(s) of such file(s) or link to such files:
2.  Both MAIN executables (32- and 64-bit) of "Unreal Commander" by Max Diesel : https://x-diesel.com/?download
3.
4.

## Please tell us details about your environment.

* UPX version used 3.96 (`upx --version`):
* Host Operating System and version: Windows 10 Pro 20H2 (Build 19042.928)
* ( BUT I could reproduce this on other machines with different versions of Window 10 as well!)
* Host CPU architecture: Intel i5-4570
* Target Operating System and version: ~see above: did not compress
* Target CPU architecture:  ~see above: did not compress

**Comment by jreiser** [comment]
Please try the tip of `devel` branch, which works for me on Uncom.exe (64-bit).

**Comment by wosaX** [comment]
Thank you for your hint!

But I just wanted to give a possible hint for improving  (or, maybe regain lost abilities of) the great UPX compressor.

Since I´m´now 70+ of age (- which feels too old to re-start a new attempt in programming and compiling, which I dropped almost 30 yeras ago...) ...
   and
Since the compression of those files works flawless if using UPX v.3.91
I will not get deeper into it.
Just wanted to contibute my small part.

**Comment by bitraid** [comment]
You don't have to compile anything - the above link have directions on how to download the latest builds. For example here you get the latest build as of now: https://github.com/upx/upx/actions/runs/775869948#artifacts

**Comment by wosaX** [comment]
@bitraid

Thank you again for your quick reply and attempt to help !
... but for me neither the version"-msvc-14.2" nor the version "gcc-9" did do the job. :-(

But, as I mentioned before: for me personally this is not any problem! (I always have added in my Windows a working path for my "tools" folder. - And in that path reside, side by side "upx.exe" and "upx391.exe" !  So in case I just ad the number "391" to my repeated command line.)
I´m just wondering what happened after the revision of UPX v.3.91 ?! and wanted to report that "issue" - no more, not less.

Greetings from beautiful and sunny Hamburg!

**Comment by bitraid** [comment]
This is the same case as #69.

**Comment by wosaX** [comment]
Thank you again !

I ONLY can verify for the 32-bit executable to result in a faulty file.
   Even more:
running the decompressed "UnrealCommander32.exe" produced a blue screen on Windows 10, 64 bit !!!

...BUT: for the "UnrealCommander64.exe" this is NOT true: - this file still runs flawless:
**1st try:**
    used UPX, v3.91 for compression and decompression
**2nd try:**
    used UPX, v3.91 for compression and UPX, v3.96 for decompression

Hope that provides some further and maybe useful information...
