### ISSUE TITLE
Unpacked Binary Behaves Differently from Original / Packed Binary

### ISSUE THREAD

**Issue by chezwicker** [upx/upx#495]
## What's the problem (or question)?

My understanding is that `upx -d` does the inverse of what `upx` does. I think I read somewhere (I can' find it any longer) that the original would be restored 1:1.

Now the problem is that not only there is a difference between the original and the packed/unpacked version ([diff.txt](https://github.com/upx/upx/files/6408234/diff.txt): output of `diff <(xxd ex.exe) <(xxd ex-up.exe) > diff.txt`), but the unpacked binary executes differently from the orignal (whereas the packed version executes the same).

## What should have happened?

I would expect the unpacked binary to behave exactly the same as the original and packed version.

## Do you have an idea for a solution?

If this behavior is as designed, then it might be good to clarify in the documentation.

## How can we reproduce the issue?

Tiny repro: [example.zip](https://github.com/upx/upx/files/6408227/example.zip)

1. Run `ex.exe`- it outputs "Sorry, wrong arguments!"
2. Copy `ex.exe` to `ex-p.exe`
3. Pack `ex-p.exe` using `upx ex-p.exe` 
4. Copy `ex-p.exe` to `ex-up.ex`
5. Run `ex-p.exe` - it outputs "Sorry, wrong arguments!"
6. Unpack `ex-up.exe` using `upx -d ex-up.exe``
7. Run `ex-up.exe` - there's no output

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.96
* Host Operating System and version: MacOS 10.15.4
* Host CPU architecture: Intel
* Target Operating System and version: Windows 10 Enterprise 19042.928
* Target CPU architecture: Intel (in a VM)

**Comment by bitraid** [comment]
This bug (unpacking ASLR PE files) has been fixed - [download latest builds](https://github.com/upx/upx-automatic-builds) or use `--strip-relocs=0` with `-d`.

**Comment by chezwicker** [comment]
Thank you! Unfortunately hadn't found the according issue before reporting, sorry ;-(
