### ISSUE TITLE
How to compile in Win

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#499]
make -C src all
make[1]: Entering directory 'Z:/4/src'
"sed" is not executable or batch command
process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile:140: pipe: No such file or directory
process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile:193: pipe: No such file or directory
Makefile:65: /../src/stub/src/c/Makevars.lzma: No such file or directory
make[1]: *** No rule to make target '/../src/stub/src/c/Makevars.lzma'.  Stop.
make[1]: Leaving directory 'Z:/4/src'
make: *** [Makefile:31: all] Error 2

**Comment by jreiser** [comment]
At the top level of the UPX source tree, see `README.SRC`:
```
  - LZMA SDK from https://github.com/upx/upx-lzma-sdk
    When using git run 'git submodule update --init --recursive'.
```
and set environment variable `UPX_LZMADIR=/path/to/lzmaXXX`

**Comment by jreiser** [comment]
Specifically see the bottom of the page https://github.com/upx/upx/actions/runs/823722400
linked from https://github.com/upx/upx/actions
linked from https://github.com/upx/upx-automatic-builds
linked from https://github.com/upx
