### ISSUE TITLE
Unsupport shc file

### ISSUE THREAD

**Issue by jingslunt** [upx/upx#515]
```
appman@DESKTOP-PBHSH3O:~$ shc -rvf test.sh
shc: WARNING!!
   Scripts of length near to (or higher than) the current System limit on
   "maximum size of arguments to EXEC", could comprise its binary execution.
   In the current System the call sysconf(_SC_ARG_MAX) returns 2097152 bytes
   and your script "test.sh" is 2302494 bytes length.
shc shll=bash
shc [-i]=-c
shc [-x]=exec '%s' "$@"
shc [-l]=
shc opts=
shc: cc   test.sh.x.c -o test.sh.x
shc: strip test.sh.x
shc: chmod ug=rwx,o=rx test.sh.x
appman@DESKTOP-PBHSH3O:~$ upx -f test.sh.x -o test
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: test.sh.x: NotCompressibleException

Packed 1 file: 0 ok, 1 error.
```

**Comment by jreiser** [comment]
Please upload ("Attach files by ..."), give the URL, or email an actual input file which fails, such as the test.sh.x of the Description.  Compress with gzip or zip to reduce transfer size.

**Comment by jingslunt** [comment]
##### SHC: transfer linux shell script to c script
>install shc command
```
#ubuntu
sudo add-apt-repository ppa:neurobin/ppa
sudo apt-get update
sudo apt-get install shc
```

- Attach file
[Google'Drive](https://drive.google.com/file/d/1U7dTav4GqnOwN6NauYZPutgGXG_kE98d/view?usp=sharing)

**Comment by jreiser** [comment]
Most of the file `test.sh.x` already has  been compressed by some other tool such as gzip.  So when upx searches for repeated substrings to use as the basis for compression, then the substrings that upx finds are so nearly equi-distributed that the size reduction that can be obtained is very small, and not worth the effort of coding for compression; therefore upx complains `Not compressible`.
