### ISSUE TITLE
Program compressed with UPX 3.92 won't start on Windows 10 (UPX 3.91 is fine!)

### ISSUE THREAD

**Issue by lordmulder** [upx/upx#52]
## What's the problem (or question)?

My program, written in C++ and compiled by Visual Studio 2015 (Update-3), just **crashes** on startup on my Windows 10 (Version 1607, Build 14393.693) machine, when compressed by UPX v3.92. Actually the compressed program won't even start! Instead I get immediately the error message _"The application was unable to start correctly (0xC0000005)"_. It has to be pointed out that the exactly same binaries, compressed with UPX v3.91, work just fine! And, of course, the original (uncompressed) binaries work fine too.

![grafik](https://cloud.githubusercontent.com/assets/470590/21948975/ded54b54-d9ee-11e6-892a-5924b305b920.png)

## What should have happened?

The program compressed by UPX v3.92 should work, just like it does when compressed by UPX v3.91.

(Yeah, that's obvious. But I don't know what else to write here)

## Do you have an idea for a solution?

Not at this point, sorry. But could be related to #49.

## How can we reproduce the issue?

I provide here a full set of the original **uncompressed** binaries for you:
http://muldersoft.com/temp/upx_bug.1_uncompressed.zip

Also I provide the binaries *compressed* by **UPX v3.91** that work fine for me:
http://muldersoft.com/temp/upx_bug.2_compressed_upx391.zip

And, finally, also the binaries *compressed* by **UPX v3.92** that are crashing:
http://muldersoft.com/temp/upx_bug.3_compressed_upx392.zip

If you want to look at the source code or the program compile yourself:
https://github.com/lordmulder/Simple-x264-Launcher

Just try to start the program "x264_launcher.exe" and you'll see (hopefully) that the version compressed by UPX v3.92 won't start (it crashes right away!) while the version compressed by UPX v3.91 _does_ work. If you want to compress it yourself, please start with the "original" binaries and be sure to compress the EXE file as well as the "MUtils1.DLL" and the various "Qt*.DLL" files. I *never* compress any of the MSVCR libraries.

Note that the sample program I provide is reduced to the minimum. So even when the program starts, it will only display an error message (displayed by the program itself) and exit. That is perfectly expected! What is **not** expect is that the program crashes before it even starts with an error message from the system :anguished:

(Please be sure to extract the program as provided with all its DLL's so that it can work correctly)

## Please tell us details about your environment.
* UPX version used: UPX v3.92 with "--best" option, nothing special
* Operating System and version: Windows 10 x64 (Version 1607, Build 14393.693)
* CPU architecture: x86-64 (aka AMD64), Intel Core i7 (6700K)

![grafik](https://cloud.githubusercontent.com/assets/470590/21949174/4ae8ea2a-d9f0-11e6-98c6-7b8186e7e3e6.png)

![grafik](https://cloud.githubusercontent.com/assets/470590/21949136/13a79584-d9f0-11e6-9db7-334101e5cdcd.png)

![grafik](https://cloud.githubusercontent.com/assets/470590/21949142/1a8902fc-d9f0-11e6-8ffb-7af074ae4105.png)

**Comment by ml1050** [comment]
Seems to be already fixed on the devel branch.

**Comment by lordmulder** [comment]
Would you kindly share a Windows build of the "devel branch" so that I can confirm?

Thank you...

**Comment by ml1050** [comment]
Unfortunately I can't.  I use linux exclusively and can not build a windows version. @markus-oberhumer will build upx 3.93 for all platforms.

**Comment by markus-oberhumer** [comment]
We now have automated builds of the devel branch - please download the current win32 version from

https://github.com/upx/upx-automatic-builds/tree/devel-20170115-051904-acd993-travis/i386-w64-mingw32-gcc-4.6-release

**Comment by ml1050** [comment]
Cool, thanks Markus!

**Comment by lordmulder** [comment]
Thanks for the link!

**Comment by lordmulder** [comment]
I get this, if I compress MSVCR140.DLL from Visual Studio 2015 with latest "dev" (git-acd993) build:

![grafik](https://cloud.githubusercontent.com/assets/470590/21962916/1a49e57c-db30-11e6-8cfb-21904313e5a6.png)

**Comment by markus-oberhumer** [comment]
Please reopen this issue if not fixed yet.

P.S. Wildcards should work now in the latest devel build.

**Comment by markus-oberhumer** [comment]
Please test with the fresh 3.93 release and close if it is fixed.

**Comment by lordmulder** [comment]
> Please test with the fresh 3.93 release and close if it is fixed.

Just tried UPX v3.93 and things look good - so far. Thank you!
