### ISSUE TITLE
CantUnpackException: ElfXX_Ehdr corrupted / Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by esmailzadeh1** [upx/upx#522]
## What's the problem (or question)?
After compress a shared library created with Go, it's Can't works
## What should have happened?
Segmentation fault (core dumped)

## Do you have an idea for a solution?
I haven't

## How can we reproduce the issue?

1- Create a main.go and put this code and Build it: `CGO_LDFLAGS="-ldl -lcrypto -lm -Wl,--build-id=none" go build -o library.so -buildmode=c-shared  -ldflags="-s -w -buildid=" -trimpath`

```
package main

/*
#cgo CFLAGS: -fPIC -O2
#cgo LDFLAGS: -ldl -lm
*/
import "C"
import (
	"github.com/rainycape/dl"
	"log"
)

func main() {

}

//export strrchr
func strrchr(s *C.char, c C.int) *C.char {
	lib, err := dl.Open("libc", 0)
	if err != nil {
		log.Fatalln(err)
	}
	defer lib.Close()

	var old_strrchr func(s *C.char, c C.int) *C.char
	lib.Sym("strrchr", &old_strrchr)

	return old_strrchr(s, c)
}
```
2- Using `LD_PRELOAD=./library.so /usr/bin/cat` , it's will work.
3- When using upx UPX 3.96 release for compress with `upx -o library.so library.so` the library can't works(Segmentation fault (core dumped))
4- Decompress doesn't working too and give this error:

```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx96: socket1upx.so: CantUnpackException: ElfXX_Ehdr corrupted
```
5- When using UPX latest devel version the library.so can't compress too.

```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX 4.0.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx.out: socket1.so: EOFException: premature end of file                       
```

## Please tell us details about your environment.
* UPX version 3.96
* Host Operating System and version: Ubuntu 20.04 LTS (Focal Fossa)
* Host CPU architecture: x86_64
* Target Operating System and version: Ubuntu  20.04 LTS (Focal Fossa)
* Target CPU architecture: x86_64

**Comment by n454149301** [comment]
I have same question:

when i build a simple demo with -linkshared, with "github.com/kataras/iris/v12", it's work.
when i use upx on complex products, with -linkshared, with "github.com/kataras/iris/v12", i got segmentation fault.
if when i use upx on complex products use 'upx -d ./broken -o dest', use ./dest, it's can work?

when i delete -linkshared, Everything is all right.
when i don't use "github.com/kataras/iris/v12", Everything is all right too.

so, I'm not sure if it's "github.com/kataras/iris/v12" problem.

**Comment by jreiser** [comment]
@n454149301 Please give the complete entire literal commands that you ran, and specify "succeeds" or "fails" for each command.  If a command fails then specify the message or symptoms.

**Comment by n454149301** [comment]
@jreiser 

Sorry, the test program I wrote didn't trigger the above problem. 
Only our company's golang service, about 300000 lines of system encountered. 
Sorry, I can't upload the relevant code.

**Comment by jreiser** [comment]
@n454149301 In some cases this info (a few kilobytes) can provide clues without revealing too much of the contents:
```
$ readelf --file-header --segments --dynamic ./my_app  # before compression
$ readelf --file-header --segments           ./my_app.upx  # after compression
```

**Comment by n454149301** [comment]
@jreiser 

I found that some programmers said that my problem was the ld(binutils) problem.
I updated my ubuntu 18.04LTS to ubuntu 20.04LTS. update binutils to 2.32.
Everything is all right. This problem can't be reproduced at all......

[go_issues_42238](https://github.com/golang/go/issues/42238#issuecomment-720434847)

**Comment by esmailzadeh1** [comment]
> readelf --file-header --segments --dynamic

Before compression

`ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x302c0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          996248 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         10
  Size of section headers:           64 (bytes)
  Number of section headers:         32
  Section header string table index: 31

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x000000000002f968 0x000000000002f968  R      0x1000
  LOAD           0x0000000000030000 0x0000000000030000 0x0000000000030000
                 0x0000000000057305 0x0000000000057305  R E    0x1000
  LOAD           0x0000000000088000 0x0000000000088000 0x0000000000088000
                 0x00000000000170d0 0x00000000000170d0  R      0x1000
  LOAD           0x000000000009fe08 0x00000000000a0e08 0x00000000000a0e08
                 0x0000000000053438 0x00000000000873b8  RW     0x1000
  DYNAMIC        0x00000000000eedc0 0x00000000000efdc0 0x00000000000efdc0
                 0x0000000000000200 0x0000000000000200  RW     0x8
  NOTE           0x0000000000000270 0x0000000000000270 0x0000000000000270
                 0x0000000000000088 0x0000000000000088  R      0x4
  TLS            0x000000000009fe08 0x00000000000a0e08 0x00000000000a0e08
                 0x0000000000000000 0x0000000000000008  R      0x8
  GNU_EH_FRAME   0x000000000009eb78 0x000000000009eb78 0x000000000009eb78
                 0x00000000000000fc 0x00000000000000fc  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x000000000009fe08 0x00000000000a0e08 0x00000000000a0e08
                 0x000000000004f1f8 0x000000000004f1f8  R      0x1

 Section to Segment mapping:
  Segment Sections...
   00     .note.gnu.build-id .note.go.buildid .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt 
   01     .init .plt .plt.got .text .fini 
   02     .rodata .eh_frame_hdr .eh_frame 
   03     .init_array .fini_array .data.rel.ro .dynamic .got .got.plt .data .go.buildinfo .noptrdata .bss .noptrbss 
   04     .dynamic 
   05     .note.gnu.build-id .note.go.buildid 
   06     .tbss 
   07     .eh_frame_hdr 
   08     
   09     .init_array .fini_array .data.rel.ro .dynamic .got 

Dynamic section at offset 0xeedc0 contains 28 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000010 (SYMBOLIC)           0x0
 0x000000000000000c (INIT)               0x30000
 0x000000000000000d (FINI)               0x872f8
 0x0000000000000019 (INIT_ARRAY)         0xa0e08
 0x000000000000001b (INIT_ARRAYSZ)       16 (bytes)
 0x000000000000001a (FINI_ARRAY)         0xa0e18
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x2f8
 0x0000000000000005 (STRTAB)             0xb28
 0x0000000000000006 (SYMTAB)             0x3f0
 0x000000000000000a (STRSZ)              1068 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0xf0000
 0x0000000000000002 (PLTRELSZ)           936 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x2f5c0
 0x0000000000000007 (RELA)               0x1060
 0x0000000000000008 (RELASZ)             189792 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              SYMBOLIC STATIC_TLS
 0x000000006ffffffb (FLAGS_1)            Flags: NODELETE
 0x000000006ffffffe (VERNEED)            0xff0
 0x000000006fffffff (VERNEEDNUM)         2
 0x000000006ffffff0 (VERSYM)             0xf54
 0x000000006ffffff9 (RELACOUNT)          7902
 0x0000000000000000 (NULL)               0x0
`

After compression

`ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x302c0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          996248 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         10
  Size of section headers:           64 (bytes)
  Number of section headers:         32
  Section header string table index: 31
readelf: Error: Reading 2048 bytes extends past end of file for section headers

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x000000000002f968 0x000000000002f968  R      0x1000
  LOAD           0x0000000000030000 0x0000000000030000 0x0000000000030000
                 0x000000000002519d 0x000000000002519d  R E    0x1000
  LOAD           0x0000000000056000 0x0000000000088000 0x0000000000088000
                 0x00000000000170d0 0x00000000000170d0  R      0x1000
  LOAD           0x0000000000056e08 0x00000000000a0e08 0x00000000000a0e08
                 0x0000000000053438 0x00000000000873b8  RW     0x1000
  DYNAMIC        0x00000000000a5dc0 0x00000000000efdc0 0x00000000000efdc0
                 0x0000000000000200 0x0000000000000200  RW     0x8
  NOTE           0x0000000000000270 0x0000000000000270 0x0000000000000270
                 0x0000000000000088 0x0000000000000088  R      0x4
  TLS            0x0000000000056e08 0x00000000000a0e08 0x00000000000a0e08
                 0x0000000000000000 0x0000000000000008  R      0x8
  GNU_EH_FRAME   0x0000000000055b78 0x000000000009eb78 0x000000000009eb78
                 0x00000000000000fc 0x00000000000000fc  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x0000000000056e08 0x00000000000a0e08 0x00000000000a0e08
                 0x000000000004f1f8 0x000000000004f1f8  R      0x1

Dynamic section at offset 0xa5dc0 contains 28 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000010 (SYMBOLIC)           0x0
 0x000000000000000c (INIT)               0x54dd8
 0x000000000000000d (FINI)               0x872f8
 0x0000000000000019 (INIT_ARRAY)         0xa0e08
 0x000000000000001b (INIT_ARRAYSZ)       16 (bytes)
 0x000000000000001a (FINI_ARRAY)         0xa0e18
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x2f8
 0x0000000000000005 (STRTAB)             0xb28
 0x0000000000000006 (SYMTAB)             0x3f0
 0x000000000000000a (STRSZ)              1068 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0xf0000
 0x0000000000000002 (PLTRELSZ)           936 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x2f5c0
 0x0000000000000007 (RELA)               0x1060
 0x0000000000000008 (RELASZ)             189792 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              SYMBOLIC STATIC_TLS
 0x000000006ffffffb (FLAGS_1)            Flags: NODELETE
 0x000000006ffffffe (VERNEED)            0xff0
 0x000000006fffffff (VERNEEDNUM)         2
 0x000000006ffffff0 (VERSYM)             0xf54
 0x000000006ffffff9 (RELACOUNT)          7902
 0x0000000000000000 (NULL)               0x0
`

After compression I can't use the file and got this error:

Segmentation fault (core dumped)

binutils is already the newest version (2.34-6ubuntu1.3).
Ubuntu 20.04 LTS
