### ISSUE TITLE
Trace/breakpoint trap with aarch64+python

### ISSUE THREAD

**Issue by muyu1944** [upx/upx#523]
## What's the problem (or question)?

build a py script to so file use cython
compress the so file use upx
in python environment import this so file, process will crash with "Trace/breakpoint trap"

## How can we reproduce the issue?

1.write a sample py script test.py:
`def test():  print('ok')`

2.compile and build test.py:
python -m cython test.py
gcc -I/usr/include/python2.7 -lpython2.7 -shared -fPIC -o test.so test.c

3.import test.so in python process
`>>> import test`
`>>> test.test()`
`ok`

4.compress test.so ues upx:
upx test.so -o test1.so

5.import compressed test1.so in python process:
`>>> import test1`
`Trace/breakpoint trap`
`[root@localhost home]#`

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.95 and 3.96 and devel
* Host Operating System and version: Centos 7 1810 aarch64
* Host CPU architecture: aarch64
* Target Operating System and version: Centos 7 1810 aarch64
* Target CPU architecture: aarch64

**Comment by libing0526** [comment]
perhaps we have same problem, after packed, the Section header table file offset of so file is large than file size. [https://github.com/upx/upx/issues/625](url)
