### ISSUE TITLE
How to keep the /tmp/upx????? file after executing the compression and not delete it until the end of the run

### ISSUE THREAD

**Issue by etjson** [upx/upx#524]
How to keep the /tmp/upx????? file after executing the compression and not delete it until the end of the run.

Some programs will still read their own files during execution, and if they are deleted during execution, they will exception.

**Comment by jreiser** [comment]
Please state the OS and file type, in order to positively identify the environment for this request.

Executable files on Linux(-like) systems which are not ELF (or which fail to meet the usual properties of ELF executables), are the ones which use a temporary file in /tmp; see src/stub/src/i386-*.elf.execve-main.c.   If this is your case, then modify the source to remove the calls to unlink(); then re-build the stubs and upx.  Or, use some environment variable to control the unlink().

**Comment by etjson** [comment]
> Please state the OS and file type, in order to positively identify the environment for this request.
> 
> Executable files on Linux(-like) systems which are not ELF (or which fail to meet the usual properties of ELF executables), are the ones which use a temporary file in /tmp; see src/stub/src/i386-*.elf.execve-main.c. If this is your case, then modify the source to remove the calls to unlink(); then re-build the stubs and upx. Or, use some environment variable to control the unlink().

![image](https://user-images.githubusercontent.com/41315967/132428604-9b88e73a-daef-4299-a7a1-15dd332cb76e.png)

Is this it?

**Comment by etjson** [comment]
@jreiser 

According to the operation you mentioned above, I deleted the corresponding code, but the file will still be deleted automatically.

**Comment by jreiser** [comment]
```
$ git grep unlink'(' i386-linux.elf.execve-main.c
i386-linux.elf.execve-main.c:            unlink(tmpname);
i386-linux.elf.execve-main.c:            // Now we must re-create the file; it was unlink()ed!
i386-linux.elf.execve-main.c:        int err = unlink(tmpname);
i386-linux.elf.execve-main.c:            (void) unlink(tmpname);
i386-linux.elf.execve-main.c:            unlink(tmpname);
$ 
```
So there are 4 lexical calls to unlink() at various places in the code.

Please do not copy+paste images of text.  Instead: place the next between two lines that each contain exactly 3 backtick characters (decimal 96, hex 0x60, octal 0120; often to the left of the key with the numeral '1' and the exclamation point '!').  This forms a "block quote" for the Markdown language that GitHub uses for Comments.

**Comment by etjson** [comment]
> ```
> $ git grep unlink'(' i386-linux.elf.execve-main.c
> i386-linux.elf.execve-main.c:            unlink(tmpname);
> i386-linux.elf.execve-main.c:            // Now we must re-create the file; it was unlink()ed!
> i386-linux.elf.execve-main.c:        int err = unlink(tmpname);
> i386-linux.elf.execve-main.c:            (void) unlink(tmpname);
> i386-linux.elf.execve-main.c:            unlink(tmpname);
> $ 
> ```
> 
> So there are 4 lexical calls to unlink() at various places in the code.
> 
> Please do not copy+paste images of text. Instead: place the next between two lines that each contain exactly 3 backtick characters (decimal 96, hex 0x60, octal 0120; often to the left of the key with the numeral '1' and the exclamation point '!'). This forms a "block quote" for the Markdown language that GitHub uses for Comments.

Still not working, I deleted all the other files containing `unlink` code, the file will still be deleted automatically

**Comment by etjson** [comment]
@jreiser 

The file size in the picture is 20M+, that's why I took a screenshot of part of it to tell you what type of file it is.

**Comment by etjson** [comment]
@jreiser 

i386-linux.elf.execve-main.c
```
if (fork() == 0)
    {
        if (fork() == 0)
        {
            // Sleep 3 seconds, then remove the temp file.
            struct timespec ts; ts.tv_sec = UPX4; ts.tv_nsec = 0;
            nanosleep(&ts, 0);
            //unlink(tmpname);
        }
        exit(0);
    }
```

The main thing is to make this change, look at the comment note is to delete the file after 3 seconds.

**Comment by etjson** [comment]
@jreiser 

Is there something wrong with the way I compile? I modified the code and executed the following command:

```
make clean
make all
```

**Comment by jreiser** [comment]
Perhaps seeing the system calls that actually are made will help you understand what happens:
```
strace ./my_compressed_app args...
```

Re-compiling: see the top-level `README.SRC` file, particularly the section "If you want to modify the stub sources ...".
You will re-build `src/stub/i386-linux.elf.execve-*.h` (2 files #included by `src/p_lx_exc.cpp`) before you can run `make` in the (top-level) `src/` directory.

**Comment by etjson** [comment]
@jreiser 

![image](https://user-images.githubusercontent.com/41315967/132443261-62cbafcd-3dd3-4b32-9c41-49dcb92dcca0.png)

```
2886  epoll_wait(19,  <unfinished ...>
2877  <... nanosleep resumed>NULL)      = 0
2877  unlink("/tmp/upxCX4IWA5ACZ1")     = 0
2877  exit(0)                           = ?
2877  +++ exited with 0 +++
2886  <... epoll_wait resumed>[], 10128, 100) = 0
```

The strace log shows that the file deletion was still performed, so the compilation did not take effect after modifying the source code?

**Comment by etjson** [comment]
@jreiser 

Yes, the problem has been solved, thank you very much!
