### ISSUE TITLE
Can't compress Rust binaries built with RPi compiler

### ISSUE THREAD

**Issue by ravenclaw900** [upx/upx#525]
## What's the problem (or question)?

Compressing a rust binary built with the Raspberry Pi compiler fails with: `CantPackException: bad DT_GNU_HASH n_bucket=0x11  n_bitmask=0x2  len=0x84`

## What should have happened?

Binary compresses fine.

## Do you have an idea for a solution?

No, sorry.

## How can we reproduce the issue?

1. Try compressing [attached binary](https://github.com/upx/upx/files/7148497/dietpi_dashboard_rust.tar.gz)

## Please tell us details about your environment.

* UPX version used (`upx --version`):
```
upx 3.96
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
Copyright (C) 1996-2020 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2020 Laszlo Molnar
Copyright (C) 2000-2020 John F. Reiser
Copyright (C) 2002-2020 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```
* Host Operating System and version:
Debian 11.0
* Host CPU architecture:
x86_64
* Target Operating System and version:
Raspberry Pi OS 11.0
* Target CPU architecture:
armv6

**Comment by jreiser** [comment]
This is fixed on the `devel` branch.

**Comment by ravenclaw900** [comment]
Yep, that works.

**Comment by Efreak** [comment]
I'm getting similar errors on rust binaries using the binary linked in #564. For some reason, `exa` is able to be compressed, while others are not. Not sure if this is related. I didn't keep a backup of the original, unfortunately, as I didn't expect it to actually work, but I can provide the resulting binary if necessary; running `exa -v` doesn't give any errors mentioned in other issues (I ran the command in a while loop, it ran >3500x)

```
UPX git-b4558e+ Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx.out: _kn: CantPackException: bad DT_GNU_HASH (1+ max_bucket)=0x1 < symbias=0x38
upx.out: hexcat: CantPackException: bad DT_GNU_HASH (1+ max_bucket)=0x1 < symbias=0x35
upx.out: neols: CantPackException: bad DT_GNU_HASH (1+ max_bucket)=0x1 < symbias=0x3b
upx.out: kibi: CantPackException: bad DT_GNU_HASH (1+ max_bucket)=0x1 < symbias=0x4f
upx.out: tre: CantPackException: bad DT_GNU_HASH (1+ max_bucket)=0x1 < symbias=0x4a
upx.out: rust-15-puzzle-cli: CantPackException: bad DT_GNU_HASH (1+ max_bucket)=0x1 < symbias=0x43
upx.out: huniq: CantPackException: bad DT_GNU_HASH (1+ max_bucket)=0x1 < symbias=0x35
upx.out: hexyl: CantPackException: bad DT_GNU_HASH (1+ max_bucket)=0x1 < symbias=0x39
upx.out: parallel-sh: CantPackException: bad DT_GNU_HASH (1+ max_bucket)=0x1 < symbias=0x51
   1011312 ->    408096   40.35%   linux/arm64   exa

Packed 1 file.
```

**Comment by jreiser** [comment]
@Efreak Please upload ("Attach files by ...") or give the URL to `exa` and to one of the files which cause `CantPackException`. (Compress the upload with zip, gzip, or .tgz to reduce space and time.)  It looks like the builder creates improper DT_GNU_HASH tables.

**Comment by Efreak** [comment]
@jreiser everything is in [rust-bins.zip](https://github.com/upx/upx/files/7655052/rust-bins.zip). I rebuilt my own exa binary (`exa-cargo`) and reinstalled exa from Termux (`exa-termux`), so both of these files are in the root of the zip; both of them compress fine with upx. The other files are in .bin/cargo and all return DT_GNU_HASH.
