### ISSUE TITLE
Broken compression on armv7l

### ISSUE THREAD

**Issue by satmandu** [upx/upx#529]
## What's the problem (or question)?

binutils 2.37 is built and then compressed with upx. The `size` binary is broken when compressed. Uncompressing fixes the issue.

![image](https://user-images.githubusercontent.com/1096701/134676077-e68cceb1-b14d-4a70-9c57-72238de405c8.png)

## How can we reproduce the issue?

(Attaching binaries.)
[size.armv7l.uncompressed.zip](https://github.com/upx/upx/files/7225707/size.armv7l.uncompressed.zip)
[size.armv7l.compressed.zip](https://github.com/upx/upx/files/7225708/size.armv7l.compressed.zip)

The package script we use to build upx: https://github.com/skycocker/chromebrew/blob/master/packages/upx.rb
The package script I used to build binutils: https://github.com/skycocker/chromebrew/blob/d2100fc8934deb6c0fec81971378e0a4df40adc6/packages/binutils.rb

(Let us know if you need access to a container to replicate this... I can walk you through setting up a container using docker on a raspberry pi 4.)

## Please tell us details about your environment.

* UPX version used (`upx --version`):
```
upx --version
upx 4.0.0-git-8a828474ca68+
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
Copyright (C) 1996-2021 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2021 Laszlo Molnar
Copyright (C) 2000-2021 John F. Reiser
Copyright (C) 2002-2021 Jens Medoch
Copyright (C) 1995-2017 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```
```
ldd `which upx`
        linux-vdso.so.1 (0x00007fff53f8d000)
        libucl.so.1 => /usr/local/lib64/libucl.so.1 (0x00007ae9a94fc000)
        libz.so.1 => /usr/local/lib64/libz.so.1 (0x00007ae9a94e0000)
        libstdc++.so.6 => /usr/local/lib64/libstdc++.so.6 (0x00007ae9a92b1000)
        libm.so.6 => /usr/local/lib64/libm.so.6 (0x00007ae9a91ac000)
        libgcc_s.so.1 => /usr/local/lib64/libgcc_s.so.1 (0x00007ae9a9192000)
        libc.so.6 => /usr/local/lib64/libc.so.6 (0x00007ae9a8fd8000)
        /lib64/ld-linux-x86-64.so.2 => /usr/local/lib64/ld-linux-x86-64.so.2 (0x00007ae9a9723000)
```
* Host Operating System and version: ChromeOS M91
* Host CPU architecture: armv7l
* Target Operating System and version: ChromeOS M91
* Target CPU architecture: armv7l

**Comment by jreiser** [comment]
It is inefficient and impolite to post screenshots of text sessions such as in the Description above of this Issue (https://user-images.githubusercontent.com/1096701/134676077-e68cceb1-b14d-4a70-9c57-72238de405c8.png)  Instead capture text by shell re-direction or Select+copy(text), then paste the captured text into a Markdown block so as to produce pre-formatted constant-width output.  Use a line which has three backtick characters (hex 0x60: \`\`\`) just before, and just after, the text.  Use the Preview tab in a Comment widget to check formatting.

The UPX-compressed `size` is not broken.  `size` does not understand every executable ELF file, and in particular does not understand the reduced ELF format generated by UPX.  Perhaps you should consider commands such as `ls -l`, `readelf --segments`, `readelf --sections`, or `readelf --headers`.
