### ISSUE TITLE
libQt5WebEngineCore.5.so on the Qt5.15.2 and libcef is same problem (core dump)

### ISSUE THREAD

**Issue by muse117** [upx/upx#532]
## What's the problem (or question)?
I run cmd "upx libQt5WebEngineCore.so.5"，get core dump error

## What should have happened?
![微信截图_20211016145336](https://user-images.githubusercontent.com/9733486/137577472-0bd299d4-c3dc-4322-9e75-76e1b76efb20.png)

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.96
* Host Operating System and version: ubuntu16.04
* Host CPU architecture:
* Target Operating System and version: vmware-16
* Target CPU architecture:

**Comment by jreiser** [comment]
The screenshot shows that upx-3.96 executed successfully: "Packed 1 file." with no core dump.  Please state how to re-create the core dump: what process was running, the command line arguments, and where to get a copy of the executable.

**Comment by muse117** [comment]
> The screenshot shows that upx-3.96 executed successfully: "Packed 1 file." with no core dump. Please state how to re-create the core dump: what process was running, the command line arguments, and where to get a copy of the executable.

I update screenshot. You can see the difference between no upx and upxed. 
![微信图片_20211019142201](https://user-images.githubusercontent.com/9733486/137855144-63634171-8a3a-43ef-980e-701c35d656f4.png)

**Comment by muse117** [comment]
Libcef runs into the same problem
![微信截图_20211021103718](https://user-images.githubusercontent.com/9733486/138201914-d6918a23-1af0-4352-91c3-2a6d20afc6dd.png)

**Comment by muse117** [comment]
> Please run `readelf --segments` on each library, then copy+paste the text into a Comment here. Put a line that contains three back-tick characters (decimal 96, hex 0x60, octal 0140) before and after the pasted text, so that the formatted Comment uses constant-width charcters.

96 0x60 0140
LC_ALL=c readelf --segments libcef.so
readelf: Error: Reading 0x840 bytes extends past end of file for section headers

Elf file type is DYN (Shared object file)
Entry point 0x0
There are 9 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x00000000000001f8 0x00000000000001f8  R      8
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000022ebedd 0x00000000022ebedd  R E    1000
  LOAD           0x0000000002831520 0x0000000004e88520 0x0000000004e88520
                 0x00000000003b05c1 0x00000000004ad35c  RW     1000
  DYNAMIC        0x0000000002bb76b8 0x000000000520e6b8 0x000000000520e6b8
                 0x0000000000000440 0x0000000000000440  RW     8
  NOTE           0x0000000000000238 0x0000000000000238 0x0000000000000238
                 0x0000000000000024 0x0000000000000024  R      4
  GNU_EH_FRAME   0x00000000026b23b4 0x0000000004d083b4 0x0000000004d083b4
                 0x000000000017e404 0x000000000017e404  R      4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0
  TLS            0x0000000002831520 0x0000000004e88520 0x0000000004e88520
                 0x0000000000000010 0x0000000000000010  R      8
  GNU_RELRO      0x0000000002831520 0x0000000004e88520 0x0000000004e88520
                 0x000000000038aae0 0x000000000038aae0  RW     10

LC_ALL=c readelf --segments libQt5WebEngineCore.so.5
readelf: Error: Reading 0x7c0 bytes extends past end of file for section headers

Elf file type is DYN (Shared object file)
Entry point 0x9d1900
There are 8 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000034e856d 0x00000000034e856d  R E    200000
  LOAD           0x00000000034e8a68 0x00000000076eaa68 0x00000000076eaa68
                 0x0000000000485a80 0x00000000006155a0  RW     1000
  DYNAMIC        0x000000000390bc30 0x0000000007b0dc30 0x0000000007b0dc30
                 0x00000000000004d0 0x00000000000004d0  RW     8
  NOTE           0x0000000000000200 0x0000000000000200 0x0000000000000200
                 0x0000000000000024 0x0000000000000024  R      4
  TLS            0x00000000034e8a68 0x00000000076eaa68 0x00000000076eaa68
                 0x0000000000000018 0x000000000000007c  R      8
  GNU_EH_FRAME   0x00000000034e45b8 0x00000000074e65b8 0x00000000074e65b8
                 0x0000000000000a14 0x0000000000000a14  R      4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     10
  GNU_RELRO      0x00000000034e8a68 0x00000000076eaa68 0x00000000076eaa68
                 0x0000000000427598 0x0000000000427598  R      1
96 0x60 0140

**Comment by muse117** [comment]
@jreiser Hi,

After you compile the program, can you use UPX compression to reproduce the phenomenon?

I am emailing you a sample compiled with version 81, which contains upx compression of "libcef.so" and the original "libcef.so.origin". You can compare version 81 with version 94 to see if the LOAD segment is causing this problem.

**Comment by Tshit** [comment]
Have same problem when use upx for compressing libcef.so, here is the readelf --headers --segments --dynamic libcef.so result

**Comment by Tshit** [comment]
Have same problem when use upx for compressing libcef.so, here is the readelf --headers --segments --dynamic libcef.so result 
Before using upx:
ELF 头：
  Magic：  7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  类别:                              ELF64
  数据:                              2 补码，小端序 (little endian)
  版本:                              1 (current)
  OS/ABI:                            UNIX - System V
  ABI 版本:                          0
  类型:                              DYN (共享目标文件)
  系统架构:                          Advanced Micro Devices X86-64
  版本:                              0x1
  入口点地址：              0x1929c40
  程序头起点：              64 (bytes into file)
  Start of section headers:          142604616 (bytes into file)
  标志：             0x0
  本头的大小：       64 (字节)
  程序头大小：       56 (字节)
  Number of program headers:         11
  节头大小：         64 (字节)
  节头数量：         31
  字符串表索引节头： 30

节头：
  [号] 名称              类型             地址              偏移量
       大小              全体大小          旗标   链接   信息   对齐
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .note.crashpad.in NOTE             00000000000002a8  000002a8
       0000000000000020  0000000000000000   A       0     0     4
  [ 2] .note.gnu.build-i NOTE             00000000000002c8  000002c8
       0000000000000024  0000000000000000   A       0     0     4
  [ 3] .dynsym           DYNSYM           00000000000002f0  000002f0
       0000000000009378  0000000000000018   A       7     1     8
  [ 4] .gnu.version      VERSYM           0000000000009668  00009668
       0000000000000c4a  0000000000000002   A       3     0     2
  [ 5] .gnu.version_r    VERNEED          000000000000a2b4  0000a2b4
       0000000000000390  0000000000000000   A       7    11     4
  [ 6] .gnu.hash         GNU_HASH         000000000000a648  0000a648
       00000000000005e4  0000000000000000   A       3     0     8
  [ 7] .dynstr           STRTAB           000000000000ac2c  0000ac2c
       00000000000073f6  0000000000000000   A       0     0     1
  [ 8] .rela.dyn         RELA             0000000000012028  00012028
       0000000000f0afe0  0000000000000018   A       3     0     8
  [ 9] .rela.plt         RELA             0000000000f1d008  00f1d008
       0000000000008100  0000000000000018  AI       3    25     8
  [10] .rodata           PROGBITS         0000000000f25200  00f25200
       00000000009f7994  0000000000000000 AMS       0     0     256
  [11] .gcc_except_table PROGBITS         000000000191cb94  0191cb94
       000000000000414c  0000000000000000   A       0     0     4
  [12] .eh_frame_hdr     PROGBITS         0000000001920ce0  01920ce0
       0000000000001294  0000000000000000   A       0     0     4
  [13] .eh_frame         PROGBITS         0000000001921f78  01921f78
       0000000000006c8c  0000000000000000   A       0     0     8
  [14] .init             PROGBITS         0000000001929c04  01928c04
       0000000000000017  0000000000000000  AX       0     0     4
  [15] .fini             PROGBITS         0000000001929c1c  01928c1c
       0000000000000009  0000000000000000  AX       0     0     4
  [16] .text             PROGBITS         0000000001929c40  01928c40
       0000000006818dfc  0000000000000000  AX       0     0     64
  [17] .plt              PROGBITS         0000000008142a40  08141a40
       0000000000005610  0000000000000000  AX       0     0     16
  [18] .tdata            PROGBITS         0000000008149050  08147050
       0000000000000018  0000000000000000 WAT       0     0     8
  [19] .tbss             NOBITS           0000000008149068  08147068
       000000000000004d  0000000000000000 WAT       0     0     8
  [20] .fini_array       FINI_ARRAY       0000000008149068  08147068
       0000000000000008  0000000000000008  WA       0     0     8
  [21] .init_array       INIT_ARRAY       0000000008149070  08147070
       0000000000000010  0000000000000008  WA       0     0     8
  [22] .data.rel.ro      PROGBITS         0000000008149080  08147080
       000000000061dbc0  0000000000000000  WA       0     0     64
  [23] .dynamic          DYNAMIC          0000000008766c40  08764c40
       0000000000000420  0000000000000010  WA       7     0     8
  [24] .got              PROGBITS         0000000008767060  08765060
       00000000000243c8  0000000000000000  WA       0     0     8
  [25] .got.plt          PROGBITS         000000000878b428  08789428
       0000000000002b18  0000000000000000  WA       0     0     8
  [26] .tm_clone_table   PROGBITS         000000000878ef40  0878bf40
       0000000000000000  0000000000000000  WA       0     0     8
  [27] .data             PROGBITS         000000000878ef40  0878bf40
       0000000000073858  0000000000000000  WA       0     0     16
  [28] .bss              NOBITS           00000000088027a0  087ff798
       000000000019f72c  0000000000000000  WA       0     0     32
  [29] .comment          PROGBITS         0000000000000000  087ff798
       0000000000000080  0000000000000001  MS       0     0     1
  [30] .shstrtab         STRTAB           0000000000000000  087ff818
       000000000000012d  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  l (large), p (processor specific)

程序头：
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x0000000000000268 0x0000000000000268  R      0x8
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000001928c04 0x0000000001928c04  R      0x1000
  LOAD           0x0000000001928c04 0x0000000001929c04 0x0000000001929c04
                 0x000000000681e44c 0x000000000681e44c  R E    0x1000
  LOAD           0x0000000008147050 0x0000000008149050 0x0000000008149050
                 0x0000000000644ef0 0x0000000000644ef0  RW     0x1000
  LOAD           0x000000000878bf40 0x000000000878ef40 0x000000000878ef40
                 0x0000000000073858 0x0000000000212f8c  RW     0x1000
  TLS            0x0000000008147050 0x0000000008149050 0x0000000008149050
                 0x0000000000000018 0x0000000000000065  R      0x8
  DYNAMIC        0x0000000008764c40 0x0000000008766c40 0x0000000008766c40
                 0x0000000000000420 0x0000000000000420  RW     0x8
  GNU_RELRO      0x0000000008147050 0x0000000008149050 0x0000000008149050
                 0x0000000000644ef0 0x0000000000644fb0  R      0x1
  GNU_EH_FRAME   0x0000000001920ce0 0x0000000001920ce0 0x0000000001920ce0
                 0x0000000000001294 0x0000000000001294  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x0
  NOTE           0x00000000000002a8 0x00000000000002a8 0x00000000000002a8
                 0x0000000000000044 0x0000000000000044  R      0x4

 Section to Segment mapping:
  段节...
   00     
   01     .note.crashpad.info .note.gnu.build-id .dynsym .gnu.version .gnu.version_r .gnu.hash .dynstr .rela.dyn .rela.plt .rodata .gcc_except_table .eh_frame_hdr .eh_frame 
   02     .init .fini .text .plt 
   03     .tdata .fini_array .init_array .data.rel.ro .dynamic .got .got.plt 
   04     .tm_clone_table .data .bss 
   05     .tdata .tbss 
   06     .dynamic 
   07     .tdata .fini_array .init_array .data.rel.ro .dynamic .got .got.plt 
   08     .eh_frame_hdr 
   09     
   10     .note.crashpad.info .note.gnu.build-id 

Dynamic section at offset 0x8764c40 contains 66 entries:
  标记        类型                         名称/值
 0x0000000000000001 (NEEDED)             共享库：[libdl.so.2]
 0x0000000000000001 (NEEDED)             共享库：[libpthread.so.0]
 0x0000000000000001 (NEEDED)             共享库：[librt.so.1]
 0x0000000000000001 (NEEDED)             共享库：[libgobject-2.0.so.0]
 0x0000000000000001 (NEEDED)             共享库：[libglib-2.0.so.0]
 0x0000000000000001 (NEEDED)             共享库：[libnss3.so]
 0x0000000000000001 (NEEDED)             共享库：[libnssutil3.so]
 0x0000000000000001 (NEEDED)             共享库：[libsmime3.so]
 0x0000000000000001 (NEEDED)             共享库：[libnspr4.so]
 0x0000000000000001 (NEEDED)             共享库：[libfontconfig.so.1]
 0x0000000000000001 (NEEDED)             共享库：[libgio-2.0.so.0]
 0x0000000000000001 (NEEDED)             共享库：[libm.so.6]
 0x0000000000000001 (NEEDED)             共享库：[libX11.so.6]
 0x0000000000000001 (NEEDED)             共享库：[libXcomposite.so.1]
 0x0000000000000001 (NEEDED)             共享库：[libXdamage.so.1]
 0x0000000000000001 (NEEDED)             共享库：[libXext.so.6]
 0x0000000000000001 (NEEDED)             共享库：[libXfixes.so.3]
 0x0000000000000001 (NEEDED)             共享库：[libXrender.so.1]
 0x0000000000000001 (NEEDED)             共享库：[libexpat.so.1]
 0x0000000000000001 (NEEDED)             共享库：[libX11-xcb.so.1]
 0x0000000000000001 (NEEDED)             共享库：[libxcb.so.1]
 0x0000000000000001 (NEEDED)             共享库：[libxcb-dri3.so.0]
 0x0000000000000001 (NEEDED)             共享库：[libXcursor.so.1]
 0x0000000000000001 (NEEDED)             共享库：[libXi.so.6]
 0x0000000000000001 (NEEDED)             共享库：[libXtst.so.6]
 0x0000000000000001 (NEEDED)             共享库：[libdrm.so.2]
 0x0000000000000001 (NEEDED)             共享库：[libXrandr.so.2]
 0x0000000000000001 (NEEDED)             共享库：[libgbm.so.1]
 0x0000000000000001 (NEEDED)             共享库：[libXss.so.1]
 0x0000000000000001 (NEEDED)             共享库：[libdbus-1.so.3]
 0x0000000000000001 (NEEDED)             共享库：[libasound.so.2]
 0x0000000000000001 (NEEDED)             共享库：[libatk-1.0.so.0]
 0x0000000000000001 (NEEDED)             共享库：[libatk-bridge-2.0.so.0]
 0x0000000000000001 (NEEDED)             共享库：[libpangocairo-1.0.so.0]
 0x0000000000000001 (NEEDED)             共享库：[libpango-1.0.so.0]
 0x0000000000000001 (NEEDED)             共享库：[libcups.so.2]
 0x0000000000000001 (NEEDED)             共享库：[libatspi.so.0]
 0x0000000000000001 (NEEDED)             共享库：[libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             共享库：[libc.so.6]
 0x0000000000000001 (NEEDED)             共享库：[ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libcef.so]
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            标志： NOW
 0x0000000000000007 (RELA)               0x12028
 0x0000000000000008 (RELASZ)             15773664 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          657161
 0x0000000000000017 (JMPREL)             0xf1d008
 0x0000000000000002 (PLTRELSZ)           33024 (bytes)
 0x0000000000000003 (PLTGOT)             0x878b428
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000006 (SYMTAB)             0x2f0
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0xac2c
 0x000000000000000a (STRSZ)              29686 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0xa648
 0x0000000000000019 (INIT_ARRAY)         0x8149070
 0x000000000000001b (INIT_ARRAYSZ)       16 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x8149068
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000000000000c (INIT)               0x1929c04
 0x000000000000000d (FINI)               0x1929c1c
 0x000000006ffffff0 (VERSYM)             0x9668
 0x000000006ffffffe (VERNEED)            0xa2b4
 0x000000006fffffff (VERNEEDNUM)         11
 0x0000000000000000 (NULL)               0x0
After using upx:
ELF 头：
  Magic：  7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  类别:                              ELF64
  数据:                              2 补码，小端序 (little endian)
  版本:                              1 (current)
  OS/ABI:                            UNIX - System V
  ABI 版本:                          0
  类型:                              DYN (共享目标文件)
  系统架构:                          Advanced Micro Devices X86-64
  版本:                              0x1
  入口点地址：              0x1929c40
  程序头起点：              64 (bytes into file)
  Start of section headers:          142604616 (bytes into file)
  标志：             0x0
  本头的大小：       64 (字节)
  程序头大小：       56 (字节)
  Number of program headers:         11
  节头大小：         64 (字节)
  节头数量：         31
  字符串表索引节头： 30
readelf：错误：Reading 1984 bytes extends past end of file for 节头

程序头：
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x0000000000000268 0x0000000000000268  R      0x8
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000001928c04 0x0000000001928c04  R      0x1000
  LOAD           0x0000000001928c04 0x0000000001929c04 0x0000000001929c04
                 0x000000000269ce71 0x000000000269ce71  R E    0x1000
  LOAD           0x0000000003fc6050 0x0000000008149050 0x0000000008149050
                 0x0000000000644ef0 0x0000000000644ef0  RW     0x1000
  LOAD           0x0000000003fc6f40 0x000000000878ef40 0x000000000878ef40
                 0x0000000000073858 0x0000000000212f8c  RW     0x1000
  TLS            0x0000000003982050 0x0000000008149050 0x0000000008149050
                 0x0000000000000018 0x0000000000000065  R      0x8
  DYNAMIC        0x0000000003f9fc40 0x0000000008766c40 0x0000000008766c40
                 0x0000000000000420 0x0000000000000420  RW     0x8
  GNU_RELRO      0x0000000003982050 0x0000000008149050 0x0000000008149050
                 0x0000000000644ef0 0x0000000000644fb0  R      0x1
  GNU_EH_FRAME   0x0000000001920ce0 0x0000000001920ce0 0x0000000001920ce0
                 0x0000000000001294 0x0000000000001294  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x0
  NOTE           0x00000000000002a8 0x00000000000002a8 0x00000000000002a8
                 0x0000000000000044 0x0000000000000044  R      0x4

Dynamic section at offset 0x3f9fc40 contains 66 entries:
  标记        类型                         名称/值
 0xa983582e818d75e3 (<未知>：a983582e818d75e3)        0x4b8a73c3f4d44de5
 0xc800b6a20d2e7f20 (<未知>：c800b6a20d2e7f20)        0x4275839bd05548c6
 0x7978160cd2d6e8ff (<未知>：7978160cd2d6e8ff)        0xc1e4526e58b5c52a
 0xf9ea4c8bd452c17d (<未知>：f9ea4c8bd452c17d)        0x5e034803f05a5100
 0x175f0b43a006e518 (<未知>：175f0b43a006e518)        0xc883c10d3072c69b
 0x13dc3cac27d5b775 (<未知>：13dc3cac27d5b775)        0xe06c8f793790d32c
 0xcc6508b07ddc01ef (<未知>：cc6508b07ddc01ef)        0xaf8d0d04cf025ae9
 0x9c5a9228c0cb4de9 (<未知>：9c5a9228c0cb4de9)        0xe70c3a7834801815
 0x0186c8ac989e83ce (<未知>：186c8ac989e83ce)       0xdee2865e54e7d0d9
 0x0ad2c46d64b5d10b (<未知>：ad2c46d64b5d10b)       0x56b0903cd9d9ea67
 0x4a5657ee10d95360 (<未知>：4a5657ee10d95360)        0x28ea60a00c894208
 0xc1492130717e7a93 (<未知>：c1492130717e7a93)        0xc61d0cb3388db109
 0xa5067a93d024487d (<未知>：a5067a93d024487d)        0x99f161e3d4f0392f
 0x2987a0c289176590 (<未知>：2987a0c289176590)        0xc2f0c31c2117b9c5
 0x078c6dfe3474f54e (<未知>：78c6dfe3474f54e)       0x6101ab83690b52e8
 0x484c203ccadb80c9 (<未知>：484c203ccadb80c9)        0x11cd0b91e86195f
 0x2b499e09f88612f0 (<未知>：2b499e09f88612f0)        0xd9c3ae7c3456411e
 0x5b1d6849ffecd843 (<未知>：5b1d6849ffecd843)        0xc4b07da818c9bb4
 0x38e6b0152c25c88d (<未知>：38e6b0152c25c88d)        0x77b5ffd1937a306f
 0x4543140fdfe8d512 (<未知>：4543140fdfe8d512)        0x91f7093f0ac06908
 0x60ec212c0dc581c1 (<未知>：60ec212c0dc581c1)        0xd0ad74fbfbc5c471
 0x4cd8aedf09b10997 (<未知>：4cd8aedf09b10997)        0xb2a4f5e980c3460f
 0xe97f1e5a25e853bb (<未知>：e97f1e5a25e853bb)        0x61d90078f02607f3
 0xbc1c3b0d93a41ab4 (<未知>：bc1c3b0d93a41ab4)        0x9f0ee31249bc964f
 0x43640523097d2fb4 (<未知>：43640523097d2fb4)        0xfa1f59184703e3a9
 0x0f433c373da1a093 (<未知>：f433c373da1a093)       0xcf6e1a74c97db0d7
 0x5b6b99ef7064dae8 (<未知>：5b6b99ef7064dae8)        0x732f08359eed816f
 0x97350b0eeca413a1 (<未知>：97350b0eeca413a1)        0xcb323c031ef832e9
 0x3c038384e1e12641 (<未知>：3c038384e1e12641)        0x20579f93bbb752b7
 0x08e0c205226dff1f (<未知>：8e0c205226dff1f)       0x3c80c1b804471907
 0x78d60abf1250a047 (<未知>：78d60abf1250a047)        0xf10c7da21fb00718
 0x2b2dc5c66f9204e9 (<未知>：2b2dc5c66f9204e9)        0xc4c2753603fb5b5d
 0x02f4f40a3e873902 (<未知>：2f4f40a3e873902)       0xee3fa69c6716d501
 0x8efc39e7be8bb983 (<未知>：8efc39e7be8bb983)        0x25c409944a261765
 0xa04423493780a00c (<未知>：a04423493780a00c)        0xdc29491f73bec07f
 0x400906780b6d3ec3 (<未知>：400906780b6d3ec3)        0x1b612f40050d10df
 0x1c1a08871f741127 (<未知>：1c1a08871f741127)        0xec0e52e96a1e24e3
 0x7a8b4318beb58122 (<未知>：7a8b4318beb58122)        0x5d65a558ae0517e8
 0x1f075968511c9561 (<未知>：1f075968511c9561)        0xd270cc1ebf052115
 0x0589e1aeb5b6c806 (<未知>：589e1aeb5b6c806)       0x9808bfa11458b0e1
 0x581ca5bd69f1f0ea (<未知>：581ca5bd69f1f0ea)        0x53fd1d3efdb9c0f8
 0x5f45f5e7786d231a (<未知>：5f45f5e7786d231a)        0xca91fbb48ebf8a48
 0x6c13c381faa012bd (<未知>：6c13c381faa012bd)        0x25fbe9550e4581f2
 0x92d6534232c0c84c (<未知>：92d6534232c0c84c)        0x8467d0ccec27e146
 0x9571d84640ef23be (<未知>：9571d84640ef23be)        0xe31e3025f85eb0f7
 0xb6c2396fdfc81b0f (<未知>：b6c2396fdfc81b0f)        0x6d20c294d0cf417
 0x4367a704a8220e4c (<未知>：4367a704a8220e4c)        0xb4ae35280f3e0664
 0x20ccb44f10d25dbd (<未知>：20ccb44f10d25dbd)        0x8b0253be6494e8a5
 0xa05688fc40309066 (<未知>：a05688fc40309066)        0x86042eb82160c98d
 0xc6540fe28fa457cd (<未知>：c6540fe28fa457cd)        0x35dfd0f8483ef8be
 0x160808e21ed13de9 (<未知>：160808e21ed13de9)        0xb800256f59d95c5e
 0xb7ee48f0518c48e0 (<未知>：b7ee48f0518c48e0)        0x2836c1a31085854a
 0x254f3363102bacdb (<未知>：254f3363102bacdb)        0xeb1b9f05724525c2
 0x22b5a332fc0a4720 (<未知>：22b5a332fc0a4720)        0xcf0544611cb04c4
 0xfa0ed636141dfb41 (<未知>：fa0ed636141dfb41)        0x7020da3808f06418
 0x0a101820dcddafee (<未知>：a101820dcddafee)       0x28628859d290fd8
 0x18ce4877e15b68cc (<未知>：18ce4877e15b68cc)        0x5c2de0bd697f02c1
 0xc0496c1b17e93de6 (<未知>：c0496c1b17e93de6)        0x3c61e33ad971d421
 0x8cd005301067c996 (<未知>：8cd005301067c996)        0xdf5ea9ca581b37c1
 0x5ef89b7cf7b42244 (<未知>：5ef89b7cf7b42244)        0x6caccc8c854fec7
 0x445d482521d2fd5f (<未知>：445d482521d2fd5f)        0x5c22a7bf43aa2977
 0x84187816860d185e (<未知>：84187816860d185e)        0x8b408e4c334c9171
 0x16d717dce9257f43 (<未知>：16d717dce9257f43)        0x8601c60806e9b7ef
 0x1d555c605e452126 (<未知>：1d555c605e452126)        0x968c13a11cae570b
 0x17484e332149082e (<未知>：17484e332149082e)        0x817e41005340946
 0xc047e36c85c40115 (<未知>：c047e36c85c40115)        0x4441e785c0073781

**Comment by Tshit** [comment]
I think upx may crashed dynamic library link when compressing
