### ISSUE TITLE
How to customize /tmp/upx???? The beginning name of

### ISSUE THREAD

**Issue by etjson** [upx/upx#537]
Some programs need to dynamically read the contents of their own files, so I removed unlink(tmpname); but it created a lot of /tmp/upx????? If I delete them directly, I can't distinguish whether /tmp/upx is in use by other programs, so I want to specify the deletion by changing tmpname.

**Comment by etjson** [comment]
[https://github.com/upx/upx/issues/524](https://github.com/upx/upx/issues/524)

This is the problem I raised before, mainly for the php language packaged phar package program needs to read its own file content when running, so you can not delete /tmp/upx????? file, but because of the removal of the unlink, each restart of the program generates /tmp/upx????? files that cannot be cleaned up automatically.

**Comment by etjson** [comment]
```text
if (fork() == 0)
    {
        if (fork() == 0)
        {
            // Sleep 3 seconds, then remove the temp file.
            struct timespec ts; ts.tv_sec = UPX4; ts.tv_nsec = 0;
            nanosleep(&ts, 0);
            unlink(tmpname);
        }
        exit(0);
    }
```
Regarding this logic of automatically deleting itself after 3 seconds, can you consider optimizing it to detect whether the program is running and wait for the kill message to be received before deleting itself, or tell me how `tmpname` can be customized?

**Comment by jreiser** [comment]
@etjson   File `src/stub/src/i386-linux.elf.execve-main.c`:
```
go_self(char const *tmpname, char *argv[], char *envp[]) {...}
```
You have `envp[]`, so you can write `getenv()`.  Create a convention that utilizes one or more environment variables to specify what you want done, then modify `go_self()` to do it.  Consider the various ways of implementing "position-independent string constants"; look at the generation of `"/proc/self/exe"` in `stub/src/*.S`.  Look in `include/linux.h` for hints about missing system calls.

The build process is:
```
    pushd src/stub; make; popd   # see https://github.com/upx/upx-stubtools
    pushd src; make; popd
```

**Comment by etjson** [comment]
@jreiser 

Yes, the problem has been solved, thank you very much!
