### ISSUE TITLE
Provide a container image with UPX

### ISSUE THREAD

**Issue by tqvarnst** [upx/upx#539]
## What's the problem (or question)?
Not really a problem, but IMO one of the more interesting use-cases for UPX is to compress the size of an executable in a container. Since containers are often transferred over the network, the size of containers is important. 

## What should have happened?
Today if you want to build a container you either need UPX installed in your build system or you need to create a container that has UPX. By shipping an official UPX Linux container it would make this process simpler and improve 3rd party usage of UPX. 

## Do you have an idea for a solution?
Include creating and shipping an official UPX container into your release process and publish it on either Docker Hub or Quay.io.

## How can we reproduce the issue?
N/A

## Please tell us details about your environment.
N/A, but this would be Linux only feature since containers are based on Linux.

**Comment by phaus** [comment]
I am using UPX within my Docker Builds.
So if you need to have a start image, you may look into https://github.com/phaus/gobelt

**Comment by tqvarnst** [comment]
Thanks, Philipp! But I would like to see an official image from the UPX community itself that is maintained and updated. I also think that it would be beneficial to the UPX community to do it since it will probably make the echo system and consumption of using UPX easier and better. 

By the way, I'm in no way meaning that you are not maintaining the image that you do. It's just that from a license and trust perspective it would be better that the community delivers an image like this and not a single individual.

**Comment by jreiser** [comment]
As distributed by Team UPX and as [auto-built](https://github.com/upx/upx-automatic-builds) by commits to `devel` branch, UPX is a single compiled binary executable file that depends only on the shared libraries `libc.so`, `libgcc_s.so`, `libm.so`, `libstdc++.so`, and `libz.so`.  It is trivial to place that one file into a container, whether by initial construction or later network copy.  Unlike an ocean shipping container, where a 20-foot unit interoperates with any container ship, any port, any truck container chassis, and any rail car container carrier in the `world`, there is no single standard format for a "Linux container".  Team UPX will leave that tower of Babel to container maintaiers.

**Comment by pratikbalar** [comment]
I think this can help https://github.com/pratikbalar/docker-upx-multiarch

**Comment by polarathene** [comment]
Do you really need an official container when you can use this? (_or some variant of it, eg in a multi-stage Dockerfile_):

```Dockerfile
FROM alpine:3.14
RUN apk add --no-cache upx=3.96-r1

COPY file /path/to/file
RUN upx --lzma /path/to/file
```

If you were to run UPX within the Dockerfile, you'd be shaving off 1 line from that really.

I take it you want to just pull an image already built and use `docker run` with a volume mount instead?
