### ISSUE TITLE
32-bit DLL Injection fails with UPX3.92-compressed DLL

### ISSUE THREAD

**Issue by reliasn** [upx/upx#54]
## What's the problem (or question)?
DLL Injection fails when using UPX 3.92. It was working well with 3.91.

## What should have happened?
In the sample DLL Injection project that I'm posting below, it should have shown a MessageBox with "Hi!" upon injection. This only happens when the DLL is compressed with UPX 3.91.

## Do you have an idea for a solution?
No.

## How can we reproduce the issue?
1. Clone my DLL Injection test project: https://github.com/reliasn/dllinjecttest
2. Build everything (Used VS2015, but it should work for older ones)
3. Apply UPX on ``dlltest.dll``
4. Run ``dllinjecttest.exe`` with Skype.exe opened (Or any other 32-bit process).

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.92
* Operating System and version: Windows 10 64-bit
* CPU architecture: Intel Core i7-6700HQ

**Comment by markus-oberhumer** [comment]
Please try the latest devel build

https://github.com/upx/upx-automatic-builds/tree/devel-20170117-d333c94-travis/i386-w64-mingw32-gcc-4.6-release

**Comment by reliasn** [comment]
Working great! I think this issue can be closed.

Thanks for the quick reply!

**Comment by reliasn** [comment]
Just reporting that the issue is present on UPX 3.93. I also tried this devel build and got the same problem:

https://github.com/upx/upx-automatic-builds/tree/devel-20170206-d30a0a2-travis/i386-w64-mingw32-gcc-4.6-release

**Comment by reliasn** [comment]
I tested with the dummy project that I mentioned above and it worked well, but when I test with the DLL of my main application, it doesn't. I removed the DLL exports and even made my DllMain similar to the dummy project, but it simply doesn't work, i.e., the MessageBox isn't displayed. If you want, I can send you privately my application uncompressed, but I'm not sure if you'll be able to test it because the DLL injection happens on the process of a game instead of Skype.

I modified my DLL Injection method by injecting an ASM stub (``dllInjectAsm``) that calls ``LoadLibrary`` in the target process and also ``GetLastError`` by using function pointers:
```c++
typedef HMODULE (WINAPI *LoadLib)(LPCTSTR lpFileName);
typedef DWORD (WINAPI *GetLastErr)(void);

struct dllInjectData {
    DWORD loadLib, getLastErr;
    char dllPath[MAX_PATH];
};

void dllInjectAsm(dllInjectData *dllData){
    DWORD ret = (DWORD)LoadLib(dllData->loadLib)(dllData->dllPath);
    if(!ret){
        ret = (DWORD)GetLastErr(dllData->getLastErr)();
    }
}
```
I get the value of ``ret`` by calling ``GetExitCodeThread`` on the thread created by ``CreateRemoteThread``. Its value can be the address of the DLL in the target process or the error returned by ``GetLastError``. So far, I'm getting the error [0x3E6 Invalid access to memory location - ERROR_NOACCESS](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681388(v=vs.85).aspx). This error happens on UPX 3.92, 3.93 and the devel build I mentioned. Version 3.91 works well.

I will try to collect more details but so far that's all the info that I have.

**Comment by reliasn** [comment]
Just updating my issue for the latest UPX 3.94.

I released a 64-bit version of my application and this problem doesn't seem to happen on 64-bit.
However, the 32-bit version still gives me the error that I described above. UPX 3.91 works well for both.
