### ISSUE TITLE
need help，I can't use upx -d unpack file 

### ISSUE THREAD

**Issue by zlyuan99** [upx/upx#543]
## What's the problem (or question)?
I use vim open file see this:
![image](https://user-images.githubusercontent.com/30078049/145329891-15d213c7-db60-42c8-9a70-bc97db34021a.png)

and i do this:

[root@localhost  upx-3.91_linux]# file unknow_file
_unknow_file: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, stripped_

[root@localhost upx-3.91_linux]# ldd unknow_file
        _not a dynamic executable_

[root@localhost upx-3.91_linux]# strings unknow_file
`7tQ
/lib64
nux-x86-
so.2
!CRt
__gmon_start
cke6
ht)s
popen
,ftime
fg:s
msIp
_add
mall
Mdi y
5*Gmk
scep
ccesrcmp
[FLIBC_2.
q#HH
 2G#r
H!gwt
<@~"
,@I>
p)/9
te2<
m[z;
#$7!
K       $X
ra`H>_
v -
f /u
nero
/flmf+
k/TW
9CC5
N/pr
l%3m
ses/
utl
Edeb
        ev/n
ull H
(>&1F
eog34
fs2
5oh6C
        ef |
 gr)
 az
zi00
,o0 |
|ome
TO C    r
' Li
`       LWU
fCBn`;/M
ICd     H
YgL3
UxL2
dlbm
Vyby
        9mMU    0v
4_RvcH
ByZC
1d'wvM
        Zn}
;lYi1
~kZW'
Y8qI
MS+4
'vZ
jchot    "==2
st      ==
jZX}    Nz
MvKi
AvdT    E
a7{>;
3}<;
V0bCY8z
;dsZ
YrID1
7wgMj
        |'Bwp
|s      =s
^i      nIHK
pbnQ
9Jw=
L2I(
yAtc
;f      +IU     Cew
9U'YhU  nVs/
Wi      rt
o ui
awks
{ pr
$2 }
        "/"
        :       w`
fyd op
\2IG
8;^wZ
swI8B
        ea+
        :W(e:'
<;Oga
UUFl
DQk     wMTRLG
w       aNy
VFB     Q0J
        MDE0A
Genu
-1FA
Ft      F-+
3_6t
0406
}1cc
{&#O
1[      4;
['f6h9
KXY1a
d$)-
{8L)
L        \(L
FGHIJKLMNOPQRSTUVW
ghijk<n
tuvwxyz0123456789+P
92.168.0.47
-%08X
        Y%\
gw/u~
+xrlW
]b/w
lv'2
#uN -
R9gtB
k'b`
&d3Z
=xlMw
{ 8.`
>N^
wkill -
USQRH
PROT_EXEC|PROT_WRITE failed.
$Info: This file is packed with the
 executable packer http://
.sf.net $
$Id:
 3.91 Copyright (C) 1996-2013 the
 Team. All Rights Reserved. $
_j<X
j2AZE)
/proc/self/exe
IuJH
Y^_H
nW*)
DOt$
[wkA
([]A\A]
t)'_
Ys/,
AVJG
SAhL
t%$<$
@bQsA
}[ `
?;Iy
;lBs&
dhA^A_
VFr@k
xAZt?
uE8*
IHAv|
GCC: (GNU) 4.
7 201
Red Hat
-17)
.symtab
trh     interp
rno.ABI-
gnuo
.build-id
ha8     dyn
vDsi
rela(
pltri
texf
eh_frame_hdr
koK     ctoQp
jcr|
,[Gbs&com;t
<9$
K'ON6?
?-?8e
&M O
OLv$
{WBd
TGl'(C
7`OgO
bCF?v
`/dy
@>P_
.V_j
(=/A
O(rv
call_gm[k
Ustart
ff.c
__CTOR_LIST
D{;`'JC
doClobKE
b_K_auP
/'pleted.635N
dummyg/
}ENDKFRAME
ecsa
6Z_GLOBAW
L_OFFSE
TABLE=
62r,y_end
YN{IC
mkti
@@TIBC_2.
su_{snpr
f%eb
Jv_RegisXhk
;she
f} &gy
a+Hic
sUkops.
~IO{|
uGdK*em4($'
ir!pqs
srccmzbNn
qepg
'IsFi
Foi8
}Us2
hfXY

![image](https://user-images.githubusercontent.com/30078049/145331062-5a1ffccb-b87a-4277-9aaf-a8ac9d62b675.png)

## How can we reproduce the issue?

1. help me look is this file packed by UPX ?
2. if yes, how can i unpack, use which version?
3. thanks 
4. the file [https://drive.google.com/file/d/1cPw8EGl1ehV7xzAv_sXRJA982Gt35gqG/view?usp=sharing](url)

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* upx 3.91
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
The file `unknow_file` with sha256sum `1b7fc864e9bc82e71bec3e3d559f1d8a27e39df04d9ffb00142b92fb0c40d5c3` is output from compression by upx, but later modified by overwriting selected bytes so that the existing offline de-compression code in `upx -d` no longer recognizes the file.  The file `unknow_file` should be treated as malware.  Do not use it.  Increase your doubt of the trustworthiness of the source from which you obtained it.

**Comment by zlyuan99** [comment]
Yes I trust the file，Can't use upx -d de-compression ,  Is there any other way to  view  source code?

**Comment by zlyuan99** [comment]
thanks  your help

**Comment by bitraid** [comment]
> Yes I trust the file，Can't use upx -d de-compression , Is there any other way to view source code?

Since you know (?) assembly, you can easily unpack the file using a debugger.

**Comment by jreiser** [comment]
@zlyuan99   Compress a known-good file, then look at the output, much like you did in the original Description above, especially the region highlighted in red.  Comparing the two, then you might be able to guess what was modified.

If not, then run 5 simultaneous Terminal sessions: one: a text editor on `p_lx_elf.cpp`, then: two pairs of (text editor on output of `od -Ax -tx4c <filename>`, `gdb` on `upx.out`) where one `<filename>` is `unknow_file`, and the other `<filename>` is a compressed good file.  In each gdb, put a breakpoint on the first line of `PackLinuxElf64::canUnpack`, then `(gdb) run -d -f -o <filename>.decompressed`.  When gdb hits the breakpoint, then `(gdb) step` while following execution in the text editor and the results of calls to `seek()` and `readx()` using `x/<addr> <n>` in gdb (or in the output of `od`).  Observe the difference between `canUnpack()` returning `false` for `unknow_file` but `true` for the known-good file.  Finally, use a binary file editor to undo the malicious changes to `unknow_file`, then invoke `upx -d`.
