### ISSUE TITLE
PE: Relocations are written twice

### ISSUE THREAD

**Issue by kornelpal** [upx/upx#547]
## What's the problem (or question)?
Relocations are written twice. The following line appears three times in `PeFile::pack0`, but executed only twice because of the `last_section_rsrc_only` conditions:
```cpp
fo->write(oxrelocs,soxrelocs);
```

## What should have happened?
Only one copy of the relocations should be written.

## Do you have an idea for a solution?
I think that the[ one without a `last_section_rsrc_only` condition](https://github.com/upx/upx/blob/5d1347a359bb63c9e67bf2a6499ed5bc1184de08/src/pefile.cpp#L2680) is not needed as the location of the other two are consistent with `PeFile::callProcessRelocs`. There might be something else that needs to be corrected to avoid breaking resources written after relocations.

## How can we reproduce the issue?
Found by reading the source code.

## Please tell us details about your environment.
N/A

**Comment by ml1050** [comment]
You're right. Line 2680 is not needed.
