### ISSUE TITLE
Trojan.Genneric

### ISSUE THREAD

**Issue by zuozhehao** [upx/upx#548]
## What's the problem (or question)?

```
#include <iostream>

int main()
{
    std::cout << "Hello World!\n";
}
```

I didn't do anything，command I use `upx -2 Test.exe`

![20211220173835](https://user-images.githubusercontent.com/4464252/146746475-d711b3c1-40d5-4ab0-be08-38262a368640.png)

When I use the `upx --best Test.exe`  parameter
![1639993586(1)](https://user-images.githubusercontent.com/4464252/146747032-97a05f05-6398-403d-a1e2-be0d60f93709.png)

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): UPX git-5d1347
* Host Operating System and version: win10
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by bitraid** [comment]
See pinned issue https://github.com/upx/upx/issues/437.

**Comment by jreiser** [comment]
Also, please include the name and version number of the program which claimed that `C:\text.exe` was a trojan.
