### ISSUE TITLE
Option '--lzma' doesn't seem to be documented in the man page or in 'upx --help'

### ISSUE THREAD

**Issue by mss1451** [upx/upx#549]
## What's the problem (or question)?

Typing 'upx --help' or 'man upx' should show that I can also use '--lzma' option for better compression but I can't find it. It seems to be only mentioned in the [NEWS](https://github.com/upx/upx/blob/devel/NEWS) file.
## What should have happened?

Documentation should include '--lzma' option and any other options if they are also not documented.
## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.96-git-d7ba31cab8ce+
* Host Operating System and version: 5.15.10-artix1-1 x86_64 GNU/Linux
* Host CPU architecture: 64-bit
* Target Operating System and version: 5.15.10-artix1-1 x86_64 GNU/Linux
* Target CPU architecture: 64-bit

**Comment by jreiser** [comment]
Lzma does appear in `--help`:
```
$  ./upx.out --help  |  grep lzma
  --lzma              try LZMA [slower but tighter than NRV]
```
If you have specific proposals for changes in the documentation, then please submit a `pull` request that embodies those changes.
