### ISSUE TITLE
chocolate-doom.exe v2.3.0 crashes once packed with `--brute` or above

### ISSUE THREAD

**Issue by Kroc** [upx/upx#55]
## What's the problem (or question)?

chocolate-doom.exe (v2.3.0) will not launch after packing with UPX when either `--brute` or `--ultra-brute`. You can download chocolate-doom from here: https://www.chocolate-doom.org/wiki/index.php/Downloads

## What should have happened?

Obviously, it should not crash.

## Do you have an idea for a solution?

No, I have no concept of why this happens.

## How can we reproduce the issue?

```
upx.exe --brute chocolate-doom.exe
```

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.92w
* Operating System and version: Windows 10 x64
* CPU architecture: Intel Celeron x64

**Comment by markus-oberhumer** [comment]
BTW, does it work with upx 3.91 ?

**Comment by markus-oberhumer** [comment]
Please try the fresh UPX 3.93 release and close this issue if fixed.

**Comment by Kroc** [comment]
Working again, thanks so much!
