### ISSUE TITLE
Bad reloc[0xcbb] = 0x3c540 during compression

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#552]
## What's the problem (or question)?

An error occurred:
Bad reloc[0xcbb] = 0x3c540
during compression
## What should have happened?

normal compression of input exe

## How can we reproduce the issue?

1. compress https://css-ig.net/bin/pingo-win64.zip
2. with https://github.com/upx/upx/suites/4789894651/artifacts/133974870

## Please tell us details about your environment.

* UPX version used (`upx --version`): https://github.com/upx/upx/suites/4789894651/artifacts/133974870
* Host Operating System and version: 11x64
* Host CPU architecture: x64
* Target Operating System and version: 11x64
* Target CPU architecture: x64

**Comment by jreiser** [comment]
@kornelpal After the latest commit on `devel`, I now see:
```
upx.out: pefile.cpp:2601: void PeFile::pack0(OutputFile*, ht&, ht&, unsigned int, upx_uint64_t, bool) [with LEXX = LE64; ht = PeFile64::pe_header_t; upx_uint64_t = long long unsigned int]: Assertion `(soxrelocs == 0) == !has_oxrelocs' failed.
```
for this testcase `pingo.exe`.  Please investigate.

**Comment by kornelpal** [comment]
@jreiser, pull request #553 fixes the assertion and compression is now successful. (I haven't tested the problem described in this issue.)

**Comment by jreiser** [comment]
@necros2k7 The merge onto `devel` enables successful compression. Auto-builds are available on https://github.com/upx/upx/actions/runs/1641716844 .
