### ISSUE TITLE
Update README: remove AArch64 bullet point

### ISSUE THREAD

**Issue by sdavids** [upx/upx#557]
## What's the problem (or question)?

https://upx.github.io/main/2017/05/12/UPX-3.94-released.html
> This release adds support for arm64-linux (aka “aarch64”) 

https://github.com/upx/upx/blob/a46b63817a9c6ad5af7cf519332e859f11558592/README#L92-L95

## What should have happened?
The bullet point should have been removed or modified to`AArch64 (64-bit ARM) for iOS.`

## Do you have an idea for a solution?
--

## How can we reproduce the issue?
--

## Please tell us details about your environment.
--

**Comment by markus-oberhumer** [comment]
Fixed on devel4 branch.
