### ISSUE TITLE
"upx" command doesn't appear on windows.

### ISSUE THREAD

**Issue by proxdxd03** [upx/upx#558]
## What's the problem (or question)?
If I download UPX and run the upx.exe, a command line window appears and instantly closes again. If I then try to use the `upx` command, it is not known.

## What should have happened?
The command should appear and compress the EXE file.

## How can we reproduce the issue?
1. Download UPX (windows 32bit or 64 bit).
2. Unzip the download.
3. Open the upx.exe in the ZIP.
4. Open the command line and enter `upx --best "SomeApp.exe"`.

## Please tell us details about your environment.
* UPX version used (`upx --version`): Newest
* Operating System and version: Microsoft Windows 10 Pro
* CPU architecture: Intel Core i7-7660U

**Comment by jreiser** [comment]
`upx-3.95-win64.zip` is a container for transporting 11 files easily; it is not an installer.  See https://github.com/upx/upx/pull/542 for one possible installer; there are others.
