### ISSUE TITLE
Error while trying to build

### ISSUE THREAD

**Issue by luckynzm** [upx/upx#567]
## What's the problem (or question)?

Hi, im getting this error while trying to build from git
```
./../src/stub/scripts/check_whitespace_git.sh ./..
ERROR: hard TAB detected ./src/stub/tools/macho-snip/udf.s: 	.align 4
```
## What should have happened?

It should build?
## Do you have an idea for a solution?

Not really
## How can we reproduce the issue?

1.Clone the repo as of now
2. run make
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): Current devel branch (i think that's how you say it?)
* Host Operating System and version: Artix Linux 5.16.10-artix1-1
* Host CPU architecture: x86_64
* Target Operating System and version: N/A
* Target CPU architecture: N/A

**Comment by jreiser** [comment]
A good way to specify the version when executable does not build: `git log -n 1  |  sed 1q`.
Please try tip of `devel` branch now; see commit above.
