### ISSUE TITLE
Rust musl binary packing gives error

### ISSUE THREAD

**Issue by sonicrules1234** [upx/upx#568]
## What's the problem (or question)?
Instead of packing the executable, it gives an error instead.  This happens with both the stable and devel versions, but it might be a different error on the stable version.
```
[westly@manjaro] ~/rustprojects/upx-test-musl $ ../../upx/src/upx.out --best --lzma target/x86_64-unknown-linux-musl/release/upx-test-musl                                                    07:48:28
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-b9b1f3  Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx.out: target/x86_64-unknown-linux-musl/release/upx-test-musl: CantPackException: bad nbucket 0


Packed 0 files.

WARNING: this is an unstable beta version - use for testing only! Really.
```

## What should have happened
Successfully pack the executable.

## How can we reproduce the issue?

1. Compile rust program with the x86_64-unknown-linux-musl target.
2. run upx --best --lzma <path/to/executable>
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.0.0 git
* Host Operating System and version: Manjaro Linux
* Host CPU architecture: x86_64
* Target Operating System and version:
* Target CPU architecture:
[upx-test-musl.zip](https://github.com/upx/upx/files/8237822/upx-test-musl.zip)

**Comment by jreiser** [comment]
Fixed on `devel` branch:
```
$ ../upx.out -f -o foo upx-test-musl
UPX git-53f41a+ Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   3752224 ->    969836   25.85%   linux/amd64   foo              
```

**Comment by sonicrules1234** [comment]
Thanks, seems to work.
