### ISSUE TITLE
Packing FreeBSD on MacOS fails.

### ISSUE THREAD

**Issue by davidnewhall** [upx/upx#569]
## What's the problem (or question)?
Packing minimal Freebsd 386 binary on MacOS fails.

"32 bit freebsd throwing an error too, while packing on macOS (x86_64)."

## What should have happened?
Working executable should have been produced.

## Do you have an idea for a solution?
Sorry, no. :(

## How can we reproduce the issue?

Test code (`./cmd/main.go`): 
```
package main

func main() {
	println("working")
}
```

Compile command:
```
GOOS=freebsd GOARCH=386 go build ./cmd -o t
```

UPX output:
```
$ upx ./t
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: ./t: InternalError: can not apply reloc 'LEXEC000:1' without section 'LEXEC025'
```

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.96
* Host Operating System and version:  macOS 10.14.6
* Host CPU architecture: x86_64
* Target Operating System and version: FreeBSD
* Target CPU architecture: 386
*  Go version go1.17.6 darwin/amd64

**Comment by jreiser** [comment]
@davidnewhall Please upload or supply a direct URL to the executable ELF file which fails (in this case, `./t`).  See the line "Attach files by ..." at the bottom of every Comment entry widget here on GitHub; compress the upload with gzip, zip, or .tgz.  This avoids several problems with re-constructing development environments and versions.

**Comment by davidnewhall** [comment]
[helloworld.zip](https://github.com/upx/upx/files/8258968/helloworld.zip)

**Comment by davidnewhall** [comment]
Very customer-focused bot. Cool.
