### ISSUE TITLE
Add support for macOS dylib compression.

### ISSUE THREAD

**Issue by feicong** [upx/upx#57]
## What's the problem (or question)?
upx 3.93 do not support macOS dylib's compression.

## What should have happened?
cat ./hello
`#include <stdio.h>

static void hello() {
	printf("hello\n");
}`

$ clang -v
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ cc -dynamiclib -o ./hello ./hello.c 
$ upx ./hello
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.93        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 29th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: ./hello: UnknownExecutableFormatException

Packed 0 files.

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):3.93
* Operating System and version:macOS 10.11.6,XCode 8.2, clang v8.0
* CPU architecture: x86_64

**Comment by markus-oberhumer** [comment]
I've changed the title of your bug report - please correct it if you disagree.

**Comment by jreiser** [comment]
The "help-wanted" tag arises because I do not know what the MacOS dynamic loader assumes about a .dylib.  See the comment about ELF dynamic libraries in p_lx_elf.cpp:
```
        // Heuristic HACK for shared libraries (compare Darwin (MacOS) Dylib.)
        // If there is an existing DT_INIT, and if everything that the dynamic
        // linker ld-linux needs to perform relocations before calling DT_INIT
        // resides below the first SHT_EXECINSTR Section in one PT_LOAD, then
        // compress from the first executable Section to the end of that PT_LOAD.
        // We must not alter anything that ld-linux might touch before it calls
        // the DT_INIT function.
        //
        // Obviously this hack requires that the linker script put pieces
        // into good positions when building the original shared library,
        // and also requires ld-linux to behave.
```
Similar knowledge is needed about .dylib.

**Comment by feicong** [comment]
Mach-O file header struct mach_header/mach_header_64 has a field to determinate what the macho type is.
`
struct mach_header_64 {
	uint32_t	magic;		/* mach magic number identifier */
	cpu_type_t	cputype;	/* cpu specifier */
	cpu_subtype_t	cpusubtype;	/* machine specifier */
	uint32_t	filetype;	/* type of file */
	uint32_t	ncmds;		/* number of load commands */
	uint32_t	sizeofcmds;	/* the size of all the load commands */
	uint32_t	flags;		/* flags */
	uint32_t	reserved;	/* reserved */
};
`

the filetype maybe:
`
#define	MH_OBJECT	0x1		/* relocatable object file */
#define	MH_EXECUTE	0x2		/* demand paged executable file */
#define	MH_FVMLIB	0x3		/* fixed VM shared library file */
#define	MH_CORE		0x4		/* core file */
#define	MH_PRELOAD	0x5		/* preloaded executable file */
#define	MH_DYLIB	0x6		/* dynamically bound shared library */
#define	MH_DYLINKER	0x7		/* dynamic link editor */
#define	MH_BUNDLE	0x8		/* dynamically bound bundle file */
#define	MH_DYLIB_STUB	0x9		/* shared library stub for static */
					/*  linking only, no section contents */
#define	MH_DSYM		0xa		/* companion file with only debug sections */
#define	MH_KEXT_BUNDLE	0xb		/* x86_64 kexts */
`

MH_DYLIB means macho is a dylib.
`
$ otool -h ./libunderstandpatcher.dylib 
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           6    17       2056 0x00100085

$ otool -hv ./libunderstandpatcher.dylib 
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64  X86_64        ALL  0x00       DYLIB    17       2056   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS
`

like elf DT_INIT function init tricks, macho did this by "__DATA$__mod_init_func" section.
when dyld load macho dylib done, call runDyldInitializers() to run init funcs, code in dyldInitialization.cpp like this:
`
#if DYLD_INITIALIZER_SUPPORT

typedef void (*Initializer)(int argc, const char* argv[], const char* envp[], const char* apple[]);

extern const Initializer  inits_start  __asm("section$start$__DATA$__mod_init_func");
extern const Initializer  inits_end    __asm("section$end$__DATA$__mod_init_func");

//
// For a regular executable, the crt code calls dyld to run the executables initializers.
// For a static executable, crt directly runs the initializers.
// dyld (should be static) but is a dynamic executable and needs this hack to run its own initializers.
// We pass argc, argv, etc in case libc.a uses those arguments
//
static void runDyldInitializers(const struct macho_header* mh, intptr_t slide, int argc, const char* argv[], const char* envp[], const char* apple[])
{
	for (const Initializer* p = &inits_start; p < &inits_end; ++p) {
		(*p)(argc, argv, envp, apple);
	}
}
#endif // DYLD_INITIALIZER_SUPPORT
`

  
eg:
`
$ otool -s __DATA __mod_init_func ./libunderstandpatcher.dylib 
./libunderstandpatcher.dylib:
Contents of (__DATA,__mod_init_func) section
0000000000001050	00 0d 00 00 00 00 00 00
`
0xD00 pointer to my _init_func() function in __TEXT,__text section:
`
$ otool -tv ./libunderstandpatcher.dylib 
./libunderstandpatcher.dylib:
(__TEXT,__text) section
_init_funcs:
0000000000000d00	pushq	%rbp
0000000000000d01	movq	%rsp, %rbp
0000000000000d04	subq	$0x40, %rsp
0000000000000d08	leaq	0x1e9(%rip), %rdi
0000000000000d0f	movb	$0x0, %al
0000000000000d11	callq	0xe82
0000000000000d16	leaq	0x1f8(%rip), %rdi
0000000000000d1d	movl	$0x2, %esi
0000000000000d22	movl	%eax, -0x14(%rbp)
0000000000000d25	callq	0xe70
`

**Comment by jreiser** [comment]
Analysis and strategy: Based on comment from @feicong and some experimentation with
```
#include <stdio.h>

static void hello() {
	printf("hello\n");
}

int my_var;

void
__attribute__((__constructor__))
my_init(int argc, char const *const argv[], char const *const envp[], char const *const apple[])
{
    my_var = argc;
}
```
it looks like I should insert the offset of the UPX decompressor stub at the beginning of the (__DATA, __mod_init_func) section, or create such a section if it does not exist.  Building that program with flag -dynamiclib and applying "otool -r" after linking shows no relocations, so the dylinker must apply implicitly the runtime base address ('slide' value) to the offset.  The .dylib has no __PAGEZERO segment, has __TEXT.vmaddr==0, and __LINKEDIT.initprot==VM_PROT_READ (no VM_PROT_EXECUTE, although __LINKEDIT.maxprot does allow it.)  Any segment with VM_PROT_WRITE might be relocated by the dylinker before calling the __mod_init_funcs, and __LINKEDIT belongs to dylinker; so the __TEXT segment is the only one that can be compressed.  The compressed .dylib will have a smaller __TEXT.filesize, and other segments will slide by pages towards the beginning of the file, but other LC_SEGMENT_64 parameters will remain the same (except for the additional __mod_init_func.)

**Comment by feicong** [comment]
yes, the  (__DATA, __mod_init_func) section must be exists or created. 
get macho's relocation entries can view llvm's source code `llvm/tools/llvm-readobj/MachODumper.cpp-> MachODumper::printRelocations()`, i test same app also is null.
```
llvm-readobj -r `which python`

File: /usr/bin/python
Format: Mach-O 32-bit i386
Arch: i386
AddressSize: 32bit
Relocations [
]

File: /usr/bin/python
Format: Mach-O 64-bit x86-64
Arch: x86_64
AddressSize: 64bit
Relocations [
]

$ ./llvm-readobj -r ~/Program/insert_dylib

File: /Users/mbp/Program/insert_dylib
Format: Mach-O 64-bit x86-64
Arch: x86_64
AddressSize: 64bit
Relocations [
]
```

yes the first writable seg is reloa addr.
```
template <typename A>
void Rebaser<A>::calculateRelocBase()
{
	const std::vector<MachOLayoutAbstraction::Segment>& segments = fLayout.getSegments();
	if ( fHeader->flags() & MH_SPLIT_SEGS ) {
		// reloc addresses are from the start of the first writable segment
		for(std::vector<MachOLayoutAbstraction::Segment>::const_iterator it = segments.begin(); it != segments.end(); ++it) {
			const MachOLayoutAbstraction::Segment& seg = *it;
			if ( seg.writable() ) {
				// found first writable segment
				fOrignalVMRelocBaseAddress = seg.address();
				fOrignalVMRelocBaseAddressValid = true;
			}
		}
	}
	else {
		// reloc addresses are from the start of the mapped file (base address)
		fOrignalVMRelocBaseAddress = segments[0].address();
		fOrignalVMRelocBaseAddressValid = true;
	}
```

**Comment by jreiser** [comment]
@feicong  How much of the __TEXT segment can be compressed, and how much of the section_64 commands that point into __TEXT?    Logically it seems that from __TEXT.__text.offset to __TEXT.filesize should be compressible; this *omits* from the beginning of the file through the end of all the load_command.  I suppose it would be a good idea to check that in __TEXT all section_64.nreloc are 0, because otherwise the dylinker will relocate (scribble on) compressed bytes before they are de-compressed.

Can the __TEXT.section_64 command structs themselves be omitted [but do compress and retain the data that they point to], except for the first one __TEXT.__text (whose .offset marks the end of the area that can be used to add new load_commands such as code signing, etc.)?  I see other section names such as  __stubs, __stub_helper, __const, __cstring, __unwind_info.  Presumably the dynamic linker (the only code that runs before the upx de-compressor stub) does not care about any of these except perhaps __unwind_info.  Does runtime exception handling rely on finding __unwind_info, and when are the pointers to it discovered and cached?

I have made enough progress that I am debugging a live compressed shared library after dylinker has called its initialization function (upx de-compressor stub.)  I'd like to reduce the remaining trial-and-error.

**Comment by jreiser** [comment]
@feicong My test case (similar to Feb.5) runs correctly using 'devel' branch.  How well does it work for you?

**Comment by feicong** [comment]
still error.

```
upx_devel $ ./src/upx.out ~/Desktop/hello
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX git-4854c0+ Markus Oberhumer, Laszlo Molnar & John Reiser   May 13th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx.out: ~/Desktop/hello: NotCompressibleException

Packed 1 file: 0 ok, 1 error.

WARNING: this is an unstable beta version - use for testing only! Really.
```

**Comment by jreiser** [comment]
The compiled version of this input file <i>is</i> too small to compress: only 4KiB of __TEXT.  Un-commenting the <tt>//</tt> lines gives 45056 bytes of __TEXT, which is enough to compress.  Generally the cross-over is somewhere in the middle.
```
/* cc -dynamiclib -o ./hello.dylib ./hello.c */
#include <stdio.h>

static void hello() {
	printf("hello\n");
}

int my_var;

//int const x[10000] = {1,2,3};

int
__attribute__((__constructor__))
my_init(int argc, char const *const argv[], char const *const envp[], char const *const apple[])
{
    my_var = argc;
    return 5;  //return x[2];
}
=====
$ size hello.dylib   # too small with "//" comments
__TEXT	__DATA	__OBJC	others	dec	hex
4096	4096	0	4096	12288	3000	
$ size hello.dylib   # compressible after un-commenting
__TEXT	__DATA	__OBJC	others	dec	hex
45056	4096	0	4096	53248	d000	
```

In addition, the <tt>devel</tt> branch contains a fix for a botched edit sometime last year.

**Comment by feicong** [comment]
thx, i tested it. now it can be compiled. but can't be loaded by `dlopen`.

```$ size hello.dylib
__TEXT	__DATA	__OBJC	others	dec	hex
45056	4096	0	4096	53248	d000

$ size hello2.dylib
__TEXT	__DATA	__OBJC	others	dec	hex
0	4096	0	4096	8192	2000

$ lldb
...
(lldb) file
error: 'target create' takes exactly one executable path argument, or use the --core option.
(lldb) target create ~/Documents/project/upx_devel/src/upx
error: unable to find executable for '~/Documents/project/upx_devel/src/upx'
(lldb) b main
Breakpoint 1: where = upx.out`main at main.cpp:1411, address = 0x000000010002e250
(lldb) r
Process 77109 launched: '~/Documents/project/upx_devel/src/upx.out' (x86_64)
Process 77109 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x000000010002e250 upx.out` main(argc=-1951509963, argv=0x0000000000000000)  at main.cpp:1411
   1408	#endif
   1409
   1410	int __acc_cdecl_main main(int argc, char *argv[])
-> 1411	{
   1412	    int i;
   1413	    static char default_argv0[] = "upx";
   1414	//    int cmdline_cmd = CMD_NONE;
Target 0: (upx.out) stopped.
(lldb) po dlopen("~/Desktop/hello2.dylib", 0)
 nil
(lldb) po dlopen("~/Desktop/hello.dylib", 0)
0x0000000101000300

(lldb) po dlsym(0x0000000101000300, "my_init")
0x0000000100360340

(lldb) po dlsym(0x0000000101000300, "my_var")
0x000000010036a008
```

**Comment by feicong** [comment]
there is a little problem with compiling code. line 53 of the Makefile needs to be modified on my system.

before:
```
LIBS += -lucl -lz
```
after:
```
LIBS += -lucl -lz -lc++
```

**Comment by jreiser** [comment]
Please tell me which symbols are supplied by "-lc++", or some other reason for needing it.

**Comment by jreiser** [comment]
dlopen() should work now.

**Comment by feicong** [comment]
ok, the dylib can be loaded now. but dlopen() emit a error output(It may not affect dylib execution?).

```
(lldb) po dlopen("/Users/rmbp/Desktop/hello.dylib", 0)
error: unable to find section for section 5
0x0000000100402650

(lldb) po dlsym(0x0000000100402650, "my_var")
0x000000010036b008

(lldb) po dlsym(0x0000000100402650, "my_init")
0x0000000100361340
```

btw: `-lc++` used by link stl part. If you do not add this parameter, you will return the following error:

```
$ make CXX=clang UPX_UCLDIR=/usr/local/opt/ucl BUILD_TYPE_DEBUG=1 all -j8
Updating .depend
clang '-DUPX_VERSION_GITREV="563165e6ae23"' -I/usr/local/opt/ucl/include -O0 -g -fno-strict-aliasing -fwrapv -funsigned-char -Wall -W -Wcast-align -Wcast-qual -Wmissing-declarations -Wpointer-arith -Wshadow -Wvla -Wwrite-strings -Werror -o help.o -c help.cpp
clang -O0 -g -fno-strict-aliasing -fwrapv -funsigned-char -Wall -W -Wcast-align -Wcast-qual -Wmissing-declarations -Wpointer-arith -Wshadow -Wvla -Wwrite-strings -Werror -o upx.out c_file.o c_init.o c_none.o c_screen.o compress.o compress_lzma.o compress_ucl.o compress_zlib.o except.o file.o filter.o filteri.o help.o lefile.o linker.o main.o mem.o msg.o p_armpe.o p_com.o p_djgpp2.o p_exe.o p_lx_elf.o p_lx_exc.o p_lx_interp.o p_lx_sh.o p_mach.o p_ps1.o p_sys.o p_tmt.o p_tos.o p_unix.o p_vmlinx.o p_vmlinz.o p_w32pe.o p_w64pep.o p_wcle.o packer.o packer_c.o packer_f.o packhead.o packmast.o pefile.o s_djgpp2.o s_object.o s_vcsa.o s_win32.o snprintf.o stdcxx.o ui.o util.o work.o -lucl -lz
Undefined symbols for architecture x86_64:
  "std::exception::what() const", referenced from:
      vtable for Throwable in except.o
      vtable for CantPackException in except.o
      vtable for Exception in except.o
      vtable for CantUnpackException in except.o
      vtable for UnknownExecutableFormatException in except.o
      vtable for NotCompressibleException in except.o
      vtable for AlreadyPackedException in except.o
      ...
  "std::exception::~exception()", referenced from:
      Throwable::Throwable(char const*, int, bool) in except.o
      Throwable::Throwable(Throwable const&) in except.o
      Throwable::~Throwable() in except.o
  "std::terminate()", referenced from:
      ___clang_call_terminate in compress_lzma.o
      ___clang_call_terminate in file.o
      ___clang_call_terminate in linker.o
      ___clang_call_terminate in mem.o
      ___clang_call_terminate in packmast.o
      ___clang_call_terminate in pefile.o
      ___clang_call_terminate in ui.o
      ...
  "typeinfo for std::bad_alloc", referenced from:
      GCC_except_table4 in work.o
      typeinfo for std::bad_alloc* in work.o
  "typeinfo for std::exception", referenced from:
      typeinfo for Throwable in except.o
      GCC_except_table4 in work.o
      typeinfo for std::exception* in work.o
  "vtable for __cxxabiv1::__class_type_info", referenced from:
      typeinfo for COutBufferException in compress_lzma.o
      typeinfo for IUnknown in compress_lzma.o
      typeinfo for NCompress::NLZMA::CBaseState in compress_lzma.o
      typeinfo for CMyUnknownImp in compress_lzma.o
      typeinfo for CLZInWindow in compress_lzma.o
      typeinfo for IMatchFinderSetNumPasses in compress_lzma.o
      typeinfo for File in file.o
      ...
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for __cxxabiv1::__pointer_type_info", referenced from:
      typeinfo for std::bad_alloc* in work.o
      typeinfo for std::exception* in work.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for __cxxabiv1::__si_class_type_info", referenced from:
      typeinfo for ICompressCoder in compress_lzma.o
      typeinfo for ICompressSetOutStream in compress_lzma.o
      typeinfo for ICompressSetCoderProperties in compress_lzma.o
      typeinfo for ICompressWriteCoderProperties in compress_lzma.o
      typeinfo for ISequentialInStream in compress_lzma.o
      typeinfo for ISequentialOutStream in compress_lzma.o
      typeinfo for ICompressProgressInfo in compress_lzma.o
      ...
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for __cxxabiv1::__vmi_class_type_info", referenced from:
      typeinfo for NCompress::NLZMA::CEncoder in compress_lzma.o
      typeinfo for MyLzma::InStream in compress_lzma.o
      typeinfo for MyLzma::OutStream in compress_lzma.o
      typeinfo for MyLzma::ProgressInfo in compress_lzma.o
      typeinfo for NBT2::CMatchFinder in compress_lzma.o
      typeinfo for NBT3::CMatchFinder in compress_lzma.o
      typeinfo for NBT4::CMatchFinder in compress_lzma.o
      ...
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for std::exception", referenced from:
      Throwable::Throwable(char const*, int, bool) in except.o
      std::exception::exception(std::exception const&) in except.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "operator delete[](void*)", referenced from:
      LeFile::~LeFile() in lefile.o
      ElfLinker::~ElfLinker() in linker.o
      PackLinuxElf32::~PackLinuxElf32() in p_lx_elf.o
      PackLinuxElf64::~PackLinuxElf64() in p_lx_elf.o
      PackLinuxElf32::buildLinuxLoader(unsigned char const*, unsigned int, unsigned char const*, unsigned int, Filter const*) in p_lx_elf.o
      PackLinuxElf64::buildLinuxLoader(unsigned char const*, unsigned int, unsigned char const*, unsigned int, Filter const*) in p_lx_elf.o
      PackMachBase<N_Mach::MachClass_32<N_BELE_CTP::BEPolicy> >::~PackMachBase() in p_mach.o
      ...
  "operator delete(void*)", referenced from:
      NBT2::CMatchFinder::~CMatchFinder() in compress_lzma.o
      NBT3::CMatchFinder::~CMatchFinder() in compress_lzma.o
      NBT4::CMatchFinder::~CMatchFinder() in compress_lzma.o
      NHC4::CMatchFinder::~CMatchFinder() in compress_lzma.o
      NCompress::NLZMA::CEncoder::Create() in compress_lzma.o
      NCompress::NLZMA::CEncoder::~CEncoder() in compress_lzma.o
      MyLzma::InStream::~InStream() in compress_lzma.o
      ...
  "operator new[](unsigned long)", referenced from:
      LeFile::readObjectTable() in lefile.o
      LeFile::readPageMap() in lefile.o
      LeFile::readResidentNames() in lefile.o
      LeFile::readEntryTable() in lefile.o
      LeFile::readFixupPageTable() in lefile.o
      LeFile::readFixups() in lefile.o
      LeFile::readNonResidentNames() in lefile.o
      ...
  "operator new(unsigned long)", referenced from:
      NCompress::NLZMA::CEncoder::Create() in compress_lzma.o
      ElfLinker::addSymbol(char const*, char const*, unsigned long long) in linker.o
      ElfLinker::addRelocation(char const*, unsigned int, char const*, char const*, unsigned long long) in linker.o
      ElfLinker::addSection(char const*, void const*, int, unsigned int) in linker.o
      PackArmPe::newLinker() const in p_armpe.o
      PackCom::newLinker() const in p_com.o
      PackDjgpp2::newLinker() const in p_djgpp2.o
      ...
  "___cxa_allocate_exception", referenced from:
      COutBuffer::FlushWithCheck() in compress_lzma.o
      throwCantPack(char const*) in except.o
      throwUnknownExecutableFormat(char const*, bool) in except.o
      throwNotCompressible(char const*) in except.o
      throwAlreadyPacked(char const*) in except.o
      throwNotPacked(char const*) in except.o
      throwChecksumError() in except.o
      ...
  "___cxa_bad_typeid", referenced from:
      printErr(char const*, Throwable const*) in msg.o
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in compress_lzma.o
      NCompress::NLZMA::CEncoder::Code(ISequentialInStream*, ISequentialOutStream*, unsigned long long const*, unsigned long long const*, ICompressProgressInfo*) in compress_lzma.o
      upx_lzma_compress(unsigned char const*, unsigned int, unsigned char*, unsigned int*, upx_callback_t*, int, int, upx_compress_config_t const*, upx_compress_result_t*) in compress_lzma.o
      ___clang_call_terminate in file.o
      ___clang_call_terminate in linker.o
      ___clang_call_terminate in mem.o
      is_dlm(InputFile*, unsigned int) in p_djgpp2.o
      ...
  "___cxa_call_unexpected", referenced from:
      MyAlloc(unsigned long) in compress_lzma.o
      MyFree(void*) in compress_lzma.o
      Throwable::Throwable(char const*, int, bool) in except.o
      Throwable::Throwable(Throwable const&) in except.o
      Throwable::~Throwable() in except.o
      prettyName(char const*) in except.o
  "___cxa_end_catch", referenced from:
      NCompress::NLZMA::CEncoder::Code(ISequentialInStream*, ISequentialOutStream*, unsigned long long const*, unsigned long long const*, ICompressProgressInfo*) in compress_lzma.o
      upx_lzma_compress(unsigned char const*, unsigned int, unsigned char*, unsigned int*, upx_callback_t*, int, int, upx_compress_config_t const*, upx_compress_result_t*) in compress_lzma.o
      is_dlm(InputFile*, unsigned int) in p_djgpp2.o
      handle_allegropak(InputFile*, OutputFile*) in p_djgpp2.o
      try_pack(Packer*, void*) in packmast.o
      try_unpack(Packer*, void*) in packmast.o
      PeFile::canUnpack0(unsigned int, LE16&, LE32&, unsigned int) in pefile.o
      ...
  "___cxa_free_exception", referenced from:
      COutBuffer::FlushWithCheck() in compress_lzma.o
      InputFile::sopen(char const*, int, int) in file.o
      OutputFile::sopen(char const*, int, int, int) in file.o
      do_one_file(char const*, char*) in work.o
  "___cxa_pure_virtual", referenced from:
      vtable for IMatchFinder in compress_lzma.o
      vtable for IInWindowStream in compress_lzma.o
      vtable for IUnknown in compress_lzma.o
      vtable for IMatchFinderSetNumPasses in compress_lzma.o
      vtable for ICompressCoder in compress_lzma.o
      vtable for ICompressSetOutStream in compress_lzma.o
      vtable for ICompressSetCoderProperties in compress_lzma.o
      ...
  "___cxa_rethrow", referenced from:
      try_pack(Packer*, void*) in packmast.o
      try_unpack(Packer*, void*) in packmast.o
  "___cxa_throw", referenced from:
      COutBuffer::FlushWithCheck() in compress_lzma.o
      throwCantPack(char const*) in except.o
      throwUnknownExecutableFormat(char const*, bool) in except.o
      throwNotCompressible(char const*) in except.o
      throwAlreadyPacked(char const*) in except.o
      throwNotPacked(char const*) in except.o
      throwChecksumError() in except.o
      ...
  "___gxx_personality_v0", referenced from:
      MyAlloc(unsigned long) in compress_lzma.o
      MyFree(void*) in compress_lzma.o
      COutBuffer::FlushWithCheck() in compress_lzma.o
      NBT2::CMatchFinder::CMatchFinder() in compress_lzma.o
      CLZInWindow::~CLZInWindow() in compress_lzma.o
      NBT2::CMatchFinder::~CMatchFinder() in compress_lzma.o
      NBT3::CMatchFinder::CMatchFinder() in compress_lzma.o
      ...
ld: symbol(s) not found for architecture x86_64
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [upx.out] Error 1
```

**Comment by jreiser** [comment]
<tt>error: unable to find section for section 5</tt> is from the debugger lldb, which is trying to load debuginfo from the just-loaded shared library.  (UPX has "removed" the debug info by compressing it and putting it where lldb cannot find it.  <tt>upx -d</tt> will restore the degbuginfo from its compressed state; meanwhile lldb cannot read it.  If you want debuginfo at run time, then don't compress.)  The message does not appear (and everything else works as expected) if the debugger is not used.
<tt>-lc++</tt> should be appended automatically when using a C++ final link step.  Try <tt>CXX=clang++</tt> .  In a Makefile, then <tt>CXX</tt> is the traditional abbreviation for "a C++ build tool", and <tt>CC</tt> is the traditional abbreviation for "a C build tool".

**Comment by feicong** [comment]
thx. no problem now. close issue.
