### ISSUE TITLE
Segmentation fault on ppc64le after running compressed binary

### ISSUE THREAD

**Issue by mgiessing** [upx/upx#571]
## What's the problem (or question)?
After applying `upx --lzma` to a binary (specifically protoc-gen-go) it seems to be corrupt and throws a core dump if executed

## What should have happened?
I would expect this to work normally as tests on x86/amd64 works fine without problems.

## Do you have an idea for a solution?
I'm not entirely sure but I have seen issues on other archs relating to page size which is different for IBM Power Systems (ppc64le)

## How can we reproduce the issue?

1. Minimal Dockerfile that has both binaries, the compressed and uncompressed:

```Dockerfile
FROM golang:1.13.4-alpine3.10 as go_builder
RUN apk add --no-cache build-base curl git

RUN mkdir -p ${GOPATH}/src/github.com/golang/protobuf && \
    curl -sSL https://api.github.com/repos/golang/protobuf/tarball/v1.3.2 | tar xz --strip 1 -C ${GOPATH}/src/github.com/golang/protobuf &&\
    cd ${GOPATH}/src/github.com/golang/protobuf && \
    go build -ldflags '-w -s' -o /golang-protobuf-out/protoc-gen-go ./protoc-gen-go && \
    install -Ds /golang-protobuf-out/protoc-gen-go /out/usr/bin/protoc-gen-go

ARG UPX_VERSION
ARG ARCH
RUN echo https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-${ARCH}_linux.tar.xz
RUN mkdir -p /upx && curl -sSL https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-${ARCH}_linux.tar.xz | tar xJ --strip 1 -C /upx && \
    install -D /upx/upx /usr/local/bin/upx

RUN mkdir /out/usr/upx_bin
RUN cp /out/usr/bin/protoc-gen-go /out/usr/upx_bin/protoc-gen-go
RUN upx --lzma /out/usr/upx_bin/protoc-gen-go
WORKDIR /out/usr/
ENTRYPOINT ["/bin/sh"]
```

2. Build like this:

`docker build --build-arg ARCH=powerpc64le --build-arg UPX_VERSION=3.96 -t test_upx .`

4. Exec into the container and run :

`docker run -ti --rm test_upx`

5. Execute both:

```bash
# This works
/out/usr # ./bin/protoc-gen-go 

# This throws an Segmentation fault error:
/out/usr # ./upx_bin/protoc-gen-go 
Segmentation fault (core dumped)
```

I have also tried this on an x86 Linux system (with `docker build --build-arg ARCH=amd64 --build-arg UPX_VERSION=3.96 -t test_upx .` and it works fine there without issues.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
```bash
/out/usr # upx --version
upx 3.96
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Copyright (C) 1996-2020 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2020 Laszlo Molnar
Copyright (C) 2000-2020 John F. Reiser
Copyright (C) 2002-2020 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```
* Host Operating System and version:
```bash
/out/usr # cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.3
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
* Host CPU architecture:
```bash
/out/usr # uname -a
Linux c32bd5bb538d 4.18.0-348.20.1.el8_5.ppc64le #1 SMP Tue Mar 8 12:51:43 EST 2022 ppc64le Linux
```
* Target Operating System and version: same as host
* Target CPU architecture: same as host

**Comment by mgiessing** [comment]
Just for completeness: The `upx --lzma` command runs without issues during the docker build:

```bash
[...]
Step 10/12 : RUN upx --lzma /out/usr/upx_bin/protoc-gen-go
 ---> Running in 3a2753ced1c3
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   4565944 ->   1210448   26.51%  linux/ppc64le  protoc-gen-go

Packed 1 file.
Removing intermediate container 3a2753ced1c3
[...]
```

**Comment by jreiser** [comment]
Please upload or provide a URL to the `protoc-gen-go` executable file, before compression by UPX.  See the "Attach files by ..." in the footer of every Comment entry widget here on GitHub.  Compress the upload using gzip, zip, or .tgz.  Supplying the actual executable avoids problems with reproducing its development environment and all the tools (Alpine, go, docker, etc.)

**Comment by mgiessing** [comment]
Thanks for the quick repsonse! I got you both executables in the zipfile
- protoc-gen-go is the compressed/corrupt file after using upx
- protoc-gen-go_ORIG is the uncompressed/original file that works 
[protoc-gen-go.zip](https://github.com/upx/upx/files/8309297/protoc-gen-go.zip)

**Comment by mgiessing** [comment]
@jreiser Have you been able to investigate this a little bit?

What I figured out, that even a very simple "hello world" Program written in Go suffers from this issue. So I assume there must be something wrong with the packer for ppc64le :/

**Comment by jreiser** [comment]
@mgiessing I don't have any ppc64le hardware, so I use:
```
$  /usr/bin/qemu-ppc64le --version
qemu-ppc64le version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.39)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
$  /usr/bin/gdb-multiarch  --version
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.

$ $GDB
(gdb) target remote :1234

$ $QEMU -strace -g 1234 protoc-gen-go
4503 open("/proc/self/exe",O_RDONLY) = 4
4503 mmap(NULL,1210819,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS,-1,0) = 0x0000004000801000
4503 mmap(0x0000004000801000,1209943,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED,4,0) = 0x0000004000801000
4503 mprotect(0x0000004000926000,10691,PROT_EXEC|PROT_READ) = 0
4503 readlink("/proc/self/exe",0x00000040007ff6bc,4095) = 47
4503 mmap(0x0000000000010000,4718592,PROT_NONE,MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED,-1,0) = 0x0000000000010000
4503 mmap(0x0000000000010000,1987808,PROT_EXEC|PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED,-1,0) = 0x0000000000010000
4503 mprotect(0x0000000000010000,1987808,PROT_EXEC|PROT_READ) = 0
4503 mmap(0x0000000000200000,2378115,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED,-1,0x1f0000) = 0x0000000000200000
4503 mprotect(0x0000000000200000,2378115,PROT_READ) = 0
4503 mmap(0x0000000000450000,108464,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED,-1,0x440000) = 0x0000000000450000
4503 mprotect(0x0000000000450000,108464,PROT_READ|PROT_WRITE) = 0
4503 mmap(0x000000000046b000,149960,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED,-1,0) = 0x000000000046b000
4503 mmap(NULL,4096,PROT_READ,MAP_PRIVATE,4,0) = 0x0000004000929000
4503 close(4) = 0
4503 munmap(0x0000004000801000,1210819) = 0

## The UPX run-time stub has completed its de-compression; protoc-gen-go is running.

4503 open("/proc/self/auxv",O_RDONLY) = 4
4503 read(4,0x7fffa8,1024) = 336
4503 close(4) = 0
4503 sched_getaffinity(0,8192,274886288312,128,0,0) = 8
4503 open("/sys/kernel/mm/transparent_hugepage/hpage_pmd_size",O_RDONLY) = 4
4503 read(4,0x8003a0,20) = 8

## The contents that were read is "2097152\n" which is 2MB on the host x86_64 system.

4503 close(4) = 0
4503 write(2,0x2862dd,13)fatal error:  = 13
4503 write(2,0x28b48b,30)failed to get system page size = 30

## protoc-gen-go did not like 2MB.

4503 write(2,0x283a19,1)
 = 1
4503 write(2,0x28fc4e,46)runtime: panic before malloc heap initialized
 = 46
4503 nanosleep(274886295960,0,1000,0,0,0) = 0
4503 nanosleep(274886295960,0,1000,0,0,0) = 0
4503 write(2,0x286db0,16)
runtime stack:
 = 16
4503 write(2,0x31b050,13)runtime.throw = 13
4503 write(2,0x2839fe,1)( = 1
4503 write(2,0x7ffc5c,8)0x28b48b = 8
4503 write(2,0x283a65,2),  = 2
4503 write(2,0x7ffc60,4)0x1e = 4
4503 write(2,0x283a5b,2))
 = 2
4503 write(2,0x283a1a,1)	 = 1
4503 write(2,0x443f22,34)/usr/local/go/src/runtime/panic.go = 34
4503 write(2,0x283a09,1): = 1
4503 write(2,0x7ffc31,3)774 = 3
4503 write(2,0x283a2b,2) + = 2
4503 write(2,0x7ffc60,4)0x5c = 4
4503 write(2,0x283cbf,4) fp= = 4
4503 write(2,0x7ffc58,12)0x4000800328 = 12
4503 write(2,0x283cdf,4) sp= = 4
4503 write(2,0x7ffc58,12)0x40008002e8 = 12
4503 write(2,0x283cd7,4) pc= = 4
4503 write(2,0x7ffc5d,7)0x3ccec = 7
4503 write(2,0x283a19,1)
 = 1
4503 write(2,0x305088,18)runtime.mallocinit = 18
4503 write(2,0x2839fe,1)( = 1
4503 write(2,0x283a5b,2))
 = 2
4503 write(2,0x283a1a,1)	 = 1
4503 write(2,0x444432,35)/usr/local/go/src/runtime/malloc.go = 35
4503 write(2,0x283a09,1): = 1
4503 write(2,0x7ffc31,3)434 = 3
4503 write(2,0x283a2b,2) + = 2
4503 write(2,0x7ffc5f,5)0x2ec = 5
4503 write(2,0x283cbf,4) fp= = 4
4503 write(2,0x7ffc58,12)0x4000800368 = 12
4503 write(2,0x283cdf,4) sp= = 4
4503 write(2,0x7ffc58,12)0x4000800328 = 12
4503 write(2,0x283cd7,4) pc= = 4
4503 write(2,0x7ffc5d,7)0x19eec = 7
4503 write(2,0x283a19,1)
 = 1
4503 write(2,0x31ce50,17)runtime.schedinit = 17
4503 write(2,0x2839fe,1)( = 1
4503 write(2,0x283a5b,2))
 = 2
4503 write(2,0x283a1a,1)	 = 1
4503 write(2,0x444636,33)/usr/local/go/src/runtime/proc.go = 33
4503 write(2,0x283a09,1): = 1
4503 write(2,0x7ffc31,3)542 = 3
4503 write(2,0x283a2b,2) + = 2
4503 write(2,0x7ffc60,4)0x6c = 4
4503 write(2,0x283cbf,4) fp= = 4
4503 write(2,0x7ffc58,12)0x40008003e0 = 12
4503 write(2,0x283cdf,4) sp= = 4
4503 write(2,0x7ffc58,12)0x4000800368 = 12
4503 write(2,0x283cd7,4) pc= = 4
4503 write(2,0x7ffc5d,7)0x3f80c = 7
4503 write(2,0x283a19,1)
 = 1
4503 write(2,0x335360,14)runtime.rt0_go = 14
4503 write(2,0x2839fe,1)( = 1
4503 write(2,0x7ffc58,12)0x4000800802 = 12
4503 write(2,0x283a65,2),  = 2
4503 write(2,0x7ffc58,12)0x4000800812 = 12
4503 write(2,0x283a65,2),  = 2
4503 write(2,0x7ffc58,12)0x400080081a = 12
4503 write(2,0x283a65,2),  = 2
4503 write(2,0x7ffc58,12)0x400080082a = 12
4503 write(2,0x283a65,2),  = 2
4503 write(2,0x7ffc58,12)0x400080083e = 12
4503 write(2,0x283a65,2),  = 2
4503 write(2,0x7ffc58,12)0x4000800855 = 12
4503 write(2,0x283a65,2),  = 2
4503 write(2,0x7ffc58,12)0x4000800868 = 12
4503 write(2,0x283a65,2),  = 2
4503 write(2,0x7ffc58,12)0x40008008a9 = 12
4503 write(2,0x283a65,2),  = 2
4503 write(2,0x7ffc58,12)0x40008008cc = 12
4503 write(2,0x283a65,2),  = 2
4503 write(2,0x7ffc58,12)0x40008008ed = 12
4503 write(2,0x283f41,5), ... = 5
4503 write(2,0x283a5b,2))
 = 2
4503 write(2,0x283a1a,1)	 = 1
4503 write(2,0x443bc3,38)/usr/local/go/src/runtime/asm_ppc64x.s = 38
4503 write(2,0x283a09,1): = 1
4503 write(2,0x7ffc32,2)87 = 2
4503 write(2,0x283a2b,2) + = 2
4503 write(2,0x7ffc60,4)0xb0 = 4
4503 write(2,0x283cbf,4) fp= = 4
4503 write(2,0x7ffc58,12)0x4000800450 = 12
4503 write(2,0x283cdf,4) sp= = 4
4503 write(2,0x7ffc58,12)0x40008003e0 = 12
4503 write(2,0x283cd7,4) pc= = 4
4503 write(2,0x7ffc5d,7)0x670f0 = 7
4503 write(2,0x283a19,1)
 = 1
4503 exit_group(2)
```

So what is the huge page size on ppc64le, and how should I tell qemu?

**Comment by mgiessing** [comment]
pagesize on **ppc64le** is **64k (65536)**

```bash
[root@p1361-kvm1 ~]# uname -m
ppc64le
[root@p1361-kvm1 ~]# getconf PAGESIZE
65536
```

While it should be **4k (4096)** on **x86**:

```bash
(py37) [root@x3850x5-5 ~]# uname -m
x86_64
(py37) [root@x3850x5-5 ~]# getconf PAGESIZE
4096
```

You can tell `qemu-ppc64le` via the `-p` flag (however I haven't tested it on x86 HW yet)

https://helpmanual.io/help/qemu-ppc64le/

```bash
-p pagesize   QEMU_PAGESIZE     set the host page size to 'pagesize'
```

However I haven't tried it on x86 yet

**Comment by mgiessing** [comment]
@jreiser I'm not sure how well this offering works, but it seems like people can get access to ppc64le systems here:

https://openpower.ic.unicamp.br/minicloud/

Furthermore there is a Jenkins hosted at Oregon State University if that helps for builds etc.:
https://powerci.osuosl.org/ 
Request acces here:
https://osuosl.org/services/powerdev/request_powerci/

**Comment by mgiessing** [comment]
I'm not very experienced with gdb and strace but I tried to replicate your setting on my native ppc64le HW:

1.) Run `gdb --args protoc_gen_go`
2.) Run strace in parallel terminal `strace -p $(pgrep -f protoc-gen-go)` 

I attached the the strace, because I am very unaware of how to interpret/analyse that.
[protoc_strace.log.zip](https://github.com/upx/upx/files/8340113/protoc_strace.log.zip)

**Comment by jreiser** [comment]
I have requested minicloud access, and await a response.

Meanwhile, I updated the x86_64 test system to Ubuntu 20.04 LTS, but `qemu-ppc64le version 4.2.1 (Debian 1:4.2-3ubuntu6.21)`  still did not work properly, even with `-p 65536` to set the PAGE_SIZE.
So I built qemu-7.0.0.rc1 from source (whose --version says `qemu-ppc64le version 6.2.91`, indicating (6 - 4) ==> 2 years of development since Ubuntu 20.04 LTS), and that seems to work.
The older versions tossed in an extra call to `munmap` that erased nearly the entire de-compressed image.

Now I'm chasing a problem with the initial environment: the register contents at first instruction after `execve` syscall.  Control has been transferred to the de-compressed image, and `crt0` has started, but SIGSEGV.  Documentation is failing me.

**Comment by jreiser** [comment]
@mgiessing  The above commit on `devel` branch runs for me under qemu-ppc64le (version 7.0.0-rc1) on x86_64.  Using the `-strace` argument to qemu-ppc64le shows the same output for `protoc-gen-go_ORIG` and on the result of compressing by UPX (after the initial de-compression).

**Comment by mgiessing** [comment]
Thanks a lot for all of your effort you put into this! I'll have access to all relevant ppc64le systems (bare-metal, KVM & PowerVM) on Thursday where I'll test it😌

**Comment by mgiessing** [comment]
@jreiser I can confirm that it works with the devel branch (`upx 4.0.0-git-a54bef20057d`) on ppc64le (tested on KVM & PowerVM so far) - thanks a lot!

One last question: Is there any kind of nightly build that provides the pre-compled `upx` executables? Building UCL & UPX from source works fine but binaries would be nice!
I have seen GH actions binaries for x86 and I guess only releases will be build using travis, which provides more architectures...?

Thanks!

**Comment by jreiser** [comment]
A chek-n to branch `devel` whose commit message tags a particular Issue, triggers a  GitHub Action which is a set of builds.  Click on `Actions` in the menu strip near the top of an Issue page (for instance, leading eventually to https://github.com/upx/upx/actions/runs/2041013164) or begin at https://github.com/upx/upx-automatic-builds. These builds are for Linux and Windows on *x86.
The code for the Actions is in `upx/.github`, perhaps in `workflows/ci.yml`. Pull requests are welcome (for other architectures and/or other OS that are supported by Travis or other free-as-in-beer build farms),  especially when documented so that I don't have to become an expert Travis administrator.

**Comment by mgiessing** [comment]
I'll try to create artefacts using the integrated GH actions and docker buildx with qemu - at least that is something I have done before and there is a higher chance it'll work compared to start from scratch with travis.
As the issue itself is fixed, I'll close this now :)
