### ISSUE TITLE
cudnn_cnn_infer64_8.dll and cudnn_ops_infer64_8.dll after compress can't work

### ISSUE THREAD

**Issue by zshfeng00** [upx/upx#572]
## What's the problem (or question)?

I use upx to compress cudnn's dll cudnn_cnn_infer64_8.dll and cudnn_ops_infer64_8.dll, compress success, but the exe load compressd dll fail 
## What should have happened?

cudnn_cnn_infer64_8.dll and cudnn_ops_infer64_8.dll after compress should work normally
## Do you have an idea for a solution?

no idea
## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* upx 3.96

* Host Operating System and version:
* win10
* Host CPU architecture:
* intel x64
* Target Operating System and version:
* win10
* Target CPU architecture:
* intel x64

**Comment by jreiser** [comment]
@zshfeng00 You must upload (see the line "Attach files by ..." at the bottom of every widget pane for entering a Comment on GitHub) or provide a URL to the files which fail.  Compess the upload using gzip, zip, or .tgz.

**Comment by zshfeng00** [comment]
@jreiser cudnn_cnn_infer64_8.dll and cudnn_ops_infer64_8.dll download url: https://developer.nvidia.com/rdp/cudnn-archive
you can download "Download cuDNN v8.2.1 (June 7th, 2021), for CUDA 11.x", the dll in cudnn-11.3-windows-x64-v8.2.1.32/cuda/bin path
thanks!
