### ISSUE TITLE
GraalVM generated simple console app doesn't start on Win10 64bit

### ISSUE THREAD

**Issue by wolftobias** [upx/upx#574]
## What's the problem (or question)?
I've generated a simple java console app with graalvm graalvm-ce-java17-windows-amd64-22.0.0.2, the app 
is starting after generating a exe.
After using upx it doesn't, there is no crash, but also no system outs on the cli.

## What should have happened?
I'm making some system.out.println to let the user know whats happening, after upx the exe is much smaller but there are no more sysouts. 

## Do you have an idea for a solution?
No sorry, no idea!

## How can we reproduce the issue?
I've attached the graalvm produced exe
[CMDisableServiceLogging.zip](https://github.com/upx/upx/files/8461723/CMDisableServiceLogging.zip)

## Please tell us details about your environment.

Windows 10 64bit, VM Workstation, latest updates

**Comment by jreiser** [comment]
Graalvm makes assumptions about introspection (using a specific strategy to examine the symbol table of the running process) that are not true when the executable has been compressed by upx.  See https://github.com/upx/upx/issues/405 .
