### ISSUE TITLE
App crashes on Windows 7 with UPX compressed dll

### ISSUE THREAD

**Issue by toxieainc** [upx/upx#575]
## What's the problem (or question)?

Application crashes on Windows 7 (Win10 works), also tested/verified by multiple users, if a specific dll (VPinMAME.dll) is UPX compressed (--best --lzma).

## What should have happened?

No crash.

## Do you have an idea for a solution?

No.

## How can we reproduce the issue?

1. Download https://github.com/vpinball/pinmame/releases/download/v3.5-36-f32fb6c/VPinMAME-sc-3.5-36-f32fb6c-win-x86.zip
2. Run setup.exe on Windows 7
3. Press 'Test' button (may also require pressing 'Install' before that, which will just hook up the dlls COM stuff in the registry)
4. Crash

## Please tell us details about your environment.

* UPX version used (`upx --version`): Due to other issues (crashes on various setups) with the officially released 3.96 we need to use trunk builds, currently this is artifact 176385880 (from https://github.com/upx/upx/actions/runs/1923164111)
* Host Operating System and version: Windows 7
* Host CPU architecture: Intel 32bit and 64bit
* Target Operating System and version: dto.
* Target CPU architecture: dto.

**Comment by Andy0619** [comment]
你好，你的来信已收到

**Comment by jreiser** [comment]
There is no interest in fixing problems for Windows 7, particularly when Windows 10 works.

**Comment by toxieainc** [comment]
But this app still ships on and supports Windows 7.

**Comment by jreiser** [comment]
What was the most recent version of UPX that worked for running the compressed app on Windows 7?

Microsoft support for Windows 7 ended on Jan.14, 2020, which is 2.5 years ago: https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962
