### ISSUE TITLE
CantPackException: bad Mach_command[10]{cmd=0x32, size=0x20}

### ISSUE THREAD

**Issue by ronaaron** [upx/upx#578]
Built the latest git version of UPX (git-a54bef) on an Apple M1 (MacBook Air), hoping to be able to compress an executable I created there.

I had hoped for a compression, but instead got the error listed in the subject line.

## How can we reproduce the issue?

1. build UPX on an Apple M1 machine
2. build another exe using XCode 13+
3. compress that exe
4. see the error

## Please tell us details about your environment.

* UPX version used (`upx --version`): git-a54bef
* Host Operating System and version: macOS 12.4
* Host CPU architecture: Apple M1
* Target Operating System and version: same as host
* Target CPU architecture: same as host

**Comment by jreiser** [comment]
Believed to be fixed in commit above.

**Comment by ronaaron** [comment]
Thank you. The build compiles, and it does compress, so that's great!

However, the compressed exe no longer works. I get "Killed: 9" when trying to run it (even when using '-o' to create a completely different executable).

**Comment by jreiser** [comment]
Especially for arm64 (aarch64,  as opposed to amd64 (x86_64)), you have encountered the problems of Apple's implementation of run-time security.    See https://github.com/upx/upx/issues/434#issuecomment-1064824409 .  In addition, Apple's documentation is missing or exceedingly poor.  So far, it appears that the developer (that's you) must do several things after UPX compression has completed; UPX itself cannot do them.

**Comment by ronaaron** [comment]
Hmm. I am indeed planning on 'signing' my executable, because of the Apple nonsense.

That said, the un-compressed executable runs perfectly well, while the UPX compressed one does not. Are you sure that's not a UPX issue?

**Comment by jreiser** [comment]
See 12d2bc937e0995d61d67957d000a96212e3a1728.  I have not found any documentation on exactly which Mach command structures an executable must contain.  Also, the requirements seem to change from release to release (Mavericks to Catalina to BigSur to Monterey, for instance.)  So, I have been experimenting, trying to construct the smallest possible Mach-o executable in terms of the number of Mach-o commands.  If you know more, then please tell or give a URL.

**Comment by ronaaron** [comment]
Thank you; I appreciate your hard work, which is made that much harder by Apple.
I, too, keep hitting my head when Apple moves the ceiling. 

Unfortunately, I don't really know more about any of the innards than you do. It would be nice if there were up to date and accurate internals information. But their documentation tends to lag severely, and very little internals info is reliable.

**Comment by ronaaron** [comment]
I just did the signing dance. The regular executable signed no problem; the UPX compressed one seemed to be signed, but still crashed with the 'Killed: 9' message.

**Comment by jreiser** [comment]
Well, that means that the upx code does not know how to build the Mach-o structs that are smaller but still valid.  Please run "otool -hl" on both the signed original version and on the signed compressed version.  If the output is small then please post here in a quoted comment block (constant-width characters), else "Attach files by ...".  I  will look at them, and see what I can find.

**Comment by ronaaron** [comment]
I just did the `otool -hl` on both, and compared the output; no difference unfortunately.

**Comment by jreiser** [comment]
Commit https://github.com/upx/upx/commit/af45f0a92b625fdcbbd986e38ea656719ccd00ed fixed the immediate complaint.  GitHub bots are getting picky, so Closing.  Track the general issue of "UPX vs MacOS" in https://github.com/upx/upx/issues/434#issuecomment-1064824409
