### ISSUE TITLE
MacOS sample does not unpack (analysis help)

### ISSUE THREAD

**Issue by albertzsigovits** [upx/upx#579]
## What's the problem (or question)?
I have a malicious MacOS sample that does not unpack. Would like to unpack it:
SHA256: b817fb1d6f784fe78def191e2499eb9b4b3429e002c9921f6c7a3b9a4c7ad72e
https://www.virustotal.com/gui/file/b817fb1d6f784fe78def191e2499eb9b4b3429e002c9921f6c7a3b9a4c7ad72e
(Let me know if you can't download it)

With UPX 3.95: `upx: file.cpp:276: virtual int InputFile::readx(MemBuffer*, int): Assertion (unsigned)len <= buf->getSize() failed.`
With UPX 3.96: `CantUnpackException: file corrupted`
With UPX latest commit git-a54bef+: `CantUnpackException: file corrupted`
`--fileinfo` or `-t` does not work on the sample either.

## What should have happened?
The sample should unpack automatically via the `upx -d` command.

## Do you have an idea for a solution?
Banging my head around this sample for a few days now.
Created test cases from MacOS to compare how the file header should look like.
(Used `x86_64` `ifconfig` from MacOS 12.4 Monterey)
It seems to me that the malicious sample in question has been manually altered to evade malware analysts.

Malicious sample:
│000003b0│ 55 89 71 6a 55 50 58 21 ┊ 10 0a 0d 22 00 00 00 00 │U×qjUPX!┊•__"0000│
│000003c0│ b8 39 1c 00 b8 39 1c 00 ┊ d8 06 00 00 0d 02 00 00 │×9•0×9•0┊×•00_•00│
│000003d0│ 08 00 00 00 fb 79 cd ff ┊ cf fa ed fe 07 00 00 01 │•000×y××┊××××•00•│
│000003e0│ 03 00 02 06 0a b8 06 00 ┊ 01 ed ff e7 1d 19 06 48 │•0••_×•0┊•×××•••H│
│000003f0│ 5f 5f 50 41 47 45 5a 45 ┊ 52 4f 00 01 65 b7 4a 0e │__PAGEZE┊RO0•e×J•│

p_filesize and p_blocksize checks out. Then a `0d 02 00 00`, which may be l_version and l_format?
Question 1: What UPX version was used to pack if I get `0d 02 00 00`?
Then the next section is interesting:
`03 00 02 06 0a b8 06 00 01 ed ff e7 1d 19 06 48`
Before `H__PAGEZERO` aka `19 06 48 5f 5f 50 41 47 ....`, there should be 16 bytes.
It seems here we are missing 3 bytes here. 
Question 2: What 3 bytes are missing here? Could you deduce it somehow?

x86_64 ifconfig file from MacOS 12.4:
│000003b0│ d3 83 f0 8f 55 50 58 21 ┊ eb 09 0d 22 00 00 00 00 │××××UPX!┊×__"0000│
│000003c0│ 80 df 01 00 80 df 01 00 ┊ 18 07 00 00 82 02 00 00 │××•0××•0┊••00×•00│
│000003d0│ 02 00 00 00 d9 74 cb ff ┊ cf fa ed fe 07 00 00 01 │•000×t××┊××××•00•│
│000003e0│ 03 00 02 03 11 f8 06 ff ┊ 4d f7 7d 85 00 20 00 00 │•0•••×•×┊M×}×0 00│
│000003f0│ 19 03 48 5f 5f 50 41 47 ┊ 45 5a 45 52 b7 4a 4e d9 │••H__PAG┊EZER×JN×│

This has been packed with UPX `3.96`. I get `82 02 00 00`. (l_version and l_format?)
Here we see we have 16 bytes `03 00 02 03 11 f8 06 ff ┊ 4d f7 7d 85 00 20 00 00` before `H__PAGEZER` aka `19 03 48 5f 5f .....`
What 3 bytes am I missing from the malicious sample?

## How can we reproduce the issue?
`upx -d sample -o test`

## Please tell us details about your environment.
* UPX version used (`upx --version`): `UPX 3.96`
* Host Operating System and version: `MacOS 12.4 Monterey`
* Host CPU architecture: `Intel x86_64`
* Target Operating System and version: `Any`
* Target CPU architecture: `Intel x86_64`

**Comment by jreiser** [comment]
I cannot find any link to download the actual bad file.  The link https://www.virustotal.com/gui/file/b817fb1d6f784fe78def191e2499eb9b4b3429e002c9921f6c7a3b9a4c7ad72e yields an analysis page (various hash values, etc.), but that analysis page does not link to the actual bad file.

**Comment by albertzsigovits** [comment]
[OptimizeStorage.zip](https://github.com/upx/upx/files/8805800/OptimizeStorage.zip)

Here you go, password in `infected`.

**Comment by jreiser** [comment]
Analyzing the Mach-o headers probably won't give specific clues.  MacOS will refuse to run anything that doesn't look OK.  However the Mach-o headers do show that the compression output style is that of upx-3.95.  The layout of the compressed file has evolved as MacOS requirements changed, often yearly.

I added some code to try harder on this corrupted file:
```
$ upx -d -i -f -o foo OptimizeStorage
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-907c17+ Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
[WARNING] file corrupted

[WARNING] attempting recovery, overlay_offset = 0x3bc

   1849976 <-    720912   38.97%   macho/amd64   foo
```
It is easy for malware to defeat this addition, but there remain other ways to counter newer malware.  It just takes time...

**Comment by albertzsigovits** [comment]
Much appreciated, works as expected now!
Going to have to study the newly added code to fully understand the picture.
Cheers!
