### ISSUE TITLE
UPX 3.96 does not pack correctly Mach-O FAT file containing x86_64 and arm64 architectures.

### ISSUE THREAD

**Issue by urianpaul94** [upx/upx#580]
## What's the problem (or question)?

Hello,
I tried to pack a Mach-O FAT file compiled for x86_64 and arm64. After pack the file using UPX 3.96, it eliminates the x86_64 arhitecture. I saw that this problem seems to be just for the FAT files containing that two arhitectures.
Also, I saw that for FAT files containing other architectures (ex: x86_64, ppc_7400, i386) it works fine. I tried it on the following file: 
https://www.virustotal.com/gui/file/50478e88c6ecbd9b932aeb3f60396232f65653afd1b7b52cd5762dd0a2596a5d

## What should have happened?

The packed file should contain both arhitectures from the FAT file.

## Do you have an idea for a solution?

No.

## How can we reproduce the issue?
1. I used the following file from VirusTotal: https://www.virustotal.com/gui/file/1bbca867ff7574774c39d2d38040921389b3543d6974b6323f86995dbed2c274
2. I packed it with the following command: upx file_name -o packed_file_name
3. When I run file on the packed_file_name, I get: file_packed_2: Mach-O 64-bit executable arm64

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.96
* Host Operating System and version: macOS Monterey version 12.4
* Host CPU architecture: 2,4 GHz 8-Core Intel Core i9
* Target Operating System and version: macOS Monterey version 12.4
* Target CPU architecture: Tried to pack FAT file: x86_64, arm64.

**Comment by jreiser** [comment]
Same as https://github.com/upx/upx/issues/462.  Fixed in the 'devel` branch

Also, neither linked page at VirusTotal provides any way to download the actual bits, so I could not test your specific case(s).
