### ISSUE TITLE
terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by c02y** [upx/upx#585]
## What's the problem (or question)?

When running upx, it fails with message `terminated by signal SIGSEGV (Address boundary error)`

## What should have happened?

It should work.

## How can we reproduce the issue?

1. git clone the repo (the latest commit id is 23bc186f275c)
2. make
3. ./src/upx.out ./src/upx.out
4. rm -rfv ~/.local/bin/upx && cp ./src/upx.out ~/.local/bin/upx
5. `~/.local/bin/upx --version` fails with message `terminated by signal SIGSEGV (Address boundary error)`
6. `./src/upx.out --version` works fine.

**NOTE: **
1. the compressed `./src/upx.out` is always working fine
2. if I do not compress `./src/upx.out`, and copy/move the `./src/upx.out` into `~/.local/bin/upx`, it is always working fine
3. once I copy/move the compressed `./src/upx.out` into `~/.local/bin/upx`, the `~/.local/bin/upx` will not work right after I copy/move it or eventually.
4. `rm -rfv ~/.local/bin/upx && ./src/upx.out -o ~/.local/bin/upx ./src/upx.out && ~/.local/bin/upx` makes no difference
5. `terminated by signal SIGSEGV (Address boundary error)` is the message from fish shell, if you run the whole process in bash, the error message will be `Segmentation fault (core dumped)`
6. I've tried the whole process in fish shell and bash shell, and in alacritty and kitty, the process can be reproduced.
7. `rm -rfv ~/.local/bin/upx && /usr/bin/upx -o ~/.local/bin/upx ./src/upx.out && ~/.local/bin/upx` is working fine, `/usr/bin/upx` in the command is `3.96-git-d7ba31cab8ce+` installed from Arch Linux repo

I'm not sure if you can reproduce this, since it is very weird, but I can reproduce it in my environment.

## Please tell us details about your environment.

* UPX version used (`upx --version`): `4.0.0-git-23bc186f275c`
* Host Operating System and version: `Arch Linux 5.18.7-zen1-1-zen`
* Host CPU architecture: `Intel Core i7-10875H (16) @ 5.1GHz`
* Target Operating System and version: The same as the host
* Target CPU architecture: The same as the host

Screenshot:
![image](https://user-images.githubusercontent.com/2135996/176554294-525dd233-80f9-4448-b0d4-73fab68e767a.png)

**Comment by jreiser** [comment]
For text, please use copy+paste instead of a screen shot.  Put a line that contains only 3 backticks (character: hex 0x60, octal 0140, decimal 96; located on the same key as tilde on many keyboards) both before and after the pasted text.  This will cause github's  Markdown processing to display the pasted text in a constant-width font, without filling lines, and with a shaded background.  Such text can be searched, indexed, and translated very easily in contrast to a screen shot.

You're right, it is very weird.  In 3 runs I see two successes followed by one failure.  Please run the failure under the gdb debugger, and when the SIGSEGV happens then gather some diagnostic info:
```
$ gdb ~/.local/bin/upx
(gdb) run --version
SIGSEGV
(gdb) x/i $pc   ## the faulting instruction
(gdb) x/12i $pc-0x20   ## probable instruction context (heuristic)
(gdb) info reg   ## contents of all registers
(gdb) x/16xw $sp   ## dump active portion of stack
(gdb) bt   ## subroutine backtrace
```
And of course, see if the problem happens in a DEBUG version; change the Makefile to
```
BUILD_TYPE_DEBUG    ?= 1
```

**Comment by c02y** [comment]
> For text, please use copy+paste instead of a screen shot. Put a line that contains only 3 backticks (character: hex 0x60, octal 0140, decimal 96; located on the same key as tilde on many keyboards) both before and after the pasted text. This will cause github's Markdown processing to display the pasted text in a constant-width font, without filling lines, and with a shaded background. Such text can be searched, indexed, and translated very easily in contrast to a screen shot.

The screenshot is inessential, it is just a simplified version of the whole process I already described in text, just in case people can not fully understand the text or wouldn't believe it since it is very weird.

> You're right, it is very weird. In 3 runs I see two successes followed by one failure. Please run the failure under the gdb debugger, and when the SIGSEGV happens then gather some diagnostic info:
> 
> ```
> $ gdb ~/.local/bin/upx
> (gdb) run --version
> SIGSEGV
> (gdb) x/i $pc   ## the faulting instruction
> (gdb) x/12i $pc-0x20   ## probable instruction context (heuristic)
> (gdb) info reg   ## contents of all registers
> (gdb) x/16xw $sp   ## dump active portion of stack
> (gdb) bt   ## subroutine backtrace
> ```

I've tried it, running it in gdb is always working fine.
```
>> ~/.local/bin/upx --version
fish: Job 1, '~/.local/bin/upx --version' terminated by signal SIGSEGV (Address boundary error)
[SIGSEGV]>> gdb ~/.local/bin/upx
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/chz/.local/bin/upx...
(No debugging symbols found in /home/chz/.local/bin/upx)
(gdb) run --version
Starting program: /home/chz/Dotfiles.d/bin/.local/bin/upx --version
upx 4.0.0-git-23bc186f275c
UCL data compression library 1.03
zlib data compression library 1.2.12
LZMA SDK version 4.43
Copyright (C) 1996-2021 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2021 Laszlo Molnar
Copyright (C) 2000-2021 John F. Reiser
Copyright (C) 2002-2021 Jens Medoch
Copyright (C) 1995-2017 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
[Inferior 1 (process 87352) exited normally]
(gdb)
......
...... execute `run --version` several times, works normally every time
(gdb) x/i $pc
No registers.
(gdb) x/12i $pc-0x20
No registers.
(gdb) info reg
The program has no registers now.
(gdb) x/16xw $sp
No registers.
(gdb) bt
No stack.
(gdb)
```

> 
> And of course, see if the problem happens in a DEBUG version; change the Makefile to
> 
> ```
> BUILD_TYPE_DEBUG    ?= 1
> ```

It doesn't help, debug version is also not working normally once it is in `~/.local/bin/`.

**Comment by jreiser** [comment]
Cannot reproduce:  (I always re-build in the `stub` directory to ensure no staleness.)
```
$ cd src; git checkout 23bc186
$ cd stub; make clean; make all
$ cd ..; make clean; make
$ ./upx.out ./upx.out
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-23bc18+ Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  11284624 ->   2030912   18.00%   linux/amd64   upx.out                       

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
$ cp upx.out ~/.local/bin/upx
$ !$ --version
~/.local/bin/upx --version
upx 4.0.0-git-23bc186f275c+
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
Copyright (C) 1996-2021 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2021 Laszlo Molnar
Copyright (C) 2000-2021 John F. Reiser
Copyright (C) 2002-2021 Jens Medoch
Copyright (C) 1995-2017 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.

```
