### ISSUE TITLE
CantPackException: bad DT_{0x694c6b63} = 0x8db640 (beyond EOF)

### ISSUE THREAD

**Issue by messense** [upx/upx#586]
## What's the problem (or question)?
upx compress a Rust musl binary errors with `CantPackException: bad DT_{0x694c6b63} = 0x8db640 (beyond EOF)`

## What should have happened?
compress successful

## Do you have an idea for a solution?

No

## How can we reproduce the issue?

1. compile upx from git (23bc186f275c3c3ec8bbcecb78bae11de0cb8ce2)
2. run `upx aliyundrive-webdav`

`aliyundrive-webdav` is in attachment: [x86_64-unknown-linux-musl-bin.zip](https://github.com/upx/upx/files/9033969/x86_64-unknown-linux-musl-bin.zip)

## Please tell us details about your environment.

* UPX version used (`upx --version`): UPX git-23bc18 
* Host Operating System and version: Ubuntu 20.04
* Host CPU architecture: x86_64
* Target Operating System and version: Ubuntu 20.04
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
Fixed by above commit on `devel` branch.

**Comment by messense** [comment]
It works, Thanks!
