### ISSUE TITLE
How to separate filters from methods?

### ISSUE THREAD

**Issue by tansy** [upx/upx#587]
## What's the problem (or question)?

There is an option `--brute` that tries all available compression methods & filters. From my experience it always uses lzma but lof of the times it's not what I actually want as lzma is tight compressor but a slow one. I'd rather had slightly worse compression but much faster start.

I tried to find an option to choose filter/s separately or any that would distinguish between them but it seems to be none.

## Do you have an idea for a solution?

Is there a chance to add an option to choose filters or make a separate one for filters and for methods?

## Do you have an idea for a solution?
Separate option for filter/s, like `--filter=<filter|try-all>`, similarly for methods.

**Comment by jreiser** [comment]
Which hardware and operating system are most important to you?  Older hardware and OS are unlikely to see changes because they cannot be debugged.
Meanwhile, here are the available tuning options for modern OS:  If you do not like lzma then do not use `--brute` or `--ultra-brute`.  Compression effort is `-1` through `-9`, then `--best`, `--brute`, `--ultra-brute`.  Check the source code `src/main.cpp` for subroutine `get_options()` which enables specifying method (`--nrv2e`, etc.) and `--filter=`, as well as low-level options such as `--crp-lzma-pb`.

**Comment by tansy** [comment]
> Which hardware and operating system are most important to you? 

IA 32/64, linux and windows, these I am using most of the time.

> Meanwhile

I have checked manual and there are two options there that are not in help (`--all-methods`, `--all-filters`) but they are said to be for TMT Pascal compiler only. In the same time, this option is turned on, internally, by `--brute` in `do_option()`.

>  Check the source code src/main.cpp for subroutine get_options()

I did, thank you, and found also some comments in `do_option()`, namely `--filter=` and `--small`, but they are not described. What is actual parameter for filter option, number, string?

Maybe these options could be described in manual and mentioned in help.

**Comment by markus-oberhumer** [comment]
There are a number of compression fine-tuning options, but these are undocumented as they change from release to release. Try the `--no-lzma` option or have a look at the source code.

**Comment by tansy** [comment]
Thanks for the answer.
For anyone interested in using it \`--no-lzma' should be after \`--brute' as these arguments are passed in order of appearance.

**Comment by markus-oberhumer** [comment]
> For anyone interested in using it `--no-lzma' should be after `--brute' as these arguments are passed in order of appearance.

While undocumented this is unexpected. I'll have a look.

**Comment by tansy** [comment]
[This script](https://dpaste.com/H5EX3HA5R) may help

```
$ wc -c prog*
135182 prog
 64014 prog--brute
 66062 prog--brute--no-lzma
 64526 prog--lzma
 64014 prog--no-lzma--brute
 66574 prog-9
```
