### ISSUE TITLE
UPXed go binaries don't work on OS X 10.11.6

### ISSUE THREAD

**Issue by CAFxX** [upx/upx#59]
## What's the problem (or question)?
Go binaries don't work (exit with error) after compression with upx

## What should have happened?
Go binaries should work after compression with upx

## Do you have an idea for a solution?
Nope :)

## How can we reproduce the issue?
1. install go (`go version` reports `go version go1.7.5 darwin/amd64`)
2. `go build hello.go -o hello` where `hello.go` is the following file:
```
package main

import "fmt"

func main() {
	fmt.Println("Hello World!")
}
``` 
3. run `./hello`, notice that it prints `Hello World!` and exits with status=0
4. `upx -o hello.upx hello`
5. run `./hello.upx` notice that it prints nothing and exits with status=127

## Please tell us details about your environment.

* UPX version used (`upx --version`):
```
upx 3.93
UCL data compression library 1.03
zlib data compression library 1.2.5
LZMA SDK version 4.43
Copyright (C) 1996-2017 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2017 Laszlo Molnar
Copyright (C) 2000-2017 John F. Reiser
Copyright (C) 2002-2017 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```
* Operating System and version:
```
System Version:	OS X 10.11.6 (15G1217)
  Kernel Version:	Darwin 15.6.0
```
* CPU architecture:
amd64 (Intel Core i7)

**Comment by CAFxX** [comment]
Zip file containing hello.go, hello and hello.upx (as discussed above)
[hello.zip](https://github.com/upx/upx/files/743357/hello.zip)

**Comment by iikira** [comment]
I have this problem too.
By the way, macho/i386 is quite normal and macho/amd64 is broken.

**Comment by jreiser** [comment]
@CAFxX  Thank you for attaching hello.zip.  A small, concrete test case really helps.  The problem seems to arise because MacOS does not let subsequent code override attributes of PAGEZERO in some ways.  Investigating further...

**Comment by shatil** [comment]
Thanks for filing @CAFxX. I have encountered the same issue on macOS Sierra 10.12.2 (16C67) using Brew-installed UPX 3.93. Here are my artifacts as well: [hello.tar.gz](https://github.com/upx/upx/files/751372/hello.tar.gz)

I am new to UPX, so I don't know if I'm doing this right, but my process:
```go
package main

import "fmt"

func main() {
	fmt.Println("hello")
}
```

Without UPX:
```
11:17:25 $ go build hello.go
11:17:31 $ ./hello
hello
11:17:35 $ echo $?
0
```

With UPX:
```
11:17:52 $ upx hello
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.93        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 29th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1611712 ->    557720   34.60%   macho/amd64   hello

Packed 1 file.
11:17:57 $ ./hello
11:18:02 $ echo $?
127
```

In case it helps, `upx -V`:
```
11:18:41 $ upx -V
upx 3.93
UCL data compression library 1.03
zlib data compression library 1.2.8
LZMA SDK version 4.43
```

**Comment by jreiser** [comment]
@CAFxX please try the tip of 'devel' branch (or the 93cefde commit.)

**Comment by CAFxX** [comment]
@jreiser seems to work correctly

**Comment by jreiser** [comment]
Closing.
