### ISSUE TITLE
Unable to compress scripts and have them work.

### ISSUE THREAD

**Issue by TBOpen** [upx/upx#590]
## What's the problem (or question)?
When I compress scripts they won't run, nothing seems to happen.

## What should have happened?
It should have run - a bunch of scripts compressed with a much older version of UPX ran okay.  Otherwise I didn't know you could compress scripts.

## Do you have an idea for a solution?

fix whatever broke?

## How can we reproduce the issue?
compress a script and try to use it .. ldd for example.

## Please tell us details about your environment.
* UPX version used (`upx --version`): 
upx 4.0.0-git-d61edc9c7f04
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43

* Host Operating System and version: devuan chimaera
* Host CPU architecture: 386
* Target Operating System and version: same
* Target CPU architecture: same

**Comment by jreiser** [comment]
Please upload an actual script file which fails.  See "Attach files by ..." in the footer of each Comment entry pane.  Or, give the URL of the actual file.  To save space and satisfy the upload filters on GitHub, then compress the file using gzip, zip, or .tgz.

**Comment by TBOpen** [comment]
I haven't found any it works with - here's ldd
[ldd.zip](https://github.com/upx/upx/files/9330901/ldd.zip)

**Comment by alexmyczko** [comment]
`bashx` to the rescue:

```
-rw-r--r-- 1 root root  5401 Mar 17 14:37 ldd
-rwxr-xr-x 1 root root  2486 Aug 15 23:47 lddxz
```

see https://github.com/alexmyczko/autoexec.bat/blob/master/bashx

**Comment by jreiser** [comment]
Note that <tt>bashx</tt> requires <tt>bash, sed, unxz</tt> at run time.

**Comment by alexmyczko** [comment]
patches (PRs) welcome

**Comment by jreiser** [comment]
I am still waiting for an actual file (script) which fails according to this Issue.  Perhaps the problem is subsumed by https://github.com/upx/upx/issues/604 ?

**Comment by TBOpen** [comment]
The ldd.zip can be compressed using the parameters indicated and it had a problem.

**Comment by jreiser** [comment]
Could there be a problem with `bash`?  I cannot get `bash -c "cmd" arg1 arg2` to pass `arg1` and `arg2` to `cmd`.

First, a helper program that just prints `argv[]`:
```
$ cat my_args.c
#include <stdio.h>

int main(int argc, char *argv[])
{
    int j;
    for (j=0; j<argc; ++j) {
        printf("%d: %s\n", j, argv[j]);
    }
    printf("***EOF***\n");
    return 0;
}
```

Now a test run, with the `execve` syscalls monitored by `strace`:
```
$ strace -e trace=clone,execve bash -c "./my_args $1 $2" 123 456
execve("/usr/bin/bash", ["bash", "-c", "./my_args  ", "123", "456"], 0x7ffd182038a0 /* 62 vars */) = 0
execve("./my_args", ["./my_args"], 0x5589b6589900 /* 60 vars */) = 0
0: ./my_args
***EOF***
+++ exited with 0 +++
```
So `bash -c "./my_args" 123 456` did not pass `123` and `456` to `./my_args`.  Thus `ldd.upx /bin/date` does not see the `/bin/date`, so the desired output does not appear.
