### ISSUE TITLE
Wishlist: default to 8086 code and add --286 flag

### ISSUE THREAD

**Issue by hackerb9** [upx/upx#591]
Have you considered making 8086 the default operating mode, unless 286 instructions are detected? That way 8086 executables would not get munged and people who wanted to save a few extra bytes could use a new flag (--286?). 

This seems like a good compromise. Executables will run everywhere by default and optimization is an option. (Currently, the reverse is true.)

_Originally posted by @hackerb9 in https://github.com/upx/upx/issues/530#issuecomment-929796731_

**Comment by markus-oberhumer** [comment]
Sorry, but we won't change any default flags.
