### ISSUE TITLE
File throws EXCEPTION_ACCESS_VIOLATION after unpacking (analysis help)

### ISSUE THREAD

**Issue by albertzsigovits** [upx/upx#594]
## What's the problem (or question)?
I have a malicious(!) file at hand, which flawlessly unpacks with `upx -d`, only issue is if I try to run it, it throws exception violation (C0000005, EXCEPTION_ACCESS_VIOLATION) error code right on the first instruction.
It seems to me that the packer, it was used to pack with, has been altered/modified or some key data or code is not unpacked properly or missing after the default `upx -d` is executed.
Could you help me find what's missing from the unpacked file?

Packed file: `36be260fb05e2f5aced8cd56b9e9038992762be4910352e28d46c9a99ff58635` (sha256)
```
upx --fileinfo
packed_malicious [amd64-win64.pe, win64/pe]
679936 bytes, compressed by UPX 13, method 14, level 10, filter 0x49/0x25
```

Unpacked file: `f6266c4ca360939b260163bd95df11f35f6d7151cdefbf4deb086507c7a874f0` (sha256)
```
2135552 <-    679936   31.84%    win64/pe     test.exe
Unpacked 1 file.
```
When running this unpacked PE file, it throws (C0000005, EXCEPTION_ACCESS_VIOLATION), right on the first instruction.

## What should have happened?
The executable PE file should run flawlessly without the EXCEPTION error code.

## Do you have an idea for a solution?
I think the packer, that was used to pack the file with, has been altered and some key data or section or code is not transferred or unpacked properly when unpacking with `upx -d`.
I tried to manually unpack it with a debugger, but there's no pushad/popad instruction in the assembly, which is weird.

## How can we reproduce the issue?
1. Download original packed file. [7866016262.zip](https://github.com/upx/upx/files/9433876/7866016262.zip) (MALICIOUS!)(Password is `infected`)
2. Unpack it with `upx -d`.
3. Open x64dbg debugger and Open the unpacked file.
4. See EXCEPTION error code right on the first instruction.

## Please tell us details about your environment.
* UPX version used (`upx --version`): 
```
upx 3.96
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
```

* Host Operating System and version: `Windows 10 Pro 10.0.19044`
* Host CPU architecture: `x64`
* Target Operating System and version: `Windows 10 Pro 10.0.19044`
* Target CPU architecture: `x64`

**Comment by bitraid** [comment]
This is actually a bug in UPX, which removes the relocation section when unpacking with `-d` (and this is an ASLR enabled PE file, which requires a relocation section). Try with `--strip-relocs=0`, or use a more recent build of UPX.

**Comment by albertzsigovits** [comment]
Thanks, didn't spot the missing .reloc, `--strip-relocs=0` worked perfectly.
