### ISSUE TITLE
Mistaken supported platform, `powerpc64le-darwin.macho`

### ISSUE THREAD

**Issue by rjzak** [upx/upx#596]
## What's the problem (or question)?
The UPX application, run as `upx --help` shows a list of supported platforms. I think that showing support for `powerpc64le-darwin.macho  macho/ppc64le` is a typographical error.

## What should have happened?
It should read as `powerpc64-darwin.macho macho/ppc64` since all Apple PowerPC machines are Big Endian. Little Endian was never supported. Reference: [libmacho/arch.c](https://opensource.apple.com/source/cctools/cctools-898/libmacho/arch.c.auto.html).

## Do you have an idea for a solution?
Change the output when running `upx --help`.

## How can we reproduce the issue?

1. Run `upx --help`
2. Notice the third line from the bottom.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.95
* Host Operating System and version: Ubuntu 20.04
* Host CPU architecture: x86_64
* Target Operating System and version: N/A
* Target CPU architecture: N/A

**Comment by markus-oberhumer** [comment]
Yes, I've been wondering about this as well.

There are some fragments in `src/stub/Makefile` about powerpc64-darwin.macho, though.

**Comment by markus-oberhumer** [comment]
Thanks for handling this. Maybe it's time to start our Mac G5  (dormant for more than 10 years) to actually do some pre 4.0.0 testing.

**Comment by markus-oberhumer** [comment]
Which reminds me, I think we also have a Mac G4 somewhere in the closet. Maybe should try that as well.

**Comment by jreiser** [comment]
My iMac G5 is PPC970FX+altivec running Mac OSX 10.5.8; built in 2009.

It sure looks like Apple is actively trying to make it very hard for a UPX-compressed executable to run.  MacOS BigSur and Monterey do not work "at all".  I cannot find documentation on what is required; trial-and-error is very slow.

**Comment by Nguyenhieu1a** [comment]
Comment

**Comment by markus-oberhumer** [comment]
Hmm, the stub name is still called `stub/powerpc64le-darwin.macho-entry.h` - this needs to be tested.

**Comment by jreiser** [comment]
libbfd does not handle (big endian) powerpc64-darwin.macho:
```
$ cd src/stub; make clean; make
multiarch-objcopy-2.27:tmp/powerpc64-darwin.macho-entry.bin: Invalid bfd target
```

**Comment by markus-oberhumer** [comment]
That's because of the misspelled  `elf64-powerpcbe` instead of  `elf64-powerpc`.

This diff works for me and builds the stubs:


```
diff --git a/src/stub/Makefile b/src/stub/Makefile
index e369107b..73b1ef36 100644
--- a/src/stub/Makefile
+++ b/src/stub/Makefile
@@ -137,9 +137,9 @@ STUBS += powerpc64le-linux.elf-entry.h
 STUBS += powerpc64le-linux.elf-fold.h
 STUBS += powerpc64le-linux.kernel.vmlinux-head.h
 STUBS += powerpc64le-linux.kernel.vmlinux.h
-#STUBS += powerpc64-darwin.dylib-entry.h
-#STUBS += powerpc64-darwin.macho-entry.h
-#STUBS += powerpc64-darwin.macho-fold.h
+STUBS += powerpc64-darwin.dylib-entry.h
+STUBS += powerpc64-darwin.macho-entry.h
+STUBS += powerpc64-darwin.macho-fold.h
 STUBS += powerpc64-linux.elf-entry.h
 STUBS += powerpc64-linux.elf-fold.h
 #STUBS += powerpc64-linux.kernel.vmlinux-head.h
@@ -1460,7 +1460,7 @@ tmp/powerpc64le-darwin.macho-main.o : $(srcdir)/src/$$T.c


 powerpc64-darwin.macho%.h : tc_list = powerpc64-darwin.macho powerpc64-linux.elf default
-powerpc64-darwin.macho%.h : tc_bfdname = elf64-powerpcbe
+powerpc64-darwin.macho%.h : tc_bfdname = elf64-powerpc

 tc.powerpc64-darwin.macho.ld = multiarch-ld-2.27 -b $(tc_bfdname)

```

**Comment by jreiser** [comment]
As of 2a02bce544c9c57170c1f6385122171c22330166, `upx --help` no longer reports `powerpc64le-darwin.macho`, and `powerpc64le-darwin` has been scrubbed from `src`.
