### ISSUE TITLE
stubtools: libmpfr.so.4 not found for aarch64-linux-gnu/4.9.2/cc1

### ISSUE THREAD

**Issue by jreiser** [upx/upx#603]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
When re-building the (de-)compression stubs using stubtools-20210104 on a current Linux system (Fedora 36), then building fails because libmpfr.so.4 cannot be found.  Example:
```
arm64-linux-gcc-4.9.2 -nostdinc -MMD -MT arm64-linux.elf-entry.h -fno-exceptions -fno-asynchronous-unwind-tables \
   -Wall -W -Wcast-align -Wcast-qual -Wstrict-prototypes -Wwrite-strings -Werror -c src/arm64-linux.elf-entry.S \
   -o tmp/arm64-linux.elf-entry.bin
<PATH>/bin-upx-20210104/packages/gcc-aarch64-linux-gnu-4.9.2-3.fc22.x86_64/bin/../libexec/gcc/\
   aarch64-linux-gnu/4.9.2/cc1: error while loading shared libraries: libmpfr.so.4: \
   cannot open shared object file: No such file or directory
make: *** [Makefile:654: arm64-linux.elf-entry.h] Error 1
```

## What should have happened?
Use libmpfr.so.6 which is available.

## Do you have an idea for a solution?
Workaround: `sudo ln -s libmpfr.so.6 /usr/lib64/libmpfr.so.4` (Path may vary according to Linux distribution.)

## How can we reproduce the issue?

1. cd src/stub
2. make clean
3. make
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): `$( git checkout devel )`  currently is: `2a02bce544c9c57170c1f6385122171c22330166`.
* Host Operating System and version: Fedora release 36 (Thirty Six)
* Host CPU architecture: x86_64
* Target Operating System and version: Fedora release 36 (Thirty Six)
* Target CPU architecture: x86_64

**Comment by markus-oberhumer** [comment]
Please manually install the missing libs from previous Fedora/RHEL versions, see https://github.com/upx/upx/blob/devel4/.github/workflows/ci.yml how we do this for Ubuntu 22.04.

Alternatively you can use a Podman based approach, see https://github.com/upx/upx/tree/devel4/misc/rebuild-stubs-with-podman

**Comment by markus-oberhumer** [comment]
I think that Podman/Docker is the way to go, as Linux distributions may change in incompatible ways over time, and as far as I understand Linux Docker images also work under Windows and macOS.

@jreiser Please reopen if you cannot use the Podman approach.
