### ISSUE TITLE
cannot unpack macho/amd64: bad packed Mach load_command @0x688

### ISSUE THREAD

**Issue by markus-oberhumer** [upx/upx#606]
This was detected by new "basic tests" in https://github.com/upx/upx/actions/runs/3197072914/jobs/5219835240

## What's the problem (or question)?

upx: upx.packed: CantUnpackException: bad packed Mach load_command @0x688

## What should have happened?

No error.

## How can we reproduce the issue?

1. download the macos-11 or macos-12 Artifact from https://github.com/upx/upx/actions/runs/3197072914
2. compress and decompress a macho/amd64 binary from that Artifact

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 4.0.0-git-c4437cb2934c

**Comment by markus-oberhumer** [comment]
@jreiser Thanks for your fix, but there is probably another (unrelated?) error which affects the
macos12 build/release-clang build:

  https://github.com/upx/upx/actions/runs/3199571402/jobs/5225483585

Please have a look.

**Comment by jreiser** [comment]
Please demonstrate the error that you see.  It works for me when built "by hand" using pre-September build system:
```
$ git branch | grep '\*'
* devel4
$ git pull
Already up to date.
$ git log -n 1
commit 1e8f1f49d0b7734b1417f64d0b439786bbe2a07c (HEAD -> devel4, origin/devel4)
Author: John Reiser <jreiser@...com>
Date:   Thu Oct 6 10:15:10 2022 -0700
$ git diff   ## src/Makefile only
-BUILD_TYPE_DEBUG    ?= 0
+BUILD_TYPE_DEBUG    ?= 1
$ make clean; make
   [[snip]]

$ upx.out -f -o foo upx.test   ## compress a copy of upx-devel4-c4437cb-macos-12/release-clang/upx with a short name
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX git-1e8f1f+ Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2022

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   2597528 ->    704528   27.12%   macho/amd64   foo 
                          
$ /home2/upx/src/upx.out -d -f -o bar foo  ## de-compress
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX git-1e8f1f+ Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2022

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   2597528 <-    704528   27.12%   macho/amd64   bar

$ sha256sum $(find .)
4b0837c41f494244c1ddc08fff8bfeb03530f707eb88d5fdc4669095d25e1b9f  ./upx-devel4-c4437cb-macos-12/release-clang/upx
4b0837c41f494244c1ddc08fff8bfeb03530f707eb88d5fdc4669095d25e1b9f  ./upx.test  ## copy with short name
4b0837c41f494244c1ddc08fff8bfeb03530f707eb88d5fdc4669095d25e1b9f  ./bar  ## de-compressed
50cd7cfd8d162f9b74392d353a0564690c7ec531d629ec8b387658260c97c69f  ./foo  ## compressed

$ cmp upx.test bar; echo $?
0  ## files have same content
$ 
```

**Comment by markus-oberhumer** [comment]
@jreiser It seems you have to use compression level `-3` to trigger the problem:

```
upx upx-devel4-1e8f1f4-macos-12/release-clang/upx -3 -o u4_3
upx -t u4_3
upx: u4_3: NotPackedException: not packed by UPX
```

Strange.

**Comment by jreiser** [comment]
Please give an exact URL for `upx-devel4-1e8f1f4-macos-12/release-clang/upx` .   I could not find one on the page https://github.com/upx/upx/actions/runs/3199571402/jobs/5225483585 in any of the sections Build cmake release-clang, Make artifact, Upload artifact, Run basic tests.

**Comment by markus-oberhumer** [comment]
Just visit https://github.com/upx/upx/actions/workflows/ci.yml , there you can see "CI ... Commit 1234567".

In this case it is https://github.com/upx/upx/actions/runs/3199571402 , and the macos-12 Artifact is at the bottom of that page.

(Unfortunately the CodeQL actions are not clearly marked in the generic "Actions")

**Comment by markus-oberhumer** [comment]
@jreiser Are you sure that commit b4167c6 refers to this macos-12 macho/amd64 problem?

In any case it did not change anything: https://github.com/upx/upx/actions/runs/3203149733

**Comment by jreiser** [comment]
@markus-oberhumer  Please fix the tests so that a failing test prints the contents of a bug report, including the lowest-level  execve() which failed.  The link https://github.com/upx/upx/actions/runs/3203149733 claims (line 44) that the failure is `5/10 Test  #5: upx-list .........................***Failed    0.01 sec` but it is not "developer friendly" to find out what that is.

**Comment by jreiser** [comment]
> In any case it did not change anything: https://github.com/upx/upx/actions/runs/3203149733

@markus-oberhumer  It's a bug in `clang` for MacOS 12 at the `release` level for compression level `-3`.

All of compressing at default level, and `-l` (list) and `-t` (test) and `-d` (de-compressing) work for me on MacOS 12 amd64 (All of the work for this Comment was done using Apple command-line developer tools on MacOS 12.)
```
% curl https://github.com/upx/upx/suites/8661462110/artifacts/389799698)  >  upx-devel4-201d9f1-macos-12.tar
% tar xf upx-devel4-201d9f1-macos-12.tar
% cd upx-devel4-201d9f1-macos-12/release-clang/
% shasum -a 256 upx
8eac12590819435b1863c01402af9fd7c0ecda41c793c22e771503d3c555cd39  upx
% ./upx -f -o upx.packed ./upx
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX git-201d9f  Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2022

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   2597528 ->    704528   27.12%   macho/amd64   upx.packed
                   
% ./upx.packed -l ./upx.packed
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX git-201d9f  Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2022

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   2597528 ->    704528   27.12%   macho/amd64   ./upx.packed

% ./upx.packed -t ./upx.packed
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX git-201d9f  Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2022

testing ./upx.packed [OK]

% ./upx.packed -d -f -o upx.unpacked ./upx.packed
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX git-201d9f  Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2022

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   2597528 <-    704528   27.12%   macho/amd64   upx.unpacked

% shasum -a 256 upx*
8eac12590819435b1863c01402af9fd7c0ecda41c793c22e771503d3c555cd39  upx
a72ff34f4eb46cbbf8820918ccc9c67888447dfea166dfb22b30b5595ca31515  upx.packed
8eac12590819435b1863c01402af9fd7c0ecda41c793c22e771503d3c555cd39  upx.unpacked
% cmp upx upx.unpacked    ## no output: files have same content
% 
```

I also installed `brew` and `cmake` and re-compiled and re-built both release-clang/upx and debug-clang/upx "from scratch" (but using pre-generated `stubs/*.h`), and both of those also work for `-l` and `-t` and `-d` at the default compression level.

Then I tried compression level `-3`.  This works for `debug-clang/upx` but fails for `release-clang/upx`:
```
release-clang % ./upx -3 -f -o upx.packed ./upx
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX git-201d9f  Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2022

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   2597528 ->    909328   35.01%   macho/amd64   upx.packed   
                 
release-clang % ./upx.packed -l ./upx.packed
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX git-201d9f  Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2022

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx.packed: ./upx.packed: NotPackedException: not packed by UPX
```

So that's a bug in the build process (compile and link) for `release-clang/upx`.
(Also note that macOS-11 passes the CI tests for 201d9f.)
```
% clang --version
Apple clang version 14.0.0 (clang-1400.0.29.201)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by jreiser** [comment]
> In any case it did not change anything: https://github.com/upx/upx/actions/runs/3203149733

Commit https://github.com/upx/upx/commit/f88bfb36cd15ba5541e2fba256fce0b9f3d33835 above passes my local testing on macos12: 
```
./upx -3 -f -o upx.packed ./upx
./upx.packed -l ./upx.packed
./upx.packed -t ./upx.packed
./upx.packed -d -f -o upx.unpacked ./upx.packed
cmp ./upx ./upx.packed
```
The failed runs on macos12 in 3203149733 actually produced a complaint "Not packed by upx" because the PackHeader could not be found (a bug).  The CI harness discarded this complaint, which is unfriendly towards developers.

**Comment by markus-oberhumer** [comment]
This seems to be fixed.
