### ISSUE TITLE
UPX compressed binaries fail to run on RHEL 9 with SELinux enabled

### ISSUE THREAD

**Issue by markus-oberhumer** [upx/upx#607]
This problem seems to be related to `selinuxuser_execmod`. Help wanted from somebody who is familiar with extensive SELinux internals.

Relevant links:

https://bugzilla.redhat.com/show_bug.cgi?id=2132528

https://github.com/pterodactyl/panel/issues/4410

https://akkadia.org/drepper/selinux-mem.html

(Info: this issue has been extracted from #605)

**Comment by markus-oberhumer** [comment]
Does this also affect Fedora 36?

**Comment by markus-oberhumer** [comment]
@jreiser  I have noticed that the recent devel4 commit c6b2b8c72016ffb81ab0f01bcdf3f64a349cf527 talks about SELinux. Is this related to this issue?

**Comment by jreiser** [comment]
In theory, yes, but I have not seen this in real life on Fedora 36 regardless of /etc/selinux/config setting.  I have downloaded real Red Hat 9.0 (free for developers), perhaps that will exhibit the problem(s).

Various pieces of SELinux do not allow a PT_LOAD to have simultaneous  PRO_EXEC and PRO_WRITE, and one of the pieces forbids adding PROT_EXEC tto a non-MAP_ANONYMOUS segment.  So overlapping de-compression of PROT_EXEC is forbidden except by starting with `read(`, instead of `mmap(`.The rules are not crystal lear about when PROT_EXEC can be added at all.I can find no "recpe" for "legal" JIT compilation.

**Comment by markus-oberhumer** [comment]
I did a quick install of Rocky Linux 9 (Rocky-9.0-20220805.0-x86_64-minimal.iso) in VirtualBox-6.1 and found that upx-4.0.0-amd64_linux and upx-4.0.0-386_linux work (even without the post-4.0.0 c6b2b8c72016ffb81ab0f01bcdf3f64a349cf527 commit; and upx-3.95 and 3.96 do indeed crash).

```
$ uname -a
Linux localhost.localdomain 5.14.0-70.30.1.el9_0.x86_64 #1 SMP PREEMPT Thu Nov 3 20:29:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ rpm -qa | grep selinux-policy
selinux-policy-34.1.29-1.el9_0.2.noarch
selinux-policy-targeted-34.1.29-1.el9_0.2.noarch

$ semanage boolean --list  | grep selinuxuser_
selinuxuser_direct_dri_enabled (on   ,   on)  Allow selinuxuser to direct dri enabled
selinuxuser_execheap           (off  ,  off)  Allow selinuxuser to execheap
selinuxuser_execmod            (off  ,  off)  Allow selinuxuser to execmod
selinuxuser_execstack          (on   ,   on)  Allow selinuxuser to execstack
selinuxuser_mysql_connect_enabled (off  ,  off)  Allow selinuxuser to mysql connect enabled
selinuxuser_ping               (on   ,   on)  Allow selinuxuser to ping
selinuxuser_postgresql_connect_enabled (off  ,  off)  Allow selinuxuser to postgresql connect enabled
selinuxuser_rw_noexattrfile    (on   ,   on)  Allow selinuxuser to rw noexattrfile
selinuxuser_share_music        (off  ,  off)  Allow selinuxuser to share music
selinuxuser_tcp_server         (off  ,  off)  Allow selinuxuser to tcp server
selinuxuser_udp_server         (off  ,  off)  Allow selinuxuser to udp server
selinuxuser_use_ssh_chroot     (off  ,  off)  Allow selinuxuser to use ssh chroot
```

**Comment by markus-oberhumer** [comment]
Works for me, closing.  Please feel free to reopen. (CC @ccallahan  )
