### ISSUE TITLE
Signed Mach-O files cannot be unpacked

### ISSUE THREAD

**Issue by AandersonL** [upx/upx#610]
## What's the problem (or question)?
If a packed binary is signed, `upx -d` will fail.

## What should have happened?
Normally unpack signed binaries.

## Do you have an idea for a solution?
It's possible to solve by removing the signature from the binary
`codesign --remove-signature ls && upx -d ls`

But probably the error is at [p_mach.cpp](https://github.com/upx/upx/blob/devel4/src/p_mach.cpp#L1752), when the `buff` variable is read backwards and eventually hit some signature related byte, then it will start the header search from the wrong offset.

## How can we reproduce the issue?

1.  cp /bin/ls .
2. lipo -thin x86_64 ls -output ls.x86 (cause arm64 packing is broken)
3. upx ls.x86
4. codesign --force --deep -s - ls.x86
5. upx -d ls.x86

## Please tell us details about your environment.

* upx 3.96
* macOS Monterey
* M1/Arm64 
* macOS Monterey
* x86_64

**Comment by jreiser** [comment]
Unpacking (`upx -d`) a signed file invalidates the signing: the position, length, and byte-value contents of the Mach_segments change.  Also, there is no guarantee that `codesign` does not "encrypt" (well, at least obfuscate) some portions of its input; so `upx -d` might not even see the same byte ranges that were written by `upx` and present as input to the signing.  The lack of documentation on exactly what `codesign` does (the input byte ranges, rules, etc.) also discourages any development that is related to `codesign`.  Just apply the workaround as noted in the Description: `codesign --remove-signature` before unpacking (`upx -d`).
