### ISSUE TITLE
C hello world program compressed with UPX crashes on arm64/Raspberry 4 B

### ISSUE THREAD

**Issue by jlesage** [upx/upx#611]
## What's the problem (or question)?
Running a simple, hello world test program crashes with `Illegal instruction` or `Segmentation fault`.

## What should have happened?
The program should run normally.

## Do you have an idea for a solution?
I have other binaries that are compressed with the same version and they work well.  The one that doesn't work is the smallest one.  Could the problem be related to the size of the binary to compress?

## How can we reproduce the issue?
All the following steps are done on a a Raspberry 4 B with 4GB RAM, running the Raspberry OS 64 bit.

First, compile UPX:

1. `sudo apt install git make cmake gcc g++`
2. `git clone https://github.com/upx/upx.git /tmp/upx`
3. `git -C /tmp/upx checkout devel4`
4. `git -C /tmp/upx submodule init`
5. `git -C /tmp/upx submodule update --recursive`
6. `make -C /tmp/upx build/release-gcc -j$(nproc)`

Then, compile the hello world program with `gcc /tmp/test.c -o /tmp/test`.  Content of `test.c` is:

```
#include <stdio.h>
#include <stdlib.h>

int main()
{
    printf("Hello!\n");
    return 0;
}
```

Make sure the `/tmp/test` can run successfully:
```
$ /tmp/test
Hello!
```

Now run UPX on the test program:
```
$ /tmp/upx/build/release-gcc/upx /tmp/test
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX git-fff53e  Markus Oberhumer, Laszlo Molnar & John Reiser   Oct 23rd 2022

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
      9360 ->      7000   74.79%   linux/arm64   test

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
```

Run the test program.  At that point, it crashes either with `Illegal instruction` or `Segmentation fault`:
```
$ /tmp/test
Illegal instruction
 $ /tmp/test
Illegal instruction
$ /tmp/test
Segmentation fault
$ /tmp/test
Segmentation fault
```

## Please tell us details about your environment.

* UPX version used (`upx --version`):
```
upx 4.0.0-git-fff53efc050e
UCL data compression library 1.03
zlib data compression library 1.2.13
LZMA SDK version 4.43
Copyright (C) 1996-2022 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2022 Laszlo Molnar
Copyright (C) 2000-2022 John F. Reiser
Copyright (C) 2002-2022 Jens Medoch
Copyright (C) 1995-2022 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```

* raspinfo:
```
Raspberry Pi 4 Model B Rev 1.2
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"

Raspberry Pi reference 2022-04-04
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 27a8050c3c06e567c794620394a8c2d74262a516, stage2

Linux raspberrypi 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux
```

**Comment by jreiser** [comment]
@jlesage Thank you for a clear, concise, and thorough Description.

The bug was introduced 7 months ago (2022-03-25) when adapting to variable PAGE_SIZE for qemu.  37360c8e089ca6b4d6dc3e33a7cc18fd526b8015 above fixes it.

**Comment by jlesage** [comment]
Hi @jreiser,

I'm still seeing the crash with the  latest `devel4`, that includes [c331b9f](https://github.com/upx/upx/commit/c331b9f1e27cc6ddb439884491021a919e2d5703).

**Comment by jreiser** [comment]
@jlesage  It used to fail for me, as you first reported.  Now it works for me dozens of times, and again today I have reviewed the source `upx-devel4/src/stub/src/amd64-linux.elf-main.c`. (Note the `#include` in `arm64-linux.elf-main.c`.)   In order for changes to the sources for the stubs to propagate info `upx`, a`make all` must be run in the `src/stubs` directory before running `make` in `src`.  Compiling the stubs requires the upx stubtools, which is a non-trivial collection that is available only for Linux x86_64.  That is [partly] why `devel4` uses `podman` to re-build the stubs in a virtual x86_64 environment.  If `upx-devel4/src/stub/arm64-linux.elf-fold.h` does not have a later date than `upx-devel/src/stub/src/amd64-linux.elf-main.c` then the stub has not been re-built from source.

I have attached [hello.upx.debug.gz](https://github.com/upx/upx/files/9854439/hello.upx.debug.gz) which was compiled with  `#define DEBUG 1` in `amd64-linux.elf-main.c`.  The original problem was handling .bss when mapping the PT_INTERP `/lib/ld-linux-aarch64.so.1`.  `readelf --segments` of that file shows that the layout is:
```
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000020d58 0x0000000000020d58  R E    0x10000
  LOAD           0x00000000000214f8 0x00000000000314f8 0x00000000000314f8
                 0x0000000000001ba8 0x0000000000001d08  RW     0x10000
```
The debug output from running `./hello.upx.debug` now ends with
```
INTERP
xfind_pages  0x22  0xffffdacf1120  7  0x0  0xffffdacf1038
 p_vaddr=0x0  p_memsz=0x20d58
 p_vaddr=0x314f8  p_memsz=0x1d08
  addr=0x0  lo=0x0  hi=0x34000
  addr=0xffffaadda000
do_xmap reloc=0xffffaadda000
LOAD p_offset=0x0  p_vaddr=0x0  p_filesz=0x20d58  p_memsz=0x20d58  p_flags=0x5
  mlen=0x21000
mmap addr=0xffffaadda000  len=0x21000  offset=0x0  lo_frag=0x0
LOAD p_offset=0x214f8  p_vaddr=0x314f8  p_filesz=0x1ba8  p_memsz=0x1d08  p_flags=0x6
  mlen=0x3000
mmap addr=0xffffaae0b000  len=0x3000  offset=0x21000  lo_frag=0x4f8
bzero 0xffffffffaae0d0a0  0xf60

auxv_up 7  0xffffaadda000
  33  0xffffaae2d000
  51  0x1270
  16  0x887
  6  0x1000
  17  0x64
  3  0xffffaae0e040
  4  0x38
  5  0x9
  7  0x0
Hello!
```
Inspecting the relevant parameters for the second [PT_]LOAD which includes the .bss:
```
LOAD p_offset=0x214f8  p_vaddr=0x314f8  p_filesz=0x1ba8  p_memsz=0x1d08  p_flags=0x6
  mlen=0x3000
mmap addr=0xffffaae0b000  len=0x3000  offset=0x21000  lo_frag=0x4f8
bzero 0xffffffffaae0d0a0  0xf60
```
we see that the mapped length is `(PAGE_OFFSET & p_vaddr) + p_filesz` which is `(0xfff & 0x000314f8) + 0x1ba8 ==> 0x20a0` and then rounded up to the page boundary `0x3000`.  The rounding up handles both the OS guarantee of "zeroes from `_end` to page boundary", and also allows for the possibility of a larger page size at run time.  The line `mmap addr=0xffffaae0b000  len=0x3000`shows that the mapping was done OK.  The `bzero` line shows that the region from the high end of `p_filesz`, namely `+0x20a0`, to the next page boundary `0x3000` which is `0xf60` away, was cleared.  This includes all of the region `[p_filesz, p_memsz)`.

So, **my request to you** is to run `hello.upx.debug` and see what it reports for mapping and .bss of `ld-linux-aarch64.so.1`.

My RPi4 has
```
$ dpkg --list | grep libc-bin
ii  libc-bin                    2.31-13+deb11u4                arm64        GNU C Library: Binaries
$ sha256sum /lib/ld-linux-aarch64.so.1
98647d6a7853ae206790ae266f0fe00856d6912efffa3194cc4a9e7d41693c57  /lib/ld-linux-aarch64.so.1

**Comment by markus-oberhumer** [comment]
@jreiser I may have made an error transplanting your patches from devel to devel4    98fedef1a16fe7daeb127dd10290a12ad56fef34 - please double check.

Also please note that the latest devel does not build on Actions: https://github.com/upx/upx/actions/runs/3308088020

**Comment by markus-oberhumer** [comment]
Also I noticed an aarch64-linux-musl regression by the last patches in the new upx-test-build-with-zig repo:

Works: 
upx 4.0.0-git-60a054431438
Log: https://github.com/upx/upx-test-build-with-zig/actions/runs/3309031161/jobs/5461828359
Artifact: https://github.com/upx/upx-test-build-with-zig/suites/8919584601/artifacts/408810458

Fails:
upx 4.0.0-git-98fedef1a16f
Log: https://github.com/upx/upx-test-build-with-zig/actions/runs/3312230278/jobs/5468647121
Artifact: https://github.com/upx/upx-test-build-with-zig/suites/8927051264/artifacts/409373435

**Comment by jreiser** [comment]
@markus-oberhumer  Please give pointers (src file paths, locations, URLs, whatever) for "upx-test-build-with-zig".  The latest commit 98fedef1a16fe7daeb127dd10290a12ad56fef34 in devel4 (Mon Oct 24 12:55:20 2022 +0200) has no file whose name contains 'zig'.  There is also no string 'zig' anywhere in the devel4 tree:
```
$ git branch
* devel4
$ git log -n 1
ommit 98fedef1a16fe7daeb127dd10290a12ad56fef34 (HEAD -> devel4, origin/devel4, origin/HEAD)
Author: Markus F.X.J. Oberhumer <markus@...>
Date:   Mon Oct 24 12:55:20 2022 +0200

    testsuite: update checksums
$ find . -name '*zig*'
  # empty output: no filename contains 'zig'
$ grep -sr zig .
  # empty output: no file contains the string 'zig'
```

**Comment by jlesage** [comment]
@jreiser, see attached the output from the binary you provided.  There is one output from a successful run and one from a crashed run (`Illegal instruction`).

[hello_debug_output_success.txt](https://github.com/upx/upx/files/9855363/hello_debug_output_success.txt)
[hello_debug_output_crash.txt](https://github.com/upx/upx/files/9855364/hello_debug_output_crash.txt)

On my Raspberry:
```
$ dpkg --list | grep libc-bin
ii  libc-bin                             2.31-13+rpt2+rpi1+deb11u5        arm64        GNU C Library: Binaries
sha256sum /lib/ld-linux-aarch64.so.1
078b207900a6f78e4072830130ddffe609c5c4475cdc816d994f000851eafd4b  /lib/ld-linux-aarch64.so.1
```

**Comment by markus-oberhumer** [comment]
@jreiser But https://github.com/upx/upx/issues/611#issuecomment-1289537414 contains 4 links - just click on them !!

**Comment by jreiser** [comment]
@jlesage Thank you for the two .txt files of debug output.  They show the same arguments and results for stub debugging, modulo relocation constants.

Changing my `/etc/apt/sources.list` to use `bullseye-updates`, and then running `apt-get update; apt-get upgrade libc-bin` gave me
```
$ dpkg --list | grep libc-bin
ii  libc-bin                    2.31-13+deb11u5                arm64        GNU C Library: Binaries
$ sha256sum /lib/ld-linux-aarch64.so.1
585ea8ab582624fe720e73cdec311fdaf1c4ed481319929dd0ce4c3af8bd21c4  /lib/ld-linux-aarch64.so.1
```
which is closer to, but not quite the same as, your `2.31-13+rpt2+rpi1+deb11u5`.  Where did you get your `libc-bin` package?  And even, where can I download a filesystem image for the Pi OS that you are running?

**Comment by jlesage** [comment]
@jreiser I use the Raspberry Pi OS (64-bit).  You can find the download link here:

https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit

Note that I installed the "Lite" version.

**Comment by markus-oberhumer** [comment]
linux/arm64 now works for me again in devel4 c7ef08dc2d7a4d7ee66e6ef2b9d6b59c1b40e9bd

**Comment by markus-oberhumer** [comment]
@jlesage Please test and close if fixed. Thanks!

**Comment by jlesage** [comment]
I'm not able to reproduce with the latest `devel4`.

Thanks @jreiser and @markus-oberhumer !
