### ISSUE TITLE
Please mark prereleases as those

### ISSUE THREAD

**Issue by SuperSandro2000** [upx/upx#614]
https://github.com/upx/upx/releases/tag/v3.99 is marked as a latest release but in fact it is a prerelease and should be marked as such, so that automation packaging automation is not triggered.

**Comment by markus-oberhumer** [comment]
I may consider that, but (modulo known regressions) 3.99 is much better than 3.96.

**Comment by markus-oberhumer** [comment]
v4.0.0 should be ready very soon, so marked as prerelease.
