### ISSUE TITLE
[Icon] for UPX

### ISSUE THREAD

**Issue by blackcrack** [upx/upx#616]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

The Graphical Gui/Surfaces have no Graphical "Feedback" for the Eyes

## What should have happened?

if i look the Executable, should it have an graphical "underline" with a Graphic in an Filemanager or so, as Icon

## Do you have an idea for a solution?

  
an free under CC-SA builded Icon for grafical Filemanagers in QT,WinNT and other:  

[upx.zip](https://github.com/upx/upx/files/9893067/upx.zip)

it's made like whitehat style , with an round white Background with an small effect, it's shows, if the "Darkmode" on and the Background of the Filemanager is dark ;)

## How can we reproduce the issue?

1. Open in your Windowmanager an Filemanager 
2. go into the Folder where is the UPX executable
3. Make the Eyes open 
4. and Look the Executable

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

WinNT and Fedora , x86 & x86_64
Manny CPU's

best to the UPX Community

**Comment by markus-oberhumer** [comment]
UPX is a console program that does not have any icons. You may want to get in touch with one of UPX GUI frontend apps.

**Comment by blackcrack** [comment]
well, but it is used in WinNT.. also.. well, then.. oky, kick it in the trash..
