### ISSUE TITLE
X64 program decompress crashed

### ISSUE THREAD

**Issue by peter8777555** [upx/upx#619]
* UPX version used (`upx --version`): upx 4.0.0
* Host Operating System and version: Windows 7 X64  SP1
* Host CPU architecture: Intel Q8400

I decompress snapshot64.exe and snapshot64.exe  crashed.

Please refer to the sample file.

[snapshot64.zip](https://github.com/upx/upx/files/9944824/snapshot64.zip)

**Comment by bitraid** [comment]
This is a commercial program that reads and writes its licence information directly into (the end of) the binary, and it expects to be compressed by UPX.

**Comment by peter8777555** [comment]
To bitraid:

I decompress snapshot.exe (X86) is OK.

**Comment by bitraid** [comment]
> To bitraid:
> 
> I decompress snapshot.exe (X86) is OK.

Yes, but when the program is unpacked it doesn't run properly because it reads itself from disk and expects to be packed. This is by design of the program and has nothing to do with UPX.

**Comment by peter8777555** [comment]
To bitraid:

I know,this is another question.

I want to know why
decompress snapshot.exe (X86) is OK.
decompress snapshot64.exe (X64) is NG. can fixed ?

**Comment by bitraid** [comment]
For me they both crash. To find out exactly why, you have to reverse engineer the program (something that I guess is not permitted by its licence).

**Comment by peter8777555** [comment]
bitraid>For me they both crash. For me they both crash. 

For me
decompress snapshot.exe (X86) is OK and run is OK.
decompress snapshot64.exe (X64) is OK but run crashed.
