### ISSUE TITLE
Double packing attempt does not lead to AlreadyPackedException

### ISSUE THREAD

**Issue by jengelh** [upx/upx#622]
## What's the problem (or question)?

```
a4:../Archiving/upx> upx ./upx
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1949752 ->    502756   25.79%   linux/amd64   upx                           

Packed 1 file.
a4:../Archiving/upx> upx ./upx
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: ./upx: CantPackException: need DT_INIT; try "void _init(void){}"

Packed 0 files.
```

## What should have happened?

I would have liked to see

```
upx: ./upx: AlreadyPackagedException: already packed by UPX
```

## How can we reproduce the issue?

1. attempt pack a file twice

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.96 / 4.00
* Host Operating System and version: openSUSE Tumbleweed 20221107
* Host CPU architecture: amd64
* Target Operating System and version: linux-gnu/ELF
* Target CPU architecture: amd64

**Comment by jreiser** [comment]
The Description is half incorrect: upx-3.96 does complain AlreadyPackedException. Using upx-3.96-amd64_linux:
```
$ cp upx upx-396
$ ./upx-396 -o foo ./upx-396
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx-396: ./upx-396: AlreadyPackedException
```

In the analogous situation upx-4.0.0 (Oct 28th 2022) complains `CantPackException: bad ElfXX_Shdrs` which is fixed in b99d8dcbf18d720d4f9a9d5df35ae22416757c47.

**Comment by markus-oberhumer** [comment]
Seems to work now, thanks!

**Comment by jengelh** [comment]
Cannot confirm. Even with state e6c6ea5dfd557a6027d7aa9a583c5daf94d43884 I'm getting that DT_INIT message. Test file attached. I wonder if it is because it's a PIE binary.
[upx.zip](https://github.com/upx/upx/files/9965966/upx.zip)

**Comment by markus-oberhumer** [comment]
Sorry, I'm reopening.

**Comment by jreiser** [comment]
@jengelh Please test https://github.com/upx/upx/commit/84a0d7365c5a2b78d3786839c071c85b214eab02 or later.

**Comment by jengelh** [comment]
Works for me.
