### ISSUE TITLE
UPX 4.01 produces file which does not pass selftest - macho/arm64

### ISSUE THREAD

**Issue by polomsky** [upx/upx#628]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
Testing just compressed file fails with `CantUnpackException: file corrupted`.
And this is the probably reason why file fails with segmentation fault.

## What should have happened?
expected that file will pass testing

## Do you have an idea for a solution?
No idea, but can not reproduce for version 3.96.

## How can we reproduce the issue?
1. build `macho/arm64` binary with go compiler 1.19.3 linux/amd64: `GOOS=darwin GOARCH=arm64 go build -o output file.go`
2. `upx --best output`
3. `upx -t output`

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.0.1
* Host Operating System and version: Linux Mint 20.3 Una, kernel 5.4.0-132-generic
* Host CPU architecture: x86_64
* Target Operating System and version:
* Target CPU architecture: macho/arm64

**Comment by jreiser** [comment]
@polomsky You must upload (`Attach files by` in the footer of each Comment) or give URL to an actual `file.go` which fails.

[Edit:]Also, where did you get go 1.19.3?  Debian bullseye has golang-1.15.15-1.  Fedora 36 has golang-1.18.7-1.fc36.x86_64.

**Comment by polomsky** [comment]
[hello.zip](https://github.com/upx/upx/files/10076702/hello.zip)

@jreiser Go version I have directly from website https://go.dev/dl/go1.19.3.linux-amd64.tar.gz

Edit: the source code
```go
package main

import "fmt"

func main() {
	fmt.Println("HELLO!")
}
```

**Comment by chenrui333** [comment]
I have run into the similar issue

This is my log
```
(lldb) target create "./upx2"
Current executable set to '/Users/rui/Downloads/brew/upx2' (arm64).
(lldb) run -V
error: Bad executable (or shared library)
(lldb) run --version
error: Bad executable (or shared library)
```

I was trying to compress upx by itself using `/opt/homebrew/Cellar/upx/4.0.1/bin/upx -1 upx2`

upx seems built out fine
```
$ /opt/homebrew/Cellar/upx/4.0.1/bin/upx --version
upx 4.0.1
UCL data compression library 1.03
zlib data compression library 1.2.13
LZMA SDK version 4.43
doctest C++ testing framework version 2.4.9
Copyright (C) 1996-2022 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2022 Laszlo Molnar
Copyright (C) 2000-2022 John F. Reiser
Copyright (C) 2002-2022 Jens Medoch
Copyright (C) 1995-2022 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
Copyright (C) 2016-2021 Viktor Kirilov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```

relates to https://github.com/Homebrew/homebrew-core/pull/116052

**Comment by jreiser** [comment]
Fixed by above commit https://github.com/upx/upx/commit/5f0922c40853d44f57bbd317bd76a5a58b49175c .
Builds are available for a while on https://github.com/upx/upx/actions/runs/3808301638 .

**Comment by jimmidyson** [comment]
@jreiser Thanks for fixing this! Any chance of getting a release out including this fix?
