### ISSUE TITLE
EOFException: premature end of file

### ISSUE THREAD

**Issue by google-mirror** [upx/upx#629]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
Compressing libtest.so [linux/arm64, NRV2E/9]
upx: libtest.so: EOFException: premature end of file*************]   20.9%  -

## How can we reproduce the issue?

1. upx.exe --android-shlib -9 libtest.so
2. [libtest.zip](https://github.com/upx/upx/files/10074170/libtest.zip)
3. libtest.so is a valid so and can be run successfully
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): UPX 4.0.1
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
Fixed by above commit https://github.com/upx/upx/commit/5c61279c618ba4516ac73b140202a83a7aa79d57 .

**Comment by markus-oberhumer** [comment]
Testing the compressed file does not work for me, but might be same as #599

```
$ ./upx --version-short
upx 4.0.1-devel.41+git-bb4cbdff

$ ./upx libtest.so -o x2 --android-shlib

$ md5sum libtest.so x2
d3c77c88fde6846e865b2c669e08f69f  libtest.so
ee00728296a51fba5359a343eb5b9f8a  x2

$ ./upx -t x2

testing x2
upx: x2: Exception: compressed data violation

Tested 1 file: 0 ok, 1 error.
```
