### ISSUE TITLE
Packed alertmanager (golang amd64) segfaults on start

### ISSUE THREAD

**Issue by FauxFaux** [upx/upx#63]
## What's the problem (or question)?

If I pack the `alertmanager` tool, which is produced by `go`, the command immediately segfaults on start.

The backtrace is very useless:
```
#0  0x0000000000e5d299 in ?? ()
#1  0x0000000000e5d4a6 in ?? ()
#2  0x0000000000000000 in ?? ()
```

## What should have happened?
I would expect either a warning that it is unpackable, or it to work after packing.

## How can we reproduce the issue?
1. Fetch and build https://github.com/prometheus/alertmanager using golang-1.7.1 on amd64 Ubuntu 16.10.
   * Note that it doesn't use the standard `go get` build process, but is a standard golang binary (as far as I'm aware). I used commit `0ea1cac51e6a620ec09d053f0484b97932b5c902`.
   * Alternatively, grab the binary from http://b.goeswhere.com/alertmanager-c25a54ed4967ef53e8987240b6d1eb754738e7d9bb09d47e59656c3a041ea14c.gz (that's the sha256sum of the file, before compression).
2. `upx alertmanager`
3. `./alertmanager`

This will immediately exit with SIGSEGV.

## Please tell us details about your environment.
* UPX version used (`upx --version`): upx 3.93 (from website) and upx 3.9.1 (from Ubuntu) tested
* Operating System and version: Ubuntu 16.10 ("Yakkety")
* CPU architecture: amd64

**Comment by PaulWebSec** [comment]
#1 and #2 are at the end of the same line while they sum different; this may be an opportunity for dynamic resolution.
Example:
#0  0x0000000000e5d299 in ?? (3*3)
#1  0x0000000000e5d4a6 in ?? (2*2*2)
#2  0x0000000000000000 in ?? (2*2*2*2). . . sets = 4

**Comment by PaulWebSec** [comment]
resolution: 01010101 or 100b

**Comment by jreiser** [comment]
Fixed on devel branch at commit https://github.com/upx/upx/commit/fc261ad8cd6676000abe092c2724a237c864aafa ; related to issue #43.

**Comment by FauxFaux** [comment]
I don't really understand what happened, but it was certainly a form of beauty. Thank you, kind sir.

**Comment by PaulWebSec** [comment]
[UPX TRIALS PROP.docx](https://github.com/upx/upx/files/768759/UPX.TRIALS.PROP.docx)

"here's what happened plus; "
