### ISSUE TITLE
MacOS malware file won't unpack

### ISSUE THREAD

**Issue by albertzsigovits** [upx/upx#630]
## What's the problem (or question)?
Trying to analyze this malicious program, but can't automatically unpack with `upx -d`.
`upx: malwarefile: CantUnpackException: file corrupted`
Would like to understand why it's not unpacking.
Attached the sample, password is `infected`.

## What should have happened?
File should unpack automatically with `upx -d`.

## Do you have an idea for a solution?
The sample looks to be packed with `3.95`.
Not sure, have tried a few different scenarios:
Unpacking with `-d` with upx 4.0.1, on all 3 platforms, Windowsx64, Linuxx64, Mac build, none of them unpack the file.
Tried a few 3rd party UPX fixer/recovery solution, but none of them think it's actually corrupted.
```
Found UPX! Header Position at 948 00000000
Found UPX! Header Position at 1978171
Found UPX! Header Position at 1980558
UPX! p_filesize :0x8c 0x23 0x5a 0x00
Header Position:956
File Size Position:1980582
0x8c compare 0x8c
0x23 compare 0x23
0x5a compare 0x5a
0x00 compare 0x00
```
Everything looks fine.
Needs some extra code to try harder on the corrupted sample?

## How can we reproduce the issue?
`upx -d b81c271d735e2beed0e3fb70a28aee233d794aaa1f528c4272d194e15dcb534e -o unpacked`

## Please tell us details about your environment.
* UPX version used (`upx --version`): `4.01 release`
* Host Operating System and version: `MacOS 13.0.1`
* Host CPU architecture: `x86_64`
* Target Operating System and version: `Ubuntu 20.04.5 LTS, Windows 10.0.19044.2251, MacOS 13.0.1`
* Target CPU architecture: `x86_64`

[8433818436.zip](https://github.com/upx/upx/files/10075827/8433818436.zip)

**Comment by flyingbird** [comment]
[unpacked.zip](https://github.com/upx/upx/files/10093646/unpacked.zip)
Here is the unpacked file :)

**Comment by albertzsigovits** [comment]
Thank you! Any tips or tricks to share? :)

**Comment by flyingbird** [comment]
@albertzsigovits remove the signature first, then unpack.
