### ISSUE TITLE
Arithmetic overflow while reading bundle

### ISSUE THREAD

**Issue by ygoe** [upx/upx#633]
## What's the problem (or question)?
When compressing an application built for linux-arm with .NET 6.0 as a single executable file, an error message is shown when starting the application on the target system. This is the full output:

```
Failure processing application bundle; possible file corruption.
Arithmetic overflow while reading bundle.
A fatal error occured while processing application bundle
```

Does that message come from Linux, bash, upx or .NET? I have no idea. It's not from my application.

The compiled application file is 13 MB and compresses to a little less than half of it, so using upx is desirable here to minimise the ready-to-run download size.

## What should have happened?
The application should start and print its own messages.

## Do you have an idea for a solution?
No.

## How can we reproduce the issue?
1. Create a .NET 6.0 console application and publish it as single file for linux-arm (on Windows)
2. Compress the file: `upx MyApp` (on Windows)
3. Copy the executable on a Raspberry Pi (32-bit OS)
4. Run the application: `./MyApp`

## Please tell us details about your environment.
* UPX version used (`upx --version`): 4.0.1 for win-x64 (just downloaded)
* Host Operating System and version: Windows 10
* Host CPU architecture: amd64
* Target Operating System and version: Raspberry Pi OS
* Target CPU architecture: armhf

**Comment by jreiser** [comment]
@yoge You must upload (`Attach files by ...` in the footer of a new Comment) or give the URL of an actual input file which fails to run after compression.  There is no other way that we can reproduce exactly what you see, which is necessary for debuggging.  In particular, it is very unclear exactly what kind of executable you are talking about.  WTF is a `.NET 6.0 console application` that is targeted at 32-bit armhf under Raspberrry Pi OS?

Also note that `.NET` executables for Windows are not supported in general.  No one on UPX Team is interested.

**Comment by ygoe** [comment]
I'll attach a simple application tomorrow. I'm not using a normal framework-dependent .NET assembly (like we had it the past 20 years) but a natively compiled executable that is just a single self-contained file and has zero dependencies on the target system, in this case Linux. I'd assume that should just work with upx.

**Comment by bitraid** [comment]
Although the bundle contains .NET executables, it is not a .NET file itself, but you should not use UPX on it. The bundle will read itself from disk at runtime to extract its files, and should not be modified in any way (plus, it already supports compression).

**Comment by ygoe** [comment]
Alright, I've read up this topic closer than last time and found out that what was advertised as AOT compilation wasn't fully native code in .NET 6. Native AOT compilation has been added in .NET 7 and when I use this, I can successfully compress a sample application with upx for Win64 (from 3 down to 1 MB). So it seems that the message I saw came from .NET and not upx.
