### ISSUE TITLE
FreeBSD 13.1 UnknownExecutableFormatException

### ISSUE THREAD

**Issue by SeanKS4TD** [upx/upx#636]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
When attempting to use UPX on a FreeBSD binary, a UnknownExecutableFormatException error is thrown.

## What should have happened?
The binary should be successfully compressed.

## Do you have an idea for a solution?
No.

## How can we reproduce the issue?

Attempt to compress a FreeBSD binary using UPX (I've attached *hello.gz* which is a "hello world" written in Free Pascal and compiled under FreeBSD 13.1 for testing).

## Please tell us details about your environment.
[hello.gz](https://github.com/upx/upx/files/10145658/hello.gz)

* UPX version used (`upx --version`):

```
  upx 3.96
  UCL data compression library 1.03
  zlib data compression library 1.2.12
  LZMA SDK version 4.43
```

* Host Operating System and version: FreeBSD 13.1-RELEASE-p3
* Host CPU architecture: amd64
* Target Operating System and version: FreeBSD 13.1-RELEASE-p3
* Target CPU architecture: amd64

**Comment by jreiser** [comment]
64-bit FreeBSD is not supported.
