### ISSUE TITLE
UPX in open crash

### ISSUE THREAD

**Issue by hrsk123** [upx/upx#637]
Csáo csáo na az lenne a probléma hogy a Loadert ahogy megnyitom crashel

Hello my problem are If i opne the loader instant crash

**Comment by jreiser** [comment]
You made `no attempt` to follow our NewIssue(BugReport) template, which guides you to supply the information that is required to reproduce the problem that you see.

```
<!---

IF YOU REMOVE THIS TEMPLATE WE WILL CLOSE YOUR ISSUE WITHOUT RESPONSE.
Just read it and fill in the details we're asking, it saves so much of our time. Thanks!

-->
```
