### ISSUE TITLE
Windows executable - decompressed exe crashes

### ISSUE THREAD

**Issue by LoZio** [upx/upx#638]
## What's the problem (or question)?
I need to decompress a backup program that is UPX compressed. Our EDR marks it as a threat. It is not. No way to tinker on the EDR side. The exe is snapshot64.exe from here http://drivesnapshot.de/en/down.htm
Decompression is fine with
```
     File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   4198176 <-   1367328   32.57%    win64/pe     snapshot64.exe
```
But executable file crashes with
![image](https://user-images.githubusercontent.com/869890/207351845-d22985fd-ac12-48c9-aba8-c80f670a0c7c.png)

## What should have happened?
Program starts

## Do you have an idea for a solution?
Actually not. I read several threads about relocatable executables (ALSR) not being reconstructed fine in "latest" versions, but nothing changes also with older versions back to 2.x. The error seems to point to resource not being rebuilt ok.

## How can we reproduce the issue?

1. Grab http://www.drivesnapshot.de/download/snapshot64.exe
2. upx.exe -d snapshot64.exe
3. .\snapshot64.exe

## Please tell us details about your environment.

* UPX version used (`upx --version`): any from 2.96 => 4.0.1
* Host Operating System and version: Windows 10 22H2
* Host CPU architecture: x64
* Target Operating System and version: Win64
* Target CPU architecture: x64

**Comment by LoZio** [comment]
If you open the executable with ResourceHacker you can see that the STARTUPSCREEN dialog resource is broken, it is the only one between many

**Comment by bitraid** [comment]
This is #619 again. I guess people are trying to crack the program because the keygen that the scene group "CORE" released back in '15, no longer works on recent versions. This is a very good program and it's more that worth its money (plus, you probably won't succeed in cracking it).

**Comment by LoZio** [comment]
You're wrong by a long shot and I know the value of that tool, our company used it back in the Windows 2003 days. Also you do not need any crack for it if you're on the steal side, its check is date-based and I suppose you know this is a no brainer.
If this is against some policy you can close the issue (and keep the decompression routine broken).

**Comment by bitraid** [comment]
The decompression is not broken - see https://github.com/upx/upx/issues/619#issuecomment-1304665581 on why this happens.

**Comment by jreiser** [comment]
Same as #619
