### ISSUE TITLE
UPX incorrectly compresses files from which there are BSS sections containing data

### ISSUE THREAD

**Issue by fixer121** [upx/upx#639]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

There is a PE file that has data in a section marked as uninitialized data.
The file has been dumped from memory.

The system loads such sections into memory and uses/performs as usual.
However, UPX refuses to compress the file with the following message:

E:\>upx r.bss_section.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX 4.0.1       Markus Oberhumer, Laszlo Molnar & John Reiser   Nov 16th 2022

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: r.bss_section.exe: CantPackException: superfluous data between sections (try --force)
Packed 1 file: 0 ok, 1 error.

An attempt to compress with the --force option creates a very small file that is completely inoperable.
An attempt to uncompress it will fade to an error:

E:\>upx r.bss_section.exe --force
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX 4.0.1       Markus Oberhumer, Laszlo Molnar & John Reiser   Nov 16th 2022

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1019904 ->     38912    3.82%    win32/pe     r.bss_section.exe

Packed 1 file.

E:\>upx -d r.bss_section.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX 4.0.1       Markus Oberhumer, Laszlo Molnar & John Reiser   Nov 16th 2022

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: r.bss_section.exe: CantUnpackException: mem_size 2; take care

Unpacked 1 file: 0 ok, 1 error.

I put to archive file r.exe also. It is the same file as r.bss_section.exe, but it has reset the BSS flags for all section in the object table, it also runs normally.

This files you can download from:
https://cloud.mail.ru/public/kH9i/JeZjHxUuv

## What should have happened?

I have analyzed a piece of UPX source code. Condition 1 is met for a number of sections of this file
On the next passes of the cycle, this leads to the condition (condition 2), the output of the error message, and the failure to compress.

    if ((isection[ic].flags & PEFL_BSS) || isection[ic].rawdataptr == 0  	// condition 1
        || (isection[ic].flags & PEFL_INFO))
    {
        holes.add(isection[ic].vaddr,isection[ic].vsize);
        continue;
    }
   ...
    if (jc && isection[ic].rawdataptr - jc > ih.filealign)			// condition 2
        throwCantPack("superfluous data between sections");

## Do you have an idea for a solution?

I propose:
Process BSS section that have data as normal (as the operating system does).

## How can we reproduce the issue?

1.Download archive from https://cloud.mail.ru/public/kH9i/JeZjHxUuv and unpack it
2.run 
upx r.bss_section.exe

## Please tell us details about your environment.

* UPX version used (`upx --version`):
E:\>upx --version
upx 4.0.1
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.13
LZMA SDK version 4.43
Copyright (C) 1996-2022 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2022 Laszlo Molnar
Copyright (C) 2000-2022 John F. Reiser
Copyright (C) 2002-2022 Jens Medoch
Copyright (C) 1995-2022 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.

* Host Operating System and version:
Windows 7 x64, Windows 10 x64
* Host CPU architecture:
Intel, AMD
* Target Operating System and version:
same
* Target CPU architecture:
same

**Comment by jreiser** [comment]
> [r.exe] is the same file as r.bss_section.exe, but it has reset the BSS flags for all section in the object table, it also runs normally.

1) Why not write a small utility program which resets the BSS flags; then apply that utility program before invoking UPX?
2) Why not fix the memory dumper to clear the PEFL_BSS flag when a section contains initialized data?
3) Why not use GitHub to create a Fork of UPX, apply the changes you desire, then compile and use that?  If it works, then submit a Pull Request for consideration by UPX Team.

**Comment by fixer121** [comment]
If the system launches a PE file, albeit not quite standard, then the system does not consider it non-standard, then it is necessary to adapt UPX like this, it is necessary that after compression such files can also be launched. Just suggest making UPX more versatile. In this case, I found out the reason for this behavior by looking into the source code of UPX, but the reason will not be understood by others.
In some cases, you need to compress protected files. This change will help solve some of the problems with such files.

**Comment by fixer121** [comment]
Bringing to standard is a very good thing. Our task is to teach UPX to compress files that the system considers acceptable in fact.

**Comment by jreiser** [comment]
The work-around of a utility program to clear the BSS flag (and otherwise change a "BSS" section that contains bytes with  non-zero values  into a DATA section) implies that the original complaint is only an inconvenience.  The root cause of the inconvenience is the memory dumper program which forgot to perform this operation in the first place.  Please identify the memory dumper program, and spend at least as much resources getting it fixed as complaining about UPX.  As for Standards, the meaning of `BSS` as "block of memory with all values zero"  has been around for at least 60 years.  Just because Microsoft Windows allows non-conformance is no reason to require every other program to ignore it, too.
