### ISSUE TITLE
Cross-compiling from release source tarball.

### ISSUE THREAD

**Issue by lancethepants** [upx/upx#64]
## What's the problem (or question)?
When compiling (cross-compiling for armel on x86_64) with upx-3.93-src.tar.xz source it fails with 

./../src/stub/scripts/check_whitespace.sh ./..
ERROR: binary file detected ./src/c_file.o: ELF(|4(

At this point it has compiled all .cpp files and it's ready to link.
If I `mkdir .git` in top_srcdir it compiles OK.
I only ever cross-compile upx, so not sure if a factor or not.  It doesn't like something about check_whitespace.sh, but when using check_whitespace_git.sh it works.  Compiling from git works without issue.

## What should have happened?
have upx.out binary

## Do you have an idea for a solution?
Seems it thinks it's compiling when it should really should be linking?
Maybe needs something more done when preparing release source tarballs from git.

## How can we reproduce the issue?

1. x-compile ucl/zlib

2.

```
export UPX_UCLDIR=/dir/to/ucl-1.03

LDFLAGS="-static -L/point/to/zlib" \
CPPFLAGS="-I/point/to/zlib" \
CXXFLAGS="-some -cpu -options" \
make \
CXX=arm-linux-g++ \
all
```

## Please tell us details about your environment.

Debian 8 x86_64

**Comment by markus-oberhumer** [comment]
Please build in a subdir called "build" (see check_whitespace.sh for details) or use an out-of-tree build directory.

Or just use ```make CHECK_WHITESPACE=/bin/true```

**Comment by cieplutki** [comment]
> Or just use make CHECK_WHITESPACE=/bin/true

Now it works! Thanks. I added it to my version of README.
After long time and many swears I started to check what this `src/stub/scripts/check_whitespace.sh ` script is actually doing and didn't get any satisfactory conclusions.
You should add it to README or README.SRC as there is nothing about that and if anyone follows instructions they will hit the wall.

Getting back to README.SRC instructions it just says
 ```
 Set the environment variable UPX_UCLDIR to point to your  UCL build directory, e.g.
     export UPX_UCLDIR=$HOME/local/src/ucl-1.03       (Unix)
  Finally type
     make 
```
and when you do
$ make
you get 

`UPX info: please choose a target for 'make'
`
How am I suppose to know what are the targets? I tried 'src', 'doc' and all I got 

`make: Nothing to be done for `src'.
`
Would it be impudent to actually propose some improvement to Makefile?
In section `default` you can add depending target and it will do make everything automagically: (check attached .diff)
```
-default:
-	@echo "UPX info: please choose a target for 'make'"
+default: all
+#	@echo "UPX info: please choose a target for 'make'"

```

------------------------------------

> Please build in a subdir called "build" (see check_whitespace.sh for details) or use an out-of-tree build directory.

This one I don't get - what do you mean?
```
/usr/src/upx-3.93-src/ $ mkdir build
/usr/src/upx-3.93-src/ $ cd build
/usr/src/upx-3.93-src/build/ $ make -f ../Makefile

```
?

[Makefile.diff.gz](https://github.com/upx/upx/files/948462/Makefile.diff.gz)

**Comment by jaykepeters** [comment]
how build on mac
