### ISSUE TITLE
ncmds errors during decompression of files

### ISSUE THREAD

**Issue by ashrivastav** [upx/upx#642]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
While trying to decompress file we are getting folowing error: 

./upx --decompress packed_1ea852a26424cbdb583e7c2bf1e9a2412274063f9a945b25d39e30d02e54c5e0
[doctest] doctest version is 2.4.9
[doctest] compiler version is gcc 9.4.0 (64-bit)
[doctest] run with "--dt-help" for options
[doctest] test cases:  28 |  28 passed | 0 failed | 0 skipped
[doctest] assertions: 393 | 393 passed | 0 failed |
[doctest] Status: SUCCESS!
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX git-7c57b1  Markus Oberhumer, Laszlo Molnar & John Reiser   Nov 22nd 2022

        File size         Ratio      Format      Name

upx: packed_1ea852a26424cbdb583e7c2bf1e9a2412274063f9a945b25d39e30d02e54c5e0: CantUnpackException: bad Mach_header.ncmds = 30

## What should have happened?

The file should decompress properly.
./upx --decompress packed_1ea852a26424cbdb583e7c2bf1e9a2412274063f9a945b25d39e30d02e54c5e0
[doctest] doctest version is 2.4.9
[doctest] compiler version is gcc 9.4.0 (64-bit)
[doctest] run with "--dt-help" for options
[doctest] test cases:  28 |  28 passed | 0 failed | 0 skipped
[doctest] assertions: 361 | 361 passed | 0 failed |
[doctest] Status: SUCCESS!
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX git-fdec47  Markus Oberhumer, Laszlo Molnar & John Reiser   Nov 16th 2022

        File size         Ratio      Format      Name
    329984 <-    106512   32.28%   macho/i386    packed_1ea852a26424cbdb583e7c2bf1e9a2412274063f9a945b25d39e30d02e54c5e0

Unpacked 1 file.
-
 ./upx -t macho_x64_all_variations/Calculator_391_lzma
[doctest] doctest version is 2.4.9
[doctest] compiler version is gcc 9.4.0 (64-bit)
[doctest] run with "--dt-help" for options
[doctest] test cases:  28 |  28 passed | 0 failed | 0 skipped
[doctest] assertions: 393 | 393 passed | 0 failed |
[doctest] Status: SUCCESS!
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2022
UPX git-7c57b1  Markus Oberhumer, Laszlo Molnar & John Reiser   Nov 22nd 2022

testing macho_x64_all_variations/Calculator_391_lzma
upx: macho_x64_all_variations/Calculator_391_lzma: CantUnpackException: bad Mach_header.ncmds = 26

Tested 1 file: 0 ok, 1 error.

[Calculator_391_lzma.zip](https://github.com/upx/upx/files/10317404/Calculator_391_lzma.zip)

## Do you have an idea for a solution?
 Already raised a Pull request for the same.

## How can we reproduce the issue?

1. Take any macho file with number of lc segements more than 24, we can't decompress such files due to error.
2. Uploaded a sample Calculator macho with ncmds more than 24, we can find many more examples.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx v4.0.1
* Host Operating System and version: Ubuntu 18
* Host CPU architecture: x86_64
* Target Operating System and version: Ubuntu 18
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
@ashrivastav Please upload ("Attach files by ..." in the footer while entering a Comment here on GitHub) or give the URL of an actual file which suffers the complaint.  Or, in this case, please upload a file which contains the first `Mach_header.sizeofcmds` bytes of a file which suffers the complaint.  It is necessary to see what other limits may be endangered.

**Comment by ashrivastav** [comment]
> @ashrivastav Please upload ("Attach files by ..." in the footer while entering a Comment here on GitHub) or give the URL of an actual file which suffers the complaint. Or, in this case, please upload a file which contains the first `Mach_header.sizeofcmds` bytes of a file which suffers the complaint. It is necessary to see what other limits may be endangered.

Uploaded sample calculator with ncmds 26 , but we can find more files with ncmds in 30's as well easily.

**Comment by jreiser** [comment]
Fixed by above commit https://github.com/upx/upx/commit/4a3aecb3bf4af3fb9c2e03a635783e0c08f61217 .  ncmds can be large because the number of DYLIB can be large.  Changing just ncmds is easy.  But the Mach_command LC_LOAD_DYLIB contains the name of the library, which can be a long character string; so sizeofcmds also should change.
