### ISSUE TITLE
The dll of win32 cannot be loaded after processing

### ISSUE THREAD

**Issue by vmtest888** [upx/upx#643]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):  4.0.1
* Host Operating System and version:   win10
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

The program only uses protobuf

```
#include "pch.h"
#include "addressbook.pb.h"

#pragma comment(lib, "libprotobuf.lib")

BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}
```

dll is 32 bit
test_protobuf_32_upx.dll is processed by upx
test_protobuf_32.dll is unprocessed

```
C:\Users\Administrator>C:\\Python27\\python.exe
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> ctypes.WinDLL(r'C:\\Users\\Administrator\\source\\repos\\test_protobuf_32\\Release\\test_protobuf_32_upx.dll') 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 1114] 动态链接库(DLL)
>>> ctypes.WinDLL(r'C:\\Users\\Administrator\\source\\repos\\test_protobuf_32\\Release\\test_protobuf_32.dll')     
<WinDLL 'C:\\Users\\Administrator\\source\\repos\\test_protobuf_32\\Release\\test_protobuf_32.dll', handle 7b460000 at 2b09930>
>>>
```

The two dlls are in the attachment
[Release.zip](https://github.com/upx/upx/files/10378495/Release.zip)

pdb file
[pdb.zip](https://github.com/upx/upx/files/10378517/pdb.zip)

**Comment by vmtest888** [comment]
![lQLPJwoIQuRO3MDNBM_NB2mwpyQSSKwOKhoDuEOCyQAOAA_1897_1231](https://user-images.githubusercontent.com/26427035/211488469-a6c96538-346a-4740-8ed6-ab496aec624b.png)

![1673335820139_51B64F7A-2F26-43e9-B52F-03F28B10882D](https://user-images.githubusercontent.com/26427035/211488739-755cdbf1-e089-48cc-b8f9-34c6f078bb36.png)

Looks like _tls_index error

**Comment by vmtest888** [comment]
amd64-win64.pep.S will save and restore tls, i386-win32.pe.S will not。


amd64-win64.pep.S  
```
section         PETLSHAK
                lea     rax, [rdi + tls_address]
                push    [rax]   // save the TLS index
                mov     [rax],  IMM32(tls_value) // restore compressed data overwritten by the TLS index
                push    rax

...

section         PETLSHAK2               // restore the TLS index
                pop     rdi
                pop     rax
                mov     [rdi], eax
```

**Comment by ml1050** [comment]
Can you please check what value the tls index points to when loading the uncompressed and the compressed DLL? In the compressed case UPX assumes that after uncompression is finished the tls index points to a 0. But this may be not correct when at the point of PETLSHAK the tls index points to something which is not 0.

**Comment by vmtest888** [comment]
In the screenshot above, the tls index is 5.

> Can you please check what value the tls index points to when loading the uncompressed and the compressed DLL? In the compressed case UPX assumes that after uncompression is finished the tls index points to a 0. But this may be not correct when at the point of PETLSHAK the tls index points to something which is not 0.

**Comment by vmtest888** [comment]
No problem with x64, I think you can refer to PETLSHAK2 for x64

**Comment by ml1050** [comment]
Okay, if the tls_index points to 5 when the dll is loaded then upx's assumption of 0 is not correct. So a snippet like the above mentioned PETLSHAK2 is needed for the 32-bit case too. I'm not sure why we  added this extra code to the 64-bit code path only...

**Comment by vmtest888** [comment]
Hmm, so please add PETLSHAK2 for pe x86 and I'll try again

**Comment by jreiser** [comment]
I've only cursory knowledge of this issue, but I made the indicated source changes and auto-built via Actions.  WARNING: UNTESTED.

**Comment by vmtest888** [comment]
@jreiser 

![1673575824433_3C425DB2-3D7C-42e9-8BA3-7ECE987C706F](https://user-images.githubusercontent.com/26427035/212221080-4c77f31b-bba6-4ae6-9e7f-435047c040be.png)

![lQLPJwnj4Y8pOBDNAl7NCJewm5phTE14DV8Du9eNZcChAA_2199_606](https://user-images.githubusercontent.com/26427035/212221097-09bfa6b9-8287-40f4-8507-a804c2217ba9.png)

eax is not assigned, it is 0, crashed.



I think it might be handled like this
```
section         PETLSHAK
                //mov     dword ptr [edi + tls_address], offset tls_value
                lea       eax, [edi + tls_address]
                push    [eax]   // save the TLS index
                mov     dword ptr [eax], offset tls_value // restore compressed data overwritten by the TLS index
                push    eax
```

**Comment by jreiser** [comment]
Trying again...

**Comment by vmtest888** [comment]
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX git-826725  Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    830976 ->    313856   37.77%    win32/pe     test_protobuf_32_upx.dll

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
```

@jreiser 
The new commit test above passes. By the way, when will the official version 4.0.2 be released?

```
D:\work\source\upx.git\src\stub>C:\\Python27\\python.exe 
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> ctypes.WinDLL(r'C:\\Users\\Administrator\\source\\repos\\test_protobuf_32\\Release\\test_protobuf_32_upx.dll')
<WinDLL 'C:\\Users\\Administrator\\source\\repos\\test_protobuf_32\\Release\\test_protobuf_32_upx.dll', handle 2d80000 at 2b0dd90>
>>> ctypes.WinDLL(r'C:\\Users\\Administrator\\source\\repos\\test_protobuf_32\\Release\\test_protobuf_32.dll')     
<WinDLL 'C:\\Users\\Administrator\\source\\repos\\test_protobuf_32\\Release\\test_protobuf_32.dll', handle 7b150000 at 2b194b0>
>>>
```

**Comment by jreiser** [comment]
@vmtest888 Thank you for crisp reporting, for help in pin-pointing the problem, and for assistance in debugging and coding and testing.
Only Markus decides the date of an official release.  The minimum requirement usually is closing of all Issues for the milestone.  For 4.0.2, the current count is 7 closed of 8 total, and it looks like the 8th might be closed soon.  After that, there should be confidence of sufficient testing; user reports of the methdology and scope of testing can help!.  Then, actually making a release is not quite 100% automated, so the task must fit into the Markus calendar.  Short answer: I really do not know when.
