### ISSUE TITLE
valgrind memcheck.h file missing on branch devel4

### ISSUE THREAD

**Issue by jreiser** [upx/upx#644]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

Branch devel4 does not build.
```
$ git checkout devel4; git log -n 1
commit d92d5e00d1d3436a6e1544366bf3b71c0997e1b4 (HEAD -> devel4, origin/devel4, origin/HEAD)
Merge: ba76a1df cc994326
Author: Markus F.X.J. Oberhumer <markus@...>
Date:   Sun Jan 15 14:09:50 2023 +0100

    Merge branch 'devel' into devel4

$ cd build/debug; cmake --build .
[ 36%] Building CXX object CMakeFiles/upx.dir/src/c_file.cpp.o
In file included from /path/to/src/c_file.cpp:28:
/path/to/src/conf.h:145:12: fatal error: valgrind/include/valgrind/memcheck.h: No such file or directory
  145 | #  include <valgrind/include/valgrind/memcheck.h>
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
## What should have happened?

The branch should build successfully.
## Do you have an idea for a solution?

`git add` all necessary files.

## How can we reproduce the issue?

1. git checkout devel4
2. mkdir -p build/debug; cd build/debug
3. cmake --build .
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): commit d92d5e00d1d3436a6e1544366bf3b71c0997e1b4
* Host Operating System and version: Linux  6.0.15-200.fc36.x86_64
* Host CPU architecture: x86_64
* Target Operating System and version: Linux  6.0.15-200.fc36.x86_64 (same as Host)
* Target CPU architecture: x86_64

**Comment by markus-oberhumer** [comment]
Please run `git submodule update --init`
