### ISSUE TITLE
release windows-arm64 binary

### ISSUE THREAD

**Issue by namoen0301** [upx/upx#645]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

Currently only x86 and x64 version are shipped as part of the release. It's possible to build arm64 binaries for windows.
VS2019/2022 has been released a fully ARM64 windows msvc build toolchain, so i think it's not hard.

## What should have happened?
release windows arm64 version such as `upx-4.0.2-winarm64.zip`

by the way, i noticed https://github.com/upx/upx/commit/8d364c82e28518d45e25ae19e816d14d06d8b576 , it means upx will release arm64ec version?

## Do you have an idea for a solution?
I successfully built a upx windows arm64 binary which used MSVC+vcpkg+CMake.
![image](https://user-images.githubusercontent.com/4280572/219334940-bd3a309a-e925-41e5-baf2-61bacb62841b.png)

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.0.2
* Host Operating System and version: Windows 11 22h2 22621.1265
* Host CPU architecture: x86_64
* Target Operating System and version: Windows 11 22h2 22621.1265
* Target CPU architecture: arm64

**Comment by markus-oberhumer** [comment]
Building win64/arm64 binaries is trivial - but official binaries will only be released once UPX actually supports win64/arm64. Blocked by issue #502
