### ISSUE TITLE
Version 4.0.2 can not compress my program (tmt/adam format) but previous versions did this

### ISSUE THREAD

**Issue by CandyMan30** [upx/upx#646]
upx: tmt/adam: bad header; imagesize=0x309000  entry=0  relocsize=0x3f030
upx: NDN.PRG: CantPackException: can't pack new-exe
[NDN.zip](https://github.com/upx/upx/files/10765980/NDN.zip)

**Comment by jreiser** [comment]
https://github.com/upx/upx/issues/632 probably is related.

**Comment by markus-oberhumer** [comment]
Should be fixed in devel branch, but please test with your binaries.
