### ISSUE TITLE
[CantPackException: can't pack new-exe] when trying to pack a Windows on ARM exe built with Clang-LLVM-MinGW-LLD toolchain

### ISSUE THREAD

**Issue by okibcn** [upx/upx#647]
## What's the problem (or question)?
After generating EXE files for Windows using the Clang-LLVM-MinGW-LLD toolchain, the winarm64 version can't be compacted while the win32 and win64 can be compacted. This is the output:

```
> .\upx.exe .\nano_win_arm64.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX git-c18180  Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: .\nano_win_arm64.exe: CantPackException: can't pack new-exe
Packed 0 files.

WARNING: this is an unstable beta version - use for testing only! Really.
```

I have tested with the current upx release v4.0.2 and with a fresh build using upx commit [c181806](https://github.com/upx/upx/commit/c181806414beb772906989e175e7df00f5d2cea3). Both show the same message.

Note the other two versions for win32 and win64 can be packed without a problem.

## What should have happened?
It should have properly packed the exe file.

## Do you have an idea for a solution?
Not yet, but probably the `strip` [source code](https://github.com/llvm/llvm-project/tree/main/llvm/lib/ObjCopy)  of the [LLVM project](https://github.com/llvm/llvm-project) can provide some clue about the structure of the exe file generated for LLVM executables for Windows on ARM.
In any case, a brief inspection of the DOS, PE, COFF headers and content directory info doesn't show anything out of a normal Windows EXE file for the 0xAA64 (little endian ARM64) [machine type](https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#machine-types).

## How can we reproduce the issue?
1. Download the attached [nano.zip](https://github.com/upx/upx/files/10775355/nano.zip) including Windows versions for amd64 and arm64 compiled using both the same LLVM toolchain.
2. extract to a folder and run upx in both with `upx *`
This is the output:
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX git-c18180  Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    611840 ->    290304   47.45%    win64/pe     nano_win_amd64.exe
upx: nano_win_arm64.exe: CantPackException: can't pack new-exe

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.

```
## Please tell us details about your environment.
* UPX version used (`upx --version`): same behavior using the latest release v4.0.2 and with a fresh build using commit [c181806](https://github.com/upx/upx/commit/c181806414beb772906989e175e7df00f5d2cea3). Both show the same issue. This is the output of the dev-test version:
```
upx 4.0.3-git-c181806414be
UCL data compression library 1.03
zlib data compression library 1.2.13.1-motley
LZMA SDK version 4.43
doctest C++ testing framework version 2.4.9
```
* Host Operating System and version: Same output in Windows 11 dev preview build 25300 and Ubuntu 22.04.1 
* Host CPU architecture: amd64
* Target Operating System and version: Windows 11
* Target CPU architecture: arm64

**Comment by okibcn** [comment]
It is the same message described in issue #245  or issue #320. However, since this time it is not a VS-generated executable, but generated using LLVM, it is most probably caused by a different issue.

**Comment by markus-oberhumer** [comment]
win64/arm64 is not supported by UPX (see #502), but we need a better error message

**Comment by okibcn** [comment]
> win64/arm64 is not supported by UPX (see #502), but we need a better error message

@markus-oberhumer I think #502 is a different issue. That one is a request to officially support WoA as a host. But, this issue is about supporting WoA as a target exe platform. Actually, WoA is already supported for binaries generated by MSVC isn't it?

**Comment by markus-oberhumer** [comment]
Fixed in devel branch.
