### ISSUE TITLE
armv7l upx compressed binary segfaulting

### ISSUE THREAD

**Issue by satmandu** [upx/upx#654]
## What's the problem (or question)?

Upx compressed armv7l binary (from git 2.39.2) is segfaulting. `upx -d` gives us a working binary though.
```
chronos@rpi4b-armv7l /usr/local/lib/crew/packages $ /usr/local/libexec/git-core/git-remote-https
Segmentation fault (core dumped)
chronos@rpi4b-armv7l /usr/local/lib/crew/packages $ upx -d /usr/local/libexec/git-core/git-remote-https
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.2       Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 30th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    612344 <-    332392   54.28%    linux/arm    git-remote-https

Unpacked 1 file.
chronos@rpi4b-armv7l /usr/local/lib/crew/packages $ /usr/local/libexec/git-core/git-remote-https
error: remote-curl: usage: git remote-curl <remote> [<URL>]

```

## How can we reproduce the issue?

1. The problematic compressed binary is inside https://gitlab.com/api/v4/projects/26210301/packages/generic/git/2.39.2_armv7l/git-2.39.2-chromeos-armv7l.tar.xz at `/usr/local/libexec/git-core/git-remote-https`
2. When decompressed it works fine.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 
```
upx --version
upx 4.0.2
UCL data compression library 1.03
zlib data compression library 1.2.13.1-motley
LZMA SDK version 4.43
doctest C++ testing framework version 2.4.9
Copyright (C) 1996-2023 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2023 Laszlo Molnar
Copyright (C) 2000-2023 John F. Reiser
Copyright (C) 2002-2023 Jens Medoch
Copyright (C) 1995-2022 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
Copyright (C) 2016-2021 Viktor Kirilov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```
* Host Operating System and version: Chromebrew/M91
* Host CPU architecture: armv7l
* Target Operating System and version: Chromebrew
* Target CPU architecture: armv7l

**Comment by jreiser** [comment]
Please test.  Pre-built executables at https://github.com/upx/upx/actions/runs/4328879494

**Comment by satmandu** [comment]
The segfault is gone on armv7l, and doesn't occur on i686 or x86_64.
```
chronos@rpi4b-armv7l /usr/local/lib/crew/packages $ /usr/local/libexec/git-core/git-remote-https
error: remote-curl: usage: git remote-curl <remote> [<url>
```

**Comment by satmandu** [comment]
Fixed by https://github.com/upx/upx/commit/bedef6fbdbb5122858f5abd5ef7a3de3d5569221
