### ISSUE TITLE
CantPackException: bad DT_{0x5} = 0xa000 (beyond EOF), CantUnpackException: header corrupted 4

### ISSUE THREAD

**Issue by satmandu** [upx/upx#655]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
Using `upx --lzma` on `/usr/local/libexec/at-spi-bus-launcher` from the gnome package `at-spi2-core` using upx built from  https://github.com/upx/upx/commit/f4c4d5148e4f8c9fc5bfd2c2e836ee2aa27fbaab

Either I get a can't pack error, or the binary is packed, but testing gives an error.

on x86_64:
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: /usr/local/tmp/crew/dest/usr/local/libexec/at-spi-bus-launcher-crewupxtmp: CantPackException: bad DT_{0x5} = 0xa000 (beyond EOF)
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: /usr/local/tmp/crew/dest/usr/local/libexec/at-spi2-registryd-crewupxtmp: CantPackException: bad DT_{0x5} = 0x1b000 (beyond EOF)
```

on armv7l:
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: /usr/local/tmp/crew/dest/usr/local/libexec/at-spi2-registryd-crewupxtmp: CantPackException: too many ElfXX_Phdr; try '--force-execve'

Packed 0 files.
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
     34589 ->     12492   36.12%    linux/arm    at-spi-bus-launcher-crewupxtmp

Packed 1 file.
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

upx: /usr/local/tmp/crew/dest/usr/local/libexec/at-spi-bus-launcher-crewupxtmp: CantUnpackException: header corrupted 4

```
on i686:
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: /usr/local/tmp/crew/dest/usr/local/libexec/at-spi2-registryd-crewupxtmp: CantPackException: too many ElfXX_Phdr; try '--force-execve'

Packed 0 files.
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
     38677 ->     13240   34.23%   linux/i386    at-spi-bus-launcher-crewupxtmp

Packed 1 file.
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

upx: /usr/local/tmp/crew/dest/usr/local/libexec/at-spi-bus-launcher-crewupxtmp: CantUnpackException: header corrupted 4
```

Binaries archives of these builds are at: 
     armv7l: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/at_spi2_core/2.47.90_armv7l/at_spi2_core-2.47.90-chromeos-armv7l.tar.zst',
       i686: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/at_spi2_core/2.47.90_i686/at_spi2_core-2.47.90-chromeos-i686.tar.zst',
     x86_64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/at_spi2_core/2.47.90_x86_64/at_spi2_core-2.47.90-chromeos-x86_64.tar.zst'

## What should have happened?

Successfully packed binaries should not fail testing.

## How can we reproduce the issue?

```


## Please tell us details about your environment.
<!--- Include as many relevant details about the environment you experienced the bug in -->
* UPX version used (`upx --version`):
```
upx --version
upx 4.0.3
UCL data compression library 1.03
zlib data compression library 1.2.13.1-motley
LZMA SDK version 4.43
doctest C++ testing framework version 2.4.9
Copyright (C) 1996-2023 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2023 Laszlo Molnar
Copyright (C) 2000-2023 John F. Reiser
Copyright (C) 2002-2023 Jens Medoch
Copyright (C) 1995-2022 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
Copyright (C) 2016-2021 Viktor Kirilov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```
* Host Operating System and version: ChromeOS
* Host CPU architecture:  i686, armv7l, x86_64
* Target Operating System and version:
* Target CPU architecture:

**Comment by markus-oberhumer** [comment]
Is this a regression?

Also, there are quite a number of files in https://github.com/upx/upx-testsuite-v2/tree/master/files/all that could be tested.

**Comment by satmandu** [comment]
The making of compressed binaries which fail `upx -t` is definitely a regression.

I should run the other tests during upx builds...

**Comment by jreiser** [comment]
No, it is NOT a regression. @satmandu has some very ugly executables.  For instance, applying /usr/bin/readelf to armv7l/at-spi2-registryd:
```
Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .gnu.hash         GNU_HASH        00001b14 001b14 000034 04   A 27   0  4
  [ 2] .hash             HASH            00001b48 001b48 0004f8 04   A 27   0  4
  [ 3] .gnu.version      VERSYM          00002040 002040 000172 02   A 27   0  2
  [ 4] .gnu.version_r    VERNEED         000021b4 0021b4 000060 00   A 28   3  4
  [ 5] .rel.dyn          REL             00002214 002214 0000f0 08   A 27   0  4
  [ 6] .rel.plt          REL             00002304 002304 000570 08  AI 27  21  4
  [ 7] .init             PROGBITS        00002874 002874 00000c 00  AX  0   0  4
  [ 8] .plt              PROGBITS        00002880 002880 00083c 00  AX  0   0  4
  [ 9] .text             PROGBITS        000030bc 0030bc 006594 00  AX  0   0  4
  [10] .fini             PROGBITS        00009650 009650 000008 00  AX  0   0  4
  [11] .rodata           PROGBITS        00009658 009658 003cf4 00   A  0   0  4
  [12] .ARM.extab        PROGBITS        0000d34c 00d34c 000000 00   A  0   0  1
  [13] .ARM.exidx        ARM_EXIDX       0000d34c 00d34c 000008 08  AL  9   0  4
  [14] .eh_frame         PROGBITS        0000d354 00d354 000004 00   A  0   0  4
  [15] .eh_frame_hdr     PROGBITS        0000d358 00d358 000008 00   A  0   0  4
  [16] .fini_array       FINI_ARRAY      0000eeb0 00deb0 000004 04  WA  0   0  4
  [17] .init_array       INIT_ARRAY      0000eeb4 00deb4 000004 04  WA  0   0  4
  [18] .dynamic          DYNAMIC         0000eeb8 00deb8 000148 08  WA 28   0  4
  [19] .data             PROGBITS        0000f000 00e000 0000e0 00  WA  0   0  4
  [20] .tm_clone_table   PROGBITS        0000f0e0 00e0e0 000000 00  WA  0   0  4
  [21] .got              PROGBITS        0000f0e0 00e0e0 0002f4 00  WA  0   0  4
  [22] .bss              NOBITS          0000f3d4 00e3d4 00008c 00  WA  0   0  4
  [23] .ARM.attributes   ARM_ATTRIBUTES  00000000 00e3d4 000035 00      0   0  1
  [24] .shstrtab         STRTAB          00000000 00e409 000102 00      0   0  1
  [25] .interp           PROGBITS        00010000 00f000 000019 00   A  0   0  4
  [26] .note.ABI-tag     NOTE            0001001c 00f01c 000020 00   A  0   0  4
  [27] .dynsym           DYNSYM          0001003c 00f03c 000b90 10   A 28   1  4
  [28] .dynstr           STRTAB          00017000 016000 000ea6 00   A  0   0  4

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  PHDR           0x000034 0x00000034 0x00000034 0x00220 0x00220 R   0x4
  LOAD           0x000000 0x00000000 0x00000000 0x0d360 0x0d360 R E 0x1000
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x10
  EXIDX          0x00d34c 0x0000d34c 0x0000d34c 0x00008 0x00008 R   0x4
  GNU_EH_FRAME   0x00d358 0x0000d358 0x0000d358 0x00008 0x00008 R   0x4
  LOAD           0x00deb0 0x0000eeb0 0x0000eeb0 0x00524 0x005b0 RW  0x1000
  GNU_RELRO      0x00deb0 0x0000eeb0 0x0000eeb0 0x00150 0x00150 RW  0x4
  DYNAMIC        0x00deb8 0x0000eeb8 0x0000eeb8 0x00148 0x00148 RW  0x4
  INTERP         0x00f000 0x00010000 0x00010000 0x00019 0x00019 R   0x1
      [Requesting program interpreter: /lib/ld-linux-armhf.so.3]
  LOAD           0x00f000 0x00010000 0x00010000 0x019bc 0x019bc RW  0x1000
  NOTE           0x00f01c 0x0001001c 0x0001001c 0x00020 0x00020 R   0x4
  LOAD           0x011000 0x00012000 0x00012000 0x00e10 0x00e10 RW  0x1000
  LOAD           0x012000 0x00013000 0x00013000 0x00e34 0x00e34 RW  0x1000
  LOAD           0x013000 0x00014000 0x00014000 0x00e54 0x00e54 RW  0x1000
  LOAD           0x014000 0x00015000 0x00015000 0x00e70 0x00e70 RW  0x1000
  LOAD           0x015000 0x00016000 0x00016000 0x00e8c 0x00e8c RW  0x1000
  LOAD           0x016000 0x00017000 0x00017000 0x00ea8 0x00ea8 RW  0x1000
```
Notice that there are 9 [PT_]LOAD segments, the last six of which are less than one page (0x1000), and with Write permission.  Some of them should be Read-Only, for instance .dynstr at offset 0x16000, VirtAddr 0x17000.  Also, there are 17 Elf32_Phdr, when the traditional limit is 14, so that Ehdr and Phdrs fit in 512 bytes.

@satmandu Which static linker and linker script produced this?

**Comment by satmandu** [comment]
I'm using @rui314's mold linker.

**Comment by satmandu** [comment]
Should I open an issue with the mold team?

**Comment by jreiser** [comment]
Yes, please open an issue with the mold team, unless you have specified your own linker script (often a file whose name ends in `.lds` .)  Run `/usr/bin/readelf --all /bin/date` and see what the usual memory layout looks like.

**Comment by satmandu** [comment]
Happy to pull out anything from the build if that will help track down where the breakage is happening. If this is a problem with what mold linker is doing, then I definitely want to request that it be addressed upstream.

**Comment by jreiser** [comment]
I can make the UPX limit on sizeof(_Ehdr + _Phdrs) be twice as big (1K on 32-bit, and 2K on 64-bit), and I wlll investigate the other problems.  But so far the mold linker definitely is part of the pain.  And it costs you speed speed and space at run time, as well as increased exposure to attack by malware. I can imagine some uses for such a layout, but not for "standard" execution.

**Comment by rui314** [comment]
@satmandu It looks like the sections are in a random order in the executable file. How did you create this executable? Did you pass some special option to force some section ordering?

**Comment by markus-oberhumer** [comment]
@jreiser Please do **not** start to add support for binaries that have unusual/strange headers!

Instead throw a nice throwCantPack("xxx not supported; take care") to give people a hint that this either might be some malware or they have to fix their linker (scripts).

**Comment by rui314** [comment]
As the creator of the mold linker, I can say that these executables are not what mold is expected to create. You guys don't have to support them.

**Comment by satmandu** [comment]
@rui314 Here is the build log:

[at_spi2_core-2.47.90-armv7l.log](https://github.com/upx/upx/files/10909569/at_spi2_core-2.47.90-armv7l.log)

This is using mold 1.10.0:
```
chronos@rpi4b-armv7l /usr/local/lib/crew/packages $ mold --version
mold 1.10.0 (compatible with GNU ld)
```

The build options (as per the build log) were:
```
meson setup -Dprefix=/usr/local -Dlibdir=/usr/local/lib -Dmandir=/usr/local/share/man -Dbuildtype=release -Db_lto=true -Dstrip=true -Db_pie=true -Dcpp_args='-O2 -pipe -ffat-lto-objects -fPIC -mfloat-abi=hard -mthumb -mfpu=vfpv3-d16 -march=armv7-a+fp -fuse-ld=mold ' -Dc_args='-O2 -pipe -ffat-lto-objects -fPIC -mfloat-abi=hard -mthumb -mfpu=vfpv3-d16 -march=armv7-a+fp -fuse-ld=mold ' \
    builddir
```

If we're doing something wrong during the build which causes mold to create something unexpected, I would really like to know what that is, so we can fix it!

**Comment by jreiser** [comment]
Here's the deal: UPX compresses executables, so UPX tries to get all its information from `Elfxx_Phdr` (the execution view, which is the only pieces that the operating system guarantees to be in memory at execution, and which includes the `PT_DYNAMIC` segment with many DT_xxxxx entries), and none from `Elfxx_Shdr` (the linking view: the Sections)  However, there is no DT_xxxxx which gives the length of `DT_SYMTAB`, `DT_HASH`, or `DT_GNU_HASH`. UPX must access these tables in order to check for symbol names such as `main`, `__libc_start_main`, `__uClibc_main`, `__uClibc_start_main`, `JNI_OnLoad`, and possibly others.  In order to access these tables safely, UPX must know their bounds.  (Yes, there have been malware attacks [fuzzers] which cause SIGSEGV or corruption by tricking UPX into accessing beyond one of these tables.  And the `gold` linker takes liberties with the `DT_GNU_HASH` table by omitting trailing zero entries that should be there [correct execution never will touch them], etc.)

So, UPX used to look at the layout that is produced by the recipes used by `/usr/bin/ld` from the `binutils` package, and determine that one table ends whenever "the next" table begins.  But then the order of the tables changed, so UPX gathers all the starting offsets of the various tables, sorts the list, and says that a table ends at the following start offset.  This works well as long as the tables are contiguous, which is expected because it saves space and cache misses at run time. But **satmandu**'s  executables put tables at apparently random offsets, interspersed with bytes from other sources (or even into separate `PT_LOAD` with padding zero bytes until a page boundary), so looking at the next offset in the sorted list of start offsets gives an inaccurate answer, often a large over-estimate.

So, I will "back off" and not be so aggressive when UPX detects an unusual layout.  Probably this will allow an occasional SIGSEGV at compress time, and perhaps even a rare corrupted output.

**Comment by satmandu** [comment]
Thank you @jreiser . @rui314 Happy to take this discussion to an issue on the mold GitHub, since we now know what to look for in mold output?

(But also happy to leave it here if that is easier to get the issue resolved.)

Also happy to contribute a docker reproducer for the build process. (Fastest on a machine that supports aarch64 And armv7l, like a RPI4B...)

**Comment by satmandu** [comment]
Here is a reproducer.

This is the docker build env script we use for `armv7l`. Feel free to modify or cut down as you feel comfortable.
```
#!/bin/bash
if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
  SESSION_TYPE=remote/ssh
elif pstree -p | egrep --quiet --extended-regexp ".*sshd.*\($$\)"; then
  SESSION_TYPE=remote/ssh
else
  case $(ps -o comm= -p $PPID) in
    sshd|*/sshd) SESSION_TYPE=remote/ssh;;
  esac
fi
X11=-e
X11+=" "
X11+=DISPLAY=${DISPLAY:-:0.0}
X11+=" "
if ! [[ $SESSION_TYPE == remote/ssh ]] && [ -d /tmp/.X11-unix ]; then
  X11+=" -v /tmp/.X11-unix:/tmp/.X11-unix "
fi
if [ -f "$HOME"/.Xauthority ]; then
  X11+=--volume=$HOME/.Xauthority:/home/chronos/user/.Xauthority:rw
  X11+=" "
  X11+=--volume=$HOME/.Xauthority:/home/chronos/.Xauthority:rw
fi
docker pull --platform linux/arm/v7 satmandu/crewbuild:fievel-armv7l.m91
docker pull tonistiigi/binfmt
docker run --privileged --rm tonistiigi/binfmt --install all
docker run --platform linux/arm/v7 --rm --net=host ${X11}  -v $(pwd)/pkg_cache:/usr/local/tmp/packages -v $(pwd):/output -h $(hostname)-armv7l -it satmandu/crewbuild:fievel-armv7l.m91
```

Once the build env container starts, one can do this:
```
cd /usr/local/tmp
crew build -k at_spi2_core
```
The build will be created (and saved) in `/usr/local/tmp/crew/` and files can be copied in and out from the dir where the script was invoked (which appears in the container as the `/output` directory.)

You will find `readelf` and `llvm-readelf` in the path inside the container.

**Comment by satmandu** [comment]
I'm also noticing that this is an issue with the x86_64 version of this binary build:

Looking at ` readelf --all /usr/local/libexec/at-spi2-registryd`:

```
  Program Headers:
    Type           Offset             VirtAddr           PhysAddr
                   FileSiz            MemSiz              Flags  Align
    PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                   0x0000000000000380 0x0000000000000380  R      0x8
    LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                   0x0000000000011918 0x0000000000011918  R E    0x1000
    GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                   0x0000000000000000 0x0000000000000000  RW     0x10
    GNU_EH_FRAME   0x000000000001168c 0x000000000001168c 0x000000000001168c
                   0x000000000000028c 0x000000000000028c  R      0x4
    LOAD           0x0000000000011d18 0x0000000000012d18 0x0000000000012d18
                   0x0000000000000a38 0x0000000000000b90  RW     0x1000
    GNU_RELRO      0x0000000000011d18 0x0000000000012d18 0x0000000000012d18
                   0x00000000000002e8 0x00000000000002e8  RW     0x8
    DYNAMIC        0x0000000000011d28 0x0000000000012d28 0x0000000000012d28
                   0x0000000000000280 0x0000000000000280  RW     0x8
    INTERP         0x0000000000013000 0x0000000000014000 0x0000000000014000
                   0x000000000000001c 0x000000000000001c  R      0x1
        [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
    LOAD           0x0000000000013000 0x0000000000014000 0x0000000000014000
                   0x0000000000001f28 0x0000000000001f28  RW     0x1000
    NOTE           0x0000000000013020 0x0000000000014020 0x0000000000014020
                   0x0000000000000020 0x0000000000000020  R      0x4
    LOAD           0x0000000000015000 0x0000000000016000 0x0000000000016000
                   0x0000000000000df8 0x0000000000000df8  RW     0x1000
    LOAD           0x0000000000016000 0x0000000000017000 0x0000000000017000
                   0x0000000000000e20 0x0000000000000e20  RW     0x1000
    LOAD           0x0000000000017000 0x0000000000018000 0x0000000000018000
                   0x0000000000000e40 0x0000000000000e40  RW     0x1000
    LOAD           0x0000000000018000 0x0000000000019000 0x0000000000019000
                   0x0000000000000e60 0x0000000000000e60  RW     0x1000
    LOAD           0x0000000000019000 0x000000000001a000 0x000000000001a000
                   0x0000000000000e80 0x0000000000000e80  RW     0x1000
    LOAD           0x000000000001a000 0x000000000001b000 0x000000000001b000
                   0x0000000000000e98 0x0000000000000e98  RW     0x1000
```

(Verifying now that this does not happen if I use gold linker.)

**Comment by satmandu** [comment]
Rebuilding with gold linker seems to not create a binary with all the LOAD headers:
```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x00000000000001f8 0x00000000000001f8  R      0x8
  INTERP         0x0000000000000238 0x0000000000000238 0x0000000000000238
                 0x000000000000001c 0x000000000000001c  R      0x1
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000011918 0x0000000000011918  R E    0x1000
  LOAD           0x0000000000011d18 0x0000000000012d18 0x0000000000012d18
                 0x0000000000000a38 0x0000000000000b90  RW     0x1000
  DYNAMIC        0x0000000000011d28 0x0000000000012d28 0x0000000000012d28
                 0x0000000000000280 0x0000000000000280  RW     0x8
  NOTE           0x0000000000000254 0x0000000000000254 0x0000000000000254
                 0x0000000000000020 0x0000000000000020  R      0x4
  GNU_EH_FRAME   0x000000000001168c 0x000000000001168c 0x000000000001168c
                 0x000000000000028c 0x000000000000028c  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x0000000000011d18 0x0000000000012d18 0x0000000000012d18
                 0x00000000000002e8 0x00000000000002e8  RW     0x8
```
Though I do still get a upx packing error:
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023   
UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

        File size         Ratio      Format      Name 
   --------------------   ------   -----------   -----------
upx: /usr/local/tmp/crew/dest/usr/local/libexec/at-spi2-registryd-crewupxtmp: CantPackException: bad DT_{0x5} = 0x1b000 (beyond EOF)
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023   
```

@rui314 I will open an issue on the mold repo for this issue.

@jreiser Do you want the binaries generated by using gold linker for the `CantPackException: bad DT_{0x5} = 0x1b000 (beyond EOF)` upx complaint?

**Comment by satmandu** [comment]
Also can confirm that there are fewer LOAD segments in the gold linker armv7l build:
```
Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  PHDR           0x000034 0x00000034 0x00000034 0x00140 0x00140 R   0x4
  INTERP         0x000174 0x00000174 0x00000174 0x00019 0x00019 R   0x1
      [Requesting program interpreter: /lib/ld-linux-armhf.so.3]
  LOAD           0x000000 0x00000000 0x00000000 0x0d360 0x0d360 R E 0x1000
  LOAD           0x00deb0 0x0000eeb0 0x0000eeb0 0x00524 0x005b0 RW  0x1000
  DYNAMIC        0x00deb8 0x0000eeb8 0x0000eeb8 0x00148 0x00148 RW  0x4
  NOTE           0x000190 0x00000190 0x00000190 0x00020 0x00020 R   0x4
  GNU_EH_FRAME   0x00d358 0x0000d358 0x0000d358 0x00008 0x00008 R   0x4
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x10
  EXIDX          0x00d34c 0x0000d34c 0x0000d34c 0x00008 0x00008 R   0x4
  GNU_RELRO      0x00deb0 0x0000eeb0 0x0000eeb0 0x00150 0x00150 RW  0x4
```
I do get a upx complaint with that binary too:
```
Attempting to compress /usr/local/tmp/crew/dest/usr/local/libexec/at-spi2-registryd ...
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023 
UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: /usr/local/tmp/crew/dest/usr/local/libexec/at-spi2-registryd-crewupxtmp: CantPackException: too many ElfXX_Phdr; try '--force-execve'

Packed 0 files.
```

**Comment by jreiser** [comment]
@satmandu Yes please, I would like a copy of the binary produced by the `gold` linker where upx complains `CantPackException: bad DT_{0x5} = 0x1b000 (beyond EOF)`.

And if the binary produced by `gold` on armv7l still draws the complaint "too may ElfXX_Phdr" then I would like a copy of that binary, too.

**Comment by satmandu** [comment]
The i686 gold linker build output also gives these errors when attempting to compress with upx:
```
Attempting to compress /usr/local/tmp/crew/dest/usr/local/libexec/at-spi-bus-launcher ...
Attempting to compress /usr/local/tmp/crew/dest/usr/local/libexec/at-spi2-registryd ...
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: /usr/local/tmp/crew/dest/usr/local/libexec/at-spi2-registryd-crewupxtmp: CantPackException: too many ElfXX_Phdr; try '--force-execve'

Packed 0 files.
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
     38677 ->     13240   34.23%   linux/i386    at-spi-bus-launcher-crewupxtmp

Packed 1 file.
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

upx: /usr/local/tmp/crew/dest/usr/local/libexec/at-spi-bus-launcher-crewupxtmp: CantUnpackException: header corrupted 4

Tested 0 files.
```

Here are the relevant binary packages built with gold linker which have those binaries:

  binary_url({
     armv7l: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/at_spi2_core/2.47.90-1_armv7l/at_spi2_core-2.47.90-1-chromeos-armv7l.tar.zst',
       i686: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/at_spi2_core/2.47.90-1_i686/at_spi2_core-2.47.90-1-chromeos-i686.tar.zst',
     x86_64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/at_spi2_core/2.47.90-1_x86_64/at_spi2_core-2.47.90-1-chromeos-x86_64.tar.zst'
  })
  binary_sha256({
     armv7l: '1e314e567f78876737ca8edcb01a6d337abd3bc2d313b457a34cc05b9597cc5a',
       i686: '4f1e8c5e96d437c8cc9bea10ee8529ab70b72fc9f4b382eec9c9a1e28ed751cf',
     x86_64: '00ca30e7f09d1724adeda7ea5b38e83fe3519da4c724916be629297f8da64eaf'
  })

**Comment by jreiser** [comment]
@satmandu Those are not the versions produced by `gold`.  They still have multiple LOAD at the end.  For example on x86_64/.../at-spi2-registryd:
```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
   [[snip]]
 INTERP         0x0000000000013000 0x0000000000014000 0x0000000000014000
                 0x000000000000001c 0x000000000000001c  R      0x1
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
  LOAD           0x0000000000013000 0x0000000000014000 0x0000000000014000
                 0x0000000000001f28 0x0000000000001f28  RW     0x1000
  NOTE           0x0000000000013020 0x0000000000014020 0x0000000000014020
                 0x0000000000000020 0x0000000000000020  R      0x4
  LOAD           0x0000000000015000 0x0000000000016000 0x0000000000016000
                 0x0000000000000df8 0x0000000000000df8  RW     0x1000
  LOAD           0x0000000000016000 0x0000000000017000 0x0000000000017000
                 0x0000000000000e20 0x0000000000000e20  RW     0x1000
  LOAD           0x0000000000017000 0x0000000000018000 0x0000000000018000
                 0x0000000000000e40 0x0000000000000e40  RW     0x1000
  LOAD           0x0000000000018000 0x0000000000019000 0x0000000000019000
                 0x0000000000000e60 0x0000000000000e60  RW     0x1000
  LOAD           0x0000000000019000 0x000000000001a000 0x000000000001a000
                 0x0000000000000e80 0x0000000000000e80  RW     0x1000
  LOAD           0x000000000001a000 0x000000000001b000 0x000000000001b000
                 0x0000000000000e98 0x0000000000000e98  RW     0x1000
```

**Comment by satmandu** [comment]
> @satmandu Those are not the versions produced by `gold`.  They still have multiple LOAD at the end.  For example on x86_64/.../at-spi2-registryd:
> ```
> Program Headers:
>   Type           Offset             VirtAddr           PhysAddr
>                  FileSiz            MemSiz              Flags  Align
>    [[snip]]
>  INTERP         0x0000000000013000 0x0000000000014000 0x0000000000014000
>                  0x000000000000001c 0x000000000000001c  R      0x1
>       [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
>   LOAD           0x0000000000013000 0x0000000000014000 0x0000000000014000
>                  0x0000000000001f28 0x0000000000001f28  RW     0x1000
>   NOTE           0x0000000000013020 0x0000000000014020 0x0000000000014020
>                  0x0000000000000020 0x0000000000000020  R      0x4
>   LOAD           0x0000000000015000 0x0000000000016000 0x0000000000016000
>                  0x0000000000000df8 0x0000000000000df8  RW     0x1000
>   LOAD           0x0000000000016000 0x0000000000017000 0x0000000000017000
>                  0x0000000000000e20 0x0000000000000e20  RW     0x1000
>   LOAD           0x0000000000017000 0x0000000000018000 0x0000000000018000
>                  0x0000000000000e40 0x0000000000000e40  RW     0x1000
>   LOAD           0x0000000000018000 0x0000000000019000 0x0000000000019000
>                  0x0000000000000e60 0x0000000000000e60  RW     0x1000
>   LOAD           0x0000000000019000 0x000000000001a000 0x000000000001a000
>                  0x0000000000000e80 0x0000000000000e80  RW     0x1000
>   LOAD           0x000000000001a000 0x000000000001b000 0x000000000001b000
>                  0x0000000000000e98 0x0000000000000e98  RW     0x1000
> ```

Taking a look...

**Comment by satmandu** [comment]
Mea culpa to @rui314 . This isn't mold's fault. It is patchelf's. I added patchelf to our build process some time ago to account for the possibility of changing our install location. It appears that this utterly borks the binaries as @jreiser noted. 

This is the output from mold's binary generation, before patchelf touches it:
```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x00000000000001f8 0x00000000000001f8  R      0x8
  INTERP         0x0000000000000238 0x0000000000000238 0x0000000000000238
                 0x000000000000001c 0x000000000000001c  R      0x1
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000011918 0x0000000000011918  R E    0x1000
  LOAD           0x0000000000011d18 0x0000000000012d18 0x0000000000012d18
                 0x0000000000000a38 0x0000000000000b90  RW     0x1000
  DYNAMIC        0x0000000000011d28 0x0000000000012d28 0x0000000000012d28
                 0x0000000000000280 0x0000000000000280  RW     0x8
  NOTE           0x0000000000000254 0x0000000000000254 0x0000000000000254
                 0x0000000000000020 0x0000000000000020  R      0x4
  GNU_EH_FRAME   0x000000000001168c 0x000000000001168c 0x000000000001168c
                 0x000000000000028c 0x000000000000028c  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x0000000000011d18 0x0000000000012d18 0x0000000000012d18
                 0x00000000000002e8 0x00000000000002e8  RW     0x8
```
And yes, the binary generated here is compressed by `upx` just fine.

**Comment by satmandu** [comment]
As it's clear that patchelf is at fault here, I'm going to open an issue upstream with THEM... so perhaps there's not much sense in debugging this here further, with the caveat that since NixOS heavily uses patchelf, you may see issues when people try to use `upx` on binaries generated in that OS...

**Comment by markus-oberhumer** [comment]
Thanks for debugging this.

@jreiser Can we add a simple check and just refuse to pack such binaries?

**Comment by jreiser** [comment]
@satmandu One "hack" that allows changing DT_RUNPATH (while avoiding the use of patchelf) , is for some early stage in the build process to add a place-holder definition  such as` -rpath=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx `which reserves space in the DT_STRTAB.  Then update later by over-writing that string.  The terminating '\0' byte in the update will end the RUN_PATH.  There probably will be some left-over garbage of "xxx...x" at the end, but that is a small price to pay.

**Comment by jreiser** [comment]
Another hack: /usr/bin/ld used to put an additional 3 or 4 empty (all-zero) ElfXX__Dyn entries at the end of the PT_DYNAMIC segment, for the purpose of allowing `/usr/bi/prelink`  to add some entries.  `prelink` seems to have fallen out-of-favor and not used often, but perhaps /usr/bin/ld still adds the extra entries.  So take one.  Remember to adjust the .filesz and .memsz of the Phdr, and the .sh_size of the _Shdr.
