### ISSUE TITLE
Win exe - Can these parts be further compressed?

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#656]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

Can empty space in windows executables be further compressed?
start of exe
![start](https://user-images.githubusercontent.com/16452453/224519245-092fc1c6-3913-4cfc-b37b-238fff5f30a0.png)
end of exe
![end](https://user-images.githubusercontent.com/16452453/224519253-cd7a6935-f4d4-48f8-91b3-c6b17bf4e859.PNG)
## What should have happened?

Compressing these parts will further reduce file size
## How can we reproduce the issue?

1. Compress any windows binary
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): latest actions build
* Host Operating System and version: win11
* Host CPU architecture: x64
* Target Operating System and version: win11
* Target CPU architecture: x64

**Comment by jreiser** [comment]
You must upload ("Attach files by ...") or give a URL to an actual PE .exe file, and then describe the regions which you suspect might be further compressed, naming  ranges of numerical byte offsets from the beginning of the file. Screenshots of some dump are not helpful, espcially when the dump tool was not specified, and the key for how to interpret the picture is missing.

**Comment by necros2k7** [comment]
2 screenshots above depict standard header start of windows executable file compressed by UPX and end part of executable file, which can be seen with any file viewer by hitting F3
