### ISSUE TITLE
Enhancement: Update LZMA SDK to latest revision

### ISSUE THREAD

**Issue by pwallner** [upx/upx#66]
## What's the problem (or question)?
no problem, enhancement

## What should have happened?
---

## Do you have an idea for a solution?
Update to latest lzma sdk

## How can we reproduce the issue?
---

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94 git
* Operating System and version: dm900
* CPU architecture: armv7l

**Comment by markus-oberhumer** [comment]
An upgrade would mean quite some work (and we need the current version for the runtime decompressors anyway), so unless you can provide any hard data (compression ratio, speed) to justify the efforts this won't happen.
