### ISSUE TITLE
CantPackException: need DT_INIT; try "void _init(void){}"

### ISSUE THREAD

**Issue by zmtong1988** [upx/upx#660]
## What's the problem (or question)?

The UPX compressed i386 shared library，and run packed so，error happend:

```C
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023

UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: winex11.drv.so: CantPackException: need DT_INIT; try "void _init(void){}"

Packed 0 files.
```

## What should have happened?

It should compress the  i386 shared library .

## Do you have an idea for a solution?

I looked at the "CantPackException: DT required_INIT; try" void _INIT (void) {} "error reason. Found upx_dt_ini_ in invert_pt_dynamic(), No other values have been assigned.

```c
void PackLinuxElf32::invert_pt_dynamic(Elf32_Dyn const *dynp, unsigned headway)
{
    if (dt_table[Elf32_Dyn::DT_NULL]) {
        return;  // not 1st time; do not change upx_dt_init
    }
    Elf32_Dyn const *const dynp0 = dynp;
    unsigned ndx = 0;
    unsigned const limit = headway / sizeof(*dynp);  if (dynp)
    for (; ; ++ndx, ++dynp) {
        if (limit <= ndx) {
            throwCantPack("DT_NULL not found");
        }
        unsigned const d_tag = get_te32(&dynp->d_tag);
        if (d_tag < DT_NUM) {
            if (Elf32_Dyn::DT_NEEDED != d_tag
            &&  dt_table[d_tag]
            &&    get_te32(&dynp->d_val)
               != get_te32(&dynp0[-1+ dt_table[d_tag]].d_val)) {
                char msg[50]; snprintf(msg, sizeof(msg),
                    "duplicate DT_%#x: [%#x] [%#x]",
                    d_tag, -1+ dt_table[d_tag], ndx);
                throwCantPack(msg);
            }
            dt_table[d_tag] = 1+ ndx;
        }
        if (Elf32_Dyn::DT_NULL == d_tag) {
            break;  // check here so that dt_table[DT_NULL] is set
        }
    }   
	upx_dt_init = 0;
         if (dt_table[Elf32_Dyn::DT_INIT])          upx_dt_init = Elf32_Dyn::DT_INIT;
    else if (dt_table[Elf32_Dyn::DT_PREINIT_ARRAY]) upx_dt_init = Elf32_Dyn::DT_PREINIT_ARRAY;
    else if (dt_table[Elf32_Dyn::DT_INIT_ARRAY])    upx_dt_init = Elf32_Dyn::DT_INIT_ARRAY;
 
    ......
}
    
```

#readelf -h winex11.drv.so

![0000](https://user-images.githubusercontent.com/22734355/225812932-2155da6a-0670-4c5d-8769-2f37774c006e.png)

Excuse me,  INIT, INIT_ARRAY, and INIT_ARRAYSZ of a shared binary are not regular addresses, but 0x60009992 (Operating System specific: 60009992), 0x60009990 (Operating System specific: 60009990), and 0x60009991 (Operating System specific: 60009991). How can I achieve file compression?

## How can we reproduce the issue?

1. upx -9 winex11.drv.so

2. Here is the shared binary.
  
   [winex11.drv.so.gz](https://github.com/upx/upx/files/10997879/winex11.drv.so.gz)

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.0.3 
* Host Operating System and version: debian11
* Host CPU architecture: x86_64
* Target Operating System and version: same
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
`How can I achieve file compression?`

0. Use the standard values for DT_INIT, DT_INIT_ARRAY, DT_INIT_ARRAYSZ.
1. Point to the file and the developer package that contains the #define for the OS-specific values that are used.
2. Point to the documentation, blog post, discussion thread, etc. that explains why the new values were implemented, the benefits, the costs, etc.
3. Use a binary file editor to overwrite the DT_XXXXX entries with the standard values, compress, use the binary editor to restore the new values.

**Comment by zmtong1988** [comment]
@jreiser 
Thank you very much for your answer.
I will study how to achieve it, but if I don't understand, I will seek advice. Thank you.

**Comment by zmtong1988** [comment]
@jreiser Thank you.
Can be compressed for use. 
Write a judgment modification program to confirm whether (INIT) exists. If it does not exist d_tag (0x60009992) is modified to the conventional value d_tag (0x0000000c), can use upx compression.

**Comment by zmtong1988** [comment]
@jreiser  
Hello, I have a question for you.

Recently, when I was practicing using UPX to compress the shared library files generated by Wine compilation, I encountered a problem. I want to ask for advice.

I use UPX to compress Wine to generate kernelbase.dll files. These files can be compressed, but they cannot be used.

When compiling Wine, I checked whether the ImageBase of the kernelbase.dll file is fixed at 0x7b000000.

I see that upx calls the VirtualProtect, ExitProcess, GetProcAddress, and LoadLibraryA of kernel32 for processing when compressing dll files.

Whether the kernelbase.dll and kernel32.dll files generated by Wine cannot be compressed. What if I want to compress?

Thank you.

**Comment by jreiser** [comment]
I found an ancient kernel32.dll.so from 2009 which had
```
Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x000000 0x7b800000 0x7b800000 0xbde58 0xbde58 R E 0x1000
  LOAD           0x0be000 0x7b8be000 0x7b8be000 0xbb09c 0xbc9e0 RW  0x1000
```
The LOAD.VirtAddr of 0x7b800000 was responsible for a SIGSEGV.  The commit above fixed it. I did not find any kernelbase.dll to try.

**Comment by zmtong1988** [comment]
@jreiser 
Thank you very much for your answer

I used UPX to test the shared library file as follows:

1. Wine compiled using MinGW
[mingw.zip](https://github.com/upx/upx/files/11143647/mingw.zip)

2. Wine is compiled using GCC( It will generate two types of dll files and dll.so files )
[gcc.zip](https://github.com/upx/upx/files/11143648/gcc.zip)
