### ISSUE TITLE
Feat. req. Add update app option / flag

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#661]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
Can update flag / option be implemented in UPX like in "yt-dlp -U" tool? 

## What should have happened?
Running upx -U (or another special) command should download and update current binary to latest Release/Actions build

## Do you have an idea for a solution?
Check update methods of other apps like "yt-dlp"

## How can we reproduce the issue?
-

## Please tell us details about your environment.

* UPX version used (`upx --version`): latest actions build
* Host Operating System and version: win11 
* Host CPU architecture: x64
* Target Operating System and version: win11 , win10
* Target CPU architecture: x64, x32

**Comment by markus-oberhumer** [comment]
No. You should only ever use stable **release versions**, and you can use a package manager like Chocolatey or Scoop (on Windows) or Brew (on macOS) if you do not want to download our official binaries.

See https://repology.org/project/upx/history for more options.
