### ISSUE TITLE
The problem with the packed gopnik2 game

### ISSUE THREAD

**Issue by bolknote** [upx/upx#662]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

Segmentation fault: 11

## What should have happened?

The game starts

## How can we reproduce the issue?

1. clone https://github.com/bolknote/gopnik2
2. make
3. upx -9 gop2
4. ./gop2

## Please tell us details about your environment.

* UPX version used (`upx --version`):
upx 4.0.2
UCL data compression library 1.03
zlib data compression library 1.2.13.1-motley
LZMA SDK version 4.43
doctest C++ testing framework version 2.4.9

* Host Operating System and version: Darwin 22.4.0 Darwin Kernel Version 22.4.0 (MacOS 13.3)
* Host CPU architecture: Intel x86
* Target Operating System and version: MacOS
* Target CPU architecture: Intel x86

**Comment by jreiser** [comment]
Same as #612.  Also, see https://github.com/upx/upx/issues/612#issuecomment-1489960577 for how to provide more helpful information.

**Comment by bolknote** [comment]
```
lldb ./gop2
(lldb) target create "./gop2"
Current executable set to '/Users/bolk/Downloads/gop2_linux/gop2' (x86_64).
(lldb) run
Process 58214 launched: '/Users/bolk/Downloads/gop2_linux/gop2' (x86_64)
Process 58214 stopped
* thread #1, stop reason = EXC_BAD_ACCESS (code=1, address=0x7ff7bff07464)
    frame #0: 0x000000010002846f
->  0x10002846f: cmpl   $0x19, (%rsi)
    0x100028472: jne    0x1000284bd
    0x100028474: movq   0x20(%rsi), %r8
    0x100028478: testq  %r8, %r8
Target 0: (gop2) stopped.
(lldb)

**Comment by bolknote** [comment]
Looks like another problem.

**Comment by jreiser** [comment]
Works for me using tip of branch `devel4`.  Builds are available under Artifacts on the Actions page https://github.com/upx/upx/actions/runs/4558834955.
