### ISSUE TITLE
UnknownExecutableFormatException

### ISSUE THREAD

**Issue by 00032118** [upx/upx#666]
Hello, is this SEC way of defining segments not supported?Is there any way to solve it besides modifying the code?

[root@cloud xdp]#  clang -O2 -Wall -target bpf -c xdp_example.c -o xdp_example.o
[root@cloud xdp]# ls -al
total 400
drwxr-xr-x 2 root root     64 Apr 11 08:25 .
drwxr-xr-x 3 root root    182 Apr 11 08:14 ..
-rw-r--r-- 1 root root    288 Apr 11 02:45 test.txt
-rw-r--r-- 1 root root    360 Apr 11 08:25 xdp_example.c
-rw-r--r-- 1 root root 400816 Apr 11 08:25 xdp_example.o
[root@cloud xdp]# cd ..
[root@cloud upx-4.0.2-amd64_linux]# ls
COPYING  LICENSE  NEWS  README  readme.txt  test.o  THANKS  upx  upx.1  upx-doc.html  upx-doc.txt  xdp
[root@cloud upx-4.0.2-amd64_linux]# ./upx ./xdp/xdp_example.o
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.2       Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 30th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: ./xdp/xdp_example.o: UnknownExecutableFormatException

Packed 0 files.

[root@cloud xdp]# more xdp_example.c
#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

#ifndef __section
# define __section(NAME)                  \
   __attribute__((section(NAME), used))
#endif

int const ttt[100000] = {1,2,3};

__section("prog")
int xdp_pass(struct xdp_md *ctx)
{
    return XDP_PASS;  /*XDP_PASS*/
}

char __license[] __section("license") = "GPL";

**Comment by ml1050** [comment]
Object files  (.o) are not supported by UPX. They are not executable.

**Comment by 00032118** [comment]
> UPX 不支持对象文件 (.o)。它们不可执行。

Thank you very much for your prompt reply and I wish you all the best.
