### ISSUE TITLE
GraalVM native image crashes when compressed with UPX

### ISSUE THREAD

**Issue by BullyWiiPlaza** [upx/upx#670]
## What's the problem (or question)?
I compiled a Spring REST API Java program to a native EXE using GraalVM. When I run the EXE, it works fine. After compressing the EXE, it fails to run:

```
D:\Moved\demo\target>upx -9 demo.exe -o demo-compressed.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.2       Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 30th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
 149934080 ->  47769600   31.86%    win64/pe     demo-compressed.exe                                                                                                                                                                            Packed 1 file.

D:\Moved\demo\target>demo-compressed.exe

D:\Moved\demo\target>echo %ERRORLEVEL%
193
```

## What should have happened?
The EXE starts up normally.

## Do you have an idea for a solution?
No, maybe looking into what UPX does wrong or if the EXE format is unexpected or the EXE is bigger than expected.

## How can we reproduce the issue?
1. Download my `demo.exe` package: https://mega.nz/file/ioMRxQQZ#SGpa4Vqswz1fiYpiqDRRtPId_Qu46uV5T_H4vGZuQTI
2. Unpack it, verify it runs by starting the `demo.exe`
3. Compress the `demo.exe` via `upx -9 demo.exe -o demo-compressed.exe`
4. Run the `demo-compressed.exe`
5. It fails to run, the bug has been reproduced successfully

## Please tell us details about your environment.
* UPX version used (`upx --version`): [4.0.2 (latest)](https://github.com/upx/upx/releases/tag/v4.0.2)
* Host Operating System and version: Windows 11 Pro
* Host CPU architecture: AMD64
* Target Operating System and version: Windows 11 Pro
* Target CPU architecture: AMD64

**Comment by vicasong** [comment]
I'm having the same issue with upx v4.1.0

**Comment by markus-oberhumer** [comment]
Could you please try if any older UPX version happens to work?

**Comment by BullyWiiPlaza** [comment]
@markus-oberhumer 
Yes, I tried older/other UPX versions just now. The results are below.

`upx-4.1.0`:
Packing succeeds but the packed EXE fails to run.
```
>demo-compressed-4.1.0.exe
>echo %ERRORLEVEL%
193
```

Note: The error level 193 means `ERROR_BAD_EXE_FORMAT` on Windows. This implies that something is wrong with how UPX built the packed EXE.

`upx-3.96`:
Packing succeeds but the packed EXE fails to run.
```
>demo-compressed-3.96.exe
>echo %ERRORLEVEL%
193
```

`upx-3.95`:
Packing fails. It looks like this bug was fixed in later versions.
```
>upx-3.95-win64\upx -9 demo.exe -o demo-compressed-3.95.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95w       Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: demo.exe: CantPackException: size of Load Configuration directory unexpected

Packed 1 file: 0 ok, 1 error.
```
I didn't try even older versions since most likely they won't even be able to pack successfully. It seems like this never worked before.

**Comment by markus-oberhumer** [comment]
I've just realized that  demo.exe does work for me if you use one of the compression levels -1, -2, -3 or -4, e.g.

```
upx-4.1.0 demo.exe -o test_4.exe -4
```


BTW, how is this demo.exe created / linked? It seems to have an uncommon Load Configuration size.

**Comment by BullyWiiPlaza** [comment]
> I've just realized that demo.exe does work for me if you use one of the compression levels -1, -2, -3 or -4, e.g.
> 
> ```
> upx-4.1.0 demo.exe -o test_4.exe -4
> ```
> 
> BTW, how is this demo.exe created / linked? It seems to have an uncommon Load Configuration size.

Hi, great finding! I can confirm that with `-4` compression it works but starting from `-5` it fails.

The EXE is compiled/linked using the `native-image` utility provided by GraalVM, for more information check out this Medium post: https://medium.com/graalvm/using-graalvm-and-native-image-on-windows-10-9954dc071311

In short, `native-image` can turn a Java JAR program which contains compiled Java classes etc. into a real native EXE using the Visual Studio C++ toolchain (MSVC compiler). The created native EXE can then be ran on any PC without an existing Java VM. That does increase the file size though but startup times are also much lower than when running the code on a Java VM.

**Comment by markus-oberhumer** [comment]
It seems the source code is at https://github.com/oracle/graal

Next step is to figure out how they actually call the linker and if they do something unexpected.

**Comment by markus-oberhumer** [comment]
Some more initial testing/debugging logs.

x5.exe works, but x6.exe does not.

```diff
$ git diff

diff --git a/src/pefile.cpp b/src/pefile.cpp
index 1e0b9382..b2747d4f 100644
--- a/src/pefile.cpp
+++ b/src/pefile.cpp
@@ -2561,7 +2561,7 @@ void PeFile::pack0(OutputFile *fo, ht &ih, ht &oh, unsigned subsystem_mask,
             fo->write(ibuf, oh.filealign - ic);
     }

-#if 0
+#if 1
     printf("%-13s: program hdr  : %8d bytes\n", getName(), (int) sizeof(oh));
     printf("%-13s: sections     : %8d bytes\n", getName(), (int) sizeof(osection[0]) * oobjs);
     printf("%-13s: ident        : %8d bytes\n", getName(), (int) identsize);
```

```
./build/release/upx demo.exe --prefer-ucl -5 -o x5.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX git-2a491f  Markus Oberhumer, Laszlo Molnar & John Reiser    Oct 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
win64/pe     : program hdr  :      264 bytes
win64/pe     : sections     :      120 bytes
win64/pe     : ident        :       37 bytes
win64/pe     : compressed   : 58561264 bytes
win64/pe     : decompressor :      557 bytes
win64/pe     : tls          :        0 bytes
win64/pe     : aligned_tls  :        0 bytes
win64/pe     : resources    :        0 bytes
win64/pe     : imports      :     1712 bytes
win64/pe     : exports      :        0 bytes
win64/pe     : relocs       :       28 bytes
win64/pe     : loadconf     :      320 bytes
 149934080 ->  58565632   39.06%    win64/pe     x5.exe

Packed 1 file
```

```
./build/release/upx demo.exe --prefer-ucl -6 -o x6.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX git-2a491f  Markus Oberhumer, Laszlo Molnar & John Reiser    Oct 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
win64/pe     : program hdr  :      264 bytes
win64/pe     : sections     :      120 bytes
win64/pe     : ident        :       37 bytes
win64/pe     : compressed   : 58027008 bytes
win64/pe     : decompressor :      557 bytes
win64/pe     : tls          :        0 bytes
win64/pe     : aligned_tls  :        0 bytes
win64/pe     : resources    :        0 bytes
win64/pe     : imports      :     1712 bytes
win64/pe     : exports      :        0 bytes
win64/pe     : relocs       :       28 bytes
win64/pe     : loadconf     :      320 bytes
 149934080 ->  58031104   38.70%    win64/pe     x6.exe

Packed 1 file.
```

**Comment by markus-oberhumer** [comment]
@BullyWiiPlaza Can you find out how **your** demo.exe is getting linked (e.g. by enabling some log/debug options)?

**Comment by BullyWiiPlaza** [comment]
> @BullyWiiPlaza Can you find out how **your** demo.exe is getting linked (e.g. by enabling some log/debug options)?

Hi, unfortunately, I was unable to find a straight answer to this myself, also enabling debugging logs didn't really help in that regard either. I created an issue on the GraalVM project to clarify how exactly the EXE is linked: https://github.com/oracle/graal/issues/7605

**Comment by markus-oberhumer** [comment]
Feedback from https://github.com/oracle/graal/issues/7605 : look at class `WindowsCCLinkerInvocation`

Graal source file is `substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/CCLinkerInvocation.java`

Nothing unusual here except maybe `/FILEALIGN:4096`

**Comment by markus-oberhumer** [comment]
I did some debugging with `x64dbg` under Wine, but nothing unusual - the program simply exits with exit code 193.

```
INT3 breakpoint at <ntdll.RtlExitUserProcess> ([00006FFFFFF839C0](x64dbg://localhost/address64#00006FFFFFF839C0))!
Process stopped with exit code 0xC1 (193)
```

Setting a breakpoint at ` RtlExitUserProcess`  produces this backtrace:

![Screenshot_2023-10-25_09-52-20](https://github.com/upx/upx/assets/2130496/5bbf72be-ba1f-4553-bd69-f183d5f85633)

Someone else will have to figure out what is going on. HELP WANTED.

**Comment by markus-oberhumer** [comment]
Update: found ERROR_BAD_EXE_FORMAT

See https://github.com/oracle/graal/issues/7605#issuecomment-1779642637

**Comment by markus-oberhumer** [comment]
Also see this comment https://github.com/upx/upx/issues/559#issuecomment-1032047038 from @kornelpal

**Comment by markus-oberhumer** [comment]
This might be a GraalVM bug introduced in Graal version 22, see https://github.com/oracle/graal/issues/4340

**Comment by markus-oberhumer** [comment]
The UPX team believes this is a GraalVM bug introduced in Graal version 22, so closing.

See https://github.com/oracle/graal/issues/4340

EDIT 1: also see related UPX bug report #559

EDIT 2: also see https://github.com/oracle/graal/issues/7605

**Comment by markus-oberhumer** [comment]
Update: https://github.com/oracle/graal/issues/4340 has been closed, so the problem might be fixed in the latest GraalVM version.

Please retest your binaries and confirm at https://github.com/oracle/graal/issues/4340 (or open a new GraalVM issue).

**Comment by su-404** [comment]
> ## What's the problem (or question)?
> I compiled a Spring REST API Java program to a native EXE using GraalVM. When I run the EXE, it works fine. After compressing the EXE, it fails to run:
> 
> ```
> D:\Moved\demo\target>upx -9 demo.exe -o demo-compressed.exe
>                        Ultimate Packer for eXecutables
>                           Copyright (C) 1996 - 2023
> UPX 4.0.2       Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 30th 2023
> 
>         File size         Ratio      Format      Name
>    --------------------   ------   -----------   -----------
>  149934080 ->  47769600   31.86%    win64/pe     demo-compressed.exe                                                                                                                                                                            Packed 1 file.
> 
> D:\Moved\demo\target>demo-compressed.exe
> 
> D:\Moved\demo\target>echo %ERRORLEVEL%
> 193
> ```
> 
> ## What should have happened?
> The EXE starts up normally.
> 
> ## Do you have an idea for a solution?
> No, maybe looking into what UPX does wrong or if the EXE format is unexpected or the EXE is bigger than expected.
> 
> ## How can we reproduce the issue?
> 1. Download my `demo.exe` package: https://mega.nz/file/ioMRxQQZ#SGpa4Vqswz1fiYpiqDRRtPId_Qu46uV5T_H4vGZuQTI
> 2. Unpack it, verify it runs by starting the `demo.exe`
> 3. Compress the `demo.exe` via `upx -9 demo.exe -o demo-compressed.exe`
> 4. Run the `demo-compressed.exe`
> 5. It fails to run, the bug has been reproduced successfully
> 
> ## Please tell us details about your environment.
> * UPX version used (`upx --version`): [4.0.2 (latest)](https://github.com/upx/upx/releases/tag/v4.0.2)
> * Host Operating System and version: Windows 11 Pro
> * Host CPU architecture: AMD64
> * Target Operating System and version: Windows 11 Pro
> * Target CPU architecture: AMD64

Hello, pls what is the graalvm version you are using？

**Comment by BullyWiiPlaza** [comment]
> Hello, pls what is the graalvm version you are using？

Hello, this issue was closed but to answer your question, I mentioned the GraalVM version I used in the following comment: https://github.com/oracle/graal/issues/4340#issuecomment-1913611746

**Comment by sergeevabc** [comment]
Source: [crip_v241_20250510.zip](https://github.com/user-attachments/files/20142713/crip_v241_20250510.zip)

It was compiled from [JAR ](https://github.com/Hakky54/certificate-ripper/releases/download/2.4.1/crip-fat-jar.tar.gz) using GraalVM 17 on Windows 7 x64.

``` console
$ native-image --no-fallback -march=compatibility -Ob --enable-http --enable-https -jar crip.jar
(success)

$ crip_v241_20250510.exe --version
Certificate Ripper v2.4.1

$ upx --version
upx 5.0.1

$ upx crip_v241_20250510.exe
Compressing crip_v241_20250510.exe [win64/pe, NRV2E/7]

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  27725824 ->   9499136   34.26%    win64/pe     crip_v241_20250510.exe

$ crip_v241_20250510.exe --version
(nothing)

```

**Comment by kornelpal** [comment]
The old workaround from https://github.com/upx/upx/issues/559#issuecomment-1032047038 does not work with newer GraalVM versions as described in https://github.com/oracle/graal/issues/4340#issuecomment-1290881544.

I came up with another workaround; instead of removing a file from `svm.jar`, a new one can be added to force `CopyingImageHeapProvider` to be used:
- Download [ForcedCopyingImageHeapProviderFeature.zip](https://github.com/user-attachments/files/20146348/ForcedCopyingImageHeapProviderFeature.zip)
- Extract `ForcedCopyingImageHeapProviderFeature.class` from `ForcedCopyingImageHeapProviderFeature.zip`
    - Source code is also included, but only the compiled class file is needed.
- Inject `ForcedCopyingImageHeapProviderFeature.class` to `lib/svm/builder/svm.jar` of GraalVM using path `com/oracle/svm/core/os/ForcedCopyingImageHeapProviderFeature.class` inside of `svm.jar`
    - Note that jar files are zip files with a different extension, so you should be able to use any zip editing tool to add the file.
    - [7-Zip](https://www.7-zip.org/) is a good zip (and jar) editor tool for Windows.
    - You might want to create a backup of the original `svm.jar`.
- Add `--features=com.oracle.svm.core.os.ForcedCopyingImageHeapProviderFeature` to `native-image` command line

The above should work with all existing GraalVM Community Edition versions, but a future GraalVM update may break it.

**Comment by sergeevabc** [comment]
@kornelpal
I have read what you wrote several times, but cannot grasp that.

Unknown `svm.jar` popped up, obscure slash in front of `/ForcedCopyingImageHeapProviderFeature.class`, etc

Let's say we need to compile `app.jar` into `app.exe`, what should be the command?

**Comment by kornelpal** [comment]
@sergeevabc, I've edited my previous post to include more details. Let me know if you need further clarification.

**Comment by sergeevabc** [comment]
@kornelpal 

Thank you, it works as expected. GraalVM generated binaries are UPXed fine now.  But what does `ForcedCopyingImageHeapProviderFeature.java` do that GraalVM developers neglected to do? And what can we do to make it part of the official distribution?

**Comment by kornelpal** [comment]
`ForcedCopyingImageHeapProviderFeature` just forces `CopyingImageHeapProvider` to be used before `WindowsImageHeapProvider` is registered. It needs to be injected into the GraalVM jar file because it is using non-exported classes.

`CopyingImageHeapProvider` is less memory efficient but is compatible with UPX.

`WindowsImageHeapProvider` is well meaning and is trying to share memory between processes too by mapping the shared memory directly from the exe file. When combined with UPX this results in random compressed data being used from the exe file instead of the actual uncompressed shared data. 

My recommendations for making `WindowsImageHeapProvider` compatible with UPX (from https://github.com/upx/upx/issues/559#issuecomment-1032047038):
- Compare the static parts of the in-memory image heap with the mapped file and fall back to `super.commitAndCopyMemory` when not matching.
- Or create a paging file backed (`INVALID_HANDLE_VALUE`) file mapping object, copy the uncompressed image heap to it and then that can be used and shared the same way as the mapped executable file.

If neither the above are likely to be implemented, you might want to request an official feature in GraalVM to force the use of `CopyingImageHeapProvider`.

**Comment by sergeevabc** [comment]
@kornelpal 

Thank you for the clear explanation.

By the way, I tired to compile `ForcedCopyingImageHeapProviderFeature.java` myself, but…

``` console
$ javac -cp svm.jar ForcedCopyingImageHeapProviderFeature.java

ForcedCopyingImageHeapProviderFeature.java:5: error: package org.graalvm.nativeimage does not exist
import org.graalvm.nativeimage.ImageSingletons;

(errors like that)
```

**Comment by kornelpal** [comment]
You need to either copy `svm.jar` to the current directory or specify the full path of it on the `javac` command line so that `javac` can find it.

**Comment by jreiser** [comment]
> trying to share memory between processes too by mapping the shared memory directly from the exe file

This is a sin, and Oracle is guilty.  There never was, and never will be, any guarantee that the in-memory process image contains a byte-wise copy from any portion of any exe file, or that there even is [was] a exe file at all.  For instance, the process image can be constructed [via shared memory with another process] from pieces downloaded from different sites over the network, which pieces become unreachable after downloading.

**Comment by sergeevabc** [comment]
@kornelpal
> You need to either copy svm.jar to the current directory or specify the full path of it on the javac command line so that javac can find it

I did, but…

<details>
  <summary>See errors log</summary>

``` console
$ dir /b
ForcedCopyingImageHeapProviderFeature.java
svm.jar

$ javac -cp svm.jar ForcedCopyingImageHeapProviderFeature.java
ForcedCopyingImageHeapProviderFeature.java:5: error: package org.graalvm.nativeimage does not exist
import org.graalvm.nativeimage.ImageSingletons;
                              ^
ForcedCopyingImageHeapProviderFeature.java:6: error: package org.graalvm.nativeimage.hosted does not exist
import org.graalvm.nativeimage.hosted.Feature;
                                     ^
ForcedCopyingImageHeapProviderFeature.java:8: error: cannot find symbol
public class ForcedCopyingImageHeapProviderFeature implements Feature {
                                                              ^
  symbol: class Feature
ForcedCopyingImageHeapProviderFeature.java:10: error: cannot find symbol
    public void afterRegistration(AfterRegistrationAccess access) {
                                  ^
  symbol:   class AfterRegistrationAccess
  location: class ForcedCopyingImageHeapProviderFeature
ForcedCopyingImageHeapProviderFeature.java:9: error: method does not override or implement a method from a supertype
    @Override
    ^
ForcedCopyingImageHeapProviderFeature.java:11: error: cannot find symbol
        ImageSingletons.add(ImageHeapProvider.class, new CopyingImageHeapProvider());
        ^
  symbol:   variable ImageSingletons
  location: class ForcedCopyingImageHeapProviderFeature
6 errors
```
</details>

**Comment by kornelpal** [comment]
Steps to create a build environment:
- No other Java/OpenJDK/GraalVM installation
    - You may skip this but this ensures that only the correct versions are used.
- Download the first and currently most recent GraalVM CE Windows binaries:
    - https://github.com/oracle/graal/releases/download/vm-19.0.0/graalvm-ce-windows-amd64-19.0.0.zip
    - https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-24.0.1/graalvm-community-jdk-24.0.1_windows-x64_bin.zip
- Extract both of the above zip files to `C:\graal`
    - This is to ensure that the original, unmodified `svm.jar` will be used by the matching `javac` version.
- Copy unmodified `ForcedCopyingImageHeapProviderFeature.java` to `C:\graal`
- Open command prompt in `C:\graal`

After the above setup both of these work for me with no errors and producing a new `ForcedCopyingImageHeapProviderFeature.class` file:
```
C:\graal\graalvm-ce-19.0.0\bin\javac.exe -cp C:\graal\graalvm-ce-19.0.0\jre\lib\svm\builder\svm.jar ForcedCopyingImageHeapProviderFeature.java
C:\graal\graalvm-community-openjdk-24.0.1+9.1\bin\javac.exe -cp C:\graal\graalvm-community-openjdk-24.0.1+9.1\lib\svm\builder\svm.jar ForcedCopyingImageHeapProviderFeature.java
```

@sergeevabc please note that I have provided the compiled `ForcedCopyingImageHeapProviderFeature.class` file in my original post as I understand that compiling it from source is and advanced task. I used GraalVM CE 19.0.0 for compiling it to ensure that it works with all currently existing GraalVM CE versions. Please feel free to use that.

**Comment by sergeevabc** [comment]
@kornelpal
Indeed, both distributions you mentioned throw no error here.
Then it boils down to the version of GraalVM I use, it is [17 Enterprise Edition LTS][1].

``` console
$ java --version
java 17.0.15 2025-04-15 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 17.0.15+9.1 (build 17.0.15+9-LTS-jvmci-23.0-b58)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 17.0.15+9.1 (build 17.0.15+9-LTS-jvmci-23.0-b58, mixed mode, sharing)
```

Any ideas why it does not like `ForcedCopyingImageHeapProviderFeature.java`?

[1]: https://web.archive.org/web/20250510204604if_/https://file.cnxiaobai.com/Windows/%E5%8A%9E%E5%85%AC%E8%BD%AF%E4%BB%B6/%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7/Java/Oracle%20JDK/JDK%2017/GraalVM/graalvm-jdk-17.0.15_windows-x64_bin.zip
