### ISSUE TITLE
clang++ complaints in vendor/gzip for branch devel4 on MacOS 13

### ISSUE THREAD

**Issue by jreiser** [upx/upx#677]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

In a new git clone of branch devel4, then clang++ complains `implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Werror,-Wshorten-64-to-32]` when compiling vendor/zlib/gzwrite.c and gzread.c.

The complaint is:
CompileC /Users/jreiser/upx-devel4/build/extra/upx.build/Debug/upx_vendor_zlib.build/Objects-normal/arm64/gzwrite.o /Users/jreiser/upx-devel4/vendor/zlib/gzwrite.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'upx_vendor_zlib' from project 'upx')
    cd /Users/jreiser/upx-devel4
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -ivfsstatcache /var/folders/hy/vxrbv0kd4vd57bphx65kthp80000gn/C/com.apple.DeveloperTools/14.3.1-14E300c/Xcode/SDKStatCaches.noindex/macosx13.3-22E245-.sdkstatcache -target arm64-apple-macos13.3 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -Wno-trigraphs -fpascal-strings -O2 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-implicit-fallthrough -DCMAKE_INTDIR\=\"Debug\" -DHAVE_STDARG_H\=1 -DHAVE_VSNPRINTF\=1 -DHAVE_UNISTD_H\=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -fstrict-aliasing -Wdeprecated-declarations -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -I/Users/jreiser/upx-devel4/build/extra/Debug/include -I/Users/jreiser/upx-devel4/build/extra/upx.build/Debug/upx_vendor_zlib.build/DerivedSources-normal/arm64 -I/Users/jreiser/upx-devel4/build/extra/upx.build/Debug/upx_vendor_zlib.build/DerivedSources/arm64 -I/Users/jreiser/upx-devel4/build/extra/upx.build/Debug/upx_vendor_zlib.build/DerivedSources -F/Users/jreiser/upx-devel4/build/extra/Debug -fsanitize\=undefined -fsanitize-undefined-trap-on-error -fstack-protector-all -Wall -Werror -std\=gnu11 -fno-strict-aliasing -fno-strict-overflow -funsigned-char -fno-tree-vectorize -MMD -MT dependencies -MF /Users/jreiser/upx-devel4/build/extra/upx.build/Debug/upx_vendor_zlib.build/Objects-normal/arm64/gzwrite.d --serialize-diagnostics /Users/jreiser/upx-devel4/build/extra/upx.build/Debug/upx_vendor_zlib.build/Objects-normal/arm64/gzwrite.dia -c /Users/jreiser/upx-devel4/vendor/zlib/gzwrite.c -o /Users/jreiser/upx-devel4/build/extra/upx.build/Debug/upx_vendor_zlib.build/Objects-normal/arm64/gzwrite.o
/Users/jreiser/upx-devel4/vendor/zlib/gzwrite.c:78:20: error: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Werror,-Wshorten-64-to-32]
            writ = write(state->fd, strm->next_in, put);
                 ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jreiser/upx-devel4/vendor/zlib/gzwrite.c:108:24: error: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Werror,-Wshorten-64-to-32]
                writ = write(state->fd, state->x.next, put);
                     ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.

The vendor/zlib version is:
```
$ git log
commit 460622b25ac8b5def9018d2e230cf63fc715822b (HEAD)
Author: upx-vendor-bot[bot] <none@none>
Date:   Wed May 3 07:29:30 2023 +0000

    Automatically created from git devel branch 9e307e184a1f
```
The compiler version is:
```
% clang++ --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
## What should have happened?

No complaints from compiler.

## Do you have an idea for a solution?

Widen the declaration of `writ` and the return value of gzread; or use casts.

## How can we reproduce the issue?

1. git clone -b devel4 https://github.com/upx/upx.git upx-devel4; cd upx-devel4
2. mkdir build/debug; cd build/debug
3. cmake ../.. -G Xcode
4. cmake --build .

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 4.0.2-devel.81+git-dae45ae0-dirty
* Host Operating System and version: Apple M1 Mini MacOS 13.1 (Ventura)
* Host CPU architecture: arm64 (aarch64-v8a)
* Target Operating System and version: same
* Target CPU architecture: same

**Comment by markus-oberhumer** [comment]
It seems that `cmake -G Xcode` adds a lot of extra warnings - I'll have a look.

In the meantime you can try `cmake -G Xcode -DUPX_CONFIG_DISABLE_WERROR=ON` as a workaround.

**Comment by markus-oberhumer** [comment]
Completely unrelated, on macOS arm64 registers `x18` and `x29` are reserved. Does our Linux gcc toolchain respect that?

**Comment by jreiser** [comment]
Where is the documentation of the restriction on x18 and x29 by MacOS arm64?

In **Procedure Call Standard for the ARM 64-bit Architecture**, ARM IHI 0055B (2013), section 5.1.1 General-purpose Registers (p.14) it says that r18 is `The Platform Register: If needed, otherwise a temporary register. See notes`.  The Note says `The role of register r18 is platform-specific.  If a platform ABI has need of a dedicated general purpose register to carry inter-procedural state (for example, the thread context) then it sould use this register for that purpose. ...`  And x29 is `FP, The Frame Pointer`.  Also r16 and r17 are intra-procedure-call temporaries (if needed by PLT code, for example), else general temporaries.  This hints that the restriction on r18 does not matter to UPX of a main program, but might need to be preserved by UPX on a shared library.  Because UPX handles all linkage internally (no PLT), then r16 and r17 also are available.  Low-level assembly code of UPX will have to avoid r29, but otherwise "the compiler" is charge of that register.

**Comment by markus-oberhumer** [comment]
CMake now adds `-Wno-shorten-64-to-32` when using the Xcode generator.
