### ISSUE TITLE
UPX crashes with SIGILL when compressing ARM static PIE

### ISSUE THREAD

**Issue by markus-oberhumer** [upx/upx#688]
Current devel branch crashes when compressing the attached test file (which is UPX compiled as ARM static PIE).

[upx-static-pie-arm.zip](https://github.com/upx/upx/files/12165516/upx-static-pie-arm.zip)

upx-4.0.1 and 4.0.2 seem to work, so possible regression.

```
$ make debug
$ cd build/debug
$ lldb -- ./upx upx-static-pie-arm -o xx
[...]
(lldb) r
Process 296399 launched: '/home/local/cvs/00-upx/upx--upx.git/build/debug/upx' (x86_64)
[...]
Process 296399 stopped
* thread #1, name = 'upx', stop reason = signal SIGILL: illegal instruction operand
    frame #0: 0x000000000058d496 upx`PackLinuxElf32::forward_Shdrs(this=0x00000000008c45b0, fo=0x00007fffffffd4f0,
eho=0x0000000000000000) at p_lx_elf.cpp:5721:17
   5718         fo->write(&file_image[get_te32(&sec_arm_attr->sh_offset)], attr_len);
   5719         total_out = fpad4(fo, total_out += attr_len);
   5720
-> 5721         set_te16(&eho->e_shnum, 3);
   5722         set_te16(&eho->e_shentsize, sizeof(Elf32_Shdr));
   5723         set_te32(&eho->e_shoff, total_out);
   5724         set_te16(&eho->e_shstrndx, 1);
(lldb)
```

**Comment by jreiser** [comment]
This might be just a more-complete implementation of support for (Elf32_Shdr.sh_type == ARM_ATTRIBUTES), and not truly a regression.  In particular, some debuggers such as gdb (via libbfd) and/or some OS such as Android have different interpretations of the 30-year old ELF specification for those  ElfXX_Ehdr fields that relate to ElfXX_Shdr records.  Earlier upx didn't support everything, so the debugger and/or OS either refused to accept it al all, or gave partial answers.  Current upx gives more-complete support, which had some growing pains in learning the actual demands of gdb, Android, and System V.

**Comment by markus-oberhumer** [comment]
Removing milestone and regression as this only ever affected the devel branch.
