### ISSUE TITLE
UPX can't compress win32/PE/exe with empty entries in Import Lookup Table

### ISSUE THREAD

**Issue by lightagain** [upx/upx#69]
## What's the problem (or question)?

Trying to compress win32/PE executable file, produced by RAD Studio XE2  (simple "Hello World" project; work on any version of Windows) with UPX version 3.91 - compressed successfully and compressed exe is working.
Trying to compress this executable with 3.92 and 3.93 - UPX fails with following output:
`upx: Project1.exe: InternalError: should not happen`

## What should have happened?

Versions 3.92 and 3.93 should compress this exe w/o errors

## Do you have an idea for a solution?
My investigation shown:
1. Exe has regular import directory and Delay load import directory.
2. Some entries in Import directory don't have import entries (functions) in it (gdiplus.dll, imm32.dll, windowscodecs.dll, dwmapi.dll, shell32.dll, uxtheme.dll, wtsapi32.dll)
3. upx fails to handle these empty entries in import directory
pefile.cpp:
```
            if (idlls[ic]->ordinal)
                ilinker->add(idlls[ic]->name, idlls[ic]->ordinal);
            else if (idlls[ic]->shname)
                ilinker->add(idlls[ic]->name, idlls[ic]->shname);
            else
                throwInternalError("should not happen"); // <- should not happen, but it's happen.
```

Don't know is it correct by PE specification, but exe with these "empty entries" correctly working in Windows and accepted by PE tools.
My suggestion is to add support for empty entries into import table as it was in 3.91.

## How can we reproduce the issue?

1. try to compress Project1.exe [Project1.zip](https://github.com/upx/upx/files/816530/Project1.zip) with upx v3.93
`upx.exe Project1.exe`
produce the following output:
`upx: Project1.exe: InternalError: should not happen`

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.91, 3.92, 3.93
* Operating System and version: Windows 10 x64; Windows 7 x64
* CPU architecture: source exe is win32 PE executable

**Comment by ml1050** [comment]
Unfortunately fixing this is non trivial. The "#if 0" code below is the reason why empty imports are not working now.

`    
    // create the preprocessed data
    upx_byte *ppi = oimport;  // preprocessed imports
    for (ic = 0; ic < dllnum; ic++)
    {
        LEXX *tarr = idlls[ic]->lookupt;
#if 0 && ENABLE_THIS_AND_UNCOMPRESSION_WILL_BREAK // FIXME
        if (!*tarr)  // no imports from this dll
            continue;
#endif
`

**Comment by ml1050** [comment]
Unfortunately fixing this problem is not trivial, as allowing empty imports would break the uncompression code (see ENABLE_THIS_AND_UNCOMPRESSION_WILL_BREAK in pefile.cpp).

**Comment by John-Yu** [comment]
you can try this code. in PeFile::processImports0(...)

` 

    ... 
    unsigned ic; 
    for (ic = 0; dllnum && im->dllname; ic++, im++) 
    { 
        idlls[ic] = dlls + ic;
        dlls[ic].name = ibuf + im->dllname;
        dlls[ic].shname = NULL;
        dlls[ic].ordinal = 0;
        dlls[ic].iat = im->iat;
        dlls[ic].lookupt = (LEXX*) (ibuf + (unsigned) (im->oft ? im->oft : im->iat));
        dlls[ic].original_position = ic;
        dlls[ic].isk32 = strcasecmp(kernelDll(), (const char*)dlls[ic].name) == 0;
		//useless DLL, ignore it 
		if (!*(dlls[ic].lookupt)) {
			dllnum--;
			ic--;
			continue;
		}
        soimport += strlen(dlls[ic].name) + 1 + 4;
    ...

`

**Comment by John-Yu** [comment]
Only change this one point, I have tested, it works well.

**Comment by lightagain** [comment]
@John-Yu, I used this solution for my exe's  (on v3.93) - no problems found

**Comment by jreiser** [comment]
The proposed fix above https://github.com/upx/upx/issues/69#issuecomment-325868625 doe work for compression.  But after that then the existing de-compression does not work: https://github.com/upx/upx/issues/69#issuecomment-292278306 .  So is anyone interested in working on the de-compression?
