### ISSUE TITLE
Unity libil2cpp.so test failed on arm64-v8a platform

### ISSUE THREAD

**Issue by TaffyStudio** [upx/upx#693]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
I used -- android hlib to compress so files, but when using - t to test the output file, I received an error message:
upx: libil2cpp.so: CantUnpackException: bad PT_LOAD phdr[1]

                        Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX git-fa364d  Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 3rd 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  62992736 ->  30626092   48.62%   linux/arm64   libil2cpp.so                                                                                                                                                                                   Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.

D:\Desktop>upx libil2cpp.so -t
[doctest] doctest version is 2.4.11
[doctest] compiler version is msvc 19.35.32217 (64-bit, C++201703)
[doctest] run with "--dt-help" for options
===============================================================================
[doctest] test cases:  40 |  40 passed | 0 failed | 0 skipped
[doctest] assertions: 629 | 629 passed | 0 failed |
[doctest] Status: SUCCESS!
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX git-fa364d  Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 3rd 2023

upx: libil2cpp.so: CantUnpackException: bad PT_LOAD phdr[1]

Tested 0 files.

WARNING: this is an unstable beta version - use for testing only! Really.

## What should have happened?
The output file should pass the test

## How can we reproduce the issue?

[libil2cpp.zip](https://github.com/upx/upx/files/12255512/libil2cpp.zip)
1.use --android-shlib to pack the file
2.use -t to test the output file
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):upx 4.1.0-git-fa364d6ea309
* Host Operating System and version:Windows 11 Insider Preview 23H2
* Host CPU architecture:i5-10300H(X64)
* Target Operating System and version:Android13
* Target CPU architecture:Snapdragon 888(arm64-v8a)

**Comment by markus-oberhumer** [comment]
@jreiser please have a look if this should go into v4.1.0

**Comment by jreiser** [comment]
@markus-oberhumer  Yes, probably this should go into v4.1.0.  Working on it...

**Comment by jreiser** [comment]
Fixed; builds available on Actions page for bb76df9bcbea01600b5818567481ed5337b2f7c4 .
