### ISSUE TITLE
Compressed golang armv8 library crashes on Android (UPX 4.1.0)

### ISSUE THREAD

**Issue by zhaodice** [upx/upx#694]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
Compressed armv8 library crashes

## What should have happened?
App should be able to launch without crash

## Do you have an idea for a solution?
nop

## How can we reproduce the issue?

1. compile a golang jni library `go build -ldflags "-s -w" -buildmode=c-shared -o libgo-cqhttp.so`
2. upx it `upx --android-shlib --force-pie --best --brute libgo-cqhttp.so`
3. System.loadLibrary("go-cqhttp")
4. crash

## Please tell us details about your environment.

* UPX version used (`upx --version`):
upx 4.1.0
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.13.1-motley
LZMA SDK version 4.43
Copyright (C) 1996-2023 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2023 Laszlo Molnar
Copyright (C) 2000-2023 John F. Reiser
Copyright (C) 2002-2023 Jens Medoch
Copyright (C) 1995-2023 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.

* Host Operating System and version:
Proxmox VE 8, on LXC container Ubuntu kinetic 
Linux LXC-GoCompile 6.2.16-4-bpo11-pve #1 SMP PREEMPT_DYNAMIC PVE 6.2.16-4~bpo11+1 (2023-07-07T15:05Z) x86_64 x86_64 x86_64 GNU/Linux

* Host CPU architecture:
x86_64 

* Target Operating System and version:
Android 10, VIVO Y52s
Linux localhost 4.14.141+ #1 SMP PREEMPT Fri Jul 7 11:53:45 CST 2023 aarch64

* Target CPU architecture:
aarch64

it sames to : https://github.com/upx/upx/issues/669
~I will test this version later~ oh no, it expired

```
08-09 20:10:46.434 16394 16394 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/org.mirai.astral.gdice-06aAAnGKRhN_KhT2Hzto6w==/lib/arm64/libgo-cqhttp.so" has unsupported e_shentsize: 0x0 (expected 0x40)
08-09 20:10:46.434 16394 16394 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
08-09 20:10:46.434 16394 16394 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
08-09 20:10:46.434 16394 16394 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1667)
08-09 20:10:46.434 16394 16394 E AndroidRuntime:        at org.mirai.zhao.dice.console.worker.GOCQ.main(Unknown Source:2)
08-09 20:10:46.434 16394 16394 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-09 20:10:46.434 16394 16394 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:372)
08-09 20:10:46.435 16394 16394 E AndroidRuntime: Error reporting crash
08-09 20:10:46.435 16394 16394 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:535)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:128)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.os.ServiceManager.rawGetService(ServiceManager.java:263)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:129)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:4223)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:4220)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:38)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.app.ActivityManager.getService(ActivityManager.java:4211)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$LoggingHandler.uncaughtException(RuntimeInit.java:120)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:2181)
08-09 20:10:46.435 16394 16394 E AndroidRuntime: Error reporting crash
08-09 20:10:46.435 16394 16394 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:535)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:128)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.os.ServiceManager.rawGetService(ServiceManager.java:263)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:129)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:4223)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:4220)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:38)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at android.app.ActivityManager.getService(ActivityManager.java:4211)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:179)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
08-09 20:10:46.435 16394 16394 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:2187)
```

**Comment by markus-oberhumer** [comment]
I would be surprised, but could you try if upx-4.0.0 , 4.0.1 or 4.0.2 happen to work ?

**Comment by zhaodice** [comment]
> I would be surprised, but could you try if upx-4.0.0 , 4.0.1 or 4.0.2 happen to work ?

upx4.0.0: libgo-cqhttp.so: CantPackException: bad dynsym
upx4.0.2: libgo-cqhttp.so: CantPackException: bad dynsym

**Comment by jreiser** [comment]
Please supply the library which failed. `/lib/arm64/libgo-cqhttp.so`, both before and after compression.
Please supply the complete source to the testcase which fails: `System.loadLibrary("go-cqhttp")` is not even a complete statement.

**Comment by zhaodice** [comment]
> Please supply the library which failed. `/lib/arm64/libgo-cqhttp.so`, both before and after compression. Please supply the complete source to the testcase which fails: `System.loadLibrary("go-cqhttp")` is not even a complete statement.

OK, I will provide the `so`
[DemoSo.zip](https://github.com/upx/upx/files/12308523/DemoSo.zip)

KOTLIN CODE: 
```
package org.mirai.zhao.dice.console.worker
//GOCQ.kt
object GOCQ {
    external fun run()
    init{
        System.loadLibrary("go-cqhttp")
    }
}
```

```
package org.mirai.zhao.dice.console.worker
//GOCQLoader.kt
object GOCQLoader {
    @JvmStatic
    fun main(args: Array<String>) {
        GOCQ.run()
    }
}
```

**Comment by zhaodice** [comment]
Actually , you can simply load the so file, then it crashs

**Comment by jreiser** [comment]
Using the supplied [DemoSo.zip](https://github.com/upx/upx/files/12308523/DemoSo.zip) I cannot reproduce the behavior that was reported in the initial Description of this Issue.
In the system log, the complaint is:
```
   08-09 20:10:46.434 16394 16394 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: \
   "/data/app/org.mirai.astral.gdice-06aAAnGKRhN_KhT2Hzto6w==/lib/arm64/libgo-cqhttp.so" \
   has unsupported e_shentsize: 0x0 (expected 0x40)
```
and the rest is a consequence of `dlopen failed`.

When I try to reproduce:
```
$ $UPXv410 --android-shlib -f -o foo libgo-cqhttp.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  12827304 ->   9349660   72.89%   linux/arm64   foo                           

Packed 1 file.

$ sha256sum libgo-cqhttp.so foo
f6bdce522302c4c05cdf8f855209f440af22a2963630335f88cdd4ff1bed0229  libgo-cqhttp.so
635e861dfc9ca56fcf457a8bfa8a4741641022bab7c63a40428dcd79edeb0eb8  foo

$ readelf --all foo  |  grep 'ection header'
  Start of section headers:          9347768 (bytes into file)
  Size of section headers:           64 (bytes)
  Number of section headers:         29
  Section header string table index: 28
```
which does not match the initial complaint `unsupported e_shentsize: 0x0 (expected 0x40)` because `Size of section headers: 64 (bytes)` and (64 == 0x40).

**Comment by zhaodice** [comment]
> Using the supplied [DemoSo.zip](https://github.com/upx/upx/files/12308523/DemoSo.zip) I cannot reproduce the behavior that was reported in the initial Description of this Issue. In the system log, the complaint is:

yes, you're right , your `--android-shlib -f -o foo libgo-cqhttp.so` looks working fine,

but... my exec params that reported are:

`upx --android-shlib --force-pie --brute libgo-cqhttp.so`

it will produce many warnings:
```
# readelf --all /root/outputs/arm64-v8a/libgo-cqhttp.so |  grep 'ection header'
readelf: Error:  bad symbol index: 2d99869e in reloc
readelf: Error:  bad symbol index: 6baeb3de in reloc
readelf: Error:  bad symbol index: 0a97a213 in reloc
readelf: Error:  bad symbol index: c6c946dc in reloc
readelf: Error:  bad symbol index: d63674e6 in reloc
readelf: Error:  bad symbol index: 81e66676 in reloc
readelf: Error:  bad symbol index: a07fde9c in reloc
readelf: Warning: local symbol 1 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 3 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 4 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 5 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 6 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 7 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 8 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 9 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 10 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 21 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 38 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 40 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 41 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 57 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 85 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 89 found at index >= .dynsym's sh_info value of 1
readelf: Warning: local symbol 98 found at index >= .dynsym's sh_info value of 1
readelf: Warning: Invalid vna_next field of 0
readelf: Warning: Invalid vn_next field of 0
```

**Comment by jreiser** [comment]
@zhaodice  The combination of `--force-pie` and actually being a shared library (not a main program) will not work unless the input to UPX specifies a PT_INTERP.  Only a PT_INTERP performs dynamic relocation and symbol name resolution (connecting external references to the corresponding defined values.)  So you must convince the static binder (/usr/bin/ld, gold, etc.) which built `libgo-cqhttp.so` to insert a `Elf64_Phdr` with `(.p_type == PT_INTERP)`, and designating the run-time interpreter such as `rtld`, `ld-linux.so`, etc.

**Comment by zhaodice** [comment]
> @zhaodice The combination of `--force-pie` and actually being a shared library (not a main program) will not work unless the input to UPX specifies a PT_INTERP. Only a PT_INTERP performs dynamic relocation and symbol name resolution (connecting external references to the corresponding defined values.) So you must convince the static binder (/usr/bin/ld, gold, etc.) which built `libgo-cqhttp.so` to insert a `Elf64_Phdr` with `(.p_type == PT_INTERP)`, and designating the run-time interpreter such as `rtld`, `ld-linux.so`, etc.

ok, I use the command `upx --android-shlib -f --brute libgo-cqhttp.so` , it works.
if it is wrong usage , it could add a checking ? if no more things, this issue can be closed.

**Comment by markus-oberhumer** [comment]
@jreiser Would it be easy to spot a bad `--force-pie` usage ?

**Comment by markus-oberhumer** [comment]
@zhaodice Why did you think that `--force-pie` was needed in the first place ? Is there some issue with our docs?

**Comment by zhaodice** [comment]
> @zhaodice Why did you think that `--force-pie` was needed in the first place ? Is there some issue with our docs?

I saw the Chinese communication website :https://www.zhihu.com/pin/1090591270547542016
he said `--android-shlib`  can keep the elf header, and `--force-pie` can be used to solve text relocation,
so I though it can be used together on the future version...Sorry.
```
The bug of upx3.95 is really wonderful

--android-shlib can keep the elf header (otherwise 7.0+ will report dolpen fail)

--force-pie can be used to solve text relocation

but after --force-pie is enabled --android-shlib doesn't work

, so the so file I got now either crashes with text relocation, or crashes with dolpen fail...
```

**Comment by jreiser** [comment]
Another reason for trying `--force-pie`  is tighter compression:
```
$ $UPXv410 --android-shlib --force-pie -f -o foo-yes-force-pie libgo-cqhttp.so
  12827304 ->   4687732   36.54%   linux/arm64   foo-yes-force-pie

$ $UPXv410 --android-shlib             -f -o foo-no-force-pie  libgo-cqhttp.so
  12827304 ->   9570844   74.61%   linux/arm64   foo-no-force-pie

$ readelf --relocs libgo-cqhttp.so  |  grep 'Relocation section'
Relocation section '.rela.dyn' at offset 0x1938 contains 58464 entries:
```
All but 1 of those  58464 relocations are R_AARCH64_RELATIVE at 24 bytes each, so 1.4MB total.  If `--force-pie` then UPX can compress them because the stub de-compressor runs _first_ after `execve`, and before the PT_INTERP.  The run-time stub de-compressor will de-compress and present the relocations to the PT_INTERP.  If no `--force-pie` then the UPX stub de-compressor runs _after_ the dynamic relocation processing of `dlopen`, and so must leave the relocations (and their targets) un-compressed.  This is one example of why R_arch_RELATIVE should be re-written.  See https://github.com/upx/upx/issues/696 .  The other space savings of (4 MB - 1.4 MB) = 2.6 MB comes from compressing other ELF tables that reside below .text, and from compressing
```
  [16] .data.rel.ro      PROGBITS        000000000075b5a0 7595a0 48f010 00  WA  0   0 32
```
which is 4.9 MB of the _targets_ (written destinations) of relocation, which must be writeable by `dlopen` (or the PT_INTERP.)

Alternately, if the original `libgo-cqhttp.so` had a PT_INTERP, then `--force-pie` would compress it into a main program which the PT_INTERP would process.  There is also a slight problem of where the PT_INTERP should transfer control: currently `.e_entry` is 0, and there is no symbol `main`.  (There is a `main.main`; perhaps this is a feature of `golang`?)

Update: When turning a .so shared library into an ET_DYN main program, then the DF_!_PIE flag bit should be set in the DT_FLAGS_1 entry of PT_DYNAMIC.

**Comment by zhaodice** [comment]
> Update: When turning a .so shared library into an ET_DYN main program, then the DF_!_PIE flag bit should be set in the DT_FLAGS_1 entry of PT_DYNAMIC.

This is a executable program project origenally, but I edited its sources, and added some JNI interface to call the `main()` function and `-buildmode=c-shared` to build it as a `so file` .
you're right , `main.main` is a feature of `golang`
