### ISSUE TITLE
CantPackException: corrupted file

### ISSUE THREAD

**Issue by 239** [upx/upx#699]
## What's the problem (or question)?
`upx *`
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: age: AlreadyPackedException
upx: bat: CantPackException: corrupted file; try '--debug' for more details
upx: upx: AlreadyPackedException

Packed 0 files.
```
`upx --debug bat`
```
upx: bat: CantPackException: corrupted file; details: bytes > 0 (/home/mfx/code/github/upx/upx4/src/util/membuffer.cpp: alloc: 203)
```

## What should have happened?
```
...
upx: bat: AlreadyPackedException
...
```

## Do you have an idea for a solution?
Related issue: #622
`file *`
```
age: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, no section header
bat: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), statically linked, no section header
upx: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, no section header
```

`upx -l *`
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   4986442 ->   2931248   58.78%   linux/amd64   age
   5491832 ->   2594720   47.25%   linux/amd64   bat
   2082896 ->    568268   27.28%   linux/amd64   upx
   --------------------   ------   -----------   -----------
  12561170 ->   6094236   48.52%                 [ 3 files ]
```

## How can we reproduce the issue?
[bat-v0.23.0-x86_64-unknown-linux-musl.tar.gz](https://github.com/upx/upx/files/12418135/bat-v0.23.0-x86_64-unknown-linux-musl.tar.gz)
1. Compress PIE binaries like [**bat**](https://github.com/sharkdp/bat/releases/latest), **fd**, **nu** or **starship**
2. Run UPX again

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.1.0
* Host Operating System and version: various
* Host CPU architecture: x86-64
* Target Operating System and version: any
* Target CPU architecture: x86-64

**Comment by markus-oberhumer** [comment]
Please attach your `bat`  file.

**Comment by 239** [comment]
[bat-v0.23.0-x86_64-unknown-linux-gnu.tar.gz](https://github.com/sharkdp/bat/releases/download/v0.23.0/bat-v0.23.0-x86_64-unknown-linux-gnu.tar.gz)
[bat-v0.23.0-x86_64-unknown-linux-musl.tar.gz](https://github.com/sharkdp/bat/releases/download/v0.23.0/bat-v0.23.0-x86_64-unknown-linux-musl.tar.gz)

**Comment by markus-oberhumer** [comment]
@jreiser John please have a look

**Comment by jreiser** [comment]
Fixed by above commit.
