### ISSUE TITLE
[devel branch] crash on upx -d

### ISSUE THREAD

**Issue by lynnux** [upx/upx#7]
upx -d aaaa.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2015
UPX 3.92w       Markus Oberhumer, Laszlo Molnar & John Reiser   Mar 30th 2015

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
Assertion failed: file_image != NULL, file p_lx_elf.cpp, line 240

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

==========================================
code: assert(file_image != NULL);  // set by PackLinuxElf64help1
However, it seems file_image never be set by PackLinuxElf64help1

**Comment by markus-oberhumer** [comment]
The devel branch is currently undergoing heavy cleanups - please wait until the upx-testsuite is functional.
