### ISSUE TITLE
 error: 'acc_cta__44' declared as an array with a negative size

### ISSUE THREAD

**Issue by tpgxyz** [upx/upx#70]
## What's the problem (or question)?
I'm trying to compile upx-3.93 with a LLVM/clang 4.0 (didn't tried with GCC yet).
I get errors like:

make: Leaving directory '/builddir/build/BUILD/upx-3.93-src/src'
In file included from compress_ucl.cpp:29:
./conf.h:61:1: error: 'acc_cta__44' declared as an array with a negative size
ACC_COMPILE_TIME_ASSERT_HEADER(CHAR_MAX == 255) // -funsigned-char
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./miniacc.h:2036:104: note: expanded from macro 'ACC_COMPILE_TIME_ASSERT_HEADER'
#    define ACC_COMPILE_TIME_ASSERT_HEADER(e)  ACC_EXTERN_C_BEGIN extern int __ACC_CTA_NAME(acc_cta__)[1-2*!(e)]; ACC_EXTERN_C_END

Full build.log can be found here https://abf.openmandriva.org/build_lists/99977

## What should have happened?
upx should compile without errors

## Do you have an idea for a solution?
Nope :(

## How can we reproduce the issue?

1. run make with a CC set to clang
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.93
* Operating System and version: OpenMandriva Lx cooker
* CPU architecture: x86_64, i586, armv7hl, aarch64

**Comment by markus-oberhumer** [comment]
It seems the RPM spec file blindly overrides UPX's CXXFLAGS in src/Makefile.

**Comment by tpgxyz** [comment]
Ok, my bad. Thanks for hint.

**Comment by marcocpt** [comment]
> Ok, my bad. Thanks for hint.

I have the same problem, but I don't quite understand how to modify it. Can you say something specific?

**Comment by tpgxyz** [comment]
@marcocpt simply do not set CXXFLAGS=
