### ISSUE TITLE
Option to update a target in-place instead of using unlink/rename 

### ISSUE THREAD

**Issue by jjlin** [upx/upx#706]
## What's the problem (or question)?

Some programs (Git, for example) install by default with a large number of hard links to a single executable, where the invocation name determines how the executable behaves. Since `upx` unlinks the original file and renames the temp output file to the original file name, the hard links are all broken and would need to be reconstructed.

## What should have happened?

Ideally, there should be an option (or perhaps it should just be the default behavior on supported systems) to update the original file in-place instead of using the current unlink/rename approach.

**Comment by jreiser** [comment]
Please give the details (OS, distribution, version) of the installation of `git` which uses a large number of hard links.  On Fedora Linux, they are soft links:
```
$ type git
git is hashed (/usr/bin/git)
$ rpm -qf /usr/bin/git
git-core-2.40.1-1.fc36.x86_64
$ rpm -ql git-core-2.40.1-1.fc36.x86_64
   <<snip>>
/usr/libexec/git-core/git-am
   <<snip>>
$ ls -l /usr/libexec/git-core/git-am
lrwxrwxrwx. 1 root root 13 Apr 25 11:05 /usr/libexec/git-core/git-am -> ../../bin/git
```
So those links are symbolic links (soft links), not hardlinks, and they do not have the problem alleged.

Hard links can be useful, but they are fragile.  Overwriting  a file that has hardlinks creates problems for recovery from application crashes, device errors, power fail, etc.

Update: Overwriting also creates a problem with concurrent active use: either corruption of uses, or prohibitiion of change if there are active uses.  Unlink+rename avoids the problem.

**Comment by markus-oberhumer** [comment]
We have to use a new temporary file because packing can fail at any any time, but I'd guess we could indeed write the contents of the new file over the original file (instead of renaming). How do other tools handle this issue?

**Comment by markus-oberhumer** [comment]
I've created a new branch `test-preserve-link` https://github.com/upx/upx/tree/test-preserve-link

Some review/testing would be appreciated.

**Comment by jjlin** [comment]
@jreiser I'm referring to building Git from source. I suspect most Linux distros will package things without using hard links.

Yeah, updating an executable in-place when it's actively in use will cause problems, so my musing that it should perhaps be default behavior turns out to be a bad idea.

**Comment by markus-oberhumer** [comment]
This will definitely **NOT** be the default, and I'm also thinking about ignoring `--link` on non-Unix platforms.

Users are expected know what they are doing when using this flag.

**Comment by jjlin** [comment]
I did some testing with `--link` and it looks fine, except the usage info doesn't list the `--link` option, but maybe you were planning on adding that later. Thanks for implementing this so quickly!

**Comment by markus-oberhumer** [comment]
@jjlin Yes, still need to add some docs.

**Comment by markus-oberhumer** [comment]
Fixed in devel. Beware:

```cpp
// NOTE: only use "preserve_link" if you really need it, e.g. it can fail
//   with ETXTBSY and other unexpected errors; renaming files is much safer
```
