### ISSUE TITLE
error: taking address of packed member 'sz_cpr' of class or structure

### ISSUE THREAD

**Issue by tpgxyz** [upx/upx#71]
## What's the problem (or question)?
I'm trying to build upx-3.93 with LLVM/Clang and i got this error:

make: Leaving directory '/builddir/build/BUILD/upx-3.93-src/src'
p_lx_elf.cpp:926:71: error: taking address of packed member 'sz_cpr' of class or structure 'PackUnix::b_info' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
    int r = upx_compress(uncLoader, h.sz_unc, sizeof(h) + cprLoader, &h.sz_cpr,
                                                                      ^~~~~~~~
p_lx_elf.cpp:991:71: error: taking address of packed member 'sz_cpr' of class or structure 'PackUnix::b_info' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
    int r = upx_compress(uncLoader, h.sz_unc, sizeof(h) + cprLoader, &h.sz_cpr,
                                                                      ^~~~~~~~
2 errors generated.

Full build.log can be found here https://abf.openmandriva.org/build_lists/100148

## Do you have an idea for a solution?
upx should compile without errors

## How can we reproduce the issue?

1.run make with a CXX set to clang
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.93
* Operating System and version: OpenMandriva Lx cooker
* CPU architecture: x86_64

**Comment by markus-oberhumer** [comment]
This seems a new warning introduced in the current llvm-4.0 pre-release.

Just use `make CXXFLAGS_WERROR=` for now.

**Comment by jreiser** [comment]
Furthermore, clang's complaint is incorrect.

**Comment by markus-oberhumer** [comment]
Anyway, the warning is now worked-around in the current devel branch.
