### ISSUE TITLE
Compacting using pyinstaller causing antivirus false positives

### ISSUE THREAD

**Issue by gabriellopesdesouza2002** [upx/upx#711]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

I've been facing this problem for more than 3 weeks, I've now discovered that it was all the UPX's fault.

Apparently after updating libraries and Python itself to version 3.11.5 and pyinstaller to version 5.13.0, errors began to occur. After a version downgrade, pyinstaller was unable to create the executable due to a lack of dependencies. Today, creating the executable in python version: 3.11.5 from the Microsoft Store using pyinstaller in version 5.12.0 using the following command first:

pyinstaller --onefile --console --name "Difal V1.0.6" --upx-dir "UPX" --add-data "C:/Users/gabriel.souza/Documents/Projetos Python/Whirlpool/Difal/ui/ base/data/icons;icons/" --add-data "C:/Users/gabriel.souza/Documents/Projetos Python/Whirlpool/Difal/ui/base/data/buttons;buttons/" --add-data " C:/Users/gabriel.souza/Documents/Projetos Python/Whirlpool/Difal/ui/base/data/background;background/" --add-data "C:/Users/gabriel.souza/Documents/Projetos Python/Whirlpool /Difal/ui/base/data;data/" --add-data "C:/Users/gabriel.souza/Documents/Python Projects/Whirlpool/Difal/ui/base;base/" "C:/Users/gabriel .souza/Documents/Projetos Python/Whirlpool/Difal/main.py"

UPX caused a false positive in the antivirus. The problem was resolved using the following command:

pyinstaller --noconfirm --onefile --console --icon "C:/Users/gabriel.souza/Documents/Projetos Python/Whirlpool/Difal/ui/base/data/icons/icon_logo.ico" --name "Difal" --add-data "C:/Users/gabriel.souza/Documents/Python Projects/Whirlpool/Difal/ui/base/data/icons;icons/" --add-data "C:/Users/gabriel.souza/ Documents/Projetos Python/Whirlpool/Difal/ui/base/data/buttons;buttons/" --add-data "C:/Users/gabriel.souza/Documents/Projetos Python/Whirlpool/Difal/ui/base/data/ background;background/" --add-data "C:/Users/gabriel.souza/Documents/Python Projects/Whirlpool/Difal/ui/base/data;data/" "C:/Users/gabriel.souza/Documents/ Python Projects/Whirlpool/Difal/main.py"

Regarding other libraries, I redid the pyinstaller bootloader, checked the website: https://www.virustotal.com/ for viruses. Only 1 vulnerability was recognized out of 68 recognized by any virus, unlike the version made with UPX, there was 1 vulnerability out of 55 recognized.

I tested it with my entire software development team and only the version without UPX worked correctly.

I would like you to resolve this issue as quickly as possible, as it is a great library for reducing the size of executables.

## What should have happened?

Working as it always has

## Do you have an idea for a solution?

I don't have a solution

## How can we reproduce the issue?

1. Create any executable with and without upx
2. Test in a computer with an antivirus, for example BitDefender antivirus

## Please tell us details about your environment.

* UPX version used (`upx --version`): 5.12.0
* Host Operating System and version: Windows 11 Version 22H2. Compilation: 22621.2283
* Host CPU architecture: ACPI\GenuineIntel_-_Intel64_Family_6_Model_140_-_11th_Gen_Intel(R)_Core(TM)_i5-1135G7_@_2.40GHz\_0 
* Target Operating System and version: Windows 11 Version 22H2. Compilation: 22621.2283 (coworker)
* Target CPU architecture: ACPI\GenuineIntel_-_Intel64_Family_6_Model_140_-_11th_Gen_Intel(R)_Core(TM)_i5-1135G7_@_2.40GHz\_0 (coworker)

**Comment by jreiser** [comment]
The solution is highlighted at the top of the main Issues page https://github.com/upx/upx/issues in the story `[[PINNED] False positive antivirus alerts of official UPX releases](https://github.com/upx/upx/issues/437) .  UPX co-operates fully with various virus/malware detectors; they can take some time before recognizing new official releases of UPX.  In some cases, end users such as yourself can accelerate the process by contacting the creators of the scanning software, as described in Issue #437.

**Comment by markus-oberhumer** [comment]
Please see pinned issue #437
