### ISSUE TITLE
Add an option to remove UPX information in compressed executable file

### ISSUE THREAD

**Issue by hclihn** [upx/upx#714]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
When using the `strings` command on the compressed executable file, you can find the UPX information in the output:
```bash
$ strings path/to/upx/compressed/executable
...
PROT_EXEC|PROT_WRITE failed.
$Info: This file is packed with the UPX executable packer http://upx.sf.net $
$Id: UPX 4.02 Copyright (C) 1996-2023 the UPX Team. All Rights Reserved. $
...
```

## What should have happened?
The use of the upx program on my Go executable is not only compressing down the size significantly, but also hide function names and files names in the `.gopclntab` to prevent reverse engineering of the codes from hackers.

Since upx provides the `-d` option to decompress the compressed executable, this makes it easier for hackers to restore the uncompressed executable. The UPX strings in the compressed executable provides them the clue of what to use to restore.

If there is an option for the user to produce the compressed executable without saving the UPX information, then it will make it a bit harder for hackers to find a way to restore the code.

## Do you have an idea for a solution?
Add a new command-line option to not saving the UPX information listed above.

## How can we reproduce the issue?

1. Issue the command `strings path/to/upx/compressed/executable`
2. Look for UPX information in the output

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.02
* Host Operating System and version: Linux RHEL9
* Host CPU architecture: x86-64
* Target Operating System and version: Linux RHEL9
* Target CPU architecture: x86-64

**Comment by hclihn** [comment]
From `main.cpp`, I found the undocumented `--small` option which seemed to make this feature work:
1. With no `--small` issued, we get the 2-line (big) identity strings:
    ```
    $Info: This file is packed with the UPX executable packer http://upx.sf.net $
    $Id: UPX 4.02 Copyright (C) 1996-2023 the UPX Team. All Rights Reserved. $
    ```
1. With `--small` issued, we get the 1-line (small) identity string:
    ```
    $Id: UPX (C) 1996-2023 the UPX Team. All Rights Reserved. http://upx.sf.net $
    ```
1. With `--small --small` issued, we get the tiny identity string (just the version):
    ```
    4.02
    ```
So I wonder if this feature can be documented either in the help text or somewhere in this repo? 

Though we can still find `UPX!` patterns in the `strings` output, but that's the compressed data header (magic). I will not ask it to be removed.

**Comment by markus-oberhumer** [comment]
UPX is not a software protection tool, and any tampering of the headers is a violation of our license terms.

See the files https://github.com/upx/upx/blob/master/README and https://github.com/upx/upx/blob/master/LICENSE
