### ISSUE TITLE
Set minimum permissions for workflows

### ISSUE THREAD

**Issue by gabibguti** [upx/upx#715]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

GitHub workflows are [granted high permissions by default](https://docs.github.com/en/actions/security-guides/automatic-token-authentication). Permissions that allow, for example, to delete your source code and publish releases.

## What should have happened?

Use minimum permissions to run GitHub workflows, granting jobs only the necessary permissions.

## Do you have an idea for a solution?

[Set restricted permissions to run GitHub workflows](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions) and resolve one by one the workflows, granting jobs only the necessary permissions.

## How can we reproduce the issue?

Not applicable.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

Not applicable.

##### Additional context

My name is Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by markus-oberhumer** [comment]
I've changed the `Settings > Actions > General` section `Workflow permissions` from `Read and write permissions` to `Read repository contents`
