### ISSUE TITLE
LZMA decoder on AMD64 gets random exit(127)

### ISSUE THREAD

**Issue by jreiser** [upx/upx#717]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

On AMD64, compressed main program or shared library gets random exit(127) during stub decode because of interface error when calling LzmaDecode.
## How can we reproduce the issue?

1. Compress AMD64 executable using --lzma.
2. Run.
3. Random exit(127) with frequency about 1 in 1000.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx-4.0.2
* Host Operating System and version: Linux 6.x
* Host CPU architecture: x86_64
* Target Operating System and version: Linux 6.x
* Target CPU architecture:x86_64
* 
https://github.com/MichalStrehovsky/PublishAotCompressed/issues/11

**Comment by jreiser** [comment]
Fix by Kevin Gosse.  Thank you!

https://github.com/upx/upx/pull/716
https://github.com/MichalStrehovsky/PublishAotCompressed/issues/11

**Comment by kevingosse** [comment]
Do you have an estimated timeframe for release? (days, weeks, months?)

I'm not asking to put pressure, it's just that if you don't think it'll be released in the coming weeks then I'll use my own fork in the meantime 🙂

**Comment by jreiser** [comment]
@markus-oberhumer  This bug+fix is a significant candidate for a 4.1.1 release.

@kevingosse  Keep using your own fork in the meantime.

**Comment by markus-oberhumer** [comment]
@jreiser When was this bug introduced?

**Comment by jreiser** [comment]
According to `git blame src/stub/src/arch/amd64/lzma_d.S`:
```
7185358b9 (John Reiser             2006-07-15 20:05:41 -0700  46) //      addq src,lsrc; push lsrc  // &input_eof   *****
3360787c2 (John Reiser             2023-10-06 13:29:29 -0700  47) //      subq src,lsrc //restore the value of lsrc   *****
7185358b9 (John Reiser             2006-07-15 20:05:41 -0700  48)
3843ec1e0 (John Reiser             2006-07-15 16:01:53 -0700  49) #define M_LZMA          14
86392f197 (László Molnár           2013-08-28 00:24:54 +0200  50) #ifndef NO_METHOD_CHECK
3843ec1e0 (John Reiser             2006-07-15 16:01:53 -0700  51)         cmpb $ M_LZMA,methb; jne not_lzma
86392f197 (László Molnár           2013-08-28 00:24:54 +0200  52) #endif
7185358b9 (John Reiser             2006-07-15 20:05:41 -0700  53)         pushq %rbp; movq %rsp,%rbp  // we use alloca
3843ec1e0 (John Reiser             2006-07-15 16:01:53 -0700  54)
3843ec1e0 (John Reiser             2006-07-15 16:01:53 -0700  55) //LzmaDecode(  // from lzmaSDK/C/7zip/Compress/LZMA_C/LzmaDecode.h
3843ec1e0 (John Reiser             2006-07-15 16:01:53 -0700  56) //      %arg1= &CLzmaDecoderState,
3843ec1e0 (John Reiser             2006-07-15 16:01:53 -0700  57) //      %arg2= in,  %arg3l= inSize, %arg4= &inSizeProcessed,
7185358b9 (John Reiser             2006-07-15 20:05:41 -0700  58) //      %arg5= out, %arg6l= outSize, arg7@ 8+%esp/ &outSizeProcessed
3843ec1e0 (John Reiser             2006-07-15 16:01:53 -0700  59) //)
7185358b9 (John Reiser             2006-07-15 20:05:41 -0700  60)         movl (ldst),%arg6l  // &outSize  XXX: 4GB
3843ec1e0 (John Reiser             2006-07-15 16:01:53 -0700  61)         movq dst,%arg5  // outp
3843ec1e0 (John Reiser             2006-07-15 16:01:53 -0700  62)         movq lsrc,%arg3  // inSize   *****
```
(Where I have annotated three lines with `*****`: the first and last lines for the bug, the middle line for the fix) it was 17 years ago on 2006-07-15.

**Comment by markus-oberhumer** [comment]
@jreiser 

1) looks like there is similar code in

amd64-darwin.dylib-entry.S
amd64-darwin.macho-entry.S
i386-linux.elf-so_entry.S

2) what about arm,arm64,mips,powerpc,powerpc64,etc? did you check these?
