### ISSUE TITLE
Failed to compress icon archive ; "mem_size 2; take care" and "object alignment too small"

### ISSUE THREAD

**Issue by xamidi** [upx/upx#718]
## What's the problem (or question)?
I created an .ico archive (DLL), and noticed that it can only be compressed (via `upx --brute ico.dll`) with old 32-bit UPX versions, and only when it contains `.reloc`.

- [ico-compressable-only-upx394w.dll](https://github.com/upx/upx/files/12840241/ico-compressable-only-upx394w.dll.zip) (1.38 MiB) was created with GConvert 5.2. (Named before I realized that UPX 3.95 32-bit also works.)
- [ico-uncompressable.dll](https://github.com/upx/upx/files/12840242/ico-uncompressable.dll.zip) (1.37 MiB) was created with ResourceHacker 5.2.1 (build 376).

`upx-4.1.0-win64` and `upx-4.1.0-win32`:
- `ico-compressable-only-upx394w.dll` failed with `CantPackException: mem_size 2; take care`.
- `ico-uncompressable.dll` started to compress, but failed at 4/4 with `CantPackException: object alignment too small`.

`upx-3.95-win64`:
- `ico-compressable-only-upx394w.dll` printed `File: ../../../src/packer.cpp, Line 1596 \n\nExpression: f_ptr + f_len <= i_ptr + i_len'` and **crashed** with `UPX executable packer has stopped working` pop-up.
- `ico-uncompressable.dll` failed with `CantPackException: filealign < 0x200 is not yet supported`.

`upx-3.95-win32`:
- `ico-compressable-only-upx394w.dll` **succeeded** and created [ico-compressed-by-upx-3.95-win32.dll](https://github.com/upx/upx/files/12840374/ico-compressed-by-upx-3.95-win32.dll.zip) (156 KiB) which works fine<sup>✻</sup> under Windows 7.
- `ico-uncompressable.dll` failed with `CantPackException: filealign < 0x200 is not yet supported`.

`upx394w`:
- `ico-compressable-only-upx394w.dll` **succeeded** and created [ico-compressed-by-upx394w.dll](https://github.com/upx/upx/files/12840268/ico-compressed-by-upx394w.dll.zip) (156 KiB) which works fine<sup>✻</sup> under Windows 7.
- `ico-uncompressable.dll` failed with `CantPackException: filealign < 0x200 is not yet supported`.

<sup>✻</sup><sub>When setting icons manually via editing files; `Properties -> Customize -> Change Icon...` won't show the icons of a compressed icon archive.</sub>

## What should have happened?
I suspect it should've worked in later versions since it worked in earlier versions.
Also I do not see an issue with compressing a DLL without `.reloc` that is essentially just an archive of images, so that should probably work, too.

## Do you have an idea for a solution?
Take the old 32-bit versions as good examples.

## How can we reproduce the issue?

1. Download the (linked) uncompressed DLL files.
2. Use `upx --brute <DLL name>` with the given UPX versions on the two DLLs.

## Please tell us details about your environment.
* UPX version used (`upx --version`):
   1. upx 4.1.0 [both 32- and 64-bit]
      NRV data compression library 0.84
      UCL data compression library 1.03
      zlib data compression library 1.2.13.1-motley
      LZMA SDK version 4.43
   2. upx 3.95 [both 32- and 64-bit]
      NRV data compression library 0.84
      UCL data compression library 1.03
      zlib data compression library 1.2.3
      LZMA SDK version 4.43
   3. upx 3.94 [32-bit]
      NRV data compression library 0.84
      UCL data compression library 1.03
      zlib data compression library 1.2.3
      LZMA SDK version 4.43

* Host Operating System and version:
  - Windows 7 Ultimate (SP1) 64-bit
* Host CPU architecture:
  - x86-64
* Target Operating System and version:
  - Windows NT
* Target CPU architecture:
  - 32-bit ICL
  - `PE32 executable (DLL) (GUI) Intel 80386, for MS Windows`, for `ico-compressable-only-upx394w.dll` ([VirusTotal](https://www.virustotal.com/gui/file/e6337ad6f8994a473459957fafc0d720ff2b41438b7ffe7a816acaa1f3859eac/details))
  - `PE32 executable (DLL) (GUI) Intel 80386 (stripped to external PDB), for MS Windows`, for `ico-uncompressable.dll` ([VirusTotal](https://www.virustotal.com/gui/file/32e8163cf514f4080b2f967e665bdd1bfb45c5dc07628b163ce7e257ca25e8c9/details))

**Comment by jreiser** [comment]
`git bame pefile.h: 9da4f7a6d (Markus F.X.J. Oberhumer 2022-11-27 12:34:15 +0100 515)     struct alignas(1) pe_header_t {`

```
$ gdb --args upx -f -o foo ico-compressable-only-upx394w.dll
(gdb) b PeFile::pack0
(gdb) run
Breakpoint 1.1, PeFile::pack0<LE32, PeFile32::pe_header_t> (this=0x901760, fo=0x7fffffffd1d0, ih=..., oh=..., subsystem_mask=0x3c0c, 
    default_imagebase=0x400000, last_section_rsrc_only=0x0) at /home/jreiser/upx-devel4/src/pefile.cpp:2310

(gdb) p &ih
$3 = (PeFile32::pe_header_t *) 0x901b66
```
should be 4-byte aligned, but address ends in 6.

**Comment by markus-oberhumer** [comment]
First investigations:

`ico-uncompressable.dll` : The check for `filealign < 0x200` was removed in commit 222471744f6ee9623a629f4d1584d57b95f50571 by @kornelpal  , but there is given no further explanation so I'm assuming this now should be supported

**Comment by markus-oberhumer** [comment]
`ico-uncompressable.dll` has an invalid PE header. Devel branch gives better error message.

`ico-compressable-only-upx394w.dll` has invalid empty relocs. Devel branch ignores these, so this **might** work now.
