### ISSUE TITLE
Reference actions by commit SHA

### ISSUE THREAD

**Issue by gabibguti** [upx/upx#719]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

Actions referenced by tags and branches are more vulnerable to attacks, such as the tag being moved to a malicious commit or a malicious commit being pushed to the branch.

Although there are pros and cons for each reference, GitHub understands [using commit SHAs is more reliable](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-shas), specially for actions developed by other users such as `ilammy/msvc-dev-cmd@v1`, as does [Scorecard](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies) security tool.

## What should have happened?

Reference actions by commit SHA in GitHub workflows because they guarantee you are using an immutable version.

## Do you have an idea for a solution?

Replace, for example, `actions/checkout@v4` that is referenced by tag, to `actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 #v4.1.0`. The comment keeps the version readable and maintaince can be supported by Dependabot or Renovatebot.

## How can we reproduce the issue?

Not applicable.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

Not applicable.

**Comment by markus-oberhumer** [comment]
I've updated all third-party workflows to use SHA.
