### ISSUE TITLE
UPX rounds file modification time down to nearest second

### ISSUE THREAD

**Issue by PhilipRoman** [upx/upx#724]
## What's the problem (or question)?
By default UPX sets file modification time rounded down to nearest second.
This can break makefiles in subtle ways, as the file will appear older than it actually is.
It is not a serious issue, as I can work around by just using "touch", but still took me some time to figure out what is happening.

## What should have happened?
It probably shouldn't do that :) At least I don't see a good reason why

## Do you have an idea for a solution?
Modification time seems to be set using `utime` at `src/work.cpp:218`
I guess it could use an API which has higher resolution timing, such as `utimes` (microseconds) or `utimensat` (nanoseconds)
Both of these are defined in POSIX, so should be reasonably portable.
It is a drop in replacement, no other changes should be needed (st_atime and st_mtime should already support nanoseconds).
I would happily open a PR, but I'm not sure how your feature detection works, so leaving it up to you guys

## How can we reproduce the issue?

```
$ gcc tmp2.c -lexecinfo # any file works, ignore the "-lexecinfo"
$ stat a.out
  File: a.out
  Size: 100912          Blocks: 200        IO Block: 4096   regular file
Device: fd01h/64769d    Inode: 133675      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/   admin)   Gid: ( 1000/   admin)
Access: 2023-10-22 12:11:45.343396363 +0300
Modify: 2023-10-22 12:11:45.343396363 +0300
Change: 2023-10-22 12:11:45.343396363 +0300
$ upx a.out
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.2       Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 30th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    100912 ->     28248   27.99%   linux/amd64   a.out

Packed 1 file.
$ stat a.out
  File: a.out
  Size: 28248           Blocks: 56         IO Block: 4096   regular file
Device: fd01h/64769d    Inode: 132484      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/   admin)   Gid: ( 1000/   admin)
Access: 2023-10-22 12:11:45.000000000 +0300
Modify: 2023-10-22 12:11:45.000000000 +0300
Change: 2023-10-22 12:12:02.593482676 +0300

```

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.1.0
* Host Operating System and version: Alpine Linux, also happens on Artix Linux
* Host CPU architecture: x86_64
* Target Operating System and version: Same as host
* Target CPU architecture: Same as host

**Comment by markus-oberhumer** [comment]
This should be fixed in devel branch - please give it some testing.

**Comment by PhilipRoman** [comment]
Works good on my side, thanks for the quick response!
