### ISSUE TITLE
UPX v4.20 for Windows x86-32-bit on Windows XP SP3

### ISSUE THREAD

**Issue by LordGarfio** [upx/upx#726]
## What's the problem (or question)?

upx-4.2.0-win32 on Windows XP SP3, do not runs, it shows a system error message: "The system cannot execute the specified program". Its v4.1.0 runs fine.

## Please tell us details about your environment.

* UPX version 4.20
* Windows XP Home Edition SP3 (v5.1.2600).
* Intel x86 Family 6 Model 14 Stepping 8, GenuineIntel

Cheers.

**Comment by bitraid** [comment]
Does this build work for you: https://github.com/upx/upx/suites/17648947422/artifacts/1009186789

**Comment by peter8777555** [comment]
To bitraid :

This is for Vista.
Windows XP can not work.

**Comment by bitraid** [comment]
> To bitraid :
> 
> This is for Vista. Windows XP can not work.

Oh yeah, that's right...

**Comment by markus-oberhumer** [comment]
This is definitely unexpected - I'll have a look.

**Comment by markus-oberhumer** [comment]
BTW, does the DOS version work fine under XP?

**Comment by peter8777555** [comment]
To markus-oberhumer:

DOS ver:
DOS 7.10 : OK
Windows XP CMD : OK

**Comment by peter8777555** [comment]
To markus-oberhumer:

--lzma and --best do NOT work

I have try
V4.1.0 : --lzma and --best work
V4.2.0 : --lzma and --best do NOT work

Testing below:


F:\SEP_TempPass\2\f>UPX_V4_10w --lzma z3a.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1123328 ->    357888   31.86%    win32/pe     z3a.exe

Packed 1 file.

F:\SEP_TempPass\2\f>UPX_V4_20w --lzma z3b.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.2.0       Markus Oberhumer, Laszlo Molnar & John Reiser   Oct 26th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1123328 ->    542208   48.27%    win32/pe     z3b.exe

Packed 1 file.

--------------------------------------------------------------------------------------

F:\SEP_TempPass\2\f>UPX_V4_10w --best z3a.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1123328 ->    387584   34.50%    win32/pe     z3a.exe

Packed 1 file.

F:\SEP_TempPass\2\f>UPX_V4_20w --best z3b.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.2.0       Markus Oberhumer, Laszlo Molnar & John Reiser   Oct 26th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1123328 ->    568320   50.59%    win32/pe     z3b.exe

Packed 1 file.

**Comment by markus-oberhumer** [comment]
@peter8777555 I fear I don't get your `--lzma` bug report. Could you provide more details?

**Comment by peter8777555** [comment]
To markus-oberhumer:

Test Sample:
https://www.faststonesoft.net/DN/FSCapture102.zip

Test Ver:
UPX_V4_0_2w.exe
UPX_V4_1_0w.exe
UPX_V4_2_0w.exe

![z1](https://github.com/upx/upx/assets/29886853/9e7aaddd-41a7-4a31-8814-d88a88bd4f30)

![z2](https://github.com/upx/upx/assets/29886853/1e142886-9c8a-4645-bf16-826658ce934e)

**Comment by markus-oberhumer** [comment]
@peter8777555 Please open a new issue for this problem, thanks!

**Comment by markus-oberhumer** [comment]
Could you please test if/how these 4 binaries work on older Windows versions such as XP or even Windows 2000?

[upx-test-20231029.zip](https://github.com/upx/upx/files/13198441/upx-test-20231029.zip)

**Comment by peter8777555** [comment]
Option B works well.

![z222](https://github.com/upx/upx/assets/29886853/4a501bd2-79c4-408b-8840-cf7427675367)

**Comment by markus-oberhumer** [comment]
Great, so this is probably  the same `activeCodePage` problem as in issue https://github.com/upx/upx/issues/729

**Comment by peter8777555** [comment]
I test Chinese filename is OK on Windows XP.

**Comment by LordGarfio** [comment]
> Could you please test if/how these 4 binaries work on older Windows versions such as XP or even Windows 2000?
> 
> [upx-test-20231029.zip](https://github.com/upx/upx/files/13198441/upx-test-20231029.zip)

![upx-test-20231029](https://github.com/upx/upx/assets/65074751/e6ca7be4-88d8-43b5-b99a-75651d5218b2)

Above was tested UPX's 32-bit version only.

Test B runs.

**Comment by WAJIM-MMX** [comment]
> Could you please test if/how these 4 binaries work on older Windows versions such as XP or even Windows 2000?
> 
> [upx-test-20231029.zip](https://github.com/upx/upx/files/13198441/upx-test-20231029.zip)

XP x86 SP3:
upx_win32_test_a.exe - FAIL
upx_win32_test_b.exe - OK
![WXP-Error](https://github.com/upx/upx/assets/149331272/43ac2928-94dd-404f-ac92-2e5558cf8779)

XP x64 SP2:
upx_win32_test_a.exe - FAIL (same as on XP x86)
upx_win32_test_b.exe - OK
upx_win64_test_a.exe - FAIL (same as on XP x86)
upx_win64_test_b.exe - OK

W2K SP4:
upx_win32_test_a.exe - FAIL
upx_win32_test_b.exe - FAIL
![W2K-Error](https://github.com/upx/upx/assets/149331272/0f5c1f5f-ceee-4751-acbb-ef959e47e7b7)

Vista x86 SP2:
upx_win32_test_a.exe - OK
upx_win32_test_b.exe - OK

**Comment by markus-oberhumer** [comment]
Looks like this is the same `activeCodePage` problem as in issue  https://github.com/upx/upx/issues/729#issuecomment-1784181297  - see that link for some more info.

The next official release will revert that manifest change. In the meantime the DOS binary should work fine on older Windows versions.

Also it seems that Windows 2000 is just too old for modern Win32 C++ exception handling, so use the DOS version there as well.

Thanks to everyone!
