### ISSUE TITLE
UPX 4.2.0 with LOW packed rate

### ISSUE THREAD

**Issue by peter8777555** [upx/upx#728]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

UPX 4.2.0 with LOW packed rate

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.2.0
* Host Operating System and version: Windows 7 X64
* Host CPU architecture: Intel Q8400
* Target Operating System and version: Windows 7 X64
* Target CPU architecture:  Intel Q8400

Test Sample:
https://www.faststonesoft.net/DN/FSCapture102.zip

Test Ver:
UPX_V4_0_2w.exe
UPX_V4_1_0w.exe
UPX_V4_2_0w.exe

![z0](https://github.com/upx/upx/assets/29886853/63c423b0-95d1-472c-a844-a08a63868980)

![z1](https://github.com/upx/upx/assets/29886853/a6689f35-e8ce-4579-8d35-2b5b046f4c1c)

![z2](https://github.com/upx/upx/assets/29886853/faae79c1-9dfa-4a57-86c2-732a3372e466)

**Comment by markus-oberhumer** [comment]
Fixed in devel branch commit https://github.com/upx/upx/commit/19c6b969ab4839448ddda0b4badf48de891871a2 . Thanks!

**Comment by peter8777555** [comment]
Test 19c6b96 OK.
Thank you.
