### ISSUE TITLE
UPX 4.2.0 can NOT pack Chinese filename on Windows 11

### ISSUE THREAD

**Issue by peter8777555** [upx/upx#729]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

UPX 4.2.0 can NOT pack Chinese filename on Windows 11

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.2.0
* Host Operating System and version: Windows 11 X64 Chinese Edtion
* Host CPU architecture: Intel Q8400
* Target Operating System and version: Windows 11 X64 Chinese Edtion
* Target CPU architecture: Intel Q8400

Test Sample:
See attached file.

Test Ver:
UPX_V4_0_2w.exe
UPX_V4_1_0w.exe
UPX_V4_2_0w.exe

![z5](https://github.com/upx/upx/assets/29886853/3655d276-6d8e-4f75-ba95-ee792ff29620)

[這是一個測試_V4_0_2.zip](https://github.com/upx/upx/files/13197860/_V4_0_2.zip)

**Comment by markus-oberhumer** [comment]
Could you please test if/how these 4 binaries work with Chinese filenames?

[upx-test-20231029.zip](https://github.com/upx/upx/files/13198441/upx-test-20231029.zip)

**Comment by peter8777555** [comment]
Option B work well.

![zzz1](https://github.com/upx/upx/assets/29886853/78474cd9-8b08-4675-9729-7d8db74a359b)

**Comment by markus-oberhumer** [comment]
Great, thanks!

**Comment by markus-oberhumer** [comment]
The cause behind this problem is that the v4.2.0 official build was changed to use this manifest entry:

```
 <application>
   <windowsSettings>
     <activeCodePage xmlns="http://schemas.microsoft.com/SMI/2019/WindowsSettings">UTF-8</activeCodePage>
   </windowsSettings>
 </application>
```


I think I somewhere read that UTF-8 should be enabled by default, but obviously this was not a good idea.

**Comment by peter8777555** [comment]
I think CJK(Chinese/Japanese/Korean) will have this problem.

**Comment by markus-oberhumer** [comment]
The next official release will revert that manifest change. Thanks!

**Comment by httpsColon** [comment]
谢谢你，湾友，我今天也发现了，准备提交来着

**Comment by peter8777555** [comment]
To httpsColon:
兄弟 平安喜樂,
還有 低壓縮率 還沒解決,
我已發帖.
