### ISSUE TITLE
Apache mod_ssl.so can't be decompressed after compressing anymore

### ISSUE THREAD

**Issue by pwallner** [upx/upx#73]
## What's the problem (or question)?
Compiled UPX from source, compressed "so" file doesn't expand anymore (upx 3.94-git-483db31acd0a+)

## What should have happened?
upx should decompress

## Do you have an idea for a solution?
sorry no...

## How can we reproduce the issue?
I used from apache the mod_ssl.so with following steps (orginal file and compressed file which cannot be decompressed anymore are attached - _**please rename *.txt to *.zip because I can't upload zip files**_):
```
root@dm900:/media/usb# upx --lzma mod_ssl.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX git-483db3+ Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 30th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    187892 ->    121052   64.43%    linux/arm    mod_ssl.so

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
root@dm900:/media/usb# upx -d mod_ssl.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX git-483db3+ Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 30th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: mod_ssl.so: CantUnpackException: corrupt b_info

Unpacked 1 file: 0 ok, 1 error.

WARNING: this is an unstable beta version - use for testing only! Really.
```

## Please tell us details about your environment.
* UPX version used (`upx --version`): 
upx 3.94-git-483db31acd0a+
UCL data compression library 1.03
zlib data compression library 1.2.8
LZMA SDK version 4.43

* Operating System and version: DreamOS 2.5, 4.3.0r26-2017-01-10
* CPU architecture: Dual-Core 12K DMIPS (armv7l)

[mod_ssl.txt](https://github.com/upx/upx/files/841294/mod_ssl.txt)

**Comment by jreiser** [comment]
Thank you for the testcase!
