### ISSUE TITLE
Please consider removing `-Werror=cast-align` while building upx

### ISSUE THREAD

**Issue by moui0** [upx/upx#730]
## What's the problem (or question)?

I'm trying to build upx on RISC-V 64, and I got some error messages like this:
```
In file included from /build/upx/src/upx/src/check/../util/xspan_impl_ptr_or_null.h:48,
                 from /build/upx/src/upx/src/check/../util/xspan_impl.h:249,
                 from /build/upx/src/upx/src/check/../util/xspan.h:51,
                 from /build/upx/src/upx/src/check/../conf.h:798,
                 from /build/upx/src/upx/src/check/dt_xspan.cpp:29:
/build/upx/src/upx/src/check/../util/xspan_impl_common.h: In instantiation of ‘XSpan::PtrOrSpanOrNull<U> XSpan::PtrOrSpanOrNull<T>::type_cast() const [with U = short unsigned int; T = char]’:
/build/upx/src/upx/src/check/dt_xspan.cpp:118:38:   required from here
/build/upx/src/upx/src/check/../util/xspan_impl_common.h:287:32: error: cast from ‘XSpan::PtrOrSpanOrNull<char>::pointer’ {aka ‘char*’} to ‘rpointer’ {aka ‘short unsigned int*’} increases required alignment of target type [-Werror=cast-align]
  287 |         return R(R::Unchecked, reinterpret_cast<rpointer>(ptr), size_in_bytes,
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/upx/src/upx/src/check/../util/xspan_impl_common.h:288:18: error: cast from ‘XSpan::PtrOrSpanOrNull<char>::pointer’ {aka ‘char*’} to ‘rpointer’ {aka ‘short unsigned int*’} increases required alignment of target type [-Werror=cast-align]
  288 |                  reinterpret_cast<rpointer>(base));
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
(Full log at [here](https://[archriscv.felixc.at/.status/log.htm?url=logs/upx/upx-4.2.0-1.log](https://archriscv.felixc.at/.status/log.htm?url=logs/upx/upx-4.2.0-1.log)))

This is because the code performs a cast from a type with a lower alignment to a type with a higher alignment. The warning/error will never be emitted when compiling for x86-64, but the behavior is different in RISC-V.

## What should have happened?

The error should not appear.

I investigated the code and noticed that this part of the test code was actually aligned. However, the compiler simply outputs an error message when it realizes that the alignment has increased.

https://github.com/upx/upx/blob/cd1df6f6b15110ba2c7b560be94e947c10950e4e/src/check/dt_xspan.cpp#L67
https://github.com/upx/upx/blob/cd1df6f6b15110ba2c7b560be94e947c10950e4e/src/check/dt_xspan.cpp#L75-L77
https://github.com/upx/upx/blob/cd1df6f6b15110ba2c7b560be94e947c10950e4e/src/check/dt_xspan.cpp#L118-L120

## Do you have an idea for a solution?

In general, there are two ways to solve the cast-align problem:
1. Remove `-Werror=cast-align` or add `-Wno-error=cast-align` while building.
2. Use `memcpy` instead of typecasting.

But considering that the intent of this part of the code is to test xspan-related code, I think the first approach should be taken.

## How can we reproduce the issue?

1. Install `riscv-gnu-toolchain`
2. `CC=riscv64-linux-gnu-gcc CXX=riscv64-linux-gnu-g++ make`

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.2.0
* Host Operating System and version: Arch Linux (Kernel: 6.5.9-arch2-1)
* Host CPU architecture: x86_64
* Target Operating System and version: None
* Target CPU architecture: None

**Comment by markus-oberhumer** [comment]
I had thought that `reinterpret_cast` automatically disables -Wcast-align warnings - at least clang does this.

Which compiler are you using?

**Comment by moui0** [comment]
riscv64-linux-gnu-g++ 12.2.0

**Comment by markus-oberhumer** [comment]
Thanks, I'll have a look.

In any case `-Werror` will remain the default for Git developer builds; quoting from CMakeLists.txt:

```
# warnings are fatal errors; annoy developers to keep the source code warning-free
```

**Comment by markus-oberhumer** [comment]
Should be fixed in devel branch commit https://github.com/upx/upx/commit/38a676f6f78e82ca0c2f08ef16446bc3e66cd453

**Comment by jreiser** [comment]
> ```
> # warnings are fatal errors; annoy developers to keep the source code warning-free
> ```
One result of this is an impediment to development, because MSVC++ is not such a good compiler.  `git log | grep MSVC` shows several dozen instances.  A few of them were corrections for coding errors, but many more are just Windows-isms, pettiness, or outright compiler errors.  The world would be a better place without MSVC++; use `clang++` instead.

**Comment by markus-oberhumer** [comment]
MSVC has **much** improved in the recent years, but yes, like every compiler it has its own set of annoying warnings.

The main inconvenience is that I cannot test it locally and it only shows up in CI builds -  that's why I'm using the `test-misc` branch for temporary commits, and then do a `git rebase -i` as needed.

**Comment by markus-oberhumer** [comment]
@moui0 

Looking at https://gitlab.archlinux.org/archlinux/packaging/packages/upx.git , it seems the main "problem" is that Arch prefers building from Git instead of using our source code tarball release - which then enables the strict Git developer options.

IMO Arch should thus enable all of UPX_CONFIG_DISABLE_GITREV, UPX_CONFIG_DISABLE_SANITIZE and UPX_CONFIG_DISABLE_WERROR .

See https://github.com/upx/upx/blob/devel/CMakeLists.txt

**Comment by markus-oberhumer** [comment]
@moui0 

Also it seems that the Arch build is currently **not** running `make test` / `ctest`.

In any case you will need to enable `UPX_CONFIG_DISABLE_SELF_PACK_TEST` on riscv (and all other platforms that are not supported by UPX).

**Comment by moui0** [comment]
Thanks for your guidance. I didn't notice that before.

I'll report your advice to Arch Linux.
