### ISSUE TITLE
Fuzzers development

### ISSUE THREAD

**Issue by MykolaMykhno** [upx/upx#733]
Hi, I'm Mykola Mykhno, developing fuzzers for oss-fuzz.

## What's the problem (or question)?
Where do you want to put fuzzers and seed corpus? Fuzzers can be placed in the oss fuzz repo in the project directory, but seed corpuses must be placed elsewhere.

## What should have happened?
Fuzzers and seed corpuses must be stored in some place.

## Do you have an idea for a solution?
I could place fuzzers in oss-fuzz repo at project directory, and fuzzers in `tests` directory. Or I could create directory `oss-fuzz` in this repo, and store fuzzers and seed corpuses here.

## How can we reproduce the issue?
-

## Please tell us details about your environment.
* UPX version used (`upx --version`): upx 4.2.0
* Host Operating System and version: ubuntu:20.04
* Host CPU architecture: x86_64
* Target Operating System and version: ubuntu:20.04
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
About how many files, how much space, what distribution of file sizes, what frequency of updates/re-orgs, etc.?

**Comment by jreiser** [comment]
@MykolaMykhno  Please provide some context about your involvement with UPX.  Are you an individual acting for yourself, or are you part of an organized or semi-organized group?  What is the goal that you seek?

In general, fuzzing the compression side of UPX tends to result in mere curiosities that have little or no security impact. A developer who uses UPX in order to reduce the space required to store or transmit an app is highly likely to attempt compression of an executable file which has a valid format.  A bug which is triggered by an invalid format tends to be equivalent to a poor error message from the UPX compressor, which is a kind of "compiler".  Such a bug does get fixed, but it is basically considered to be a "nuisance."

In contrast, a bug in the de-compression side of UPX gets significant attention because of the possibility that it may be a symptom a successful attempt (or possibly-successful attempt) to use the compression of UPX in order to hide malware inside an executable file.  Security-scanning software relies on de-compression (`upx -d`) to reveal the true de-compressed contents that will be executed, so that the scanner can analyze the software in order to detect malware.  The ability to fool the UPX de-compressor might provide a means to fool the security scanner into not detecting malware that is present  The likely administrative result would be a ban  on the use of UPX.

**Comment by MykolaMykhno** [comment]
I'm Mykola Mykhno from Leviathan Security Group, I'm working on ISE project and my goal is to develop fuzzers for oss-fuzz which will respond to requirements from attack surface analysis document.

At this moment I can say that seed corpuses it would be several files at this moment 5 files which would be placed once and after it wouldn't change frequently. Seed corpuses must be placed somewhere outside oss-fuzz repo, it could be your main repo, or other your repo for example test, or I can use test files from your test repo as seed corpuses. 

About fuzzers, they also wouldn't change often, but they can be placed in oss-fuzz repo. In case if it would be placed in your repo, I would have to follow your code style and you would have to review fuzzers. In other case, review process and style would be reviewed by someone from oss-fuzz project.

**Comment by markus-oberhumer** [comment]
Well, if you want to work on this I'd suggest that you use your own UPX fork for the time being.

**Comment by markus-oberhumer** [comment]
I'm closing this for now, but this issue can get reopened later.

Please report back if you find problems or want to get some support code merged.

**Comment by MykolaMykhno** [comment]
Hello, @markus-oberhumer @jreiser , I have created PR to test suite with seed corpuses for fuzzers: https://github.com/upx/upx-testsuite/pull/3. I have created PR to first version because in description of second mentioned that second test suite for ELF files, and I have not only ELF executables.

Also I need your contact email which also must have google account, to make possible for you recieving fuzzing notifications and getting crash test cases.

**Comment by markus-oberhumer** [comment]
Please rename this new testsuite to `upx-testsuite-v3` and start fuzzing with your own forks for the time being.

Also, please document the LICENSE of those new test files.

**Comment by jreiser** [comment]
I'm not sure about a couple items:

> ... because in description of second mentioned that second test suite for ELF files, and I have not only ELF executables.

What does this mean?  In particular: ` I have not only ELF executables.`  Does this mean that there are other file types besides ELF executables?  That's OK, I guess.  Providing some descriptive context about the files and directories would help make better communication.

> Also I need your contact email which also must have google account, to make possible for you recieving fuzzing notifications and getting crash test cases.

Please explain `which also must have google account`.  Does this mean that I must have an email address `@gmail.com`?  Why?  And what is the problem with using "ordinary" email, or using Comments to an Issue here at https://github.com/upx/upx/issues/733 etc.?  An inspection of any `git log` entry for a commit that I made will show an email address for me.  Also, [almost] any copyright notice at the beginning of a `upx/src/...` file will show an [indirect] email address for me.

**Comment by MykolaMykhno** [comment]
> Please rename this new testsuite to `upx-testsuite-v3` and start fuzzing with your own forks for the time being.
> 
> Also, please document the LICENSE of those new test files.

Okay, thank you

**Comment by MykolaMykhno** [comment]
> I'm not sure about a couple items:
> 
> > ... because in description of second mentioned that second test suite for ELF files, and I have not only ELF executables.
> 
> What does this mean? In particular: ` I have not only ELF executables.` Does this mean that there are other file types besides ELF executables? That's OK, I guess. Providing some descriptive context about the files and directories would help make better communication.

Yes, I mean seed corpuses are also other executable file types, for example PE and Mach-O files. These executable files are packed version of basic `hello world` program built for different architectures and OS. And I will create `upx-testsuite-v3` for the purpose of storing seed corpuses at this moment. Thank you.

> > Also I need your contact email which also must have google account, to make possible for you recieving fuzzing notifications and getting crash test cases.
> 
> Please explain `which also must have google account`. Does this mean that I must have an email address `@gmail.com`? Why? And what is the problem with using "ordinary" email, or using Comments to an Issue here at #733 etc.? An inspection of any `git log` entry for a commit that I made will show an email address for me. Also, [almost] any copyright notice at the beginning of a `upx/src/...` file will show an [indirect] email address for me.

Based on documentation of [oss-fuzz](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#primary) you need have google account for contact email, because test cases stored at `GCP Storage bucket`. If your contact email also have access to GCP so I would be able to use it.
