### ISSUE TITLE
Cannot open swap file c:\cwsdpmi.swp

### ISSUE THREAD

**Issue by 3FLLC** [upx/upx#736]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by markus-oberhumer** [comment]
LOL. This error means that the DOS version has run out of physical memory.

Install more RAM or add a hard disk C: to enable swapping.
