### ISSUE TITLE
UnknownExecutableFormatException when pack android armv7/x86 golang generated so file. 

### ISSUE THREAD

**Issue by bronze1man** [upx/upx#74]
## What's the problem (or question)?
Upx can not compress golang1.7.5 android armv7a so file,and get an UnknownExecutableFormatException error
It also can not compress golang1.7.5 android x86 so file,and get an UnknownExecutableFormatException.

## What should have happened?
It should compress those so files.

## Do you have an idea for a solution?
No.

## How can we reproduce the issue?

1.unzip the file in next comment
2.upx jni/armeabi-v7a/libgojni.so
3.upx jni/x86/libgojni.so

## Please tell us details about your environment.

* UPX version used (`upx --version`):
~/work/FastLemonFree > upx --version
upx 3.93
UCL data compression library 1.03
zlib data compression library 1.2.5
LZMA SDK version 4.43
Copyright (C) 1996-2017 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2017 Laszlo Molnar
Copyright (C) 2000-2017 John F. Reiser
Copyright (C) 2002-2017 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.

* Operating System and version:
os x 10.11.6 
* CPU architecture:
host is amd64,target is armv7a and x86

**Comment by bronze1man** [comment]
[jni.zip](https://github.com/upx/upx/files/850424/jni.zip)

**Comment by markus-oberhumer** [comment]
I don't think we support shared libraries on Android yet.

**Comment by jreiser** [comment]
Those two .so files have no DT_INIT in their PT_DYNAMIC segment, which is why UPX does not consider them eligible to be compressed. However, they do have DT_INIT_ARRAY, which is similar.  So this is an enhancement, although in some ways a needless complication.

**Comment by bronze1man** [comment]
@jreiser looks like the message of that error is not accurate.
I will try to add DT_INIT into that library.

ps: why not just add a DT_INIT segment into that .so files?

**Comment by bronze1man** [comment]
I found a workaround to finish my job:
add `void _init(void){}` to a .c file

Upx can be easier to use.

http://www.cnblogs.com/fishou/p/4202061.html

![image](https://cloud.githubusercontent.com/assets/1107541/24086942/2113b338-0d53-11e7-8809-2bf16b95c770.png)

**Comment by jreiser** [comment]
```
ps: why not upx just add a DT_INIT segment into those .so files?
```
 @bronze1man Because adding DT_INIT would increase the size of the existing PT_DYNAMIC.  Thus the PT_DYNAMIC would have to move somewhere else, and this is quite cumbersome to accomplish.  I consider the UnknownFormatException complaint to be accurate: a .so which does not have a DT_INIT fails to meet the existing requirements for the format of a file that current UPX knows how to process.

**Comment by bronze1man** [comment]
@jreiser
I think you should print a message like:
```
This binary do not have DT_INIT segment, UPX do not know how to process. You can try add follow code to your .c file:
void _init(void){}
```

Then The user will try to add a DT_INIT segment to origin .so file. And bypass this limit.
UnknownFormatException just make people come to here. 😝
