### ISSUE TITLE
UPX corrupts exports on EXE files

### ISSUE THREAD

**Issue by anthonyshibitov** [upx/upx#742]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
An EXE with exports once packed has a corrupted export section filled with invalid values.

## What should have happened?
The packed file should have values in the export table indicating that there are no exports.

## Do you have an idea for a solution?
It appears UPX doesn't cause any issues to the exports when packing a DLL. Perhaps use this code for EXEs as well?

## How can we reproduce the issue?

1. Pack an EXE file with exports
2. Inspect packed EXE exports

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94
* Host Operating System and version: Windows 11
* Host CPU architecture: x64
* Target Operating System and version: Windows 11
* Target CPU architecture: x64

Exports from packed file as viewed in PE-bear
![image](https://github.com/upx/upx/assets/21368773/e5dc9717-2e9c-4db1-b86d-1e1ce7759b7e)

Exports from unpacked file as viewed in PE-bear
![image](https://github.com/upx/upx/assets/21368773/f8fe38b0-c0c7-4891-b1bb-54b3ed751b22)

**Comment by ml1050** [comment]
The export data will be correctly in its place after the decompression is finished. If you do not like that just use --compress-exports=0.

**Comment by anthonyshibitov** [comment]
> The export data will be correctly in its place after the decompression is finished. If you do not like that just use --compress-exports=0.

Is the packed export table being filled with invalid values an intentional output/desired behavior? If not, I would consider this a bug.

**Comment by jreiser** [comment]
The packed export table is ...`packed`.  The only things that matter are that it is smaller than the original, and that **after** decompression it has a layout and values that are acceptable to the dynamic linking handler of the OS and associated runtime support software.  For any other inspection, then use `--compress-exports=0` for compression, or `upx -d` for decompression.
