### ISSUE TITLE
Compressed arm64 segfaults when more than 500 environment variables are set

### ISSUE THREAD

**Issue by jordiclariana** [upx/upx#743]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

When running a compressed arm64 application while there are more than 500 environment variables the application segfaults.

## What should have happened?

The application should run normally, having access to all set environment variables.

## Do you have an idea for a solution?

Not really.

## How can we reproduce the issue?

1. Given the following program `main.go`:
```
package main

import (
	"fmt"
)

func main() {
  fmt.Print("Executed\n")
}
```
2. Compile with:
```
GOARCH=arm64 GOOS=linux go build -ldflags "-s -w" -o "/tmp/test" main.go
```
3. Compressed it with:
```
upx -o /tmp/test.upx /tmp/test
```
4. Run this script
```
env -i bash -c 'for i in {1..500}; do export ENVVAR_$i="x"; done; /tmp/test.upx'
```
> The `env -i` ensures the bash subshell will have no env vars. Then the `for` loop will create (and export) 500 env vars.
5. The program will fail with the following output:
```
fatal error: failed to get system page size
runtime: panic before malloc heap initialized

runtime stack:
runtime.throw({0xac790?, 0x0?})
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/panic.go:1077 +0x40 fp=0xffffe4c15e10 sp=0xffffe4c15de0 pc=0x408a0
runtime.mallocinit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/malloc.go:389 +0x2c0 fp=0xffffe4c15e50 sp=0xffffe4c15e10 pc=0x1a2b0
runtime.schedinit()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/proc.go:726 +0x9c fp=0xffffe4c15ea0 sp=0xffffe4c15e50 pc=0x441dc
runtime.rt0_go()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:86 +0xa4 fp=0xffffe4c15ed0 sp=0xffffe4c15ea0 pc=0x6b5f4
```

The result is the same for a C program, or any other language for that matter, just the output is different depending on how that specific language handles/reports segmentation faults.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
```
upx 4.2.1
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.3.0.1-motley
LZMA SDK version 4.43
Copyright (C) 1996-2023 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2023 Laszlo Molnar
Copyright (C) 2000-2023 John F. Reiser
Copyright (C) 2002-2023 Jens Medoch
Copyright (C) 1995-2023 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```
* Host Operating System and version:
```
Linux test 6.5.11-linuxkit #1 SMP PREEMPT Mon Dec  4 11:30:00 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```
* Host CPU architecture: arm64
* Target Operating System and version: Ubuntu 23.10, Alpine (latest) on Docker, etc
* Target CPU architecture: aarch64

**Comment by markus-oberhumer** [comment]
Confirmed. I've also tested all other archs, but only `arm64` is affected.
