### ISSUE TITLE
--unmap-all-pages seems not effective any more

### ISSUE THREAD

**Issue by Jackyxty** [upx/upx#749]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

I would like to unmap all initial packer pages and found the compress option `--unmap-all-pages` from docs.
I tried the latest version 4.x and there is always one crumb page left in the memory, with or without this option.

## What should have happened?

With this option enabled, all initial pages should be unmapped from memory.

## Do you have an idea for a solution?

Seems introduced from this commit: https://github.com/upx/upx/commit/491e8640b2c862c10fa127a12eed8a983c6c6361#diff-797fc339c131c779bf2d76001faf7bb0831513cb6fd2e76879d49cd8b011a433R519
Don't know if it was expected

## How can we reproduce the issue?

```
1. upx --unmap-all-pages elffile
2. ./elffile
3. cat /proc/`pidof elffile`/maps
4. You can notice the page left (just below the [stack])
```

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.2.1
* Host Operating System and version: Linux, Ubuntu 22.04
* Host CPU architecture: x86_64
* Target Operating System and version: Linux, Ubuntu 22.04
* Target CPU architecture: x86_64

**Comment by markus-oberhumer** [comment]
I recall some discussion, but @jreiser should know if this is indeed intended

**Comment by jreiser** [comment]
It's a "nuisance" feature that was added when some [one!] user complained that /proc/self/exe didn't "work" for a compressed executable.  This was in the days when /proc was still considered to be optional because of the code space cost to the Linux kernel.  (It costs ~200 bytes in each UPX runtime de-compression stub.) Now RAM is "cheap" (new laptops have at least 8GB, RaspberryPi often has >=1GB) and /proc is essentially required due to evolution (systemd, etc.)

The UPX option can be restored without too much effort.  It's on the list: a few weeks away?

**Comment by markus-oberhumer** [comment]
Is there a valid use case for this option? I'd rather remove the option.

**Comment by Jackyxty** [comment]
> Is there a valid use case for this option? I'd rather remove the option.

Hi! Thanks for the reply.

For a specific use case, I would like to use `prctl(PR_SET_MM, PR_SET_MM_EXE_FILE, ...)` to set `/proc/self/exe` to another file. Yet it requires all the initial memory map of the ELF to be unmapped first. In `man prctl` it says
>To change the symbolic link, one needs to unmap all existing executable memory areas, including those created by the kernel itself (for example the kernel usually creates at least one executable memory area for the ELF .text section).

It's not easy for an ordinary ELF to unmap all the initial pages. Then I came up with using UPX and find the `--unmap-all-pages` option.
It would be really appreciated if this option can be restored. Thanks!

**Comment by Jackyxty** [comment]
Hi, any update here?

still looking forward to use this feature

**Comment by jreiser** [comment]
@Jackyxty In addition to an extra mapping of the first page of /proc/self/exe, currently the upx run-time de-compression stub adds an environment variable whose name is `   ` (three spaces) and whose value is`(readlink "/proc/self/exe")`.   Discuss.

**Comment by Jackyxty** [comment]
The env var is OK for me. Keeping or removing it as you wish.

I would just like to use the compress time option `--unmap-all-pages`, to make upx NOT keeping the extra mapping of the first page of /proc/self/exe.
