### ISSUE TITLE
UPX package removed from Debian 12 around 2023-05-11

### ISSUE THREAD

**Issue by dtoubelis** [upx/upx#755]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

I've upgraded my build environment to Debian 12 and upx-ucl package is no longer there.
I traced this problem down to this - https://tracker.debian.org/news/1430936/upx-ucl-removed-from-testing/,
so it appears the package failed to build and was automatically excluded. 

## What should have happened?

The package should remain in the distribution. Our build tools depend on it.

## Do you have an idea for a solution?

Somebody needs to coordinate with Debian maintainers to resolve the packaging issue.

## How can we reproduce the issue?

1. Install Debian 12
2. apt search upx-ucl

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version: Debian 12
* Target CPU architecture: amd64

**Comment by boretom** [comment]
@dtoubelis I got the same issue and compiled an older version (v4.0.2) myself. At least that worked without a problem.

And as an alternative I did also installed the Ubuntu [jammy (22.04LTS)](https://packages.ubuntu.com/jammy/) packages (upx version 3.96) which did work too: 

- [libucl1](https://packages.ubuntu.com/jammy/libucl1)
- [upx](https://packages.ubuntu.com/jammy/upx-ucl)

**Comment by markus-oberhumer** [comment]
Some options:
- complain at Debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025053
- download and use our pre-compiled binary https://github.com/upx/upx/releases/latest
- build from source code
- switch to another distribution https://repology.org/project/upx/history

This is obviously not an UPX issue, closing.
