### ISSUE TITLE
IPv6 enabled source code mirror

### ISSUE THREAD

**Issue by boretom** [upx/upx#756]
## What's the problem (or question)?
Since UPX is hosted on github the repo can't be accessed by IPv6. I use IPv6-only server for cost reasons for compiling projects when I'm on the road.

## What should have happened?
It would be very nice to have UPX and the dependent submodules be mirrored to some IPv6 enabled provider. Including automatic patching of the '.gitmodules'after mirroring.

## Do you have an idea for a solution?
Gitlab or Codeberg come to mind as provider with IPv6 support. Gitlab got a 'Mirror' functionality.

## How can we reproduce the issue?

1. Setup an IPv6 only computer or server
2. run `git clone https://github.com/upx/upx.git upx-github`
3. Watch it fail 

```
Cloning into 'upx-github'...
fatal: unable to access 'https://github.com/upx/upx.git/': Failed to connect to github.com port 443 after 15 ms: Couldn't connect to server
```

## Please tell us details about your environment.

* latest git commit
* Debian 12 
* AMD64
* Debian 12
* AMD 12

Of course that is a very low-prio issue but it would be nice to have a solution anyway.

**Comment by markus-oberhumer** [comment]
Some options:
- complain at GitHub / Microsoft.
- set up your own mirror

**Comment by boretom** [comment]
> Some options:
> 
>     * complain at GitHub / Microsoft.

Sure, nobody tried that before :/

But ok I'll set it up myself

**Comment by markus-oberhumer** [comment]
Well, I think you should complain even if the chance of getting heard is low.

Still, I wonder about the actual motivation of GitHub of not enabling IPv6. Better user tracking?

**Comment by boretom** [comment]
The discussion about IPv6 and Github goes one for a few years already. I don't think they would admit that the reason is better user tracking :).

The have enabled IPv6 for *.github.io (but not for github.io) so the UPX homepage is reachable via IPv6. I don't remember when but they did enable IPv6 once for a short moment and it did seem to lead to some problems and they turned it off again.

But you're right I gotta complain. It's to assume that's a resource topic and the lack of need for IPv6.

I set up a pipline yesterday on Gitlab to mirror UPX and the vendor modules, that works. Now with a local git hook it will work excellent.
