### ISSUE TITLE
upx v4.2.2 amd64 on ubuntu 20.04  run failed

### ISSUE THREAD

**Issue by senryzou** [upx/upx#757]
steps
1. wget https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-amd64_linux.tar.xz
2. tar -xf  upx-4.2.2-amd64_linux.tar.xz
3. cd upx-4.2.2-amd64_linux
4. ./upx --help
```
 ./upx --help
Killed
```
no this issue for 4.2.1
```
 cd ../upx-4.2.1-amd64_linux/
./upx --help
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.2.1       Markus Oberhumer, Laszlo Molnar & John Reiser    Nov 1st 2023

Usage: upx [-123456789dlthVL] [-qvfk] [-o file] file..
...
```

**Comment by senryzou** [comment]
OS version
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

**Comment by jreiser** [comment]
Works on Fedora 38:
```
$ wget https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-amd64_linux.tar.xz
$ xzcat upx-4.2.2-amd64_linux.tar.xz  |  tar -xf -
$ cd upx-4.2.2-amd64_linux
$ sha256sum ./upx
e0dff9d826f017f0f55c2c6e07888d4f22e2bafc36bd820b1966ddab7d73e012  ./upx
$ ./upx --help
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX 4.2.2       Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 3rd 2024

Usage: upx [-123456789dlthVL] [-qvfk] [-o file] file..

Commands:
  -1     compress faster                   -9    compress better
   <<SNIP>>
    powerpc64le-linux.kernel.vmlinux     vmlinux/ppc64le

UPX comes with ABSOLUTELY NO WARRANTY; for details visit https://upx.github.io
$ 
```
So it's time to try on Ubuntu.
Also works with `sudo /sbin/setenforce Enforcing`, so SELinux is not the immediate problem.

**Comment by senryzou** [comment]
work well on Red Hat Enterprise Linux release 8.8 (Ootpa)
```
cat /etc/redhat-release
Red Hat Enterprise Linux release 8.8 (Ootpa)
 wget https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-amd64_linux.tar.xz
tar -xf upx-4.2.2-amd64_linux.tar.xz
cd upx-4.2.2-amd64_linux

 ls
COPYING  LICENSE  NEWS  README  THANKS.txt  upx  upx-doc.html  upx-doc.txt  upx.1

./upx --help
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX 4.2.2       Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 3rd 2024

Usage: upx [-123456789dlthVL] [-qvfk] [-o file] file..

```

**Comment by senryzou** [comment]
Failed after multiple executions on  Red Hat Enterprise Linux release 8.8 (Ootpa)
```
 ./upx --help
Killed
```

**Comment by senryzou** [comment]
> Works on Fedora 38:
> 
> ```
> $ wget https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-amd64_linux.tar.xz
> $ xzcat upx-4.2.2-amd64_linux.tar.xz  |  tar -xf -
> $ cd upx-4.2.2-amd64_linux
> $ sha256sum ./upx
> e0dff9d826f017f0f55c2c6e07888d4f22e2bafc36bd820b1966ddab7d73e012  ./upx
> $ ./upx --help
>                        Ultimate Packer for eXecutables
>                           Copyright (C) 1996 - 2024
> UPX 4.2.2       Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 3rd 2024
> 
> Usage: upx [-123456789dlthVL] [-qvfk] [-o file] file..
> 
> Commands:
>   -1     compress faster                   -9    compress better
>    <<SNIP>>
>     powerpc64le-linux.kernel.vmlinux     vmlinux/ppc64le
> 
> UPX comes with ABSOLUTELY NO WARRANTY; for details visit https://upx.github.io
> $ 
> ```
> 
> So it's time to try on Ubuntu. Also works with `sudo /sbin/setenforce Enforcing`, so SELinux is not the immediate problem.

Please help execute multiple times to see if it has failed

**Comment by markus-oberhumer** [comment]
@senryzou Can you test if you also experience crashes with the **unpacked** upx executable?

**Comment by jreiser** [comment]
It works for me on Ubuntu 20.04.6 LTS (Live Desktop) which is what is available from https://releases.ubuntu.com/focal/ .  I used the shell loop
```
for i in 0 1 2 3 4 5 6 7 8 9
    do for j in 0 1 2 3 4 5 6 7 8 9
        do ./upx --help >foo || echo $i $j $?
        done
    done
```
to execute `./upx --help` 100 times, with no failures: the ./upx succeeded, and the `echo ` never was executed.
`uname -a` says `Linux ubuntu 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`.

**Comment by jreiser** [comment]
Let's see how far execution does get: which system calls are made. `strace ./upx --help `.  Even the initial `execve` that is performed by the shell might fail.  If so, then the shell might report "Killed" immediately, with no other system call info.  Successful execution begins with (for example):
```
$ strace ./upx --help 2>&1 | sed 5q
execve("./upx", ["./upx", "--help"], 0x7ffe4916ed28 /* 55 vars */) = 0
brk(NULL)                               = 0x2734000
arch_prctl(0x3001 /* ARCH_??? */, 0x7fff0edf33e0) = -1 EINVAL (Invalid argument
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
```
and those calls after `execve` are made by crt0 in libc.so.6.

**Comment by markus-oberhumer** [comment]
Probably some hardware issue. Closing, please feel free to reopen.
