### ISSUE TITLE
invert_pt_dynamic() needs better checking for malformed input

### ISSUE THREAD

**Issue by jreiser** [upx/upx#759]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

Elf*::invert_pt_dynamic() needs better checking of the number of buckets in the symbol table.

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65510
https://oss-fuzz.com/testcase?key=4528496344891392

	    #4 0x6694db in PackLinuxElf32::invert_pt_dynamic(N_Elf::Dyn<N_Elf::ElfITypes<LE16, LE32, LE32, LE32, LE32> > const*, unsigned int) [upx/src/p_lx_elf.cpp:2142](https://github.com/upx/upx/blob/250c656b9eb24b0fb54fe8c015d38b0eba5ee80c/src/p_lx_elf.cpp#L2142):26
## How can we reproduce the issue?

1. upx -t https://oss-fuzz.com/download?testcase_id=4528496344891392
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx-4.2.2
* Host Operating System and version: Linux
* Host CPU architecture: x86_64
* Target Operating System and version: Linux
* Target CPU architecture: x86_64

**Comment by prantoran** [comment]
I got a noob question 😅, what does the function `invert_pt_dynamic()` do?

**Comment by jreiser** [comment]
@prantoran Looking at /usr/include/elf.h, the tags DT_* (DT_STRTAB, DT_SYMTAB, DT_GNU_HASH, etc.) in the PT_DYNAMIC segment  can appear in any order., and the tags themselves are not restricted to a set of small positive integers (for example: DT_GNU_HASH).  Rather than search PT_DYNAMIC sequentially on every access, it is useful to have a sorted array, and a dense interval of tags (consecutive) where possible.  Also, not all the implied arrays have a designated length (for example: DT_STRTAB).  So `invert_pt_dynamic` enables faster and more secure access.
