### ISSUE TITLE
upx for android execute file can't use -DANDROID_PIE

### ISSUE THREAD

**Issue by nmyggg** [upx/upx#76]
I use cmake build android execute file and with upx packer 

Android shell show  error: only position independent executables (PIE) are supported. when i set  -DANDROID_PIE flags and execute

**Comment by jreiser** [comment]
Please use the green "New issue" button which brings up the page https://github.com/upx/upx/issues/new .  Then edit the template to give us the information we need to investigate your issue.  In particular: the version of Android, the hardware environment (which hardware), the commands that you gave to cause the complaint.  If you can, then please attach a small test case (actual executable file) which triggers the complaint.  Also, please run "readelf --headers --segments name_of_bad_executable" and copy+paste the output into a message here.  (Add a line of three backquotes before the output, and another line of three backquotes after the output.  Then Preview to see that the formatting of the output has been preserved.  This information will help us analyze the situation.  Thank you.)
