### ISSUE TITLE
PEfile should check ih.subsystem

### ISSUE THREAD

**Issue by jreiser** [upx/upx#767]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

Check ih.subsystem in PeFile ::readPeHeader.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65526
https://oss-fuzz.com/testcase?key=4929157922357248
## How can we reproduce the issue?

1. upx -t https://oss-fuzz.com/download?testcase_id=4929157922357248
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx-4.2.2
* Host Operating System and version: Linux
* Host CPU architecture: x86_64
* Target Operating System and version: Linux
* Target CPU architecture: x86_64

**Comment by markus-oberhumer** [comment]
@jreiser HINT: note that `throwCantPack()`, `throwCantUnpack()` and `throwInternalError()` are overloaded for printf-style varargs

https://github.com/upx/upx/blob/250c656b9eb24b0fb54fe8c015d38b0eba5ee80c/src/except.h#L205

**Comment by jreiser** [comment]
@markus-oberhumer HINT: lines 3 through N of a git commit message can be used to call attention to significant items, such as new overloading of `throwCantPack()` etc.

```
$ git blame src/except.h  |  grep throwCantPack
0ac6c36af (Markus F.X.J. Oberhumer 2023-09-01 11:59:29 +0200 210) NORET void throwCantPack(const char *format, ...) may_throw attribute_format(1, 2);
$ git log 0ac6c36af
commit 0ac6c36af29db87e262e7180a46ae8efc40bb7a7
Author: Markus F.X.J. Oberhumer <markus@...>
Date:   Fri Sep 1 11:59:29 2023 +0200

    src: add a check for libc qsort(); cleanups

$ 
```
So the feature is only 4 months old, and the commit message says nothing about `throwCantPack()`.  Improved communication really would help make it easier to work on upx.
