### ISSUE TITLE
Compressed binaries for linux/arm segfault

### ISSUE THREAD

**Issue by svenschwermer** [upx/upx#768]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
When compressing an executable for linux/arm (32 bit, v7-A), the application crashes with a segmentation fault upon exit. In this case, the application is statically linked.

## What should have happened?
The executable should have returned cleanly.

## Do you have an idea for a solution?
I bisected upx and the offending commit is [adb0ca8](https://github.com/upx/upx/commit/adb0ca8250f2d04a62c14b7f5994c0668900c3fc)

Even when building the original executable with `-g -Og` and linking without `-s`, I don't get anything useful out of the coredump/running in gdb:
```
# gdb PLACEHOLDER
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-poky-linux-gnueabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from PLACEHOLDER...
(No debugging symbols found in PLACEHOLDER)
(gdb) run --help
Starting program: PLACEHOLDER --help
Usage: PLACEHOLDER COMMAND [OPTIONS]

// SNIP

Program received signal SIGSEGV, Segmentation fault.
0xb6ffc3fc in ?? ()
(gdb) bt
#0  0xb6ffc3fc in ?? ()
#1  0xb6ffcaa8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

## How can we reproduce the issue?
1. Cross-compile executable for target armhf (`-march=armv7-a -Os`; link with `-static -s`)
2. Run `upx --best` on cross-compiled executable
3. Run executable on target

## Please tell us details about your environment.
* UPX version used: I bisected between v4.0.2 (last good) and v4.2.2 (current, bad)
* Host Operating System and version: Arch Linux (Linux kernel: 6.6.10)
* Host CPU architecture: x86_64
* Target Operating System and version: Custom Yocto distribution (Linux kernel: 4.1.32)
* Target CPU architecture: armv7l

**Comment by jreiser** [comment]
Please upload ("Paste, drop, or click to add files") or give the URL to an actual executable file which fails.  There are too many variables: source-code language, compiler, linker (static binder), runtime library (especially with `-static -s`), etc.  Debugging is much easier when having an actual executable which fails.

**Comment by svenschwermer** [comment]
I was able to put together a minimal reproducible scenario.

Source (test.c):
```c
#include <stdio.h>
int main()
{
    printf("Test\n");
    return 0;
}
```

Build container (Dockerfile):
```dockerfile
FROM debian:buster
RUN dpkg --add-architecture armhf
RUN apt-get update && apt-get install -y \
    gcc-arm-linux-gnueabihf \
 && rm -rf /var/lib/apt/lists/*
```

1. `docker build -t crossbuilder .`
2. `docker run -v$(pwd):/mnt crossbuilder arm-linux-gnueabihf-gcc -static -o /mnt/test /mnt/test.c`
3. `upx --best -o test.upx test`
4. Run `test.upx` on target => `Test\n` is printed to stdout, then the process segfaults

Without `-static`, it does not segfault. Uncompressed, it does not segfault either.

I attached the executables [here](https://github.com/upx/upx/files/13907439/test-files.tar.gz).
