### ISSUE TITLE
Compressed ELF crashed when using --brute

### ISSUE THREAD

**Issue by Jackyxty** [upx/upx#770]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

After using UPX to compress a simple "HelloWorld" ELF, the compressed binary segfault at starting, 
It happens only when applying `--brute`/`--ultra-brute`, with or without `--no-lzma`. It does not happen when using `--best`.
It happens on both ELF64 and ELF32.
It seems not happen on larger binary.

## What should have happened?

The compressed binary should not crash.

## Do you have an idea for a solution?

Maybe some issue specific to small file and `--brute`.
The execution crashes on some empty page.
<img width="792" alt="image" src="https://github.com/upx/upx/assets/9113679/0848f577-d887-4d02-b336-ec8c1cb1f638">

## How can we reproduce the issue?

1. prepare the following source code
```C
#include <stdio.h>

int main(int argc, char *argv[])
{
	printf("Hello World %d\n", argc);
	return 0;
}
```
2. gcc helloworld.c -o elf
3. upx --brute elf
4. ./elf
5. Segmentation fault (core dumped)

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 4.2.2
* Host Operating System and version: Ubuntu 22.04
* Host CPU architecture: x86_64
* Target Operating System and version: Ubuntu 22.04
* Target CPU architecture: x86_64

**Comment by markus-oberhumer** [comment]
Could you try if `--brute --no-filter` makes any difference?

**Comment by Jackyxty** [comment]
> Could you try if `--brute --no-filter` makes any difference?

Sure. But I get the same result for both ELF64 and ELF32.
Also found that the compressed binary is byte-identical with and without `--no-filter`.

**Comment by markus-oberhumer** [comment]
Ok, thanks. Please attach your binary so that we can reproduce.

**Comment by Jackyxty** [comment]
just a simple helloworld, no fancy stuff. 😎 
Here it is.
[elf.zip](https://github.com/upx/upx/files/13964492/elf.zip)
