### ISSUE TITLE
Exception: compressed data violation when using lzma on i386-linux file

### ISSUE THREAD

**Issue by markus-oberhumer** [upx/upx#774]
## What's the problem (or question)?

Compressed data violation when using lzma on this attached i386-linux file:

[test.zip](https://github.com/upx/upx/files/13998527/test.zip)

## How can we reproduce the issue?
1. `upx-4.2.1 --lzma test.out -o x1`
2. `upx-4.2.1 -t x1`

## Please tell us details about your environment.
* UPX version used (`upx --version`): 4.2.1 and current git
* Host Operating System and version: Linux
* Host CPU architecture: amd64
* Target Operating System and version: Linux
* Target CPU architecture: i386

**Comment by jreiser** [comment]
What toolchain (compiler, static binder [/usr/bin/ld etc.]) constructed test.out?
```
$ unzip test.zip
$ readelf --header test.out
  Type:                              EXEC (Executable file)

  Entry point address:               0x19bd20

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align

  LOAD           0x000000 0x00010000 0x00010000 0x18ad1c 0x18ad1c R   0x1000
  LOAD           0x18ad20 0x0019bd20 0x0019bd20 0x16d380 0x16d380 R E 0x1000
  LOAD           0x2f80a0 0x0030a0a0 0x0030a0a0 0x0ba78 0x0ba78 RW  0x1000
  LOAD           0x303b18 0x00316b18 0x00316b18 0x001f4 0x04b34 RW  0x1000
```
The expected VirtAddr of the first PT_LOAD is 0x00400000 (4MiB), especially for an ET_EXEC which has 4 PT_LOAD "segments".

```
void PackLinuxElf32::unpack(OutputFile *fo)

    if (Elf32_Ehdr::ET_EXEC == get_te16(&ehdri.e_type)) {
        if (get_te32(&ehdri.e_entry) < 0x401180
        &&  get_te16(&ehdri.e_machine)==Elf32_Ehdr::EM_386) {
            // old style, 8-byte b_info:
            // sizeof(b_info.sz_unc) + sizeof(b_info.sz_cpr);
            szb_info = 2*sizeof(unsigned);
        }
    }
````

```
$ readelf --header x1
  Entry point address:               0x3c4c58

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x000000 0x00010000 0x00010000 0x01000 0x30b64c RW  0x1000
  LOAD           0x000000 0x0031c000 0x0031c000 0xaa276 0xaa276 R E 0x1000
```
Because the Entry `0x3c4c58 < 0x400000`, then unpack() decides `szb_info = 2*sizeof(unsigned);` but actually `szb_info = 12;`  This confusion propagates.

**Comment by markus-oberhumer** [comment]
test.out is a current UPX built by `zig cc` and thus linked by lld. If you think there is something wrong with the file we should report that to the Zig/LLVM team.

**Comment by jreiser** [comment]
[ls.gz](https://github.com/upx/upx/files/14057373/ls.gz) from Ubuntu-22.04-3
