### ISSUE TITLE
circular DT_HASH or DT_GNUHASH lookup

### ISSUE THREAD

**Issue by jreiser** [upx/upx#775]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

Corrupted DT_HASH or DT_GNUHASH can cause infinite loop
## How can we reproduce the issue?

1. upx -t https://oss-fuzz.com/download?testcase_id=5515443683000320
2. and upx -t https://oss-fuzz.com/download?testcase_id=4847320181047296

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx-4.2.2
* Host Operating System and version: Linux
* Host CPU architecture: x86_64
* Target Operating System and version: Linux
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
CI tests fails only on ubuntu-22.04; succeeds everywhere else, in particular on ubuntu-20.04.
Ubuntu-22.04 has many failures on tests of symlinks in the filesystem.  Is this a one-time quirk?

**Comment by markus-oberhumer** [comment]
I clicked on `re-run failed jobs` and the problem persisted.
