### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by Cluvert** [upx/upx#776]
i can't download the upx on my windows10

**Comment by jreiser** [comment]
The original Description is not adequate.
1. Can you download anything at all, from any site?  (Is WiFi up, or the ethernet cable plugged in; is your ISP up; can you `ping` or view any site, etc..)
2. Copy+Paste into a Comment here the exact URL link that you tried.
3. Say the OS version, browser name and version, hardware architecture, etc.  (what our  New Issue form asks for!)
