### ISSUE TITLE
Is x86 macOS 12 supported?

### ISSUE THREAD

**Issue by osalbahr** [upx/upx#777]
## What's the problem (or question)?

Upon version bumping on Homebrew, [the x86 macOS 12 CI](https://github.com/Homebrew/homebrew-core/actions/runs/7648824581/job/20842340379) fails with the following error:

```console
  ==> /usr/local/Cellar/upx/4.2.2/bin/upx -1 --force-execve ./upx
                         Ultimate Packer for eXecutables
                            Copyright (C) 1996 - 2024
  UPX 4.2.2       Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 3rd 2024
  
          File size         Ratio      Format      Name
     --------------------   ------   -----------   -----------
  upx: ./upx: CantPackException: macOS is currently not supported (try --force-macos)
```

To my surprise, the build passed on all other combinations of architecture (x86, arm) and version (12-14) except for x86 macOS 12. I am wondering if that platform is supported.

- https://github.com/Homebrew/homebrew-core/pull/160367#issuecomment-1909292028

## What should have happened?

Test passes.

## Do you have an idea for a solution?

Clarify which platforms are supported. [The developer README](https://github.com/upx/upx/blob/5d649f83ecae9afa68f77d344aec5575b5eac948/README.SRC#L101) does mention macOS.

## How can we reproduce the issue?

1. Install `upx` on GitHub's x86 macOS 12 runner
2. Run `/usr/local/Cellar/upx/4.2.2/bin/upx -1 --force-execve ./upx`

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.2.2
* Host Operating System and version: macOS 12
* Host CPU architecture: x86
* Target Operating System and version: macOS 12
* Target CPU architecture: x86

- - -

- might be related: #612

**Comment by osalbahr** [comment]
Adding `--force-macos` made the CI pass.

Keeping open in case the flag was meant to be needed in all platforms.

**Comment by markus-oberhumer** [comment]
UPX x86_64 and arm64 **should** work on macOS 12 and earlier, but the packed binaries won't run on macOS 13+.

That's why we added `--force-macos` so that you can override if you know what you are doing.

**Comment by markus-oberhumer** [comment]
Some related issues:

- [ ] https://github.com/upx/upx/issues/434
- [ ] https://github.com/upx/upx/issues/446
- [ ] https://github.com/upx/upx/issues/601
- [ ] https://github.com/upx/upx/issues/612

**Comment by osalbahr** [comment]
@markus-oberhumer Thank you for clarifying!

**Comment by markus-oberhumer** [comment]
The problem is that Apple changed some internal things in macOS 13+, and of course this is undocumented...

Also see https://github.com/upx/upx-fork-apple-oss-distributions-xnu/issues/1 where we try to build the XNU kernel from official published source code (which of course also does not work).
