### ISSUE TITLE
4.0.2 and later versions corrupts some win32 DLLs (e.g. chrome.dll) after compression

### ISSUE THREAD

**Issue by xrayer** [upx/upx#778]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

Observed when compressing chrome.dll of 360 Extreme Explorer (chromium based). I used most conservative options for compression: upx -1 -f --compress-exports=0 --compress-icons=0 --compress-resources=0 --strip-relocs=0 chrome.dll
but after compression the program crashed. I stepped down with UPX versions and found that version 4.0.1 compress it properly that program runs after compresion without crash. The same with even older 3.96. I compared the compressed binaries and theres only 2-byte difference with all versions in range 4.0.2 to 4.2.2 but huge number of differences when compared to 4.0.1. So something had changed bad way since that version.

## What should have happened?

Program should run without crash after compression of DLL as it did when compressed with older UPX version.

## Do you have an idea for a solution?

Look at what changed on win32/PE compression between version 4.0.1 and 4.0.2

## How can we reproduce the issue?

1.get Chrome based 360 extreme explorer, e.g. https://archive.org/download/360EE_Modified_Version/360EE_13.0.2310.0_Modified.7z
2. upx -1 -f --compress-exports=0 --compress-icons=0 --compress-resources=0 --strip-relocs=0 chrome.dll
3. run chome
4. it crash

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 4.2.2
* Host Operating System and version: Windows XP
* Host CPU architecture: intel Core i7-2600K
* Target Operating System and version: Windows XP
* Target CPU architecture: x86

**Comment by markus-oberhumer** [comment]
Might be related to https://github.com/upx/upx/issues/643

**Comment by markus-oberhumer** [comment]
This could be a real bug, but then downloading some random file from archive.org with calls itself  "Modified_Version" is not encouraging.

Closing for now. Please feel free to reopen with trusted test cases.
