### ISSUE TITLE
[DOS EXE] Keep original EXE header

### ISSUE THREAD

**Issue by roytam1** [upx/upx#791]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
I wonder if UPX can keep original EXE header (including size and contents) so target program can still able to use contents in EXE header.

## What should have happened?
Currently, UPX replaced EXE header with its own one.

## Do you have an idea for a solution?
Add a switch to keep original EXE header, and try best to keep it unless there is a need for unpacking stub use.

## How can we reproduce the issue?

1. upx edit.com
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.95w
* Host Operating System and version: Win 7 SP1
* Host CPU architecture: x64
* Target Operating System and version: DOS
* Target CPU architecture: x86

**Comment by ml1050** [comment]
What kind of information do you want to access from the original header? The size of the dos/exe header is 30 bytes, and UPX needs to set all of them for the compressed program. 

If you want to keep he original header then you could append it as an overlay to your program before compression and use the --overlay=copy command line switch for UPX.

**Comment by roytam1** [comment]
> What kind of information do you want to access from the original header? The size of the dos/exe header is 30 bytes, and UPX needs to set all of them for the compressed program.

MS' `EDIT.COM` strores strings inside EXE header (after EXE header fields). From my testing, I need to keep same header size and same "header overlay" i.e. extra data after EXE header fields and fixing header size and image size in EXE header in order to make it work.

**Comment by jreiser** [comment]
@roytam1 How should UPX determine the length of the "strings inside EXE header (after EXE header fields)"?  That is, how many bytes do you want copied from the original EXE (beginning at byte 30)  into the compressed EXE (also beginning at byte 30)?

**Comment by ml1050** [comment]
I think the bytes we need are the ones between 30 and ih.headsize16*16.

**Comment by markus-oberhumer** [comment]
Well, if you need some extra info then store it (or patch it into the executable) before compressing with UPX.
