### ISSUE TITLE
The compression .so file cannot use in Linux

### ISSUE THREAD

**Issue by hejiwen** [upx/upx#792]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

upx libicfs-common.so.2  succeeded，but upx -d  libicfs-common.so.2 prompts "NotPackedException: not packed by UPX".
I try other so files, all have this problem.

## What should have happened?

upx -d  libicfs-common.so.2  can decompress the file to original file

## How can we reproduce the issue?

1. upx libicfs-common.so.2 
2. upx  -d libicfs-common.so.2 
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
 3.96
* Host Operating System and version:
 Centos8.6
* Host CPU architecture:
 Intel Xeon Gold 5218
* Target Operating System and version:
 Centos8.6
* Target CPU architecture:
  Intel Xeon Gold 5218

**Comment by jreiser** [comment]
Please "Paste, drop, or click to add files" libicfs-common.so.2, or provide a URL to the package that contains it.

**Comment by markus-oberhumer** [comment]
Also please try the latest version 4.2.2.

**Comment by jreiser** [comment]
No evidence of failure, no response in one month to our request for a failing file or more info.
