### ISSUE TITLE
Add option to override CantPackException: file is too small

### ISSUE THREAD

**Issue by Harvie** [upx/upx#795]
## What's the problem (or question)?
Cannot run upx on files that are too small. I am geting following error:
`CantPackException: file is too small`

While this might be extremely sensible idea in most cases, when going for disk space saving.

I do sometimes use upx compression of shell scripts to prevent mildly advanced users from messing around with the code. I understand that upx compression can be easily reverted, but goal here is to prevent semi-clueless managers doing uninformed and harmfull modifications to the scripts. This works quite well, but not with the small files (which are the most tempting for these people :-) I understand this might be quite niche application, but the fix seems to be quite small, easy and straightforward.

## What should have happened?
We should have choice to circumvent this check

## Do you have an idea for a solution?
Add option `--force-small` to circumvent this check

## How can we reproduce the issue?
Try to compress file that is too small

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.96
* Host Operating System and version: Debian 11
* Host CPU architecture: x86_64
* Target Operating System and version: Debian 11
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
You **must** "Paste, drop, or click to add files" an actual executable file which will be used as a testcase.

**Comment by jreiser** [comment]
Also, the Discussion about large files https://github.com/upx/upx/discussions/723 applies.  You probably have **many** small files, so the use of a mounted squashfs filesystem often makes sense.

**Comment by Harvie** [comment]
> You must "Paste, drop, or click to add files" an actual executable file which will be used as a testcase.

upx [test.sh.txt](https://github.com/upx/upx/files/14603320/test.sh.txt)
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX 4.2.2       Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 3rd 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: test.sh.txt: IOException: file is too small -- skipped

Packed 0 files.
```

> Also, the Discussion about large files https://github.com/upx/upx/discussions/723 applies. You probably have many small files, so the use of a mounted squashfs filesystem often makes sense.

if you read my original issue text, you will figure out, the compression is not my main concern.

**Comment by markus-oberhumer** [comment]
Well, why don't just add some large comments to the bottom of your scripts?

**Comment by Harvie** [comment]
That's actualy what i do now, but it's not very elegant :-D

**Comment by markus-oberhumer** [comment]
AFAIR these minimum size requirements are there for a good reason, and I really don't want to risk breaking things.

So sorry, this is WONTFIX.

**Comment by Harvie** [comment]
> AFAIR these minimum size requirements are there for a good reason

yeah. obviously. the reason is the fact the UPX adds uncompressed decompressor code header to the compressed data. therefore it might easily happen that when you compress files smaller than the decompressor, the compressed binary would be bigger.

> and I really don't want to risk breaking things.

that is why i've suggested to only do this when `--force-small` flag would be used. people usualy know they should not use force flags unless they know what they are doing.

**Comment by markus-oberhumer** [comment]
> that is why i've suggested to only do this when `--force-small` flag would be used. people usualy know they should not use force flags unless they know what they are doing.

I'm pretty sure that certain buffers are expected to have a minimum size, so this is not trivial.

Why don't you just write a simple awk/perl/python script to automate adding comments?

**Comment by bitraid** [comment]
@Harvie , you might be interested in [shc](https://github.com/neurobin/shc).

**Comment by markus-oberhumer** [comment]
@bitraid Thanks for that link, shc looks even more scary than upx :smile:
