### ISSUE TITLE
Error packing cockroach.exe on Windows 10: CantPackException: relocation overflow 506779448 10

### ISSUE THREAD

**Issue by lospejos** [upx/upx#796]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
I'm on `Windows 10 LSTC 21H2 build 19044.4046`, on Intel CPU: `12th Gen Intel(R) Core(TM) i7-12700H 2.30 GHz`, with `32GB` RAM. UPX version `4.2.2`.
Steps performed:
1) Downloaded file `cockroach-v23.2.2.windows-6.2-amd64.zip` from https://binaries.cockroachdb.com/cockroach-v23.2.2.windows-6.2-amd64.zip
2) Unpacked `cockroach.exe` to a local directory, file has `529919478` bytes (`500MB), it's quite large
3) Started `upx` like this:
```
upx -9 -v cockroach.exe
```
4) After process finished (all dots in progress bar became stars/asterisks), an error occurred:
```
> upx -9 -v cockroach.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX 4.2.2       Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 3rd 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: cockroach.exe: CantPackException: relocation overflow 506779448 10

Packed 1 file: 0 ok, 1 error.
```
No temporary or partially compressed files present in directory. RAM load was not large, during compression I noticed 2 of 20 vCPU kernel was loaded on approx 60%-80%.

## What should have happened?
I was expected that file should be compressed successfully without errors.

## Do you have an idea for a solution?
Unfortunately I don't, since I'm not an expert. My **not professional** assumption is that this error is due to lacking of some resources (f.e. handlers, temp buffers, descriptors etc) or something like (buffer?) overflow/underflow, as well as some error in application code (`upx`) or underlying library/module code (crt/vcrt etc).

## How can we reproduce the issue?

Please see my steps description above.

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.2.2
* Host Operating System and version: Windows 10 LSTC 21H2 build 19044.4046
* Host CPU architecture: 12th Gen Intel(R) Core(TM) i7-12700H 2.30 GHz
* Target Operating System and version: the same
* Target CPU architecture: the same

**Comment by markus-oberhumer** [comment]
This is a limitation how UPX currently handles relocations - basically the program is just too large.

**Comment by markus-oberhumer** [comment]
Having a quick look, it seems `cockroach.exe` is a Go program. But why is it so large? 500 MB is ridiculous.

**Comment by bitraid** [comment]
> Having a quick look, it seems `cockroach.exe` is a Go program. But why is it so large? 500 MB is ridiculous.

It contains DWARF debugging information. By removing it (running strip), the size is reduced to about 187 MB, and can then be successfully compressed by upx (to less than 60 MB - 45.7 MB using lzma).

**Comment by jreiser** [comment]
More reasons for large size of a Go program: Go decided to avoid "DLL hell" by not using any DLLs, partly because the Go runtime library lacked a stable ABI for a whlle, and partly due to cross-OS incompatibilities.  [Remember the many-year evolution of support for threads in glibc; and from its beginning Go has specialized in threads.]  (Almost) all the Go runtime support routines that are needed, are statically bound in to each Go program.  One side effect is that a Go program tends to be highly compressible, because runtime library routines often have similar prologues and epilogs; and cross-subroutine tail merging (such as error handling for system calls) is not used.

**Comment by jreiser** [comment]
The code in pefile.cpp is thin on encapsulation, abstraction, and maintainability.  For instance:
```
void PeFile::Reloc::add(unsigned pos, unsigned type) {
    assert(start_did_alloc);
    if ((pos << 4) >> 4 != pos || type > 0xf)
        throwCantPack("relocation overflow %u %u", pos, type);
    set_le32(start_buf + (RELOC_INPLACE_OFFSET + 4 * counts[0]), (pos << 4) + (type & 0xf));
    counts[0] += 1;
}
```
When bit width matters, then `%#x` is much better than `%u` in a _printf_ format.
Why are 4 bits used for the `type`? Yes, it's easier for a programmer to decode in hexadecimal, but what else?
```
:g/rel.add(/p
            rel.add(*q++ + rvamin, (big & 4) ? 2 : 1);
                rel.add(*q + rvamin, 1);
        rel.add(rvamin + get_le32(wrkmem + 4 * ic), bits == 32 ? 3 : 10);

:g/reloc_type/p
    static const unsigned reloc_type = 3;
    static const unsigned reloc_type = 10;
    const unsigned reloc_type = tls_traits<LEXX>::reloc_type;
        rel->add(tls_handler_offset + tls_handler_offset_reloc, reloc_type);
        rel->add(newaddr + ic, reloc_type);
        rel->add(newaddr + sotls - 2 * cb_size, reloc_type);
```
So the only visible `type` values are {1,2,3,10}.  2 bits could encode those 4 cases.  In the particular case of `cockroach.exe`, just 1 extra bit for the `position` would be enough. Is there a relationship between the cases {1,2,3,10} and Windows-defined types?  What is it?  Could 3 bits be used, with dynamically-assigned slots (as encountered at run time) and two `unsigned [8]` tables for encoding+decoding?

**Comment by bitraid** [comment]
Before the related changes (UPX versions 4.0.2 and older), the file could be successfully compressed.

**Comment by ml1050** [comment]
The 'type' field is the native PE relocation type value from here: https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#base-relocation-types

IIRC types 1,2,3 are used only for 32 bit PE files.  and type 10 is only used for 64 bit files. I think I used the code "(pos << 4) + (type & 0xf)"  before 64 bit CPUs were a thing, and I did not expect such huge files where pos<<4 could overflow a 32 bit value.

**Comment by markus-oberhumer** [comment]
I've rewritten Laszlo's original reloc handling code a little bit in UPX 4.2.0 but did not touch the core design. And I did add that overflow error check (which was missing in previous versions).

A much cleaner way would be to remove the in-place memory optimization (`RELOC_INPLACE_OFFSET`) and use a dynamically allocated array of 5-byte structs to hold the full reloc info.

But then, 500 MB is close to our `UPX_RSIZE_MAX_MEM` limit, and nobody should pack such huge files anyway, so this is a WONTFIX from me (unless you can convince me otherwise).

**Comment by markus-oberhumer** [comment]
@lospejos So the solution to your probem seems to be to run `strip cockroach.exe` before running `upx cockroach.exe`.

**Comment by jreiser** [comment]
@ml1050   I have pushed a branch `jreiser-issue796` which implements yesterday's idea https://github.com/upx/upx/issues/796#issuecomment-2002512753 : Allow one more bit (29 bits: length 536,870,912) when tracking the position of a relocation in `pefile.cpp`, by enumerating only the IMAGE_REL_BASED_* cases that actually are seen.  Please comment if you can.
Speculating: Another bit (30 bits total) might be possible if most actual 80386 code is well-behaved.

**Comment by markus-oberhumer** [comment]
@jreiser I can see what you are trying to achieve, but this only make the original in-place memory optimization hack even more convoluted. Sigh - I'll probably have to tackle this problem after all.

**Comment by markus-oberhumer** [comment]
Fixed in devel branch.
