### ISSUE TITLE
How to rebuild stub

### ISSUE THREAD

**Issue by yujack008** [upx/upx#798]
No a Bug。

I have download bin-upx-20221212.tar.gz to ~/local/bin/bin-upx/
I have change src/stub/src/arm64-linux.elf-so_entry.S file. But i dont know how to rebuild stub, is any tutorials ?

I run "make all" but no any stub compile log

**Comment by yujack008** [comment]
i have sucess。
cd src/stub
make all

**Comment by markus-oberhumer** [comment]
See misc/podman/rebuild-stubs/20-image-run-shell.sh

**Comment by jreiser** [comment]
@yujack008,
> I have change src/stub/src/arm64-linux.elf-so_entry.S file.

Please share your goal, strategy, and code!
