### ISSUE TITLE
Compress the Chrome.dll, Vivaldi.dll, Opera.dll, etc..

### ISSUE THREAD

**Issue by Uber-1** [upx/upx#802]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

How can I properly compress Chrome.dll, Vivaldi.dll, Opera.dll, etc.?

## What should have happened?

Well, just reduce the size of DLLs and keep it's ability to work.

## Do you have an idea for a solution?

Sorry, I don't have it.
Also I'm not really sure about the source of problem: is that a bug in UPX, or just somewhat of chrome.dll protection.
I hope, you could say if there is any problem or help to solve that.

## How can we reproduce the issue?

1. Download the chrome-based browser and unpack it (you may use any of my [toys](https://github.com/Uber-1/Toys/tree/main/BAT_SA) to save your time, or use a copy of the browser you have). I have tested with Ungoogled Chromium, Vivaldi, Opera, and some another, but I think, we can use any of chrome-based ones.
2. Now run _upx.exe --best --no-backup --overlay=copy --force chrome.dll_  (or vivaldi.dll, opera.dll, etc...)
3. Try to start chome.exe
4. Browser just crashes silently when starting. No errors. 

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.2.2
* Host Operating System and version:  W10 21H2 x64
* Host CPU architecture: x86-64, AMD sFM2
* Target Operating System and version:  W10 21H2 x64
* Target CPU architecture: x86-64, AMD sFM2

**Comment by jreiser** [comment]
>     1. Download the chrome-based browser and unpack it (you may use any of my [toys](https://github.com/Uber-1/Toys/tree/main/BAT_SA) to save your time, or use a copy of the browser you have).

@Uber-1  Please give the URL to an actual .exe  file. I cannot find any actual .exe file in the BAT_SA directory.

**Comment by Uber-1** [comment]
My toys are not an exe, just simple batch script-downloader. You may ignore my folder if you wish.

Well, you may use this official link for Ungoogled
https://github.com/macchrome/winchrome/releases/download/v123.6312.90-M123.0.6312.90-r1262506-Win64/ungoogled-chromium-123.0.6312.90-1_Win64.7z

Just try to compress chrome.dll via upx and launch chrome.exe then.

**UPD:**
If I do "-d --no-backup" then, the new unpacked dll gets it's previous size and works again.
