### ISSUE TITLE
pe binary compiled by dmd(dlang) can not compress

### ISSUE THREAD

**Issue by avriltank** [upx/upx#803]
this is a demo:
[vibe_http.zip](https://github.com/upx/upx/files/14783714/vibe_http.zip)
```dlang
import vibe.core.core : runApplication;
import vibe.http.server;

void handleRequest(scope HTTPServerRequest req, scope HTTPServerResponse res)
{
	if (req.path == "/")
		res.writeBody("Hello, World!", "text/plain");
}

void main()
{
	auto settings = new HTTPServerSettings;
	settings.port = 8080;
	settings.bindAddresses = ["::1", "127.0.0.1"];

	auto l = listenHTTP(settings, &handleRequest);
	scope (exit) l.stopListening();

	runApplication();
}
```

dub.json like this:
```json
{
	"authors": [
		"avriltank"
	],
	"copyright": "Copyright © 2024, avriltank",
	"dependencies": {
		"vibe-d": "~>0.10.0"
	},
	"description": "A minimal D application.",
	"license": "proprietary",
	"name": "vibe_http"
}
```

**Comment by jreiser** [comment]
Please show the exact command line that you used to invoke upx, and the resulting console output including error message that was produced.  The file vibe_http.exe compresses without complaint using today's release upx-4.2.3:

```
$ upx-4.2.3 -f -o vibe_http.exe.packed  vibe_http.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX 4.2.3       Markus Oberhumer, Laszlo Molnar & John Reiser   Mar 27th 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   3528704 ->    962048   27.26%    win64/pe     vibe_http.exe.packed    
                       
Packed 1 file.

$ sha256sum vibe_http.exe*
9619eb03bd793b0631cd0d22f1c4f9c8f9e2c0c339fdcdaacfa43c41d19ee8b6  vibe_http.exe
e1f3f14f7c16aee18d81480c50fc4b1971017969300f0d984eafeefa510cf9c7  vibe_http.exe.packed

$ 
```

**Comment by avriltank** [comment]
Sorry for the confusion. If I'm writing a program in Dlang, it can run normally without compression using UPX. However, after compression with UPX, the program becomes unexecutable.
![upx_cannot_run](https://github.com/upx/upx/assets/13652682/0dd24e34-b984-42be-80ba-33af458c8263)

**Comment by jreiser** [comment]
A proper Issue report related to `the program becomes unexecutable` must include a URL or actual copy ("Paste, drop, or click to add files", which must be zip'ped or gzip'ped) of an actual program (.exe file, etc.) that fails to execute, together with the instructions to cause the failure, and the evidence that there _is_ a failure.  Also include the name and version of the Operating System, and the hardware architecture, and the software build chain (name and version of compiler, static linker, etc.) which translates from source code to executable. The template that `New bug` gives, prompts for this information.
