### ISSUE TITLE
XDown exe doesn't work compressed

### ISSUE THREAD

**Issue by peter8777555** [upx/upx#805]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

XDown exe doesn't work compressed

## Do you have an idea for a solution?

No.

## How can we reproduce the issue?

web site:
https://xdown.org/

Download Link:
https://dl.xdown.dev/windows/i386/xdown-2.0.8.6.zip

upx --force XDown.exe

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.2.3
* Host Operating System and version: Windows 11
* Host CPU architecture: Intel i5-8500
* Target Operating System and version: Windows 11
* Target CPU architecture: Intel i5-8500

**Comment by markus-oberhumer** [comment]
What happens if you do **not** use `--force` ?

**Comment by peter8777555** [comment]
> What happens if you do **not** use `--force` ?

![z1](https://github.com/upx/upx/assets/29886853/f327b9a9-f068-4386-9f0b-7869b0686152)

**Comment by markus-oberhumer** [comment]
Well, unfortunately that file is not supported.

**Comment by peter8777555** [comment]
> Well, unfortunately that file is not supported.

I remove the GUARD_CF flag from XDown.exe
XDown.exe can work well.

UPX XDown.exe (do not use --force)
but
XDown.exe doesn't work compressed ?

**Comment by markus-oberhumer** [comment]
Sorry, I cannot help you here, but if you are the author of `xdown` then you should be able to debug this.
