### ISSUE TITLE
CI failures for arm64 and powerpc

### ISSUE THREAD

**Issue by markus-oberhumer** [upx/upx#806]
I've just enhanced the CMake test suite a little bit to explicitly test all packed nrv2b/nrv2d/nrv2e/lzma versions, and it seems there are problems on arm64 and powerpc.

https://github.com/upx/upx/actions/runs/8581771688/job/23519164380

**Comment by jreiser** [comment]
For zigcc powerpc64le-linux- musl, then  https://github.com/upx/upx/actions/runs/8581771688/job/23519164380 at line 531 shows
```
 upx 4.3.0-git-97cf29ffbb05
+ qemu-ppc64le ./upx-packed-n2d.out --version-short
/__w/upx/upx/misc/testsuite/mimic_ctest.sh: line 90:  5334 Segmentation fault      (core dumped) "${upx_runner[@]}" ./upx-packed-n2d${exe} --version-short
Error: Process completed with exit code 139.
```
So that is a problem with n2d on ppc64le.

Please point to the specific problem on arm64.

**Comment by markus-oberhumer** [comment]
arm64 is here https://github.com/upx/upx/actions/runs/8581771688/job/23519163110

**Comment by jreiser** [comment]
@markus-oberhumer  git branch `jreiser-issue806` fixes the problems and passes CI test.  The branch has been pushed to the origin repo, and is ready to be combined into `devel`.  I believe that a "fast forward merge" should work.

**Comment by markus-oberhumer** [comment]
Thanks!
