### ISSUE TITLE
Error reports in CI tests are not developer-friendly

### ISSUE THREAD

**Issue by jreiser** [upx/upx#807]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

Errors that are reported during a CI run are not easy enough for a developer to reproduce.  Searching for the path to the working directory, and the actual command line that caused the reported error, and the effective paths to relevant inupt files (and how they were constructed), is too hard and takes too long.

For instance, in https://github.com/upx/upx/actions/runs/8585295841/job/23526558285 the section "Mimic ctest tests with QEMU qemu-aarch64" reports at line 532:
```
 + qemu-aarch64 ./upx-packed-n2d.out --version-short
/__w/upx/upx/misc/testsuite/mimic_ctest.sh: line 90:  5340 Segmentation fault      (core dumped) "${upx_runner[@]}" ./upx-packed-n2d${exe} --version-short
Error: Process completed with exit code 139.
```
where line 36 says `upx_run='qemu-aarch64 /__w/upx/upx/build/zig/aarch64-linux-musl/debug/upx'`  That's a good start at providing hints to the information that a developer needs.  However, other information is missing:

1. What is the absolute path to the actual working directory?  The `bash`-maintained environment variable `$PWD` gives a relative path which can be a nice clue; an absolute path is better.
2. What is the connection between the shell variables `upx_runner` and `upx_run`?
3. How was the input file `./upx-packed-n2d${exe}` constructed?

## What should have happened?

At the point of the Error, give enough information to construct a good Bug Report for that specific Error.

## Do you have an idea for a solution?

In general, how can a developer run the CI actions locally before triggering the CI?  Something like `cd src; make run-testsuite` or `misc/podman/rebuild-stubs/20-image-run-shell.sh` with its commented suggestions at the end, is desired.  (Of course, use local `upx-stubtools` where appropriate.)

Even more generally, a developer would like to be able to look at something like the results from `strace -f -e trace=chdir,execve,fork,vfork,clone,__clone2,clone3 -v -s 500` of an entire CI run. Perhaps the `DEBUG` trap of the `bash` shell can be leveraged to provide similar information.
## How can we reproduce the issue?

Find a failing CI run, and look at the transcript of the failing step(s), usually marked with an 'X' circled in red color.
## Please tell us details about your environment.

* UPX version used (`upx --version`): upx-4.2.3
* Host Operating System and version: Linux 6.x (Fedora and/or Ubuntu)
* Host CPU architecture: x86_64
* Target Operating System and version: Linux 6.x (Fedora and/or Ubuntu)
* Target CPU architecture: x86_64

**Comment by markus-oberhumer** [comment]
See https://github.com/upx/upx/blob/devel/misc/testsuite/mimic_ctest.sh .

Feel free to add your own scripts if you are unhappy - I already have spent a **HUGE** amout of time on making all this CI/testing stuff work on all platforms...

**Comment by markus-oberhumer** [comment]
Current status is fine for me, so I'd suggest that you add your own GitHub Actions workflow file that perfectly suits your needs.

**Comment by markus-oberhumer** [comment]
Works for me.
