### ISSUE TITLE
run failed on arm32 page_size 32k

### ISSUE THREAD

**Issue by HenryShen210** [upx/upx#808]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

binary packed with upx run failed on arm32 32k page_size machine

## What should have happened?

runs well

## How can we reproduce the issue?

1. pack vim with upx
2. run ./vim on arm32 32k page size machine
3. vim stopped with return 127

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.2.2
* Host Operating System and version: ubuntu 14.04
* Host CPU architecture: i686
* Target Operating System and version: linux 4.2.8
* Target CPU architecture: arm32

**Comment by jreiser** [comment]
@HenryShen210 What is the size of the original input file, and how many `readelf --segments input_file  |  grep LOAD` does it contain?
There's a conflict between compression and large page sizes employed by common static linkers (/bin/ld, etc.).  The obvious strategy for placement of PT_LOAD typically creates significant fragmentation (average 1/2 a page) at each boundary between PT_LOADs.  This fragmentation is not compressible. Logic in upx-v4.2.2 (commit ed2633bf9 of 2023-11-26) decided that a page size less than 64KiB would indicate that 4KiB was *also* acceptable, which usually enables reducing the fragmentation significantly.

Try telling your softtware build toolchain to use 64KiB as the page size. Then upx won't try to reduce the fragmentation by using 4KiB.

**Comment by HenryShen210** [comment]
original file size is 1.27MB and readelf --segments input_file  |  grep LOAD is 2. compression of upx is worked(from 1.27MB to 728KB), but vim after compression run failed on my arm32 machine

**Comment by jreiser** [comment]
Thank you for prompt response.  It would also help to know more about the specific target environment:.

1. Linux distribution and kernel version:  `$ uname -a`
2. CPU properties: the first several lines from /proc/cpuinfo, such as `$ sed 10q </proc/cpuinfo`
3.  Memory properties: the last several lines from /proc/meminfo, such as `$ tail -10 /proc/meminfo`
4. The detailed address space layout: the complete output from `$ readelf --segments input_file`

**Comment by HenryShen210** [comment]
1. Linux distribution and kernel version: 
  Linux 4.2.8 SMP Wed Apr 10 14:41:17 CST 2024 armv7l GNU/Linux

2. CPU properties: 
processor	: 0
model name	: Annapurna Labs Alpine AL214 Quad-core ARM Cortex-A15 CPU @ 1.70GHz
Speed		: 1.7GHz
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0xc0f
CPU revision	: 4

3. Memory properties: 
KernelStack:       20960 kB
PageTables:        63968 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    25049472 kB
Committed_AS:    5437696 kB
VmallocTotal:     565248 kB
VmallocUsed:       33280 kB
VmallocChunk:     474496 kB

4. The detailed address space layout:
  $ readelf --segments input_file:
  Elf file type is EXEC (Executable file)
Entry point 0xa311
There are 8 program headers, starting at offset 52

Program Headers:
```
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  EXIDX          0x13b2d0 0x001432d0 0x001432d0 0x00008 0x00008 R   0x4
  PHDR           0x000034 0x00008034 0x00008034 0x00100 0x00100 R E 0x4
  INTERP         0x000134 0x00008134 0x00008134 0x00019 0x00019 R   0x1
      [Requesting program interpreter: /lib/ld-linux-armhf.so.3]
  LOAD           0x000000 0x00008000 0x00008000 0x13b2dc 0x13b2dc R E 0x8000
  LOAD           0x13b2dc 0x0014b2dc 0x0014b2dc 0x0aa98 0x10760 RW  0x8000
  DYNAMIC        0x13b2e8 0x0014b2e8 0x0014b2e8 0x000f8 0x000f8 RW  0x4
  NOTE           0x000150 0x00008150 0x00008150 0x00044 0x00044 R   0x4
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x4
```
 Section to Segment mapping:
  Segment Sections...
   00     .ARM.exidx 
   01     
   02     .interp 
   03     .interp .note.ABI-tag .note.gnu.build-id .hash .dynsym .dynstr .gnu.version .gnu.version_r .rel.dyn .rel.plt .init .plt .text .fini .rodata .ARM.exidx .eh_frame 
   04     .init_array .fini_array .jcr .dynamic .got .data .bss 
   05     .dynamic 
   06     .note.ABI-tag .note.gnu.build-id 
   07

**Comment by markus-oberhumer** [comment]
What is the status of this issue?

**Comment by jreiser** [comment]
I cannot reproduce the problem because I cannot find a `vim` built for 32KB page size.  On the "Get Ubuntu" page for ARM architecture the options are 64-bit ubuntu-24.0.4 (Workstation) whose `/usr/bin/vim.basic` uses 64KB pages, or 32-bit ubuntu-22.0.4 (Server) whose `/usr/bin/vim.basic` ALSO uses 64KB pages (not 32KB pages.)

@HenryShen210 please provide access to your `vim` that is built for 32KB page size.  I suppose I could take an executable that has `.p_align` of 64KB and change it to 32KB, but that's messy.

(Edit: Also, please invoke the compressed `vim` under `strace`, which should print a couple dozen lines before it exits with failure.)

**Comment by HenryShen210** [comment]
[vim.zip](https://github.com/user-attachments/files/16607277/vim.zip)
vim is the original file and vim.upx is the compressed one.
the message showed by running strace vim.upx:
# ./strace ./vim.upx         
execve("./vim.upx", ["./vim.upx"], 0x7db0fa90 /* 26 vars */) = 0
open("/proc/self/exe", O_RDONLY)        = 3
mmap2(NULL, 2908, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x75cc0000
cacheflush(0x75cc0000, 0x75cc0b5c, 0)   = 0
mprotect(0x75cc0000, 2908, PROT_READ|PROT_EXEC) = 0
readlink("/proc/self/exe", "/tmp/vim.upx", 4095) = 12
cacheflush(0x7d8f7064, 0x7d8f7198, 0)   = 0
munmap(0x8000, 1391164)                 = 0
mmap2(0x8000, 1290976, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x8000
cacheflush(0x8000, 0x8134, 0)           = 0
cacheflush(0x8134, 0x1432e0, 0)         = 0
cacheflush(0x1432e0, 0x1432e8, 0)       = 0
mprotect(0x8000, 1290976, PROT_READ|PROT_EXEC) = 0
mmap2(0x14b000, 44404, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = -1 EINVAL (Invalid argument)
exit(127)                               = ?
+++ exited with 127 +++

**Comment by jreiser** [comment]
It seems possible that the system with hardware page size 32K might invoke programs with software AT_PAGESZ of 0x1000.  The upx runtime de-compression stub believes AT_PAGESZ, so it maps the Elf32_Phdr ("segment") of
```
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x13b2dc 0x0014b2dc 0x0014b2dc 0x0aa98 0x10760 RW  0x8000
```
at the next lower page address which is `(0x0014b2dc &~ (-1 + 0x1000`) which is `0x14b000`, which is not a multiple of 0x8000, which draws the complaint.  This behavior agrees with the strace report of
```
mmap2(0x14b000, 44404, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = -1 EINVAL (Invalid argument)
```

Why would the Linux kernel say that the page size is 0x1000 when the hardware demands 0x8000?  Good question!
Here is how to tell:
```
$ gdb /bin/date
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04.2) 12.1
   <<snip>>
Reading symbols from /bin/date...
(No debugging symbols found in /bin/date)
(gdb) b *100   ## cause the program to stop at the very first instruction
Breakpoint 1 at 0x64
(gdb) run
Starting program: /usr/bin/date 
Warning: cannot insert breakpoint 1
Cannot access memory at address 100
(gdb) x/64xw $sp   ## examine the stack
0xbefff5d0:	0x00000001	0xbefff719	0x00000000	0xbefff727  ## 1==argc, {0xbefff719, 0}==argv. {0xbefff727, ...-environ
0xbefff5e0:	0xbefff737	0xbefff746	0xbefff758	0xbefff768
0xbefff5f0:	0xbefff77d	0xbefff792	0xbefff7a1	0xbefff7b0
0xbefff600:	0xbefff7b9	0xbefff7cc	0xbefff7d9	0xbefffdc8
0xbefff610:	0xbefffdd4	0xbefffe03	0xbefffe25	0xbefffe3c
0xbefff620:	0xbefffe47	0xbefffe67	0xbefffe74	0xbefffe7c
0xbefff630:	0xbefffe87	0xbefffe98	0xbefffeb7	0xbefffece
0xbefff640:	0xbeffff0f	0xbeffff1f	0xbeffff87	0xbeffffbd
0xbefff650:	0xbeffffd4	0x00000000	0x00000021	0xb6ffc000   ## 0x00000000==end_environ, 0x00000021==start Elf32_auxv
0xbefff660:	0x00000010	0x003fb0d6	0x00000006	0x00001000   ## 0x00000006==AT_PAGESZ, 0x00001000==page_size
0xbefff670:	0x00000011	0x00000064	0x00000003	0x00400034
0xbefff680:	0x00000004	0x00000020	0x00000005	0x00000009
0xbefff690:	0x00000007	0xb6fcf000	0x00000008	0x00000000
0xbefff6a0:	0x00000009	0x00401ef5	0x0000000b	0x000003e8
0xbefff6b0:	0x0000000c	0x000003e8	0x0000000d	0x000003eb
0xbefff6c0:	0x0000000e	0x000003eb	0x00000017	0x00000000
(gdb) q
Quit anyway? (y or n) y
$ 
```
So, @HenryShen210 please run that debugging session on your actual machine, and then report the value for AT_PAGESZ.

**Comment by HenryShen210** [comment]
It's hard for me to install gdb on my running machine, so I use a program with pagesz = getauxval(AT_PAGESZ); and printf("Page size: %lu bytes\n", pagesz); to get page size. I get Page size: 32768 bytes on my test machine.

**Comment by jreiser** [comment]
@HenryShen210 The build succeeded, so you may visit the Actions page https://github.com/upx/upx/actions/runs/10427223385, download the Artifact for any OS flavor, and try out the bulit upx.

**Comment by HenryShen210** [comment]
New upx works on our 4k page and 32k page arm32 environment，thanks
