### ISSUE TITLE
Some static Qt programs crash with error code 0xc0000142 after compressed with some combinations of method and level

### ISSUE THREAD

**Issue by Alex6357** [upx/upx#811]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

Some programs built with static Qt 6.7.0 unexecutable with some combinations of compression level and method. Error code is 0xc0000142.
For example, a file work with lzma/10 and NRV2E/1, but not lzma/1 and NRV2E/10.

## What should have happened?

I think different method and compression level should behave the same.

## Do you have an idea for a solution?

I don't know detailed working progress of upx. But the program need to load data from it. If some data was uncompressed into wrong place in memory it may fail to run. And his is related to my sourcecode. I can use `--best` earlier but not now.

## How can we reproduce the issue?

[app.zip](https://github.com/upx/upx/files/15026699/app.zip)
Compress this exe with `--best` or `--lzma -1`, it will crash. With `-1` or `--lzma --best`, it will run normally.

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 4.2.3
* Host Operating System and version: Windows 11 22631.3520
* Host CPU architecture: amd64
* Target Operating System and version: Windows 11 22631.3520
* Target CPU architecture: amd64

**Comment by jreiser** [comment]
Please consider exploring the PE-specific options for controlling compression of Resources, such as:
```
# upx --help
Options for win32/pe, rtm32/pe & arm/pe:
  --compress-exports=0    do not compress the export section
  --compress-exports=1    compress the export section [default]
  --compress-icons=0      do not compress any icons
  --compress-icons=1      compress all but the first icon
  --compress-icons=2      compress all but the first icon directory [default]
  --compress-icons=3      compress all icons
  --compress-resources=0  do not compress any resources at all
  --keep-resource=list    do not compress resources specified by list
  --strip-relocs=0        do not strip relocations
  --strip-relocs=1        strip relocations [default]
```

**Comment by Alex6357** [comment]
@jreiser Thanks. NRV2E/10 and LZMA/1 worked with `--compress-exports=0`.
LZMA/10 worked with `--compress-exports=1` too. I wonder why.
Still I will close this issue.

**Comment by jreiser** [comment]
> I wonder why.

Speculation: Both NRV and LZMA are derivatives of `deflate`, and the compressed output can contain substrings which are literal byte-for-byte copies of small sub-intervals of the input. If this happens in the "right" place(s), then the de-compressed program might "work" even if it inspects the compressed file.  Among other things, this also suggests that the program should be more careful about validating the contents of Resources.
