### ISSUE TITLE
upx is killed on Gentoo Linux 3.14.51

### ISSUE THREAD

**Issue by alxivnov** [upx/upx#812]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

Running `upx --help` prints `Killed`.

## What should have happened?

I expect to see help.

## Do you have an idea for a solution?

Probably, build settings can be tweaked or minimum Linux kernel can be specified.

## How can we reproduce the issue?

1. Run `upx --help` or `upx --version`
2. Get `Killed` on 4.2.3/3.96
3. Or `PROT_EXEC|PROT_WRITE failed.` on 3.91

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version: Linux 3.14.51
* Host CPU architecture: x86_64
* Target Operating System and version:
* Target CPU architecture:

<img width="962" alt="Снимок экрана 2024-04-20 в 17 14 10" src="https://github.com/upx/upx/assets/19705653/e779f010-df31-426b-bcc6-4ac93b8a4fe7">

**Comment by jreiser** [comment]
Which actual Linux distribution is your Linux 3.14.51 ("1gb-csmlb-cow #8") and where can we get a copy?  We need to reproduce the error in order to diagnose and investigate.

**Comment by alxivnov** [comment]
> Which actual Linux distribution is your Linux 3.14.51, and where can we get a copy? Running `$ uname -a` is a good start.

Distro appears to be Gentoo. It is a shared machine from CSP, but I'll try to provide max info I can.

<img width="344" alt="Снимок экрана 2024-04-20 в 17 30 33" src="https://github.com/upx/upx/assets/19705653/0963c8a6-9593-4734-bde0-a917722ab3cb">

**Comment by jreiser** [comment]
> Distro appears to be Gentoo. It is a shared machine from CSP, but I'll try to provide max info I can.

Gentoo Linux often is re-configured, re-compiled, or re-built by the end user or an intermediary, so we need to know the modifications.  If you can give a downloadable URL to what you actually use, then that will help, too.

**Comment by jreiser** [comment]
General debug starting point: use `strace` to see which system call(s) actually fail.  `$ strace ./upx --help`

Edit: if you can, then please use Copy+Paste with Markdown to post Terminal (console) output. The result is more useful than a screenshot because the posted text can be Copied+Pasted itself.
For inline (less than one line), enclose text between single backtick characters  (hex 0x60, octal 0140, decimal 96; often on a key to the left of the digit '1').  For multiple lines, then bracket the whole paragraph between lines than contain only three backticks.

**Comment by alxivnov** [comment]
> General debug starting point: use `strace` to see which system call(s) actually fail. `$ strace ./upx --help`
> 
> Edit: if you can, then please use Copy+Paste with Markdown to post Terminal (console) output. The result is more useful than a screenshot because the posted text can be Copied+Pasted itself. For inline (less than one line), enclose text between single backtick characters (hex 0x60, octal 0140, decimal 96; often on a key to the left of the digit '1'). For multiple lines, then bracket the whole paragraph between lines than contain only three backticks.

Thanks for responsiveness. Unfortunetely, none of the following commands are available `strace`, `ftrace`, `ltrace`, `perf`, `apt`. As I said, I have limited privileges. I will contact support, but it will take time.
