### ISSUE TITLE
CI failure for powerpc32

### ISSUE THREAD

**Issue by markus-oberhumer** [upx/upx#813]
CI log at https://github.com/upx/upx/actions/runs/8772050272/job/24072073151

File: [upx-devel-eb3c55b-zigcc-powerpc-linux-musl.zip](https://github.com/upx/upx/files/15051999/upx-devel-eb3c55b-zigcc-powerpc-linux-musl.zip)

I've seen this problem before, but it seems to be flaky (or highly dependent on the bytes of the actual program). But this time the CI job did catch it.

How to reproduce:

```sh
$ cd upx-devel-eb3c55b-zigcc-powerpc-linux-musl/zig/powerpc-linux-musl/debug
$ qemu-ppc ./upx -3 --nrv2b upx -o upx-packed-nrv2b
$ qemu-ppc ./upx-packed-nrv2b
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
zsh: segmentation fault (core dumped)  qemu-ppc ./upx-packed-nrv2b
```

**Comment by markus-oberhumer** [comment]
I've rebased your commit onto devel and it seems to work fine, thanks!

Plan for some rainy Sunday:
- [ ] get old Mac G4 and Mac G5 from basement (both dual-boot macOS / Fedora 12)
- [ ] linux-powerpc on G4
  - [ ] test running various UPX packed exes 
  - [ ] compile a recent Valgrind
  - [ ] test running UPX packed exe under Valgrind
- [ ] linux-powerpc64 on G5
  - [ ] test running various UPX packed exes
  - [ ] compile a recent Valgrind
  - [ ] test running UPX packed exe under Valgrind
- [ ] test darwin-powerpc under macOS 10.4 on G4
  - [ ] also install gcc-7 from Tigerbrew and try to compile UPX on G4
- [ ] test darwin-powerpc under macOS 10.5 on G5
  - [ ] also install gcc-7 from Tigerbrew and try to compile UPX on G5

**Comment by markus-oberhumer** [comment]
@jreiser I fear your last patch is not sufficient, I've found another problem with current `devel` branch:

File:  [upx-zigcc-linux-master-486f794-powerpc-linux-musl.zip](https://github.com/upx/upx/files/15069283/upx-zigcc-linux-master-486f794-powerpc-linux-musl.zip)

``` sh
$ cd upx-zigcc-linux-master-486f794-powerpc-linux-musl/build-upx-devel-842d2cb/zig/powerpc-linux-musl/debug
$ qemu-ppc ./upx -3 --nrv2b upx -o upx-packed-nrv2b
$ qemu-ppc ./upx-packed-nrv2b
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
zsh: segmentation fault (core dumped)  qemu-ppc ./upx-packed-nrv2b
```

**Comment by markus-oberhumer** [comment]
So this was a NRV2B decompression bug after all - which explains why it was flaky. Did you double check NRV2D and NRV2E as well?

**Comment by jreiser** [comment]
Fixed; closing.  [Power* is not nice to program.]
