### ISSUE TITLE
CantPackException

### ISSUE THREAD

**Issue by Krammig** [upx/upx#814]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

I might be misunderstanding, but I thought UPX was able to compress .NET DLL's  ?   
If I am mistaken my apologies. 

Trying to copmpress a .NET DLL as follows ; 

upx.exe -5 -k -o mywebservice_1.dll myservice.dll

Error message reads - CantPackException  .NET files not supported yet. 

## What should have happened?

File compressed. 

## How can we reproduce the issue?

1.  Using the command above (assuming that is correct) compress a .NET DLL
2.
3.
4.

## Please tell us details about your environment.

* UPX Current 4.2.3
* Windows 7 and Windows 10
* Intel

**Comment by markus-oberhumer** [comment]
Just as the error says, NET files are unfortunately not supported.
