### ISSUE TITLE
git-e2163d+ failed with 'CantPackException: MemBuffer invalid array index 0 (0 bytes)' message at some ARM EABI5 binaries

### ISSUE THREAD

**Issue by Sfinx** [upx/upx#817]
## What's the problem (or question)?

git-ddf2da+ failed with 'CantPackException: MemBuffer invalid array index 0 (0 bytes)' message at some ARM EABI5 binaries (failing sample attached below). But the  stock ubuntu 22.04 UPX (3.96) packs this binary without any error and binary runs successfully at target platform. 

## What should have happened?

executing latest git upx should produce packed binary

## Do you have an idea for a solution?

No

## How can we reproduce the issue?

Attached is the test binary

[test.zip](https://github.com/upx/upx/files/15175858/test.zip)

test binary pack error with latest upx (no command line arguments given):

```
Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX git-e2163d+ Markus Oberhumer, Laszlo Molnar & John Reiser   Apr 21st 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: a.out: CantPackException: MemBuffer invalid array index 0 (0 bytes)

Packed 1 file: 0 ok, 1 error.

WARNING: this is an unstable beta version - use for testing only! Really.

```

test binary pack message with upx 3.96 (no command line arguments given):

```
Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   2400104 ->   1502576   62.60%    linux/arm    a.out                         

Packed 1 file.
```

## Please tell us details about your environment.

Tried two UPX versions. First is stock Ubuntu 22.04 one and it works ok at the above binary:

```
upx 3.96
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
Copyright (C) 1996-2020 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2020 Laszlo Molnar
Copyright (C) 2000-2020 John F. Reiser
Copyright (C) 2002-2020 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```

Second is latest git one:

```
upx 4.2.3-devel.39+git-e2163d67-dirty
UCL data compression library 1.03
zlib data compression library 1.3.0.1-motley
LZMA SDK version 4.43
doctest C++ testing framework version 2.4.11
Copyright (C) 1996-2024 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2024 Laszlo Molnar
Copyright (C) 2000-2024 John F. Reiser
Copyright (C) 1995-2024 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
Copyright (C) 2016-2023 Viktor Kirilov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```

Host OS: Stock Ubuntu 22.04
Host CPU: AMD Ryzen 7 7840HS
Target Operating System: Armbian 24.5.0
Target CPU architecture: ARM EABI5

**Comment by jreiser** [comment]
Will be fixed shortly.
Note that your build process produces an empty PT_NOTE:
```
$ readelf --segments a.out
Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  NOTE           0x000000 0x00000000 0x00000000 0x00000 0x00000 R   0x4
```

**Comment by Sfinx** [comment]
Yep, I'm removing .note.ABI-tag. Checked: it do not related to bug.

**Comment by Sfinx** [comment]
Oops, related

**Comment by jreiser** [comment]
An unofficial testing version is available in the Artifacts on the Actions page https://github.com/upx/upx/actions/runs/8912734027 .

**Comment by Sfinx** [comment]
Works for me, thanks !
