### ISSUE TITLE
CI failure for i386-linux

### ISSUE THREAD

**Issue by markus-oberhumer** [upx/upx#818]
CI job failure when self-packing `gcc-m32/debug/upx` : https://github.com/upx/upx/actions/runs/8952228091/job/24590028743

Artifact: https://github.com/upx/upx/actions/runs/8952228091/artifacts/1473371890

Can reproduce on my Fedora 40 box when testing the Artifact.

**Comment by jreiser** [comment]
Fixed on branch `jreiser-hatch32` by commit e5546bc8b0a1dd1884e26abbfd62caba7918e5eb.  CI passes https://github.com/upx/upx/actions/runs/8972672014.  Please incorporate into branch `devel`.

**Comment by markus-oberhumer** [comment]
Done, thanks!
