### ISSUE TITLE
packed *.so success but launch failed on Android 7.0

### ISSUE THREAD

**Issue by Qrilee** [upx/upx#82]
## crash on Android 7.0?
I have tested it on Android 5.0 and 6.0 succeed,but failed on Android 7.0

## What should have happened?
the logcat : java.lang.UnsatisiedLinkError:dlopen failed: "/data/app/com.qtfreet.test-1/lib/arm/libqtfreet00.so" has no section headers

## Please tell us details about your environment.
upx 3.93
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Copyright (C) 1996-2017 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2017 Laszlo Molnar
Copyright (C) 2000-2017 John F. Reiser
Copyright (C) 2002-2017 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.

**Comment by jreiser** [comment]
Same as https://github.com/upx/upx/issues/65
