### ISSUE TITLE
upx: build/libhbkeys-amd64.so: CantPackException: PT_NOTE 0x406f18 above stub

### ISSUE THREAD

**Issue by cifaz** [upx/upx#823]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
[Linux](upx: build/libhbkeys-amd64.so: CantPackException: PT_NOTE 0x406f18 above stub)
the application with golang, golang version is go1.22.3

## What should have happened?
execute upx 

## Do you have an idea for a solution?
no

## How can we reproduce the issue?

1. [libhbkeys-amd64.zip](https://github.com/upx/upx/files/15343007/libhbkeys-amd64.zip)
2. upx libhbkeys-amd64.so

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.2.4
* Host Operating System and version: Rocky Linux Rocky Linux
* Host CPU architecture: amd64
* Target Operating System and version: Linux 
* Target CPU architecture: amd64

**Comment by jreiser** [comment]
The static binder (linker) generates this layout:
```
$ readelf --segments libhbkeys-amd64.so
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x000000000040707c 0x000000000040707c  R E    0x200000
  LOAD           0x0000000000407868 0x0000000000607868 0x0000000000607868
                 0x00000000002835ba 0x00000000002ebe98  RW     0x200000
  DYNAMIC        0x0000000000649db0 0x0000000000849db0 0x0000000000849db0
                 0x0000000000000210 0x0000000000000210  RW     0x8
  NOTE           0x0000000000000238 0x0000000000000238 0x0000000000000238
                 0x0000000000000024 0x0000000000000024  R      0x4
  NOTE           0x0000000000407018 0x0000000000407018 0x0000000000407018
                 0x0000000000000064 0x0000000000000064  R      0x4
  TLS            0x0000000000407868 0x0000000000607868 0x0000000000607868
                 0x0000000000000000 0x0000000000000008  R      0x8
  GNU_EH_FRAME   0x00000000004065d0 0x00000000004065d0 0x00000000004065d0
                 0x00000000000001cc 0x00000000000001cc  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x0000000000407868 0x0000000000607868 0x0000000000607868
                 0x0000000000242798 0x0000000000242798  R      0x1
```
The immediate problem is the second PT_NOTE:
```
 NOTE           0x0000000000407018 0x0000000000407018 0x0000000000407018
                0x0000000000000064 0x0000000000000064  R      0x4
```
whose `VirtAddr` 0x407018 is near the high-address end of the first  PT_LOAD  which ends at 0x40707c, and in particular is greater than the last eXecutable Section  `.fini` at 0x3784e4 [`readelf --sections`].  The first eXecutable Section is `.init` at 0x9b838.  The mixing of non-eXecutable linker tables at the beginning of the first PT_LOAD, followed by eXectuable `.plt` and `.text`(etc.), followed by non-eXecutable `.rodata`, is too complex for UPX to handle.  If libhbkeys-amd64 were a main program, then UPX could re-arrange all the PT_NOTEs to lie within the linker tables at the beginning of the first PT_LOAD.  However in a compressed shared library then the UPX runtime de-compression stub is called **after** all linker actions (relocation, etc.), and thus handling the mixture requires much more work.

The workaround for a shared library is to generate all PT_NOTE before any eXecutable Sections.  This should be possible by modifying the schema (`script`) that is used by the static binder.  For the default binutils package, then the default schema is given by the output of `/usr/bin/ld -shared --verbose`, and a modified schema can be invoked using `-T path/to/schema`.

**Comment by jreiser** [comment]
It would be possible to enhance UPX to "exclude a PT_NOTE  at the high end of .text" in addition to the current "exclude this [not so little] region at the low end of .text"; but it's not worth the trouble.

The Go-lang static binder has several pecadillos that it should fix.  Notice that the two PT_NOTEs, the ELF Ehdr, Phdrs, Shdrs, runtime relocation and symbol tables are in an Executable segment (the first PT_LOAD).  They never should be executed, so that's an unnecessary security risk. Fix it by making another PT_LOAD, Read-only and non-Executable, at Offset 0. 
```
 Section to Segment mapping:
  Segment Sections...
   00     .note.gnu.build-id .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .text .fini .rodata .eh_frame_hdr .eh_frame .note.go.buildid
   01     .init_array .fini_array .data.rel.ro .dynamic .got .got.plt .data .go.buildinfo .noptrdata .bss .noptrbss
   02     .dynamic
   03     .note.gnu.build-id
   04     .note.go.buildid
   05     .tbss
   06     .eh_frame_hdr
   07
```

**Comment by markus-oberhumer** [comment]
Is this file built using the official Go toolchain? Maybe the Go team should be notified and asked for feedback.
