### ISSUE TITLE
Please Teach Me How To Crypt my exe File

### ISSUE THREAD

**Issue by skylord17110** [upx/upx#824]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
Please consult the source file upx/README.
```
SHORT DOCUMENTATION
===================

'upx program.exe' will compress a program or DLL. For best compression
results try 'upx --best program.exe' or 'upx --brute program.exe'.

Please see the file UPX.DOC for the full documentation. The files
NEWS and BUGS also contain various tidbits of information.
```
and
```
  - We will *NOT* add any sort of protection and/or encryption.
    This only gives people a false feeling of security because
    all "protectors" can be broken by definition.
```
