### ISSUE TITLE
Golang linux/amd64 binary: CantPackException: bad DT_HASH nbucket=0x7  len=0xc6960

### ISSUE THREAD

**Issue by mdosch** [upx/upx#825]
Dear upx maintainers,

thank you for this useful program.

## What's the problem (or question)?
When trying to compress a golang linux/amd64 binary I get `CantPackException: bad DT_HASH nbucket=0x7  len=0xc6960`, see [here](https://salsa.debian.org/mdosch/go-sendxmpp/-/jobs/5756033#L53).

## What should have happened?
I'd expected upx to successfully compress the binary as it does for linux/arm64 and win/amd64.

## Do you have an idea for a solution?
Sorry, no idea.

## How can we reproduce the issue?

1. Download [the binary from the linked CI job](https://salsa.debian.org/mdosch/go-sendxmpp/-/jobs/5756033/artifacts/raw/linux-amd64/go-sendxmpp?inline=false)
2.  Try to compress it using upx

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.2.2 (debian bookworm-backports and sid/unstable)
 ```
upx 4.2.2
UCL data compression library 1.03
zlib data compression library 1.3.0.1-motley
LZMA SDK version 4.43
doctest C++ testing framework version 2.4.11
Copyright (C) 1996-2024 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2024 Laszlo Molnar
Copyright (C) 2000-2024 John F. Reiser
Copyright (C) 2002-2024 Jens Medoch
Copyright (C) 1995-2023 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
Copyright (C) 2016-2023 Viktor Kirilov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```
* Host Operating System and version: Debian sid/unstable (local), registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v16.11.1 (CI)
* Host CPU architecture: amd64 (local sid machine), x86_64 (CI)
* Target Operating System and version: Linux
* Target CPU architecture: amd64

**Comment by mdosch** [comment]
I build 4.2.4 and now I get a different error:

```
 upx --version
upx 4.2.4
UCL data compression library 1.03
zlib data compression library 1.3.1.1-motley
LZMA SDK version 4.43
doctest C++ testing framework version 2.4.11
Copyright (C) 1996-2024 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2024 Laszlo Molnar
Copyright (C) 2000-2024 John F. Reiser
Copyright (C) 1995-2024 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
Copyright (C) 2016-2023 Viktor Kirilov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```

```
upx ./go-sendxmpp\(1\)                           
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX 4.2.4       Markus Oberhumer, Laszlo Molnar & John Reiser    May 9th 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: ./go-sendxmpp(1): CantPackException: bad DT_STRSZ 0x28e

Packed 0 files.
```

**Comment by jreiser** [comment]
Please try an Artifact (build) from the Actions page https://github.com/upx/upx/actions/runs/9183263218 which should fix this Issue.

**Comment by mdosch** [comment]
Thank you for the incredible fast fix, it works:

```
upx-jreiser-issue825-784ddbf-zigcc-x86_64-linux-gnu.2.3.4/zig/x86_64-linux-gnu.2.3.4/release/upx go-sendxmpp\(1\) 
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX git-784ddb  Markus Oberhumer, Laszlo Molnar & John Reiser   May 10th 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   8728897 ->   3390840   38.85%   linux/amd64   go-sendxmpp(1)                

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
```

**Comment by jreiser** [comment]
@markus-oberhumer Please incorporate the fix commit https://github.com/upx/upx/commit/784ddbf8d775cd3dfdf0896af166be62a943382f from branch `jreiser-issue825` into the `devel` branch.

**Comment by markus-oberhumer** [comment]
Done.
