### ISSUE TITLE
Two use-of-uninitialized-memory bugs in UPX

### ISSUE THREAD

**Issue by Heinzeen** [upx/upx#827]
## What's the problem?
While running tests on UPX, we found 2 use-of-uninitialized-memory bugs. In detail:

1. Out-of-bound read causes uninitialized memory to be used in function `get_ne32`.
2. The variable `bb` is used uninitialized in function `ucl_nrv2b_decompress_safe_le32`, called by `upx_decompress`.

## What should have happened?
1. Detect the potential out-of-bound read and behave accordingly.
2. Avoid using uninitialized memory.

## Do you have an idea for a solution?

The complexity of the project makes it non-trivial to understand the codebase for people who have never worked on it, but we tried running some tests to help you in the analysis of the bugs we are reporting. We are summarizing here the results of our analysis:

1. in [src/pmach.cpp:1782](https://github.com/upx/upx/blob/devel/src/p_mach.cpp#L1782) the buffer `buf3` is accessed starting by offset 1 for a total of 4 bytes. (i.e. from byte 1 to byte 4). With this specific input file, the variable `bufsize`, which defines the length of `buf3`, seems to be set to 4, so reading 4 bytes starting from byte 1 will result in reading 1 byte over the memory allocation. In this case, checking the `bufsize` variable and behaving accordingly before proceeding with the execution might prevent the out-of-bound memory access.
2. in file `src/ucl/srcn2b_d.c:62`, the call `getbit(bb)` appears to overrun the `src` buffer. Due to the code being non-trivial, we are unsure why this is happening and how to fix it. It is possible that the `src` buffer contains data that is not properly terminated, resulting in the check `bb & 0x7f` to fail on detecting the end of the buffer and thus causing an overrun. In this case, ensuring the correct termination of the buffer before executing this function should solve the issue.

## How can we reproduce the issue?
In the [attached archive](https://github.com/user-attachments/files/15546409/upx-uninit.zip), you will find:

- the executable used for our tests 
- the testcase used to trigger the bugs
- the stacktrace when each bug was observed
- the output of Valgrind
- a directory `uninit` containing numbered directories, one for each bug, containing the mentioned files (i.e. testcase, stacktrace and valgrind’s output)

The executable is one of the fuzzing harnesses you made available for OSS-Fuzz (namely, [test_packed_file_fuzzer](https://github.com/google/oss-fuzz/blob/master/projects/upx/fuzzers/test_packed_file_fuzzer.cpp)), compiled with a main function that opens a file, reads its content and calls LLVMFuzzerTestOneInput with it. To observe the bugs, a memory error detection tool like valgrind is needed; it can be run with a command line similar to `valgrind --track-origins=yes ./test_packed_file_fuzzer uninit/1/testcase`.

When we tried building the fuzzing harnesses from the OSS-Fuzz building system, we had problems in one of the early steps; in particular, the `git apply` command in `build.sh` file kept resulting in an error. We investigated and we think this is due to a change made to the `CmakeLists.txt` after the initial release for OSS-Fuzz, which was probably not followed by an update of the relative patch file. In the archive, you will also find the custom `build.patch` file we created to compile this version of the fuzzing harnesses.

## Please tell us details about your environment.
* UPX version used: commit hash 3495d1a, latest at the time of testing.
* Host Operating System and version: reproduced on both Ubuntu 22.04 and Ubuntu 20.04
* Host CPU architecture: x86_64
* Compiler: clang 18.0

**Comment by jreiser** [comment]
@markus-oberhumer  Please incorporate branch `jreiser-issue827` which contains two fixes, into the branch `devel`. The ContinuousIntegration tests succeed.

**Comment by markus-oberhumer** [comment]
Done.
