### ISSUE TITLE
CantPackException: relocs overflow

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#829]
@markus-oberhumer @jreiser @ml1050 

## What's the problem (or question)?
error while compressing exe

## What should have happened?
compress w/o error

## Do you have an idea for a solution?
nope

## How can we reproduce the issue?
1. compress attached sample with "--overlay=copy --compress-icons=1 --lzma --best --force" flags
[relocs overflow.zip](https://github.com/user-attachments/files/15736414/relocs.overflow.zip)

## Please tell us details about your environment.
* UPX version used (`upx 4.3.0-git-40b7e24fcc08
UCL data compression library 1.03
zlib data compression library 1.3.1.1-motley
LZMA SDK version 4.43
doctest C++ testing framework version 2.4.11):
* Host Operating System and version: win11
* Host CPU architecture: x64
* Target Operating System and version: win11
* Target CPU architecture: x64

**Comment by markus-oberhumer** [comment]
Broken program:

```
upx-4.2.4: relocs overflow.exe: CantPackException: bad reloc size_of_block 0
```
