### ISSUE TITLE
Incorrect size of win32 file on packing

### ISSUE THREAD

**Issue by TrueCat17** [upx/upx#832]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

size of file: 10.8 MB

>upx -9 file.exe
>upx -d file.exe

size of file: 10.5 MB

(level 1 instead of 9 - no changes)

Also, file works, but more AntiViruses (on virustotal) start talking about bad things (and Google Drive blocks zip with compressed file)

## What should have happened?

File size must have original value (btw, ok for v. 3.96)

## Do you have an idea for a solution?

Some change from 3.96 (debian 'oldstable' repo) to 4.2.2 (debian 'sid' repo) is bad

## How can we reproduce the issue?

1. upx -9 file.exe
2. upx -d file.exe
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.2.2
* Host Operating System and version: Debian (Sid)
* Host CPU architecture: amd64
* Target Operating System and version: win7+
* Target CPU architecture: i386

[file.zip](https://github.com/user-attachments/files/15859530/file.zip)

**Comment by bitraid** [comment]
That's because the relocation section is not needed and it's being striped. Use `--strip-relocs=0` if you want to keep it. Older versions just zeroed it out instead of completely removing it.

**Comment by TrueCat17** [comment]
Thanks, it worked

Perhaps it’s not worth completely deleting this section, since antiviruses react so strongly to it?
Is it possible to insert some kind of “stub”?

**Comment by bitraid** [comment]
This section is not mandatory for all files. This is an executable without ASLR, and the section could simply be omitted by a linker flag. It could also be removed with `strip -R .reloc`. I also checked with VirusTotal, and the false positive trigger by some AVs, doesn't happen because of the missing section, but from the compression.

**Comment by TrueCat17** [comment]
But then why `--strip-relocs=0` solves the problem with antiviruses?
Does this parameter somehow affect compression?

**Comment by bitraid** [comment]
> But then why `--strip-relocs=0` solves the problem with antiviruses?

I don't see solving it. Current scans show:
- `upx --strip-relocs=0` (7/71): https://www.virustotal.com/gui/file/aed06cbcc82a70729f6ca4c9c0f5784f77d0d5786376ab0a85ce30d610e5cc48
- `upx --strip-relocs=0 -9` (8/72): https://www.virustotal.com/gui/file/5a882f34aae9d9bfc398e716b0665293dc72bed1ea6ab0d651504840ee86c243
- `upx --strip-relocs=0 --lzma` (6/71): https://www.virustotal.com/gui/file/b07fb6cc49f1f52b9fe0e80ef1b9a6285d9f11e4120bba2c43aedc64b99f38ac

**Comment by TrueCat17** [comment]
Yes, but without this param - 17/73 (just `upx -9`):  
https://www.virustotal.com/gui/file/02c6db3ed57546db8d1d56d9b71b0a4ab8b09c00048541a9c4308806198fbb79

17 >> 7
It is important

**Comment by bitraid** [comment]
That's totally random. On a different file, you could observe the complete opposite (or no detection at all).

**Comment by markus-oberhumer** [comment]
This is obviously not a UPX issue, so closing.
