### ISSUE TITLE
checksum error de-compressing ELF with  large .p_align and small blocksize

### ISSUE THREAD

**Issue by jreiser** [upx/upx#836]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

When an ELF executable has a large "PT_LOAD gap", then in some cases  the checksum of a compressed gap is computed incorrectly.  The error occurs for any gap which has a non-compressible piece when partitioned into `blocksize` pieces. (Because the gap is usually all-zero, then any incompressible piece must be a small final piece, such as about 9 bytes or fewer.) The `blocksize` is the largest .p_filesz in the entire input file, except that the region from the last (.p_filesz + .p_offset) to end-of-file also acts like the .p_filesz of a "phantom" PT_LOAD.  The gap is the distance between (.p_filesz + .p_offset) and the .p_offset of the next PT_LOAD (or end-of-file). The error occurs because the checksum of a large gap is computed incorrectly when a piece is not compressible.  The error cannot occur if the largest .p_filesz is at least one-half of .p_align.
## What should have happened?

Always compute the checksum of the gap correctly.
## Do you have an idea for a solution?

One-line patch coming soon. 
## How can we reproduce the issue?

Compress these files in upx-testsuite-v2, then try to de-compress them (`upx -d` or `upx -t`):
```
files/all/armeb-linux.elf/upx_test04_sf_a_exe_dynamic_pie_c.out
files/all/arm-linux.elf/upx_test04_hf_a_exe_dynamic_pie_c.out
files/all/arm-linux.elf/upx_test04_hf_t_exe_dynamic_pie_c.out
files/all/powerpc-linux.elf/upx_test04_hf_exe_dynamic_nopie_x.out
```
Each file has .p_align = 0x10000 (64KiB) with maximum .p_filesz of 0x2980.  The largest .p_filesz is smaller than (0x10000 / 2).
## Please tell us details about your environment.

* UPX version used (`upx --version`): upx-4.2.4.   `git blame` says that the bug has existed since 2005-02-20.
* Host Operating System and version:  Linux 6.8.9 (any supported by upx)
* Host CPU architecture: x86_64 (any supported by upx)
* Target Operating System and version: same as Host
* Target CPU architecture: same as Host

**Comment by jreiser** [comment]
Branch jreiser-issue836 passes CI Actions https://github.com/upx/upx/actions/runs/9815779701 and upx-testsuite-v2 and local "make run-testsuite".  @markus-oberhumer please incorporate into branch devel.

**Comment by markus-oberhumer** [comment]
I have merged the commit `Fix checksum error de-compressing ELF with large .p_align and small blocksize` as the other commit seems to refer to issue #834
