### ISSUE TITLE
CantPackException: mem_size 2 couldn't be a more cryptic error message!

### ISSUE THREAD

**Issue by psommerfeld** [upx/upx#842]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

Have an AppImage of size 746897792 bytes. Get "CantPackException: mem_size 2; take care".
I followed the code a bit. Turns out this  means an exe that is > UPX_RSIZE_MAX.

## What should have happened?

util.cpp's mem_size is very cryptic. Shouldn't have to search the source code to understand the failure.
At least just copy the condition that caused the throw into the exception message:
    if very_unlikely (n > UPX_RSIZE_MAX)
--        throwCantPack("mem_size 2; take care");
++       throwCantPack("n > UPX_RSIZE_MAX; executable is too big to handle");

## Do you have an idea for a solution?

My first time hearing about and using UPX
Change util.cpp:mem_size() to give useful throw messages.

## How can we reproduce the issue?

1.  Find exe_file > 768 MB
2. upx exe_file

## Please tell us details about your environment.

* UPX version used (`upx --version`):upx 4.2.4
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.3.1.1-motley
LZMA SDK version 4.43
Copyright (C) 1996-2024 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2024 Laszlo Molnar
Copyright (C) 2000-2024 John F. Reiser
Copyright (C) 1995-2024 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
* Host Operating System and version:
Linux on ChromeOS
* Host CPU architecture:
x64
* Target Operating System and version:
Same
* Target CPU architecture:
Same

**Comment by jreiser** [comment]
Using upx-4.2.4 (the current release), then the recipe doesn't always produce a nasty message.

I started with the `demo.exe` file of Issue #670, which is 149,934,080 bytes.  Then I enlarged the file by appending 800 MiB of zeroes: `dd if=/dev/zero bs=4M count=200  |  cat issue670/demo.exe - > foo.exe`, which produced a `foo.exe` of 988,794,880 bytes. Running upx:
```
$ upx-4.2.4-amd64_linux/upx -f -o foo.upx foo.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX 4.2.4       Markus Oberhumer, Laszlo Molnar & John Reiser    May 9th 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: foo.exe: IOException: file is too large -- skipped

Packed 0 files.
```
So in this case, upx-4.2.4 already is nicer than alleged.  Perhaps the recipe can be made more specific?

**Comment by markus-oberhumer** [comment]
Indeed we could just say

   `CantPackException: unsupported exectuable` 

But we have decided to attach some internal technical details to our error messages.

Sorry if this confuses you, but WONTFIX.
