### ISSUE TITLE
I get this error 

### ISSUE THREAD

**Issue by Aggelos11** [upx/upx#846]
upx: /var/www/html/folder1/backdoor5.exe: CantPackException: GUARD_CF enabled PE files are not supported (use --force to disable)
Packed 1 file: 0 ok, 1 error.
root@kali:/opt/upx-4.2.4-amd64_linux#

**Comment by jreiser** [comment]
Just like the error message says, upx does not support compression of a PE file which enables GUARD_CF.  If you want to compress the file, then you can (re-compile and) re-build the file without GUARD_CF.  Or, you can try using the `--force` flag when invoking upx to compress the file, and when executing the compressed file, then use some operating system feature to turn off or ignore the checking that would be activated by GUARD_CF.

**Comment by Aggelos11** [comment]
What is guard _cf? Why it’s enabled? I just wrote a python script and compiled it with pyinstaller

**Comment by jreiser** [comment]
> What is guard _cf? Why it’s enabled?

Google is your friend.  GUARD_CF is a feature which tries to increase security against some forms of malicious attack.  Check the documentation for pyinstaller for any method to turn off GUARD_CF.
