### ISSUE TITLE
ssssss

### ISSUE THREAD

**Issue by ehsanfoolade** [upx/upx#850]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by BlobTheKat** [comment]
I think this issue should be put on higher priority, it's really breaking my workflow 😕
