### ISSUE TITLE
NotCompressibleException

### ISSUE THREAD

**Issue by MStratton64** [upx/upx#851]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
I am trying to compress a vfp9 32bit exe and am getting "upx: ramsys.exe: NotCompressibleException"
## How can we reproduce the issue?

1. I am running ipx ramsys.exe
2.I can provide this exe if required
3.
4.

## Please tell us details about your environment.

* UPX version used UPX 4.2.4:
* Host Operating System and version: Windows 11
* Host CPU architecture: X64
* Target Operating System and version: All versions of windows at or above Windows XP
* Target CPU architecture: x64

**Comment by jreiser** [comment]
> 2.I can provide this exe if required

Yes, a reproducible test case is required.  So please "Paste, drop, or lick to add files", or state a URL, or email the file to me as an attachment.

**Comment by MStratton64** [comment]
[POS_COMM.zip](https://github.com/user-attachments/files/17104304/POS_COMM.zip)
Hi Thanks for your response, the one I was trying to compress is too big, I have a attached a smaller one with the same issue :)
![24-09-2024 9-15-35 AM](https://github.com/user-attachments/assets/17f2c377-f966-43a2-a882-110cbefd4af4)

**Comment by bitraid** [comment]
This file consists of an exe stub of about only 30kb, and the rest is the Fox Pro ".app" file, appended as overlay data. The ".app" file is already compressed, but even if it wasn't, UPX doesn't compress overlay data. So, it would only try to compress the first part, but it can't, because it's too small, thus the `NotCompressibleException` message (if the size doesn't decrease with ZIP, it won't with UPX either).

**Comment by MStratton64** [comment]
Ah OK that explains it, thank you for this.

**Comment by cieplutki** [comment]
> and the rest is the Fox Pro ".app" file, appended as overlay data. The ".app" file is already compressed

Do you know what compression is used there? I tried lzma and deflate but it's not it.

**Comment by MStratton64** [comment]
I believe it is handled internally by FoxPro's own packaging and compression mechanisms
