### ISSUE TITLE
document if chocolatey support is official

### ISSUE THREAD

**Issue by gogo2464** [upx/upx#853]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

I see the upx on chocolatey at the address https://community.chocolatey.org/packages/upx but I see no issue about that on upx issues. 

## What should have happened?

 I have already got a malware from chocolatey (supply chain attack) for another software.

## Do you have an idea for a solution?

Could we create documentation online to ensure this is official please?

## How can we reproduce the issue?

1. watch https://community.chocolatey.org/packages/upx
2. see that there is no official doc about on upx

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version: windows 11
* Host CPU architecture: amd64
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
See the pinned Issue https://github.com/upx/upx/issues/437 , "False positive antivirus alerts of official UPX releases".  The user of UPX should consult the Chocolatey report, determine the identity of the anti-virus vendor(s) which has flagged UPX, then consult with that vendor about its mistaken detection of UPX as malware.

**Comment by gogo2464** [comment]
Not any av has been triggered by chocolatey. 

I would like still to ensure that upx is responsible of chocolatey port please?

**Comment by jreiser** [comment]
> I would like still to ensure that upx is responsible of chocolatey port please?

UPX has no connection to chocolatey.  See https://upx.github.io/ for official information and URL to releases https://github.com/upx/upx/releases/tag/v4.2.4 .

**Comment by gogo2464** [comment]
thank you. it is probably a malware then.

**Comment by gogo2464** [comment]
imho you should probably react

**Comment by jreiser** [comment]
The only sure correct source of pre-built UPX is from the page designated by the Download button on https://upx.github.io/ , which currently points to  https://github.com/upx/upx/releases/tag/v4.2.4 .  Any other source is suspect as unreliable.  Or, you can build UPX yourself from the git sources; use the git tags to choose the release version.  UPX uses UCL, and officially-released pre-built versions of UPX use a compatible private version of UCL which compresses better than the publicly-available UCL.  The `--lzma` compressor is the same, and almost always produces smaller compressed output than UCL, but has greater CPU cost for run-time de-compression.

**Comment by gogo2464** [comment]
@jreiser could we add upx build from source to an official upx support please? then we could ask to remove the old.

**Comment by jreiser** [comment]
Official builds of UPX from anything other than a designated official release are unlikely.  However, Action builds from Continuous Integration may be a suitable substitute.  Any check-in to the official GitHub repo https://github.com/upx/upx.git initiates a build.  These builds are tracked on the Actions page https://github.com/upx/upx/actions which can be reached by the Actions button in the GitHub menu bar at the top of an Issue.  In addition to building from a clean check-out of the source, an Action build runs tests for self-consistency (compress, de-compress, identify, ...) on each supported platform.  (A build for official release involves more thorough testing of many more test cases.)  Interpreting a failed Action build often requires investigating _why_ the build failed.  For instance, currently the **zig** tools are not available on some platforms, so the sub-build for such a platform will fail.

**Comment by joachimschmidt557** [comment]
Hi, maintainer of the upx chocolatey package here. It is correct that this is not an official package. However, the package is **not malware**. You can check the checksums of the [zip files included](https://community.chocolatey.org/packages/upx#files) (click on the <kbd>Show</kbd> button) in the chocolatey package with those in the corresponding GitHub release, they are identical.

The process of creating and publishing these chocolatey packages is completely open source and transparent. You can inspect the source code for the [updater script](https://github.com/joachimschmidt557/chocolatey-packages-manual-automatic/tree/master/automatic/upx) yourself. The updater scripts are not run by me, but by [AppVeyor](https://ci.appveyor.com/project/joachimschmidt557/chocolatey-packages-manual-automatic) automatically.

That being said, while all current chocolatey packages of upx are the official binaries, there is no 100% guarantee that future chocolatey packages are safe: Chocolatey servers, AppVeyor servers, my Github account, my chocolatey account, etc. could all be compromised and used to publish a malicious package version. If you want to minimize that risk, do consider using a different way of downloading an up-to-date version of upx, bearing in mind that no version will reduce the risk to 0%, as even this repository or GitHub servers could be compromised.

I take security very seriously. If you suspect a compromise in the package creation process, do reach out directly to me via email please :)
