### ISSUE TITLE
change algorithm to bypass yara rules

### ISSUE THREAD

**Issue by gogo2464** [upx/upx#854]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

Many other issues on this repo state UPX programs are detected to be malwares as upx is often used by malware.

## What should have happened?

Upx packed program should not be considered as malware. No matter if the upx usage comes from a wish to spend too much memory or if it comes from a wish to create real malware for cyber security infrastructure audit.

3 years ago I was going to prepare a memory of what I did at school to bypass malware based on a compiler implementation. In this feature I would like to bypass yara rules designed to upx (accidental or not) by changing the generator algorithm and set it yara rules as input to upx before generation to finally generate a specific packed program that will not contains such signature based on inputed rules syntax.

## Do you have an idea for a solution?

This will be a really long term PR. If you think it sounds not UPX related, I could fork and do my own repo.

## How can we reproduce the issue?

1. 
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
See pinned Issue #437," False positive antivirus alerts of official UPX releases."  The user of UPX should consult with the antivirus vendor(s) in order to change the vendor software to avoid automatic flagging of UPX-compressed executables as suspect.  UPX co-operates fully with A-V vendors by providing a de-compressor (`upx -d`) so that the A-V vendor can scan the de-compressed software, and avoid mistakely identifying UPX compression as a source of suspicion.

**Comment by gogo2464** [comment]
Thank you for the reply.

I would like to provide a different answer. Should i fofk upx and then modify my own repo with no merging?

**Comment by jreiser** [comment]
Forking the GitHub repo for UPX, then doing your own development in the forked repo, would be best for now.  UPX is not interested in the apparent complexity of the described feature.

**Comment by gogo2464** [comment]
Sure no issue.

When should be the next very stable release please? I would like to build upon.

**Comment by jreiser** [comment]
The next stable release is decided by Markus.  The date is unpredictable, but history of previous years suggests some time in the next three months. Meanwhile, the recent build https://github.com/upx/upx/actions/runs/11239291138 for branch `jreiser-pagebig` is the bugfix branch that is closest to release.  Branch` jreiser-ELF2` is the branch with newest features which might get merged into a release.  See https://github.com/upx/upx/actions for builds from all check-ins.

**Comment by gogo2464** [comment]
great thanks!

**Comment by gogo2464** [comment]
@jreiser could you ping me when the next stable release will be released please?

**Comment by jreiser** [comment]
@gogo2464 OK.  Although there is precedent for a stable release sometime in the next three months or so, nevertheless the date is unknown, unpredictable, and the lead time between the decision to release and actual release can be only a few days.

**Comment by gogo2464** [comment]
yes sure. I just would like to be pinged.
