### ISSUE TITLE
UPX compressing for other target architectures

### ISSUE THREAD

**Issue by iselind** [upx/upx#86]
## What's the problem (or question)?

I have UPX installed on my x86_64 machine running Debian Wheezy, the go binaries i want to compress are intended to run on ARM and Little Endian MIPS. My question is if there is anything specific i need to think about when compressing the go binaries as the target and host systems are not the same architecture. Do i need to include some library built for my target for the de-compression to work here?

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.08
* Operating System and version: Debian Wheezy
* CPU architecture:
HOST: x86_64
TARGET: ARM and Little endian MIPS

**Comment by iselind** [comment]
To clarify a bit, my target systems doesn't have anything UPX/UCL related installed today.

**Comment by markus-oberhumer** [comment]
Any host version can cross-compile all supported target archs.

**Comment by iselind** [comment]
So the de-compression is completely CPU architecture agnostic?

Doesn't the target system need some knowledge how to de-compress the UPX compressed binary? Some library or similar?
Is the loader really able to work things out on its own?

**Comment by iselind** [comment]
@markus-oberhumer The reason i ask is that i'm having difficulties getting the compressed GO binary for linux/mipsel to run.

UPX detects that it's indeed a linux/mipsel binary i'm trying to compress.

**Comment by iselind** [comment]
I am able to get things to run well for ARM but MIPS i've not yet succeeded on. The mips is a mipsisa32r2el if it matters.

**Comment by markus-oberhumer** [comment]
Please open a new issue for the linux/mipsel problem.

**Comment by iselind** [comment]
Created #87 as requested
