### ISSUE TITLE
NotPackedException: not packed by UPX

### ISSUE THREAD

**Issue by Vazza202** [upx/upx#860]
When I use upx to compress my file, I've made edits to where upx can't decompress it with the -d command but I want to take it further and make it throw this exception  NotPackedException: not packed by UPX... I've looked through the code all day and found p_exe.cpp packer.cpp, packhead.cpp, packhead.h, packmast.cpp, packmast.h, except.cpp, except.h and I have been trying to follow the code logic to track it down, idk if it's because I'm exhausted or what and I feel like it in front of my eyes. Still, it's just not coming to me on what the code is doing to make it throw the exception or what it's looking for or checking before the decompression so I can make edits to the binary or the code but I prefer the binary.

If anyone can help out, I would appreciate it. thanks.

**Comment by jreiser** [comment]
> upx can't decompress it with the -d command

When `upx -d` gives up (abandons further work), then there is always a message of some kind. Display the messsge.  Run under a debugger and show the traceback. Also give details of the environment: OS and version, version of UPX, etc.

**Comment by Vazza202** [comment]
I'm under Windows 11

the version of upx is 4.2.4.


So when I add an unpacked file it says NotPackedException: not packed by UPX

with my packed file I modified the binary to try and throw off upx detecting that it has been packed by upx... then when I try to decompress it, it gives a upx: "PACKED.exe: CantUnpackException: file is possibly modified/hacked/protected; take care!" message...


what I'm trying to achieve is... to get it to say "NotPackedException: not packed by UPX" by editing the binary more or editing the 
source code... I rather edit the binary but if needed I'll edit the code. 

The problem is I don't know what upx is looking for so I can edit it. i modified the headers, I modified the section headers, I picked apart the binary for more obfuscation as well but it's still not triggering the "NotPackedException: not packed by UPX"

**Comment by jreiser** [comment]
> Run under a debugger and show the traceback.

@Vazza202  Please heed that earlier advice. Attempting to debug just by reading code tends to be **extremely** slow and exhausing. **GET A DEBUGGER**: a program which greatly assists.  There are free (no monetary cost) debuggers, such as MSVC Community Edition (https://visualstudio.microsoft.com/downloads/), and  gdb on Linux or Cygwin (https://cygwin.com/) or WSL (Windows Subsystem for Linux).  There are also other free debuggers, as well as paid commercial debuggers.

Also, do a github `clone` of the source for upx, then `make build/debug; cd build/debug; cmake --build .`

**Comment by Vazza202** [comment]
The reason i'm not using a debugger is because I thought you guys would know right of the bat lmao... you're a contributor... how do you not know?

I'm using xdbg debugger... what do you want me to look for?? 

"When upx -d gives up (abandons further work), then there is always a message of some kind. Display the messsge. Run under a debugger and show the traceback. Also give details of the environment: OS and version, version of UPX, etc." 

maybe give some context on what I'm looking for... you expect people to run off "give a traceback"? a trace back of what? lmao come on dude.

**Comment by bitraid** [comment]
What you're trying to do is against the [licence](https://github.com/upx/upx/blob/devel/LICENSE) of UPX:

```
 - We grant you special permission to freely use and distribute all UPX
    compressed programs. But any modification of the UPX stub (such as,
    but not limited to, removing our copyright string or making your
    program non-decompressible) will immediately revoke your right to
    use and distribute a UPX compressed program.

  - UPX is not a software protection tool; by requiring that you use
    the unmodified UPX version for your proprietary programs we
    make sure that any user can decompress your program. This protects
    both you and your users as nobody can hide malicious code -
    any program that cannot be decompressed is highly suspicious
    by definition.
```

So, I don't think that helping a noob do that is right. Also, have in mind that even if you manage to do what you're trying to, the program can be easily unpacked and dumped by a debugger like x64dbg, in less than a minute.

**Comment by Vazza202** [comment]
lmao you aint dumping shit nerd calm down. when giving source code expect it to be customized.

It can't be unpacked if the source code is modified to your own dumb ass lmao fucking noob doesn't understand what source code is.
