### ISSUE TITLE
Compressed linux/mipsel binary refuse to start

### ISSUE THREAD

**Issue by iselind** [upx/upx#87]
## What's the problem (or question)?

As requested in #86 i create a new ticket for the linux/mipsel issue i'm having.

I am compressing Go programs for MIPS and ARM architectures. For ARM everything seems to work just fine but I cannot get the MIPS binaries to start.

The MIPS binaries are correctly detected as linux/mipsel (little endian mips) during compression. The achitecture that is intended to run the compressed binary is mipsisa32r2el.

## What should have happened?

The compressed binary should be possible to start

## Do you have an idea for a solution?

No, sorry

## How can we reproduce the issue?

I reproduce the problem with 100 % certainty using these steps
1. build github.com/prometheus/node_exporter with GOOS=linux and GOARCH=mipsle set in the environment. The build result will be a binary named node_exporter. Yes, the GOARCH should be mipsle, not mipsel, as that's the cross compile target for Go apps.
2. cp node_exporter node_exporter_working
3. upx node_exporter
node_exporter_working start just fine on the target system while node_exporter doesn't even print the initial messages.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.08
* Operating System and version: Debian Wheezy
* CPU architecture: 
HOST: x86_64
TARGET: mipsisa32r2el

**Comment by markus-oberhumer** [comment]
Please try upx 3.93. Also this might be fixed in the current devel branch.

**Comment by iselind** [comment]
I tried using https://github.com/upx/upx/releases/download/v3.93/upx-3.93-amd64_linux.tar.xz and it actually start. =)

**Comment by iselind** [comment]
Thanks a lot for your time, much appreciated!

**Comment by ZenBoy999** [comment]
I got the same issue on 3.96 the latest version, and found v3.93 is working for the MediaTek MT7621 Soc.
