### ISSUE TITLE
segfaults when compressing a binary

### ISSUE THREAD

**Issue by untoreh** [upx/upx#88]
## What's the problem (or question)?
binary in question: terraform
the terraform binary compressed using upx (tried `-1` or `--best`) segfaults using this version
( alpine version )
upx 3.93
UCL data compression library 1.03
zlib data compression library 1.2.8
LZMA SDK version 4.43

## What should have happened?

no segfaults
## Do you have an idea for a solution?

the same binary does not segfaults after compression when using this version
( ubuntu version )
upx 3.91
UCL data compression library 1.03
LZMA SDK version 9.22 beta
## How can we reproduce the issue?

1. `wget https://releases.hashicorp.com/terraform/0.9.2/terraform_0.9.2_linux_amd64.zip`
2. `upx -1 terraform`
3. `./terraform`

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Operating System and version: alpine/ubuntu
* CPU architecture: x86_64

**Comment by untoreh** [comment]
the version from github has no problems so maybe it is related to musl
upx 3.93
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43

**Comment by markus-oberhumer** [comment]
If our official release works then please close this issue and report the problem to your distribution.

**Comment by untoreh** [comment]
is it distribution related if it depends on musl? the problem appears both on voidlinux-musl and alpine

**Comment by jreiser** [comment]
There might be interaction with specific Linux kernels.  Please report "uname -a" (and the version of 'musl') for each case, and identify whether success or failure.

**Comment by untoreh** [comment]
the test were run under docker, so the kernel is the same, you can take the alpine  kernel as reference I suppose
`Linux u1 4.4.59-0-virtgrsec #1-Alpine SMP Tue Apr 4 08:37:50 GMT 2017 x86_64 Linux`

**Comment by markus-oberhumer** [comment]
UPX builds fine and passes the whole testsuite under AlpineLinux 3.2 to 3.5 - see

https://github.com/upx/upx-automatic-builds/tree/gitlab-20170407-cdddf56-gitlab  

So this is some other problem not related to UPX.
