### ISSUE TITLE
corrupted compression of the Mach/i386 files

### ISSUE THREAD

**Issue by micsuka** [upx/upx#9]
## What's the problem (or question)?

We cross compile on Linux to Mac and compress it with upx 3.91. The upx compiled from the devel/travis branches is not able to compress/decompress my exe on the host system (not running it on Mac yet). The UPX apparently corrupts the binary, decompression crashes.

e.g.: upx.out main, then upx.out -d main crashes. Here is the call stack:

> Core was generated by `./upx.out -d main'.
> Program terminated with signal 11, Segmentation fault.
> # 0  0x000000000045bf6c in PackMachBase<N_Mach::MachClass_64<N_BELE_CTP::LEPolicy> >::canUnpack (this=0x1995010) at p_mach.cpp:1969
> 
> 1969            if (lc_seg == ptr->cmd) {
> (gdb) where
> # 0  0x000000000045bf6c in PackMachBase<N_Mach::MachClass_64<N_BELE_CTP::LEPolicy> >::canUnpack (this=0x1995010) at p_mach.cpp:1969
> # 1  0x00000000004842d8 in try_unpack (p=0x1995010, user=0x7ffec7ffbc00) at packmast.cpp:128
> # 2  0x0000000000485463 in PackMaster::visitAllPackers (func=0x484251 <try_unpack(Packer*, void*)>, f=0x7ffec7ffbc00, o=0x7ffec7ffbdb8, user=0x7ffec7ffbc00)
> 
> ```
> at packmast.cpp:332
> ```
> # 3  0x000000000048592c in PackMaster::getUnpacker (f=0x7ffec7ffbc00) at packmast.cpp:368
> # 4  0x00000000004859ce in PackMaster::unpack (this=0x7ffec7ffbda0, fo=0x7ffec7ffbcd0) at packmast.cpp:390
> # 5  0x00000000004a0709 in do_one_file (iname=0x7ffec7ffe94e "main", oname=0x7ffec7ffc370 "main.002") at work.cpp:173
> # 6  0x00000000004a0aae in do_files (i=2, argc=3, argv=0x7ffec7ffc8e8) at work.cpp:300
> # 7  0x00000000004292a6 in main (argc=3, argv=0x7ffec7ffc8e8) at main.cpp:1560
> 
> (gdb) f 0
> # 0  0x000000000045bf6c in PackMachBase<N_Mach::MachClass_64<N_BELE_CTP::LEPolicy> >::canUnpack (this=0x1995010) at p_mach.cpp:1969
> 
> 1969            if (lc_seg == ptr->cmd) {
> (gdb) print ptr
> $1 = (const Mach_command *) 0x42e9b59f
> (gdb) print *ptr
> Cannot access memory at address 0x42e9b59f

The main is a i386 file:

> file main
> main: Mach-O executable i386

Apparently, the problem is only with the compression, because if I compress my exe with the stable upx, the devel/travis version can decompress it and the file is identical with the original.

Recently we found out that the compressed binaries don't work on Sierra and we're aware that you're working on it. Maybe this one is related to the Sierra bug too.
## What should have happened?

upx -d should have produced the original exe, but it crashed.
## How can we reproduce the issue?

Explained above.
## Please tell us details about your environment.

- UPX version used (`upx --version`):

upx 3.92-BETA-git-ab0260a9174e+
UCL data compression library 1.03
zlib data compression library 1.2.7
LZMA SDK version 4.43

upx 3.91
UCL data compression library 1.03
- Operating System and version:
  Debian Linux 7
- CPU architecture:
  x86_64

**Comment by micsuka** [comment]
The lowest version of MacOS we need is 10.7 (Lion).

**Comment by jreiser** [comment]
https://www.dropbox.com/s/f8x4oypdjmequuf/upx.out?dl=0 (x86_64 executable) works for me, for both 32-bit and 64-bit executables back to Mac OS X 10.5.8 (Leopard).

**Comment by micsuka** [comment]
it seems to be working, tested on Sierra.
thanks :)

**Comment by micsuka** [comment]
it is working on Mac. but we're experiencing problems with windows with this version this time. Our application is behaving weird on windows (windows 8, but other versions have been reported too), it's lagging, especially when playing sounds. Maybe some section in the exe is missing/wrong.

I attached a small test program which playing a wav. You can see that the same exe compressed with the new (unstable) upx is behaving weird, while compressed with the stable upx it's ok. But after I decompress the buggy exe, it's running as expected.

[test.zip](https://github.com/upx/upx/files/515595/test.zip)

**Comment by markus-oberhumer** [comment]
Please open a new issue for the win32 problem. Thanks.

**Comment by jreiser** [comment]
fixed on devel branch
