### ISSUE TITLE
winscp.exe 5.9.5.7441 from today

### ISSUE THREAD

**Issue by humandxp** [upx/upx#90]
## What's the problem (or question)?
does not compress with message:
upx: Winscp.exe: InternalError: should not happen

## Do you have an idea for a solution?
get back to code from 3.91 that version compresses exe

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.91-3.93 and 2 day old dev builds
* Operating System and version: win 7 x64
* CPU architecture: x64

**Comment by Mattiwatti** [comment]
This is the same issue as #223. (or I suppose technically #223 is the same issue as this, since this one was first...)
