### ISSUE TITLE
Binary that dynamically links against musl segfaults when compressed

### ISSUE THREAD

**Issue by kozross** [upx/upx#93]
## What's the problem (or question)?

I've built a small program, designed to dynamically link against musl instead of glibc. It runs normally when not compressed. However, after I compress it with ``upx`` (at any level of compression) and try to run it, it segfaults. Notably, if I link against musl statically, this problem does not occur.

## What should have happened?

According to the UPX documentation (and my experience with a static link) it should have run the same way.

## Do you have an idea for a solution?

Currently, the solution is 'not using UPX to compress my binary', but hopefully not for long!

## How can we reproduce the issue?

1. ``git clone https://notabug.org/koz.ross/evolog``
2. ``cd evolog``
3. Change the ``MUSL`` variable in ``GNUmakefile`` to point to the root of your musl install, if needed.
4. ``make``
5. Observe the test running.
6. ``cd test``
7. ``upx test-block``
8. ``./test-block``
9. Observe the segmentation fault.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.93
* Operating System and version: Arch Linux
* CPU architecture: x86_64
* Clang version: 4.0
* musl version: 1.1.16

**Comment by markus-oberhumer** [comment]
FYI, UPX works fine under AlpineLinux 3.x, so this might not be musl-related.

**Comment by jreiser** [comment]
@kozross  Please run these commands, then copy+paste the output into a comment here.  This information will help debugging.  Thank you.
```
uname -a   # kernel version and build date
ldd /bin/date   # hints about "standard" PT_INTERP
strace ./test-block   # system calls invoked by compressed test-block
gdb ./test-block   # clues about state at time of SIGSEGV
(gdb) run   # until SIGSEGV
(gdb) info reg   # display all registers
(gdb) x/4i $pc   # current and next instructions
(gdb) x/12i $pc-0x20   # likely previous instructions (heuristic)
(gdb) x/16xw $sp   # contents at active end of stack
(gdb) info proc
(gdb) shell cat /proc/PID/maps   # layout of address space (PID is processID from "info proc")
```

**Comment by kozross** [comment]
@jreiser I assume you mean the *compressed* ``./test/test-block`` in this case?

**Comment by jreiser** [comment]
@kozross Yes, the compressed test-block program.

When I build evolog and try running uncompressed test-block, then I get SIGILL because the program tries to execute a "rdrand %eax" instruction which does not exist on that machine.  Is there a substitute?

**Comment by kozross** [comment]
@jreiser Please find below the information you requested. I had to use lldb (because that's what Clang binaries get debugged in), so some of the commands will be different. I put them in brackets afterwards to make it clear what's what where I thought appropriate.

```
uname -a -> Linux Sebastian 4.10.11-1-ARCH #1 SMP PREEMPT Tue Apr 18 08:39:42 CEST 2017 x86_64 GNU/Linux

ldd /bin/date ->
    linux-vdso.so.1 (0x00007ffea96fd000)
    libc.so.6 => /usr/lib/libc.so.6 (0x00007f892930c000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f89296b0000)

strace ./test/test-block ->

execve("./test/test-block", ["./test/test-block"], [/* 44 vars */]) = 0
mmap(0x120000, 65536, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, 0, 0) = 0x120000
readlink("/proc/self/exe", "/home/koz/documents/programming/"..., 4096) = 56
mmap(0x400000, 12288, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x400000
mmap(0x400000, 5972, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x400000
mprotect(0x400000, 5972, PROT_READ|PROT_EXEC) = 0
mmap(0x402000, 2368, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0x1000) = 0x402000
mprotect(0x402000, 2368, PROT_READ|PROT_WRITE) = 0
open("/usr/lib/ld-musl-x86_64.so.1", O_RDONLY) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\34\242\5\0\0\0\0\0"..., 1024) = 1024
mmap(NULL, 2682880, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd9e6d8e000
mmap(0x7fd9e6d8e000, 567456, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x7fd9e6d8e000
mmap(0x7fd9e7018000, 5300, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x8a000) = 0x7fd9e7018000
mmap(0x7fd9e701a000, 8560, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fd9e701a000
close(3)                                = 0
munmap(0x101000, 133440)                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7fd9e6c2c370} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

(lldb) register read (info reg) ->
       rax = 0x00007ffff7c0a368
       rbx = 0x0000000000100fec
       rcx = 0x00007fffffffd7b0
       rdx = 0x0000000000000038
       rdi = 0x00007ffff7bf4678
       rsi = 0x00007ffff7c0abd8
       rbp = 0x0000000000000000
       rsp = 0x00007fffffffd618
        r8 = 0x00000000ffffffff
        r9 = 0x0000000000000000
       r10 = 0x0000000000000032
       r11 = 0x0000000000000202
       r12 = 0x0000000000000000
       r13 = 0x0000000000000000
       r14 = 0x0000000000000000
       r15 = 0x00007fffffffda60
       rip = 0x00007ffff7dc6345
    rflags = 0x0000000000010287
        cs = 0x0000000000000033
        fs = 0x0000000000000000
        gs = 0x0000000000000000
        ss = 0x000000000000002b
        ds = 0x0000000000000000
        es = 0x0000000000000000

(lldb) memory read/4i $pc  
->  0x7ffff7dc6345: 48 8b 50 08        movq   0x8(%rax), %rdx
    0x7ffff7dc6349: 81 e2 ff ff ff 7f  andl   $0x7fffffff, %edx         ; imm = 0x7FFFFFFF 
    0x7ffff7dc634f: 48 83 fa 08        cmpq   $0x8, %rdx
    0x7ffff7dc6353: 75 0e              jne    0x7ffff7dc6363
(lldb) memory read/12i $pc-0x20
    0x7ffff7dc6325: 83 c0 10                 addl   $0x10, %eax
    0x7ffff7dc6328: eb dc                    jmp    0x7ffff7dc6306
    0x7ffff7dc632a: 48 89 f8                 movq   %rdi, %rax
    0x7ffff7dc632d: 48 03 84 24 c0 00 00 00  addq   0xc0(%rsp), %rax
    0x7ffff7dc6335: 48 89 c6                 movq   %rax, %rsi
    0x7ffff7dc6338: 48 03 b4 24 c8 00 00 00  addq   0xc8(%rsp), %rsi
    0x7ffff7dc6340: 48 39 f0                 cmpq   %rsi, %rax
    0x7ffff7dc6343: 74 24                    je     0x7ffff7dc6369
->  0x7ffff7dc6345: 48 8b 50 08              movq   0x8(%rax), %rdx
    0x7ffff7dc6349: 81 e2 ff ff ff 7f        andl   $0x7fffffff, %edx         ; imm = 0x7FFFFFFF 
    0x7ffff7dc634f: 48 83 fa 08              cmpq   $0x8, %rdx
    0x7ffff7dc6353: 75 0e                    jne    0x7ffff7dc6363
(lldb) memory read/16xw $sp
0x7fffffffd618: 0x00007fffffffea89 0x00000000bfebfbff
0x7fffffffd628: 0x0000000000000064 0x0000000000000000
0x7fffffffd638: 0x0000000000000000 0x0000000000000000
0x7fffffffd648: 0x0000000000000000 0x0000000000000000
0x7fffffffd658: 0x0000000000000000 0x0000000000000000
0x7fffffffd668: 0x00007fffffffea79 0x0000000000000000
0x7fffffffd678: 0x0000000000000000 0x0000000000000000
0x7fffffffd688: 0x0000000000000000 0x0000000000000000

(lldb) platform shell cat /proc/1426/maps
00100000-00101000 r-xp 00000000 08:11 40502263                           /home/koz/documents/programming/c/evolog/test/test-block
00122000-00130000 rwxp 00000000 00:00 0 
00400000-00402000 r-xp 00000000 00:00 0 
00402000-00403000 rwxp 00000000 00:00 0                                  [heap]
7ffff7d6c000-7ffff7df7000 r-xp 00000000 08:03 2252666                    /usr/lib/musl/lib/libc.so
7ffff7df7000-7ffff7ff6000 ---p 00000000 00:00 0 
7ffff7ff6000-7ffff7ff8000 rwxp 0008a000 08:03 2252666                    /usr/lib/musl/lib/libc.so
7ffff7ff8000-7ffff7ffb000 rwxp 00000000 00:00 0 
7ffff7ffb000-7ffff7ffd000 r--p 00000000 00:00 0                          [vvar]
7ffff7ffd000-7ffff7fff000 r-xp 00000000 00:00 0                          [vdso]
7ffffffde000-7ffffffff000 rwxp 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
```

The ``rdrand`` instruction is an [Intel-only compiler intrinsic][1]. The AMD equivalent came out in 2015 according to the link.

[1]: https://en.wikipedia.org/wiki/RDRAND

**Comment by jreiser** [comment]
@kozross  Thank you for the debug info.  Commit cd11bb1 on 'devel' branch now works for me.
 
[Note: Something like 40% of all in-use x86_64 chips do not support RDRAND.]

**Comment by kozross** [comment]
@jreiser Thank you - I appreciate the fast fix! This code is written exclusively for personal use, and I happen to have an x86_64 which supports this instruction. Obviously if someone wants to use it and doesn't have it, I'd consider modifying it something less specific.

**Comment by rofl0r** [comment]
@jreiser: as a long-time musl user i'd be interested to hear what the actual problem with musl libc was, would you mind explaining briefly what your commit did? thanks!

**Comment by jreiser** [comment]
libmusl used Elf64_auxv{AT_BASE}.a_un.a_val to compute its own base address: the "slide" value, the difference between the actual address of the PT_LOAD in the current process and the address assumed by the most recent static binding.  /bin/ld assumes 0 for the base address, but  /usr/bin/prelink might change it.  glibc does not use AT_BASE (it is simple enough to determine by dead reckoning), and because an executable that has been compressed by upx has no PT_LOAD, then the linux kernel supplies 0 for AT_BASE.  One problem on some ancient linux kernels for i686 was not supplying AT_BASE and several other AT_* values at all, which forced upx to slide down argc, argv, and the environment string pointers in order to make space for them.  But for several years the kernel has done the right thing: supply default values for all the reasonable AT_* slots.
