### ISSUE TITLE
Multi-core compression enhancement

### ISSUE THREAD

**Issue by msbroadf** [upx/upx#94]
Thanks for UPX. I have a 20core 64GB machine where i would like to use brute or ultra-brute more often. UPX appears to be single threaded when finding the optimal compression. I took a quick look in Packer::compressWithFilters to see how its done. Would i be right in saying this is the only function that needs to be parallelized?

**Comment by markus-oberhumer** [comment]
Yes, Packer::compressWithFilters() is the one function to parallelize.

But then there are subtle interactions with buildLoader() and the UI interface, so this will need some major refactoring first (like extracting **all** thread-local state into its own class).

**Comment by msbroadf** [comment]
OK thats a bit much for me to take on at the moment. i was hoping it was just that function and i could have a go at changing it...

**Comment by markus-oberhumer** [comment]
Closing this issue as "wontfix" for now.

**Comment by svnpenn2** [comment]
https://github.com/upx/upx/issues/155

**Comment by svnpenn** [comment]
Here is workaround:

~~~
find | grep -i -e exe -e dll | xargs -L1 -P5 upx --brute
~~~

**Comment by msbroadf** [comment]
@svnpenn no thats not relevant, essentially the --ultra-brute command needs to be multi-threaded...
