### ISSUE TITLE
XUL.DLL is corrupted after compression with UPX 3.93 but it works with UPX 3.91

### ISSUE THREAD

**Issue by xrayer** [upx/upx#95]
## What's the problem (or question)?

K-Meleon browser 75.1 failed to start after compression of XUL.DLL with UPX 3.93 but it works when compressed with UPX 3.91 and older. The error message is: "K-Meleon failed to initialize. Please reinstall. It fails at any copression level or exra options.

## What should have happened?

It should start normally.

## Do you have an idea for a solution?

Seems to be another issue of reworking UPX between ver 3.91 and 3.92-3

## How can we reproduce the issue?

1. Download K-Meleon 75.1 portable https://sourceforge.net/projects/kmeleon/files/k-meleon/75.1/K-Meleon75.1.7z/download
2. compress XUL.DLL with UPX 3.93 (doen't matter what extra options are used)
3. run K-Meleon.exe

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.93
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Copyright (C) 1996-2017 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2017 Laszlo Molnar
Copyright (C) 2000-2017 John F. Reiser
Copyright (C) 2002-2017 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
* Operating System and version: Windows XP-SP3
* CPU architecture: initel core i-7 2600K, 4GB RAM

**Comment by xrayer** [comment]
I retested with version 3.94 and problem with XUL.DLL still remains.

**Comment by xrayer** [comment]
I retested with version 3.95 and problem with XUL.DLL still remains.

**Comment by azev** [comment]
same here. xul.dll + upx = crash

**Comment by xrayer** [comment]
Even worse, I found more problem files when compressing RetroZilla 2.2 and FastStone Image Viewer 6.7. While compressed files worked under WinXP it caused a BSOD under Win98. I unpacked the files and recompressed with UPX 3.91 and it works fine. So I woulnd't reccomend use newer UPX for compression win32 binaries targetted for older Windows.
