### ISSUE TITLE
Unable to compress any exe file since version 3.92w

### ISSUE THREAD

**Issue by markusdonath** [upx/upx#97]
## What's the problem (or question)?

All of the exe files created by Embarcadero C++ Builder (I am using version 10.2 Tokyo) cannot be compressed by UPX starting with version 3.92w. The error message is:
upx: UPXTest.exe: InternalError: should not happen

## What should have happened?

The files should be compressed or at least there should be a better error message.

## Do you have an idea for a solution?

No.

## How can we reproduce the issue?

1. You can test it yourself with a test exe: https://www.dropbox.com/s/korsfjxhocdfk00/UPXTest.exe?dl=0
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
upx 3.94
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Copyright (C) 1996-2017 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2017 Laszlo Molnar
Copyright (C) 2000-2017 John F. Reiser
Copyright (C) 2002-2017 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.

* Host Operating System and version:
Windows 10 Enterprise 64 bit
* Host CPU architecture:
Intel Xeon X5690
* Target Operating System and version:
Windows 10 Enterprise 64 bit
* Target CPU architecture:
Intel Xeon X5690

**Comment by owai1980** [comment]
it's true, i have the same problem with embarcadero XE 1
i can help with some tests if necessary...
Johan

**Comment by markusdonath** [comment]
I would like to know, is there any investigation of my problem?

**Comment by John-Yu** [comment]
There is a same issue, [issues69](https://github.com/upx/upx/issues/69)

**Comment by John-Yu** [comment]
The exe files created by Embarcadero C++ Builder  have empty entries in Import Lookup Table, 3.94UPX does not deal it.

**Comment by owai1980** [comment]
great!
it seems you found the solution to this annoying bug :-)
did not try yet, but thanks!!

**Comment by justjenny** [comment]
I get this error - InternalError should not happen - why ?

**Comment by justjenny** [comment]
Hi again, regarding 'InternalError should not happen'  - Have done a bit more testing and It only seems to happen when my exe contains Calls to the prompt.  I'm using Window 10 - Everything else seems ok.
